INSERT OR IGNORE INTO machines_info (slug, lang, title, "desc") VALUES
('barbell', 'es', 'Barra', 'Barra larga de acero utilizada para levantamientos pesados como sentadillas, press banca y peso muerto.'),
('barbell', 'en', 'Barbell', 'Long steel bar used for heavy lifts such as squats, bench press, and deadlifts.'),
('barbell', 'pt', 'Barra', 'Barra longa de aço utilizada para levantamentos pesados como agachamentos, supino e levantamento terra.'),
('barbell', 'fr', 'Barre', 'Longue barre en acier utilisée pour les levées lourdes comme les squats, le développé couché et le soulevé de terre.'),
('barbell', 'de', 'Langhantel', 'Lange Stahlstange, die für schwere Übungen wie Kniebeugen, Bankdrücken und Kreuzheben verwendet wird.'),
('barbell', 'it', 'Bilanciere', 'Lunga sbarra d acciaio utilizzata per sollevamenti pesanti come squat, panca piana e stacchi da terra.'),
('barbell', 'zh', '杠铃', '用于深蹲、卧推和硬拉等大重量训练的长钢杆。'),
('barbell', 'ja', 'バーベル', 'スクワット、ベンチプレス、デッドリフトなどの高重量トレーニングに使用される長いスチール製の棒。'),
('barbell', 'ko', '바벨', '스쿼트, 벤치 프레스, 데드리프트와 같은 고중량 운동에 사용되는 긴 강철 막대입니다.'),
('barbell', 'ar', 'بار (Barbell)', 'قضيب فولاذي طويل يستخدم للتمارين الثقيلة مثل القرفصاء، وضغط الصدر، والرفعة الميتة.'),
('barbell', 'hi', 'बारबेल', 'लंबी स्टील की रॉड जिसका उपयोग स्क्वैट्स, बेंच प्रेस और डेडलिफ्ट जैसे भारी वजन उठाने के लिए किया जाता है।'),
('barbell', 'ru', 'Штанга', 'Длинный стальной гриф, используемый для тяжелых упражнений, таких как приседания, жим лежа и становая тяга.'),
('barbell', 'nl', 'Halterstang', 'Lange stalen stang die wordt gebruikt voor zware lifts zoals squats, bench press en deadlifts.'),
('barbell', 'sv', 'Skivstång', 'Lång stålskena som används för tunga lyft som knäböj, bänkpress och marklyft.'),
('barbell', 'pl', 'Sztanga', 'Długi stalowy drążek używany do ciężkich ćwiczeń, takich jak przysiady, wyciskanie na ławce i martwy ciąg.'),
('barbell', 'id', 'Barbel', 'Batang baja panjang yang digunakan untuk angkatan berat seperti squat, bench press, dan deadlift.'),
('barbell', 'bn', 'বারবেল', 'লম্বা স্টিলের রড যা স্কোয়াট, বেঞ্চ প্রেস এবং ডেডলিফটের মতো ভারী ওজন তোলার জন্য ব্যবহৃত হয়।'),
('barbell', 'vi', 'Thanh đòn', 'Thanh thép dài dùng cho các bài tập nặng như squat, đẩy ngực và deadlift.'),
('barbell', 'fa', 'هالتر', 'میله فولادی بلند که برای حرکات سنگین مانند اسکات، پرس سینه و ددلیفت استفاده می‌شود.');