INSERT OR IGNORE INTO machines_info (slug, lang, title, "desc") VALUES
('battle_ropes', 'es', 'Cuerdas de batalla', 'Cuerdas pesadas y largas utilizadas para ejercicios de potencia, resistencia cardiovascular y fuerza de agarre.'),
('battle_ropes', 'en', 'Battle ropes', 'Heavy, long ropes used for power, cardiovascular endurance, and grip strength exercises.'),
('battle_ropes', 'pt', 'Cordas de batalha', 'Cordas pesadas e longas utilizadas para exercícios de potência, resistência cardiovascular e força de pegada.'),
('battle_ropes', 'fr', 'Cordes ondulatoires (Battle ropes)', 'Cordes lourdes et longues utilisées pour les exercices de puissance, d endurance cardiovasculaire et de force de préhension.'),
('battle_ropes', 'de', 'Battle Ropes', 'Schwere, lange Seile, die für Kraft-, Herz-Kreislauf-Ausdauer- und Griffkraftübungen verwendet werden.'),
('battle_ropes', 'it', 'Battle ropes', 'Corde pesanti e lunghe utilizzate per esercizi di potenza, resistenza cardiovascolare e forza della presa.'),
('battle_ropes', 'zh', '战绳', '用于爆发力、心肺耐力和握力训练的厚重长绳。'),
('battle_ropes', 'ja', 'バトルロープ', '瞬発力、心肺持久力、握力トレーニングに使用される重くて長いロープ。'),
('battle_ropes', 'ko', '배틀 로프', '폭발적인 힘, 심폐 지구력 및 악력 훈련에 사용되는 무겁고 긴 로프입니다.'),
('battle_ropes', 'ar', 'حبال المعركة (Battle ropes)', 'حبال ثقيلة وطويلة تستخدم لتمارين القوة، والتحمل القلبي الوعائي، وقوة القبضة.'),
('battle_ropes', 'hi', 'बैटल रोप्स', 'भारी, लंबी रस्सियों का उपयोग शक्ति, हृदय सहनशक्ति और पकड़ की ताकत के व्यायाम के लिए किया जाता है।'),
('battle_ropes', 'ru', 'Боевые канаты', 'Тяжелые длинные канаты, используемые для тренировки взрывной силы, сердечно-сосудистой выносливости и силы хвата.'),
('battle_ropes', 'nl', 'Battle ropes', 'Zware, lange touwen gebruikt voor kracht-, cardiovasculaire uithoudingsvermogen- en gripkrachtoefeningen.'),
('battle_ropes', 'sv', 'Battle ropes', 'Tunga, långa rep som används för kraft-, kardiovaskulär uthållighets- och greppstyrketräning.'),
('battle_ropes', 'pl', 'Liny treningowe (Battle ropes)', 'Ciężkie, długie liny używane do ćwiczeń mocy, wytrzymałości układu krążenia i siły chwytu.'),
('battle_ropes', 'id', 'Battle ropes', 'Tali berat dan panjang yang digunakan untuk latihan daya, ketahanan kardiovaskular, dan kekuatan cengkeraman.'),
('battle_ropes', 'bn', 'ব্যাটল রোপস', 'ভারী, লম্বা দড়ি যা শক্তি, কার্ডিওভাসকুলার সহনশীলতা এবং গ্রিপ শক্তির ব্যায়ামের জন্য ব্যবহৃত হয়।'),
('battle_ropes', 'vi', 'Dây thừng tập gym', 'Dây thừng nặng và dài dùng cho các bài tập sức mạnh, sức bền tim mạch và lực cầm nắm.'),
('battle_ropes', 'fa', 'طناب بتل روپ', 'طناب‌های سنگین و بلند که برای تمرینات قدرتی، استقامت قلبی-عروقی و تقویت قدرت پنجه استفاده می‌شود.');