INSERT INTO machines_info (slug, lang, title, "desc") VALUES
('cable_machine', 'es', 'Máquina de cables', 'Sistema de poleas y cables que permite una tensión constante en diversos ángulos.'),
('cable_machine', 'en', 'Cable machine', 'Pulley and cable system that allows for constant tension at various angles.'),
('cable_machine', 'pt', 'Máquina de cabos', 'Sistema de polias e cabos que permite uma tensão constante em diversos ângulos.'),
('cable_machine', 'fr', 'Machine à poulies', 'Système de poulies et de câbles permettant une tension constante sous différents angles.'),
('cable_machine', 'de', 'Kabelzugturm', 'Seilzugsystem, das eine konstante Spannung in verschiedenen Winkeln ermöglicht.'),
('cable_machine', 'it', 'Macchina ai cavi', 'Sistema di pulegge e cavi che consente una tensione costante in diverse angolazioni.'),
('cable_machine', 'zh', '绳索训练机', '滑轮和绳索系统，允许在不同角度保持恒定张力。'),
('cable_machine', 'ja', 'ケーブルマシン', '様々な角度で一定の負荷をかけることができる滑車とケーブルのシステム。'),
('cable_machine', 'ko', '케이블 머신', '다양한 각도에서 일정한 장력을 유지할 수 있게 해주는 풀리와 케이블 시스템입니다.'),
('cable_machine', 'ar', 'جهاز الكيبل (Cable machine)', 'نظام بكرات وكابلات يسمح بتوفير شد مستمر من زوايا مختلفة.'),
('cable_machine', 'hi', 'केबल मशीन', 'पुली और केबल सिस्टम जो विभिन्न कोणों पर निरंतर तनाव बनाए रखने की अनुमति देता है।'),
('cable_machine', 'ru', 'Тренажер с тросами (Кроссовер)', 'Система блоков и тросов, обеспечивающая постоянное напряжение под разными углами.'),
('cable_machine', 'nl', 'Kabelmachine', 'Katrol- en kabelsysteem dat constante spanning vanuit verschillende hoeken mogelijk maakt.'),
('cable_machine', 'sv', 'Kabelmaskin', 'Triss- och kabelsystem som möjliggör konstant spänning i olika vinklar.'),
('cable_machine', 'pl', 'Wyciąg (Cable machine)', 'System bloczków i linek umożliwiający stałe napięcie pod różnymi kątami.'),
('cable_machine', 'id', 'Mesin kabel', 'Sistem katrol dan kabel yang memungkinkan tegangan konstan di berbagai sudut.'),
('cable_machine', 'bn', 'কেবল মেশিন', 'পুলি এবং কেবল সিস্টেম যা বিভিন্ন কোণ থেকে ক্রমাগত টেনশন বজায় রাখার অনুমতি দেয়।'),
('cable_machine', 'vi', 'Máy kéo cáp', 'Hệ thống ròng rọc và dây cáp cho phép lực căng không đổi ở nhiều góc độ khác nhau.'),
('cable_machine', 'fa', 'دستگاه سیم‌کش', 'سیستم قرقره و کابل که امکان ایجاد تنش ثابت در زوایای مختلف را فراهم می‌کند.');