INSERT OR IGNORE INTO machines_info (slug, lang, title, "desc") VALUES
('cable_crossover', 'es', 'Cruce de poleas', 'Estación de poleas duales ajustable para trabajar el pecho y los hombros desde múltiples ángulos con tensión constante.'),
('cable_crossover', 'en', 'Cable crossover', 'Adjustable dual pulley station to work the chest and shoulders from multiple angles with constant tension.'),
('cable_crossover', 'pt', 'Crossover', 'Estação de polias duplas ajustável para trabalhar o peito e os ombros a partir de múltiplos ângulos com tensão constante.'),
('cable_crossover', 'fr', 'Crossover (Vis-à-vis)', 'Station à double poulie réglable pour travailler les pectoraux et les épaules sous plusieurs angles avec une tension constante.'),
('cable_crossover', 'de', 'Kabelzug-Station', 'Verstellbare Doppel-Seilzugstation, um Brust und Schultern aus mehreren Winkeln mit konstanter Spannung zu trainieren.'),
('cable_crossover', 'it', 'Crossover ai cavi', 'Stazione a doppia puleggia regolabile per allenare petto e spalle da molteplici angolazioni con tensione costante.'),
('cable_crossover', 'zh', '绳索交叉训练机', '可调节的双滑轮站，通过恒定张力从多个角度训练胸部和肩部。'),
('cable_crossover', 'ja', 'ケーブルクロスオーバー', '調整可能なデュアルプーリーステーションで、一定の負荷をかけながら多角的に胸部と肩を鍛えることができます。'),
('cable_crossover', 'ko', '케이블 크로스오버', '일정한 장력을 유지하면서 여러 각도에서 가슴과 어깨를 단련할 수 있는 조절 가능한 듀얼 풀리 스테이션입니다.'),
('cable_crossover', 'ar', 'جهاز الكيبل المتداخل (Cable crossover)', 'محطة بكرات مزدوجة قابلة للتعديل لتدريب الصدر والأكتاف من زوايا متعددة مع توفير شد مستمر.'),
('cable_crossover', 'hi', 'केबल क्रॉसओवर', 'सीने और कंधों को निरंतर तनाव के साथ कई कोणों से प्रशिक्षित करने के लिए समायोज्य दोहरी पुली स्टेशन।'),
('cable_crossover', 'ru', 'Кроссовер', 'Регулируемая станция с двумя блоками для проработки грудных мышц и плеч под разными углами с постоянным напряжением.'),
('cable_crossover', 'nl', 'Cable crossover', 'Instelbaar dubbel katrolstation om de borst en schouders vanuit meerdere hoeken met constante spanning te trainen.'),
('cable_crossover', 'sv', 'Cable crossover', 'Justerbar dubbel trissstation för att träna bröst och axlar från flera vinklar med konstant spänning.'),
('cable_crossover', 'pl', 'Brama do wyciągu (Cable crossover)', 'Regulowana stacja z dwoma wyciągami do treningu klatki piersiowej i barków pod wieloma kątami przy stałym napięciu.'),
('cable_crossover', 'id', 'Cable crossover', 'Stasiun katrol ganda yang dapat disesuaikan untuk melatih dada dan bahu dari berbagai sudut dengan tegangan konstan.'),
('cable_crossover', 'bn', 'কেবল ক্রসওভার', 'ক্রমাগত টেনশনের সাথে একাধিক কোণ থেকে বুক এবং কাঁধকে প্রশিক্ষিত করার জন্য অ্যাডজাস্টেবল ডুয়াল পুলি স্টেশন।'),
('cable_crossover', 'vi', 'Máy kéo cáp đôi (Cable crossover)', 'Trạm ròng rọc đôi có thể điều chỉnh để tập ngực và vai từ nhiều góc độ với lực căng không đổi.'),
('cable_crossover', 'fa', 'دستگاه سیم‌کش کراس‌اور', 'ایستگاه قرقره دوبل قابل تنظیم برای تمرین دادن سینه و شانه‌ها از زوایای متعدد با تنش ثابت.');