INSERT INTO machines_info (slug, lang, title, "desc") VALUES
('chest_press_machine', 'es', 'Máquina de press de pecho', 'Máquina diseñada para realizar el movimiento de empuje de pecho con trayectoria guiada y resistencia ajustable.'),
('chest_press_machine', 'en', 'Chest press machine', 'Machine designed to perform chest pushing movements with a guided path and adjustable resistance.'),
('chest_press_machine', 'pt', 'Máquina de supino', 'Máquina projetada para realizar o movimento de empurrar o peito com trajetória guiada e resistência ajustável.'),
('chest_press_machine', 'fr', 'Machine à développé pectoraux', 'Machine conçue pour effectuer le mouvement de poussée des pectoraux avec une trajectoire guidée et une résistance réglable.'),
('chest_press_machine', 'de', 'Brustpresse', 'Gerät für Brustdruckbewegungen mit geführter Bahn und einstellbarem Widerstand.'),
('chest_press_machine', 'it', 'Macchina per pectoral press', 'Macchina progettata per eseguire il movimento di spinta per il petto con traiettoria guidata e resistenza regolabile.'),
('chest_press_machine', 'zh', '胸部推举机', '设计用于在引导轨迹和可调阻力下进行胸部推举动作的机器。'),
('chest_press_machine', 'ja', 'チェストプレス・マシン', 'ガイド付きの軌道と調整可能な負荷で、胸のプッシュ動作を行うためのマシン。'),
('chest_press_machine', 'ko', '체스트 프레스 머신', '가이드가 있는 궤적과 조절 가능한 저항을 통해 가슴 밀기 동작을 수행하도록 설계된 머신입니다.'),
('chest_press_machine', 'ar', 'جهاز ضغط الصدر (Chest press)', 'جهاز مصمم لأداء حركة دفع الصدر بمسار موجه ومقاومة قابلة للتعديل.'),
('chest_press_machine', 'hi', 'चेस्ट प्रेस मशीन', 'गाइडेड पाथ और समायोज्य प्रतिरोध के साथ चेस्ट पुशिंग मूवमेंट करने के लिए डिज़ाइन की गई मशीन।'),
('chest_press_machine', 'ru', 'Тренажер для жима груди', 'Тренажер для выполнения жимовых движений на грудь с фиксированной траекторией и регулируемым весом.'),
('chest_press_machine', 'nl', 'Chest press machine', 'Machine ontworpen voor borstduwbewegingen met een geleide baan en instelbare weerstand.'),
('chest_press_machine', 'sv', 'Bröstpressmaskin', 'Maskin designad för att utföra bröstpressrörelser med guidad bana och justerbart motstånd.'),
('chest_press_machine', 'pl', 'Maszyna do wyciskania na klatkę', 'Maszyna zaprojektowana do wykonywania wyciskania na klatkę piersiową z prowadnicą i regulowanym oporem.'),
('chest_press_machine', 'id', 'Mesin chest press', 'Mesin yang dirancang untuk melakukan gerakan mendorong dada dengan jalur yang dipandu dan resistensi yang dapat disesuaikan.'),
('chest_press_machine', 'bn', 'চেস্ট প্রেস মেশিন', 'গাইডেড পাথ এবং অ্যাডজাস্টেবল রেজিস্ট্যান্সের সাথে চেস্ট পুশিং মুভমেন্ট করার জন্য ডিজাইন করা মেশিন।'),
('chest_press_machine', 'vi', 'Máy đẩy ngực', 'Máy được thiết kế để thực hiện chuyển động đẩy ngực với quỹ đạo có hướng dẫn và lực cản có thể điều chỉnh.'),
('chest_press_machine', 'fa', 'دستگاه پرس سینه', 'دستگاه طراحی شده برای انجام حرکات پرسی سینه با مسیر هدایت‌شده و مقاومت قابل تنظیم.');