INSERT INTO machines_info (slug, lang, title, "desc") VALUES
('decline_bench', 'es', 'Banco declinado', 'Banco inclinado hacia abajo para ejercicios de press de pecho inferior y trabajo de abdomen.'),
('decline_bench', 'en', 'Decline bench', 'Bench angled downwards for lower chest press exercises and abdominal work.'),
('decline_bench', 'pt', 'Banco declinado', 'Banco inclinado para baixo para exercícios de supino inferior e trabalho abdominal.'),
('decline_bench', 'fr', 'Banc décliné', 'Banc incliné vers le bas pour les exercices de développé couché décliné et le travail des abdominaux.'),
('decline_bench', 'de', 'Negativbank', 'Nach unten geneigte Bank für Negativ-Bankdrücken und Bauchtraining.'),
('decline_bench', 'it', 'Panca declinata', 'Panca inclinata verso il basso per esercizi di panca declinata e lavoro addominale.'),
('decline_bench', 'zh', '下斜哑铃凳', '向下倾斜的凳子，用于下胸部推举练习和腹部训练。'),
('decline_bench', 'ja', 'デクライン・ベンチ', '下向きに傾斜したベンチで、下部胸筋のプレス運動や腹筋運動に使用します。'),
('decline_bench', 'ko', '디클라인 벤치', '아래로 기울어진 벤치로, 하부 가슴 운동 및 복근 운동에 사용됩니다.'),
('decline_bench', 'ar', 'مقعد مائل للأسفل (Decline bench)', 'مقعد مائل للأسفل لتمارين ضغط الصدر السفلي وتمارين البطن.'),
('decline_bench', 'hi', 'डिक्लाइन बेंच', 'निचले चेस्ट प्रेस व्यायाम और पेट के वर्कआउट के लिए नीचे की ओर झुकी हुई बेंच।'),
('decline_bench', 'ru', 'Скамья с отрицательным наклоном', 'Скамья, наклоненная вниз, для жима на нижнюю часть грудных мышц и тренировки пресса.'),
('decline_bench', 'nl', 'Decline bankje', 'Naar beneden gerichte bank voor lower chest press-oefeningen en buikspiertraining.'),
('decline_bench', 'sv', 'Negativ bänk', 'Bänk vinklad nedåt för negativ bröstpress och magträning.'),
('decline_bench', 'pl', 'Ławka ujemna', 'Ławka nachylona w dół do wyciskania na dolną część klatki piersiowej i treningu mięśni brzucha.'),
('decline_bench', 'id', 'Bangku decline', 'Bangku yang miring ke bawah untuk latihan tekan dada bagian bawah dan latihan perut.'),
('decline_bench', 'bn', 'ডিক্লাইন বেঞ্চ', 'লোয়ার চেস্ট প্রেস ব্যায়াম এবং পেটের ওয়ার্কআউটের জন্য নিচের দিকে হেলানো বেঞ্চ।'),
('decline_bench', 'vi', 'Ghế tập dốc xuống', 'Ghế nghiêng xuống dưới cho các bài tập đẩy ngực dưới và tập cơ bụng.'),
('decline_bench', 'fa', 'نیمکت شیب منفی (Decline)', 'نیمکت با شیب رو به پایین برای حرکات پرس سینه بخش پایینی و تمرینات شکم.');