INSERT INTO machines_info (slug, lang, title, "desc") VALUES
('dip_station', 'es', 'Estación de fondos', 'Estructura con barras paralelas para realizar fondos (dips) enfocados en tríceps y pecho.'),
('dip_station', 'en', 'Dip station', 'Structure with parallel bars to perform dips focused on triceps and chest.'),
('dip_station', 'pt', 'Estação de paralelas', 'Estrutura com barras paralelas para realizar mergulhos (dips) focados em tríceps e peito.'),
('dip_station', 'fr', 'Station à dips', 'Structure avec barres parallèles pour effectuer des dips, ciblant les triceps et les pectoraux.'),
('dip_station', 'de', 'Dip-Station', 'Struktur mit parallelen Stangen für Dips, die auf Trizeps und Brust abzielen.'),
('dip_station', 'it', 'Stazione per dip', 'Struttura con barre parallele per eseguire dip, focalizzati su tricipiti e petto.'),
('dip_station', 'zh', '双杠训练架', '带有平行杠的结构，用于执行针对三头肌和胸部的双杠臂屈伸（dips）。'),
('dip_station', 'ja', 'ディップス・ステーション', '平行棒を備えた構造で、上腕三頭筋と胸筋を鍛えるディップスを行うためのものです。'),
('dip_station', 'ko', '딥스 스테이션', '삼두근과 가슴을 집중적으로 단련하는 딥스(dips)를 수행하기 위한 평행봉 구조물입니다.'),
('dip_station', 'ar', 'جهاز المتوازي (Dip station)', 'هيكل بأشرطة متوازية لأداء تمارين الغطس (Dips) التي تستهدف الترايسيبس والصدر.'),
('dip_station', 'hi', 'डिप स्टेशन', 'ट्राइसेप्स और चेस्ट पर केंद्रित डिप्स करने के लिए समानांतर बार के साथ संरचना।'),
('dip_station', 'ru', 'Тренажер для отжиманий на брусьях', 'Конструкция с параллельными брусьями для выполнения отжиманий, направленных на проработку трицепсов и грудных мышц.'),
('dip_station', 'nl', 'Dip station', 'Structuur met parallelle stangen voor het uitvoeren van dips, gericht op triceps en borst.'),
('dip_station', 'sv', 'Dipsstation', 'Struktur med parallellstänger för att utföra dips fokuserade på triceps och bröst.'),
('dip_station', 'pl', 'Stacja do dipów', 'Konstrukcja z poręczami równoległymi do wykonywania dipów, angażujących triceps i klatkę piersiową.'),
('dip_station', 'id', 'Stasiun dip', 'Struktur dengan palang sejajar untuk melakukan dip yang berfokus pada trisep dan dada.'),
('dip_station', 'bn', 'ডিপ স্টেশন', 'ট্রাইসেপস এবং বুকের উপর ফোকাস করা ডিপস করার জন্য প্যারালাল বার সহ কাঠামো।'),
('dip_station', 'vi', 'Máy tập xà kép (Dip station)', 'Cấu trúc với thanh song song để thực hiện bài tập dips tập trung vào cơ tay sau và cơ ngực.'),
('dip_station', 'fa', 'ایستگاه پارالل', 'سازه‌ای با میله‌های موازی برای انجام حرکت پارالل (دیپ) که بر روی عضلات سه‌سر و سینه تمرکز دارد.');