INSERT OR IGNORE INTO machines_info (slug, lang, title, "desc") VALUES
('dumbbells', 'es', 'Mancuernas', 'Pesas de mano ajustables o fijas, versátiles para ejercicios de aislamiento y compuestos.'),
('dumbbells', 'en', 'Dumbbells', 'Adjustable or fixed hand weights, versatile for isolation and compound exercises.'),
('dumbbells', 'pt', 'Halteres', 'Pesos de mão ajustáveis ou fixos, versáteis para exercícios de isolamento e compostos.'),
('dumbbells', 'fr', 'Haltères', 'Poids à main réglables ou fixes, polyvalents pour les exercices d isolation et polyarticulaires.'),
('dumbbells', 'de', 'Kurzhanteln', 'Verstellbare oder feste Handgewichte, vielseitig einsetzbar für Isolations- und Verbundübungen.'),
('dumbbells', 'it', 'Manubri', 'Pesi a mano regolabili o fissi, versatili per esercizi di isolamento e composti.'),
('dumbbells', 'zh', '哑铃', '可调节或固定的手持重量，适用于孤立和复合动作。'),
('dumbbells', 'ja', 'ダンベル', '調整式または固定式のハンドウェイトで、アイソレーション種目からコンパウンド種目まで幅広く使用可能。'),
('dumbbells', 'ko', '덤벨', '조절 가능하거나 고정된 무게의 운동 기구로, 고립 및 복합 운동에 다용도로 사용됩니다.'),
('dumbbells', 'ar', 'دمبل (Dumbbells)', 'أوزان يدوية قابلة للتعديل أو ثابتة، متعددة الاستخدامات لتمارين العزل والتمارين المركبة.'),
('dumbbells', 'hi', 'डंबल्स', 'समायोज्य या निश्चित हाथ के वजन, अलगाव और यौगिक अभ्यासों के लिए बहुमुखी।'),
('dumbbells', 'ru', 'Гантели', 'Регулируемые или фиксированные ручные веса, универсальные для изолирующих и базовых упражнений.'),
('dumbbells', 'nl', 'Halters (dumbbells)', 'Verstelbare of vaste handgewichten, veelzijdig voor isolatie- en samengestelde oefeningen.'),
('dumbbells', 'sv', 'Hantlar', 'Justerbara eller fasta handvikter, mångsidiga för isolations- och basövningar.'),
('dumbbells', 'pl', 'Hantle', 'Regulowane lub stałe obciążenia ręczne, wszechstronne w ćwiczeniach izolowanych i wielostawowych.'),
('dumbbells', 'id', 'Dumbbell', 'Beban tangan yang dapat disesuaikan atau tetap, serbaguna untuk latihan isolasi dan gabungan.'),
('dumbbells', 'bn', 'ডাম্বেল', 'অ্যাডজাস্টেবল বা ফিক্সড হ্যান্ড ওয়েট, যা আইসোলেশন এবং কম্পাউন্ড ব্যায়ামের জন্য বহুমুখী।'),
('dumbbells', 'vi', 'Tạ tay (Dumbbells)', 'Tạ cầm tay điều chỉnh hoặc cố định, linh hoạt cho các bài tập cô lập và phức hợp.'),
('dumbbells', 'fa', 'دمبل', 'وزنه‌های دستی قابل تنظیم یا ثابت، بسیار کاربردی برای تمرینات ایزوله و ترکیبی.');