INSERT OR IGNORE INTO machines_info (slug, lang, title, "desc") VALUES
('elliptical', 'es', 'Elíptica', 'Máquina de cardio que simula correr o caminar sin impacto en las articulaciones.'),
('elliptical', 'en', 'Elliptical', 'Cardio machine that simulates running or walking without impact on the joints.'),
('elliptical', 'pt', 'Elíptico', 'Máquina de cardio que simula correr ou caminhar sem impacto nas articulações.'),
('elliptical', 'fr', 'Vélo elliptique', 'Machine de cardio simulant la course ou la marche sans impact sur les articulations.'),
('elliptical', 'de', 'Crosstrainer', 'Cardiogerät, das Laufen oder Gehen ohne Gelenkbelastung simuliert.'),
('elliptical', 'it', 'Ellittica', 'Macchina cardio che simula la corsa o la camminata senza impatto sulle articolazioni.'),
('elliptical', 'zh', '椭圆机', '模拟跑步或行走的有氧器械，对关节无冲击。'),
('elliptical', 'ja', 'エリプティカル', '関節への負担をかけずにランニングやウォーキングをシミュレーションできる有酸素運動マシン。'),
('elliptical', 'ko', '일립티컬', '관절에 무리를 주지 않으면서 달리기나 걷기 운동을 시뮬레이션할 수 있는 유산소 운동 기구입니다.'),
('elliptical', 'ar', 'جهاز الإليبتيكال (Elliptical)', 'جهاز كارديو يحاكي الجري أو المشي دون التسبب في صدمات للمفاصل.'),
('elliptical', 'hi', 'एलिप्टिकल', 'कार्डियो मशीन जो जोड़ों पर बिना किसी प्रभाव के दौड़ने या चलने का अनुकरण करती है।'),
('elliptical', 'ru', 'Эллиптический тренажер', 'Кардиотренажер, имитирующий бег или ходьбу без ударной нагрузки на суставы.'),
('elliptical', 'nl', 'Crosstrainer', 'Cardiomachine die hardlopen of wandelen simuleert zonder belasting van de gewrichten.'),
('elliptical', 'sv', 'Elliptisk maskin', 'Kardiomaskin som simulerar löpning eller promenad utan belastning på lederna.'),
('elliptical', 'pl', 'Orbitrek', 'Urządzenie cardio symulujące bieganie lub chodzenie bez obciążania stawów.'),
('elliptical', 'id', 'Elliptical', 'Mesin kardio yang mensimulasikan lari atau jalan tanpa dampak pada sendi.'),
('elliptical', 'bn', 'এলিটিকাল', 'কার্ডিও মেশিন যা জয়েন্টগুলোতে কোনো প্রভাব ছাড়াই দৌড়ানো বা হাঁটার অনুভূতি দেয়।'),
('elliptical', 'vi', 'Máy tập toàn thân (Elliptical)', 'Máy tập cardio mô phỏng chuyển động chạy hoặc đi bộ mà không gây tác động lên các khớp.'),
('elliptical', 'fa', 'دستگاه الیپتیکال (اسکی فضایی)', 'دستگاه هوازی که دویدن یا پیاده‌روی را بدون فشار بر مفاصل شبیه‌سازی می‌کند.');