INSERT OR IGNORE INTO machines_info (slug, lang, title, "desc") VALUES
('ez_bar', 'es', 'Barra Z', 'Barra con forma ondulada para reducir la tensión en muñecas durante ejercicios de bíceps y tríceps.'),
('ez_bar', 'en', 'EZ bar', 'Wavy-shaped bar designed to reduce wrist strain during bicep and tricep exercises.'),
('ez_bar', 'pt', 'Barra W', 'Barra com formato ondulado para reduzir a tensão nos pulsos durante exercícios de bíceps e tríceps.'),
('ez_bar', 'fr', 'Barre EZ', 'Barre ondulée conçue pour réduire la tension sur les poignets lors des exercices de biceps et de triceps.'),
('ez_bar', 'de', 'SZ-Stange', 'Gewellte Stange zur Entlastung der Handgelenke bei Bizeps- und Trizepsübungen.'),
('ez_bar', 'it', 'Bilanciere EZ', 'Barra ondulata progettata per ridurre lo stress sui polsi durante gli esercizi per bicipiti e tricipiti.'),
('ez_bar', 'zh', '曲柄杠铃 (EZ Bar)', '波浪形杠铃，旨在减轻二头肌和三头肌训练时手腕的压力。'),
('ez_bar', 'ja', 'EZバー', '二頭筋や三頭筋のトレーニング中に手首への負担を軽減するように設計された波形のバー。'),
('ez_bar', 'ko', 'EZ 바', '이두근 및 삼두근 운동 중 손목의 부담을 줄이기 위해 설계된 웨이브 형태의 바입니다.'),
('ez_bar', 'ar', 'بار متعرج (EZ bar)', 'قضيب متعرج مصمم لتقليل الضغط على المعصمين أثناء تمارين البايسبس والترايسيبس.'),
('ez_bar', 'hi', 'ईज़ी बार', 'बाइसेप्स और ट्राइसेप्स व्यायाम के दौरान कलाई के तनाव को कम करने के लिए डिज़ाइन की गई लहरदार बार।'),
('ez_bar', 'ru', 'EZ-гриф', 'Изогнутый гриф, разработанный для снижения нагрузки на запястья при выполнении упражнений на бицепс и трицепс.'),
('ez_bar', 'nl', 'EZ-bar', 'Golvende stang ontworpen om polsbelasting tijdens bicep- en tricep-oefeningen te verminderen.'),
('ez_bar', 'sv', 'EZ-stång', 'Vågig stång utformad för att minska belastningen på handlederna vid bicep- och tricepsträning.'),
('ez_bar', 'pl', 'Gryf łamany (EZ)', 'Wygięty gryf zaprojektowany w celu zmniejszenia obciążenia nadgarstków podczas ćwiczeń na biceps i triceps.'),
('ez_bar', 'id', 'EZ bar', 'Batang bergelombang yang dirancang untuk mengurangi ketegangan pergelangan tangan selama latihan bisep dan trisep.'),
('ez_bar', 'bn', 'ইজি বার', 'বাইসেপ এবং ট্রাইসেপ ব্যায়ামের সময় কবজির চাপ কমাতে ডিজাইন করা ওয়েভি-শেপড বার।'),
('ez_bar', 'vi', 'Thanh đòn zic-zac (EZ bar)', 'Thanh đòn hình sóng được thiết kế để giảm áp lực lên cổ tay trong các bài tập tay trước và tay sau.'),
('ez_bar', 'fa', 'هالتر خم (EZ Bar)', 'میله موج‌دار طراحی شده برای کاهش فشار روی مچ دست در حین تمرینات جلو بازو و پشت بازو.');