INSERT INTO machines_info (slug, lang, title, "desc") VALUES
('foam_roller', 'es', 'Rodillo de espuma', 'Herramienta cilíndrica de espuma para liberación miofascial y recuperación muscular.'),
('foam_roller', 'en', 'Foam roller', 'Cylindrical foam tool used for myofascial release and muscle recovery.'),
('foam_roller', 'pt', 'Rolo de espuma', 'Ferramenta cilíndrica de espuma usada para liberação miofascial e recuperação muscular.'),
('foam_roller', 'fr', 'Rouleau de massage', 'Outil cylindrique en mousse utilisé pour la libération myofasciale et la récupération musculaire.'),
('foam_roller', 'de', 'Faszienrolle', 'Zylindrisches Schaumstoffgerät zur myofaszialen Entspannung und Muskelregeneration.'),
('foam_roller', 'it', 'Rullo di schiuma (Foam roller)', 'Attrezzo cilindrico in schiuma utilizzato per il rilascio miofasciale e il recupero muscolare.'),
('foam_roller', 'zh', '泡沫轴', '用于肌筋膜放松和肌肉恢复的圆柱形泡沫工具。'),
('foam_roller', 'ja', 'フォームローラー', '筋膜リリースや筋肉の回復に使用される円筒形のフォームツール。'),
('foam_roller', 'ko', '폼롤러', '근막 이완 및 근육 회복을 위해 사용되는 원통형 폼 도구입니다.'),
('foam_roller', 'ar', 'أسطوانة الفوم (Foam roller)', 'أداة أسطوانية من الفوم تستخدم لتحرير اللفافة العضلية وتسريع استشفاء العضلات.'),
('foam_roller', 'hi', 'फोम रोलर', 'मायोफेशियल रिलीज़ और मांसपेशियों की रिकवरी के लिए उपयोग किया जाने वाला बेलनाकार फोम टूल।'),
('foam_roller', 'ru', 'Массажный ролл', 'Цилиндрический инструмент из пеноматериала для миофасциального релиза и восстановления мышц.'),
('foam_roller', 'nl', 'Foam roller', 'Cilindrisch schuimhulpmiddel gebruikt voor myofasciale release en spierherstel.'),
('foam_roller', 'sv', 'Foam roller', 'Cylindriskt skumverktyg som används för myofascial frisättning och muskelåterhämtning.'),
('foam_roller', 'pl', 'Roller (wałek)', 'Cylindryczne narzędzie piankowe używane do rozluźniania mięśniowo-powięziowego i regeneracji.'),
('foam_roller', 'id', 'Foam roller', 'Alat busa silindris yang digunakan untuk rilis miofasial dan pemulihan otot.'),
('foam_roller', 'bn', 'ফোম রোলার', 'মায়োফাশিয়াল রিলিজ এবং পেশী পুনরুদ্ধারের জন্য ব্যবহৃত সিলিন্ডার আকৃতির ফোম টুল।'),
('foam_roller', 'vi', 'Con lăn tập gym', 'Dụng cụ hình trụ bằng xốp dùng để giải phóng cân cơ và phục hồi cơ bắp.'),
('foam_roller', 'fa', 'فوم رولر', 'ابزار استوانه‌ای فومی که برای آزادسازی میوفاشیال و ریکاوری عضلات استفاده می‌شود.');