INSERT INTO machines_info (slug, lang, title, "desc") VALUES
('glute_drive_machine', 'es', 'Máquina de empuje de cadera', 'Máquina diseñada para realizar hip thrusts de forma segura con trayectoria guiada y carga ajustable.'),
('glute_drive_machine', 'en', 'Glute drive machine', 'Machine designed to perform hip thrusts safely with a guided path and adjustable load.'),
('glute_drive_machine', 'pt', 'Máquina de elevação pélvica', 'Máquina projetada para realizar elevação pélvica com segurança, trajetória guiada e carga ajustável.'),
('glute_drive_machine', 'fr', 'Machine à hip thrust', 'Machine conçue pour effectuer des hip thrusts en toute sécurité avec une trajectoire guidée et une charge réglable.'),
('glute_drive_machine', 'de', 'Hip-Thrust-Maschine', 'Gerät zur sicheren Ausführung von Hip Thrusts mit geführter Bewegungsbahn und einstellbarem Gewicht.'),
('glute_drive_machine', 'it', 'Macchina per hip thrust', 'Macchina progettata per eseguire hip thrust in sicurezza con traiettoria guidata e carico regolabile.'),
('glute_drive_machine', 'zh', '臀冲机 (Hip Thrust)', '设计用于以引导轨迹和可调负载安全执行臀冲动作的机器。'),
('glute_drive_machine', 'ja', 'ヒップスラスト・マシン', 'ガイド付きの軌道と調整可能な負荷で、安全にヒップスラストを行うためのマシン。'),
('glute_drive_machine', 'ko', '힙 쓰러스트 머신', '가이드가 있는 궤적과 조절 가능한 부하를 통해 힙 쓰러스트를 안전하게 수행하도록 설계된 머신입니다.'),
('glute_drive_machine', 'ar', 'جهاز دفع الورك (Hip thrust)', 'جهاز مصمم لأداء تمارين دفع الورك بأمان مع مسار موجه وحمل قابل للتعديل.'),
('glute_drive_machine', 'hi', 'ग्लूट ड्राइव मशीन', 'गाइडेड पाथ और समायोज्य भार के साथ हिप थ्रस्ट सुरक्षित रूप से करने के लिए डिज़ाइन की गई मशीन।'),
('glute_drive_machine', 'ru', 'Тренажер для ягодичного мостика', 'Тренажер, предназначенный для безопасного выполнения ягодичного мостика с фиксированной траекторией и регулируемой нагрузкой.'),
('glute_drive_machine', 'nl', 'Glute drive machine', 'Machine ontworpen om hip thrusts veilig uit te voeren met een geleide baan en instelbare belasting.'),
('glute_drive_machine', 'sv', 'Hip thrust-maskin', 'Maskin designad för att utföra hip thrusts säkert med guidad bana och justerbar belastning.'),
('glute_drive_machine', 'pl', 'Maszyna do hip thrustów', 'Maszyna zaprojektowana do bezpiecznego wykonywania wyciskania bioder z prowadnicą i regulowanym obciążeniem.'),
('glute_drive_machine', 'id', 'Mesin glute drive', 'Mesin yang dirancang untuk melakukan hip thrust dengan aman dengan jalur yang dipandu dan beban yang dapat disesuaikan.'),
('glute_drive_machine', 'bn', 'গ্লুট ড্রাইভ মেশিন', 'গাইডেড পাথ এবং অ্যাডজাস্টেবল লোডের সাথে নিরাপদে হিপ থ্রাস্ট করার জন্য ডিজাইন করা মেশিন।'),
('glute_drive_machine', 'vi', 'Máy tập mông (Hip thrust)', 'Máy được thiết kế để thực hiện bài tập đẩy hông an toàn với quỹ đạo có hướng dẫn và mức tạ có thể điều chỉnh.'),
('glute_drive_machine', 'fa', 'دستگاه گلات درایو (Hip Thrust)', 'دستگاه طراحی شده برای انجام ایمن حرکت هیپ تراست با مسیر هدایت‌شده و بار قابل تنظیم.');