INSERT OR IGNORE INTO machines_info (slug, lang, title, "desc") VALUES
('glute_ham_developer', 'es', 'Máquina de glúteo-isquios (GHD)', 'Banco especializado para fortalecer la cadena posterior, glúteos e isquiotibiales mediante extensiones.'),
('glute_ham_developer', 'en', 'Glute-Ham Developer (GHD)', 'Specialized bench to strengthen the posterior chain, glutes, and hamstrings through extensions.'),
('glute_ham_developer', 'pt', 'Máquina GHD', 'Banco especializado para fortalecer a cadeia posterior, glúteos e isquiotibiais através de extensões.'),
('glute_ham_developer', 'fr', 'Banc à lombaires (GHD)', 'Banc spécialisé pour renforcer la chaîne postérieure, les fessiers et les ischio-jambiers par des extensions.'),
('glute_ham_developer', 'de', 'Glute-Ham-Developer (GHD)', 'Spezialisierte Bank zur Stärkung der hinteren Kette, Gesäßmuskeln und Beinbeuger durch Extensions.'),
('glute_ham_developer', 'it', 'Glute Ham Developer (GHD)', 'Panca specializzata per rinforzare la catena posteriore, glutei e ischiocrurali tramite estensioni.'),
('glute_ham_developer', 'zh', 'GHD训练器', '通过伸展动作增强后侧链、臀肌和腘绳肌的专业训练凳。'),
('glute_ham_developer', 'ja', 'GHDベンチ', '伸展運動を通じて、背面筋肉群、臀部、ハムストリングを強化するための専門的なベンチ。'),
('glute_ham_developer', 'ko', 'GHD 머신', '신전 운동을 통해 후면 사슬, 둔근 및 햄스트링을 강화하기 위한 전문 벤치입니다.'),
('glute_ham_developer', 'ar', 'جهاز GHD', 'مقعد متخصص لتقوية السلسلة الخلفية، والأرداف، وأوتار الركبة من خلال تمارين التمديد.'),
('glute_ham_developer', 'hi', 'ग्लूट-हैम डेवलपर (GHD)', 'एक्सटेंशन के माध्यम से पोस्टीरियर चेन, ग्लूट्स और हैमस्ट्रिंग को मजबूत करने के लिए विशेष बेंच।'),
('glute_ham_developer', 'ru', 'Тренажер GHD', 'Специализированная скамья для укрепления задней цепи мышц, ягодиц и бицепсов бедра с помощью разгибаний.'),
('glute_ham_developer', 'nl', 'Glute-Ham Developer (GHD)', 'Gespecialiseerde bank om de posterieure keten, billen en hamstrings te versterken door middel van extensies.'),
('glute_ham_developer', 'sv', 'Glute-Ham Developer (GHD)', 'Specialiserad bänk för att stärka den bakre kedjan, gluteus och hamstrings genom extensioner.'),
('glute_ham_developer', 'pl', 'Ławka rzymska (GHD)', 'Specjalistyczna ławka do wzmacniania tylnej taśmy mięśniowej, pośladków i mięśni dwugłowych uda poprzez wyprosty.'),
('glute_ham_developer', 'id', 'Glute-Ham Developer (GHD)', 'Bangku khusus untuk memperkuat rantai posterior, bokong, dan hamstring melalui ekstensi.'),
('glute_ham_developer', 'bn', 'গ্লুট-হ্যাম ডেভেলপার (GHD)', 'এক্সটেনশনের মাধ্যমে পোস্টেরিয়র চেইন, গ্লুটস এবং হ্যামস্ট্রিং শক্তিশালী করার জন্য বিশেষ বেঞ্চ।'),
('glute_ham_developer', 'vi', 'Máy tập lưng bụng (GHD)', 'Ghế chuyên dụng để tăng cường chuỗi cơ sau, cơ mông và cơ đùi sau thông qua các bài tập duỗi.'),
('glute_ham_developer', 'fa', 'دستگاه GHD (Glute-Ham Developer)', 'نیمکت تخصصی برای تقویت زنجیره پشتی، عضلات باسن و همسترینگ از طریق حرکات بازگشت (اکستنشن).');