INSERT OR IGNORE INTO machines_info (slug, lang, title, "desc") VALUES
('hack_squat_machine', 'es', 'Máquina de sentadilla Hack', 'Máquina que guía el movimiento de sentadilla para enfatizar el trabajo de cuádriceps mediante un soporte de espalda fijo.'),
('hack_squat_machine', 'en', 'Hack squat machine', 'Machine that guides the squat movement to emphasize quad work with a fixed back support.'),
('hack_squat_machine', 'pt', 'Máquina de agachamento Hack', 'Máquina que guia o movimento de agachamento para enfatizar o trabalho de quadríceps com um suporte de costas fixo.'),
('hack_squat_machine', 'fr', 'Machine à hack squat', 'Machine qui guide le mouvement de squat pour accentuer le travail des quadriceps grâce à un support dorsal fixe.'),
('hack_squat_machine', 'de', 'Hack-Squat-Maschine', 'Gerät zur geführten Kniebeugenbewegung, das durch eine feste Rückenstütze den Fokus auf den Quadrizeps legt.'),
('hack_squat_machine', 'it', 'Macchina per hack squat', 'Macchina che guida il movimento dello squat per enfatizzare il lavoro dei quadricipiti tramite un supporto schiena fisso.'),
('hack_squat_machine', 'zh', '哈克深蹲机', '通过固定背部支撑引导深蹲动作，以强化股四头肌训练的器械。'),
('hack_squat_machine', 'ja', 'ハックスクワット・マシン', '背中を固定した状態でガイドに沿ってスクワットを行い、大腿四頭筋を重点的に鍛えるためのマシン。'),
('hack_squat_machine', 'ko', '핵 스쿼트 머신', '고정된 등받이를 통해 스쿼트 동작을 가이드하며 대퇴사두근 운동을 강조하는 머신입니다.'),
('hack_squat_machine', 'ar', 'جهاز سكوات هاك (Hack squat)', 'جهاز يوجه حركة السكوات للتركيز على عضلات الفخذ الأمامية من خلال دعم ثابت للظهر.'),
('hack_squat_machine', 'hi', 'हैक स्क्वाट मशीन', 'मशीन जो फिक्स्ड बैक सपोर्ट के साथ क्वाड्रिसेप्स वर्क पर जोर देने के लिए स्क्वाट मूवमेंट को गाइड करती है।'),
('hack_squat_machine', 'ru', 'Тренажер для гакк-приседаний', 'Тренажер, направляющий движение приседа для акцентированной проработки квадрицепсов с фиксированной опорой для спины.'),
('hack_squat_machine', 'nl', 'Hack squat machine', 'Machine die de squatbeweging begeleidt om de nadruk te leggen op quads met een vaste rugsteun.'),
('hack_squat_machine', 'sv', 'Hack squat-maskin', 'Maskin som styr knäböjningsrörelsen för att betona träning av framsida lår med ett fast ryggstöd.'),
('hack_squat_machine', 'pl', 'Maszyna do hack przysiadów', 'Maszyna prowadząca ruch przysiadu w celu zaangażowania mięśni czworogłowych uda przy wsparciu pleców.'),
('hack_squat_machine', 'id', 'Mesin hack squat', 'Mesin yang memandu gerakan squat untuk menekankan latihan otot paha depan dengan dukungan punggung tetap.'),
('hack_squat_machine', 'bn', 'হ্যাক স্কোয়াট মেশিন', 'মেশিন যা নির্দিষ্ট ব্যাক সাপোর্টের মাধ্যমে কোয়াড্রিসেপস ওয়ার্কআউটের উপর জোর দিয়ে স্কোয়াট মুভমেন্টকে গাইড করে।'),
('hack_squat_machine', 'vi', 'Máy tập đùi (Hack squat)', 'Máy hỗ trợ hướng dẫn chuyển động squat giúp tập trung vào cơ đùi trước nhờ giá đỡ lưng cố định.'),
('hack_squat_machine', 'fa', 'دستگاه هک اسکات', 'دستگاهی که حرکت اسکات را هدایت می‌کند تا با تکیه‌گاه ثابت کمر، تمرکز بر عضلات چهارسر ران باشد.');