INSERT OR IGNORE INTO machines_info (slug, lang, title, "desc") VALUES
('hex_bar', 'es', 'Barra hexagonal (Trap bar)', 'Barra en forma hexagonal que permite cargar peso alineado con el centro de gravedad, ideal para peso muerto.'),
('hex_bar', 'en', 'Hex bar (Trap bar)', 'Hexagon-shaped bar allowing weight to be loaded in line with the center of gravity, ideal for deadlifts.'),
('hex_bar', 'pt', 'Barra hexagonal (Trap bar)', 'Barra em forma hexagonal que permite carregar peso alinhado com o centro de gravidade, ideal para levantamento terra.'),
('hex_bar', 'fr', 'Barre hexagonale (Trap bar)', 'Barre de forme hexagonale permettant de charger le poids dans l axe du centre de gravité, idéale pour le soulevé de terre.'),
('hex_bar', 'de', 'Hex-Stange (Trap Bar)', 'Hexagonale Stange, die das Gewicht in einer Linie mit dem Schwerpunkt hält, ideal für Kreuzheben.'),
('hex_bar', 'it', 'Barra esagonale (Trap bar)', 'Barra a forma esagonale che permette di caricare il peso in linea con il centro di gravità, ideale per lo stacco da terra.'),
('hex_bar', 'zh', '六角杠铃 (Trap bar)', '六边形杠铃，允许重量与重心对齐，是硬拉训练的理想选择。'),
('hex_bar', 'ja', 'ヘックスバー（トラップバー）', '六角形のバーで、重心と一直線上に重量を配置できるため、デッドリフトに最適。'),
('hex_bar', 'ko', '헥스 바 (트랩 바)', '육각형 형태의 바로, 무게 중심과 정렬된 부하를 주어 데드리프트에 이상적입니다.'),
('hex_bar', 'ar', 'البار السداسي (Trap bar)', 'بار سداسي الشكل يسمح بتحميل الوزن بما يتماشى مع مركز الجاذبية، مثالي لتمارين الرفعة الميتة (Deadlift).'),
('hex_bar', 'hi', 'हेक्स बार (ट्रैप बार)', 'षट्कोणीय आकार की बार जो वजन को गुरुत्वाकर्षण केंद्र के साथ संरेखित करने की अनुमति देती है, डेडलिफ्ट के लिए आदर्श।'),
('hex_bar', 'ru', 'Гексагональный гриф (Трэп-гриф)', 'Гриф шестигранной формы, позволяющий держать вес на одной линии с центром тяжести, идеально подходит для становой тяги.'),
('hex_bar', 'nl', 'Hex bar (Trap bar)', 'Zeshoekige stang waarmee gewicht in lijn met het zwaartepunt kan worden geladen, ideaal voor deadlifts.'),
('hex_bar', 'sv', 'Hex-stång (Trap bar)', 'Hexagonformad stång som tillåter vikt i linje med tyngdpunkten, idealisk för marklyft.'),
('hex_bar', 'pl', 'Sztanga typu trap (Hex bar)', 'Sztanga w kształcie sześciokąta, umożliwiająca obciążenie w linii ze środkiem ciężkości, idealna do martwego ciągu.'),
('hex_bar', 'id', 'Hex bar (Trap bar)', 'Batang berbentuk segi enam yang memungkinkan beban dimuat sejajar dengan pusat gravitasi, ideal untuk deadlift.'),
('hex_bar', 'bn', 'হেক্স বার (ট্র্যাপ বার)', 'ষড়ভুজ আকৃতির বার যা ভরকেন্দ্রের সাথে ওজনকে সামঞ্জস্য করতে দেয়, ডেডলিফ্টের জন্য আদর্শ।'),
('hex_bar', 'vi', 'Thanh đòn lục giác (Trap bar)', 'Thanh đòn hình lục giác giúp phân bổ tạ thẳng hàng với trọng tâm, lý tưởng cho bài tập deadlift.'),
('hex_bar', 'fa', 'هالتر شش‌ضلعی (Trap Bar)', 'میله شش‌ضلعی که امکان قرارگیری وزن در راستای مرکز ثقل بدن را فراهم می‌کند، ایده‌آل برای ددلیفت.');