INSERT INTO machines_info (slug, lang, title, "desc") VALUES
('hyperextension_bench', 'es', 'Banco de hiperextensiones', 'Banco diseñado para fortalecer la zona lumbar y los erectores de la columna.'),
('hyperextension_bench', 'en', 'Hyperextension bench', 'Bench designed to strengthen the lower back and spinal erectors.'),
('hyperextension_bench', 'pt', 'Banco de hiperextensão', 'Banco projetado para fortalecer a região lombar e os eretores da espinha.'),
('hyperextension_bench', 'fr', 'Banc à hyperextensions', 'Banc conçu pour renforcer le bas du dos et les érecteurs du rachis.'),
('hyperextension_bench', 'de', 'Hyperextension-Bank', 'Bank zur Stärkung des unteren Rückens und der Wirbelsäulenstrecker.'),
('hyperextension_bench', 'it', 'Panca per iperextension', 'Panca progettata per rinforzare la zona lombare e gli erettori spinali.'),
('hyperextension_bench', 'zh', '山羊挺身训练凳', '专门用于加强下背部和脊柱竖脊肌的训练凳。'),
('hyperextension_bench', 'ja', 'ハイパーエクステンション・ベンチ', '腰部と脊柱起立筋を強化するために設計されたベンチ。'),
('hyperextension_bench', 'ko', '하이퍼익스텐션 벤치', '하부 등 근육과 척추 기립근을 강화하기 위해 설계된 벤치입니다.'),
('hyperextension_bench', 'ar', 'جهاز تمديد الظهر (Hyperextension)', 'مقعد مصمم لتقوية أسفل الظهر وعضلات العمود الفقري.'),
('hyperextension_bench', 'hi', 'हाइपरएक्सटेंशन बेंच', 'निचली पीठ और रीढ़ की हड्डी के इरेक्टर्स को मजबूत करने के लिए डिज़ाइन की गई बेंच।'),
('hyperextension_bench', 'ru', 'Скамья для гиперэкстензии', 'Скамья, предназначенная для укрепления мышц поясницы и выпрямителей позвоночника.'),
('hyperextension_bench', 'nl', 'Hyperextension bankje', 'Bank ontworpen om de onderrug en rugstrekkers te versterken.'),
('hyperextension_bench', 'sv', 'Hyperextensionsbänk', 'Bänk utformad för att stärka ländryggen och ryggsträckarna.'),
('hyperextension_bench', 'pl', 'Ławka do hiperextensji', 'Ławka zaprojektowana do wzmacniania dolnej części pleców i prostowników grzbietu.'),
('hyperextension_bench', 'id', 'Bangku hyperextension', 'Bangku yang dirancang untuk memperkuat punggung bawah dan erektor tulang belakang.'),
('hyperextension_bench', 'bn', 'হাইপারএক্সটেনশন বেঞ্চ', 'পিঠের নিচের অংশ এবং স্পাইনাল ইরেক্টর শক্তিশালী করার জন্য ডিজাইন করা বেঞ্চ।'),
('hyperextension_bench', 'vi', 'Ghế tập lưng (Hyperextension)', 'Ghế được thiết kế để tăng cường cơ lưng dưới và các cơ dựng cột sống.'),
('hyperextension_bench', 'fa', 'نیمکت فیله کمر (Hyperextension)', 'نیمکت طراحی شده برای تقویت ناحیه کمر و عضلات راست‌کننده ستون فقرات.');