INSERT INTO machines_info (slug, lang, title, "desc") VALUES
('incline_bench', 'es', 'Banco inclinado', 'Banco con ángulo ajustable hacia arriba, ideal para ejercicios de press superior de pecho y hombros.'),
('incline_bench', 'en', 'Incline bench', 'Bench with an upward adjustable angle, ideal for upper chest press and shoulder exercises.'),
('incline_bench', 'pt', 'Banco inclinado', 'Banco com ângulo ajustável para cima, ideal para exercícios de supino superior e ombros.'),
('incline_bench', 'fr', 'Banc incliné', 'Banc à angle réglable vers le haut, idéal pour le développé incliné et les exercices d épaules.'),
('incline_bench', 'de', 'Schrägbank', 'Bank mit nach oben verstellbarem Winkel, ideal für Schrägbankdrücken und Schulterübungen.'),
('incline_bench', 'it', 'Panca inclinata', 'Panca con angolo regolabile verso l alto, ideale per panca inclinata ed esercizi per le spalle.'),
('incline_bench', 'zh', '上斜哑铃凳', '向上调节角度的凳子，是上胸推举和肩部训练的理想选择。'),
('incline_bench', 'ja', 'インクライン・ベンチ', '上向きに角度調整可能なベンチで、上部胸筋や肩のトレーニングに最適。'),
('incline_bench', 'ko', '인클라인 벤치', '상향으로 각도 조절이 가능한 벤치로, 상부 가슴 운동 및 어깨 운동에 이상적입니다.'),
('incline_bench', 'ar', 'مقعد مائل للأعلى (Incline bench)', 'مقعد بزاوية قابلة للتعديل للأعلى، مثالي لتمارين ضغط الصدر العلوي وتمارين الأكتاف.'),
('incline_bench', 'hi', 'इन्क्लाइन बेंच', 'ऊपर की ओर एडजस्टेबल एंगल वाली बेंच, जो अपर चेस्ट प्रेस और कंधे के व्यायाम के लिए आदर्श है।'),
('incline_bench', 'ru', 'Скамья с положительным наклоном', 'Скамья с регулируемым углом наклона вверх, идеально подходит для жима на верхнюю часть груди и упражнений для плеч.'),
('incline_bench', 'nl', 'Incline bankje', 'Bank met naar boven verstelbare hoek, ideaal voor upper chest press en schouderoefeningen.'),
('incline_bench', 'sv', 'Incline bänk', 'Bänk med uppåt justerbar vinkel, idealisk för övre bröstpress och axelövningar.'),
('incline_bench', 'pl', 'Ławka skośna (dodatnia)', 'Ławka z regulacją kąta nachylenia w górę, idealna do wyciskania na górę klatki piersiowej i ćwiczeń barków.'),
('incline_bench', 'id', 'Bangku incline', 'Bangku dengan sudut yang dapat disesuaikan ke atas, ideal untuk latihan tekan dada atas dan bahu.'),
('incline_bench', 'bn', 'ইনক্লাইন বেঞ্চ', 'উপরের দিকে অ্যাডজাস্টেবল অ্যাঙ্গেল সহ বেঞ্চ, যা আপার চেস্ট প্রেস এবং কাঁধের ব্যায়ামের জন্য আদর্শ।'),
('incline_bench', 'vi', 'Ghế tập dốc lên (Incline bench)', 'Ghế có góc điều chỉnh hướng lên trên, lý tưởng cho các bài tập đẩy ngực trên và vai.'),
('incline_bench', 'fa', 'نیمکت شیب مثبت (Incline)', 'نیمکت با قابلیت تنظیم شیب رو به بالا، ایده‌آل برای پرس سینه بالا و تمرینات سرشانه.');