INSERT OR IGNORE INTO machines_info (slug, lang, title, "desc") VALUES
('kettlebell', 'es', 'Kettlebell (Pesa rusa)', 'Pesa de hierro fundido con forma de bola y asa, ideal para ejercicios balísticos y de fuerza funcional.'),
('kettlebell', 'en', 'Kettlebell', 'Cast iron weight with a spherical body and handle, ideal for ballistic and functional strength exercises.'),
('kettlebell', 'pt', 'Kettlebell', 'Peso de ferro fundido em forma de bola com alça, ideal para exercícios balísticos e de força funcional.'),
('kettlebell', 'fr', 'Kettlebell', 'Poids en fonte en forme de boule avec poignée, idéal pour les exercices balistiques et de force fonctionnelle.'),
('kettlebell', 'de', 'Kettlebell (Kugelhantel)', 'Gusseisernes Gewicht in Kugelform mit Griff, ideal für ballistische Übungen und funktionelles Krafttraining.'),
('kettlebell', 'it', 'Kettlebell', 'Peso in ghisa a forma di palla con maniglia, ideale per esercizi balistici e di forza funzionale.'),
('kettlebell', 'zh', '壶铃', '带有手柄的球形铸铁重物，是进行爆发力训练和功能性力量训练的理想选择。'),
('kettlebell', 'ja', 'ケトルベル', '取っ手が付いた球形の鋳鉄製ウェイトで、バリスティック種目やファンクショナル・トレーニングに最適。'),
('kettlebell', 'ko', '케틀벨', '손잡이가 달린 구형 주철 무게추로, 탄성 운동 및 기능성 근력 운동에 이상적입니다.'),
('kettlebell', 'ar', 'جرس الكاتل بيل (Kettlebell)', 'وزن من الحديد المصبوب على شكل كرة مع مقبض، مثالي للتمارين الباليستية وتمارين القوة الوظيفية.'),
('kettlebell', 'hi', 'केटलबेल', 'हैंडल के साथ गोलाकार कास्ट आयरन वेट, जो बैलिस्टिक और कार्यात्मक शक्ति व्यायाम के लिए आदर्श है।'),
('kettlebell', 'ru', 'Гиря', 'Чугунный снаряд в форме шара с рукояткой, идеально подходит для баллистических упражнений и развития функциональной силы.'),
('kettlebell', 'nl', 'Kettlebell', 'Gietijzeren gewicht in de vorm van een kogel met handvat, ideaal voor ballistische en functionele krachtoefeningen.'),
('kettlebell', 'sv', 'Kettlebell', 'Gjutjärnsvikt i form av ett klot med handtag, idealisk för ballistiska och funktionella styrkeövningar.'),
('kettlebell', 'pl', 'Kettlebell (odważnik kulowy)', 'Żeliwny odważnik w kształcie kuli z uchwytem, idealny do ćwiczeń balistycznych i siłowych.'),
('kettlebell', 'id', 'Kettlebell', 'Beban besi cor berbentuk bola dengan pegangan, ideal untuk latihan balistik dan kekuatan fungsional.'),
('kettlebell', 'bn', 'কেটলবেল', 'হ্যান্ডেল সহ গোলাকার কাস্ট আয়রন ওজন, যা ব্যালাস্টিক এবং কার্যকরী শক্তি ব্যায়ামের জন্য আদর্শ।'),
('kettlebell', 'vi', 'Tạ ấm (Kettlebell)', 'Tạ gang hình quả cầu có tay cầm, lý tưởng cho các bài tập bổ trợ sức mạnh chức năng và chuyển động bóng.'),
('kettlebell', 'fa', 'کتل‌بل', 'وزنه چدنی کروی‌شکل دارای دسته، ایده‌آل برای تمرینات پرتابی (بالستیک) و قدرت عملکردی.');