INSERT OR IGNORE INTO machines_info (slug, lang, title, "desc") VALUES
('lat_pulldown_machine', 'es', 'Máquina de jalón al pecho', 'Máquina de poleas diseñada para trabajar los músculos dorsales mediante un movimiento de tracción vertical.'),
('lat_pulldown_machine', 'en', 'Lat pulldown machine', 'Pulley machine designed to work the latissimus dorsi muscles through a vertical pulling movement.'),
('lat_pulldown_machine', 'pt', 'Máquina de puxada alta', 'Máquina de polias projetada para trabalhar os músculos dorsais através de um movimento de tração vertical.'),
('lat_pulldown_machine', 'fr', 'Machine à tirage vertical', 'Machine à poulie conçue pour travailler les muscles dorsaux via un mouvement de traction verticale.'),
('lat_pulldown_machine', 'de', 'Latzugmaschine', 'Seilzuggerät zur Stärkung der Rückenmuskulatur durch vertikale Zugbewegungen.'),
('lat_pulldown_machine', 'it', 'Lat machine', 'Macchina a cavi progettata per allenare i muscoli dorsali tramite un movimento di trazione verticale.'),
('lat_pulldown_machine', 'zh', '高位下拉机', '通过垂直拉动动作锻炼背阔肌的滑轮器械。'),
('lat_pulldown_machine', 'ja', 'ラットプルダウン・マシン', '垂直な引き下げ動作により広背筋を鍛えるためのプーリー式マシン。'),
('lat_pulldown_machine', 'ko', '랫 풀다운 머신', '수직 당기기 동작을 통해 광배근을 단련하도록 설계된 케이블 머신입니다.'),
('lat_pulldown_machine', 'ar', 'جهاز سحب الظهر (Lat pulldown)', 'جهاز بكرات مصمم لتقوية عضلات الظهر العريضة من خلال حركة سحب عمودية.'),
('lat_pulldown_machine', 'hi', 'लैट पुलडाउन मशीन', 'वर्टिकल पुलिंग मूवमेंट के माध्यम से लैटिसिमस डॉर्सी मांसपेशियों पर काम करने के लिए डिज़ाइन की गई पुली मशीन।'),
('lat_pulldown_machine', 'ru', 'Тренажер для тяги верхнего блока', 'Блочный тренажер, предназначенный для проработки широчайших мышц спины с помощью вертикальной тяги.'),
('lat_pulldown_machine', 'nl', 'Lat pulldown machine', 'Kabelmachine ontworpen om de rugspieren te trainen door middel van een verticale trekbeweging.'),
('lat_pulldown_machine', 'sv', 'Lat pulldown-maskin', 'Kabelmaskin utformad för att träna ryggmusklerna genom en vertikal dragrörelse.'),
('lat_pulldown_machine', 'pl', 'Maszyna do ściągania drążka wyciągu górnego', 'Maszyna wyciągowa zaprojektowana do pracy nad mięśniami najszerszymi grzbietu poprzez ruch pionowy.'),
('lat_pulldown_machine', 'id', 'Mesin lat pulldown', 'Mesin katrol yang dirancang untuk melatih otot punggung melalui gerakan menarik vertikal.'),
('lat_pulldown_machine', 'bn', 'ল্যাট পুলডাউন মেশিন', 'উল্লম্ব টানা মুভমেন্টের মাধ্যমে ল্যাটিসিমাস ডরসি পেশী কাজ করার জন্য ডিজাইন করা পুলি মেশিন।'),
('lat_pulldown_machine', 'vi', 'Máy kéo xô (Lat pulldown)', 'Máy tập với ròng rọc được thiết kế để tác động vào cơ xô thông qua chuyển động kéo dọc.'),
('lat_pulldown_machine', 'fa', 'دستگاه زیربغل سیم‌کش (Lat Pulldown)', 'دستگاه سیم‌کش طراحی شده برای تمرین عضلات زیربغل از طریق حرکت کششی عمودی.');