INSERT OR IGNORE INTO machines_info (slug, lang, title, "desc") VALUES
('leg_extension_machine', 'es', 'Máquina de extensión de pierna', 'Equipo diseñado para aislar y fortalecer los cuádriceps mediante un movimiento de extensión de rodilla.'),
('leg_extension_machine', 'en', 'Leg extension machine', 'Equipment designed to isolate and strengthen the quadriceps through a knee extension movement.'),
('leg_extension_machine', 'pt', 'Cadeira extensora', 'Equipamento projetado para isolar e fortalecer os quadríceps através de um movimento de extensão do joelho.'),
('leg_extension_machine', 'fr', 'Machine à leg extension', 'Équipement conçu pour isoler et renforcer les quadriceps par un mouvement d extension du genou.'),
('leg_extension_machine', 'de', 'Beinstrecker-Maschine', 'Gerät zur Isolierung und Stärkung des Quadrizeps durch Kniestreckbewegungen.'),
('leg_extension_machine', 'it', 'Macchina per leg extension', 'Attrezzatura progettata per isolare e rinforzare i quadricipiti tramite un movimento di estensione del ginocchio.'),
('leg_extension_machine', 'zh', '腿屈伸机', '旨在通过膝关节伸展动作孤立并加强股四头肌的器械。'),
('leg_extension_machine', 'ja', 'レッグエクステンション・マシン', '膝의 伸展運動を通じて大腿四頭筋を孤立させ、強化するために設計された機器。'),
('leg_extension_machine', 'ko', '레그 익스텐션 머신', '무릎 폄 동작을 통해 대퇴사두근을 고립시키고 강화하도록 설계된 장비입니다.'),
('leg_extension_machine', 'ar', 'جهاز تمرين الفخذ الأمامي (Leg extension)', 'جهاز مصمم لعزل وتقوية عضلات الفخذ الأمامية من خلال حركة تمديد الركبة.'),
('leg_extension_machine', 'hi', 'लेग एक्सटेंशन मशीन', 'घुटने के एक्सटेंशन मूवमेंट के माध्यम से कूड्रिसेप्स को अलग करने और मजबूत करने के लिए डिज़ाइन किया गया उपकरण।'),
('leg_extension_machine', 'ru', 'Тренажер для разгибания ног', 'Тренажер, предназначенный для изоляции и укрепления квадрицепсов с помощью разгибания коленей.'),
('leg_extension_machine', 'nl', 'Leg extension machine', 'Apparatuur ontworpen om de quadriceps te isoleren en te versterken door middel van een kniestrekbeweging.'),
('leg_extension_machine', 'sv', 'Leg extension-maskin', 'Utrustning utformad för att isolera och stärka quadriceps genom en knästräckningsrörelse.'),
('leg_extension_machine', 'pl', 'Maszyna do prostowania nóg (Leg extension)', 'Urządzenie zaprojektowane do izolacji i wzmacniania mięśni czworogłowych uda poprzez ruch prostowania kolan.'),
('leg_extension_machine', 'id', 'Mesin leg extension', 'Peralatan yang dirancang untuk mengisolasi dan memperkuat kuadrisep melalui gerakan ekstensi lutut.'),
('leg_extension_machine', 'bn', 'লেগ এক্সটেনশন মেশিন', 'হাঁটুর এক্সটেনশন মুভমেন্টের মাধ্যমে কোয়াড্রিসেপস আলাদা করতে এবং শক্তিশালী করতে ডিজাইন করা সরঞ্জাম।'),
('leg_extension_machine', 'vi', 'Máy tập đá đùi trước (Leg extension)', 'Thiết bị được thiết kế để cô lập và tăng cường cơ đùi trước thông qua chuyển động duỗi gối.'),
('leg_extension_machine', 'fa', 'دستگاه جلو پا (Leg Extension)', 'تجهیزات طراحی شده برای ایزوله کردن و تقویت عضلات چهارسر ران از طریق حرکت صاف کردن (اکستنشن) زانو.');