INSERT INTO machines_info (slug, lang, title, "desc") VALUES
('leg_press_machine', 'es', 'Prensa de piernas', 'Máquina para ejercicios de empuje con los pies, enfocada en fortalecer los músculos de las piernas y glúteos.'),
('leg_press_machine', 'en', 'Leg press machine', 'Machine for foot-pushing exercises, focused on strengthening leg and glute muscles.'),
('leg_press_machine', 'pt', 'Leg press', 'Máquina para exercícios de empurrar com os pés, focada em fortalecer os músculos das pernas e glúteos.'),
('leg_press_machine', 'fr', 'Presse à cuisses', 'Machine pour les exercices de poussée des pieds, axée sur le renforcement des muscles des jambes et des fessiers.'),
('leg_press_machine', 'de', 'Beinpresse', 'Gerät für Fußdruckübungen, das auf die Stärkung der Bein- und Gesäßmuskulatur ausgerichtet ist.'),
('leg_press_machine', 'it', 'Leg press', 'Macchina per esercizi di spinta con i piedi, focalizzata sul rafforzamento dei muscoli delle gambe e dei glutei.'),
('leg_press_machine', 'zh', '腿举机', '用于足部推举练习的器械，专注于增强腿部和臀部肌肉。'),
('leg_press_machine', 'ja', 'レッグプレス・マシン', '足で押し出す運動を行うマシンで、脚部と臀部の筋肉強化を目的とする。'),
('leg_press_machine', 'ko', '레그 프레스 머신', '발로 밀어내는 운동을 위한 기구로, 다리와 둔근의 근육을 강화하는 데 집중합니다.'),
('leg_press_machine', 'ar', 'جهاز ضغط الأرجل (Leg press)', 'جهاز لتمارين دفع القدمين، يركز على تقوية عضلات الأرجل والأرداف.'),
('leg_press_machine', 'hi', 'लेग प्रेस मशीन', 'पैर से धक्का देने वाले व्यायाम के लिए मशीन, जो पैरों और ग्लूट्स की मांसपेशियों को मजबूत करने पर केंद्रित है।'),
('leg_press_machine', 'ru', 'Жим ногами', 'Тренажер для упражнений на выталкивание веса ногами, направленный на укрепление мышц ног и ягодиц.'),
('leg_press_machine', 'nl', 'Leg press machine', 'Machine voor voetafduwoefeningen, gericht op het versterken van de been- en bilspieren.'),
('leg_press_machine', 'sv', 'Benpress-maskin', 'Maskin för fotpressövningar, fokuserad på att stärka ben- och sätesmusklerna.'),
('leg_press_machine', 'pl', 'Suwnica (Leg press)', 'Maszyna do ćwiczeń wypychania nóg, skupiająca się na wzmacnianiu mięśni nóg i pośladków.'),
('leg_press_machine', 'id', 'Mesin leg press', 'Mesin untuk latihan mendorong kaki, berfokus pada penguatan otot kaki dan bokong.'),
('leg_press_machine', 'bn', 'লেগ প্রেস মেশিন', 'পা দিয়ে ধাক্কা দেওয়ার ব্যায়ামের মেশিন, যা পা এবং গ্লুটস পেশী শক্তিশালী করার উপর দৃষ্টি নিবদ্ধ করে।'),
('leg_press_machine', 'vi', 'Máy tập ép đùi (Leg press)', 'Máy tập đẩy bằng chân, tập trung vào việc tăng cường sức mạnh cho cơ chân và mông.'),
('leg_press_machine', 'fa', 'دستگاه پرس پا', 'دستگاهی برای تمرینات هل دادن پا که بر تقویت عضلات پا و باسن تمرکز دارد.');