INSERT OR IGNORE INTO machines_info (slug, lang, title, "desc") VALUES
('leg_curl_machine', 'es', 'Máquina de curl de pierna', 'Equipo diseñado para aislar y fortalecer los isquiotibiales mediante un movimiento de flexión de rodilla.'),
('leg_curl_machine', 'en', 'Leg curl machine', 'Equipment designed to isolate and strengthen the hamstrings through a knee flexion movement.'),
('leg_curl_machine', 'pt', 'Máquina de cadeira flexora', 'Equipamento projetado para isolar e fortalecer os isquiotibiais através de um movimento de flexão do joelho.'),
('leg_curl_machine', 'fr', 'Machine à leg curl', 'Équipement conçu pour isoler et renforcer les ischio-jambiers par un mouvement de flexion du genou.'),
('leg_curl_machine', 'de', 'Beinbeuger-Maschine', 'Gerät zur Isolierung und Stärkung der Beinbeuger durch Kniebeugebewegungen.'),
('leg_curl_machine', 'it', 'Macchina per leg curl', 'Attrezzatura progettata per isolare e rinforzare gli ischiocrurali tramite un movimento di flessione del ginocchio.'),
('leg_curl_machine', 'zh', '腿弯举机', '旨在通过膝关节屈曲动作孤立并加强腘绳肌的器械。'),
('leg_curl_machine', 'ja', 'レッグカール・マシン', '膝の屈曲運動を通じてハムストリングスを孤立させ、強化するために設計された機器。'),
('leg_curl_machine', 'ko', '레그 컬 머신', '무릎 굽힘 동작을 통해 햄스트링을 고립시키고 강화하도록 설계된 장비입니다.'),
('leg_curl_machine', 'ar', 'جهاز تمرين الفخذ الخلفي (Leg curl)', 'جهاز مصمم لعزل وتقوية أوتار الركبة من خلال حركة ثني الركبة.'),
('leg_curl_machine', 'hi', 'लेग कर्ल मशीन', 'घुटने के फ्लेक्सियन मूवमेंट के माध्यम से हैमस्ट्रिंग को अलग करने और मजबूत करने के लिए डिज़ाइन किया गया उपकरण।'),
('leg_curl_machine', 'ru', 'Тренажер для сгибания ног', 'Тренажер, предназначенный для изоляции и укрепления бицепсов бедра с помощью сгибания коленей.'),
('leg_curl_machine', 'nl', 'Leg curl machine', 'Apparatuur ontworpen om de hamstrings te isoleren en te versterken door middel van een kniebuigbeweging.'),
('leg_curl_machine', 'sv', 'Leg curl-maskin', 'Utrustning utformad för att isolera och stärka hamstrings genom en knäböjningsrörelse.'),
('leg_curl_machine', 'pl', 'Maszyna do uginania nóg (Leg curl)', 'Urządzenie zaprojektowane do izolacji i wzmacniania mięśni dwugłowych uda poprzez ruch zginania kolan.'),
('leg_curl_machine', 'id', 'Mesin leg curl', 'Peralatan yang dirancang untuk mengisolasi dan memperkuat hamstring melalui gerakan fleksi lutut.'),
('leg_curl_machine', 'bn', 'লেগ কার্ল মেশিন', 'হাঁটুর ফ্লেকশন মুভমেন্টের মাধ্যমে হ্যামস্ট্রিং আলাদা করতে এবং শক্তিশালী করতে ডিজাইন করা সরঞ্জাম।'),
('leg_curl_machine', 'vi', 'Máy tập móc đùi sau (Leg curl)', 'Thiết bị được thiết kế để cô lập và tăng cường cơ đùi sau thông qua chuyển động gập gối.'),
('leg_curl_machine', 'fa', 'دستگاه پشت پا (Leg Curl)', 'تجهیزات طراحی شده برای ایزوله کردن و تقویت عضلات همسترینگ از طریق حرکت خم کردن زانو.');