INSERT INTO machines_info (slug, lang, title, "desc") VALUES
('mat', 'es', 'Esterilla (Mat)', 'Superficie acolchada diseñada para ejercicios de suelo, estiramientos, yoga y pilates.'),
('mat', 'en', 'Exercise mat', 'Cushioned surface designed for floor exercises, stretching, yoga, and pilates.'),
('mat', 'pt', 'Colchonete', 'Superfície acolchoada projetada para exercícios de solo, alongamento, ioga e pilates.'),
('mat', 'fr', 'Tapis de sol', 'Surface rembourrée conçue pour les exercices au sol, les étirements, le yoga et le pilates.'),
('mat', 'de', 'Gymnastikmatte', 'Gepolsterte Oberfläche für Bodenübungen, Dehnung, Yoga und Pilates.'),
('mat', 'it', 'Tappetino (Mat)', 'Superficie imbottita progettata per esercizi a terra, stretching, yoga e pilates.'),
('mat', 'zh', '瑜伽垫/地垫', '专为地面练习、伸展、瑜伽和普拉提设计的缓冲垫。'),
('mat', 'ja', 'マット', 'フロアエクササイズ、ストレッチ、ヨガ、ピラティス用に設計されたクッション性のある表面。'),
('mat', 'ko', '매트', '바닥 운동, 스트레칭, 요가 및 필라테스를 위해 설계된 쿠션감 있는 표면입니다.'),
('mat', 'ar', 'بساط رياضي (Mat)', 'سطح مبطن مصمم لتمارين الأرضية، والتمدد، واليوغا، والبيلاتس.'),
('mat', 'hi', 'मैट', 'फर्श के व्यायाम, स्ट्रेचिंग, योग और पिलेट्स के लिए डिज़ाइन की गई कुशन वाली सतह।'),
('mat', 'ru', 'Коврик для упражнений', 'Мягкая поверхность, предназначенная для упражнений на полу, растяжки, йоги и пилатеса.'),
('mat', 'nl', 'Mat', 'Gedempt oppervlak ontworpen voor grondoefeningen, stretchen, yoga en pilates.'),
('mat', 'sv', 'Träningsmatta', 'Dämpad yta utformad för golvövningar, stretchning, yoga och pilates.'),
('mat', 'pl', 'Mata do ćwiczeń', 'Amortyzowana powierzchnia zaprojektowana do ćwiczeń na podłodze, rozciągania, jogi i pilatesu.'),
('mat', 'id', 'Matras', 'Permukaan empuk yang dirancang untuk latihan lantai, peregangan, yoga, dan pilates.'),
('mat', 'bn', 'ম্যাট', 'ফ্লোর ব্যায়াম, স্ট্রেচিং, যোগব্যায়াম এবং পিলাটিসের জন্য ডিজাইন করা কুশনযুক্ত পৃষ্ঠ।'),
('mat', 'vi', 'Thảm tập', 'Bề mặt đệm được thiết kế cho các bài tập trên sàn, giãn cơ, yoga và pilates.'),
('mat', 'fa', 'مت (زیرانداز ورزشی)', 'سطح نرم طراحی شده برای تمرینات زمینی، کششی، یوگا و پیلاتس.');