INSERT OR IGNORE INTO machines_info (slug, lang, title, "desc") VALUES
('medicine_ball', 'es', 'Balón medicinal', 'Balón pesado utilizado para ejercicios de fuerza explosiva, rehabilitación y entrenamiento funcional.'),
('medicine_ball', 'en', 'Medicine ball', 'Weighted ball used for explosive strength, rehabilitation, and functional training exercises.'),
('medicine_ball', 'pt', 'Bola medicinal', 'Bola com peso usada para exercícios de força explosiva, reabilitação e treinamento funcional.'),
('medicine_ball', 'fr', 'Ballon lesté (Medicine ball)', 'Ballon lesté utilisé pour les exercices de force explosive, la rééducation et l entraînement fonctionnel.'),
('medicine_ball', 'de', 'Medizinball', 'Gewichteter Ball für Übungen zur Explosivkraft, Rehabilitation und funktionellem Training.'),
('medicine_ball', 'it', 'Palla medica', 'Palla zavorrata utilizzata per esercizi di forza esplosiva, riabilitazione e allenamento funzionale.'),
('medicine_ball', 'zh', '药球', '用于爆发力、康复和功能性训练练习的加重球。'),
('medicine_ball', 'ja', 'メディシンボール', '爆発的な筋力、リハビリテーション、ファンクショナル・トレーニングに使用される加重ボール。'),
('medicine_ball', 'ko', '메디신 볼', '폭발적인 근력, 재활 및 기능성 트레이닝 운동에 사용되는 무게가 있는 공입니다.'),
('medicine_ball', 'ar', 'كرة طبية (Medicine ball)', 'كرة ثقيلة تستخدم لتمارين القوة الانفجارية، وإعادة التأهيل، والتدريب الوظيفي.'),
('medicine_ball', 'hi', 'मेडिसिन बॉल', 'विस्फोटक शक्ति, पुनर्वास और कार्यात्मक प्रशिक्षण व्यायाम के लिए उपयोग की जाने वाली भारी गेंद।'),
('medicine_ball', 'ru', 'Медицинский мяч (Медбол)', 'Утяжеленный мяч, используемый для тренировки взрывной силы, реабилитации и функциональных упражнений.'),
('medicine_ball', 'nl', 'Medicine ball', 'Verzwaarde bal gebruikt voor explosieve kracht, revalidatie en functionele trainingsoefeningen.'),
('medicine_ball', 'sv', 'Medicinboll', 'Viktad boll som används för explosiv styrka, rehabilitering och funktionella träningsövningar.'),
('medicine_ball', 'pl', 'Piłka lekarska', 'Obciążona piłka używana do ćwiczeń siły eksplozywnej, rehabilitacji i treningu funkcjonalnego.'),
('medicine_ball', 'id', 'Medicine ball', 'Bola berbobot yang digunakan untuk latihan kekuatan eksplosif, rehabilitasi, dan pelatihan fungsional.'),
('medicine_ball', 'bn', 'মেডিসিন বল', 'বিস্ফোরক শক্তি, পুনর্বাসন এবং কার্যকরী প্রশিক্ষণের ব্যায়ামের জন্য ব্যবহৃত ওজনের বল।'),
('medicine_ball', 'vi', 'Bóng tập tạ (Medicine ball)', 'Bóng nặng được sử dụng cho các bài tập sức mạnh bùng nổ, phục hồi chức năng và tập luyện chức năng.'),
('medicine_ball', 'fa', 'مدیسین بال', 'توپ وزن‌دار استفاده شده برای تمرینات قدرت انفجاری، توان‌بخشی و تمرینات عملکردی.');