INSERT INTO machines_info (slug, lang, title, "desc") VALUES
('olympic_disc', 'es', 'Disco olímpico', 'Disco de peso estándar de 50mm diseñado para barras olímpicas, utilizado en levantamiento de pesas y entrenamiento de fuerza.'),
('olympic_disc', 'en', 'Olympic plate', '50mm standard weight plate designed for Olympic bars, used in weightlifting and strength training.'),
('olympic_disc', 'pt', 'Anilha olímpica', 'Disco de peso padrão de 50mm projetado para barras olímpicas, usado em levantamento de peso e treinamento de força.'),
('olympic_disc', 'fr', 'Disque olympique', 'Disque de poids standard de 50mm conçu pour les barres olympiques, utilisé en haltérophilie et musculation.'),
('olympic_disc', 'de', 'Olympische Hantelscheibe', '50mm Standard-Gewichtsscheibe für olympische Hantelstangen, verwendet im Gewichtheben und Krafttraining.'),
('olympic_disc', 'it', 'Disco olimpico', 'Disco di peso standard da 50mm progettato per bilancieri olimpici, utilizzato nel sollevamento pesi e nell allenamento della forza.'),
('olympic_disc', 'zh', '奥林匹克杠铃片', '专为奥林匹克杠铃设计的50mm标准配重片，用于举重和力量训练。'),
('olympic_disc', 'ja', 'オリンピック・プレート', 'オリンピック・バー用に設計された50mm標準ウェイトプレート。ウェイトリフティングや筋力トレーニングに使用。'),
('olympic_disc', 'ko', '올림픽 원판', '올림픽 바를 위해 설계된 50mm 표준 웨이트 플레이트로, 역도 및 근력 운동에 사용됩니다.'),
('olympic_disc', 'ar', 'قرص أولمبي (Olympic plate)', 'قرص وزن قياسي 50 مم مصمم للبارات الأولمبية، يستخدم في رفع الأثقال وتمارين القوة.'),
('olympic_disc', 'hi', 'ओलंपिक डिस्क', 'ओलंपिक बार के लिए डिज़ाइन की गई 50mm स्टैंडर्ड वेट प्लेट, जिसका उपयोग वेटलिफ्टिंग और स्ट्रेंथ ट्रेनिंग में किया जाता है।'),
('olympic_disc', 'ru', 'Олимпийский диск', 'Стандартный весовой диск 50 мм, предназначенный для олимпийских грифов, используется в тяжелой атлетике и силовых тренировках.'),
('olympic_disc', 'nl', 'Olympische schijf', '50mm standaard gewichtsschijf ontworpen voor olympische stangen, gebruikt bij gewichtheffen en krachttraining.'),
('olympic_disc', 'sv', 'Olympisk viktskiva', '50mm standard viktskiva designad för olympiska stänger, används vid tyngdlyftning och styrketräning.'),
('olympic_disc', 'pl', 'Talerz olimpijski', 'Standardowy talerz o średnicy 50mm zaprojektowany do sztang olimpijskich, używany w podnoszeniu ciężarów i treningu siłowym.'),
('olympic_disc', 'id', 'Piringan beban Olimpiade', 'Piringan beban standar 50mm yang dirancang untuk bar Olimpiade, digunakan dalam angkat besi dan latihan kekuatan.'),
('olympic_disc', 'bn', 'অলিম্পিক ডিস্ক', 'অলিম্পিক বারের জন্য ডিজাইন করা 50mm স্ট্যান্ডার্ড ওয়েট প্লেট, যা ওয়েটলিফটিং এবং শক্তি প্রশিক্ষণে ব্যবহৃত হয়।'),
('olympic_disc', 'vi', 'Bánh tạ Olympic', 'Bánh tạ tiêu chuẩn 50mm được thiết kế cho đòn Olympic, dùng trong cử tạ và tập luyện sức mạnh.'),
('olympic_disc', 'fa', 'صفحه هالتر المپیک', 'صفحه وزنه استاندارد ۵۰ میلی‌متری طراحی شده برای هالترهای المپیک، استفاده شده در وزنه‌برداری و تمرینات قدرتی.');