INSERT OR IGNORE INTO machines_info (slug, lang, title, "desc") VALUES
('olympic_bar', 'es', 'Barra olímpica', 'Barra de acero de alta resistencia diseñada para levantamiento de pesas olímpico y ejercicios de fuerza pesados.'),
('olympic_bar', 'en', 'Olympic bar', 'High-strength steel bar designed for Olympic weightlifting and heavy strength exercises.'),
('olympic_bar', 'pt', 'Barra olímpica', 'Barra de aço de alta resistência projetada para levantamento de peso olímpico e exercícios de força pesados.'),
('olympic_bar', 'fr', 'Barre olympique', 'Barre en acier haute résistance conçue pour l haltérophilie olympique et les exercices de force lourds.'),
('olympic_bar', 'de', 'Olympische Hantelstange', 'Hochfeste Stahlstange für olympisches Gewichtheben und schwere Kraftübungen.'),
('olympic_bar', 'it', 'Bilanciere olimpico', 'Bilanciere in acciaio ad alta resistenza progettato per il sollevamento pesi olimpico ed esercizi di forza pesanti.'),
('olympic_bar', 'zh', '奥林匹克杠铃', '专为奥林匹克举重和重型力量训练设计的高强度钢制杠铃。'),
('olympic_bar', 'ja', 'オリンピック・バー', 'オリンピックウェイトリフティングや高負荷の筋力トレーニング用に設計された高強度スチール製バー。'),
('olympic_bar', 'ko', '올림픽 바', '올림픽 역도 및 고중량 근력 운동을 위해 설계된 고강도 강철 바입니다.'),
('olympic_bar', 'ar', 'البار الأولمبي (Olympic bar)', 'بار من الصلب عالي القوة مصمم لتمارين رفع الأثقال الأولمبية وتمارين القوة الثقيلة.'),
('olympic_bar', 'hi', 'ओलंपिक बार', 'ओलंपिक वेटलिफ्टिंग और भारी शक्ति व्यायाम के लिए डिज़ाइन की गई उच्च-शक्ति वाली स्टील बार।'),
('olympic_bar', 'ru', 'Олимпийский гриф', 'Высокопрочный стальной гриф, разработанный для олимпийской тяжелой атлетики и силовых упражнений с большими весами.'),
('olympic_bar', 'nl', 'Olympische stang', 'Stalen stang met hoge sterkte, ontworpen voor olympisch gewichtheffen en zware krachttraining.'),
('olympic_bar', 'sv', 'Olympisk skivstång', 'Höghållfast stålstång designad för olympisk tyngdlyftning och tunga styrkeövningar.'),
('olympic_bar', 'pl', 'Sztanga olimpijska', 'Sztanga ze stali o wysokiej wytrzymałości, zaprojektowana do podnoszenia ciężarów i ciężkich ćwiczeń siłowych.'),
('olympic_bar', 'id', 'Olympic bar', 'Batang baja berkekuatan tinggi yang dirancang untuk angkat besi Olimpiade dan latihan kekuatan berat.'),
('olympic_bar', 'bn', 'অলিম্পিক বার', 'অলিম্পিক ওয়েটলিফ্টিং এবং ভারী শক্তির ব্যায়ামের জন্য ডিজাইন করা উচ্চ-শক্তির স্টিল বার।'),
('olympic_bar', 'vi', 'Thanh đòn Olympic', 'Thanh đòn thép cường độ cao được thiết kế cho cử tạ Olympic và các bài tập sức mạnh nặng.'),
('olympic_bar', 'fa', 'هالتر المپیک', 'میله فولادی با مقاومت بالا طراحی شده برای وزنه‌برداری المپیک و تمرینات قدرتی سنگین.');