INSERT OR IGNORE INTO machines_info (slug, lang, title, "desc") VALUES
('pec_deck_machine', 'es', 'Máquina pec deck (Contractora de pecho)', 'Máquina diseñada para aislar los músculos pectorales mediante un movimiento de aducción horizontal.'),
('pec_deck_machine', 'en', 'Pec deck machine', 'Machine designed to isolate the pectoral muscles through a horizontal adduction movement.'),
('pec_deck_machine', 'pt', 'Máquina Peck Deck', 'Máquina projetada para isolar os músculos peitorais através de um movimento de adução horizontal.'),
('pec_deck_machine', 'fr', 'Machine à pec deck', 'Machine conçue pour isoler les muscles pectoraux via un mouvement d adduction horizontale.'),
('pec_deck_machine', 'de', 'Pec-Deck-Maschine', 'Gerät zur Isolierung der Brustmuskulatur durch eine horizontale Adduktionsbewegung.'),
('pec_deck_machine', 'it', 'Pec deck', 'Macchina progettata per isolare i muscoli pettorali tramite un movimento di adduzione orizzontale.'),
('pec_deck_machine', 'zh', '蝴蝶机 (Pec Deck)', '设计用于通过水平内收动作孤立锻炼胸肌的器械。'),
('pec_deck_machine', 'ja', 'ペックデック・マシン', '水平内転運動を通じて胸筋を孤立させるために設計されたマシン。'),
('pec_deck_machine', 'ko', '펙 덱 머신', '수평 내전 동작을 통해 흉근을 고립시키도록 설계된 머신입니다.'),
('pec_deck_machine', 'ar', 'جهاز الفراشة للصدر (Pec deck)', 'جهاز مصمم لعزل عضلات الصدر من خلال حركة تقريب أفقية.'),
('pec_deck_machine', 'hi', 'पेक डेक मशीन', 'हॉरिजॉन्टल एडक्शन मूवमेंट के माध्यम से पेक्टोरल मांसपेशियों को अलग करने के लिए डिज़ाइन की गई मशीन।'),
('pec_deck_machine', 'ru', 'Тренажер «Бабочка» (Pec Deck)', 'Тренажер, предназначенный для изоляции грудных мышц с помощью горизонтального приведения.'),
('pec_deck_machine', 'nl', 'Pec deck machine', 'Machine ontworpen om de borstspieren te isoleren door middel van een horizontale adductiebeweging.'),
('pec_deck_machine', 'sv', 'Pec deck-maskin', 'Maskin utformad för att isolera bröstmusklerna genom en horisontell adduktionsrörelse.'),
('pec_deck_machine', 'pl', 'Maszyna typu butterfly (Pec deck)', 'Urządzenie zaprojektowane do izolacji mięśni klatki piersiowej poprzez ruch przywodzenia w poziomie.'),
('pec_deck_machine', 'id', 'Mesin pec deck', 'Mesin yang dirancang untuk mengisolasi otot dada melalui gerakan adduksi horizontal.'),
('pec_deck_machine', 'bn', 'পেক ডেক মেশিন', 'হরাইজন্টাল অ্যাডডাকশন মুভমেন্টের মাধ্যমে পেক্টোরাল পেশী আলাদা করার জন্য ডিজাইন করা মেশিন।'),
('pec_deck_machine', 'vi', 'Máy ép ngực (Pec deck)', 'Máy được thiết kế để cô lập cơ ngực thông qua chuyển động khép ngang.'),
('pec_deck_machine', 'fa', 'دستگاه قفسه سینه (Pec Deck)', 'دستگاه طراحی شده برای ایزوله کردن عضلات سینه از طریق حرکت دور کردن و نزدیک کردن افقی (آداکشن).');