INSERT INTO machines_info (slug, lang, title, "desc") VALUES
('plyo_box', 'es', 'Cajón pliométrico', 'Caja robusta diseñada para ejercicios de salto, explosividad y acondicionamiento físico.'),
('plyo_box', 'en', 'Plyo box', 'Sturdy box designed for jumping exercises, explosiveness, and physical conditioning.'),
('plyo_box', 'pt', 'Caixa pliométrica', 'Caixa robusta projetada para exercícios de salto, explosividade e condicionamento físico.'),
('plyo_box', 'fr', 'Boîte pliométrique (Plyo box)', 'Boîte robuste conçue pour les exercices de saut, l explosivité et le conditionnement physique.'),
('plyo_box', 'de', 'Plyo-Box', 'Robuste Box für Sprungübungen, Schnellkrafttraining und körperliche Konditionierung.'),
('plyo_box', 'it', 'Box pliometrico', 'Cassa robusta progettata per esercizi di salto, esplosività e condizionamento fisico.'),
('plyo_box', 'zh', '跳箱 (Plyo box)', '专为跳跃练习、爆发力训练和体能调节而设计的稳固箱体。'),
('plyo_box', 'ja', 'プライオボックス', 'ジャンプ運動、爆発力、身体コンディショニングのために設計された頑丈なボックス。'),
('plyo_box', 'ko', '플라이오 박스', '점프 운동, 순발력 및 신체 컨디셔닝을 위해 설계된 튼튼한 박스입니다.'),
('plyo_box', 'ar', 'صندوق القفز (Plyo box)', 'صندوق قوي مصمم لتمارين القفز، والقوة الانفجارية، واللياقة البدنية.'),
('plyo_box', 'hi', 'प्लाईओ बॉक्स', 'जंपिंग एक्सरसाइज, विस्फोटक शक्ति और शारीरिक कंडीशनिंग के लिए डिज़ाइन किया गया मजबूत बॉक्स।'),
('plyo_box', 'ru', 'Плиометрический бокс (Тумба)', 'Устойчивый ящик, предназначенный для прыжковых упражнений, тренировки взрывной силы и общей физической подготовки.'),
('plyo_box', 'nl', 'Plyo box', 'Stevige box ontworpen voor sprongoefeningen, explosiviteit en fysieke conditionering.'),
('plyo_box', 'sv', 'Plyobox', 'Robust låda utformad för hoppövningar, explosivitet och fysisk konditionsträning.'),
('plyo_box', 'pl', 'Skrzynia plyometryczna', 'Solidna skrzynia zaprojektowana do ćwiczeń skocznościowych, szybkościowych i ogólnorozwojowych.'),
('plyo_box', 'id', 'Plyo box', 'Kotak kokoh yang dirancang untuk latihan lompat, eksplosivitas, dan pengondisian fisik.'),
('plyo_box', 'bn', 'প্লাইও বক্স', 'জাম্পিং ব্যায়াম, বিস্ফোরক শক্তি এবং শারীরিক কন্ডিশনিংয়ের জন্য ডিজাইন করা মজবুত বক্স।'),
('plyo_box', 'vi', 'Hộp nhảy (Plyo box)', 'Hộp chắc chắn được thiết kế cho các bài tập nhảy, tăng sức mạnh bùng nổ và rèn luyện thể chất.'),
('plyo_box', 'fa', 'جعبه پلایومتریک (Plyo Box)', 'جعبه مستحکم طراحی شده برای تمرینات پرشی، قدرت انفجاری و آمادگی جسمانی.');