INSERT OR IGNORE INTO machines_info (slug, lang, title, "desc") VALUES
('power_rack', 'es', 'Jaula de potencia (Power rack)', 'Estructura metálica robusta para realizar ejercicios con barra de forma segura, incluyendo sentadillas y press.'),
('power_rack', 'en', 'Power rack', 'Sturdy metal structure for performing barbell exercises safely, including squats and presses.'),
('power_rack', 'pt', 'Gaiola de força (Power rack)', 'Estrutura metálica robusta para realizar exercícios com barra com segurança, incluindo agachamentos e supinos.'),
('power_rack', 'fr', 'Cage à squat (Power rack)', 'Structure métallique robuste pour effectuer des exercices avec barre en toute sécurité, y compris les squats et les développés.'),
('power_rack', 'de', 'Power Rack', 'Stabile Metallstruktur für sicheres Training mit der Langhantel, einschließlich Kniebeugen und Drückübungen.'),
('power_rack', 'it', 'Power rack', 'Struttura metallica robusta per eseguire esercizi con bilanciere in sicurezza, inclusi squat e spinte.'),
('power_rack', 'zh', '深蹲架 (Power rack)', '稳固的金属结构，用于安全地进行杠铃深蹲和推举练习。'),
('power_rack', 'ja', 'パワーラック', 'スクワットやプレスなどのバーベル種目を安全に行うための頑丈な金属製フレーム。'),
('power_rack', 'ko', '파워 랙', '스쿼트나 프레스 등 바벨 운동을 안전하게 수행할 수 있도록 설계된 튼튼한 금속 구조물입니다.'),
('power_rack', 'ar', 'قفص القرفصاء (Power rack)', 'هيكل معدني قوي لأداء تمارين البار بأمان، بما في ذلك القرفصاء والضغط.'),
('power_rack', 'hi', 'पावर रैक', 'स्क्वैट्स और प्रेसेस सहित बारबेल व्यायाम सुरक्षित रूप से करने के लिए मजबूत धातु संरचना।'),
('power_rack', 'ru', 'Силовая рама (Power rack)', 'Прочная металлическая конструкция для безопасного выполнения упражнений со штангой, включая приседания и жимы.'),
('power_rack', 'nl', 'Power rack', 'Stevige metalen structuur voor het veilig uitvoeren van oefeningen met een stang, inclusief squats en presses.'),
('power_rack', 'sv', 'Power rack', 'Robust metallstruktur för att utföra skivstångsövningar säkert, inklusive knäböj och pressar.'),
('power_rack', 'pl', 'Klatka do przysiadów (Power rack)', 'Solidna metalowa konstrukcja do bezpiecznego wykonywania ćwiczeń ze sztangą, w tym przysiadów i wyciskania.'),
('power_rack', 'id', 'Power rack', 'Struktur logam kokoh untuk melakukan latihan barbel dengan aman, termasuk squat dan press.'),
('power_rack', 'bn', 'পাওয়ার র্যাক', 'স্কোয়াট এবং প্রেস সহ বারবেল ব্যায়াম নিরাপদে করার জন্য মজবুত ধাতব কাঠামো।'),
('power_rack', 'vi', 'Khung gánh tạ (Power rack)', 'Cấu trúc kim loại chắc chắn để thực hiện các bài tập với thanh đòn một cách an toàn, bao gồm squat và đẩy tạ.'),
('power_rack', 'fa', 'پاور رک (قفسه قدرت)', 'سازه فلزی مستحکم برای اجرای ایمن تمرینات با هالتر، از جمله اسکات و پرس.');