INSERT INTO machines_info (slug, lang, title, "desc") VALUES
('pull_up_bar', 'es', 'Barra de dominadas', 'Barra fija elevada diseñada para ejercicios de tracción y fortalecimiento de espalda y brazos.'),
('pull_up_bar', 'en', 'Pull-up bar', 'Elevated fixed bar designed for pulling exercises and strengthening the back and arms.'),
('pull_up_bar', 'pt', 'Barra de elevação', 'Barra fixa elevada projetada para exercícios de tração e fortalecimento das costas e braços.'),
('pull_up_bar', 'fr', 'Barre de traction', 'Barre fixe surélevée conçue pour les exercices de traction et le renforcement du dos et des bras.'),
('pull_up_bar', 'de', 'Klimmzugstange', 'Erhöhte Feststange für Zugübungen und zur Stärkung von Rücken und Armen.'),
('pull_up_bar', 'it', 'Sbarra per trazioni', 'Sbarra fissa sopraelevata progettata per esercizi di trazione e per rinforzare schiena e braccia.'),
('pull_up_bar', 'zh', '引体向上杆', '专为拉力练习及背部和手臂肌肉强化而设计的固定高杠。'),
('pull_up_bar', 'ja', '懸垂バー', '背中や腕を鍛えるための懸垂運動用に設計された、高所に固定されたバー。'),
('pull_up_bar', 'ko', '풀업 바', '등과 팔을 강화하고 당기는 운동을 하기 위해 고안된 높게 고정된 바입니다.'),
('pull_up_bar', 'ar', 'عقلة (Pull-up bar)', 'بار ثابت مرتفع مصمم لتمارين السحب وتقوية الظهر والذراعين.'),
('pull_up_bar', 'hi', 'पुल-अप बार', 'ऊंचाई पर लगी फिक्स्ड बार जिसे पुलिंग एक्सरसाइज और पीठ व बाहों को मजबूत करने के लिए डिज़ाइन किया गया है।'),
('pull_up_bar', 'ru', 'Перекладина для подтягиваний', 'Закрепленная на высоте перекладина, предназначенная для упражнений на тягу и укрепления мышц спины и рук.'),
('pull_up_bar', 'nl', 'Pull-up bar', 'Verhoogde vaste stang ontworpen voor trekoefeningen en het versterken van de rug en armen.'),
('pull_up_bar', 'sv', 'Pull-up-stång', 'Upphöjd fast stång utformad för dragövningar och för att stärka rygg och armar.'),
('pull_up_bar', 'pl', 'Drążek do podciągania', 'Wysoko umieszczony drążek zaprojektowany do ćwiczeń podciągania oraz wzmacniania mięśni pleców i ramion.'),
('pull_up_bar', 'id', 'Pull-up bar', 'Batang tetap yang ditinggikan yang dirancang untuk latihan menarik dan memperkuat punggung dan lengan.'),
('pull_up_bar', 'bn', 'পুল-আপ বার', 'উঁচু ফিক্সড বার যা পুলিং ব্যায়াম এবং পিঠ ও বাহুর শক্তি বৃদ্ধির জন্য ডিজাইন করা হয়েছে।'),
('pull_up_bar', 'vi', 'Xà đơn (Pull-up bar)', 'Thanh cố định trên cao được thiết kế cho các bài tập kéo xà và tăng cường sức mạnh cơ lưng, tay.'),
('pull_up_bar', 'fa', 'میله بارفیکس', 'میله ثابت مرتفع طراحی شده برای تمرینات کششی و تقویت عضلات پشت و بازوها.');