INSERT INTO machines_info (slug, lang, title, "desc") VALUES
('resistance_bands', 'es', 'Bandas de resistencia', 'Bandas elásticas utilizadas para añadir resistencia progresiva en diversos ejercicios de fuerza.'),
('resistance_bands', 'en', 'Resistance bands', 'Elastic bands used to add progressive resistance to various strength exercises.'),
('resistance_bands', 'pt', 'Bandas de resistência', 'Bandas elásticas usadas para adicionar resistência progressiva em vários exercícios de força.'),
('resistance_bands', 'fr', 'Bandes de résistance', 'Bandes élastiques utilisées pour ajouter une résistance progressive à divers exercices de renforcement.'),
('resistance_bands', 'de', 'Widerstandsbänder', 'Elastische Bänder zur Erhöhung des progressiven Widerstands bei verschiedenen Kraftübungen.'),
('resistance_bands', 'it', 'Bande elastiche (Resistance bands)', 'Fasce elastiche utilizzate per aggiungere resistenza progressiva a vari esercizi di forza.'),
('resistance_bands', 'zh', '弹力带', '用于在各种力量训练中增加渐进式阻力的弹性带。'),
('resistance_bands', 'ja', 'レジスタンスバンド', '様々な筋力トレーニングに漸進的な負荷を加えるために使用されるゴムバンド。'),
('resistance_bands', 'ko', '저항 밴드', '다양한 근력 운동에 점진적인 저항을 더하기 위해 사용되는 탄성 밴드입니다.'),
('resistance_bands', 'ar', 'أربطة مقاومة (Resistance bands)', 'أربطة مرنة تستخدم لإضافة مقاومة تدريجية في تمارين القوة.'),
('resistance_bands', 'hi', 'रेजिस्टेंस बैंड्स', 'विभिन्न शक्ति व्यायामों में प्रगतिशील प्रतिरोध जोड़ने के लिए उपयोग किए जाने वाले इलास्टिक बैंड।'),
('resistance_bands', 'ru', 'Эспандеры (Резинки)', 'Эластичные ленты, используемые для создания прогрессивного сопротивления в различных силовых упражнениях.'),
('resistance_bands', 'nl', 'Weerstandsbanden', 'Elastische banden gebruikt om progressieve weerstand toe te voegen aan diverse krachttrainingsoefeningen.'),
('resistance_bands', 'sv', 'Motståndsband', 'Elastiska band som används för att lägga till progressivt motstånd i olika styrkeövningar.'),
('resistance_bands', 'pl', 'Taśmy oporowe', 'Elastyczne taśmy używane do dodawania progresywnego oporu w różnych ćwiczeniach siłowych.'),
('resistance_bands', 'id', 'Resistance bands', 'Pita elastis yang digunakan untuk menambahkan resistensi progresif pada berbagai latihan kekuatan.'),
('resistance_bands', 'bn', 'রেজিস্ট্যান্স ব্যান্ড', 'বিভিন্ন শক্তির ব্যায়ামে প্রগ্রেসিভ রেজিস্ট্যান্স যোগ করতে ব্যবহৃত ইলাস্টিক ব্যান্ড।'),
('resistance_bands', 'vi', 'Dây kháng lực', 'Dây đàn hồi được sử dụng để tạo lực cản tăng dần trong các bài tập sức mạnh.'),
('resistance_bands', 'fa', 'کش‌های بدنسازی (Resistance Bands)', 'باندهای الاستیک استفاده شده برای افزودن مقاومت پیش‌رونده در تمرینات مختلف قدرتی.');