INSERT OR IGNORE INTO machines_info (slug, lang, title, "desc") VALUES
('rowing_machine', 'es', 'Máquina de remo', 'Equipo que simula el movimiento de remo, trabajando todo el cuerpo con énfasis en la espalda y sistema cardiovascular.'),
('rowing_machine', 'en', 'Rowing machine', 'Equipment that simulates the rowing motion, working the whole body with an emphasis on back and cardiovascular system.'),
('rowing_machine', 'pt', 'Máquina de remo', 'Equipamento que simula o movimento de remo, trabalhando todo o corpo com ênfase nas costas e no sistema cardiovascular.'),
('rowing_machine', 'fr', 'Rameur', 'Équipement qui simule le mouvement de l aviron, travaillant tout le corps avec un accent sur le dos et le système cardiovasculaire.'),
('rowing_machine', 'de', 'Rudergerät', 'Gerät, das die Ruderbewegung simuliert und den ganzen Körper mit Schwerpunkt auf Rücken und Herz-Kreislauf-System trainiert.'),
('rowing_machine', 'it', 'Vogatore', 'Attrezzatura che simula il movimento del remo, allenando tutto il corpo con enfasi su schiena e sistema cardiovascolare.'),
('rowing_machine', 'zh', '划船机', '模拟划船动作的器械，锻炼全身，重点在于背部和心血管系统。'),
('rowing_machine', 'ja', 'ローイングマシン', 'ボート漕ぎの動作をシミュレートする器具で、背中と心肺機能に重点を置いて全身を鍛える。'),
('rowing_machine', 'ko', '로잉 머신', '조정 동작을 모방한 기구로, 등과 심혈관계에 중점을 두고 전신을 단련합니다.'),
('rowing_machine', 'ar', 'جهاز التجديف (Rowing machine)', 'جهاز يحاكي حركة التجديف، ويقوم بتمرين الجسم بالكامل مع التركيز على الظهر ونظام القلب والأوعية الدموية.'),
('rowing_machine', 'hi', 'रोइंग मशीन', 'रोइंग मूवमेंट को सिम्युलेट करने वाला उपकरण, जो पीठ और कार्डियोवैस्कुलर सिस्टम पर जोर देते हुए पूरे शरीर पर काम करता है।'),
('rowing_machine', 'ru', 'Гребной тренажер', 'Тренажер, имитирующий греблю, прорабатывает все тело с акцентом на спину и сердечно-сосудистую систему.'),
('rowing_machine', 'nl', 'Roeimachine', 'Apparatuur die de roeibeweging simuleert en het hele lichaam traint met de nadruk op de rug en het cardiovasculaire systeem.'),
('rowing_machine', 'sv', 'Roddmaskin', 'Utrustning som simulerar roddrörelsen och tränar hela kroppen med fokus på rygg och kardiovaskulärt system.'),
('rowing_machine', 'pl', 'Wioślarz (maszyna do wiosłowania)', 'Urządzenie symulujące ruch wiosłowania, angażujące całe ciało z naciskiem na plecy i układ sercowo-naczyniowy.'),
('rowing_machine', 'id', 'Mesin dayung', 'Peralatan yang mensimulasikan gerakan mendayung, melatih seluruh tubuh dengan penekanan pada punggung dan sistem kardiovaskular.'),
('rowing_machine', 'bn', 'রোয়িং মেশিন', 'রোয়িং মুভমেন্ট সিমুলেট করা সরঞ্জাম, যা পিঠ এবং কার্ডিওভাসকুলার সিস্টেমের উপর জোর দিয়ে পুরো শরীর কাজ করে।'),
('rowing_machine', 'vi', 'Máy chèo thuyền (Rowing machine)', 'Thiết bị mô phỏng chuyển động chèo thuyền, tập luyện toàn thân với trọng tâm là cơ lưng và hệ tim mạch.'),
('rowing_machine', 'fa', 'دستگاه روئینگ (قایقرانی)', 'تجهیزاتی که حرکت قایقرانی را شبیه‌سازی می‌کند و کل بدن را با تأکید بر پشت و سیستم قلبی-عروقی تقویت می‌کند.');