INSERT OR IGNORE INTO machines_info (slug, lang, title, "desc") VALUES
('seated_calf_raise', 'es', 'Máquina de elevación de talones sentado', 'Máquina diseñada para aislar y fortalecer los músculos sóleos de las pantorrillas mediante la flexión plantar sentado.'),
('seated_calf_raise', 'en', 'Seated calf raise', 'Machine designed to isolate and strengthen the calf soleus muscles through seated plantar flexion.'),
('seated_calf_raise', 'pt', 'Máquina de elevação de panturrilha sentado', 'Máquina projetada para isolar e fortalecer os músculos sóleos das panturrilhas através da flexão plantar sentada.'),
('seated_calf_raise', 'fr', 'Machine à mollets assis', 'Machine conçue pour isoler et renforcer les muscles soléaires des mollets par une flexion plantaire assise.'),
('seated_calf_raise', 'de', 'Sitzende Wadenmaschine', 'Gerät zur Isolierung und Stärkung der Wadenmuskulatur durch sitzende Plantarflexion.'),
('seated_calf_raise', 'it', 'Macchina per polpacci seduto', 'Macchina progettata per isolare e rinforzare i muscoli solei dei polpacci tramite flessione plantare da seduti.'),
('seated_calf_raise', 'zh', '坐姿提踵机', '专为通过坐姿跖屈动作孤立锻炼小腿比目鱼肌而设计的器械。'),
('seated_calf_raise', 'ja', 'シーテッド・カーフレイズ・マシン', '座った状態での底屈運動により、ふくらはぎのヒラメ筋を孤立させて鍛えるために設計されたマシン。'),
('seated_calf_raise', 'ko', '시티드 카프 레이즈 머신', '앉은 자세에서 발바닥 굽힘 동작을 통해 종아리의 가자미근을 고립시켜 강화하도록 설계된 머신입니다.'),
('seated_calf_raise', 'ar', 'جهاز تمرين السمانة جالساً (Seated calf raise)', 'جهاز مصمم لعزل وتقوية عضلات الساق (النعلية) من خلال حركة ثني أخمص القدم أثناء الجلوس.'),
('seated_calf_raise', 'hi', 'सीटेड काफ रेज मशीन', 'बैठकर प्लांटर फ्लेक्सियन के माध्यम से पिंडली की सोलियस मांसपेशियों को अलग करने और मजबूत करने के लिए डिज़ाइन की गई मशीन।'),
('seated_calf_raise', 'ru', 'Тренажер для подъема на носки сидя', 'Тренажер, предназначенный для изоляции и укрепления камбаловидных мышц голени с помощью сгибания стопы в положении сидя.'),
('seated_calf_raise', 'nl', 'Seated calf raise machine', 'Machine ontworpen om de kuitspieren te isoleren en te versterken door middel van zittende plantaire flexie.'),
('seated_calf_raise', 'sv', 'Sittande vadpress', 'Maskin utformad för att isolera och stärka vadmusklerna genom sittande plantarflektion.'),
('seated_calf_raise', 'pl', 'Maszyna do wspięć na palce siedząc', 'Urządzenie zaprojektowane do izolacji i wzmacniania mięśni płaszczkowatych łydek poprzez zgięcie podeszwowe w siadzie.'),
('seated_calf_raise', 'id', 'Mesin seated calf raise', 'Mesin yang dirancang untuk mengisolasi dan memperkuat otot betis melalui fleksi plantar dalam posisi duduk.'),
('seated_calf_raise', 'bn', 'সিটেড কাফ রেইজ মেশিন', 'বসে প্ল্যান্টার ফ্লেক্সিয়নের মাধ্যমে কাফের সোলিয়াস পেশী আলাদা এবং শক্তিশালী করার জন্য ডিজাইন করা মেশিন।'),
('seated_calf_raise', 'vi', 'Máy tập bắp chân ngồi (Seated calf raise)', 'Máy được thiết kế để cô lập và tăng cường cơ bắp chân thông qua động tác gập lòng bàn chân khi ngồi.'),
('seated_calf_raise', 'fa', 'دستگاه ساق پا نشسته', 'دستگاه طراحی شده برای ایزوله کردن و تقویت عضلات ساق پا (سولیوس) از طریق حرکت فلکشن کف پایی در حالت نشسته.');