INSERT INTO machines_info (slug, lang, title, "desc") VALUES
('shoulder_press_machine', 'es', 'Máquina de press de hombros', 'Equipo diseñado para el fortalecimiento de los deltoides mediante un movimiento de empuje vertical guiado.'),
('shoulder_press_machine', 'en', 'Shoulder press machine', 'Equipment designed for strengthening the deltoids through a guided vertical pushing movement.'),
('shoulder_press_machine', 'pt', 'Máquina de desenvolvimento de ombros', 'Equipamento projetado para o fortalecimento dos deltoides através de um movimento de empurrão vertical guiado.'),
('shoulder_press_machine', 'fr', 'Machine à développé épaules', 'Équipement conçu pour le renforcement des deltoïdes via un mouvement de poussée verticale guidé.'),
('shoulder_press_machine', 'de', 'Schulterpresse', 'Gerät zur Stärkung der Deltamuskeln durch eine geführte vertikale Druckbewegung.'),
('shoulder_press_machine', 'it', 'Macchina per shoulder press', 'Attrezzatura progettata per il rinforzo dei deltoidi tramite un movimento di spinta verticale guidato.'),
('shoulder_press_machine', 'zh', '肩部推举机', '旨在通过引导式垂直推举动作增强三角肌的器械。'),
('shoulder_press_machine', 'ja', 'ショルダープレス・マシン', 'ガイド付きの垂直押し出し運動により、三角筋を強化するために設計された器具。'),
('shoulder_press_machine', 'ko', '숄더 프레스 머신', '가이드가 있는 수직 밀기 동작을 통해 삼각근을 강화하도록 설계된 기구입니다.'),
('shoulder_press_machine', 'ar', 'جهاز ضغط الكتف (Shoulder press)', 'جهاز مصمم لتقوية عضلات الكتف (الدالية) من خلال حركة دفع عمودية موجهة.'),
('shoulder_press_machine', 'hi', 'शोल्डर प्रेस मशीन', 'गाइडेड वर्टिकल पुशिंग मूवमेंट के माध्यम से डेल्टोइड्स को मजबूत करने के लिए डिज़ाइन किया गया उपकरण।'),
('shoulder_press_machine', 'ru', 'Тренажер для жима плечами', 'Тренажер, предназначенный для укрепления дельтовидных мышц с помощью направленного вертикального жима.'),
('shoulder_press_machine', 'nl', 'Shoulder press machine', 'Apparatuur ontworpen voor het versterken van de deltaspieren door middel van een geleide verticale duwbeweging.'),
('shoulder_press_machine', 'sv', 'Axelpress-maskin', 'Utrustning utformad för att stärka axelmusklerna genom en guidad vertikal pressrörelse.'),
('shoulder_press_machine', 'pl', 'Maszyna do wyciskania na barki', 'Urządzenie zaprojektowane do wzmacniania mięśni naramiennych poprzez prowadzone wyciskanie pionowe.'),
('shoulder_press_machine', 'id', 'Mesin shoulder press', 'Peralatan yang dirancang untuk memperkuat otot bahu melalui gerakan menekan vertikal terpandu.'),
('shoulder_press_machine', 'bn', 'শোল্ডার প্রেস মেশিন', 'গাইডেড ভার্টিকাল পুশিং মুভমেন্টের মাধ্যমে ডেল্টয়েড শক্তিশালী করার জন্য ডিজাইন করা সরঞ্জাম।'),
('shoulder_press_machine', 'vi', 'Máy đẩy vai (Shoulder press)', 'Thiết bị được thiết kế để tăng cường sức mạnh cơ vai thông qua chuyển động đẩy dọc có dẫn hướng.'),
('shoulder_press_machine', 'fa', 'دستگاه پرس سرشانه', 'تجهیزات طراحی شده برای تقویت عضلات دلتوئید از طریق حرکت پرس عمودی هدایت‌شده.');