INSERT OR IGNORE INTO machines_info (slug, lang, title, "desc") VALUES
('smith_machine', 'es', 'Máquina Smith', 'Máquina de entrenamiento de fuerza con barra guiada, diseñada para ejercicios de presión y sentadillas con mayor estabilidad.'),
('smith_machine', 'en', 'Smith machine', 'Strength training machine with a guided barbell, designed for pressing and squatting exercises with increased stability.'),
('smith_machine', 'pt', 'Máquina Smith', 'Máquina de treinamento de força com barra guiada, projetada para exercícios de pressão e agachamento com maior estabilidade.'),
('smith_machine', 'fr', 'Machine Smith', 'Machine de musculation avec barre guidée, conçue pour les exercices de poussée et les squats avec une meilleure stabilité.'),
('smith_machine', 'de', 'Smith-Maschine', 'Krafttrainingsgerät mit geführter Langhantel, konzipiert für Druck- und Kniebeugeübungen mit erhöhter Stabilität.'),
('smith_machine', 'it', 'Smith machine', 'Macchina per l allenamento della forza con bilanciere guidato, progettata per esercizi di spinta e squat con maggiore stabilità.'),
('smith_machine', 'zh', '史密斯机', '带有引导式杠铃的力量训练器械，旨在以更高的稳定性进行推举和深蹲练习。'),
('smith_machine', 'ja', 'スミスマシン', 'ガイド付きバーベルを備えた筋力トレーニング用マシンで、安定性を高めてプレスやスクワットを行うために設計されている。'),
('smith_machine', 'ko', '스미스 머신', '안정성을 높여 프레스나 스쿼트 운동을 할 수 있도록 설계된 가이드 바벨이 있는 근력 운동 기구입니다.'),
('smith_machine', 'ar', 'جهاز سميث (Smith machine)', 'جهاز تدريب القوة مزود ببار موجه، مصمم لتمارين الضغط والقرفصاء مع ثبات أكبر.'),
('smith_machine', 'hi', 'स्मिथ मशीन', 'गाइडेड बारबेल के साथ स्ट्रेंथ ट्रेनिंग मशीन, जिसे अधिक स्थिरता के साथ प्रेस और स्क्वैट्स करने के लिए डिज़ाइन किया गया है।'),
('smith_machine', 'ru', 'Машина Смита', 'Тренажер для силовых тренировок с направляющей штангой, предназначенный для жимов и приседаний с повышенной устойчивостью.'),
('smith_machine', 'nl', 'Smith machine', 'Krachttrainingsapparaat met geleide stang, ontworpen voor druk- en squatoefeningen met verhoogde stabiliteit.'),
('smith_machine', 'sv', 'Smith-maskin', 'Styrketräningsmaskin med en guidad skivstång, utformad för press- och knäböjningsövningar med ökad stabilitet.'),
('smith_machine', 'pl', 'Maszyna Smitha (Suwnica Smitha)', 'Maszyna do treningu siłowego z prowadnicą sztangi, zaprojektowana do ćwiczeń wyciskania i przysiadów z większą stabilnością.'),
('smith_machine', 'id', 'Mesin Smith', 'Mesin latihan kekuatan dengan barbel terpandu, dirancang untuk latihan menekan dan squat dengan stabilitas yang lebih baik.'),
('smith_machine', 'bn', 'স্মিথ মেশিন', 'গাইডেড বারবেল সহ স্ট্রেন্থ ট্রেনিং মেশিন, যা অধিক স্থিতিশীলতার সাথে প্রেস এবং স্কোয়াট করার জন্য ডিজাইন করা হয়েছে।'),
('smith_machine', 'vi', 'Máy tập Smith', 'Máy tập sức mạnh với thanh đòn được dẫn hướng, thiết kế cho các bài tập đẩy và squat với độ ổn định cao hơn.'),
('smith_machine', 'fa', 'دستگاه اسمیت', 'دستگاه تمرینات قدرتی با هالتر هدایت‌شونده، طراحی شده برای تمرینات پرس و اسکات با ثبات بیشتر.');