INSERT OR IGNORE INTO machines_info (slug, lang, title, "desc") VALUES
('squat_rack', 'es', 'Soporte para sentadillas (Squat rack)', 'Estructura diseñada específicamente para sostener la barra durante ejercicios de sentadilla con seguridad.'),
('squat_rack', 'en', 'Squat rack', 'Structure specifically designed to hold the barbell during squat exercises safely.'),
('squat_rack', 'pt', 'Suporte para agachamento', 'Estrutura projetada especificamente para segurar a barra durante exercícios de agachamento com segurança.'),
('squat_rack', 'fr', 'Cage à squat', 'Structure spécifiquement conçue pour soutenir la barre lors des exercices de squat en toute sécurité.'),
('squat_rack', 'de', 'Kniebeugenständer (Squat Rack)', 'Struktur, die speziell dafür entwickelt wurde, die Langhantel während Kniebeugen sicher zu halten.'),
('squat_rack', 'it', 'Squat rack', 'Struttura progettata specificamente per sostenere il bilanciere durante gli esercizi di squat in sicurezza.'),
('squat_rack', 'zh', '深蹲架', '专门设计用于在深蹲练习中安全支撑杠铃的结构。'),
('squat_rack', 'ja', 'スクワットラック', 'スクワット種目中にバーベルを安全に保持するために特別に設計されたフレーム。'),
('squat_rack', 'ko', '스쿼트 랙', '스쿼트 운동 중 바벨을 안전하게 지지하도록 특별히 설계된 구조물입니다.'),
('squat_rack', 'ar', 'حامل القرفصاء (Squat rack)', 'هيكل مصمم خصيصاً لحمل البار أثناء تمارين القرفصاء بأمان.'),
('squat_rack', 'hi', 'स्क्वैट रैक', 'स्क्वैट एक्सरसाइज के दौरान बारबेल को सुरक्षित रूप से रखने के लिए विशेष रूप से डिज़ाइन की गई संरचना।'),
('squat_rack', 'ru', 'Стойка для приседаний', 'Конструкция, специально предназначенная для безопасного удержания штанги во время выполнения приседаний.'),
('squat_rack', 'nl', 'Squat rack', 'Structuur die specifiek is ontworpen om de stang veilig vast te houden tijdens squatoefeningen.'),
('squat_rack', 'sv', 'Squat rack', 'Struktur speciellt utformad för att hålla skivstången säkert under knäböjningsövningar.'),
('squat_rack', 'pl', 'Stojak do przysiadów', 'Konstrukcja zaprojektowana specjalnie do bezpiecznego trzymania sztangi podczas ćwiczeń przysiadów.'),
('squat_rack', 'id', 'Rak squat', 'Struktur yang dirancang khusus untuk menahan barbel selama latihan squat dengan aman.'),
('squat_rack', 'bn', 'স্কোয়াট র্যাক', 'স্কোয়াট অনুশীলনের সময় বারবেল নিরাপদে ধরে রাখার জন্য বিশেষভাবে ডিজাইন করা কাঠামো।'),
('squat_rack', 'vi', 'Giá đỡ tập squat', 'Cấu trúc được thiết kế đặc biệt để đỡ thanh đòn an toàn trong các bài tập squat.'),
('squat_rack', 'fa', 'رک اسکات', 'سازه طراحی شده به‌طور خاص برای نگهداری ایمن هالتر در طول تمرینات اسکات.');