INSERT OR IGNORE INTO machines_info (slug, lang, title, "desc") VALUES
('stair_climber', 'es', 'Máquina de escaleras', 'Equipo cardiovascular que simula subir escalones de forma continua para mejorar la resistencia y tonificar el tren inferior.'),
('stair_climber', 'en', 'Stair climber', 'Cardiovascular equipment that simulates climbing stairs continuously to improve endurance and tone the lower body.'),
('stair_climber', 'pt', 'Escada rolante de academia', 'Equipamento cardiovascular que simula subir escadas de forma contínua para melhorar a resistência e tonificar os membros inferiores.'),
('stair_climber', 'fr', 'Stair climber', 'Équipement cardio simulant la montée d escaliers en continu pour améliorer l endurance et tonifier le bas du corps.'),
('stair_climber', 'de', 'Treppensteiger', 'Herz-Kreislauf-Gerät, das kontinuierliches Treppensteigen simuliert, um die Ausdauer zu verbessern und den Unterkörper zu straffen.'),
('stair_climber', 'it', 'Stepper (Stair climber)', 'Attrezzatura cardiovascolare che simula la salita di gradini in modo continuo per migliorare la resistenza e tonificare gli arti inferiori.'),
('stair_climber', 'zh', '楼梯机', '模拟持续爬楼动作的有氧器械，旨在提高耐力并锻炼下半身。'),
('stair_climber', 'ja', 'ステアクライマー', '持久力を高め、下半身を引き締めるために継続的な階段昇降をシミュレートする有酸素運動器具。'),
('stair_climber', 'ko', '스텝밀 (천국의 계단)', '지구력을 향상시키고 하체를 단련하기 위해 지속적인 계단 오르기를 모방한 유산소 기구입니다.'),
('stair_climber', 'ar', 'جهاز صعود الدرج (Stair climber)', 'جهاز كارديو يحاكي صعود الدرج بشكل مستمر لتحسين التحمل وتنشيط الجزء السفلي من الجسم.'),
('stair_climber', 'hi', 'स्टेयर क्लाइंबर', 'कार्डियोवैस्कुलर उपकरण जो सहनशक्ति में सुधार और निचले शरीर को टोन करने के लिए लगातार सीढ़ियाँ चढ़ने का अनुकरण करता है।'),
('stair_climber', 'ru', 'Степпер (Тренажер-лестница)', 'Кардиотренажер, имитирующий непрерывный подъем по лестнице для улучшения выносливости и тонуса нижней части тела.'),
('stair_climber', 'nl', 'Stair climber', 'Cardio-apparatuur die continu traplopen simuleert om het uithoudingsvermogen te verbeteren en het onderlichaam te versterken.'),
('stair_climber', 'sv', 'Trappmaskin', 'Konditionsmaskin som simulerar kontinuerlig trappgång för att förbättra uthållighet och tona underkroppen.'),
('stair_climber', 'pl', 'Schody treningowe (Stair climber)', 'Sprzęt cardio symulujący ciągłe wchodzenie po schodach w celu poprawy wytrzymałości i wzmocnienia dolnych partii ciała.'),
('stair_climber', 'id', 'Mesin stair climber', 'Peralatan kardiovaskular yang mensimulasikan naik tangga terus-menerus untuk meningkatkan daya tahan dan mengencangkan tubuh bagian bawah.'),
('stair_climber', 'bn', 'স্টেয়ার ক্লাইম্বার', 'কার্ডিওভাসকুলার সরঞ্জাম যা ধৈর্য উন্নত করতে এবং শরীরের নিচের অংশ টোন করার জন্য ক্রমাগত সিঁড়ি বেয়ে ওঠার সিমুলেট করে।'),
('stair_climber', 'vi', 'Máy leo cầu thang (Stair climber)', 'Thiết bị cardio mô phỏng việc leo cầu thang liên tục để cải thiện sức bền và làm săn chắc cơ thể phần dưới.'),
('stair_climber', 'fa', 'دستگاه پله (Stair Climber)', 'تجهیزات قلبی-عروقی که بالا رفتن مداوم از پله را برای بهبود استقامت و فرم‌دهی پایین‌تنه شبیه‌سازی می‌کند.');