INSERT OR IGNORE INTO machines_info (slug, lang, title, "desc") VALUES
('stationary_bike', 'es', 'Bicicleta estática', 'Bicicleta fija diseñada para entrenamiento cardiovascular y fortalecimiento de piernas sin impacto articular.'),
('stationary_bike', 'en', 'Stationary bike', 'Fixed bike designed for cardiovascular training and leg strengthening with low joint impact.'),
('stationary_bike', 'pt', 'Bicicleta ergométrica', 'Bicicleta fixa projetada para treinamento cardiovascular e fortalecimento das pernas com baixo impacto articular.'),
('stationary_bike', 'fr', 'Vélo d appartement', 'Vélo fixe conçu pour l entraînement cardiovasculaire et le renforcement des jambes avec un faible impact articulaire.'),
('stationary_bike', 'de', 'Heimtrainer (Fahrrad)', 'Feststehendes Fahrrad für Herz-Kreislauf-Training und zur Stärkung der Beine bei geringer Gelenkbelastung.'),
('stationary_bike', 'it', 'Cyclette', 'Bicicletta fissa progettata per l allenamento cardiovascolare e il rafforzamento delle gambe con basso impatto articolare.'),
('stationary_bike', 'zh', '固定健身车', '专为有氧训练和腿部强化而设计的固定自行车，对关节冲击力小。'),
('stationary_bike', 'ja', 'エアロバイク', '関節への負担が少なく、有酸素運動や脚力強化のために設計された固定式自転車。'),
('stationary_bike', 'ko', '실내 자전거', '관절 충격이 적고 유산소 운동 및 하체 강화에 적합하게 설계된 고정식 자전거입니다.'),
('stationary_bike', 'ar', 'دراجة ثابتة', 'دراجة ثابتة مصممة لتدريب القلب والأوعية الدموية وتقوية الساقين مع تأثير منخفض على المفاصل.'),
('stationary_bike', 'hi', 'स्टेशनरी बाइक', 'कार्डियोवैस्कुलर ट्रेनिंग और कम जॉइंट इम्पैक्ट के साथ पैरों को मजबूत करने के लिए डिज़ाइन की गई फिक्स्ड बाइक।'),
('stationary_bike', 'ru', 'Велотренажер', 'Стационарный велосипед, предназначенный для кардиотренировок и укрепления ног с минимальной нагрузкой на суставы.'),
('stationary_bike', 'nl', 'Hometrainer', 'Vaste fiets ontworpen voor cardiotraining en beenspierversterking met lage gewrichtsbelasting.'),
('stationary_bike', 'sv', 'Träningscykel', 'Stationär cykel utformad för konditionsträning och benstyrka med låg belastning på lederna.'),
('stationary_bike', 'pl', 'Rower stacjonarny', 'Rower stacjonarny przeznaczony do treningu cardio i wzmacniania nóg przy niskim obciążeniu stawów.'),
('stationary_bike', 'id', 'Sepeda statis', 'Sepeda tetap yang dirancang untuk latihan kardiovaskular dan penguatan kaki dengan dampak sendi yang rendah.'),
('stationary_bike', 'bn', 'স্টেশনারি বাইক', 'কার্ডিওভাসকুলার ট্রেনিং এবং পায়ের শক্তি বাড়ানোর জন্য ডিজাইন করা ফিক্সড বাইক যা জয়েন্টে কম চাপ দেয়।'),
('stationary_bike', 'vi', 'Xe đạp tập thể dục (Stationary bike)', 'Xe đạp cố định được thiết kế cho việc tập luyện cardio và tăng cường sức mạnh chân với tác động khớp thấp.'),
('stationary_bike', 'fa', 'دوچرخه ثابت', 'دوچرخه ثابت طراحی شده برای تمرینات قلبی-عروقی و تقویت پاها با ضربه کم به مفاصل.');