INSERT INTO machines_info (slug, lang, title, "desc") VALUES
('treadmill', 'es', 'Cinta de correr (Treadmill)', 'Máquina de ejercicios cardiovascular que permite caminar, trotar o correr en un lugar fijo mediante una banda móvil.'),
('treadmill', 'en', 'Treadmill', 'Cardiovascular exercise machine that allows walking, jogging, or running in a fixed location using a moving belt.'),
('treadmill', 'pt', 'Esteira', 'Máquina de exercícios cardiovasculares que permite caminhar, trotar ou correr em um local fixo através de uma correia móvel.'),
('treadmill', 'fr', 'Tapis de course', 'Machine d exercice cardiovasculaire permettant de marcher, trottiner ou courir sur place grâce à une bande roulante.'),
('treadmill', 'de', 'Laufband', 'Herz-Kreislauf-Trainingsgerät, das Gehen, Joggen oder Laufen an einem festen Ort mittels eines beweglichen Bandes ermöglicht.'),
('treadmill', 'it', 'Tapis roulant', 'Macchina per esercizi cardiovascolari che consente di camminare, fare jogging o correre in un luogo fisso tramite un nastro mobile.'),
('treadmill', 'zh', '跑步机', '有氧运动器械，通过移动的履带实现在固定位置行走、慢跑或跑步。'),
('treadmill', 'ja', 'トレッドミル（ランニングマシン）', '動くベルトによって、その場でウォーキング、ジョギング、ランニングができる有酸素運動用マシン。'),
('treadmill', 'ko', '트레드밀 (런닝머신)', '움직이는 벨트를 사용하여 제자리에서 걷기, 조깅, 달리기 운동을 할 수 있는 유산소 기구입니다.'),
('treadmill', 'ar', 'جهاز المشي (Treadmill)', 'جهاز تمرين كارديو يسمح بالمشي أو الهرولة أو الجري في مكان ثابت باستخدام سير متحرك.'),
('treadmill', 'hi', 'ट्रेडमिल', 'कार्डियोवैस्कुलर एक्सरसाइज मशीन जो एक मूविंग बेल्ट के जरिए एक ही जगह पर चलने, जॉगिंग करने या दौड़ने की सुविधा देती है।'),
('treadmill', 'ru', 'Беговая дорожка', 'Кардиотренажер, позволяющий ходить, бегать трусцой или бегать на месте с помощью движущегося полотна.'),
('treadmill', 'nl', 'Loopband', 'Cardio-trainingsapparaat waarmee je op een vaste plek kunt wandelen, joggen of hardlopen met een bewegende band.'),
('treadmill', 'sv', 'Löpband', 'Konditionsmaskin som gör det möjligt att gå, jogga eller springa på en fast plats med hjälp av ett rörligt band.'),
('treadmill', 'pl', 'Bieżnia', 'Maszyna do ćwiczeń cardio, która umożliwia chodzenie, truchtanie lub bieganie w miejscu dzięki ruchomemu pasowi.'),
('treadmill', 'id', 'Treadmill', 'Mesin olahraga kardiovaskular yang memungkinkan berjalan, joging, atau berlari di tempat tetap menggunakan sabuk penggerak.'),
('treadmill', 'bn', 'ট্রেডমিল', 'কার্ডিওভাসকুলার এক্সারসাইজ মেশিন যা মুভিং বেল্টের মাধ্যমে স্থির অবস্থানে হাঁটা, জগিং বা দৌড়ানোর সুবিধা দেয়।'),
('treadmill', 'vi', 'Máy chạy bộ (Treadmill)', 'Máy tập cardio cho phép đi bộ, chạy bộ hoặc chạy tại chỗ nhờ băng chuyền chuyển động.'),
('treadmill', 'fa', 'تردمیل', 'دستگاه تمرینات قلبی-عروقی که امکان پیاده‌روی، دویدن آرام یا دویدن سریع را در یک مکان ثابت با استفاده از تسمه متحرک فراهم می‌کند.');