-- Definición del ejercicio y sus recursos
INSERT INTO exercises (slug, img, video, difficulty) 
VALUES ('ab-wheel-rollout', 'ab-wheel-rollout.jpg', 'ab-wheel-rollout.mp4', 'intermediate');

-- Relación: el ejercicio trabaja el grupo muscular 'abdominals'
INSERT INTO exercise_body_target (exercise_slug, body_target_slug) 
VALUES ('ab-wheel-rollout', 'abdominals');

-- Relación: el ejercicio utiliza la máquina 'ab-wheel'
INSERT INTO exercise_machine (exercise_slug, machine_slug) 
VALUES ('ab-wheel-rollout', 'ab-wheel');

-- Relación: alternativa al 'plank'
INSERT INTO exercise_alternative (exercise_slug, alternative_slug) 
VALUES ('ab-wheel-rollout', 'plank');

-- Información multiidioma del ejercicio
INSERT INTO exercises_info (slug, lang, title, description, benefits, instructions, tips, restrictions, mistakes) VALUES 
('ab-wheel-rollout', 'es', 'Ab wheel rollout', 'Ejercicio avanzado de anti-extensión que requiere una fuerte activación del core para estabilizar la columna.', 'Fortalece profundamente el recto abdominal y los oblicuos.\nMejora la estabilidad lumbopélvica.', 'Arrodíllate y sujeta la rueda con ambas manos.\nDeslízate hacia adelante controlando el movimiento sin arquear la espalda.\nRegresa a la posición inicial mediante la contracción abdominal.', 'Mantén la espalda neutra o ligeramente encorvada para evitar dolor lumbar.', 'Evitar si se tiene debilidad extrema en la zona lumbar.', 'Arquear la espalda durante el movimiento.\nUtilizar los brazos en lugar del abdomen para regresar.'),
('ab-wheel-rollout', 'en', 'Ab wheel rollout', 'Advanced anti-extension exercise requiring strong core activation to stabilize the spine.', 'Deeply strengthens the rectus abdominis and obliques.\nImproves lumbopelvic stability.', 'Kneel and hold the wheel with both hands.\nRoll forward controlling the movement without arching your back.\nReturn to the starting position by contracting the abdomen.', 'Keep your back neutral or slightly hunched to avoid lower back pain.', 'Avoid if you have extreme lower back weakness.', 'Arching the back during the movement.\nUsing arms instead of the abdomen to return.'),
('ab-wheel-rollout', 'pt', 'Ab wheel rollout', 'Exercício avançado de anti-extensão que requer uma forte ativação do core para estabilizar a coluna.', 'Fortalece profundamente o reto abdominal e os oblíquos.\nMelhora a estabilidade lombopélvica.', 'Ajoelhe-se e segure a roda com ambas as mãos.\nDeslize para a frente controlando o movimento sem arquear as costas.\nRegresse à posição inicial através da contração abdominal.', 'Mantenha as costas neutras ou ligeiramente curvadas para evitar dor lombar.', 'Evitar se tiver fraqueza extrema na zona lombar.', 'Arquear as costas durante o movimento.\nUsar os braços em vez do abdómen para regressar.'),
('ab-wheel-rollout', 'fr', 'Ab wheel rollout', 'Exercice avancé d''anti-extension nécessitant une forte activation du tronc pour stabiliser la colonne vertébrale.', 'Renforce profondément le grand droit de l''abdomen et les obliques.\nAméliore la stabilité lombo-pelvienne.', 'Mettez-vous à genoux et tenez la roue avec les deux mains.\nFaites rouler vers l''avant en contrôlant le mouvement sans cambrer le dos.\nRevenez à la position initiale par la contraction abdominale.', 'Gardez le dos neutre ou légèrement voûté pour éviter les douleurs lombaires.', 'À éviter en cas de faiblesse extrême du bas du dos.', 'Cambrer le dos pendant le mouvement.\nUtiliser les bras au lieu de l''abdomen pour revenir.'),
('ab-wheel-rollout', 'de', 'Ab wheel rollout', 'Fortgeschrittene Anti-Extensionsübung, die eine starke Rumpfaktivierung zur Stabilisierung der Wirbelsäule erfordert.', 'Stärkt tiefgreifend den geraden Bauchmuskel und die schrägen Bauchmuskeln.\nVerbessert die lumbopelvine Stabilität.', 'Knien Sie sich hin und halten Sie das Rad mit beiden Händen.\nRollten Sie nach vorne, während Sie die Bewegung kontrollieren, ohne den Rücken durchzustrecken.\nKehren Sie durch Bauchkontraktion in die Ausgangsposition zurück.', 'Halten Sie den Rücken neutral oder leicht gekrümmt, um Rückenschmerzen zu vermeiden.', 'Bei extremer Schwäche im Lendenbereich vermeiden.', 'Durchstrecken des Rückens während der Bewegung.\nVerwendung der Arme anstelle des Bauches für die Rückkehr.'),
('ab-wheel-rollout', 'it', 'Ab wheel rollout', 'Esercizio avanzato di anti-estensione che richiede una forte attivazione del core per stabilizzare la colonna vertebrale.', 'Rinforza profondamente il retto addominale e gli obliqui.\nMigliora la stabilità lombo-pelvica.', 'Inginocchiati e tieni la ruota con entrambe le mani.\nScivola in avanti controllando il movimento senza inarcare la schiena.\nTorna alla posizione iniziale attraverso la contrrazione addominale.', 'Mantieni la schiena neutra o leggermente curva per evitare dolori lombari.', 'Evitare in caso di estrema debolezza nella zona lombare.', 'Inarcare la schiena durante il movimento.\nUsare le braccia invece dell''addome per tornare.'),
('ab-wheel-rollout', 'zh', '腹肌轮滚轮', '高级抗伸展运动，需要强大的核心激活来稳定脊柱。', '深度增强腹直肌和斜肌。\n提高腰骨盆稳定性。', '跪下并用双手握住轮子。\n向前滑动控制动作，不要拱起背部。\n通过腹部收缩回到起始位置。', '保持背部中立或微弯，以避免腰痛。', '腰部极度虚弱者禁用。', '动作中拱背。\n用手臂代替腹部返回。'),
('ab-wheel-rollout', 'ja', '腹筋ローラー', '脊柱を安定させるために強力な体幹の活性化を必要とする高度な抗伸展エクササイズ。', '腹直筋と腹斜筋を深く強化します。\n腰椎骨盤の安定性を向上させます。', '膝をつき、両手でローラーを持ちます。\n背中を反らさずに動きをコントロールしながら前方に転がします。\n腹部を収縮させて開始位置に戻ります。', '腰痛を避けるため、背中は中立またはわずかに丸めた状態を保ちます。', '腰部に極度の弱さがある場合は避けてください。', '動作中に背中を反らすこと。\n腹部ではなく腕を使って戻ること。'),
('ab-wheel-rollout', 'ko', '복근 롤러', '척추를 안정시키기 위해 강력한 코어 활성화가 필요한 고급 항신전 운동.', '복직근과 복사근을 깊게 강화합니다.\n요추 골반 안정성을 향상시킵니다.', '무릎을 꿇고 양손으로 휠을 잡습니다.\n등을 젖히지 않고 동작을 제어하면서 앞으로 굴립니다.\n복부를 수축하여 시작 위치로 돌아옵니다.', '요통을 방지하기 위해 등을 중립 또는 약간 굽힌 상태로 유지합니다.', '허리 부위에 극도의 약점이 있는 경우 피하십시오.', '동작 중 등을 젖히는 것.\n복부 대신 팔을 사용하여 돌아오는 것.'),
('ab-wheel-rollout', 'ar', 'تمرين عجلة البطن', 'تمرين متقدم لمقاومة التمدد يتطلب تفعيلًا قويًا للعمود الفقري لتثبيت الجذع.', 'يقوي عضلة البطن المستقيمة والعضلات المائلة بعمق.\nيحسن استقرار منطقة أسفل الظهر والحوض.', 'ارکع وأمسك العجلة بكلتا يديك.\nتحرك للأمام مع التحكم في الحركة دون تقوس ظهرك.\nعد إلى وضع البداية عن طريق انقباض عضلات البطن.', 'حافظ على ظهرك في وضع محايد أو مقوس قليلًا لتجنب آلام أسفل الظهر.', 'تجنب التمرين إذا كان هناك ضعف شديد في منطقة أسفل الظهر.', 'تقوس الظهر أثناء الحركة.\nاستخدام الذراعين بدلًا من البطن للعودة.'),
('ab-wheel-rollout', 'hi', 'एब व्हील रोलआउट', 'उन्नत एंटी-एक्सटेंशन व्यायाम जिसे रीढ़ की हड्डी को स्थिर करने के लिए मजबूत कोर सक्रियण की आवश्यकता होती है।', 'रेक्टस एब्डोमिनिस और ओब्लिक को गहराई से मजबूत करता है।\nलंबोपेलविक स्थिरता में सुधार करता है।', 'घुटने टेकें और दोनों हाथों से व्हील पकड़ें।\nअपनी पीठ को मोड़े बिना गति को नियंत्रित करते हुए आगे बढ़ें।\nपेट के संकुचन द्वारा शुरुआती स्थिति में लौटें।', 'पीठ दर्द से बचने के लिए अपनी पीठ को न्यूट्रल या थोड़ा झुका हुआ रखें।', 'यदि निचले हिस्से में अत्यधिक कमजोरी है तो न करें।', 'गति के दौरान पीठ मोड़ना।\nवापस आने के लिए पेट के बजाय भुजाओं का उपयोग करना.'),
('ab-wheel-rollout', 'ru', 'Ролик для пресса', 'Продвинутое упражнение на анти-разгибание, требующее сильной активации кора для стабилизации позвоночника.', 'Глубоко укрепляет прямую мышцу живота и косые мышцы.\nУлучшает пояснично-тазовую стабильность.', 'Встаньте на колени и возьмите ролик обеими руками.\nКатитесь вперед, контролируя движение, не прогибая спину.\nВернитесь в исходное положение за счет сокращения мышц живота.', 'Держите спину ровной или слегка округленной, чтобы избежать болей в пояснице.', 'Избегайте при сильной слабости в пояснице.', 'Прогиб в спине во время движения.\nИспользование рук вместо мышц живота для возврата.'),
('ab-wheel-rollout', 'nl', 'Ab wheel rollout', 'Geavanceerde anti-extensie-oefening die sterke core-activatie vereist om de wervelkolom te stabiliseren.', 'Versterkt de rechte buikspier en schuine buikspieren diep.\nVerbetert lumbopelvische stabiliteit.', 'Zit op de knieën en houd het wiel met beide handen vast.\nRol naar voren terwijl je de beweging controleert zonder je rug te hol trekken.\nKeer terug naar de startpositie door de buikspieren aan te spannen.', 'Houd je rug neutraal of licht gebogen om rugpijn te voorkomen.', 'Vermijden bij extreme zwakte in de onderrug.', 'De rug hol trekken tijdens de beweging.\nDe armen gebruiken in plaats van de buikspieren om terug te keren.'),
('ab-wheel-rollout', 'sv', 'Ab wheel rollout', 'Avancerad anti-extensionsövning som kräver stark core-aktivering för att stabilisera ryggraden.', 'Stärker raka bukmusklerna och de sneda magmusklerna på djupet.\nFörbättrar lumbopelvic stabilitet.', 'Gå ner på knä och håll hjulet med båda händerna.\nRulla framåt och kontrollera rörelsen utan att svanka.\nÅtergå till startpositionen genom att spänna magmusklerna.', 'Håll ryggen neutral eller lätt rundad för att undvika ländryggssmärta.', 'Undvik vid extrem svaghet i ländryggen.', 'Att svanka under rörelsen.\nAnvända armarna istället för magen för att återgå.'),
('ab-wheel-rollout', 'pl', 'Ab wheel rollout', 'Zaawansowane ćwiczenie anty-wyprostu, wymagające silnej aktywacji core w celu stabilizacji kręgosłupa.', 'Głęboko wzmacnia mięsień prosty brzucha i mięśnie skośne.\nPoprawia stabilność lędźwiowo-miedniczną.', 'Uklęknij i trzymaj kółko oburącz.\nPrzetaczaj się do przodu, kontrolując ruch bez wyginania pleców.\nWróć do pozycji wyjściowej poprzez napięcie mięśni brzucha.', 'Utrzymuj plecy w pozycji neutralnej lub lekko zaokrąglonej, aby uniknąć bólu lędźwi.', 'Unikaj w przypadku ekstremalnej słabości lędźwi.', 'Wyginanie pleców podczas ruchu.\nUżywanie ramion zamiast brzucha do powrotu.'),
('ab-wheel-rollout', 'id', 'Ab wheel rollout', 'Latihan anti-ekstensi lanjutan yang memerlukan aktivasi inti yang kuat untuk menstabilkan tulang belakang.', 'Memperkuat rektus abdominis dan otot miring secara mendalam.\nMeningkatkan stabilitas lumbopelvic.', 'Berlutut dan pegang roda dengan kedua tangan.\nBergulir ke depan sambil mengontrol gerakan tanpa melengkungkan punggung.\nKembali ke posisi awal melalui kontraksi perut.', 'Jaga punggung tetap netral atau sedikit bungkuk untuk menghindari sakit punggung bawah.', 'Hindari jika ada kelemahan ekstrem di punggung bawah.', 'Melengkungkan punggung selama gerakan.\nMenggunakan lengan alih-alih perut untuk kembali.'),
('ab-wheel-rollout', 'bn', 'অ্যাব-হুইল রোলআউট', 'উন্নত অ্যান্টি-এক্সটেনশন ব্যায়াম যার জন্য মেরুদণ্ড স্থিতিশীল করতে শক্তিশালী কোর সক্রিয়করণ প্রয়োজন।', 'রেকটাস অ্যাবডোমিনিস এবং ওবলি কগুলোকে গভীরভাবে শক্তিশালী করে।\nলাম্বোপেলভিক স্থিতিশীলতা উন্নত করে।', 'হাঁটু গেড়ে বসুন এবং উভয় হাতে চাকাটি ধরুন।\nপিঠ না বাঁকিয়ে গতি নিয়ন্ত্রণ করে সামনের দিকে রোল করুন।\nপেটের সংকোচনের মাধ্যমে শুরুতে ফিরে আসুন।', 'পিঠের ব্যথা এড়াতে আপনার পিঠ নিউট্রাল বা কিছুটা বাঁকানো রাখুন।', 'নিচের পিঠে চরম দুর্বলতা থাকলে এড়িয়ে চলুন।', 'গতির সময় পিঠ বাঁকানো।\nফেরার জন্য পেটের পরিবর্তে বাহু ব্যবহার করা.'),
('ab-wheel-rollout', 'vi', 'Ab wheel rollout', 'Bài tập chống duỗi nâng cao đòi hỏi kích hoạt cơ lõi mạnh mẽ để ổn định cột sống.', 'Tăng cường sức mạnh cơ bụng thẳng và cơ chéo sâu.\nCải thiện sự ổn định vùng lưng chậu.', 'Quỳ xuống và cầm con lăn bằng cả hai tay.\nLăn về phía trước, kiểm soát chuyển động mà không làm võng lưng.\nTrở lại vị trí ban đầu bằng cách gồng bụng.', 'Giữ lưng thẳng hoặc hơi cong để tránh đau lưng dưới.', 'Tránh tập nếu bị yếu lưng dưới nghiêm trọng.', 'Võng lưng trong khi tập.\nDùng cánh tay thay vì cơ bụng để kéo về.'),
('ab-wheel-rollout', 'fa', 'چرخ شکم (Ab wheel rollout)', 'تمرین پیشرفته ضد کشش که برای تثبیت ستون فقرات به فعال‌سازی قوی هسته نیاز دارد.', 'عضله راست شکم و عضلات مایل را عمیقاً تقویت می‌کند.\nثبات کمری لگنی را بهبود می‌بخشد.', 'زانو بزنید و چرخ را با هر دو دست بگیرید.\nبدون قوس دادن به کمر، حرکت را کنترل کرده و به جلو بغلتانید.\nبا منقبض کردن عضلات شکم به وضعیت شروع بازگردید.', 'برای جلوگیری از کمردرد، پشت خود را خنثی یا کمی خمیده نگه دارید.', 'در صورت ضعف شدید در ناحیه کمر از انجام آن خودداری کنید.', 'قوس دادن به کمر در حین حرکت.\nاستفاده از بازوها به جای شکم برای بازگشت.');