-- Definición del ejercicio y sus recursos
INSERT OR IGNORE INTO exercises (slug, img, video, difficulty) 
VALUES ('alternate-leg-pull', 'alternate-leg-pull.jpg', 'alternate-leg-pull.mp4', 'intermediate');

-- Relación: el ejercicio trabaja el grupo muscular 'abdominals'
INSERT OR IGNORE INTO exercise_body_target (exercise_slug, body_target_slug) 
VALUES ('alternate-leg-pull', 'abdominals');

-- Relación: no requiere máquina, por lo tanto no se inserta en exercise_machine
INSERT OR IGNORE INTO exercise_alternative (exercise_slug, alternative_slug) 
VALUES ('alternate-leg-pull', 'plank');

-- Información multiidioma del ejercicio
INSERT OR IGNORE INTO exercises_info (slug, lang, title, description, benefits, instructions, tips, restrictions, mistakes) VALUES 
('alternate-leg-pull', 'es', 'Tracción alterna de piernas', 'Ejercicio de control core en posición de plancha, enfocado en la estabilidad dinámica.', 'Fortalece el abdomen, los glúteos y mejora la estabilidad de los hombros.', 'En posición de plancha alta, lleva una rodilla hacia el pecho sin mover la cadera.\nRegresa la pierna y alterna con la otra.', 'Mantén el abdomen contraído firmemente durante todo el movimiento.', 'Evitar si hay dolor agudo en la zona lumbar o muñecas.', 'Mover la cadera de lado a lado o arquear la espalda.'),
('alternate-leg-pull', 'en', 'Alternate leg pull', 'Core control exercise in a plank position, focused on dynamic stability.', 'Strengthens the abdomen, glutes, and improves shoulder stability.', 'In a high plank position, bring one knee towards the chest without moving the hips.\nReturn the leg and alternate with the other.', 'Keep your abdomen firmly contracted throughout the movement.', 'Avoid if there is acute lower back or wrist pain.', 'Moving the hips side to side or arching the back.'),
('alternate-leg-pull', 'pt', 'Tração alternada de pernas', 'Exercício de controle de core na posição de prancha, focado na estabilidade dinâmica.', 'Fortalece o abdómen, os glúteos e melhora a estabilidade dos ombros.', 'Na posição de prancha alta, leve um joelho em direção ao peito sem mover a anca.\nRegresse a perna e alterne com a outra.', 'Mantenha o abdómen contraído firmemente durante todo o movimento.', 'Evitar se houver dor aguda na zona lombar ou nos pulsos.', 'Mover a anca de lado a lado ou arquear as costas.'),
('alternate-leg-pull', 'fr', 'Traction alternée des jambes', 'Exercice de contrôle du tronc en position de planche, axé sur la stabilité dynamique.', 'Renforce l''abdomen, les fessiers et améliore la stabilité des épaules.', 'En position de planche haute, amenez un genou vers la poitrine sans bouger les hanches.\nRamenez la jambe et alternez avec l''autre.', 'Gardez l''abdomen fermement contracté pendant tout le mouvement.', 'À éviter en cas de douleur aiguë au bas du dos ou aux poignets.', 'Bouger les hanches de gauche à droite ou cambrer le dos.'),
('alternate-leg-pull', 'de', 'Abwechselndes Beinanziehen', 'Rumpfkontrollübung in der Plankenposition, fokussiert auf dynamische Stabilität.', 'Stärkt den Bauch, das Gesäß und verbessert die Schulterstabilität.', 'Bringen Sie in der hohen Plankenposition ein Knie in Richtung Brust, ohne die Hüfte zu bewegen.\nFühren Sie das Bein zurück und wechseln Sie mit dem anderen.', 'Halten Sie den Bauch während der gesamten Bewegung fest angespannt.', 'Bei akuten Schmerzen im unteren Rücken oder Handgelenken vermeiden.', 'Hüfte seitlich bewegen oder den Rücken durchstrecken.'),
('alternate-leg-pull', 'it', 'Trazione alternata delle gambe', 'Esercizio di controllo del core in posizione di plank, focalizzato sulla stabilità dinamica.', 'Rinforza l''addome, i glutei e migliora la stabilità delle spalle.', 'In posizione di plank alto, porta un ginocchio verso il petto senza muovere i fianchi.\nRiporta la gamba e alterna con l''altra.', 'Mantieni l''addome fermamente contratto durante tutto il movimento.', 'Evitare in caso di dolore acuto alla zona lombare o ai polsi.', 'Muovere i fianchi da un lato all''altro o inarcare la schiena.'),
('alternate-leg-pull', 'zh', '交替腿部牵引', '平板支撑位置的核心控制练习，专注于动态稳定性。', '增强腹部、臀部并提高肩部稳定性。', '在高位平板支撑中，将一只膝盖带向胸部，不要移动臀部。\n将腿放回并与另一侧交替。', '在整个动作过程中保持腹部紧绷。', '如有下背部或手腕剧痛，请避免使用。', '左右移动臀部或拱背。'),
('alternate-leg-pull', 'ja', '交互レッグプル', '動的な安定性に焦点を当てた、プランク姿勢での体幹コントロールエクササイズ。', '腹部と臀部を強化し、肩の安定性を向上させます。', 'ハイプランクの姿勢から、腰を動かさずに片膝を胸に近づけます。\n脚を戻し、反対側と交互に行います。', '動作中、腹部にしっかりと力を入れ続けます。', '腰や手首に激しい痛みがある場合は避けてください。', '腰を左右に振る、または背中を反らすこと。'),
('alternate-leg-pull', 'ko', '교대 다리 당기기', '동적 안정성에 초점을 맞춘 플랭크 자세에서의 코어 컨트롤 운동.', '복부와 둔근을 강화하고 어깨 안정성을 향상시킵니다.', '하이 플랭크 자세에서 골반을 움직이지 않고 무릎을 가슴 쪽으로 당깁니다.\n다리를 원래 위치로 되돌리고 반대쪽 다리로 수행합니다.', '동작 내내 복부에 단단히 힘을 주세요.', '허리나 손목에 급성 통증이 있으면 피하세요.', '골반을 좌우로 흔들거나 등을 젖히는 것.'),
('alternate-leg-pull', 'ar', 'سحب الساق بالتبادل', 'تمرين للتحكم في الجذع في وضع البلانك، يركز على الاستقرار الديناميكي.', 'يقوي البطن والأرداف ويحسن استقرار الكتفين.', 'في وضع البلانك العالي، اجلب ركبة واحدة نحو الصدر دون تحريك الوركين.\nأعد الساق وبدل مع الأخرى.', 'حافظ على شد عضلات البطن بقوة طوال الحركة.', 'تجنب التمرين في حالة وجود ألم حاد في أسفل الظهر أو المعصم.', 'تحريك الوركين من جانب إلى آخر أو تقوس الظهر.'),
('alternate-leg-pull', 'hi', 'अल्टरनेट लेग पुल', 'प्लैंक स्थिति में कोर कंट्रोल व्यायाम, जो गतिशील स्थिरता पर केंद्रित है।', 'पेट और ग्लूट्स को मजबूत करता है और कंधे की स्थिरता में सुधार करता है।', 'हाई प्लैंक स्थिति में, कूल्हों को हिलाए बिना एक घुटने को छाती की ओर लाएं।\nपैर को वापस लाएं और दूसरे के साथ बदलें।', 'पूरी गति के दौरान अपने पेट को मजबूती से सिकोड़ कर रखें।', 'यदि पीठ के निचले हिस्से या कलाई में तीव्र दर्द हो तो न करें।', 'कूल्हों को एक तरफ से दूसरी तरफ ले जाना या पीठ मोड़ना।'),
('alternate-leg-pull', 'ru', 'Попеременная тяга ног', 'Упражнение на контроль кора в планке, сфокусированное на динамической стабильности.', 'Укрепляет мышцы живота, ягодицы и улучшает стабильность плеч.', 'В положении высокой планки подтяните одно колено к груди, не двигая тазом.\nВерните ногу и повторите другой.', 'Держите мышцы живота напряженными на протяжении всего движения.', 'Избегайте при острой боли в пояснице или запястьях.', 'Раскачивание тазом или прогиб в спине.'),
('alternate-leg-pull', 'nl', 'Afwisselende leg pull', 'Core-controleoefening in plankpositie, gericht op dynamische stabiliteit.', 'Versterkt de buikspieren, billen en verbetert schouderstabiliteit.', 'Breng in hoge plankpositie één knie naar de borst zonder je heupen te bewegen.\nBreng het been terug en wissel af met de andere.', 'Houd je buikspieren stevig aangespannen tijdens de hele beweging.', 'Vermijden bij acute pijn in de onderrug of polsen.', 'Heupen zijwaarts bewegen of de rug hol trekken.'),
('alternate-leg-pull', 'sv', 'Växelvis benlyft/drag', 'Core-kontrollövning i plankposition med fokus på dynamisk stabilitet.', 'Stärker magmusklerna, sätet och förbättrar axelstabiliteten.', 'I en hög plankposition, dra ett knä mot bröstet utan att flytta höfterna.\nFör tillbaka benet och växla med det andra.', 'Håll magmusklerna ordentligt spända under hela rörelsen.', 'Undvik vid akut smärta i ländryggen eller handlederna.', 'Att röra höfterna från sida till sida eller svanka.'),
('alternate-leg-pull', 'pl', 'Naprzemienne przyciąganie kolan', 'Ćwiczenie kontroli core w pozycji deski, skupione na stabilności dynamicznej.', 'Wzmacnia brzuch, pośladki i poprawia stabilność barków.', 'W pozycji wysokiej deski przyciągnij kolano do klatki piersiowej, nie ruszając biodrami.\nOdłóż nogę i zmień stronę.', 'Utrzymuj brzuch mocno napięty przez cały czas trwania ruchu.', 'Unikaj w przypadku ostrego bólu lędźwi lub nadgarstków.', 'Poruszanie biodrami na boki lub wyginanie pleców.'),
('alternate-leg-pull', 'id', 'Tarik kaki bergantian', 'Latihan kontrol inti dalam posisi plank, berfokus pada stabilitas dinamis.', 'Memperkuat perut, bokong, dan meningkatkan stabilitas bahu.', 'Dalam posisi plank tinggi, bawa satu lutut ke arah dada tanpa menggerakkan pinggul.\nKembalikan kaki dan bergantian dengan kaki lainnya.', 'Jaga otot perut tetap berkontraksi dengan kuat selama gerakan.', 'Hindari jika ada nyeri pergelangan tangan atau punggung bawah yang akut.', 'Menggerakkan pinggul dari sisi ke sisi atau melengkungkan punggung.'),
('alternate-leg-pull', 'bn', 'অল্টারনেটিং লেগ পুল', 'প্ল্যাঙ্ক পজিশনে কোর কন্ট্রোল ব্যায়াম, ডায়নামিক স্থিতিশীলতার উপর দৃষ্টি নিবদ্ধ করে।', 'পেট এবং গ্লুটসকে শক্তিশালী করে এবং কাঁধের স্থিতিশীলতা উন্নত করে।', 'হাই প্ল্যাঙ্ক পজিশনে, নিতম্ব না নড়িয়ে একটি হাঁটু বুকের দিকে আনুন।\nপা ফিরিয়ে দিন এবং অন্যটির সাথে পরিবর্তন করুন।', 'পুরো নড়াচড়ার সময় আপনার পেট শক্ত করে রাখুন।', 'নিচের পিঠে বা কব্জিতে তীব্র ব্যথা থাকলে এড়িয়ে চলুন।', 'নিতম্ব এদিক-ওদিক সরানো বা পিঠ বাঁকানো।'),
('alternate-leg-pull', 'vi', 'Kéo chân luân phiên', 'Bài tập kiểm soát cơ lõi ở tư thế plank, tập trung vào sự ổn định động.', 'Tăng cường cơ bụng, cơ mông và cải thiện sự ổn định của vai.', 'Ở tư thế plank cao, đưa một đầu gối về phía ngực mà không di chuyển hông.\nĐưa chân về và đổi bên.', 'Giữ cơ bụng gồng chặt trong suốt quá trình tập.', 'Tránh tập nếu bị đau lưng dưới hoặc cổ tay cấp tính.', 'Lắc hông hoặc võng lưng.'),
('alternate-leg-pull', 'fa', 'سحب پا متناوب (Alternate leg pull)', 'تمرین کنترل هسته در وضعیت پلانک، متمرکز بر ثبات دینامیکی.', 'شکم و باسن را تقویت می‌کند و ثبات شانه‌ها را بهبود می‌بخشد.', 'در وضعیت پلانک بالا، یک زانو را بدون حرکت دادن لگن به سمت سینه بیاورید.\nپا را برگردانید و با پای دیگر انجام دهید.', 'در طول حرکت عضلات شکم را محکم منقبض نگه دارید.', 'در صورت درد حاد در کمر یا مچ دست از انجام آن خودداری کنید.', 'تکان دادن لگن به طرفین یا قوس دادن به کمر.');