-- Definición del ejercicio y sus recursos
INSERT OR IGNORE INTO exercises (slug, img, video, difficulty) 
VALUES ('alternate-arm-leg-plank', 'alternate-arm-leg-plank.jpg', 'alternate-arm-leg-plank.mp4', 'intermediate');

-- Relación: el ejercicio trabaja el grupo muscular 'abdominals'
INSERT OR IGNORE INTO exercise_body_target (exercise_slug, body_target_slug) 
VALUES ('alternate-arm-leg-plank', 'abdominals');

-- Relación: no requiere máquina, por lo tanto no se inserta en exercise_machine
INSERT OR IGNORE INTO exercise_alternative (exercise_slug, alternative_slug) 
VALUES ('alternate-arm-leg-plank', 'plank');

-- Información multiidioma del ejercicio
INSERT OR IGNORE INTO exercises_info (slug, lang, title, description, benefits, instructions, tips, restrictions, mistakes) VALUES 
('alternate-arm-leg-plank', 'es', 'Plancha con elevación alterna de brazo y pierna', 'Variación avanzada de la plancha que desafía el equilibrio y la estabilidad anti-rotacional.', 'Mejora la estabilidad del core y la coordinación neuromuscular.', 'Comienza en posición de plancha frontal.\nEleva simultáneamente el brazo derecho y la pierna izquierda sin inclinar la cadera.\nMantén por un segundo y cambia de lado.', 'Mantén la mirada hacia el suelo para alinear la columna cervical.', 'Evitar si se pierde el equilibrio o hay inestabilidad en la espalda baja.', 'Rotar la cadera al elevar los miembros.\nLevantar demasiado rápido sin control.'),
('alternate-arm-leg-plank', 'en', 'Alternate arm and leg plank', 'Advanced plank variation that challenges balance and anti-rotational stability.', 'Improves core stability and neuromuscular coordination.', 'Start in a front plank position.\nSimultaneously lift your right arm and left leg without tilting your hips.\nHold for a second and switch sides.', 'Keep your gaze towards the floor to align the cervical spine.', 'Avoid if you lose balance or have lower back instability.', 'Rotating the hips while lifting the limbs.\nLifting too quickly without control.'),
('alternate-arm-leg-plank', 'pt', 'Prancha com elevação alternada de braço e perna', 'Variação avançada da prancha que desafia o equilíbrio e a estabilidade anti-rotacional.', 'Melhora a estabilidade do core e a coordenação neuromuscular.', 'Comece na posição de prancha frontal.\nEleve simultaneamente o braço direito e a perna esquerda sem inclinar a anca.\nMantenha por um segundo e troque de lado.', 'Mantenha o olhar para o chão para alinhar a coluna cervical.', 'Evitar se perder o equilíbrio ou tiver instabilidade lombar.', 'Rodar a anca ao elevar os membros.\nLevantar demasiado rápido sem controlo.'),
('alternate-arm-leg-plank', 'fr', 'Planche avec levée alternée de bras et jambe', 'Variante avancée de la planche qui défie l''équilibre et la stabilité anti-rotationnelle.', 'Améliore la stabilité du tronc et la coordination neuromusculaire.', 'Commencez en position de planche frontale.\nLevez simultanément le bras droit et la jambe gauche sans incliner les hanches.\nMaintenez une seconde et changez de côté.', 'Gardez le regard vers le sol pour aligner la colonne cervicale.', 'À éviter en cas de perte d''équilibre ou d''instabilité du bas du dos.', 'Rotation des hanches lors de l''élévation des membres.\nSoulever trop rapidement sans contrôle.'),
('alternate-arm-leg-plank', 'de', 'Planke mit abwechselndem Arm- und Beinhub', 'Fortgeschrittene Plankenvariante, die das Gleichgewicht und die Anti-Rotations-Stabilität herausfordert.', 'Verbessert die Rumpfstabilität und neuromuskuläre Koordination.', 'Beginnen Sie in der Frontplankenposition.\nHeben Sie gleichzeitig den rechten Arm und das linke Bein, ohne die Hüfte zu neigen.\nHalten Sie eine Sekunde und wechseln Sie die Seite.', 'Halten Sie den Blick zum Boden, um die Halswirbelsäule auszurichten.', 'Vermeiden Sie es, wenn Sie das Gleichgewicht verlieren oder Instabilität im unteren Rücken haben.', 'Rotation der Hüfte beim Anheben der Gliedmaßen.\nZu schnelles Anheben ohne Kontrolle.'),
('alternate-arm-leg-plank', 'it', 'Plank con sollevamento alternato di braccio e gamba', 'Variante avanzata del plank che sfida l''equilibrio e la stabilità anti-rotazionale.', 'Migliora la stabilità del core e la coordinazione neuromuscolare.', 'Inizia in posizione di plank frontale.\nSolleva contemporaneamente il braccio destro e la gamba sinistra senza inclinare i fianchi.\nMantieni per un secondo e cambia lato.', 'Mantieni lo sguardo verso il pavimento per allineare la colonna cervicale.', 'Evitare se si perde l''equilibrio o in caso di instabilità lombare.', 'Ruotare i fianchi durante il sollevamento degli arti.\nSollevare troppo velocemente senza controllo.'),
('alternate-arm-leg-plank', 'zh', '平板支撑手臂与腿交替抬起', '平板支撑的高级变化，挑战平衡和抗旋转稳定性。', '提高核心稳定性和神经肌肉协调性。', '从前平板支撑姿势开始。\n同时抬起右臂和左腿，不要倾斜臀部。\n保持一秒钟并换边。', '保持视线朝向地板以对齐颈椎。', '如果失去平衡或下背部不稳定，请避免使用。', '抬起肢体时旋转臀部。\n抬起过快且失去控制。'),
('alternate-arm-leg-plank', 'ja', 'プランク：腕と脚の交互上げ', 'バランスと抗回旋安定性を高める高度なプランクバリエーション。', '体幹の安定性と神経筋の協調性を向上させます。', 'フロントプランクの姿勢から始めます。\n腰を傾けずに、右腕と左脚を同時に上げます。\n1秒間保持し、反対側に切り替えます。', '頚椎を揃えるため、視線は床に向けます。', 'バランスを崩す場合や腰部に不安がある場合は避けてください。', '脚や腕を上げる際に腰が回転すること。\nコントロールを失った速すぎる動作。'),
('alternate-arm-leg-plank', 'ko', '플랭크 팔 다리 교대 들어올리기', '균형 감각과 회전 방지 안정성을 향상시키는 고급 플랭크 변형.', '코어 안정성 및 신경근 협응력 향상.', '하이 플랭크 자세에서 시작합니다.\n골반이 기울어지지 않게 오른팔과 왼 다리를 동시에 들어 올립니다.\n1초 유지 후 반대쪽으로 수행합니다.', '목뼈 정렬을 위해 시선은 바닥을 향하세요.', '균형을 잃거나 허리에 불안정이 있으면 피하세요.', '사지를 들어 올릴 때 골반을 회전하는 것.\n통제 없이 너무 빠르게 들어 올리는 것.'),
('alternate-arm-leg-plank', 'ar', 'تمرين بلانك مع رفع الذراع والساق بالتبادل', 'تنويع متقدم لتمرين البلانك يتحدى التوازن والاستقرار ضد الدوران.', 'تحسين استقرار الجذع والتنسيق العصبي العضلي.', 'ابدأ في وضع البلانك الأمامي.\nارفع الذراع الأيمن والساق الأيسر في وقت واحد دون إمالة الوركين.\nحافظ على الوضع لثانية واحدة ثم بدل الجانب.', 'حافظ على نظرك نحو الأرض لمحاذاة العمود الفقري العنقي.', 'تجنب التمرين إذا فقدت توازنك أو كان لديك عدم استقرار في أسفل الظهر.', 'تدوير الوركين عند رفع الأطراف.\nالرفع بسرعة كبيرة وبدون تحكم.'),
('alternate-arm-leg-plank', 'hi', 'प्लैंक के साथ आर्म और लेग अल्टरनेट लिफ्ट', 'प्लैंक का एक उन्नत प्रकार जो संतुलन और एंटी-रोटेशनल स्थिरता को चुनौती देता है।', 'कोर स्थिरता और न्यूरोमस्कुलर समन्वय में सुधार करता है।', 'फ्रंट प्लैंक स्थिति में शुरू करें।\nकूल्हों को झुकाए बिना एक ही समय में दाहिने हाथ और बाएं पैर को उठाएं।\nएक सेकंड के लिए रुकें और दूसरी तरफ बदलें।', 'गर्दन की हड्डी को संरेखित करने के लिए फर्श की ओर देखें।', 'यदि संतुलन खो दें या पीठ के निचले हिस्से में अस्थिरता हो तो न करें।', 'अंगों को उठाते समय कूल्हों को घुमाना।\nबिना नियंत्रण के बहुत तेजी से उठाना.'),
('alternate-arm-leg-plank', 'ru', 'Планка с попеременным подъемом руки и ноги', 'Продвинутая вариация планки, развивающая баланс и антиротационную стабильность.', 'Улучшает стабильность кора и нервно-мышечную координацию.', 'Примите положение планки на предплечьях или кистях.\nОдновременно поднимите правую руку и левую ногу, не наклоняя таз.\nЗадержитесь на секунду и смените сторону.', 'Смотрите в пол для выравнивания шейного отдела позвоночника.', 'Избегайте, если теряете равновесие или есть нестабильность в пояснице.', 'Вращение тазом при подъеме конечностей.\nСлишком быстрое выполнение без контроля.'),
('alternate-arm-leg-plank', 'nl', 'Plank met afwisselende arm- en beenlift', 'Geavanceerde plankvariatie die balans en anti-rotatiestabiliteit uitdaagt.', 'Verbetert core-stabiliteit en neuromusculaire coördinatie.', 'Begin in de voorwaartse plankpositie.\nTil tegelijkertijd je rechterarm en linkerbeen op zonder je heupen te kantelen.\nHoud een seconde vast en wissel van kant.', 'Houd je blik op de grond om de nekwervels uit te lijnen.', 'Vermijden bij evenwichtsverlies of instabiliteit in de onderrug.', 'De heupen roteren bij het optillen van de ledematen.\nTe snel optillen zonder controle.'),
('alternate-arm-leg-plank', 'sv', 'Planka med växelvis arm- och benlyft', 'Avancerad plankvariation som utmanar balansen och stabiliteten.', 'Förbättrar core-stabilitet och neuromuskulär koordination.', 'Börja i en framåtlutad plankposition.\nLyft samtidigt höger arm och vänster ben utan att luta höfterna.\nHåll i en sekund och byt sida.', 'Håll blicken i golvet för att hålla nacken rak.', 'Undvik vid dålig balans eller instabilitet i ländryggen.', 'Rotera höfterna när du lyfter lemmarna.\nLyfta för snabbt utan kontroll.'),
('alternate-arm-leg-plank', 'pl', 'Plank z naprzemiennym unoszeniem ręki i nogi', 'Zaawansowana odmiana deski, która rzuca wyzwanie równowadze i stabilności anty-rotacyjnej.', 'Poprawia stabilność core i koordynację nerwowo-mięśniową.', 'Zacznij w pozycji deski przodem.\nJednocześnie unieś prawą rękę i lewą nogę bez przechylania bioder.\nWytrzymaj sekundę i zmień stronę.', 'Utrzymuj wzrok skierowany w podłogę, aby ustawić kręgosłup szyjny w jednej linii.', 'Unikaj w przypadku utraty równowagi lub niestabilności lędźwi.', 'Rotacja bioder podczas unoszenia kończyn.\nZbyt szybkie podnoszenie bez kontroli.'),
('alternate-arm-leg-plank', 'id', 'Plank dengan angkatan lengan dan kaki bergantian', 'Variasi plank tingkat lanjut yang menantang keseimbangan dan stabilitas anti-rotasi.', 'Meningkatkan stabilitas inti dan koordinasi neuromuskular.', 'Mulai dalam posisi plank depan.\nAngkat lengan kanan dan kaki kiri secara bersamaan tanpa memiringkan pinggul.\nTahan selama satu detik dan ganti sisi.', 'Jaga pandangan ke lantai untuk menyelaraskan tulang belakang leher.', 'Hindari jika Anda kehilangan keseimbangan atau memiliki ketidakstabilan punggung bawah.', 'Memutar pinggul saat mengangkat anggota tubuh.\nMengangkat terlalu cepat tanpa kendali.'),
('alternate-arm-leg-plank', 'bn', 'প্ল্যাঙ্ক উইথ অল্টারনেটিং আর্ম অ্যান্ড লেগ লিফট', 'প্ল্যাঙ্কের একটি উন্নত সংস্করণ যা ভারসাম্য এবং অ্যান্টি-রোটেশনাল স্থিতিশীলতাকে চ্যালেঞ্জ করে।', 'কোর স্থিতিশীলতা এবং নিউরোমাসকুলার সমন্বয় উন্নত করে।', 'ফ্রন্ট প্ল্যাঙ্ক পজিশনে শুরু করুন।\nনিতম্ব না বাঁকিয়ে একই সাথে ডান হাত এবং বাম পা তুলুন।\nএক সেকেন্ড ধরে রাখুন এবং দিক পরিবর্তন করুন।', 'ঘাড়ের হাড় সোজা রাখার জন্য মেঝেতে তাকান।', 'ভারসাম্য হারিয়ে ফেললে বা পিঠের নিচের অংশে অস্থিরতা থাকলে এটি এড়িয়ে চলুন।', 'অঙ্গ প্রত্যঙ্গ তোলার সময় নিতম্ব ঘোরানো।\nনিয়ন্ত্রণ ছাড়া খুব দ্রুত তোলা।'),
('alternate-arm-leg-plank', 'vi', 'Plank nâng tay và chân luân phiên', 'Biến thể nâng cao của plank thách thức sự cân bằng và ổn định xoay.', 'Cải thiện sự ổn định cơ lõi và phối hợp thần kinh cơ.', 'Bắt đầu ở tư thế plank trước.\nĐồng thời nâng tay phải và chân trái lên mà không làm nghiêng hông.\nGiữ trong một giây và đổi bên.', 'Giữ ánh nhìn xuống sàn để giữ thẳng cột sống cổ.', 'Tránh tập nếu bị mất thăng bằng hoặc bất ổn ở lưng dưới.', 'Xoay hông khi nhấc chi.\nNâng quá nhanh mà không kiểm soát.'),
('alternate-arm-leg-plank', 'fa', 'پلانک با بالا آوردن متناوب دست و پا', 'نسخه پیشرفته پلانک که تعادل و ثبات ضد چرخش را به چالش می‌کشد.', 'بهبود ثبات هسته و هماهنگی عصبی عضلانی.', 'در وضعیت پلانک از جلو شروع کنید.\nهمزمان دست راست و پای چپ را بدون کج کردن لگن بلند کنید.\nیک ثانیه نگه دارید و جهت را عوض کنید.', 'برای تراز کردن ستون فقرات گردنی، نگاه خود را به سمت زمین نگه دارید.', 'در صورت از دست دادن تعادل یا بی‌ثباتی در کمر، از انجام آن خودداری کنید.', 'چرخش لگن هنگام بلند کردن اندام‌ها.\nبلند کردن خیلی سریع و بدون کنترل.');