-- Definición del ejercicio y sus recursos
INSERT INTO exercises (slug, img, video, difficulty) 
VALUES ('alternate-leg-raises', 'alternate-leg-raises.jpg', 'alternate-leg-raises.mp4', 'beginner');

-- Relación: el ejercicio trabaja el grupo muscular 'abdominals'
INSERT INTO exercise_body_target (exercise_slug, body_target_slug) 
VALUES ('alternate-leg-raises', 'abdominals');

-- Relación: no requiere máquina, por lo tanto no se inserta en exercise_machine
INSERT INTO exercise_alternative (exercise_slug, alternative_slug) 
VALUES ('alternate-leg-raises', 'leg-raises');

-- Información multiidioma del ejercicio
INSERT INTO exercises_info (slug, lang, title, description, benefits, instructions, tips, restrictions, mistakes) VALUES 
('alternate-leg-raises', 'es', 'Elevación alterna de piernas', 'Ejercicio básico enfocado en la parte inferior del recto abdominal manteniendo la espalda estable.', 'Fortalece la zona abdominal baja y mejora el control pélvico.', 'Recuéstate boca arriba, manos bajo los glúteos.\nEleva una pierna estirada mientras la otra permanece cerca del suelo.\nAlterna el movimiento controlando el descenso.', 'Mantén la zona lumbar siempre pegada al suelo durante toda la ejecución.', 'Evitar si hay dolor agudo en la zona lumbar.', 'Arquear la espalda al bajar la pierna.\nRealizar el movimiento con impulso.'),
('alternate-leg-raises', 'en', 'Alternate leg raises', 'Basic exercise focusing on the lower rectus abdominis while keeping the back stable.', 'Strengthens the lower abdominal area and improves pelvic control.', 'Lie on your back, hands under your glutes.\nRaise one straight leg while the other remains near the floor.\nAlternate the movement, controlling the descent.', 'Keep your lower back pressed against the floor throughout the execution.', 'Avoid if there is acute lower back pain.', 'Arching the back when lowering the leg.\nPerforming the movement with momentum.'),
('alternate-leg-raises', 'pt', 'Elevação alternada de pernas', 'Exercício básico focado na parte inferior do reto abdominal, mantendo as costas estáveis.', 'Fortalece a zona abdominal inferior e melhora o controlo pélvico.', 'Deite-se de costas, mãos sob os glúteos.\nEleve uma perna esticada enquanto a outra permanece perto do chão.\nAlterne o movimento controlando a descida.', 'Mantenha a zona lombar sempre colada ao chão durante toda a execução.', 'Evitar se houver dor aguda na zona lombar.', 'Arquear as costas ao baixar a perna.\nRealizar o movimento com impulso.'),
('alternate-leg-raises', 'fr', 'Levée alternée des jambes', 'Exercice de base axé sur la partie inférieure du grand droit de l''abdomen tout en gardant le dos stable.', 'Renforce la zone abdominale inférieure et améliore le contrôle pelvien.', 'Allongez-vous sur le dos, mains sous les fessiers.\nLevez une jambe tendue tandis que l''autre reste près du sol.\nAlternez le mouvement en contrôlant la descente.', 'Gardez le bas du dos plaqué au sol pendant toute l''exécution.', 'À éviter en cas de douleur aiguë au bas du dos.', 'Cambrer le dos en baissant la jambe.\nEffectuer le mouvement avec élan.'),
('alternate-leg-raises', 'de', 'Abwechselndes Beinheben', 'Grundübung mit Fokus auf den unteren geraden Bauchmuskel bei stabiler Rückenlage.', 'Stärkt den unteren Bauchbereich und verbessert die Beckenkontrolle.', 'Legen Sie sich auf den Rücken, Hände unter das Gesäß.\nHeben Sie ein gestrecktes Bein an, während das andere in Bodennähe bleibt.\nWechseln Sie die Bewegung und kontrollieren Sie das Absenken.', 'Halten Sie den unteren Rücken während der gesamten Ausführung auf dem Boden.', 'Bei akuten Schmerzen im unteren Rücken vermeiden.', 'Durchstrecken des Rückens beim Absenken des Beins.\nAusführen der Bewegung mit Schwung.'),
('alternate-leg-raises', 'it', 'Sollevamento alternato delle gambe', 'Esercizio base focalizzato sulla parte inferiore del retto addominale mantenendo la schiena stabile.', 'Rinforza la zona addominale bassa e migliora il controllo pelvico.', 'Sdraiati sulla schiena, mani sotto i glutei.\nSolleva una gamba tesa mentre l''altra rimane vicino al suolo.\nAlterna il movimento controllando la discesa.', 'Mantieni la zona lombare sempre aderente al suolo durante tutta l''esecuzione.', 'Evitare in caso di dolore acuto alla zona lombare.', 'Inarcare la schiena durante la discesa della gamba.\nEseguire il movimento con slancio.'),
('alternate-leg-raises', 'zh', '交替腿部抬起', '基础练习，专注于下腹直肌，同时保持背部稳定。', '加强下腹部区域并改善骨盆控制。', '仰卧，双手放在臀部下方。\n抬起一条伸直的腿，另一条靠近地面。\n交替动作，控制下落。', '执行过程中始终保持下背部贴地。', '如有下背部剧痛，请避免使用。', '放下腿时拱背。\n利用惯性进行动作。'),
('alternate-leg-raises', 'ja', '交互レッグレイズ', '背中を安定させた状態で下腹直筋に焦点を当てた基本エクササイズ。', '下腹部を強化し、骨盤のコントロールを向上させます。', '仰向けになり、手を臀部の下に置きます。\n片脚を伸ばしたまま上げ、もう片方は床に近づけます。\n下ろす動作をコントロールしながら交互に行います。', '動作中、腰を常に床に押し付けた状態を保ちます。', '腰に激しい痛みがある場合は避けてください。', '脚を下ろす際に背中が反ること。\n反動を使って動作を行うこと。'),
('alternate-leg-raises', 'ko', '교대 다리 들어올리기', '등을 안정시킨 상태에서 하복직근에 집중하는 기본 운동.', '하복부 영역을 강화하고 골반 조절 능력을 향상시킵니다.', '천장을 보고 누워 손을 엉덩이 밑에 둡니다.\n한쪽 다리를 펴서 올리고 다른 쪽은 바닥 근처에 둡니다.\n내려가는 동작을 조절하며 다리를 교대합니다.', '운동 내내 허리를 바닥에 밀착시키세요.', '허리에 급성 통증이 있으면 피하세요.', '다리를 내릴 때 등을 젖히는 것.\n반동을 사용하여 운동하는 것.'),
('alternate-leg-raises', 'ar', 'رفع الساق بالتبادل', 'تمرين أساسي يركز على الجزء السفلي من عضلة البطن المستقيمة مع الحفاظ على استقرار الظهر.', 'يقوي منطقة البطن السفلية ويحسن السيطرة على الحوض.', 'استلقِ على ظهرك، ضع يديك تحت الأرداف.\nارفع ساقًا ممدودة بينما تبقى الأخرى قريبة من الأرض.\nبدل الحركة مع التحكم في النزول.', 'حافظ على أسفل ظهرك ملامسًا للأرض طوال فترة التنفيذ.', 'تجنب التمرين في حالة وجود ألم حاد في أسفل الظهر.', 'تقوس الظهر عند خفض الساق.\nأداء الحركة باستخدام الدفع.'),
('alternate-leg-raises', 'hi', 'अल्टरनेट लेग रेजेस', 'पीठ को स्थिर रखते हुए निचले रेक्टस एब्डोमिनिस पर केंद्रित मूल व्यायाम।', 'निचले पेट के क्षेत्र को मजबूत करता है और पेल्विक नियंत्रण में सुधार करता है।', 'पीठ के बल लेट जाएं, हाथ ग्लूट्स के नीचे रखें।\nएक सीधा पैर उठाएं जबकि दूसरा फर्श के करीब रहे।\nउतरते समय नियंत्रित करते हुए बारी-बारी से करें।', 'पूरी प्रक्रिया के दौरान अपनी निचली पीठ को फर्श पर दबाकर रखें।', 'यदि पीठ के निचले हिस्से में तीव्र दर्द हो तो न करें।', 'पैर नीचे लाते समय पीठ मोड़ना।\nझटके के साथ गति करना।'),
('alternate-leg-raises', 'ru', 'Попеременный подъем ног', 'Базовое упражнение, направленное на нижнюю часть прямой мышцы живота при стабильной спине.', 'Укрепляет нижнюю часть живота и улучшает контроль таза.', 'Лягте на спину, руки под ягодицы.\nПоднимите одну прямую ногу, пока вторая остается у пола.\nЧередуйте движение, контролируя опускание.', 'Держите поясницу прижатой к полу на протяжении всего выполнения.', 'Избегайте при острой боли в пояснице.', 'Прогиб в спине при опускании ноги.\nВыполнение движения по инерции.'),
('alternate-leg-raises', 'nl', 'Afwisselende beenheffen', 'Basisoefening gericht op de onderste rechte buikspier terwijl de rug stabiel blijft.', 'Versterkt de onderbuik en verbetert bekkencontrole.', 'Ga op je rug liggen, handen onder je billen.\nTil één gestrekt been op terwijl het andere dicht bij de vloer blijft.\nWissel af en controleer de daling.', 'Houd je onderrug tijdens de hele uitvoering tegen de vloer gedrukt.', 'Vermijden bij acute pijn in de onderrug.', 'De rug hol trekken bij het laten zakken van het been.\nDe beweging uitvoeren met momentum.'),
('alternate-leg-raises', 'sv', 'Växelvis benlyft', 'Grundläggande övning med fokus på den nedre delen av magmusklerna med stabil rygg.', 'Stärker nedre delen av magen och förbättrar bäckenkontrollen.', 'Ligg på rygg, händer under sätet.\nLyft ett sträckt ben medan det andra hålls nära golvet.\nVäxla och kontrollera sänkningen.', 'Håll ländryggen pressad mot golvet under hela övningen.', 'Undvik vid akut smärta i ländryggen.', 'Att svanka när benet sänks.\nUtföra rörelsen med fart/sväng.'),
('alternate-leg-raises', 'pl', 'Naprzemienne unoszenie nóg', 'Podstawowe ćwiczenie skupione na dolnej części mięśnia prostego brzucha przy stabilnych plecach.', 'Wzmacnia dolne partie brzucha i poprawia kontrolę miednicy.', 'Połóż się na plecach, dłonie pod pośladkami.\nUnieś jedną wyprostowaną nogę, podczas gdy druga pozostaje blisko podłogi.\nZmieniaj nogi, kontrolując opuszczanie.', 'Utrzymuj odcinek lędźwiowy przyciśnięty do podłogi przez cały czas.', 'Unikaj w przypadku ostrego bólu lędźwi.', 'Wyginanie pleców podczas opuszczania nogi.\nUżywanie rozpędu do wykonywania ruchu.'),
('alternate-leg-raises', 'id', 'Angkatan kaki bergantian', 'Latihan dasar yang berfokus pada rektus abdominis bawah sambil menjaga punggung tetap stabil.', 'Memperkuat area perut bawah dan meningkatkan kontrol panggul.', 'Berbaring telentang, tangan di bawah bokong.\nAngkat satu kaki lurus sementara yang lain tetap dekat dengan lantai.\nBergantian gerakan sambil mengontrol penurunan.', 'Jaga punggung bawah tetap menekan lantai selama pelaksanaan.', 'Hindari jika ada nyeri punggung bawah yang akut.', 'Melengkungkan punggung saat menurunkan kaki.\nMelakukan gerakan dengan momentum.'),
('alternate-leg-raises', 'bn', 'অল্টারনেটিং লেগ রেজেস', 'নিচের রেক্টাস অ্যাবডোমিনিস অংশে ফোকাস করা একটি প্রাথমিক ব্যায়াম, যেখানে পিঠ স্থির থাকে।', 'পেটের নিচের অংশ শক্তিশালী করে এবং পেলভিক নিয়ন্ত্রণ উন্নত করে।', 'পিঠের উপর শুয়ে পড়ুন, হাত গ্লুটসের নিচে রাখুন।\nএকটি সোজা পা তুলুন যখন অন্যটি মেঝের কাছাকাছি থাকে।', 'অনুশীলন জুড়ে আপনার নিচের পিঠ মেঝেতে চেপে রাখুন।', 'নিচের পিঠে তীব্র ব্যথা থাকলে এড়িয়ে চলুন।', 'পা নামানোর সময় পিঠ বাঁকানো।\nঝাঁকুনি দিয়ে ব্যায়াম করা।'),
('alternate-leg-raises', 'vi', 'Nâng chân luân phiên', 'Bài tập cơ bản tập trung vào phần dưới của cơ bụng thẳng trong khi giữ lưng ổn định.', 'Tăng cường vùng bụng dưới và cải thiện khả năng kiểm soát xương chậu.', 'Nằm ngửa, tay đặt dưới mông.\nNâng một chân thẳng trong khi chân kia vẫn gần sàn.\nLuân phiên động tác, kiểm soát khi hạ chân.', 'Luôn ép sát thắt lưng xuống sàn trong suốt quá trình tập.', 'Tránh tập nếu bị đau lưng dưới cấp tính.', 'Võng lưng khi hạ chân.\nDùng đà để thực hiện động tác.'),
('alternate-leg-raises', 'fa', 'بالا آوردن متناوب پا', 'تمرین پایه متمرکز بر بخش پایینی عضله راست شکم در حالی که پشت ثابت می‌ماند.', 'ناحیه پایین شکم را تقویت می‌کند و کنترل لگن را بهبود می‌بخشد.', 'به پشت دراز بکشید، دست‌ها را زیر باسن قرار دهید.\nیک پای صاف را بالا ببرید در حالی که پای دیگر نزدیک زمین است.\nبا کنترل کردن پایین آمدن، پاها را عوض کنید.', 'در طول اجرای تمرین، کمر خود را به زمین بچسبانید.', 'در صورت درد حاد در کمر از انجام آن خودداری کنید.', 'قوس دادن به کمر هنگام پایین آوردن پا.\nاستفاده از ضربه برای انجام حرکت.');