-- Definición del ejercicio y sus recursos
INSERT INTO exercises (slug, img, video, difficulty) 
VALUES ('alternate-single-leg-raise-plank', 'alternate-single-leg-raise-plank.jpg', 'alternate-single-leg-raise-plank.mp4', 'intermediate');

-- Relación: el ejercicio trabaja el grupo muscular 'abdominals'
INSERT INTO exercise_body_target (exercise_slug, body_target_slug) 
VALUES ('alternate-single-leg-raise-plank', 'abdominals');

-- Relación: no requiere máquina, por lo tanto no se inserta en exercise_machine
INSERT INTO exercise_alternative (exercise_slug, alternative_slug) 
VALUES ('alternate-single-leg-raise-plank', 'plank');

-- Información multiidioma del ejercicio
INSERT INTO exercises_info (slug, lang, title, description, benefits, instructions, tips, restrictions, mistakes) VALUES 
('alternate-single-leg-raise-plank', 'es', 'Plancha con elevación alterna de pierna', 'Variación de la plancha que añade inestabilidad al elevar una pierna, intensificando el trabajo del core.', 'Aumenta la activación del core y mejora la estabilidad de la zona lumbar.', 'En posición de plancha frontal, eleva una pierna estirada sin arquear la espalda.\nBájala y alterna con la otra pierna.', 'Mantén los glúteos contraídos para proteger la zona lumbar.', 'Evitar si hay dolor agudo en la zona lumbar.', 'Arquear la espalda al elevar la pierna.\nElevar la pierna demasiado alto perdiendo la alineación.'),
('alternate-single-leg-raise-plank', 'en', 'Alternate single leg raise plank', 'Plank variation adding instability by lifting one leg, intensifying core work.', 'Increases core activation and improves lower back stability.', 'In a front plank position, lift one straight leg without arching your back.\nLower it and alternate with the other leg.', 'Keep your glutes contracted to protect your lower back.', 'Avoid if there is acute lower back pain.', 'Arching the back when lifting the leg.\nLifting the leg too high and losing alignment.'),
('alternate-single-leg-raise-plank', 'pt', 'Prancha com elevação alternada de perna', 'Variação da prancha que adiciona instabilidade ao elevar uma perna, intensificando o trabalho do core.', 'Aumenta a ativação do core e melhora a estabilidade da zona lombar.', 'Na posição de prancha frontal, eleve uma perna esticada sem arquear as costas.\nBaixe-a e alterne com a outra perna.', 'Mantenha os glúteos contraídos para proteger a zona lombar.', 'Evitar se houver dor aguda na zona lombar.', 'Arquear as costas ao elevar a perna.\nElevar a perna demasiado alto, perdendo o alinhamento.'),
('alternate-single-leg-raise-plank', 'fr', 'Planche avec levée alternée de jambe', 'Variante de la planche ajoutant de l''instabilité en levant une jambe, intensifiant le travail du tronc.', 'Augmente l''activation du tronc et améliore la stabilité du bas du dos.', 'En position de planche frontale, levez une jambe tendue sans cambrer le dos.\nAbaissez-la et alternez avec l''autre jambe.', 'Gardez les fessiers contractés pour protéger le bas du dos.', 'À éviter en cas de douleur aiguë au bas du dos.', 'Cambrer le dos en levant la jambe.\nLever la jambe trop haut, perdant l''alignement.'),
('alternate-single-leg-raise-plank', 'de', 'Planke mit abwechselndem Beinheben', 'Plankenvariante, die durch das Anheben eines Beins Instabilität hinzufügt und die Rumpfarbeit intensiviert.', 'Erhöht die Rumpfaktivierung und verbessert die Stabilität des unteren Rückens.', 'Heben Sie in der Frontplankenposition ein gestrecktes Bein an, ohne den Rücken durchzustrecken.\nSenken Sie es ab und wechseln Sie zum anderen Bein.', 'Halten Sie das Gesäß angespannt, um den unteren Rücken zu schützen.', 'Bei akuten Schmerzen im unteren Rücken vermeiden.', 'Durchstrecken des Rückens beim Anheben des Beins.\nZu hohes Anheben des Beins und Verlust der Ausrichtung.'),
('alternate-single-leg-raise-plank', 'it', 'Plank con sollevamento alternato della gamba', 'Variante del plank che aggiunge instabilità sollevando una gamba, intensificando il lavoro del core.', 'Aumenta l''attivazione del core e migliora la stabilità della zona lombare.', 'In posizione di plank frontale, solleva una gamba tesa senza inarcare la schiena.\nAbbassala e alterna con l''altra gamba.', 'Mantieni i glutei contratti per proteggere la zona lombare.', 'Evitare in caso di dolore acuto alla zona lombare.', 'Inarcare la schiena durante il sollevamento della gamba.\nSollevare la gamba troppo in alto, perdendo l''allineamento.'),
('alternate-single-leg-raise-plank', 'zh', '平板支撑单腿交替抬起', '平板支撑的变体，通过抬起一条腿增加不稳定性，增强核心锻炼。', '增加核心激活并改善下背部稳定性。', '在前平板支撑姿势中，抬起一条直腿，不要拱背。\n放下它并与另一条腿交替。', '保持臀部收紧以保护下背部。', '如有下背部剧痛，请避免使用。', '抬腿时拱背。\n抬腿过高，失去身体排列。'),
('alternate-single-leg-raise-plank', 'ja', 'プランク：交互片脚上げ', '脚を上げることで不安定さを加え、体幹への負荷を高めるプランクバリエーション。', '体幹の活性化を高め、腰部の安定性を向上させます。', 'フロントプランクの姿勢から、背中を反らさずに片脚を伸ばしたまま上げます。\n下ろして反対側の脚と交互に行います。', '腰を守るため、臀部に力を入れた状態を保ちます。', '腰に激しい痛みがある場合は避けてください。', '脚を上げる際に背中が反ること。\n脚を上げすぎて姿勢が崩れること。'),
('alternate-single-leg-raise-plank', 'ko', '플랭크 다리 교대 들어올리기', '한쪽 다리를 들어 올려 불안정성을 더해 코어 운동을 강화하는 플랭크 변형.', '코어 활성화를 높이고 허리 안정성을 개선합니다.', '하이 플랭크 자세에서 등을 젖히지 않고 한쪽 다리를 펴서 올립니다.\n내리고 반대쪽 다리로 교대합니다.', '허리 보호를 위해 둔근을 수축 상태로 유지하세요.', '허리에 급성 통증이 있으면 피하세요.', '다리를 올릴 때 등을 젖히는 것.\n다리를 너무 높이 올려 자세가 무너지는 것.'),
('alternate-single-leg-raise-plank', 'ar', 'تمرين بلانك مع رفع الساق بالتبادل', 'تنويع لتمرين البلانك يضيف عدم استقرار عن طريق رفع ساق واحدة، مما يكثف عمل الجذع.', 'زيادة تفعيل الجذع وتحسين استقرار أسفل الظهر.', 'في وضع البلانك الأمامي، ارفع ساقًا ممدودة دون تقوس ظهرك.\nأنزلها وبدل مع الساق الأخرى.', 'حافظ على شد الأرداف لحماية أسفل الظهر.', 'تجنب التمرين في حالة وجود ألم حاد في أسفل الظهر.', 'تقوس الظهر عند رفع الساق.\nرفع الساق عاليًا جدًا وفقدان الاستقامة.'),
('alternate-single-leg-raise-plank', 'hi', 'अल्टरनेट सिंगल लेग रेज प्लैंक', 'प्लैंक का प्रकार जो एक पैर उठाकर अस्थिरता जोड़ता है, जिससे कोर का काम तेज होता है।', 'कोर सक्रियण बढ़ाता है और पीठ के निचले हिस्से की स्थिरता में सुधार करता है।', 'फ्रंट प्लैंक स्थिति में, पीठ मोड़े बिना एक सीधा पैर उठाएं।\nउसे नीचे लाएं और दूसरे पैर के साथ बदलें।', 'पीठ के निचले हिस्से की सुरक्षा के लिए अपने ग्लूट्स को सिकोड़ कर रखें।', 'यदि पीठ के निचले हिस्से में तीव्र दर्द हो तो न करें।', 'पैर उठाते समय पीठ मोड़ना।\nपैर को बहुत ऊंचा उठाना जिससे शरीर की सीध बिगड़ जाए।'),
('alternate-single-leg-raise-plank', 'ru', 'Планка с попеременным подъемом ноги', 'Вариация планки, добавляющая нестабильность за счет подъема ноги, усиливая работу кора.', 'Увеличивает активацию кора и улучшает стабильность поясницы.', 'В положении планки поднимите одну прямую ногу, не прогибая спину.\nОпустите и чередуйте с другой ногой.', 'Держите ягодицы напряженными для защиты поясницы.', 'Избегайте при острой боли в пояснице.', 'Прогиб в спине при подъеме ноги.\nСлишком высокий подъем ноги, приводящий к потере линии тела.'),
('alternate-single-leg-raise-plank', 'nl', 'Plank met afwisselende beenheffen', 'Plankvariatie die instabiliteit toevoegt door één been op te tillen, waardoor het core-werk wordt geïntensiveerd.', 'Verhoogt core-activatie en verbetert de stabiliteit van de onderrug.', 'Til in voorwaartse plankpositie één gestrekt been op zonder je rug hol te trekken.\nLaat het zakken en wissel af met het andere been.', 'Houd je billen aangespannen om je onderrug te beschermen.', 'Vermijden bij acute pijn in de onderrug.', 'De rug hol trekken bij het optillen van het been.\nHet been te hoog optillen waardoor de uitlijning verloren gaat.'),
('alternate-single-leg-raise-plank', 'sv', 'Planka med växelvis benlyft', 'Plankvariation som lägger till instabilitet genom att lyfta ett ben, vilket intensifierar core-träningen.', 'Ökar core-aktivering och förbättrar ländryggsstabilitet.', 'I en framåtlutad plankposition, lyft ett sträckt ben utan att svanka.\nSänk det och växla med det andra benet.', 'Håll sätesmusklerna spända för att skydda ländryggen.', 'Undvik vid akut smärta i ländryggen.', 'Att svanka vid benlyft.\nAtt lyfta benet för högt så att linjeringen går förlorad.'),
('alternate-single-leg-raise-plank', 'pl', 'Plank z naprzemiennym unoszeniem nogi', 'Odmiana deski dodająca niestabilność przez unoszenie nogi, intensyfikująca pracę core.', 'Zwiększa aktywację core i poprawia stabilność odcinka lędźwiowego.', 'W pozycji deski przodem unieś wyprostowaną nogę bez wyginania pleców.\nOpuść ją i zmień nogę.', 'Utrzymuj pośladki napięte, aby chronić odcinek lędźwiowy.', 'Unikaj w przypadku ostrego bólu lędźwi.', 'Wyginanie pleców podczas unoszenia nogi.\nZbyt wysokie unoszenie nogi, prowadzące do utraty prostej linii.'),
('alternate-single-leg-raise-plank', 'id', 'Plank dengan angkatan kaki tunggal bergantian', 'Variasi plank yang menambah ketidakstabilan dengan mengangkat satu kaki, mengintensifkan kerja inti.', 'Meningkatkan aktivasi inti dan stabilitas punggung bawah.', 'Dalam posisi plank depan, angkat satu kaki lurus tanpa melengkungkan punggung.\nTurunkan dan bergantian dengan kaki lainnya.', 'Jaga otot bokong tetap berkontraksi untuk melindungi punggung bawah.', 'Hindari jika ada nyeri punggung bawah yang akut.', 'Melengkungkan punggung saat mengangkat kaki.\nMengangkat kaki terlalu tinggi sehingga kehilangan kesejajaran.'),
('alternate-single-leg-raise-plank', 'bn', 'অল্টারনেটিং সিঙ্গেল লেগ রেইজ প্ল্যাঙ্ক', 'প্ল্যাঙ্কের একটি ভেরিয়েশন যা একটি পা তুলে অস্থিরতা যোগ করে, কোর এর কাজকে তীব্র করে।', 'কোর সক্রিয়করণ বাড়ায় এবং পিঠের নিচের স্থিতিশীলতা উন্নত করে।', 'ফ্রন্ট প্ল্যাঙ্ক পজিশনে, পিঠ না বাঁকিয়ে একটি সোজা পা তুলুন।\nএটি নামান এবং অন্য পায়ের সাথে পরিবর্তন করুন।', 'পিঠের নিচের অংশ রক্ষা করতে আপনার গ্লুটস শক্ত রাখুন।', 'পিঠের নিচের অংশে তীব্র ব্যথা থাকলে এড়িয়ে চলুন।', 'পা তোলার সময় পিঠ বাঁকানো।\nপা খুব বেশি উঁচুতে তোলা, যা শরীরের লাইন নষ্ট করে।'),
('alternate-single-leg-raise-plank', 'vi', 'Plank nâng chân đơn luân phiên', 'Biến thể plank thêm sự mất ổn định bằng cách nâng một chân, tăng cường tập cơ lõi.', 'Tăng cường kích hoạt cơ lõi và cải thiện sự ổn định lưng dưới.', 'Ở tư thế plank trước, nâng một chân thẳng mà không làm võng lưng.\nHạ chân xuống và đổi bên.', 'Giữ cơ mông gồng chặt để bảo vệ lưng dưới.', 'Tránh tập nếu bị đau lưng dưới cấp tính.', 'Võng lưng khi nâng chân.\nNâng chân quá cao làm mất đường thẳng cơ thể.'),
('alternate-single-leg-raise-plank', 'fa', 'پلانک با بالا آوردن متناوب پا', 'نسخه پلانک که با بلند کردن یک پا بی‌ثباتی ایجاد کرده و کار هسته را تشدید می‌کند.', 'فعال‌سازی هسته را افزایش داده و ثبات کمر را بهبود می‌بخشد.', 'در وضعیت پلانک از جلو، یک پای صاف را بدون قوس دادن به کمر بلند کنید.\nآن را پایین بیاورید و با پای دیگر انجام دهید.', 'برای محافظت از کمر، باسن را منقبض نگه دارید.', 'در صورت درد حاد در کمر از انجام آن خودداری کنید.', 'قوس دادن به کمر هنگام بلند کردن پا.\nبلند کردن پا بیش از حد بالا و از دست دادن راستای بدن.');