-- Definición de ejercicios
INSERT OR IGNORE INTO exercises (slug, img, video, difficulty) 
VALUES 
('alternating-plank-lunge', 'alternating-plank-lunge.jpg', 'alternating-plank-lunge.mp4', 'intermediate'),
('high-plank', 'high-plank.jpg', 'high-plank.mp4', 'intermediate');

-- Relaciones de grupos musculares
INSERT INTO exercise_body_target (exercise_slug, body_target_slug) 
VALUES 
('alternating-plank-lunge', 'abdominals');

-- Relaciones de alternativas
INSERT INTO exercise_alternative (exercise_slug, alternative_slug) 
VALUES 
('alternating-plank-lunge', 'high-plank');

-- Información multiidioma
INSERT OR IGNORE INTO exercises_info (slug, lang, title, description, benefits, instructions, tips, restrictions, mistakes) VALUES 
('alternating-plank-lunge', 'es', 'Plancha con zancada alterna', 'Variante dinámica de plancha que integra movimiento de piernas para aumentar la activación del core profundo.', 'Mejora la estabilidad lumbopélvica y la movilidad de cadera bajo tensión.', 'Desde posición de plancha alta, lleva un pie hacia adelante al exterior de la mano y vuelve a la posición inicial.', 'Mantén la espalda neutra y evita que la cadera caiga o se eleve durante el movimiento.', 'Evitar en caso de dolor agudo en la zona lumbar o lesiones de cadera.', 'Elevar la cadera demasiado al realizar el movimiento o perder la alineación de los hombros.'),
('alternating-plank-lunge', 'en', 'Alternating plank lunge', 'Dynamic plank variant integrating leg movement to increase deep core activation.', 'Enhances lumbopelvic stability and hip mobility under tension.', 'From a high plank position, bring one foot forward to the outside of the hand and return to the starting position.', 'Keep a neutral spine and prevent the hips from dropping or hiking during the movement.', 'Avoid if acute lower back pain or hip injuries are present.', 'Hiking hips too high during movement or losing shoulder alignment.'),
('alternating-plank-lunge', 'pt', 'Prancha com avanço alternado', 'Variante dinâmica de prancha que integra o movimento das pernas para aumentar a ativação do core profundo.', 'Melhora a estabilidade lumbopélvica e a mobilidade do quadril sob tensão.', 'Na posição de prancha alta, leve um pé para a frente, fora da mão, e retorne à posição inicial.', 'Mantenha a coluna neutra e evite que o quadril caia ou suba durante o movimento.', 'Evitar em caso de dor lombar aguda ou lesões no quadril.', 'Elevar muito o quadril durante o movimento ou perder o alinhamento dos ombros.'),
('alternating-plank-lunge', 'fr', 'Planche avec fente alternée', 'Variante dynamique de la planche intégrant un mouvement de jambe pour augmenter l''activation du core profond.', 'Améliore la stabilité lumbopelvienne et la mobilité de la hanche sous tension.', 'Depuis une position de planche haute, amenez un pied vers l''avant à l''extérieur de la main, puis revenez à la position initiale.', 'Gardez une colonne vertébrale neutre et évitez que les hanches ne s''affaissent ou ne se lèvent trop.', 'À éviter en cas de douleur lombaire aiguë ou de blessures à la hanche.', 'Lever les hanches trop haut pendant le mouvement ou perdre l''alignement des épaules.'),
('alternating-plank-lunge', 'de', 'Plank mit abwechselndem Ausfallschritt', 'Dynamische Plank-Variante, die Beinbewegungen einbezieht, um die tiefe Rumpfmuskulatur zu aktivieren.', 'Verbessert die lumbopelvinale Stabilität und Hüftbeweglichkeit unter Spannung.', 'Aus der hohen Plank-Position einen Fuß nach vorne an die Außenseite der Hand bringen und in die Ausgangsposition zurückkehren.', 'Die Wirbelsäule neutral halten und verhindern, dass die Hüften während der Bewegung absinken oder ansteigen.', 'Bei akuten Rückenschmerzen oder Hüftverletzungen vermeiden.', 'Die Hüften zu weit anheben oder die Schulterausrichtung verlieren.'),
('alternating-plank-lunge', 'it', 'Plank con affondo alternato', 'Variante dinamica del plank che integra il movimento delle gambe per aumentare l''attivazione del core profondo.', 'Migliora la stabilità lumbopelvica e la mobilità dell''anca sotto tensione.', 'Dalla posizione di plank alto, porta un piede in avanti all''esterno della mano e torna alla posizione iniziale.', 'Mantieni la colonna vertebrale neutra ed evita che il bacino si abbassi o si sollevi troppo durante il movimento.', 'Evitare in caso di dolore lombare acuto o lesioni all''anca.', 'Sollevare troppo il bacino durante il movimento o perdere l''allineamento delle spalle.'),
('alternating-plank-lunge', 'zh', '平板支撑交替弓步', '动态平板支撑变体，结合腿部运动以增加深层核心激活。', '提高紧张状态下的腰盆腔稳定性和髋关节灵活性。', '从高平板支撑位，将一只脚向前带到手的外侧，然后回到起始位置。', '保持脊柱中立，防止移动时臀部下垂或抬起。', '如有急性腰痛或髋关节损伤，请避免使用。', '移动时臀部抬得太高或失去肩膀对齐。'),
('alternating-plank-lunge', 'ja', 'プランク・オルタネーティング・ランジ', '深層コアの活性化を高めるための脚の動きを統合した動的プランクバリエーション。', '緊張下での腰骨盤の安定性と股関節の可動性を向上させます。', 'ハイプランクの姿勢から、片足を手の外側へ前方に踏み出し、開始姿勢に戻ります。', '脊椎をニュートラルに保ち、動きの最中に腰が下がったり上がったりしないようにします。', '急性腰痛や股関節の怪我がある場合は避けてください。', '動きの最中に腰を上げすぎたり、肩のラインが崩れたりすること。'),
('alternating-plank-lunge', 'ko', '플랭크 얼터네이팅 런지', '심부 코어 활성화를 높이기 위해 다리 움직임을 결합한 역동적인 플랭크 변형.', '긴장 상태에서 요골반 안정성과 고관절 가동성을 향상시킴.', '하이 플랭크 자세에서 한쪽 발을 손 바깥쪽으로 가져왔다가 시작 자세로 돌아옴.', '척추 중립을 유지하고 동작 중 골반이 처지거나 솟지 않도록 주의할 것.', '급성 요통이나 고관절 부상이 있다면 피할 것.', '동작 중 엉덩이를 너무 높이 들거나 어깨 정렬을 잃는 것.'),
('alternating-plank-lunge', 'ar', 'تمرين البلانك مع الاندفاع المتبادل', 'تمرين بلانك ديناميكي يدمج حركة الساقين لزيادة تفعيل عضلات الجذع العميقة.', 'يحسن استقرار منطقة أسفل الظهر والحوض ومرونة الورك تحت الضغط.', 'من وضع البلانك العالي، أحضر إحدى القدمين للأمام إلى خارج اليد، ثم عد للوضع الأصلي.', 'حافظ على استقامة العمود الفقري وتجنب سقوط أو ارتفاع الحوض أثناء الحركة.', 'تجنب التمرين في حالة وجود آلام حادة في أسفل الظهر أو إصابات في الورك.', 'رفع الحوض عالياً جداً أثناء الحركة أو فقدان محاذاة الكتفين.'),
('alternating-plank-lunge', 'hi', 'प्लेंक अल्टरनेटिंग लंज', 'गहरी कोर सक्रियता बढ़ाने के लिए पैरों की गति को एकीकृत करने वाला गतिशील प्लेंक संस्करण।', 'तनाव के तहत लंबोपेलविक स्थिरता और कूल्हे की गतिशीलता को बढ़ाता है।', 'हाई प्लेंक स्थिति से, एक पैर को हाथ के बाहर की तरफ आगे लाएं और प्रारंभिक स्थिति में लौटें।', 'रीढ़ की हड्डी को तटस्थ रखें और गति के दौरान कूल्हों को गिरने या ऊपर उठने से रोकें।', 'यदि पीठ के निचले हिस्से में तीव्र दर्द या कूल्हे में चोट हो तो न करें।', 'गति के दौरान कूल्हों को बहुत ऊपर उठाना या कंधों का संतुलन खोना।'),
('alternating-plank-lunge', 'ru', 'Планка с поочередным выпадом', 'Динамический вариант планки, интегрирующий движение ног для усиления активации глубоких мышц кора.', 'Улучшает пояснично-тазовую стабильность и подвижность тазобедренного сустава под нагрузкой.', 'Из положения высокой планки перенесите одну ногу вперед к внешней стороне руки и вернитесь в исходное положение.', 'Держите позвоночник в нейтральном положении, избегая провисания или подъема таза.', 'Избегайте при острой боли в пояснице или травмах тазобедренного сустава.', 'Слишком высокий подъем таза во время движения или потеря выравнивания плеч.'),
('alternating-plank-lunge', 'nl', 'Plank met afwisselende lunge', 'Dynamische plankvariant die beenbeweging integreert voor verhoogde activering van de diepe core.', 'Verbetert lumbopelvische stabiliteit en heupmobiliteit onder spanning.', 'Breng vanuit een hoge plankpositie één voet naar voren aan de buitenkant van de hand en keer terug naar de startpositie.', 'Houd de ruggengraat neutraal en voorkom dat de heupen tijdens de beweging inzakken of omhoog komen.', 'Vermijden bij acute onderrugpijn of heupblessures.', 'De heupen te hoog optillen tijdens de beweging of de schouderuitlijning verliezen.'),
('alternating-plank-lunge', 'sv', 'Planka med alternerande utfall', 'Dynamisk plankvariant som integrerar benrörelser för ökad djup core-aktivering.', 'Förbättrar lumbopelvisk stabilitet och höftrörlighet under spänning.', 'Från en hög plankposition, för fram en fot till utsidan av handen och återgå till startpositionen.', 'Håll ryggraden neutral och förhindra att höfterna sjunker eller höjs under rörelsen.', 'Undvik vid akut ländryggssmärta eller höftskador.', 'Att lyfta höfterna för högt under rörelsen eller tappa axelutjämningen.'),
('alternating-plank-lunge', 'pl', 'Plank z naprzemiennym wypadem', 'Dynamiczny wariant plank integrujący ruch nóg dla zwiększenia aktywacji mięśni głębokich tułowia.', 'Poprawia stabilność lędźwiowo-miedniczną i ruchomość bioder pod obciążeniem.', 'Z pozycji planku wysokiego przesuń jedną stopę do przodu na zewnątrz dłoni i wróć do pozycji startowej.', 'Utrzymuj neutralny kręgosłup i zapobiegaj opadaniu lub unoszeniu bioder podczas ruchu.', 'Unikaj w przypadku ostrego bólu odcinka lędźwiowego lub urazów biodra.', 'Zbyt wysokie unoszenie bioder podczas ruchu lub utrata wyrównania barków.'),
('alternating-plank-lunge', 'id', 'Plank dengan lunge bergantian', 'Variasi plank dinamis yang mengintegrasikan gerakan kaki untuk meningkatkan aktivasi core dalam.', 'Meningkatkan stabilitas lumbopelvik dan mobilitas pinggul di bawah tekanan.', 'Dari posisi plank tinggi, bawa satu kaki ke depan ke luar tangan dan kembali ke posisi awal.', 'Jaga tulang belakang tetap netral dan cegah pinggul turun atau naik selama gerakan.', 'Hindari jika ada nyeri punggung bawah akut atau cedera pinggul.', 'Mengangkat pinggul terlalu tinggi selama gerakan atau kehilangan kesejajaran bahu.'),
('alternating-plank-lunge', 'bn', 'প্ল্যাঙ্ক উইথ অল্টারনেটিং লাঞ্জ', 'গভীর কোর অ্যাক্টিভেশন বাড়ানোর জন্য পায়ের নড়াচড়াকে একীভূত করা একটি গতিশীল প্ল্যাঙ্ক ভেরিয়েন্ট।', 'চাপের মুখে লম্বোপেলভিক স্থিতিশীলতা এবং হিপ গতিশীলতা উন্নত করে।', 'হাই প্ল্যাঙ্ক পজিশন থেকে একটি পা হাতের বাইরে সামনের দিকে আনুন এবং শুরুর অবস্থানে ফিরে যান।', 'মেরুদণ্ড সোজা রাখুন এবং নড়াচড়ার সময় হিপ যাতে ঝুলে না যায় বা উপরে না ওঠে তা নিশ্চিত করুন।', 'পিঠের নিচের অংশে তীব্র ব্যথা বা হিপের চোট থাকলে এটি এড়িয়ে চলুন।', 'নড়াচড়ার সময় হিপ খুব উঁচুতে তোলা বা কাঁধের ভারসাম্য হারানো।'),
('alternating-plank-lunge', 'vi', 'Plank với bước chùng chân xen kẽ', 'Biến thể plank động tích hợp chuyển động chân để tăng cường kích hoạt cơ core sâu.', 'Cải thiện sự ổn định vùng thắt lưng-chậu và độ linh hoạt của hông dưới áp lực.', 'Từ tư thế plank cao, đưa một chân lên phía trước ra ngoài bàn tay rồi trở về vị trí ban đầu.', 'Giữ cột sống trung tính và ngăn hông bị võng hoặc nhô lên trong khi di chuyển.', 'Tránh tập nếu bị đau lưng dưới cấp tính hoặc chấn thương hông.', 'Nâng hông quá cao khi di chuyển hoặc mất sự căn chỉnh của vai.'),
('alternating-plank-lunge', 'fa', 'پلانک با لانژ متناوب', 'نوعی پلانک پویا که حرکات پا را برای افزایش فعالیت عضلات عمقی شکم ادغام می‌کند.', 'پایداری لومبوی لگنی و انعطاف‌پذیری لگن را تحت فشار بهبود می‌بخشد.', 'از وضعیت پلانک بالا، یک پا را به سمت بیرون دست جلو بیاورید و به وضعیت اولیه برگردید.', 'ستون فقرات را خنثی نگه دارید و از افتادن یا بالا رفتن لگن در حین حرکت جلوگیری کنید.', 'در صورت درد حاد کمر یا آسیب‌دیدگی لگن از انجام آن خودداری کنید.', 'بالا آوردن بیش از حد لگن در حین حرکت یا از دست دادن هم‌راستایی شانه‌ها.');