-- Definición del ejercicio y sus recursos
INSERT INTO exercises (slug, img, video, difficulty) 
VALUES ('arch-body-rock', 'arch-body-rock.jpg', 'arch-body-rock.mp4', 'advanced');

-- Relación: el ejercicio trabaja el grupo muscular 'lower_back'
INSERT INTO exercise_body_target (exercise_slug, body_target_slug) 
VALUES ('arch-body-rock', 'lower_back');

-- Relación: no requiere máquina, por lo tanto no se inserta en exercise_machine
INSERT INTO exercise_alternative (exercise_slug, alternative_slug) 
VALUES ('arch-body-rock', 'arch-body-hold');

-- Información multiidioma del ejercicio
INSERT INTO exercises_info (slug, lang, title, description, benefits, instructions, tips, restrictions, mistakes) VALUES 
('arch-body-rock', 'es', 'Balanceo en arco (Arch Body Rock)', 'Variación dinámica del sostén en arco, añadiendo un balanceo controlado para fortalecer la cadena posterior.', 'Mejora el control dinámico de la espalda baja y la coordinación de la cadena posterior.', 'En posición de arco, balancéate suavemente hacia adelante y atrás sin romper la alineación.', 'Mantén la tensión en todo el cuerpo durante el balanceo.', 'Evitar si hay lesiones graves en la columna vertebral.', 'Usar impulso excesivo perdiendo el control del movimiento.\nDoblar las rodillas.'),
('arch-body-rock', 'en', 'Arch body rock', 'Dynamic variation of the arch body hold, adding controlled rocking to strengthen the posterior chain.', 'Improves dynamic lower back control and posterior chain coordination.', 'In an arch position, rock gently back and forth without breaking alignment.', 'Maintain tension throughout the entire body during the rock.', 'Avoid if there are serious spinal injuries.', 'Using excessive momentum and losing control of the movement.\nBending the knees.'),
('arch-body-rock', 'pt', 'Balanço em arco', 'Variação dinâmica da sustentação em arco, adicionando um balanço controlado para fortalecer a cadeia posterior.', 'Melhora o controlo dinâmico da zona lombar e a coordenação da cadeia posterior.', 'Na posição de arco, balanceie suavemente para a frente e para trás sem quebrar o alinhamento.', 'Mantenha a tensão em todo o corpo durante o balanço.', 'Evitar se houver lesões graves na coluna vertebral.', 'Usar impulso excessivo perdendo o controlo do movimento.\nDobrar os joelhos.'),
('arch-body-rock', 'fr', 'Balancement en arc (Arch body rock)', 'Variante dynamique du maintien en arc, ajoutant un balancement contrôlé pour renforcer la chaîne postérieure.', 'Améliore le contrôle dynamique du bas du dos et la coordination de la chaîne postérieure.', 'En position d''arc, balancez-vous doucement d''avant en arrière sans rompre l''alignement.', 'Maintenez la tension dans tout le corps pendant le balancement.', 'À éviter en cas de lésions graves de la colonne vertébrale.', 'Utiliser un élan excessif en perdant le contrôle du mouvement.\nPlier les genoux.'),
('arch-body-rock', 'de', 'Bogenwippen (Arch body rock)', 'Dynamische Variante des Bogenhalts, die durch kontrolliertes Wippen die hintere Kette stärkt.', 'Verbessert die dynamische Kontrolle des unteren Rückens und die Koordination der hinteren Kette.', 'Wippen Sie in der Bogenposition sanft vor und zurück, ohne die Ausrichtung zu verlieren.', 'Halten Sie während des Wippens die Spannung im gesamten Körper.', 'Bei schweren Wirbelsäulenverletzungen vermeiden.', 'Übermäßigen Schwung verwenden und die Kontrolle über die Bewegung verlieren.\nDie Knie beugen.'),
('arch-body-rock', 'it', 'Dondolio in arco (Arch body rock)', 'Variante dinamica del sostegno in arco, aggiungendo un dondolio controllato per rinforzare la catena posteriore.', 'Migliora il controllo dinamico della parte bassa della schiena e la coordinazione della catena posteriore.', 'In posizione di arco, dondola dolcemente avanti e indietro senza rompere l''allineamento.', 'Mantieni la tensione in tutto il corpo durante il dondolio.', 'Evitare in caso di gravi lesioni alla colonna vertebrale.', 'Usare uno slancio eccessivo perdendo il controllo del movimento.\nFlettere le ginocchia.'),
('arch-body-rock', 'zh', '弓形摇摆', '弓形保持的动态变体，增加受控摇摆以增强后侧链。', '改善下背部的动态控制和后侧链的协调性。', '在弓形位置，轻轻前后摇摆，不要破坏对齐。', '摇摆过程中保持全身紧张。', '如有严重脊柱损伤，请避免使用。', '使用过大的惯性导致动作失控。\n弯曲膝盖。'),
('arch-body-rock', 'ja', 'アーチボディロック', 'アーチボディホールドの動的バリエーションで、制御された揺れを加えて後側連鎖を強化します。', '腰部の動的制御と後側連鎖の調整を向上させます。', 'アーチ姿勢から、姿勢を崩さずに前後へ優しく揺れます。', '揺れている間、全身に力を入れ続けます。', '脊椎に深刻な怪我がある場合は避けてください。', '反動を使いすぎて動きをコントロールできなくなること。\n膝を曲げること。'),
('arch-body-rock', 'ko', '아치 바디 록', '아치 바디 홀드의 동적 변형으로, 통제된 흔들기를 추가하여 후면 사슬을 강화합니다.', '허리의 동적 조절 능력과 후면 사슬의 협응력을 향상시킵니다.', '아치 자세에서 정렬을 유지하며 부드럽게 앞뒤로 흔듭니다.', '흔드는 동안 몸 전체에 긴장을 유지하세요.', '척추에 심각한 부상이 있다면 피하세요.', '반동을 너무 크게 사용하여 동작을 통제하지 못하는 것.\n무릎을 굽히는 것.'),
('arch-body-rock', 'ar', 'تمرين التأرجح في وضع القوس', 'تنويع ديناميكي لتمرين البقاء في وضع القوس، بإضافة تأرجح محكم لتقوية السلسلة الخلفية.', 'تحسين السيطرة الديناميكية على أسفل الظهر وتنسيق السلسلة الخلفية.', 'في وضع القوس، تأرجح بلطف للأمام وللخلف دون كسر الاستقامة.', 'حافظ على التوتر في كامل جسمك أثناء التأرجح.', 'تجنب التمرين في حالة وجود إصابات خطيرة في العمود الفقري.', 'استخدام دفع مفرط وفقدان السيطرة على الحركة.\nثني الركبتين.'),
('arch-body-rock', 'hi', 'आर्च बॉडी रॉक', 'आर्च बॉडी होल्ड का गतिशील प्रकार, पिछली श्रृंखला को मजबूत करने के लिए नियंत्रित रॉकिंग जोड़ना।', 'पीठ के निचले हिस्से का गतिशील नियंत्रण और पिछली श्रृंखला का समन्वय बेहतर बनाता है।', 'आर्च स्थिति में, सीध तोड़े बिना धीरे-धीरे आगे और पीछे की ओर रॉकिंग करें।', 'रॉकिंग के दौरान अपने पूरे शरीर में तनाव बनाए रखें।', 'यदि रीढ़ की हड्डी में गंभीर चोट हो तो न करें।', 'अत्यधिक झटके का उपयोग करना जिससे गति पर नियंत्रण खो जाए।\nघुटने मोड़ना।'),
('arch-body-rock', 'ru', 'Раскачивание в дуге (Arch body rock)', 'Динамическая вариация удержания дуги с добавлением контролируемого раскачивания для укрепления задней цепи.', 'Улучшает динамический контроль поясницы и координацию задней цепи.', 'В положении дуги плавно раскачивайтесь вперед и назад, не нарушая линии тела.', 'Держите все тело в напряжении во время раскачивания.', 'Избегайте при серьезных травмах позвоночника.', 'Использование избыточного импульса с потерей контроля над движением.\nСгибание коленей.'),
('arch-body-rock', 'nl', 'Arch body rock', 'Dynamische variatie van de arch body hold, met gecontroleerd schommelen om de achterste keten te versterken.', 'Verbetert de dynamische controle van de onderrug en de coördinatie van de achterste keten.', 'Schommel in de arch-positie voorzichtig heen en weer zonder de uitlijning te verbreken.', 'Houd tijdens het schommelen spanning in je hele lichaam.', 'Vermijden bij ernstige rugblessures.', 'Te veel momentum gebruiken waardoor de controle verloren gaat.\nDe knieën buigen.'),
('arch-body-rock', 'sv', 'Arch body rock', 'Dynamisk variation av arch body hold, med kontrollerad gungning för att stärka bakre kedjan.', 'Förbättrar dynamisk kontroll av ländryggen och koordination av bakre kedjan.', 'Gunga försiktigt fram och tillbaka i arch-position utan att tappa linjeringen.', 'Behåll spänningen i hela kroppen under gungningen.', 'Undvik vid allvarliga ryggradsskador.', 'Att använda för mycket fart så att kontrollen tappas.\nBöja knäna.'),
('arch-body-rock', 'pl', 'Arch body rock', 'Dynamiczna odmiana arch body hold, dodająca kontrolowane kołysanie wzmacniające taśmę tylną.', 'Poprawia dynamiczną kontrolę dołu pleców i koordynację taśmy tylnej.', 'W pozycji łuku kołysz się delikatnie w przód i w tył bez utraty prostej linii.', 'Utrzymuj napięcie w całym ciele podczas kołysania.', 'Unikaj w przypadku poważnych urazów kręgosłupa.', 'Używanie zbyt dużego rozpędu prowadzące do utraty kontroli.\nZginanie kolan.'),
('arch-body-rock', 'id', 'Arch body rock', 'Variasi dinamis dari arch body hold, menambahkan ayunan terkontrol untuk memperkuat rantai posterior.', 'Meningkatkan kontrol dinamis punggung bawah dan koordinasi rantai posterior.', 'Dalam posisi busur, ayunkan perlahan ke depan dan belakang tanpa merusak kesejajaran.', 'Jaga ketegangan di seluruh tubuh selama berayun.', 'Hindari jika ada cedera tulang belakang yang serius.', 'Menggunakan momentum berlebihan sehingga kehilangan kontrol gerakan.\nMenekuk lutut.'),
('arch-body-rock', 'bn', 'আর্চ বডি রক', 'আর্চ বডি হোল্ডের একটি ডায়নামিক ভেরিয়েশন, পিছনের পেশিকে শক্তিশালী করার জন্য নিয়ন্ত্রিত রকিং যোগ করা।', 'পিঠের নিচের অংশ এবং পিছনের পেশির সমন্বয় উন্নত করে।', 'আর্চ পজিশনে, শরীরের লাইন ঠিক রেখে আলতো করে সামনে-পিছনে দোল খান।', 'রকিং করার সময় সারা শরীরে টানটান ভাব বজায় রাখুন।', 'মেরুদণ্ডে গুরুতর আঘাত থাকলে এড়িয়ে চলুন।', 'অতিরিক্ত ঝোক ব্যবহার করা যা গতির নিয়ন্ত্রণ হারিয়ে ফেলে।\nহাঁটু বাঁকানো।'),
('arch-body-rock', 'vi', 'Arch body rock', 'Biến thể động của arch body hold, thêm nhịp đung đưa có kiểm soát để củng cố chuỗi cơ sau.', 'Cải thiện khả năng kiểm soát động của lưng dưới và sự phối hợp chuỗi cơ sau.', 'Ở tư thế hình cung, đung đưa nhẹ nhàng qua lại mà không làm mất đường thẳng cơ thể.', 'Giữ căng cơ toàn bộ cơ thể trong khi đung đưa.', 'Tránh tập nếu bị chấn thương cột sống nghiêm trọng.', 'Dùng đà quá mức gây mất kiểm soát chuyển động.\nCo đầu gối.'),
('arch-body-rock', 'fa', 'تکان خوردن در حالت کمان (Arch body rock)', 'نسخه دینامیک نگه داشتن بدن در حالت کمان، با افزودن تکان‌های کنترل‌شده برای تقویت زنجیره خلفی.', 'کنترل دینامیک کمر و هماهنگی زنجیره خلفی را بهبود می‌بخشد.', 'در حالت کمان، بدون شکستن راستای بدن، به آرامی به جلو و عقب تاب بخورید.', 'هنگام تاب خوردن، تنش را در تمام بدن حفظ کنید.', 'در صورت آسیب‌های جدی ستون فقرات از انجام آن خودداری کنید.', 'استفاده از ضربه بیش از حد و از دست دادن کنترل حرکت.\nخم کردن زانوها.');