-- Definición del ejercicio y sus recursos
INSERT INTO exercises (slug, img, video, difficulty) 
VALUES ('arm-circles', 'arm-circles.jpg', 'arm-circles.mp4', 'beginner');

-- Relación: el ejercicio trabaja el grupo muscular 'shoulders'
INSERT INTO exercise_body_target (exercise_slug, body_target_slug) 
VALUES ('arm-circles', 'shoulders');

-- Relación: no requiere máquina, por lo tanto no se inserta en exercise_machine
INSERT INTO exercise_alternative (exercise_slug, alternative_slug) 
VALUES ('arm-circles', 'shoulder-rotations');

-- Información multiidioma del ejercicio
INSERT INTO exercises_info (slug, lang, title, description, benefits, instructions, tips, restrictions, mistakes) VALUES 
('arm-circles', 'es', 'Círculos con los brazos', 'Ejercicio de movilidad articular enfocado en los hombros para mejorar el rango de movimiento.', 'Mejora la flexibilidad de los hombros y calienta la articulación.', 'Extiende los brazos a los lados y realiza círculos pequeños y controlados.', 'Mantén los hombros relajados y el torso estable.', 'Evitar si hay dolor agudo o lesiones en el hombro.', 'Realizar círculos demasiado rápidos o con demasiada tensión en el cuello.'),
('arm-circles', 'en', 'Arm circles', 'Joint mobility exercise focused on the shoulders to improve range of motion.', 'Improves shoulder flexibility and warms up the joint.', 'Extend your arms to the sides and perform small, controlled circles.', 'Keep your shoulders relaxed and your torso stable.', 'Avoid if there is acute pain or shoulder injury.', 'Performing circles too quickly or with too much neck tension.'),
('arm-circles', 'pt', 'Círculos com os braços', 'Exercício de mobilidade articular focado nos ombros para melhorar a amplitude de movimento.', 'Melhora a flexibilidade dos ombros e aquece a articulação.', 'Estenda os braços para os lados e faça círculos pequenos e controlados.', 'Mantenha os ombros relaxados e o tronco estável.', 'Evitar se houver dor aguda ou lesão no ombro.', 'Fazer círculos demasiado rápidos ou com demasiada tensão no pescoço.'),
('arm-circles', 'fr', 'Cercles avec les bras', 'Exercice de mobilité articulaire axé sur les épaules pour améliorer l''amplitude de mouvement.', 'Améliore la flexibilité des épaules et échauffe l''articulation.', 'Étendez vos bras sur les côtés et effectuez de petits cercles contrôlés.', 'Gardez les épaules détendues et le torse stable.', 'À éviter en cas de douleur aiguë ou de blessure à l''épaule.', 'Effectuer des cercles trop rapides ou avec trop de tension au niveau du cou.'),
('arm-circles', 'de', 'Armkreisen', 'Gelenkmobilitätsübung für die Schultern zur Verbesserung des Bewegungsumfangs.', 'Verbessert die Schulterflexibilität und wärmt das Gelenk auf.', 'Strecken Sie die Arme zur Seite und führen Sie kleine, kontrollierte Kreise aus.', 'Halten Sie die Schultern entspannt und den Oberkörper stabil.', 'Bei akuten Schmerzen oder Schulterverletzungen vermeiden.', 'Zu schnelles Kreisen oder zu viel Spannung im Nacken.'),
('arm-circles', 'it', 'Circonduzioni delle braccia', 'Esercizio di mobilità articolare focalizzato sulle spalle per migliorare il range di movimento.', 'Migliora la flessibilità delle spalle e riscalda l''articolazione.', 'Estendi le braccia di lato ed esegui piccoli cerchi controllati.', 'Mantieni le spalle rilassate e il busto stabile.', 'Evitare in caso di dolore acuto o infortunio alla spalla.', 'Eseguire cerchi troppo veloci o con troppa tensione al collo.'),
('arm-circles', 'zh', '手臂画圈', '专注于肩部的关节活动度练习，以提高运动范围。', '提高肩部灵活性并温暖关节。', '向两侧伸展双臂，进行小而受控的圆圈运动。', '保持肩膀放松，躯干稳定。', '如有肩部剧痛或受伤，请避免使用。', '画圈速度过快或颈部紧张过度。'),
('arm-circles', 'ja', 'アームサークル', '可動域を向上させるための、肩に焦点を当てた関節可動域エクササイズ。', '肩の柔軟性を高め、関節を温めます。', '腕を横に伸ばし、小さく制御された円を描きます。', '肩の力を抜き、体幹を安定させます。', '肩に激しい痛みや怪我がある場合は避けてください。', '回す速度が速すぎることや、首に力が入りすぎること。'),
('arm-circles', 'ko', '팔 돌리기', '가동 범위를 향상하기 위해 어깨에 집중하는 관절 가동성 운동.', '어깨 유연성을 높이고 관절을 풀어줍니다.', '팔을 옆으로 펴고 작고 통제된 원을 그립니다.', '어깨는 편안하게 유지하고 몸통은 안정시키세요.', '어깨에 급성 통증이나 부상이 있으면 피하세요.', '너무 빨리 돌리거나 목에 힘을 너무 주는 것.'),
('arm-circles', 'ar', 'تمرين تدوير الذراعين', 'تمرين حركة المفاصل يركز على الكتفين لتحسين نطاق الحركة.', 'يحسن مرونة الكتفين ويسخن المفصل.', 'مد ذراعيك إلى الجانبين وقم بعمل دوائر صغيرة ومحكمة.', 'حافظ على استرخاء كتفيك واستقرار جذعك.', 'تجنب التمرين في حالة وجود ألم حاد أو إصابة في الكتف.', 'القيام بالدوائر بسرعة كبيرة أو بوجود توتر زائد في الرقبة.'),
('arm-circles', 'hi', 'आर्म सर्कल्स', 'कंधों पर केंद्रित संयुक्त गतिशीलता व्यायाम ताकि गति की सीमा में सुधार हो सके।', 'कंधों के लचीलेपन में सुधार करता है और जोड़ को गर्म करता है।', 'अपनी बाजुओं को बगल में फैलाएं और छोटे, नियंत्रित गोले बनाएं।', 'अपने कंधों को आराम दें और धड़ को स्थिर रखें।', 'यदि कंधे में तीव्र दर्द या चोट हो तो न करें।', 'बहुत जल्दी गोले बनाना या गर्दन में बहुत अधिक तनाव रखना।'),
('arm-circles', 'ru', 'Круговые движения руками', 'Упражнение на подвижность суставов, сфокусированное на плечах для улучшения амплитуды.', 'Улучшает гибкость плеч и разогревает сустав.', 'Вытяните руки в стороны и выполняйте небольшие контролируемые круговые движения.', 'Держите плечи расслабленными, а торс стабильным.', 'Избегайте при острой боли или травме плеча.', 'Слишком быстрое выполнение или излишнее напряжение шеи.'),
('arm-circles', 'nl', 'Armcirkels', 'Gewrichtsmobiliteitsoefening gericht op de schouders voor een beter bewegingsbereik.', 'Verbetert schouderflexibiliteit en warmt het gewricht op.', 'Streik je armen opzij en maak kleine, gecontroleerde cirkels.', 'Houd je schouders ontspannen en je romp stabiel.', 'Vermijden bij acute pijn of schouderblessure.', 'Cirkels te snel uitvoeren of te veel spanning in de nek.'),
('arm-circles', 'sv', 'Armcirklar', 'Ledrörlighetsövning med fokus på axlarna för att förbättra rörelseomfånget.', 'Förbättrar axlarnas rörlighet och värmer upp leden.', 'Sträck ut armarna åt sidorna och gör små, kontrollerade cirklar.', 'Håll axlarna avslappnade och överkroppen stabil.', 'Undvik vid akut smärta eller axelskada.', 'Att göra cirklarna för snabbt eller med för mycket spänning i nacken.'),
('arm-circles', 'pl', 'Krążenia ramion', 'Ćwiczenie mobilności stawów skupione na barkach w celu poprawy zakresu ruchu.', 'Poprawia elastyczność barków i rozgrzewa staw.', 'Wyciągnij ramiona na boki i wykonuj małe, kontrolowane kółka.', 'Utrzymuj barki rozluźnione, a tułów stabilny.', 'Unikaj w przypadku ostrego bólu lub kontuzji barku.', 'Zbyt szybkie wykonywanie krążeń lub zbyt duże napięcie szyi.'),
('arm-circles', 'id', 'Lingkaran lengan', 'Latihan mobilitas sendi yang berfokus pada bahu untuk meningkatkan rentang gerak.', 'Meningkatkan fleksibilitas bahu dan menghangatkan sendi.', 'Rentangkan tangan ke samping dan buat lingkaran kecil yang terkontrol.', 'Jaga bahu tetap rileks dan batang tubuh stabil.', 'Hindari jika ada nyeri akut atau cedera bahu.', 'Membuat lingkaran terlalu cepat atau terlalu banyak ketegangan di leher.'),
('arm-circles', 'bn', 'আর্ম সার্কেল', 'কাঁধের মুভমেন্ট রেঞ্জ উন্নত করার জন্য একটি জয়েন্ট মোবিলিটি ব্যায়াম।', 'কাঁধের নমনীয়তা উন্নত করে এবং জয়েন্টকে ওয়ার্ম আপ করে।', 'হাত পাশে ছড়িয়ে দিন এবং ছোট, নিয়ন্ত্রিত বৃত্ত তৈরি করুন।', 'আপনার কাঁধ আরামদায়ক রাখুন এবং শরীর স্থির রাখুন।', 'কাঁধে তীব্র ব্যথা বা আঘাত থাকলে এড়িয়ে চলুন।', 'খুব দ্রুত বৃত্ত ঘোরানো বা ঘাড়ে অতিরিক্ত চাপ দেওয়া।'),
('arm-circles', 'vi', 'Xoay tay', 'Bài tập vận động khớp tập trung vào vai để cải thiện phạm vi chuyển động.', 'Cải thiện độ linh hoạt của vai và làm nóng khớp.', 'Duỗi tay sang hai bên và thực hiện các vòng tròn nhỏ có kiểm soát.', 'Giữ vai thư giãn và thân người ổn định.', 'Tránh tập nếu bị đau cấp tính hoặc chấn thương vai.', 'Xoay quá nhanh hoặc gây căng thẳng quá mức lên cổ.'),
('arm-circles', 'fa', 'چرخش بازوها (Arm circles)', 'تمرین تحرک مفاصل متمرکز بر شانه‌ها برای بهبود دامنه حرکتی.', 'انعطاف‌پذیری شانه‌ها را بهبود بخشیده و مفصل را گرم می‌کند.', 'بازوها را به طرفین باز کنید و دایره‌های کوچک و کنترل‌شده ایجاد کنید.', 'شانه‌ها را شل و بدن را ثابت نگه دارید.', 'در صورت درد حاد یا آسیب شانه از انجام آن خودداری کنید.', 'انجام دادن حرکات دایره‌ای خیلی سریع یا ایجاد تنش بیش از حد در گردن.');