-- Definición del ejercicio y sus recursos
INSERT INTO exercises (slug, img, video, difficulty) 
VALUES ('around-the-world-abs', 'around-the-world-abs.jpg', 'around-the-world-abs.mp4', 'advanced');

-- Relación: el ejercicio trabaja el grupo muscular 'abdominals'
INSERT INTO exercise_body_target (exercise_slug, body_target_slug) 
VALUES ('around-the-world-abs', 'abdominals');

-- Relación: no requiere máquina, por lo tanto no se inserta en exercise_machine
INSERT INTO exercise_alternative (exercise_slug, alternative_slug) 
VALUES ('around-the-world-abs', 'leg-raises');

-- Información multiidioma del ejercicio
INSERT INTO exercises_info (slug, lang, title, description, benefits, instructions, tips, restrictions, mistakes) VALUES 
('around-the-world-abs', 'es', 'Abdominales "alrededor del mundo"', 'Ejercicio dinámico de elevación de piernas que enfatiza la rotación y el control del core.', 'Fortalece todo el cinturón abdominal y mejora la movilidad de la cadera.', 'Recuéstate boca arriba, eleva las piernas rectas y dibuja círculos amplios en el aire.', 'Mantén la zona lumbar pegada al suelo durante todo el movimiento.', 'Evitar si hay dolor agudo en la zona lumbar.', 'Arquear la espalda al mover las piernas.\nRealizar los círculos demasiado rápido sin control.'),
('around-the-world-abs', 'en', 'Around the world abs', 'Dynamic leg raise exercise that emphasizes rotation and core control.', 'Strengthens the entire abdominal belt and improves hip mobility.', 'Lie on your back, raise your straight legs, and draw wide circles in the air.', 'Keep your lower back pressed against the floor throughout the movement.', 'Avoid if there is acute lower back pain.', 'Arching the back while moving your legs.\nPerforming circles too quickly without control.'),
('around-the-world-abs', 'pt', 'Abdominais "à volta do mundo"', 'Exercício dinâmico de elevação de pernas que enfatiza a rotação e o controlo do core.', 'Fortalece todo o cinto abdominal e melhora a mobilidade da anca.', 'Deite-se de costas, eleve as pernas esticadas e desenhe círculos amplos no ar.', 'Mantenha a zona lombar colada ao chão durante todo o movimento.', 'Evitar se houver dor aguda na zona lombar.', 'Arquear as costas ao mover as pernas.\nFazer os círculos demasiado rápido sem controlo.'),
('around-the-world-abs', 'fr', 'Abdominaux "autour du monde"', 'Exercice dynamique de levée de jambes qui met l''accent sur la rotation et le contrôle du tronc.', 'Renforce toute la ceinture abdominale et améliore la mobilité de la hanche.', 'Allongez-vous sur le dos, levez vos jambes tendues et dessinez de grands cercles dans les airs.', 'Gardez le bas du dos plaqué au sol pendant tout le mouvement.', 'À éviter en cas de douleur aiguë au bas du dos.', 'Cambrer le dos en bougeant les jambes.\nEffectuer les cercles trop rapidement sans contrôle.'),
('around-the-world-abs', 'de', 'Around-the-world-Bauchübung', 'Dynamische Beinhebeübung, die die Rotation und die Rumpfkontrolle betont.', 'Stärkt den gesamten Bauchgürtel und verbessert die Hüftmobilität.', 'Legen Sie sich auf den Rücken, heben Sie die gestreckten Beine an und zeichnen Sie große Kreise in die Luft.', 'Halten Sie den unteren Rücken während der gesamten Bewegung auf dem Boden.', 'Bei akuten Schmerzen im unteren Rücken vermeiden.', 'Durchstrecken des Rückens beim Bewegen der Beine.\nDie Kreise zu schnell und ohne Kontrolle ausführen.'),
('around-the-world-abs', 'it', 'Addominali "giro del mondo"', 'Esercizio dinamico di sollevamento gambe che enfatizza la rotazione e il controllo del core.', 'Rinforza l''intera fascia addominale e migliora la mobilità dell''anca.', 'Sdraiati sulla schiena, solleva le gambe tese e disegna ampi cerchi nell''aria.', 'Mantieni la zona lombare aderente al suolo durante tutto il movimento.', 'Evitare in caso di dolore acuto alla zona lombare.', 'Inarcare la schiena durante il movimento delle gambe.\nEseguire i cerchi troppo velocemente senza controllo.'),
('around-the-world-abs', 'zh', '“环球”腹肌练习', '动态抬腿练习，强调旋转和核心控制。', '增强整个腹部区域并改善髋关节活动度。', '仰卧，抬起伸直的双腿，在空中画大圆圈。', '运动过程中始终保持下背部贴地。', '如有下背部剧痛，请避免使用。', '移动腿部时拱背。\n动作过快且失去控制。'),
('around-the-world-abs', 'ja', '「アラウンド・ザ・ワールド」腹筋', '回転と体幹のコントロールを強調する動的なレッグレイズエクササイズ。', '腹部全体を強化し、股関節の可動性を向上させます。', '仰向けになり、両脚を伸ばしたまま持ち上げ、空中で大きな円を描きます。', '動作中、腰を常に床に押し付けた状態を保ちます。', '腰に激しい痛みがある場合は避けてください。', '脚を動かす際に背中が反ること。\nコントロールを失って速く回しすぎること。'),
('around-the-world-abs', 'ko', '“전 세계” 복근 운동', '회전과 코어 조절에 집중하는 동적 다리 올리기 운동.', '복부 전체를 강화하고 고관절 가동성을 향상합니다.', '천장을 보고 누워 다리를 펴서 올리고 공중에 큰 원을 그립니다.', '운동 내내 허리를 바닥에 밀착시키세요.', '허리에 급성 통증이 있으면 피하세요.', '다리를 움직일 때 등을 젖히는 것.\n통제 없이 너무 빨리 돌리는 것.'),
('around-the-world-abs', 'ar', 'تمرين البطن "حول العالم"', 'تمرين ديناميكي لرفع الساقين يركز على الدوران والتحكم في الجذع.', 'تقوية حزام البطن بالكامل وتحسين حركة الورك.', 'استلقِ على ظهرك، وارفع ساقيك المستقيمتين، وارسم دوائر واسعة في الهواء.', 'حافظ على أسفل ظهرك ملامسًا للأرض طوال فترة الحركة.', 'تجنب التمرين في حالة وجود ألم حاد في أسفل الظهر.', 'تقوس الظهر عند تحريك الساقين.\nأداء الدوائر بسرعة كبيرة دون تحكم.'),
('around-the-world-abs', 'hi', 'अराउंड द वर्ल्ड एब्स', 'डायनामिक लेग रेज व्यायाम जो रोटेशन और कोर नियंत्रण पर जोर देता है।', 'पूरे पेट के हिस्से को मजबूत करता है और कूल्हे की गतिशीलता में सुधार करता है।', 'पीठ के बल लेट जाएं, अपने सीधे पैर उठाएं और हवा में बड़े गोले बनाएं।', 'पूरी गति के दौरान अपनी निचली पीठ को फर्श पर दबाकर रखें।', 'यदि पीठ के निचले हिस्से में तीव्र दर्द हो तो न करें।', 'पैर हिलाते समय पीठ मोड़ना।\nबिना नियंत्रण के बहुत जल्दी गोले बनाना।'),
('around-the-world-abs', 'ru', 'Пресс "Вокруг света"', 'Динамическое упражнение на поднятие ног, подчеркивающее вращение и контроль кора.', 'Укрепляет весь пояс брюшного пресса и улучшает подвижность тазобедренных суставов.', 'Лягте на спину, поднимите прямые ноги и рисуйте широкие круги в воздухе.', 'Держите поясницу прижатой к полу на протяжении всего движения.', 'Избегайте при острой боли в пояснице.', 'Прогиб в спине при движении ног.\nСлишком быстрое выполнение кругов без контроля.'),
('around-the-world-abs', 'nl', 'Around the world abs', 'Dynamische beenhefoefening die de nadruk legt op rotatie en core-controle.', 'Versterkt de hele buikspiergordel en verbetert de heupmobiliteit.', 'Ga op je rug liggen, til je gestrekte benen op en teken grote cirkels in de lucht.', 'Houd je onderrug tijdens de hele beweging tegen de vloer gedrukt.', 'Vermijden bij acute pijn in de onderrug.', 'De rug hol trekken bij het bewegen van de benen.\nDe cirkels te snel en zonder controle uitvoeren.'),
('around-the-world-abs', 'sv', 'Around the world abs', 'Dynamisk benlyftsövning som betonar rotation och core-kontroll.', 'Stärker hela magmuskelbältet och förbättrar höftrörligheten.', 'Ligg på rygg, lyft de raka benen och rita stora cirklar i luften.', 'Håll ländryggen pressad mot golvet under hela rörelsen.', 'Undvik vid akut smärta i ländryggen.', 'Att svanka när benen flyttas.\nAtt göra cirklarna för snabbt utan kontroll.'),
('around-the-world-abs', 'pl', 'Around the world abs', 'Dynamiczne ćwiczenie unoszenia nóg kładące nacisk na rotację i kontrolę core.', 'Wzmacnia cały pas brzuszny i poprawia ruchomość bioder.', 'Połóż się na plecach, unieś wyprostowane nogi i rysuj w powietrzu duże koła.', 'Utrzymuj odcinek lędźwiowy przyciśnięty do podłogi przez cały czas.', 'Unikaj w przypadku ostrego bólu lędźwi.', 'Wyginanie pleców podczas poruszania nogami.\nZbyt szybkie wykonywanie kręgów bez kontroli.'),
('around-the-world-abs', 'id', 'Around the world abs', 'Latihan angkat kaki dinamis yang menekankan rotasi dan kontrol inti.', 'Memperkuat seluruh sabuk perut dan meningkatkan mobilitas pinggul.', 'Berbaring telentang, angkat kaki lurus dan gambar lingkaran lebar di udara.', 'Jaga punggung bawah tetap menekan lantai selama gerakan.', 'Hindari jika ada nyeri punggung bawah yang akut.', 'Melengkungkan punggung saat menggerakkan kaki.\nMelakukan lingkaran terlalu cepat tanpa kontrol.'),
('around-the-world-abs', 'bn', 'অ্যারাউন্ড দ্য ওয়ার্ল্ড অ্যাবস', 'একটি ডায়নামিক লেগ রেইজ ব্যায়াম যা ঘূর্ণন এবং কোর নিয়ন্ত্রণের উপর জোর দেয়।', 'পুরো পেটের অংশ শক্তিশালী করে এবং নিতম্বের গতিশীলতা উন্নত করে।', 'পিঠের উপর শুয়ে পড়ুন, সোজা পা তুলুন এবং বাতাসে বড় বৃত্ত আঁকুন।', 'পুরো নড়াচড়ার সময় আপনার নিচের পিঠ মেঝেতে চেপে রাখুন।', 'নিচের পিঠে তীব্র ব্যথা থাকলে এড়িয়ে চলুন।', 'পা সরানোর সময় পিঠ বাঁকানো।\nনিয়ন্ত্রণ ছাড়া খুব দ্রুত বৃত্ত আঁকা।'),
('around-the-world-abs', 'vi', 'Around the world abs', 'Bài tập nâng chân động nhấn mạnh vào xoay và kiểm soát cơ lõi.', 'Tăng cường toàn bộ vùng bụng và cải thiện khả năng linh hoạt của hông.', 'Nằm ngửa, nâng thẳng chân và vẽ những vòng tròn lớn trong không trung.', 'Luôn ép sát thắt lưng xuống sàn trong suốt quá trình tập.', 'Tránh tập nếu bị đau lưng dưới cấp tính.', 'Võng lưng khi di chuyển chân.\nThực hiện vòng tròn quá nhanh mà không kiểm soát.'),
('around-the-world-abs', 'fa', 'تمرین شکم "دور دنیا" (Around the world abs)', 'تمرین دینامیک بالا آوردن پا که بر چرخش و کنترل هسته تأکید دارد.', 'کل کمربند شکمی را تقویت کرده و تحرک لگن را بهبود می‌بخشد.', 'به پشت دراز بکشید، پاهای صاف را بالا ببرید و دایره‌های بزرگی در هوا رسم کنید.', 'در طول حرکت، کمر خود را به زمین بچسبانید.', 'در صورت درد حاد در کمر از انجام آن خودداری کنید.', 'قوس دادن به کمر هنگام حرکت دادن پاها.\nانجام سریع و بدون کنترل دایره‌ها.');