-- Definición del ejercicio y sus recursos
INSERT INTO exercises (slug, img, video, difficulty) 
VALUES ('back-extension', 'back-extension.jpg', 'back-extension.mp4', 'beginner');

-- Relación: el ejercicio trabaja el grupo muscular 'lower_back'
INSERT INTO exercise_body_target (exercise_slug, body_target_slug) 
VALUES ('back-extension', 'lower_back');

-- Relación: no requiere máquina
INSERT INTO exercise_alternative (exercise_slug, alternative_slug) 
VALUES ('back-extension', 'superman');

-- Información multiidioma del ejercicio
INSERT INTO exercises_info (slug, lang, title, description, benefits, instructions, tips, restrictions, mistakes) VALUES 
('back-extension', 'es', 'Extensión de espalda', 'Ejercicio básico para fortalecer los músculos erectores de la columna y mejorar la postura.', 'Fortalece la zona lumbar y reduce el riesgo de dolor de espalda.', 'Túmbate boca abajo, manos tras la nuca o a los lados, eleva suavemente el pecho del suelo.', 'Realiza el movimiento lentamente y sin forzar el cuello.', 'Evitar si hay lesiones graves en la columna.', 'Dar tirones bruscos o levantar el pecho demasiado alto forzando las cervicales.'),
('back-extension', 'en', 'Back extension', 'Basic exercise to strengthen the erector spinae muscles and improve posture.', 'Strengthens the lower back and reduces the risk of back pain.', 'Lie face down, hands behind your head or at your sides, gently lift your chest off the floor.', 'Perform the movement slowly and without straining your neck.', 'Avoid if there are serious spinal injuries.', 'Jerking movements or lifting the chest too high, straining the cervical spine.'),
('back-extension', 'pt', 'Extensão de costas', 'Exercício básico para fortalecer os músculos eretores da coluna e melhorar a postura.', 'Fortalece a zona lombar e reduz o risco de dores nas costas.', 'Deite-se de barriga para baixo, mãos atrás da nuca ou ao lado, eleve suavemente o peito do chão.', 'Realize o movimento lentamente e sem forçar o pescoço.', 'Evitar se houver lesões graves na coluna.', 'Dar puxões bruscos ou elevar o peito demasiado alto forçando as cervicais.'),
('back-extension', 'fr', 'Extension du dos', 'Exercice de base pour renforcer les muscles érecteurs du rachis et améliorer la posture.', 'Renforce le bas du dos et réduit le risque de mal de dos.', 'Allongez-vous sur le ventre, mains derrière la tête ou sur les côtés, levez doucement la poitrine du sol.', 'Effectuez le mouvement lentement sans forcer sur le cou.', 'À éviter en cas de lésions graves de la colonne vertébrale.', 'Faire des mouvements brusques ou lever la poitrine trop haut en forçant sur les cervicales.'),
('back-extension', 'de', 'Rückenstrecken', 'Grundübung zur Stärkung der Rückenstreckmuskulatur und Verbesserung der Körperhaltung.', 'Stärkt den unteren Rücken und senkt das Risiko für Rückenschmerzen.', 'Legen Sie sich auf den Bauch, Hände hinter den Kopf oder an die Seite, heben Sie sanft die Brust vom Boden ab.', 'Führen Sie die Bewegung langsam aus, ohne den Nacken zu belasten.', 'Bei schweren Wirbelsäulenverletzungen vermeiden.', 'Ruckartige Bewegungen oder zu hohes Anheben der Brust unter Belastung der Halswirbelsäule.'),
('back-extension', 'it', 'Estensione della schiena', 'Esercizio base per rinforzare i muscoli erettori della colonna vertebrale e migliorare la postura.', 'Rinforza la zona lombare e riduce il rischio di mal di schiena.', 'Sdraiati a pancia in giù, mani dietro la nuca o sui fianchi, solleva delicatamente il petto da terra.', 'Esegui il movimento lentamente senza forzare il collo.', 'Evitare in caso di gravi lesioni alla colonna vertebrale.', 'Fare scatti bruschi o sollevare troppo il petto sforzando le cervicali.'),
('back-extension', 'zh', '背部伸展', '加强脊柱竖脊肌并改善姿势的基础练习。', '增强下背部并降低背痛风险。', '俯卧，双手放于脑后或身体两侧，轻轻抬起胸部离开地面。', '缓慢进行动作，不要拉伤颈部。', '如有严重脊柱损伤，请避免使用。', '动作生硬或抬胸过高拉伤颈椎。'),
('back-extension', 'ja', 'バックエクステンション', '脊柱起立筋を強化し、姿勢を改善するための基本エクササイズ。', '腰部を強化し、腰痛のリスクを軽減します。', 'うつ伏せになり、手を頭の後ろか体の横に置き、胸を優しく床から持ち上げます。', '首に負担をかけず、ゆっくりと動作を行います。', '脊椎に深刻な怪我がある場合は避けてください。', '反動を使うことや、首に負担がかかるほど胸を高く上げすぎること。'),
('back-extension', 'ko', '백 익스텐션', '척추 기립근을 강화하고 자세를 교정하는 기본 운동.', '허리를 강화하고 허리 통증 위험을 줄입니다.', '엎드린 상태에서 손을 머리 뒤나 옆에 두고, 가슴을 바닥에서 부드럽게 들어 올립니다.', '목에 무리를 주지 말고 천천히 동작하세요.', '척추에 심각한 부상이 있다면 피하세요.', '반동을 주거나 목에 무리가 갈 정도로 가슴을 너무 높이 드는 것.'),
('back-extension', 'ar', 'تمرين تمديد الظهر', 'تمرين أساسي لتقوية عضلات ناصبة الفقار وتحسين القوام.', 'يقوي أسفل الظهر ويقلل من خطر آلام الظهر.', 'استلقِ على بطنك، وضع يديك خلف رأسك أو بجانبك، وارفع صدرك برفق عن الأرض.', 'نفذ الحركة ببطء ودون الضغط على الرقبة.', 'تجنب التمرين في حالة وجود إصابات خطيرة في العمود الفقري.', 'القيام بحركات مفاجئة أو رفع الصدر عاليًا جدًا والضغط على الفقرات العنقية.'),
('back-extension', 'hi', 'बैक एक्सटेंशन', 'स्पाइनल इरेक्टर मांसपेशियों को मजबूत करने और मुद्रा में सुधार करने के लिए मूल व्यायाम।', 'पीठ के निचले हिस्से को मजबूत करता है और पीठ दर्द का खतरा कम करता है।', 'पेट के बल लेट जाएं, हाथ अपने सिर के पीछे या बगल में रखें, धीरे से अपनी छाती को फर्श से ऊपर उठाएं।', 'गर्दन पर दबाव डाले बिना गति को धीरे-धीरे करें।', 'यदि रीढ़ की हड्डी में गंभीर चोट हो तो न करें।', 'झटकेदार आंदोलन या छाती को बहुत ऊपर उठाना जिससे गर्दन पर दबाव पड़े।'),
('back-extension', 'ru', 'Разгибание спины', 'Базовое упражнение для укрепления мышц-выпрямителей позвоночника и улучшения осанки.', 'Укрепляет поясницу и снижает риск болей в спине.', 'Лягте на живот, руки за головой или по бокам, плавно поднимите грудь от пола.', 'Выполняйте движение медленно, не напрягая шею.', 'Избегайте при серьезных травмах позвоночника.', 'Резкие движения или слишком высокий подъем груди с нагрузкой на шейный отдел.'),
('back-extension', 'nl', 'Rugextensie', 'Basisoefening om de rugstrekkers te versterken en de houding te verbeteren.', 'Versterkt de onderrug en vermindert het risico op rugpijn.', 'Ga op je buik liggen, handen achter je hoofd of opzij, til je borst voorzichtig van de vloer.', 'Voer de beweging langzaam uit zonder je nek te belasten.', 'Vermijden bij ernstige rugblessures.', 'Schokkerige bewegingen of de borst te hoog optillen waardoor de nekwervels worden belast.'),
('back-extension', 'sv', 'Rygglyft', 'Grundläggande övning för att stärka ryggsträckarna och förbättra hållningen.', 'Stärker ländryggen och minskar risken för ryggsmärta.', 'Ligg på mage, händer bakom huvudet eller vid sidorna, lyft försiktigt bröstet från golvet.', 'Utför rörelsen långsamt utan att belasta nacken.', 'Undvik vid allvarliga ryggradsskador.', 'Ryckiga rörelser eller att lyfta bröstet för högt så att nacken belastas.'),
('back-extension', 'pl', 'Wyprosty grzbietu', 'Podstawowe ćwiczenie wzmacniające mięśnie prostowniki grzbietu i poprawiające postawę.', 'Wzmacnia dół pleców i zmniejsza ryzyko bólów kręgosłupa.', 'Połóż się na brzuchu, dłonie za głową lub po bokach, delikatnie unieś klatkę piersiową nad podłogę.', 'Wykonuj ruch powoli, nie obciążając szyi.', 'Unikaj w przypadku poważnych urazów kręgosłupa.', 'Gwałtowne ruchy lub zbyt wysokie unoszenie klatki piersiowej obciążające szyję.'),
('back-extension', 'id', 'Back extension', 'Latihan dasar untuk memperkuat otot erector spinae dan memperbaiki postur.', 'Memperkuat punggung bawah dan mengurangi risiko sakit punggung.', 'Berbaring tengkurap, tangan di belakang kepala atau di samping, angkat dada perlahan dari lantai.', 'Lakukan gerakan perlahan tanpa membebani leher.', 'Hindari jika ada cedera tulang belakang yang serius.', 'Gerakan menyentak atau mengangkat dada terlalu tinggi sehingga membebani leher.'),
('back-extension', 'bn', 'ব্যাক এক্সটেনশন', 'মেরুদণ্ডের পেশি শক্তিশালী করার এবং অঙ্গভঙ্গি উন্নত করার একটি প্রাথমিক ব্যায়াম।', 'পিঠের নিচের অংশ শক্তিশালী করে এবং পিঠ ব্যথার ঝুঁকি কমায়।', 'পেট ভরে শুয়ে পড়ুন, হাত মাথার পিছনে বা পাশে রাখুন, ধীরে ধীরে বুক মেঝে থেকে তুলুন।', 'ঘাড়ে চাপ না দিয়ে ধীরে ধীরে ব্যায়াম করুন।', 'মেরুদণ্ডে গুরুতর আঘাত থাকলে এড়িয়ে চলুন।', 'ঝাঁকুনি দিয়ে ব্যায়াম করা বা বুক খুব উঁচুতে তোলা যা ঘাড়ে চাপ দেয়।'),
('back-extension', 'vi', 'Back extension', 'Bài tập cơ bản để củng cố các cơ dựng gai sống và cải thiện tư thế.', 'Tăng cường lưng dưới và giảm nguy cơ đau lưng.', 'Nằm sấp, tay đặt sau đầu hoặc hai bên, nâng ngực nhẹ nhàng khỏi sàn.', 'Thực hiện động tác chậm rãi mà không gây căng thẳng cho cổ.', 'Tránh tập nếu bị chấn thương cột sống nghiêm trọng.', 'Chuyển động giật cục hoặc nâng ngực quá cao làm căng cột sống cổ.'),
('back-extension', 'fa', 'تمرین کشش کمر (Back extension)', 'تمرین پایه برای تقویت عضلات راست‌کننده ستون فقرات و بهبود وضعیت بدنی.', 'کمر را تقویت کرده و خطر کمردرد را کاهش می‌دهد.', 'روی شکم دراز بکشید، دست‌ها را پشت سر یا کنار بدن قرار دهید و قفسه سینه را به آرامی از زمین بلند کنید.', 'حرکت را به آرامی و بدون فشار به گردن انجام دهید.', 'در صورت آسیب‌های جدی ستون فقرات از انجام آن خودداری کنید.', 'حرکات ناگهانی یا بلند کردن بیش از حد قفسه سینه که باعث فشار به مهره‌های گردنی می‌شود.');