-- Definición del ejercicio y sus recursos
INSERT INTO exercises (slug, img, video, difficulty) 
VALUES ('bear-crawl', 'bear-crawl.jpg', 'bear-crawl.mp4', 'intermediate');

-- Relación: el ejercicio trabaja el grupo muscular 'full-body'
INSERT INTO exercise_body_target (exercise_slug, body_target_slug) 
VALUES ('bear-crawl', 'full_body');

-- Relación: no requiere máquina, por lo tanto no se inserta en exercise_machine
INSERT INTO exercise_alternative (exercise_slug, alternative_slug) 
VALUES ('bear-crawl', 'plank');

-- Información multiidioma del ejercicio
INSERT INTO exercises_info (slug, lang, title, description, benefits, instructions, tips, restrictions, mistakes) VALUES 
('bear-crawl', 'es', 'Gateo de oso (Bear Crawl)', 'Ejercicio de movimiento funcional que exige coordinación, fuerza en el core y estabilidad de hombros.', 'Mejora la coordinación, la resistencia cardiovascular y la estabilidad del core.', 'En posición de cuatro patas, eleva ligeramente las rodillas del suelo y avanza moviendo brazo y pierna opuestos.', 'Mantén la espalda lo más plana posible durante el movimiento.', 'Evitar si hay dolor agudo en muñecas o rodillas.', 'Dejar subir la cadera demasiado alto o mover el mismo brazo y pierna a la vez.'),
('bear-crawl', 'en', 'Bear crawl', 'Functional movement exercise that requires coordination, core strength, and shoulder stability.', 'Improves coordination, cardiovascular endurance, and core stability.', 'In a quadruped position, lift your knees slightly off the floor and move forward by moving opposite arm and leg.', 'Keep your back as flat as possible during the movement.', 'Avoid if there is acute wrist or knee pain.', 'Letting the hips rise too high or moving the same arm and leg at the same time.'),
('bear-crawl', 'pt', 'Rastejo de urso (Bear Crawl)', 'Exercício de movimento funcional que exige coordenação, força no core e estabilidade dos ombros.', 'Melhora a coordenação, a resistência cardiovascular e a estabilidade do core.', 'Na posição de quatro apoios, eleve ligeiramente os joelhos do chão e avance movendo braço e perna opostos.', 'Mantenha as costas o mais planas possível durante o movimento.', 'Evitar se houver dor aguda nos pulsos ou joelhos.', 'Deixar a anca subir demasiado ou mover o mesmo braço e perna ao mesmo tempo.'),
('bear-crawl', 'fr', 'Ramper de l''ours (Bear crawl)', 'Exercice de mouvement fonctionnel qui exige de la coordination, de la force du tronc et de la stabilité des épaules.', 'Améliore la coordination, l''endurance cardiovasculaire et la stabilité du tronc.', 'En position à quatre pattes, soulevez légèrement les genoux du sol et avancez en déplaçant le bras et la jambe opposés.', 'Gardez le dos le plus plat possible pendant le mouvement.', 'À éviter en cas de douleur aiguë aux poignets ou aux genoux.', 'Laisser les hanches monter trop haut ou déplacer le même bras et la même jambe en même temps.'),
('bear-crawl', 'de', 'Bärengang (Bear crawl)', 'Funktionelle Bewegungsübung, die Koordination, Rumpfkraft und Schulterstabilität erfordert.', 'Verbessert die Koordination, die kardiovaskuläre Ausdauer und die Rumpfstabilität.', 'Gehen Sie in den Vierfüßlerstand, heben Sie die Knie leicht vom Boden ab und bewegen Sie sich vorwärts, indem Sie den gegenüberliegenden Arm und das gegenüberliegende Bein bewegen.', 'Halten Sie den Rücken während der Bewegung so flach wie möglich.', 'Bei akuten Handgelenks- oder Knieschmerzen vermeiden.', 'Die Hüfte zu hoch kommen lassen oder denselben Arm und dasselbe Bein gleichzeitig bewegen.'),
('bear-crawl', 'it', 'Camminata dell''orso (Bear crawl)', 'Esercizio di movimento funzionale che richiede coordinazione, forza nel core e stabilità delle spalle.', 'Migliora la coordinazione, la resistenza cardiovascolare e la stabilità del core.', 'In posizione quadrupedica, solleva leggermente le ginocchia da terra e avanza muovendo braccio e gamba opposti.', 'Mantieni la schiena il più piatta possibile durante il movimento.', 'Evitare in caso di dolore acuto ai polsi o alle ginocchia.', 'Lasciare che i fianchi salgano troppo in alto o muovere lo stesso braccio e la stessa gamba contemporaneamente.'),
('bear-crawl', 'zh', '熊爬 (Bear crawl)', '功能性运动练习，需要协调性、核心力量和肩部稳定性。', '提高协调性、心血管耐力和核心稳定性。', '四足着地，膝盖微离地面，通过移动对侧手臂和腿向前爬行。', '运动过程中尽量保持背部平直。', '如有手腕或膝盖剧痛，请避免使用。', '臀部抬得太高或同时移动同一侧的手臂和腿。'),
('bear-crawl', 'ja', 'ベアクロール', '協調性、体幹力、肩の安定性を必要とする機能的な運動エクササイズ。', '協調性、心肺持久力、体幹の安定性を向上させます。', '四つん這いの姿勢から膝を床から少し浮かせ、対角の手と脚を動かして前進します。', '動作中、背中はできるだけ平らに保ちます。', '手首や膝に激しい痛みがある場合は避けてください。', '腰を上げすぎることや、同じ側の手と脚を同時に動かすこと。'),
('bear-crawl', 'ko', '베어 크롤', '협응력, 코어 근력, 어깨 안정성을 요구하는 기능적 운동.', '협응력, 심혈관 지구력, 코어 안정성을 향상합니다.', '네발기기 자세에서 무릎을 바닥에서 살짝 띄우고, 반대쪽 팔과 다리를 움직여 앞으로 나아갑니다.', '동작 중 등은 최대한 평평하게 유지하세요.', '손목이나 무릎에 급성 통증이 있으면 피하세요.', '엉덩이를 너무 높이 올리거나 같은 쪽 팔과 다리를 동시에 움직이는 것.'),
('bear-crawl', 'ar', 'زحف الدب (Bear crawl)', 'تمرين حركة وظيفية يتطلب التنسيق وقوة الجذع واستقرار الكتفين.', 'تحسين التنسيق والقدرة على التحمل القلبي الوعائي واستقرار الجذع.', 'في وضع الزحف، ارفع ركبتيك قليلاً عن الأرض وتحرك للأمام عن طريق تحريك الذراع والساق المتقابلين.', 'حافظ على استقامة ظهرك قدر الإمكان أثناء الحركة.', 'تجنب التمرين في حالة وجود ألم حاد في المعصمين أو الركبتين.', 'ترك الوركين يرتفعان عاليًا جدًا أو تحريك الذراع والساق نفسه في نفس الوقت.'),
('bear-crawl', 'hi', 'बियर क्रॉल', 'कार्यात्मक गति व्यायाम जिसे समन्वय, कोर शक्ति और कंधे की स्थिरता की आवश्यकता होती है।', 'समन्वय, हृदय सहनशक्ति और कोर स्थिरता में सुधार करता है।', 'चार पैरों वाली स्थिति में, अपने घुटनों को फर्श से थोड़ा ऊपर उठाएं और विपरीत हाथ और पैर को हिलाकर आगे बढ़ें।', 'गति के दौरान अपनी पीठ को जितना संभव हो सके सपाट रखें।', 'यदि कलाई या घुटने में तीव्र दर्द हो तो न करें।', 'कूल्हों को बहुत ऊपर उठने देना या एक ही हाथ और पैर को एक साथ हिलाना।'),
('bear-crawl', 'ru', 'Медвежья походка (Bear crawl)', 'Функциональное упражнение, требующее координации, силы кора и стабильности плеч.', 'Улучшает координацию, сердечно-сосудистую выносливость и стабильность кора.', 'В положении на четвереньках слегка приподнимите колени от пола и двигайтесь вперед, переставляя противоположные руку и ногу.', 'Держите спину максимально прямой во время движения.', 'Избегайте при острой боли в запястьях или коленях.', 'Слишком высокий подъем бедер или одновременное движение руки и ноги с одной стороны.'),
('bear-crawl', 'nl', 'Bear crawl', 'Functionele bewegingsoefening die coördinatie, core-kracht en schouderstabiliteit vereist.', 'Verbetert de coördinatie, cardiovasculair uithoudingsvermogen en core-stabiliteit.', 'Ga op handen en voeten staan, til je knieën iets van de vloer en beweeg vooruit door de tegenovergestelde arm en been te verplaatsen.', 'Houd je rug tijdens de beweging zo recht mogelijk.', 'Vermijden bij acute pijn in polsen of knieën.', 'Heupen te hoog laten komen of dezelfde arm en been tegelijkertijd bewegen.'),
('bear-crawl', 'sv', 'Bear crawl', 'Funktionell rörelseövning som kräver koordination, core-styrka och axelstabilitet.', 'Förbättrar koordination, kondition och core-stabilitet.', 'Stå på alla fyra, lyft knäna något från golvet och gå framåt genom att flytta motsatt arm och ben.', 'Håll ryggen så rak som möjligt under rörelsen.', 'Undvik vid akut smärta i handleder eller knän.', 'Att låta höfterna komma för högt eller att flytta samma arm och ben samtidigt.'),
('bear-crawl', 'pl', 'Bear crawl', 'Ćwiczenie ruchowe funkcjonalne wymagające koordynacji, siły core i stabilności barków.', 'Poprawia koordynację, wytrzymałość sercowo-naczyniową i stabilność core.', 'W pozycji czworaczej unieś lekko kolana nad podłogę i poruszaj się do przodu, przemieszczając przeciwległą rękę i nogę.', 'Utrzymuj plecy tak proste, jak to możliwe podczas ruchu.', 'Unikaj w przypadku ostrego bólu nadgarstków lub kolan.', 'Zbyt wysokie unoszenie bioder lub poruszanie tą samą ręką i nogą jednocześnie.'),
('bear-crawl', 'id', 'Bear crawl', 'Latihan gerakan fungsional yang membutuhkan koordinasi, kekuatan inti, dan stabilitas bahu.', 'Meningkatkan koordinasi, daya tahan kardiovaskular, dan stabilitas inti.', 'Dalam posisi merangkak, angkat lutut sedikit dari lantai dan bergerak maju dengan menggerakkan lengan dan kaki yang berlawanan.', 'Jaga punggung se-datar mungkin selama gerakan.', 'Hindari jika ada nyeri akut pada pergelangan tangan atau lutut.', 'Membiarkan pinggul naik terlalu tinggi atau menggerakkan lengan dan kaki yang sama secara bersamaan.'),
('bear-crawl', 'bn', 'বিয়ার ক্রল', 'একটি ফাংশনাল মুভমেন্ট ব্যায়াম যার জন্য সমন্বয়, কোর শক্তি এবং কাঁধের স্থিতিশীলতা প্রয়োজন।', 'সমন্বয়, কার্ডিওভাসকুলার সহনশীলতা এবং কোর স্থিতিশীলতা উন্নত করে।', 'চার পায়ে হাঁটার পজিশনে, হাঁটু মেঝে থেকে একটু উপরে তুলে বিপরীত হাত ও পা নাড়াচাড়া করে এগিয়ে যান।', 'ব্যায়ামের সময় আপনার পিঠ যতটা সম্ভব সমান রাখুন।', 'কব্জি বা হাঁটুতে তীব্র ব্যথা থাকলে এড়িয়ে চলুন।', 'কোমর খুব উঁচুতে তোলা বা একই দিকের হাত ও পা একসাথে সরানো।'),
('bear-crawl', 'vi', 'Bear crawl', 'Bài tập chuyển động chức năng đòi hỏi sự phối hợp, sức mạnh cơ lõi và độ ổn định của vai.', 'Cải thiện sự phối hợp, sức bền tim mạch và độ ổn định cơ lõi.', 'Ở tư thế bò, nhấc đầu gối lên khỏi sàn một chút và tiến về phía trước bằng cách di chuyển tay và chân đối diện.', 'Giữ lưng phẳng nhất có thể trong khi di chuyển.', 'Tránh tập nếu bị đau cổ tay hoặc đầu gối cấp tính.', 'Để hông nâng lên quá cao hoặc di chuyển cùng một tay và chân cùng lúc.'),
('bear-crawl', 'fa', 'خزیدن خرسی (Bear crawl)', 'تمرین حرکتی عملکردی که نیازمند هماهنگی، قدرت هسته و ثبات شانه‌ها است.', 'هماهنگی، استقامت قلبی عروقی و ثبات هسته را بهبود می‌بخشد.', 'در وضعیت چهار دست و پا، زانوها را کمی از زمین بلند کنید و با حرکت دادن دست و پای مخالف، به جلو حرکت کنید.', 'در طول حرکت پشت خود را تا حد ممکن صاف نگه دارید.', 'در صورت درد حاد در مچ دست یا زانو از انجام آن خودداری کنید.', 'بالا رفتن بیش از حد لگن یا حرکت دادن همزمان دست و پای یک طرف.');