-- Definición del ejercicio y sus recursos
INSERT INTO exercises (slug, img, video, difficulty) 
VALUES ('bicycle-crunches', 'bicycle-crunches.jpg', 'bicycle-crunches.mp4', 'intermediate');

-- Relación: el ejercicio trabaja el grupo muscular 'abdominals'
INSERT INTO exercise_body_target (exercise_slug, body_target_slug) 
VALUES ('bicycle-crunches', 'abdominals');

-- Relación: no requiere máquina
INSERT INTO exercise_alternative (exercise_slug, alternative_slug) 
VALUES ('bicycle-crunches', 'crunch');

-- Información multiidioma del ejercicio
INSERT INTO exercises_info (slug, lang, title, description, benefits, instructions, tips, restrictions, mistakes) VALUES 
('bicycle-crunches', 'es', 'Bicycle crunches', 'Ejercicio abdominal que imita el pedaleo, enfocándose en los músculos rectos y oblicuos del abdomen.', 'Fortalece el core y mejora la rotación del tronco.', 'Tumbado, acerca el codo opuesto a la rodilla contraria mientras estiras la otra pierna.', 'Mantén la zona lumbar pegada al suelo y controla el movimiento.', 'Evitar si hay dolor agudo en la zona lumbar o cuello.', 'Tirar del cuello con las manos o mover las piernas demasiado rápido sin control.'),
('bicycle-crunches', 'en', 'Bicycle crunches', 'Abdominal exercise that mimics pedaling, focusing on the rectus abdominis and obliques.', 'Strengthens the core and improves torso rotation.', 'Lying down, bring the opposite elbow to the opposite knee while extending the other leg.', 'Keep your lower back pressed to the floor and control the movement.', 'Avoid if there is acute lower back or neck pain.', 'Pulling on the neck with your hands or moving your legs too fast without control.'),
('bicycle-crunches', 'pt', 'Bicycle crunches', 'Exercício abdominal que imita a pedalada, focando nos músculos retos e oblíquos do abdómen.', 'Fortalece o core e melhora a rotação do tronco.', 'Deitado, aproxime o cotovelo oposto ao joelho contrário enquanto estica a outra perna.', 'Mantenha a zona lombar colada ao chão e controle o movimento.', 'Evitar se houver dor aguda na zona lombar ou pescoço.', 'Puxar o pescoço com as mãos ou mover as pernas demasiado rápido sem controlo.'),
('bicycle-crunches', 'fr', 'Bicycle crunches', 'Exercice abdominal imitant le pédalage, ciblant les muscles droits et obliques de l''abdomen.', 'Renforce le tronc et améliore la rotation du buste.', 'Allongé, ramenez le coude opposé vers le genou contraire tout en étendant l''autre jambe.', 'Gardez le bas du dos plaqué au sol et contrôlez le mouvement.', 'À éviter en cas de douleur aiguë au bas du dos ou au cou.', 'Tirer sur le cou avec les mains ou bouger les jambes trop vite sans contrôle.'),
('bicycle-crunches', 'de', 'Bicycle Crunches', 'Bauchübung, die das Radfahren imitiert und die geraden und schrägen Bauchmuskeln anspricht.', 'Stärkt die Körpermitte und verbessert die Rumpfrotation.', 'Legen Sie sich hin und führen Sie den gegenüberliegenden Ellbogen zum Knie, während Sie das andere Bein ausstrecken.', 'Halten Sie den unteren Rücken auf dem Boden und kontrollieren Sie die Bewegung.', 'Bei akuten Schmerzen im unteren Rücken oder Nacken vermeiden.', 'Am Nacken ziehen oder die Beine zu schnell ohne Kontrolle bewegen.'),
('bicycle-crunches', 'it', 'Bicycle crunches', 'Esercizio addominale che imita la pedalata, concentrandosi sui muscoli retti e obliqui dell''addome.', 'Rinforza il core e migliora la rotazione del busto.', 'Sdraiato, porta il gomito opposto verso il ginocchio contrario mentre distendi l''altra gamba.', 'Mantieni la zona lombare aderente al suolo e controlla il movimento.', 'Evitare in caso di dolore acuto alla zona lombare o al collo.', 'Tirare il collo con le mani o muovere le gambe troppo velocemente senza controllo.'),
('bicycle-crunches', 'zh', '空中自行车', '模仿骑行动作的腹肌练习，重点锻炼腹直肌和腹斜肌。', '增强核心力量并改善躯干旋转。', '仰卧，将一侧手肘向对侧膝盖靠拢，同时伸展另一条腿。', '保持下背部贴地并控制动作幅度。', '如有下背部或颈部剧痛，请避免使用。', '用手拉扯颈部或动作过快且失去控制。'),
('bicycle-crunches', 'ja', 'バイシクルクランチ', 'ペダリングを模した腹筋運動で、腹直筋と腹斜筋に焦点を当てます。', '体幹を強化し、体幹の回転を改善します。', '仰向けになり、対角の肘を膝に近づけながら、もう一方の脚を伸ばします。', '腰を床に押し付けた状態を保ち、動作をコントロールします。', '腰や首に激しい痛みがある場合は避けてください。', '手で首を引くことや、コントロールを失って速く回しすぎること。'),
('bicycle-crunches', 'ko', '바이시클 크런치', '페달 밟기를 모방한 복근 운동으로, 복직근과 복사근에 집중합니다.', '코어를 강화하고 몸통 회전을 개선합니다.', '누운 상태에서 반대쪽 팔꿈치를 반대쪽 무릎으로 가져오면서 다른 다리를 뻗습니다.', '허리를 바닥에 밀착시키고 동작을 통제하세요.', '허리나 목에 급성 통증이 있으면 피하세요.', '손으로 목을 잡아당기거나 통제 없이 다리를 너무 빨리 움직이는 것.'),
('bicycle-crunches', 'ar', 'تمرين الدراجة (Bicycle crunches)', 'تمرين للبطن يحاكي ركوب الدراجة، ويركز على عضلات البطن المستقيمة والمائلة.', 'يقوي الجذع ويحسن دوران الجذع.', 'استلقِ وقرب الكوع المعاكس إلى الركبة المقابلة مع مد الساق الأخرى.', 'حافظ على ملامسة أسفل ظهرك للأرض وتحكم في الحركة.', 'تجنب التمرين في حالة وجود ألم حاد في أسفل الظهر أو الرقبة.', 'الشد على الرقبة باليدين أو تحريك الساقين بسرعة كبيرة دون تحكم.'),
('bicycle-crunches', 'hi', 'बाइसिकल क्रंचेस', 'पेट का व्यायाम जो साइकिल चलाने की नकल करता है, जो पेट की सीधी और तिरछी मांसपेशियों पर केंद्रित है।', 'कोर को मजबूत करता है और धड़ के रोटेशन में सुधार करता है।', 'लेट जाएं, विपरीत कोहनी को विपरीत घुटने के पास लाएं और दूसरे पैर को सीधा करें।', 'अपनी निचली पीठ को फर्श पर दबाकर रखें और गति को नियंत्रित करें।', 'यदि पीठ के निचले हिस्से या गर्दन में तीव्र दर्द हो तो न करें।', 'हाथों से गर्दन को खींचना या नियंत्रण के बिना पैरों को बहुत जल्दी हिलाना।'),
('bicycle-crunches', 'ru', 'Велосипед (Bicycle crunches)', 'Упражнение на пресс, имитирующее езду на велосипеде, с акцентом на прямые и косые мышцы живота.', 'Укрепляет кор и улучшает вращение торса.', 'Лежа, приближайте противоположный локоть к колену, выпрямляя другую ногу.', 'Держите поясницу прижатой к полу и контролируйте движение.', 'Избегайте при острой боли в пояснице или шее.', 'Тянуть шею руками или двигать ногами слишком быстро без контроля.'),
('bicycle-crunches', 'nl', 'Bicycle crunches', 'Buikspieroefening die fietsen nabootst, gericht op de rechte en schuine buikspieren.', 'Versterkt de core en verbetert de romp-rotatie.', 'Liggend, breng de tegenovergestelde elleboog naar de knie terwijl je het andere been uitstrekt.', 'Houd je onderrug tegen de vloer gedrukt en controleer de beweging.', 'Vermijden bij acute pijn in de onderrug of nek.', 'Aan de nek trekken met je handen of de benen te snel zonder controle bewegen.'),
('bicycle-crunches', 'sv', 'Bicycle crunches', 'Magövning som efterliknar cykling, med fokus på raka och sneda magmuskler.', 'Stärker core och förbättrar bålrotation.', 'Liggande, för motsatt armbåge mot motsatt knä medan du sträcker ut det andra benet.', 'Håll ländryggen pressad mot golvet och kontrollera rörelsen.', 'Undvik vid akut smärta i ländrygg eller nacke.', 'Att dra i nacken med händerna eller röra benen för snabbt utan kontroll.'),
('bicycle-crunches', 'pl', 'Bicycle crunches', 'Ćwiczenie na mięśnie brzucha imitujące pedałowanie, skupiające się na mięśniach prostych i skośnych.', 'Wzmacnia core i poprawia rotację tułowia.', 'W pozycji leżącej zbliżaj przeciwny łokieć do kolana, prostując przy tym drugą nogę.', 'Utrzymuj odcinek lędźwiowy przyciśnięty do podłogi i kontroluj ruch.', 'Unikaj w przypadku ostrego bólu lędźwi lub szyi.', 'Ciągnięcie za szyję rękami lub zbyt szybkie poruszanie nogami bez kontroli.'),
('bicycle-crunches', 'id', 'Bicycle crunches', 'Latihan perut yang meniru gerakan bersepeda, berfokus pada otot perut lurus dan miring.', 'Memperkuat inti dan meningkatkan rotasi batang tubuh.', 'Berbaring, bawa siku yang berlawanan ke lutut yang berlawanan sambil meluruskan kaki lainnya.', 'Jaga punggung bawah tetap menempel ke lantai dan kontrol gerakan.', 'Hindari jika ada nyeri punggung bawah atau leher yang akut.', 'Menarik leher dengan tangan atau menggerakkan kaki terlalu cepat tanpa kontrol.'),
('bicycle-crunches', 'bn', 'বাইসাইকেল ক্রাঞ্চ', 'পেটের ব্যায়াম যা সাইকেল চালানোর অনুকরণ করে, পেটের সোজা এবং তির্যক পেশির উপর ফোকাস করে।', 'কোর শক্তিশালী করে এবং শরীরের রোটেশন উন্নত করে।', 'শুয়ে পড়ুন, বিপরীত হাত বিপরীত হাঁটুর কাছে আনুন এবং অন্য পা সোজা করুন।', 'আপনার নিচের পিঠ মেঝেতে চেপে রাখুন এবং গতি নিয়ন্ত্রণ করুন।', 'নিচের পিঠ বা ঘাড়ে তীব্র ব্যথা থাকলে এড়িয়ে চলুন।', 'হাত দিয়ে ঘাড়ে চাপ দেওয়া বা নিয়ন্ত্রণ ছাড়াই পা খুব দ্রুত নাড়ানো।'),
('bicycle-crunches', 'vi', 'Bicycle crunches', 'Bài tập bụng mô phỏng động tác đạp xe, tập trung vào cơ bụng thẳng và cơ chéo.', 'Tăng cường sức mạnh cơ lõi và cải thiện khả năng xoay thân người.', 'Nằm xuống, đưa khuỷu tay đối diện về phía đầu gối ngược lại trong khi duỗi chân kia.', 'Luôn ép sát thắt lưng xuống sàn và kiểm soát chuyển động.', 'Tránh tập nếu bị đau lưng dưới hoặc cổ cấp tính.', 'Kéo cổ bằng tay hoặc di chuyển chân quá nhanh mà không kiểm soát.'),
('bicycle-crunches', 'fa', 'تمرین دوچرخه (Bicycle crunches)', 'تمرین شکم که دوچرخه‌سواری را شبیه‌سازی می‌کند و بر عضلات راست شکمی و مورب تمرکز دارد.', 'هسته را تقویت کرده و چرخش تنه را بهبود می‌بخشد.', 'دراز بکشید، آرنج مخالف را به زانوی مقابل نزدیک کنید و پای دیگر را دراز کنید.', 'کمر خود را به زمین بچسبانید و حرکت را کنترل کنید.', 'در صورت درد حاد در کمر یا گردن از انجام آن خودداری کنید.', 'کشیدن گردن با دست‌ها یا حرکت دادن پاها با سرعت زیاد و بدون کنترل.');