-- Definición de ejercicios
INSERT OR IGNORE INTO exercises (slug, img, video, difficulty) 
VALUES 
('bicycle-crunch', 'bicycle-crunch.jpg', 'bicycle-crunch.mp4', 'intermediate'),
('crunch', 'crunch.jpg', 'crunch.mp4', 'beginner');

-- Relaciones de grupos musculares
INSERT INTO exercise_body_target (exercise_slug, body_target_slug) 
VALUES 
('bicycle-crunch', 'abdominals');

-- Relaciones de alternativas
INSERT INTO exercise_alternative (exercise_slug, alternative_slug) 
VALUES 
('bicycle-crunch', 'crunch');

-- Información multiidioma
INSERT OR IGNORE INTO exercises_info (slug, lang, title, description, benefits, instructions, tips, restrictions, mistakes) VALUES 
('bicycle-crunch', 'es', 'Bicycle crunch', 'Ejercicio de rotación que demanda una alta activación del recto abdominal y los oblicuos.', 'Mejora la coordinación core y fortalece la pared abdominal lateral.', 'Tumbado boca arriba, lleva el codo opuesto hacia la rodilla contraria alternativamente con movimiento de pedaleo.', 'Mantén la zona lumbar pegada al suelo durante todo el recorrido.', 'Evitar si hay molestias cervicales agudas.', 'Tirar del cuello con las manos o realizar el movimiento demasiado rápido.'),
('bicycle-crunch', 'en', 'Bicycle crunch', 'Rotational exercise demanding high activation of the rectus abdominis and obliques.', 'Enhances core coordination and strengthens the lateral abdominal wall.', 'Lying on your back, bring the opposite elbow to the opposite knee in a pedaling motion.', 'Keep the lower back pressed against the floor throughout the movement.', 'Avoid if acute cervical discomfort is present.', 'Pulling the neck with hands or performing the movement too quickly.'),
('bicycle-crunch', 'pt', 'Bicycle crunch', 'Exercício de rotação que exige alta ativação do reto abdominal e dos oblíquos.', 'Melhora a coordenação do core e fortalece a parede abdominal lateral.', 'Deitado de costas, leve o cotovelo oposto ao joelho contrário num movimento de pedalada.', 'Mantenha a região lombar pressionada contra o chão durante todo o movimento.', 'Evitar se houver desconforto cervical agudo.', 'Puxar o pescoço com as mãos ou realizar o movimento muito rápido.'),
('bicycle-crunch', 'fr', 'Bicycle crunch', 'Exercice de rotation nécessitant une activation élevée du grand droit et des obliques.', 'Améliore la coordination du core et renforce la paroi abdominale latérale.', 'Allongé sur le dos, amenez le coude opposé vers le genou contraire dans un mouvement de pédalage.', 'Gardez le bas du dos plaqué contre le sol pendant tout le mouvement.', 'À éviter en cas d''inconfort cervical aigu.', 'Tirer sur le cou avec les mains ou effectuer le mouvement trop rapidement.'),
('bicycle-crunch', 'de', 'Bicycle Crunch', 'Rotationsübung, die eine hohe Aktivierung des geraden Bauchmuskels und der schrägen Bauchmuskeln erfordert.', 'Verbessert die Rumpfkoordination und stärkt die seitliche Bauchwand.', 'In Rückenlage abwechselnd den gegenüberliegenden Ellbogen zum Knie führen, wie beim Fahrradfahren.', 'Den unteren Rücken während der gesamten Bewegung flach am Boden halten.', 'Bei akuten Nackenbeschwerden vermeiden.', 'Den Nacken mit den Händen ziehen oder die Bewegung zu schnell ausführen.'),
('bicycle-crunch', 'it', 'Bicycle crunch', 'Esercizio di rotazione che richiede un''elevata attivazione del retto addominale e degli obliqui.', 'Migliora la coordinazione del core e rafforza la parete addominale laterale.', 'Sdraiato sulla schiena, porta il gomito opposto verso il ginocchio contrario con un movimento di pedalata.', 'Mantieni la zona lombare premuta contro il pavimento durante tutto il movimento.', 'Evitare in caso di fastidio cervicale acuto.', 'Tirare il collo con le mani o eseguire il movimento troppo velocemente.'),
('bicycle-crunch', 'zh', '自行车卷腹', '旋转运动，需要腹直肌和腹外斜肌的高度激活。', '增强核心协调性并强化腹侧壁。', '仰卧，进行踩踏动作，使对侧肘部触碰对侧膝盖。', '在整个过程中保持腰部贴地。', '如有急性颈部不适，请避免使用。', '用手拉脖子或动作过快。'),
('bicycle-crunch', 'ja', 'バイシクルクランチ', '腹直筋と腹斜筋の高い活性化を要求する回旋運動。', 'コアの協調性を高め、腹壁の側部を強化します。', '仰向けになり、自転車を漕ぐような動作で、対側の肘と膝を近づけます。', '動作中、腰を床に押し付けた状態を保ちます。', '頸部に強い違和感がある場合は避けてください。', '手で首を引っ張ることや、動作を速すぎること。'),
('bicycle-crunch', 'ko', '바이시클 크런치', '복직근과 복사근의 높은 활성화를 요구하는 회전 운동.', '코어 협응력을 개선하고 측면 복벽을 강화함.', '누운 상태에서 페달을 밟듯 반대쪽 팔꿈치와 무릎이 닿게 함.', '동작 내내 허리를 바닥에 밀착시킬 것.', '급성 경추 통증이 있다면 피할 것.', '손으로 목을 잡아당기거나 동작을 너무 빨리 하는 것.'),
('bicycle-crunch', 'ar', 'تمرين الدراجة للبطن', 'تمرين دوراني يتطلب تفعيلاً عالياً لعضلة البطن المستقيمة والعضلات المائلة.', 'يحسن تناسق عضلات الجذع ويقوي جدار البطن الجانبي.', 'استلقِ على ظهرك، وقرّب المرفق المعاكس للركبة المعاكسة في حركة تبادلية.', 'حافظ على ملامسة أسفل الظهر للأرض طوال فترة التمرين.', 'تجنب التمرين في حالة وجود آلام حادة في الرقبة.', 'سحب الرقبة باليدين أو أداء الحركة بسرعة كبيرة.'),
('bicycle-crunch', 'hi', 'बाइसिकल क्रंच', 'घूर्णी व्यायाम जिसे रेक्टस एब्डोमिनिस और ओब्लिक्स के उच्च सक्रियण की आवश्यकता होती है।', 'कोर समन्वय में सुधार करता है और पार्श्व पेट की दीवार को मजबूत करता है।', 'पीठ के बल लेटें, पेडलिंग गति में विपरीत कोहनी को विपरीत घुटने तक लाएं।', 'पूरी गति के दौरान पीठ के निचले हिस्से को फर्श पर दबाए रखें।', 'यदि गर्दन में तीव्र असुविधा हो तो न करें।', 'हाथों से गर्दन को खींचना या बहुत जल्दी गति करना।'),
('bicycle-crunch', 'ru', 'Велосипед (Bicycle crunch)', 'Ротационное упражнение, требующее высокой активации прямой и косых мышц живота.', 'Улучшает координацию кора и укрепляет боковую стенку живота.', 'Лежа на спине, поочередно касайтесь противоположным локтем колена, имитируя езду на велосипеде.', 'Держите поясницу прижатой к полу на протяжении всего движения.', 'Избегайте при острой боли в шее.', 'Тянуть шею руками или выполнять движение слишком быстро.'),
('bicycle-crunch', 'nl', 'Bicycle crunch', 'Rotatie-oefening die hoge activering van de rectus abdominis en schuine buikspieren vereist.', 'Verbetert core-coördinatie en versterkt de zijdelingse buikwand.', 'Lig op de rug, breng de tegenovergestelde elleboog naar de tegenovergestelde knie in een trapbeweging.', 'Houd de onderrug tijdens de hele beweging tegen de vloer gedrukt.', 'Vermijden bij acute nekklachten.', 'Aan de nek trekken met de handen of de beweging te snel uitvoeren.'),
('bicycle-crunch', 'sv', 'Bicycle crunch', 'Rotationsövning som kräver hög aktivering av rectus abdominis och obliques.', 'Förbättrar core-koordination och stärker den laterala bukväggen.', 'Ligg på rygg, för motsatt armbåge mot motsatt knä i en cyklande rörelse.', 'Håll ländryggen pressad mot golvet under hela rörelsen.', 'Undvik vid akut nackbesvär.', 'Dra i nacken med händerna eller utföra rörelsen för snabbt.'),
('bicycle-crunch', 'pl', 'Bicycle crunch', 'Ćwiczenie rotacyjne wymagające wysokiej aktywacji mięśnia prostego i skośnych brzucha.', 'Poprawia koordynację tułowia i wzmacnia boczne ściany brzucha.', 'W leżeniu na plecach, naprzemiennie przyciągaj przeciwległy łokieć do kolana w ruchu rowerka.', 'Utrzymuj odcinek lędźwiowy dociśnięty do podłoża przez cały czas.', 'Unikaj w przypadku ostrego bólu karku.', 'Ciągnięcie karku rękami lub wykonywanie ruchu zbyt szybko.'),
('bicycle-crunch', 'id', 'Bicycle crunch', 'Latihan rotasi yang membutuhkan aktivasi tinggi dari rektus abdominis dan otot miring.', 'Meningkatkan koordinasi core dan memperkuat dinding perut lateral.', 'Berbaring telentang, bawa siku yang berlawanan ke lutut yang berlawanan dengan gerakan mengayuh.', 'Jaga punggung bawah tetap menempel ke lantai sepanjang gerakan.', 'Hindari jika ada ketidaknyamanan leher akut.', 'Menarik leher dengan tangan atau melakukan gerakan terlalu cepat.'),
('bicycle-crunch', 'bn', 'বাইসাইকেল ক্রাঞ্চ', 'রোটেশনাল ব্যায়াম যা রেকটাস এবডোমিনিস এবং ওবলিক্সের উচ্চ সক্রিয়তা দাবি করে।', 'কোর সমন্বয় উন্নত করে এবং পেটের পাশের দেয়াল মজবুত করে।', 'পিঠের ওপর শুয়ে, পেডলিং গতিতে বিপরীত কনুইকে বিপরীত হাঁটুর দিকে আনুন।', 'পুরো ব্যায়াম জুড়ে নিচের পিঠ মেঝের সাথে চেপে রাখুন।', 'গলায় তীব্র অস্বস্তি থাকলে এটি এড়িয়ে চলুন।', 'হাতের সাহায্যে গলা টানা বা খুব দ্রুত ব্যায়াম করা।'),
('bicycle-crunch', 'vi', 'Bicycle crunch', 'Bài tập xoay người đòi hỏi sự kích hoạt cao của cơ bụng thẳng và cơ liên sườn.', 'Cải thiện sự phối hợp cơ core và làm khỏe thành bụng bên.', 'Nằm ngửa, đưa khuỷu tay đối diện về phía đầu gối đối diện theo chuyển động đạp xe.', 'Giữ lưng dưới áp sát sàn trong suốt quá trình chuyển động.', 'Tránh tập nếu bị đau cổ cấp tính.', 'Kéo cổ bằng tay hoặc thực hiện chuyển động quá nhanh.'),
('bicycle-crunch', 'fa', 'بایسیکل کرانچ', 'تمرین چرخشی که نیازمند فعالیت بالای عضلات راست شکمی و مورب است.', 'هماهنگی عضلات شکم را بهبود می‌بخشد و دیواره جانبی شکم را تقویت می‌کند.', 'به پشت دراز بکشید، آرنج مخالف را با حرکت پدال‌زنی به زانوی مخالف برسانید.', 'در تمام طول حرکت، کمر را به زمین بچسبانید.', 'در صورت ناراحتی حاد گردن از انجام آن خودداری کنید.', 'کشیدن گردن با دست‌ها یا انجام حرکت بیش از حد سریع.');