-- Definición de ejercicios
INSERT OR IGNORE INTO exercises (slug, img, video, difficulty) 
VALUES 
('captains-chair-leg-raise', 'captains-chair-leg-raise.jpg', 'captains-chair-leg-raise.mp4', 'intermediate'),
('hanging-knee-raises', 'hanging-knee-raises.jpg', 'hanging-knee-raises.mp4', 'intermediate');

-- Relaciones de grupos musculares
INSERT OR IGNORE INTO exercise_body_target (exercise_slug, body_target_slug) 
VALUES 
('captains-chair-leg-raise', 'abdominals');

-- Relaciones de alternativas
INSERT OR IGNORE INTO exercise_alternative (exercise_slug, alternative_slug) 
VALUES 
('captains-chair-leg-raise', 'hanging-knee-raises');

-- Información multiidioma
INSERT OR IGNORE INTO exercises_info (slug, lang, title, description, benefits, instructions, tips, restrictions, mistakes) VALUES 
('captains-chair-leg-raise', 'es', 'Elevación de piernas en silla capitán', 'Ejercicio de suspensión que aísla la parte inferior del recto abdominal mediante flexión de cadera.', 'Fortalece el core inferior y mejora la estabilidad lumbopélvica.', 'Apoyado en los antebrazos sobre la estructura, eleva las piernas extendidas hasta la horizontal.', 'Evita el balanceo del cuerpo usando la fuerza de tu abdomen, no el impulso.', 'Evitar si hay lesiones de hombro o dolor lumbar crónico.', 'Balancear el cuerpo para subir las piernas o arquear excesivamente la espalda.'),
('captains-chair-leg-raise', 'en', 'Captains chair leg raise', 'Suspension exercise that isolates the lower rectus abdominis through hip flexion.', 'Strengthens the lower core and improves lumbopelvic stability.', 'Supported on your forearms, lift your extended legs to the horizontal position.', 'Avoid body swinging by using core strength, not momentum.', 'Avoid if shoulder injuries or chronic lower back pain exist.', 'Swinging the body to lift the legs or excessively arching the back.'),
('captains-chair-leg-raise', 'pt', 'Elevação de pernas na cadeira capitão', 'Exercício de suspensão que isola a parte inferior do reto abdominal através da flexão do quadril.', 'Fortalece o core inferior e melhora a estabilidade lumbopélvica.', 'Apoiado nos antebraços na estrutura, eleve as pernas estendidas até a horizontal.', 'Evite o balanço do corpo usando a força do seu abdômen, não o impulso.', 'Evitar se houver lesões no ombro ou dor lombar crônica.', 'Balançar o corpo para levantar as pernas ou arquear excessivamente as costas.'),
('captains-chair-leg-raise', 'fr', 'Leve de jambes chaise romaine', 'Exercice de suspension isolant le bas du grand droit par flexion de hanche.', 'Renforce le bas du core et améliore la stabilité lumbopelvienne.', 'En appui sur les avant-bras, élevez les jambes tendues jusqu''à l''horizontale.', 'Évitez le balancement en utilisant la force abdominale et non l''élan.', 'À éviter en cas de blessure à l''épaule ou de douleurs lombaires chroniques.', 'Se balancer pour monter les jambes ou trop cambrer le dos.'),
('captains-chair-leg-raise', 'de', 'Beinheben an der Captains Chair', 'Übung in der Schwebe, die den unteren Bauchmuskel durch Hüftbeugung isoliert.', 'Stärkt den unteren Rumpf und verbessert die lumbopelvinale Stabilität.', 'Mit Unterarmen auf die Stütze, die gestreckten Beine bis zur Horizontalen anheben.', 'Ein Schwingen durch Bauchkraft verhindern, nicht durch Schwung.', 'Bei Schulterverletzungen oder chronischen Rückenschmerzen vermeiden.', 'Schwung holen oder den Rücken zu stark durchdrücken.'),
('captains-chair-leg-raise', 'it', 'Sollevamento gambe su sedia capitano', 'Esercizio in sospensione che isola la parte inferiore del retto addominale tramite flessione dell''anca.', 'Rinforza il core inferiore e migliora la stabilità lumbopelvica.', 'Appoggiato sugli avambracci, solleva le gambe tese fino alla posizione orizzontale.', 'Evita l''oscillazione del corpo usando la forza addominale, non lo slancio.', 'Evitare in caso di lesioni alla spalla o dolore lombare cronico.', 'Oscillare il corpo per sollevare le gambe o inarcare eccessivamente la schiena.'),
('captains-chair-leg-raise', 'zh', '悬垂腿部抬高', '通过髋部屈曲隔离下腹直肌的悬挂练习。', '增强下核心并提高腰盆腔稳定性。', '前臂支撑在结构上，将伸展的双腿抬高至水平位置。', '利用腹肌力量而不是惯性来防止身体晃动。', '如有肩部损伤或慢性腰痛，请避免使用。', '身体摆动或过度拱腰。'),
('captains-chair-leg-raise', 'ja', 'キャプテンズチェア・レッグレイズ', '股関節屈曲により下腹直筋を分離して鍛える懸垂エクササイズ。', '下部コアを強化し、腰骨盤の安定性を向上させます。', '前腕を支え、脚を伸ばしたまま水平位置まで持ち上げます。', '反動を使わず、腹筋の力を使って身体の揺れを防ぎます。', '肩の怪我や慢性的な腰痛がある場合は避けてください。', '脚を持ち上げるために反動を使う、または腰を過度に反らすこと。'),
('captains-chair-leg-raise', 'ko', '캡틴스 체어 레그 레이즈', '고관절 굴곡을 통해 하복직근을 고립시키는 매달리기 운동.', '하부 코어를 강화하고 요골반 안정성을 개선함.', '팔꿈치를 지지하고 펴진 다리를 수평 위치까지 들어 올림.', '반동이 아닌 복근의 힘을 사용하여 몸의 흔들림을 방지할 것.', '어깨 부상이나 만성 요통이 있다면 피할 것.', '반동을 이용하거나 허리를 과하게 젖히는 것.'),
('captains-chair-leg-raise', 'ar', 'رفع الساقين على كرسي الكابتن', 'تمرين تعليق يعزل الجزء السفلي من عضلة البطن المستقيمة عبر ثني الورك.', 'يقوي الجذع السفلي ويحسن استقرار منطقة أسفل الظهر والحوض.', 'بالاستناد على الساعدين، ارفع ساقيك الممدودتين حتى المستوى الأفقي.', 'تجنب أرجحة الجسم باستخدام قوة عضلات البطن وليس الزخم.', 'تجنب التمرين في حالة وجود إصابات في الكتف أو آلام مزمنة في أسفل الظهر.', 'أرجحة الجسم لرفع الساقين أو تقوس الظهر بشكل مفرط.'),
('captains-chair-leg-raise', 'hi', 'कैप्टन चेयर लेग रेज', 'हिप फ्लेक्सियन के माध्यम से निचले रेक्टस एब्डोमिनिस को अलग करने वाला सस्पेंशन व्यायाम।', 'निचले कोर को मजबूत करता है और लंबोपेलविक स्थिरता में सुधार करता है।', 'अग्रबाहुओं (forearms) पर समर्थन लेते हुए, सीधे पैरों को क्षैतिज स्थिति तक उठाएं।', 'पेट की ताकत का उपयोग करें, न कि गति (momentum), जिससे शरीर न हिले।', 'यदि कंधे में चोट या पीठ के निचले हिस्से में पुराना दर्द हो तो न करें।', 'पैर ऊपर उठाने के लिए शरीर को झुलाना या पीठ को बहुत ज्यादा मोड़ना।'),
('captains-chair-leg-raise', 'ru', 'Подъем ног в упоре (Captains chair)', 'Упражнение в висе, изолирующее нижнюю часть прямой мышцы живота через сгибание бедра.', 'Укрепляет нижнюю часть кора и улучшает пояснично-тазовую стабильность.', 'Опираясь предплечьями на подлокотники, поднимите прямые ноги до горизонтали.', 'Избегайте раскачивания корпуса, используя силу мышц живота, а не инерцию.', 'Избегайте при травмах плеча или хронических болях в пояснице.', 'Раскачивание корпуса или чрезмерный прогиб в пояснице.'),
('captains-chair-leg-raise', 'nl', 'Captains chair leg raise', 'Hangende oefening die de onderste rectus abdominis isoleert door heupflexie.', 'Versterkt de onderbuik en verbetert lumbopelvische stabiliteit.', 'Ondersteund door de onderarmen, til de gestrekte benen tot de horizontale positie.', 'Voorkom zwiepen door core-kracht te gebruiken, geen momentum.', 'Vermijden bij schouderblessures of chronische onderrugpijn.', 'Het lichaam zwaaien of de rug overmatig hol trekken.'),
('captains-chair-leg-raise', 'sv', 'Captains chair leg raise', 'Hängande övning som isolerar nedre rectus abdominis genom höftflexion.', 'Stärker nedre core och förbättrar lumbopelvisk stabilitet.', 'Stödd på underarmarna, lyft de raka benen till horisontellt läge.', 'Undvik att svinga genom att använda bålstyrka, inte momentum.', 'Undvik vid axelskador eller kronisk ländryggssmärta.', 'Att svinga kroppen eller överdrivet krumma ryggen.'),
('captains-chair-leg-raise', 'pl', 'Unoszenie nóg na drążku (Captains chair)', 'Ćwiczenie w zawieszeniu izolujące dolną część mięśnia prostego brzucha poprzez zgięcie bioder.', 'Wzmacnia dolne partie tułowia i poprawia stabilność lędźwiowo-miedniczną.', 'Opierając się przedramionami, unoś wyprostowane nogi do poziomu.', 'Unikaj huśtania się, używając siły mięśni brzucha, a nie pędu.', 'Unikaj w przypadku urazów barku lub przewlekłego bólu lędźwi.', 'Huśtanie ciałem lub nadmierne wyginanie kręgosłupa.'),
('captains-chair-leg-raise', 'id', 'Captains chair leg raise', 'Latihan suspensi yang mengisolasi bagian bawah rektus abdominis melalui fleksi pinggul.', 'Memperkuat core bawah dan meningkatkan stabilitas lumbopelvik.', 'Didukung oleh lengan bawah, angkat kaki yang lurus hingga posisi horizontal.', 'Hindari mengayunkan tubuh dengan menggunakan kekuatan core, bukan momentum.', 'Hindari jika ada cedera bahu atau nyeri punggung bawah kronis.', 'Mengayunkan tubuh untuk mengangkat kaki atau melengkungkan punggung secara berlebihan.'),
('captains-chair-leg-raise', 'bn', 'ক্যাপ্টেন্স চেয়ার লেগ রেইজ', 'হিপ ফ্লেক্সশনের মাধ্যমে নিচের রেক্টাস এবডোমিনিসকে আলাদা করার জন্য সাসপেনশন ব্যায়াম।', 'নিচের কোর শক্তিশালী করে এবং লম্বোপেলভিক স্থিতিশীলতা উন্নত করে।', 'দুই হাতের ওপর ভর দিয়ে, সোজা পা দুটিকে অনুভূমিক পজিশন পর্যন্ত তুলুন।', 'শরীরের জড়তা বা মোমেন্টাম ব্যবহার না করে পেটের পেশীর জোর ব্যবহার করুন যাতে শরীর না দুলতে পারে।', 'কাঁধে চোট বা পিঠের নিচের অংশে দীর্ঘস্থায়ী ব্যথা থাকলে এড়িয়ে চলুন।', 'পায়ের ঝাপটায় শরীর দোলানো বা পিঠ অতিরিক্ত বাঁকানো।'),
('captains-chair-leg-raise', 'vi', 'Nâng chân trên ghế đội trưởng', 'Bài tập treo người cô lập phần dưới cơ bụng thẳng qua chuyển động gập hông.', 'Làm khỏe phần cơ core dưới và cải thiện sự ổn định vùng thắt lưng-chậu.', 'Tựa tay lên phần đệm, nâng hai chân duỗi thẳng lên đến vị trí song song với sàn.', 'Tránh vung người bằng cách dùng sức mạnh cơ bụng thay vì quán tính.', 'Tránh tập nếu bị chấn thương vai hoặc đau lưng dưới mãn tính.', 'Vung người để nâng chân hoặc võng lưng quá mức.'),
('captains-chair-leg-raise', 'fa', 'بالا آوردن پا روی صندلی کاپیتان', 'تمرین تعلیقی که بخش پایینی عضلات راست شکمی را از طریق خم کردن لگن ایزوله می‌کند.', 'عضلات مرکزی پایین را تقویت کرده و پایداری لومبوی لگنی را بهبود می‌بخشد.', 'با تکیه بر ساعدها، پاهای کشیده را تا وضعیت افقی بالا بیاورید.', 'با استفاده از قدرت عضلات مرکزی از تاب خوردن جلوگیری کنید، نه با شتاب.', 'در صورت آسیب‌دیدگی شانه یا درد مزمن کمر از انجام آن خودداری کنید.', 'تاب دادن بدن برای بالا بردن پاها یا قوس دادن بیش از حد به کمر.');