-- Definición de ejercicios
INSERT OR IGNORE INTO exercises (slug, img, video, difficulty) 
VALUES 
('captains-chair-straight-leg-raise', 'captains-chair-straight-leg-raise.jpg', 'captains-chair-straight-leg-raise.mp4', 'advanced'),
('captains-chair-leg-raise', 'captains-chair-leg-raise.jpg', 'captains-chair-leg-raise.mp4', 'intermediate');

-- Relaciones de grupos musculares
INSERT INTO exercise_body_target (exercise_slug, body_target_slug) 
VALUES 
('captains-chair-straight-leg-raise', 'abdominals');

-- Relaciones de alternativas
INSERT INTO exercise_alternative (exercise_slug, alternative_slug) 
VALUES 
('captains-chair-straight-leg-raise', 'captains-chair-leg-raise');

-- Información multiidioma
INSERT OR IGNORE INTO exercises_info (slug, lang, title, description, benefits, instructions, tips, restrictions, mistakes) VALUES 
('captains-chair-straight-leg-raise', 'es', 'Elevación de piernas extendidas (Captains chair)', 'Variante avanzada que mantiene la palanca larga de las piernas para maximizar la tensión en el abdomen inferior.', 'Aumenta significativamente la demanda sobre el core y la fuerza de flexión de cadera.', 'Suspendido sobre la silla capitán, eleva las piernas completamente extendidas hasta formar un ángulo de 90 grados con el torso.', 'Mantén la rodilla bloqueada y el core compacto para evitar que la pelvis se desestabilice.', 'Evitar si existe dolor lumbar o tensión excesiva en los flexores de la cadera.', 'Realizar el movimiento con balanceo o flexionar las rodillas por falta de fuerza.'),
('captains-chair-straight-leg-raise', 'en', 'Captains chair straight leg raise', 'Advanced variant maintaining a long leg lever to maximize tension in the lower abs.', 'Significantly increases core demand and hip flexion strength.', 'Suspended on the captain''s chair, lift fully extended legs to a 90-degree angle with the torso.', 'Keep knees locked and core tight to prevent pelvic instability.', 'Avoid if lower back pain or excessive hip flexor tension exists.', 'Using momentum or bending knees due to lack of strength.'),
('captains-chair-straight-leg-raise', 'pt', 'Elevação de pernas estendidas (Cadeira capitão)', 'Variante avançada que mantém a alavanca longa das pernas para maximizar a tensão no abdômen inferior.', 'Aumenta significativamente a demanda no core e a força de flexão do quadril.', 'Suspenso na cadeira capitão, eleve as pernas totalmente estendidas até formar um ângulo de 90 graus com o tronco.', 'Mantenha o joelho bloqueado e o core compacto para evitar que a pélvis se desestabilize.', 'Evitar se houver dor lombar ou tensão excessiva nos flexores do quadril.', 'Realizar o movimento com balanço ou flexionar os joelhos por falta de força.'),
('captains-chair-straight-leg-raise', 'fr', 'Leve de jambes tendues (Chaise romaine)', 'Variante avancée maintenant un long levier de jambe pour maximiser la tension sur les abdominaux inférieurs.', 'Augmente significativement la demande sur le core et la force de flexion de hanche.', 'Suspendu sur la chaise romaine, levez les jambes complètement tendues à un angle de 90 degrés avec le buste.', 'Gardez les genoux verrouillés et le core gainé pour éviter l''instabilité pelvienne.', 'À éviter en cas de douleurs lombaires ou de tension excessive dans les fléchisseurs de la hanche.', 'Utiliser de l''élan ou plier les genoux par manque de force.'),
('captains-chair-straight-leg-raise', 'de', 'Beinheben mit gestreckten Beinen (Captains Chair)', 'Fortgeschrittene Variante mit langem Beinhebel zur Maximierung der Spannung im unteren Bauch.', 'Erhöht die Rumpfbelastung und die Hüftbeugekraft signifikant.', 'In der Schwebe die vollständig gestreckten Beine in einem 90-Grad-Winkel zum Oberkörper anheben.', 'Knie durchgedrückt und Rumpf fest halten, um Beckeninstabilität zu vermeiden.', 'Bei Rückenschmerzen oder übermäßiger Spannung in den Hüftbeugern vermeiden.', 'Mit Schwung arbeiten oder Knie aus Kraftmangel beugen.'),
('captains-chair-straight-leg-raise', 'it', 'Sollevamento gambe tese su sedia capitano', 'Variante avanzata che mantiene la leva lunga delle gambe per massimizzare la tensione sugli addominali inferiori.', 'Aumenta significativamente il carico sul core e la forza di flessione dell''anca.', 'In sospensione, solleva le gambe completamente tese fino a formare un angolo di 90 gradi con il busto.', 'Mantieni il ginocchio bloccato e il core compatto per evitare l''instabilità del bacino.', 'Evitare in caso di dolore lombare o tensione eccessiva ai flessori dell''anca.', 'Eseguire il movimento con oscillazioni o flettere le ginocchia per mancanza di forza.'),
('captains-chair-straight-leg-raise', 'zh', '悬垂直腿抬高', '高级变体，通过保持长腿杠杆以最大限度地增加下腹部张力。', '显著增加核心需求和髋屈肌力量。', '悬挂在结构上，将双腿完全伸展抬高至与躯干成90度角。', '保持膝盖锁死和核心收紧，以防止骨盆不稳定。', '如有腰痛或髋屈肌过度紧张，请避免使用。', '利用惯性移动或因力量不足而弯曲膝盖。'),
('captains-chair-straight-leg-raise', 'ja', 'キャプテンズチェア・ストレートレッグレイズ', '下腹部への張力を最大化するために長い脚のレバーを維持する上級バリエーション。', 'コアへの負荷と股関節屈曲筋力を大幅に高めます。', '懸垂状態で、完全に伸ばした脚を胴体に対して90度の角度まで持ち上げます。', '膝を固定し、骨盤の安定性が損なわれないようコアを締め続けます。', '腰痛や腸腰筋の過度な緊張がある場合は避けてください。', '反動を使うこと、または筋力不足で膝を曲げること。'),
('captains-chair-straight-leg-raise', 'ko', '캡틴스 체어 스트레이트 레그 레이즈', '하복부 긴장을 극대화하기 위해 긴 다리 지렛대를 유지하는 고급 변형.', '코어 요구량과 고관절 굴곡 근력을 상당히 증가시킴.', '매달린 상태에서 완전히 편 다리를 몸통과 90도 각도가 되도록 들어 올림.', '골반 불안정을 방지하기 위해 무릎을 고정하고 코어를 단단히 유지할 것.', '요통이나 장요근 과긴장이 있다면 피할 것.', '반동을 이용하거나 근력 부족으로 무릎을 굽히는 것.'),
('captains-chair-straight-leg-raise', 'ar', 'رفع الساقين مستقيمتين على كرسي الكابتن', 'تمرين متقدم يحافظ على ذراع الرافعة الطويلة للساقين لزيادة التوتر في عضلات البطن السفلية.', 'يزيد بشكل كبير من الضغط على عضلات الجذع وقوة ثني الورك.', 'أثناء التعلق، ارفع ساقيك ممدودتين تماماً حتى تشكلا زاوية 90 درجة مع الجذع.', 'حافظ على ثبات الركبتين وتماسك الجذع لتجنب عدم استقرار الحوض.', 'تجنب التمرين في حالة وجود آلام في أسفل الظهر أو شد عضلي مفرط في عضلات الورك.', 'استخدام الزخم أو ثني الركبتين بسبب نقص القوة.'),
('captains-chair-straight-leg-raise', 'hi', 'कैप्टन चेयर स्ट्रेट लेग रेज', 'निचले पेट में तनाव को अधिकतम करने के लिए लंबे पैर के लीवर को बनाए रखने वाला उन्नत संस्करण।', 'कोर की मांग और हिप फ्लेक्सियन शक्ति को काफी बढ़ाता है।', 'कैप्टन चेयर पर लटके हुए, पूरी तरह से सीधे पैरों को धड़ के साथ 90 डिग्री के कोण तक उठाएं।', 'पेल्विक अस्थिरता से बचने के लिए घुटनों को लॉक रखें और कोर को टाइट रखें।', 'यदि पीठ के निचले हिस्से में दर्द या हिप फ्लेक्सर्स में अत्यधिक तनाव हो तो न करें।', 'गति (momentum) का उपयोग करना या ताकत की कमी के कारण घुटनों को मोड़ना।'),
('captains-chair-straight-leg-raise', 'ru', 'Подъем прямых ног в упоре', 'Продвинутый вариант, сохраняющий длинный рычаг ног для максимизации напряжения нижней части пресса.', 'Значительно увеличивает нагрузку на кор и силу сгибателей бедра.', 'В висе поднимите полностью выпрямленные ноги до угла 90 градусов к корпусу.', 'Держите колени заблокированными, а кор напряженным, чтобы избежать нестабильности таза.', 'Избегайте при болях в пояснице или перенапряжении сгибателей бедра.', 'Использование инерции или сгибание коленей из-за недостатка силы.'),
('captains-chair-straight-leg-raise', 'nl', 'Captains chair straight leg raise', 'Geavanceerde variant met lange hefboom voor maximale spanning op de onderbuik.', 'Verhoogt core-belasting en heupflexiekracht aanzienlijk.', 'Hangen, til de volledig gestrekte benen op tot een hoek van 90 graden met de romp.', 'Houd de knieën gestrekt en de core aangespannen om bekkeninstabiliteit te voorkomen.', 'Vermijden bij onderrugpijn of overmatige spanning op heupbuigers.', 'Momentum gebruiken of knieën buigen door gebrek aan kracht.'),
('captains-chair-straight-leg-raise', 'sv', 'Captains chair straight leg raise', 'Avancerad variant som håller lång hävarm för att maximera spänningen i nedre magen.', 'Ökar core-belastningen och höftböjarstyrkan markant.', 'Hängande, lyft de helt raka benen till 90 graders vinkel mot bålen.', 'Håll knäna låsta och coren spänd för att undvika bäckeninstabilitet.', 'Undvik vid ländryggssmärta eller överdriven spänning i höftböjarna.', 'Använda momentum eller böja knäna p.g.a. bristande styrka.'),
('captains-chair-straight-leg-raise', 'pl', 'Unoszenie wyprostowanych nóg (Captains chair)', 'Zaawansowany wariant z długą dźwignią nóg dla maksymalnego napięcia dolnych partii brzucha.', 'Znacząco zwiększa zaangażowanie mięśni głębokich i siłę zginaczy bioder.', 'W zwisie, unosząc całkowicie wyprostowane nogi do kąta 90 stopni względem tułowia.', 'Trzymaj kolana zablokowane i napięty brzuch, aby uniknąć niestabilności miednicy.', 'Unikaj w przypadku bólu lędźwi lub nadmiernego napięcia zginaczy bioder.', 'Używanie pędu lub uginanie kolan z braku siły.'),
('captains-chair-straight-leg-raise', 'id', 'Captains chair straight leg raise', 'Variasi lanjutan yang menjaga tuas kaki panjang untuk memaksimalkan ketegangan pada perut bawah.', 'Secara signifikan meningkatkan permintaan core dan kekuatan fleksi pinggul.', 'Saat menggantung, angkat kaki yang lurus sempurna hingga sudut 90 derajat dengan batang tubuh.', 'Jaga lutut tetap terkunci dan core tetap kencang untuk mencegah ketidakstabilan panggul.', 'Hindari jika ada nyeri punggung bawah atau ketegangan berlebih pada fleksor pinggul.', 'Menggunakan momentum atau menekuk lutut karena kurangnya kekuatan.'),
('captains-chair-straight-leg-raise', 'bn', 'ক্যাপ্টেন্স চেয়ার স্ট্রেট লেগ রেইজ', 'নিচের পেটের পেশীতে টান বাড়াতে পায়ের লিভারেজ ব্যবহার করা একটি উন্নত সংস্করণ।', 'কোর ও হিপ ফ্লেক্সর শক্তি উল্লেখযোগ্যভাবে বৃদ্ধি করে।', 'ঝুলে থাকা অবস্থায়, দুই পা পুরোপুরি সোজা রেখে শরীরের সাথে ৯০ ডিগ্রি কোণে তুলুন।', 'পেলভিক অস্থিতিশীলতা এড়াতে হাঁটু লক এবং কোর শক্ত রাখুন।', 'পিঠের নিচের অংশে ব্যথা বা হিপ ফ্লেক্সরে অতিরিক্ত টান থাকলে এটি এড়িয়ে চলুন।', 'গতির ব্যবহার করা বা শক্তির অভাবে হাঁটু ভাঁজ করা।'),
('captains-chair-straight-leg-raise', 'vi', 'Nâng chân thẳng trên ghế đội trưởng', 'Biến thể nâng cao duy trì đòn bẩy chân dài để tối đa hóa áp lực lên cơ bụng dưới.', 'Tăng đáng kể áp lực lên cơ core và sức mạnh gập hông.', 'Khi treo người, nâng hai chân duỗi thẳng hoàn toàn đến góc 90 độ so với thân.', 'Giữ khóa khớp gối và gồng cơ core để tránh mất ổn định khung chậu.', 'Tránh tập nếu bị đau lưng dưới hoặc căng cứng cơ gập hông quá mức.', 'Dùng quán tính hoặc gập đầu gối do thiếu sức mạnh.'),
('captains-chair-straight-leg-raise', 'fa', 'بالا آوردن پاهای صاف روی صندلی کاپیتان', 'نوعی تمرین پیشرفته که برای حداکثر تنش در شکم تحتانی، از اهرم بلند پاها استفاده می‌کند.', 'فشار بر عضلات مرکزی و قدرت خم کردن لگن را به شدت افزایش می‌دهد.', 'در حالت تعلیق، پاهای کاملاً کشیده را تا زاویه 90 درجه نسبت به تنه بالا بیاورید.', 'برای جلوگیری از بی‌ثباتی لگن، زانوها را قفل و عضلات مرکزی را منقبض نگه دارید.', 'در صورت درد کمر یا کشیدگی بیش از حد عضلات خم‌کننده لگن از انجام آن خودداری کنید.', 'استفاده از شتاب یا خم کردن زانوها به دلیل کمبود قدرت.');