-- Definición de ejercicios
INSERT OR IGNORE INTO exercises (slug, img, video, difficulty) 
VALUES 
('cobra-stretch', 'cobra-stretch.jpg', 'cobra-stretch.mp4', 'beginner'),
('bird-dog', 'bird-dog.jpg', 'bird-dog.mp4', 'beginner');

-- Relaciones de grupos musculares
INSERT OR IGNORE INTO exercise_body_target (exercise_slug, body_target_slug) 
VALUES 
('cobra-stretch', 'abdominals');

-- Relaciones de alternativas
INSERT OR IGNORE INTO exercise_alternative (exercise_slug, alternative_slug) 
VALUES 
('cobra-stretch', 'bird-dog');

-- Información multiidioma
INSERT OR IGNORE INTO exercises_info (slug, lang, title, description, benefits, instructions, tips, restrictions, mistakes) VALUES 
('cobra-stretch', 'es', 'Estiramiento de cobra', 'Movilidad activa que extiende la pared abdominal y mejora la flexibilidad espinal.', 'Alivia la tensión en los músculos abdominales y mejora la postura torácica.', 'Tumbado boca abajo, apoya las manos bajo los hombros y empuja el torso hacia arriba manteniendo la cadera en el suelo.', 'Mantén los hombros lejos de las orejas y respira profundamente.', 'Evitar si hay lesiones agudas en la columna vertebral.', 'Tensar excesivamente el cuello o despegar la pelvis del suelo.'),
('cobra-stretch', 'en', 'Cobra stretch', 'Active mobility move that stretches the abdominal wall and improves spinal flexibility.', 'Relieves tension in abdominal muscles and improves thoracic posture.', 'Lying face down, place hands under shoulders and push the torso upward while keeping hips on the floor.', 'Keep shoulders away from ears and breathe deeply.', 'Avoid if acute spinal injuries are present.', 'Tensing the neck excessively or lifting the pelvis off the floor.'),
('cobra-stretch', 'pt', 'Alongamento de cobra', 'Mobilidade ativa que estende a parede abdominal e melhora a flexibilidade espinal.', 'Alivia a tensão nos músculos abdominais e melhora a postura torácica.', 'Deitado de bruços, coloque as mãos sob os ombros e empurre o tronco para cima mantendo o quadril no chão.', 'Mantenha os ombros longe das orelhas e respire profundamente.', 'Evitar se houver lesões agudas na coluna vertebral.', 'Tensionar excessivamente o pescoço ou tirar o quadril do chão.'),
('cobra-stretch', 'fr', 'Étirement cobra', 'Mobilité active étirant la paroi abdominale et améliorant la flexibilité de la colonne.', 'Soulage les tensions des muscles abdominaux et améliore la posture thoracique.', 'Allongé face au sol, placez les mains sous les épaules et poussez le buste vers le haut en gardant les hanches au sol.', 'Gardez les épaules loin des oreilles et respirez profondément.', 'À éviter en cas de blessure aiguë à la colonne vertébrale.', 'Contracter excessivement le cou ou décoller le bassin du sol.'),
('cobra-stretch', 'de', 'Cobra-Dehnung', 'Aktive Mobilitätsübung zur Dehnung der Bauchwand und Verbesserung der Wirbelsäulenflexibilität.', 'Löst Spannungen in der Bauchmuskulatur und verbessert die Brusthaltung.', 'In Bauchlage die Hände unter die Schultern legen und den Oberkörper nach oben drücken, dabei die Hüfte am Boden halten.', 'Schultern weg von den Ohren halten und tief atmen.', 'Bei akuten Wirbelsäulenverletzungen vermeiden.', 'Nacken übermäßig anspannen oder das Becken vom Boden abheben.'),
('cobra-stretch', 'it', 'Allungamento cobra', 'Mobilità attiva che estende la parete addominale e migliora la flessibilità spinale.', 'Allevia la tensione nei muscoli addominali e migliora la postura toracica.', 'Sdraiato a faccia in giù, appoggia le mani sotto le spalle e spingi il busto verso l''alto mantenendo il bacino a terra.', 'Mantieni le spalle lontane dalle orecchie e respira profondamente.', 'Evitare in caso di lesioni acute alla colonna vertebrale.', 'Tendere eccessivamente il collo o sollevare il bacino da terra.'),
('cobra-stretch', 'zh', '眼镜蛇式拉伸', '主动活动度练习，延伸腹壁并改善脊柱柔韧性。', '缓解腹肌张力并改善胸部姿势。', '俯卧，将手放在肩膀下方，向上推起躯干，同时保持臀部触地。', '保持肩膀远离耳朵，深呼吸。', '如有急性脊柱损伤，请避免使用。', '过度拉紧颈部或将骨盆离开地面。'),
('cobra-stretch', 'ja', 'コブラストレッチ', '腹壁を伸展させ、脊椎の柔軟性を高めるアクティブなモビリティ動作。', '腹筋の緊張を和らげ、胸郭の姿勢を改善します。', 'うつ伏せになり、手を肩の下に置き、腰を床につけたまま上体を押し上げます。', '肩を耳から離し、深く呼吸します。', '急性脊椎損傷がある場合は避けてください。', '首に過度の力を入れることや、骨盤を床から浮かすこと。'),
('cobra-stretch', 'ko', '코브라 스트레칭', '복벽을 늘리고 척추 유연성을 향상시키는 능동적 가동성 운동.', '복부 근육의 긴장을 완화하고 흉부 자세를 개선함.', '엎드린 상태에서 손을 어깨 아래에 두고 골반을 바닥에 붙인 채 상체를 들어 올림.', '어깨를 귀에서 멀리 유지하고 깊게 호흡할 것.', '급성 척추 부상이 있다면 피할 것.', '목에 과도하게 힘을 주거나 골반을 바닥에서 떼는 것.'),
('cobra-stretch', 'ar', 'تمرين الكوبرا (Cobra stretch)', 'حركة نشطة تمد جدار البطن وتحسن مرونة العمود الفقري.', 'تخفف التوتر في عضلات البطن وتحسن وضعية الصدر.', 'استلقِ على وجهك، وضع يديك تحت كتفيك وادفع جذعك للأعلى مع إبقاء الحوض على الأرض.', 'حافظ على ابتعاد الكتفين عن الأذنين وتنفس بعمق.', 'تجنب التمرين في حالة وجود إصابات حادة في العمود الفقري.', 'الشد الزائد للرقبة أو رفع الحوض عن الأرض.'),
('cobra-stretch', 'hi', 'कोबरा स्ट्रेच', 'सक्रिय गतिशीलता जो पेट की दीवार को फैलाती है और रीढ़ की लचीलापन में सुधार करती है।', 'पेट की मांसपेशियों में तनाव को दूर करता है और छाती की मुद्रा में सुधार करता है।', 'पेट के बल लेटें, हाथों को कंधों के नीचे रखें और कूल्हों को फर्श पर रखते हुए धड़ को ऊपर धकेलें।', 'कंधों को कानों से दूर रखें और गहरी सांस लें।', 'यदि रीढ़ की हड्डी में तीव्र चोट हो तो न करें।', 'गर्दन पर अत्यधिक तनाव डालना या पेल्विस को फर्श से ऊपर उठाना।'),
('cobra-stretch', 'ru', 'Кобра (Cobra stretch)', 'Активное упражнение на мобильность, растягивающее мышцы живота и улучшающее гибкость позвоночника.', 'Снимает напряжение в мышцах живота и улучшает осанку.', 'Лежа на животе, поставьте руки под плечи и поднимите торс вверх, прижимая таз к полу.', 'Держите плечи опущенными и дышите глубоко.', 'Избегайте при острых травмах позвоночника.', 'Чрезмерное напряжение шеи или отрыв таза от пола.'),
('cobra-stretch', 'nl', 'Cobra stretch', 'Actieve mobiliteitsbeweging die de buikwand rekt en de wervelkolomflexibiliteit verbetert.', 'Verlicht spanning in buikspieren en verbetert de borsthouding.', 'Lig op de buik, plaats handen onder schouders en duw de romp omhoog terwijl de heupen op de vloer blijven.', 'Houd schouders weg van de oren en adem diep.', 'Vermijden bij acute rugletsel.', 'Nek overmatig aanspannen of het bekken van de vloer tillen.'),
('cobra-stretch', 'sv', 'Cobra stretch', 'Aktiv rörlighetsövning som töjer bukväggen och förbättrar ryggradens flexibilitet.', 'Lättar på spänningar i magmusklerna och förbättrar brösthållningen.', 'Ligg på mage, placera händerna under axlarna och tryck upp överkroppen samtidigt som höfterna hålls mot golvet.', 'Håll axlarna borta från öronen och andas djupt.', 'Undvik vid akuta ryggskador.', 'Att spänna nacken överdrivet eller lyfta bäckenet från golvet.'),
('cobra-stretch', 'pl', 'Rozciąganie kobra', 'Aktywna mobilizacja rozciągająca ścianę brzucha i poprawiająca elastyczność kręgosłupa.', 'Łagodzi napięcie mięśni brzucha i poprawia postawę klatki piersiowej.', 'W leżeniu przodem, umieść dłonie pod barkami i wypychaj tułów w górę, trzymając biodra na podłodze.', 'Trzymaj barki z dala od uszu i oddychaj głęboko.', 'Unikaj w przypadku ostrych urazów kręgosłupa.', 'Zbyt mocne napinanie szyi lub odrywanie miednicy od podłogi.'),
('cobra-stretch', 'id', 'Cobra stretch', 'Gerakan mobilitas aktif yang meregangkan dinding perut dan meningkatkan fleksibilitas tulang belakang.', 'Meredakan ketegangan pada otot perut dan memperbaiki postur dada.', 'Berbaring telentang, letakkan tangan di bawah bahu dan dorong batang tubuh ke atas sambil menjaga pinggul tetap di lantai.', 'Jauhkan bahu dari telinga dan bernapaslah dalam-dalam.', 'Hindari jika ada cedera tulang belakang akut.', 'Menegangkan leher secara berlebihan atau mengangkat panggul dari lantai.'),
('cobra-stretch', 'bn', 'কোবরা স্ট্রেচ', 'সক্রিয় গতিশীলতা যা পেটের দেয়াল প্রসারিত করে এবং মেরুদণ্ডের নমনীয়তা উন্নত করে।', 'পেটের পেশীর টান কমায় এবং বুকের ভঙ্গি উন্নত করে।', 'উপুড় হয়ে শুয়ে হাত দুটি কাঁধের নিচে রাখুন এবং হিপ মেঝেতে রেখে ধড় উপরের দিকে ঠেলুন।', 'কাঁধ কান থেকে দূরে রাখুন এবং গভীরভাবে শ্বাস নিন।', 'মেরুদণ্ডে তীব্র কোনো আঘাত থাকলে এটি এড়িয়ে চলুন।', 'ঘাড়ে অতিরিক্ত চাপ দেওয়া বা মেঝে থেকে পেলভিস তুলে ফেলা।'),
('cobra-stretch', 'vi', 'Bài tập rắn hổ mang', 'Động tác vận động linh hoạt giúp kéo giãn thành bụng và cải thiện độ linh hoạt cột sống.', 'Giảm căng thẳng ở cơ bụng và cải thiện tư thế ngực.', 'Nằm sấp, đặt tay dưới vai và đẩy thân trên lên trong khi giữ hông sát sàn.', 'Giữ vai xa tai và hít thở sâu.', 'Tránh tập nếu bị chấn thương cột sống cấp tính.', 'Gồng cổ quá mức hoặc nhấc khung chậu khỏi sàn.'),
('cobra-stretch', 'fa', 'حرکت کبری', 'حرکت پویا برای کشش دیواره شکم و بهبود انعطاف‌پذیری ستون فقرات.', 'تنش عضلات شکم را کاهش داده و وضعیت قفسه سینه را بهبود می‌بخشد.', 'به شکم دراز بکشید، دست‌ها را زیر شانه‌ها قرار دهید و لگن را روی زمین نگه داشته و تنه را به سمت بالا فشار دهید.', 'شانه‌ها را از گوش‌ها دور نگه دارید و عمیق نفس بکشید.', 'در صورت آسیب‌های حاد ستون فقرات از انجام آن خودداری کنید.', 'منقبض کردن بیش از حد گردن یا بلند کردن لگن از زمین.');