-- Definición de ejercicios
INSERT OR IGNORE INTO exercises (slug, img, video, difficulty) 
VALUES 
('crunch-straight-leg-up', 'crunch-straight-leg-up.jpg', 'crunch-straight-leg-up.mp4', 'intermediate'),
('crunch', 'crunch.jpg', 'crunch.mp4', 'beginner');

-- Relaciones de grupos musculares
INSERT INTO exercise_body_target (exercise_slug, body_target_slug) 
VALUES 
('crunch-straight-leg-up', 'abdominals');

-- Relaciones de alternativas
INSERT INTO exercise_alternative (exercise_slug, alternative_slug) 
VALUES 
('crunch-straight-leg-up', 'crunch');

-- Información multiidioma
INSERT OR IGNORE INTO exercises_info (slug, lang, title, description, benefits, instructions, tips, restrictions, mistakes) VALUES 
('crunch-straight-leg-up', 'es', 'Crunch con piernas estiradas', 'Variante de crunch que mantiene las piernas elevadas para anular la ayuda de los flexores de cadera.', 'Aísla la contracción de los abdominales superiores eliminando el impulso de las piernas.', 'Tumbado boca arriba, eleva las piernas a 90 grados y realiza el crunch intentando tocar los pies.', 'Mantén la zona lumbar pegada al suelo para proteger la columna.', 'Evitar si hay dolor agudo en la zona lumbar o cervical.', 'Tirar del cuello con las manos o perder la verticalidad de las piernas.'),
('crunch-straight-leg-up', 'en', 'Crunch with straight legs up', 'Crunch variant that keeps legs elevated to negate the assistance of hip flexors.', 'Isolates upper abdominal contraction by eliminating leg momentum.', 'Lying on your back, lift legs to 90 degrees and perform a crunch reaching towards your toes.', 'Keep your lower back pressed against the floor to protect the spine.', 'Avoid if acute lower back or neck pain exists.', 'Pulling your neck with your hands or losing leg verticality.'),
('crunch-straight-leg-up', 'pt', 'Crunch com pernas estendidas para cima', 'Variante de crunch que mantém as pernas elevadas para anular a ajuda dos flexores do quadril.', 'Isola a contração do abdômen superior eliminando o impulso das pernas.', 'Deitado de costas, eleve as pernas a 90 graus e realize o crunch tentando tocar os pés.', 'Mantenha a lombar colada ao chão para proteger a coluna.', 'Evitar se houver dor aguda na lombar ou cervical.', 'Puxar o pescoço com as mãos ou perder a verticalidade das pernas.'),
('crunch-straight-leg-up', 'fr', 'Crunch jambes tendues vers le haut', 'Variante du crunch gardant les jambes levées pour annuler l''aide des fléchisseurs de hanche.', 'Isole la contraction des abdominaux supérieurs en éliminant l''élan des jambes.', 'Allongé sur le dos, levez les jambes à 90 degrés et faites un crunch en essayant de toucher vos pieds.', 'Gardez le bas du dos plaqué au sol pour protéger la colonne.', 'À éviter en cas de douleur aiguë au bas du dos ou au cou.', 'Tirer sur le cou avec les mains ou perdre la verticalité des jambes.'),
('crunch-straight-leg-up', 'de', 'Crunch mit gestreckten Beinen', 'Crunch-Variante mit erhöhten Beinen, um die Unterstützung der Hüftbeuger auszuschließen.', 'Isoliert die Kontraktion der oberen Bauchmuskeln durch Eliminierung des Beinschwungs.', 'In Rückenlage die Beine auf 90 Grad anheben und einen Crunch ausführen, dabei versuchen, die Füße zu berühren.', 'Den unteren Rücken fest am Boden halten, um die Wirbelsäule zu schützen.', 'Bei akuten Rücken- oder Nackenschmerzen vermeiden.', 'Den Nacken mit den Händen ziehen oder die vertikale Beinposition verlieren.'),
('crunch-straight-leg-up', 'it', 'Crunch con gambe tese verso l''alto', 'Variante del crunch che mantiene le gambe elevate per annullare l''aiuto dei flessori dell''anca.', 'Isola la contrazione degli addominali superiori eliminando lo slancio delle gambe.', 'Sdraiato sulla schiena, solleva le gambe a 90 gradi ed esegui il crunch cercando di toccare i piedi.', 'Mantieni la zona lombare premuta al suolo per proteggere la colonna.', 'Evitare in caso di dolore acuto lombare o cervicale.', 'Tirare il collo con le mani o perdere la verticalità delle gambe.'),
('crunch-straight-leg-up', 'zh', '直腿向上卷腹', '卷腹变体，保持双腿抬起，以消除髋屈肌的辅助作用。', '消除腿部惯性，隔离上腹部的收缩。', '仰卧，将双腿抬高至90度，执行卷腹动作并尝试触碰脚尖。', '保持下背部贴地以保护脊柱。', '如有急性腰痛或颈痛，请避免使用。', '用手拉脖子或双腿偏离垂直线。'),
('crunch-straight-leg-up', 'ja', 'レッグアップ・クランチ', '股関節屈筋の補助を無効にするために脚を上げた状態で行うクランチバリエーション。', '脚の反動を排除し、上腹部の収縮を分離して鍛えます。', '仰向けになり、脚を90度に上げ、つま先を目指してクランチを行います。', '脊椎を保護するため、腰を床に押し付けた状態を維持します。', '腰や首に激しい痛みがある場合は避けてください。', '手で首を引っ張ることや、脚が垂直からずれること。'),
('crunch-straight-leg-up', 'ko', '레그 업 크런치', '고관절 굴곡근의 도움을 배제하기 위해 다리를 높이 든 상태의 크런치 변형.', '다리 반동을 제거하여 상복부 수축을 고립시킴.', '누운 상태에서 다리를 90도로 들어 올리고 발끝을 향해 크런치를 수행함.', '척추 보호를 위해 허리를 바닥에 밀착시킬 것.', '급성 요통이나 경추 통증이 있다면 피할 것.', '손으로 목을 잡아당기거나 다리가 수직에서 벗어나는 것.'),
('crunch-straight-leg-up', 'ar', 'تمرين البطن مع رفع الساقين للأعلى', 'تمرين بطن يحافظ على الساقين مرفوعتين لإلغاء مساعدة عضلات ثني الورك.', 'يعزل انقباض عضلات البطن العلوية عبر إلغاء زخم الساقين.', 'استلقِ على ظهرك، وارفع ساقيك بزاوية 90 درجة وقم بتمرين البطن محاولاً لمس قدميك.', 'حافظ على ملامسة أسفل الظهر للأرض لحماية العمود الفقري.', 'تجنب التمرين في حالة وجود آلام حادة في أسفل الظهر أو الرقبة.', 'سحب الرقبة باليدين أو فقدان استقامة الساقين.'),
('crunch-straight-leg-up', 'hi', 'स्ट्रेट लेग अप क्रंच', 'क्रंच का संस्करण जो हिप फ्लेक्सर्स की सहायता को खत्म करने के लिए पैरों को ऊपर रखता है।', 'पैरों की गति को खत्म करके ऊपरी पेट के संकुचन को अलग करता है।', 'पीठ के बल लेटें, पैरों को 90 डिग्री तक उठाएं और अपने पैरों को छूने की कोशिश करते हुए क्रंच करें।', 'रीढ़ की हड्डी की सुरक्षा के लिए पीठ के निचले हिस्से को फर्श पर दबाए रखें।', 'यदि पीठ के निचले हिस्से या गर्दन में तीव्र दर्द हो तो न करें।', 'हाथों से गर्दन खींचना या पैरों की सीधी स्थिति खो देना।'),
('crunch-straight-leg-up', 'ru', 'Кранч с поднятыми ногами', 'Вариант кранча с поднятыми ногами, исключающий помощь сгибателей бедра.', 'Изолирует сокращение мышц верхнего пресса за счет исключения инерции ног.', 'Лежа на спине, поднимите ноги на 90 градусов и выполняйте кранч, пытаясь коснуться стоп.', 'Прижимайте поясницу к полу для защиты позвоночника.', 'Избегайте при острой боли в пояснице или шее.', 'Тянуть шею руками или потеря вертикального положения ног.'),
('crunch-straight-leg-up', 'nl', 'Crunch met benen gestrekt omhoog', 'Crunch-variant die benen verhoogd houdt om hulp van heupbuigers uit te sluiten.', 'Isoleert contractie van de bovenste buikspieren door beenmomentum te elimineren.', 'Lig op de rug, til de benen tot 90 graden en voer de crunch uit terwijl je probeert je voeten aan te raken.', 'Houd de onderrug tegen de vloer gedrukt om de wervelkolom te beschermen.', 'Vermijden bij acute onderrug- of nekpijn.', 'Aan de nek trekken met de handen of verticale beenpositie verliezen.'),
('crunch-straight-leg-up', 'sv', 'Crunch med raka ben upp', 'Crunch-variant som håller benen upphöjda för att eliminera hjälp från höftböjare.', 'Isolerar kontraktionen av övre magmusklerna genom att eliminera benmomentum.', 'Ligg på rygg, lyft benen till 90 grader och utför crunchen genom att försöka nå fötterna.', 'Håll ländryggen pressad mot golvet för att skydda ryggraden.', 'Undvik vid akut ländryggs- eller nacksmärta.', 'Dra i nacken med händerna eller tappa benens vertikala position.'),
('crunch-straight-leg-up', 'pl', 'Crunch z uniesionymi nogami', 'Wariant cruncha z uniesionymi nogami, wykluczający pomoc zginaczy bioder.', 'Izoluje pracę górnych partii brzucha poprzez eliminację pędu nóg.', 'W leżeniu na plecach, unieś nogi do kąta 90 stopni i wykonuj crunch, próbując dotknąć stóp.', 'Utrzymuj odcinek lędźwiowy dociśnięty do podłoża, aby chronić kręgosłup.', 'Unikaj w przypadku ostrego bólu kręgosłupa lub karku.', 'Ciągnięcie karku rękami lub utrata pionowej pozycji nóg.'),
('crunch-straight-leg-up', 'id', 'Crunch dengan kaki lurus ke atas', 'Variasi crunch yang menjaga kaki tetap terangkat untuk meniadakan bantuan fleksor pinggul.', 'Mengisolasi kontraksi perut atas dengan menghilangkan momentum kaki.', 'Berbaring telentang, angkat kaki ke 90 derajat dan lakukan crunch sambil mencoba menyentuh kaki.', 'Jaga punggung bawah menempel di lantai untuk melindungi tulang belakang.', 'Hindari jika ada nyeri punggung bawah atau leher akut.', 'Menarik leher dengan tangan atau kehilangan vertikalitas kaki.'),
('crunch-straight-leg-up', 'bn', 'স্ট্রেইট লেগ আপ ক্রাঞ্চ', 'হিপ ফ্লেক্সরের সাহায্য বাদ দেওয়ার জন্য পা উপরে রাখা ক্রাঞ্চের একটি সংস্করণ।', 'পায়ের গতি বাদ দিয়ে পেটের উপরের অংশের পেশীকে আলাদাভাবে সংকুচিত করে।', 'পিঠের ওপর শুয়ে পা ৯০ ডিগ্রি পর্যন্ত তুলুন এবং পায়ের আঙুল স্পর্শ করার চেষ্টা করে ক্রাঞ্চ করুন।', 'মেরুদণ্ড সুরক্ষিত রাখতে নিচের পিঠ মেঝেতে চেপে রাখুন।', 'পিঠের নিচের অংশে বা ঘাড়ে তীব্র ব্যথা থাকলে এটি এড়িয়ে চলুন।', 'হাতের সাহায্যে গলা টানা বা পা সোজা না রাখা।'),
('crunch-straight-leg-up', 'vi', 'Crunch với chân giơ thẳng', 'Biến thể crunch giữ chân cao để loại bỏ sự hỗ trợ của cơ gập hông.', 'Cô lập sự co thắt của cơ bụng trên bằng cách loại bỏ quán tính của chân.', 'Nằm ngửa, đưa hai chân lên 90 độ và thực hiện động tác crunch cố gắng chạm vào bàn chân.', 'Giữ lưng dưới áp sát sàn để bảo vệ cột sống.', 'Tránh tập nếu bị đau lưng dưới hoặc đau cổ cấp tính.', 'Kéo cổ bằng tay hoặc làm chân mất tư thế thẳng đứng.'),
('crunch-straight-leg-up', 'fa', 'کرانچ با پاهای صاف رو به بالا', 'نوعی کرانچ که پاها را برای حذف کمک خم‌کننده‌های لگن، بالا نگه می‌دارد.', 'با حذف شتاب پاها، انقباض عضلات بالایی شکم را ایزوله می‌کند.', 'به پشت دراز بکشید، پاها را تا 90 درجه بالا بیاورید و کرانچ بزنید و سعی کنید پاها را لمس کنید.', 'برای محافظت از ستون فقرات، کمر را به زمین بچسبانید.', 'در صورت درد حاد کمر یا گردن از انجام آن خودداری کنید.', 'کشیدن گردن با دست‌ها یا از دست دادن حالت عمودی پاها.');