-- Definición de ejercicios
INSERT OR IGNORE INTO exercises (slug, img, video, difficulty) 
VALUES 
('deadbug', 'deadbug.jpg', 'deadbug.mp4', 'beginner'),
('bird-dog', 'bird-dog.jpg', 'bird-dog.mp4', 'beginner');

-- Relaciones de grupos musculares
INSERT INTO exercise_body_target (exercise_slug, body_target_slug) 
VALUES 
('deadbug', 'abdominals');

-- Relaciones de alternativas
INSERT INTO exercise_alternative (exercise_slug, alternative_slug) 
VALUES 
('deadbug', 'bird-dog');

-- Información multiidioma
INSERT OR IGNORE INTO exercises_info (slug, lang, title, description, benefits, instructions, tips, restrictions, mistakes) VALUES 
('deadbug', 'deadbug', 'Dead bug', 'Ejercicio de estabilización del core que enseña a disociar el movimiento de extremidades manteniendo la columna neutra.', 'Mejora la estabilidad lumbopélvica y el control motor profundo.', 'Tumbado boca arriba, brazos al techo y piernas a 90 grados; baja lentamente brazo y pierna opuesta sin arquear la espalda.', 'Presiona activamente la zona lumbar contra el suelo durante todo el movimiento.', 'Evitar si hay dolor agudo en la zona lumbar.', 'Perder el contacto de la zona lumbar con el suelo o mover las extremidades demasiado rápido.'),
('deadbug', 'en', 'Dead bug', 'Core stabilization exercise teaching limb dissociation while maintaining a neutral spine.', 'Enhances lumbopelvic stability and deep motor control.', 'Lying on your back, arms to ceiling and legs at 90 degrees; slowly lower opposite arm and leg without arching your back.', 'Actively press the lower back against the floor throughout the movement.', 'Avoid if acute lower back pain exists.', 'Losing lumbar contact with the floor or moving limbs too quickly.'),
('deadbug', 'pt', 'Dead bug', 'Exercício de estabilização do core que ensina a dissociar o movimento dos membros mantendo a coluna neutra.', 'Melhora a estabilidade lumbopélvica e o controle motor profundo.', 'Deitado de costas, braços para o teto e pernas a 90 graus; abaixe lentamente o braço e a perna opostos sem arquear as costas.', 'Pressione ativamente a região lombar contra o chão durante todo o movimento.', 'Evitar se houver dor lombar aguda.', 'Perder o contato da região lombar com o chão ou mover os membros muito rapidamente.'),
('deadbug', 'fr', 'Dead bug', 'Exercice de stabilisation du core enseignant la dissociation des membres tout en gardant une colonne neutre.', 'Améliore la stabilité lumbopelvienne et le contrôle moteur profond.', 'Allongé sur le dos, bras au plafond et jambes à 90 degrés; abaissez lentement le bras et la jambe opposés sans cambrer le dos.', 'Pressez activement le bas du dos contre le sol pendant tout le mouvement.', 'À éviter en cas de douleur lombaire aiguë.', 'Perdre le contact du bas du dos avec le sol ou bouger les membres trop rapidement.'),
('deadbug', 'de', 'Dead Bug', 'Kernstabilisierungsübung zur Dissoziation der Gliedmaßen bei neutraler Wirbelsäule.', 'Verbessert die lumbopelvinale Stabilität und tiefe Motorik.', 'In Rückenlage Arme zur Decke und Beine im 90-Grad-Winkel; langsam den gegenüberliegenden Arm und das Bein absenken, ohne den Rücken durchzudrücken.', 'Den unteren Rücken während der gesamten Bewegung aktiv gegen den Boden pressen.', 'Bei akuten Rückenschmerzen vermeiden.', 'Den Kontakt des unteren Rückens zum Boden verlieren oder die Gliedmaßen zu schnell bewegen.'),
('deadbug', 'it', 'Dead bug', 'Esercizio di stabilizzazione del core che insegna a dissociare il movimento degli arti mantenendo la colonna neutra.', 'Migliora la stabilità lumbopelvica e il controllo motorio profondo.', 'Sdraiato sulla schiena, braccia al soffitto e gambe a 90 gradi; abbassa lentamente braccio e gamba opposti senza inarcare la schiena.', 'Premi attivamente la zona lombare contro il pavimento durante tutto il movimento.', 'Evitare in caso di dolore lombare acuto.', 'Perdere il contatto della zona lombare con il pavimento o muovere gli arti troppo velocemente.'),
('deadbug', 'zh', '死虫式', '核心稳定练习，教导在保持脊柱中立的同时分离四肢运动。', '提高腰盆腔稳定性和深层运动控制。', '仰卧，手臂朝天，双腿弯曲90度；缓慢降低对侧手臂和腿，不要拱背。', '在整个动作过程中，主动将腰部压向地面。', '如有急性腰痛，请避免使用。', '腰部与地面失去接触或四肢移动过快。'),
('deadbug', 'ja', 'デッドバグ', '脊椎をニュートラルに保ちながら四肢の動きを分離することを学ぶコア安定化エクササイズ。', '腰骨盤の安定性と深層モーターコントロールを向上させます。', '仰向けになり、腕を天井へ、脚を90度に上げ、背中を反らさずに反対側の手足をゆっくり下ろします。', '動作中、腰を床に押し付けた状態を維持します。', '腰に激しい痛みがある場合は避けてください。', '腰が床から離れることや、手足を速く動かしすぎること。'),
('deadbug', 'ko', '데드 버그', '척추 중립을 유지하면서 사지 움직임을 분리하는 법을 배우는 코어 안정화 운동.', '요골반 안정성과 심부 운동 조절력을 향상시킴.', '누운 상태에서 팔을 천장으로, 다리를 90도로 들고 허리가 들리지 않게 반대쪽 팔과 다리를 천천히 내림.', '동작 내내 허리를 바닥에 밀착시킬 것.', '급성 요통이 있다면 피할 것.', '허리가 바닥에서 떨어지거나 사지를 너무 빨리 움직이는 것.'),
('deadbug', 'ar', 'تمرين الحشرة الميتة (Dead bug)', 'تمرين استقرار الجذع يعلم فصل حركة الأطراف مع الحفاظ على عمود فقري محايد.', 'يحسن استقرار منطقة أسفل الظهر والحوض والتحكم الحركي العميق.', 'استلقِ على ظهرك، وارفع ذراعيك للسقف وساقيك بزاوية 90 درجة؛ أنزل ذراعاً وساقاً متعاكستين ببطء دون تقوس ظهرك.', 'اضغط بنشاط بأسفل ظهرك ضد الأرض طوال فترة التمرين.', 'تجنب التمرين في حالة وجود آلام حادة في أسفل الظهر.', 'فقدان تلامس أسفل الظهر مع الأرض أو تحريك الأطراف بسرعة كبيرة.'),
('deadbug', 'hi', 'डेड बग', 'कोर स्थिरीकरण व्यायाम जो तटस्थ रीढ़ को बनाए रखते हुए अंगों के अलगाव को सिखाता है।', 'लंबोपेलविक स्थिरता और गहरे मोटर नियंत्रण को बढ़ाता है।', 'पीठ के बल लेटें, बाहें छत की ओर और पैर 90 डिग्री पर रखें; पीठ को मोड़े बिना धीरे-धीरे विपरीत हाथ और पैर को नीचे करें।', 'पूरी गति के दौरान पीठ के निचले हिस्से को फर्श पर दबाए रखें।', 'यदि पीठ के निचले हिस्से में तीव्र दर्द हो तो न करें।', 'फर्श के साथ पीठ के निचले हिस्से का संपर्क खोना या अंगों को बहुत जल्दी हिलाना।'),
('deadbug', 'ru', 'Мертвый жук (Dead bug)', 'Упражнение на стабилизацию кора, обучающее диссоциации конечностей при нейтральном положении позвоночника.', 'Улучшает пояснично-тазовую стабильность и глубокий моторный контроль.', 'Лежа на спине, руки вверх, ноги на 90 градусов; медленно опускайте противоположные руку и ногу, не прогибая спину.', 'Активно прижимайте поясницу к полу на протяжении всего движения.', 'Избегайте при острой боли в пояснице.', 'Потеря контакта поясницы с полом или слишком быстрое движение конечностями.'),
('deadbug', 'nl', 'Dead bug', 'Core-stabilisatieoefening die dissociatie van ledematen leert bij een neutrale wervelkolom.', 'Verbetert lumbopelvische stabiliteit en diepe motorische controle.', 'Lig op de rug, armen naar plafond en benen op 90 graden; laat langzaam tegengestelde arm en been zakken zonder de rug hol te trekken.', 'Druk de onderrug actief tegen de vloer tijdens de hele beweging.', 'Vermijden bij acute onderrugpijn.', 'Contact tussen onderrug en vloer verliezen of ledematen te snel bewegen.'),
('deadbug', 'sv', 'Dead bug', 'Core-stabiliseringsövning som lär ut disassociation av lemmar med neutral ryggrad.', 'Förbättrar lumbopelvisk stabilitet och djup motorisk kontroll.', 'Ligg på rygg, armar mot taket och ben i 90 grader; sänk långsamt motsatt arm och ben utan att krumma ryggen.', 'Pressa aktivt ländryggen mot golvet under hela rörelsen.', 'Undvik vid akut ländryggssmärta.', 'Att tappa ländryggens kontakt med golvet eller flytta lemmar för snabbt.'),
('deadbug', 'pl', 'Dead bug', 'Ćwiczenie stabilizujące core, uczące dysocjacji kończyn przy neutralnym kręgosłupie.', 'Poprawia stabilność lędźwiowo-miedniczną i głęboką kontrolę motoryczną.', 'W leżeniu na plecach, ręce do sufitu i nogi pod kątem 90 stopni; powoli obniżaj przeciwległą rękę i nogę bez wyginania kręgosłupa.', 'Aktywnie dociskaj odcinek lędźwiowy do podłogi przez cały czas.', 'Unikaj w przypadku ostrego bólu odcinka lędźwiowego.', 'Utrata kontaktu odcinka lędźwiowego z podłożem lub zbyt szybkie ruchy kończynami.'),
('deadbug', 'id', 'Dead bug', 'Latihan stabilisasi core yang mengajarkan disosiasi anggota tubuh sambil menjaga tulang belakang netral.', 'Meningkatkan stabilitas lumbopelvik dan kontrol motorik dalam.', 'Berbaring telentang, tangan ke langit-langit dan kaki pada 90 derajat; turunkan perlahan tangan dan kaki yang berlawanan tanpa melengkungkan punggung.', 'Tekan punggung bawah secara aktif ke lantai sepanjang gerakan.', 'Hindari jika ada nyeri punggung bawah akut.', 'Kehilangan kontak punggung bawah dengan lantai atau menggerakkan anggota tubuh terlalu cepat.'),
('deadbug', 'bn', 'ডেড বাগ', 'কোর স্ট্যাবিলাইজেশন ব্যায়াম যা মেরুদণ্ড সোজা রেখে অঙ্গপ্রত্যঙ্গের নড়াচড়া শেখায়।', 'লম্বোপেলভিক স্থিতিশীলতা এবং গভীর মোটর নিয়ন্ত্রণ উন্নত করে।', 'পিঠের ওপর শুয়ে হাত ছাদের দিকে ও পা ৯০ ডিগ্রি কোণে রাখুন; পিঠ না বাঁকিয়ে ধীরে ধীরে বিপরীত হাত ও পা নিচে নামান।', 'পুরো ব্যায়াম জুড়ে নিচের পিঠ মেঝের সাথে চেপে রাখুন।', 'পিঠের নিচের অংশে তীব্র ব্যথা থাকলে এটি এড়িয়ে চলুন।', 'নিচের পিঠ মেঝের স্পর্শ হারানো বা হাত-পা খুব দ্রুত চালানো।'),
('deadbug', 'vi', 'Dead bug', 'Bài tập ổn định cơ core giúp tách biệt chuyển động chi trong khi vẫn giữ cột sống trung tính.', 'Cải thiện sự ổn định vùng thắt lưng-chậu và kiểm soát vận động sâu.', 'Nằm ngửa, tay hướng lên trần và chân gập 90 độ; từ từ hạ tay và chân đối diện mà không võng lưng.', 'Ấn lưng dưới xuống sàn một cách chủ động trong suốt quá trình tập.', 'Tránh tập nếu bị đau lưng dưới cấp tính.', 'Mất sự tiếp xúc của lưng dưới với sàn hoặc di chuyển chi quá nhanh.'),
('deadbug', 'fa', 'دد باگ', 'تمرین ثبات‌بخش عضلات مرکزی که جدا کردن حرکات اندام‌ها را در حین حفظ ستون فقرات خنثی می‌آموزد.', 'پایداری لومبوی لگنی و کنترل حرکتی عمقی را بهبود می‌بخشد.', 'به پشت دراز بکشید، دست‌ها به سمت سقف و پاها با زاویه 90 درجه؛ دست و پای مخالف را به آرامی پایین بیاورید بدون اینکه کمر قوس بردارد.', 'در تمام طول حرکت، کمر را فعالانه به زمین فشار دهید.', 'در صورت درد حاد کمر از انجام آن خودداری کنید.', 'از دست دادن تماس کمر با زمین یا حرکت بیش از حد سریع اندام‌ها.');