-- Definición de ejercicios
INSERT OR IGNORE INTO exercises (slug, img, video, difficulty) 
VALUES 
('decline-sit-ups', 'decline-sit-ups.jpg', 'decline-sit-ups.mp4', 'advanced'),
('crunch', 'crunch.jpg', 'crunch.mp4', 'beginner');

-- Relaciones de grupos musculares
INSERT INTO exercise_body_target (exercise_slug, body_target_slug) 
VALUES 
('decline-sit-ups', 'abdominals');

-- Relaciones de alternativas
INSERT INTO exercise_alternative (exercise_slug, alternative_slug) 
VALUES 
('decline-sit-ups', 'crunch');

-- Información multiidioma
INSERT OR IGNORE INTO exercises_info (slug, lang, title, description, benefits, instructions, tips, restrictions, mistakes) VALUES 
('decline-sit-ups', 'es', 'Sit-ups declinados', 'Variante avanzada que utiliza la gravedad para aumentar la carga sobre el recto abdominal mediante un mayor rango de movimiento.', 'Maximiza el reclutamiento de fibras abdominales y la fuerza del core.', 'Asegura los pies en la banca declinada y realiza una flexión completa de tronco hacia las rodillas.', 'Mantén el control en el descenso para evitar impactos en la columna.', 'Evitar si hay problemas de espalda baja o hipertensión.', 'Realizar el movimiento con demasiada inercia o arquear la zona lumbar en la subida.'),
('decline-sit-ups', 'en', 'Decline sit-ups', 'Advanced variant using gravity to increase load on the rectus abdominis through an increased range of motion.', 'Maximizes abdominal fiber recruitment and core strength.', 'Secure feet on the decline bench and perform a full trunk flexion towards your knees.', 'Maintain control during the descent to avoid spinal impact.', 'Avoid if lower back issues or hypertension exist.', 'Using too much momentum or arching the lower back during the ascent.'),
('decline-sit-ups', 'pt', 'Sit-ups declinados', 'Variante avançada que utiliza a gravidade para aumentar a carga no reto abdominal através de uma maior amplitude de movimento.', 'Maximiza o recrutamento de fibras abdominais e a força do core.', 'Prenda os pés no banco declinado e realize uma flexão completa do tronco em direção aos joelhos.', 'Mantenha o controle na descida para evitar impactos na coluna.', 'Evitar se houver problemas na lombar ou hipertensão.', 'Realizar o movimento com muita inércia ou arquear a lombar na subida.'),
('decline-sit-ups', 'fr', 'Sit-ups déclinés', 'Variante avancée utilisant la gravité pour augmenter la charge sur le grand droit via une plus grande amplitude de mouvement.', 'Maximise le recrutement des fibres abdominales et la force du core.', 'Fixez vos pieds sur le banc décliné et effectuez une flexion complète du tronc vers vos genoux.', 'Gardez le contrôle lors de la descente pour éviter les chocs sur la colonne.', 'À éviter en cas de problèmes lombaires ou d''hypertension.', 'Utiliser trop d''élan ou cambrer le bas du dos lors de la montée.'),
('decline-sit-ups', 'de', 'Decline Sit-ups', 'Fortgeschrittene Variante, die die Schwerkraft nutzt, um die Belastung der Bauchmuskeln durch einen größeren Bewegungsumfang zu erhöhen.', 'Maximiert die Rekrutierung von Bauchmuskelfasern und die Rumpfkraft.', 'Füße auf der Negativbank sichern und eine vollständige Rumpfbeugung in Richtung der Knie ausführen.', 'Kontrolle beim Abstieg bewahren, um Stöße auf die Wirbelsäule zu vermeiden.', 'Bei Rückenproblemen oder Bluthochdruck vermeiden.', 'Zu viel Schwung verwenden oder den unteren Rücken beim Aufstieg durchdrücken.'),
('decline-sit-ups', 'it', 'Sit-up declinati', 'Variante avanzata che sfrutta la gravità per aumentare il carico sul retto addominale tramite un maggiore range di movimento.', 'Massimizza il reclutamento delle fibre addominali e la forza del core.', 'Blocca i piedi sulla panca declinata ed esegui una flessione completa del busto verso le ginocchia.', 'Mantieni il controllo durante la discesa per evitare impatti sulla colonna vertebrale.', 'Evitare in caso di problemi lombari o ipertensione.', 'Eseguire il movimento con troppa inerzia o inarcare la zona lombare durante la salita.'),
('decline-sit-ups', 'zh', '下斜仰卧起坐', '利用重力增加腹直肌负荷的高级变体，通过更大的运动范围实现。', '最大限度地招募腹肌纤维并增强核心力量。', '将脚固定在下斜凳上，执行完全的躯干弯曲，向膝盖靠拢。', '下降时保持控制，避免脊柱受到冲击。', '如有背部问题或高血压，请避免使用。', '使用过大的惯性或在上升时拱起腰部。'),
('decline-sit-ups', 'ja', 'デクライン・シットアップ', 'より広い可動域を通じて腹直筋への負荷を高めるために重力を利用した上級バリエーション。', '腹筋群の動員を最大化し、コアの強度を高めます。', 'デクラインベンチに足を固定し、膝に向かって上体を完全に起こします。', '脊椎への衝撃を避けるため、下ろす動作はコントロールを保ちます。', '背中の問題や高血圧がある場合は避けてください。', '反動を使いすぎることや、起き上がる時に腰を反らせること。'),
('decline-sit-ups', 'ko', '디클라인 싯업', '중력을 이용해 더 넓은 가동 범위에서 복직근 부하를 높이는 고급 변형.', '복근 섬유 동원을 극대화하고 코어 근력을 강화함.', '디클라인 벤치에 발을 고정하고 무릎을 향해 상체를 완전히 일으킴.', '척추 충격을 방지하기 위해 내려갈 때 통제력을 유지할 것.', '허리 질환이나 고혈압이 있다면 피할 것.', '반동을 과하게 쓰거나 올라올 때 허리를 젖히는 것.'),
('decline-sit-ups', 'ar', 'تمرين البطن على المقعد المائل (Decline sit-ups)', 'تمرين متقدم يستخدم الجاذبية لزيادة الحمل على عضلة البطن المستقيمة عبر زيادة مدى الحركة.', 'يعظم تفعيل ألياف عضلات البطن وقوة الجذع.', 'ثبّت قدميك على المقعد المائل وقم بثني جذعك بالكامل نحو ركبتيك.', 'حافظ على السيطرة أثناء النزول لتجنب التأثير على العمود الفقري.', 'تجنب التمرين في حالة وجود مشاكل في الظهر أو ارتفاع ضغط الدم.', 'استخدام زخم كبير أو تقوس أسفل الظهر أثناء الصعود.'),
('decline-sit-ups', 'hi', 'डिक्लाइन सिट-अप्स', 'उन्नत संस्करण जो गति की बढ़ी हुई सीमा के माध्यम से रेक्टस एब्डोमिनिस पर भार बढ़ाने के लिए गुरुत्वाकर्षण का उपयोग करता है।', 'पेट की मांसपेशियों को अधिकतम सक्रिय करता है और कोर की ताकत बढ़ाता है।', 'डिक्लाइन बेंच पर पैरों को सुरक्षित करें और घुटनों की ओर पूरा धड़ मोड़ें।', 'रीढ़ पर प्रभाव से बचने के लिए नीचे उतरते समय नियंत्रण रखें।', 'यदि पीठ की समस्या या उच्च रक्तचाप हो तो न करें।', 'बहुत अधिक गति (momentum) का उपयोग करना या ऊपर उठते समय पीठ के निचले हिस्से को मोड़ना।'),
('decline-sit-ups', 'ru', 'Сит-апы на наклонной скамье', 'Продвинутый вариант с использованием гравитации для увеличения нагрузки на прямую мышцу живота за счет большей амплитуды.', 'Максимизирует рекрутирование волокон пресса и силу кора.', 'Закрепите ноги на наклонной скамье и выполните полное сгибание корпуса к коленям.', 'Контролируйте опускание, чтобы избежать ударов по позвоночнику.', 'Избегайте при проблемах со спиной или гипертонии.', 'Использование инерции или прогиб поясницы при подъеме.'),
('decline-sit-ups', 'nl', 'Decline sit-ups', 'Geavanceerde variant die zwaartekracht gebruikt om de belasting op de rectus abdominis te verhogen door groter bewegingsbereik.', 'Maximaliseert rekrutering van buikspiervezels en core-kracht.', 'Zet voeten vast op de decline bank en voer een volledige rompflexie uit richting de knieën.', 'Houd controle tijdens de daling om impact op de wervelkolom te vermijden.', 'Vermijden bij rugklachten of hoge bloeddruk.', 'Te veel momentum gebruiken of onderrug hol trekken tijdens de opwaartse beweging.'),
('decline-sit-ups', 'sv', 'Decline sit-ups', 'Avancerad variant som utnyttjar gravitation för att öka belastningen på rectus abdominis genom ökat rörelseomfång.', 'Maximerar aktivering av magmuskelfibrer och bålstyrka.', 'Säkra fötterna på den lutande bänken och utför en fullständig trunkflexion mot knäna.', 'Behåll kontroll under nedgången för att undvika belastning på ryggraden.', 'Undvik vid ryggproblem eller högt blodtryck.', 'Använda för mycket momentum eller krumma ländryggen under uppstigningen.'),
('decline-sit-ups', 'pl', 'Sit-upy na ławce ujemnej', 'Zaawansowany wariant wykorzystujący grawitację do zwiększenia obciążenia mięśnia prostego brzucha poprzez większy zakres ruchu.', 'Maksymalizuje zaangażowanie włókien mięśniowych brzucha i siłę tułowia.', 'Zablokuj stopy na ławce ujemnej i wykonaj pełne zgięcie tułowia w stronę kolan.', 'Utrzymuj kontrolę podczas opuszczania, aby uniknąć obciążeń kręgosłupa.', 'Unikaj w przypadku problemów z plecami lub nadciśnienia.', 'Używanie zbyt dużego pędu lub wyginanie odcinka lędźwiowego podczas unoszenia.'),
('decline-sit-ups', 'id', 'Decline sit-ups', 'Variasi lanjutan yang menggunakan gravitasi untuk meningkatkan beban pada rektus abdominis melalui rentang gerak yang lebih besar.', 'Memaksimalkan rekrutmen serat otot perut dan kekuatan core.', 'Amankan kaki di bangku decline dan lakukan fleksi batang tubuh penuh ke arah lutut.', 'Jaga kontrol saat turun untuk menghindari dampak pada tulang belakang.', 'Hindari jika ada masalah punggung atau hipertensi.', 'Menggunakan momentum terlalu banyak atau melengkungkan punggung bawah saat naik.'),
('decline-sit-ups', 'bn', 'ডিক্লাইন সিট-আপ', 'শরীরের ওজনকে কাজে লাগিয়ে পেটের পেশীর ওপর লোড বাড়ানোর একটি উন্নত সংস্করণ।', 'পেটের পেশী ও কোর শক্তি বৃদ্ধি করে।', 'ডিক্লাইন বেঞ্চে পা আটকে সম্পূর্ণ শরীরের ওপরের অংশ হাঁটু পর্যন্ত ভাঁজ করুন।', 'মেরুদণ্ডের ওপর চাপ এড়াতে নিচে নামার সময় শরীরের নিয়ন্ত্রণ বজায় রাখুন।', 'পিঠে সমস্যা বা উচ্চ রক্তচাপ থাকলে এটি এড়িয়ে চলুন।', 'গতির ব্যবহার করা বা উপরে ওঠার সময় নিচের পিঠ বাঁকানো।'),
('decline-sit-ups', 'vi', 'Decline sit-ups', 'Biến thể nâng cao sử dụng trọng lực để tăng tải trọng lên cơ bụng thẳng qua phạm vi chuyển động lớn hơn.', 'Tối đa hóa sự kích hoạt cơ bụng và sức mạnh cơ core.', 'Cố định chân trên ghế dốc và thực hiện gập thân người hoàn toàn về phía đầu gối.', 'Kiểm soát chuyển động khi hạ xuống để tránh tác động xấu lên cột sống.', 'Tránh tập nếu bị đau lưng hoặc huyết áp cao.', 'Dùng quán tính quá nhiều hoặc võng lưng khi nâng người lên.'),
('decline-sit-ups', 'fa', 'دیکلاین سیت‌آپ', 'تمرین پیشرفته با استفاده از جاذبه برای افزایش بار روی عضلات راست شکمی از طریق دامنه حرکتی بیشتر.', 'بهره‌گیری حداکثری از فیبرهای عضلات شکم و قدرت عضلات مرکزی.', 'پاها را روی میز شیب‌دار محکم کنید و تنه را کامل به سمت زانوها خم کنید.', 'برای جلوگیری از ضربه به ستون فقرات، در پایین رفتن کنترل داشته باشید.', 'در صورت مشکلات کمر یا فشار خون بالا از انجام آن خودداری کنید.', 'استفاده از شتاب زیاد یا قوس دادن به کمر هنگام بالا آمدن.');