-- Definición de ejercicios
INSERT OR IGNORE INTO exercises (slug, img, video, difficulty) 
VALUES 
('dynamic-plank', 'dynamic-plank.jpg', 'dynamic-plank.mp4', 'intermediate'),
('front-plank', 'front-plank.jpg', 'front-plank.mp4', 'beginner');

-- Relaciones de grupos musculares
INSERT OR IGNORE INTO exercise_body_target (exercise_slug, body_target_slug) 
VALUES 
('dynamic-plank', 'abdominals');

-- Relaciones de alternativas
INSERT OR IGNORE INTO exercise_alternative (exercise_slug, alternative_slug) 
VALUES 
('dynamic-plank', 'front-plank');

-- Información multiidioma
INSERT OR IGNORE INTO exercises_info (slug, lang, title, description, benefits, instructions, tips, restrictions, mistakes) VALUES 
('dynamic-plank', 'es', 'Plancha dinámica', 'Variante de plancha que alterna entre antebrazos y manos para aumentar la activación del core y la estabilidad del hombro.', 'Mejora la estabilidad lumbopélvica y la resistencia de los músculos estabilizadores del hombro.', 'En posición de plancha, pasa de apoyarte en los antebrazos a apoyarte en las manos de forma alterna.', 'Mantén la cadera lo más estable posible, evitando que balancee de lado a lado.', 'Evitar en caso de dolor agudo en los hombros o muñecas.', 'Balancear excesivamente la cadera o realizar el cambio muy rápido sin control.'),
('dynamic-plank', 'en', 'Dynamic plank', 'Plank variant alternating between forearms and hands to increase core activation and shoulder stability.', 'Enhances lumbopelvic stability and endurance of shoulder stabilizer muscles.', 'From a plank position, alternate moving from forearms to hands.', 'Keep the hips as stable as possible, avoiding side-to-side swaying.', 'Avoid if acute shoulder or wrist pain exists.', 'Excessive hip swaying or performing the transition too quickly without control.'),
('dynamic-plank', 'pt', 'Prancha dinâmica', 'Variante de prancha que alterna entre antebraços e mãos para aumentar a ativação do core e a estabilidade do ombro.', 'Melhora a estabilidade lumbopélvica e a resistência dos músculos estabilizadores do ombro.', 'Na posição de prancha, alterne o apoio entre os antebraços e as mãos.', 'Mantenha o quadril o mais estável possível, evitando o balanço lateral.', 'Evitar em caso de dor aguda nos ombros ou pulsos.', 'Balançar excessivamente o quadril ou realizar a transição muito rápido sem controle.'),
('dynamic-plank', 'fr', 'Planche dynamique', 'Variante de planche alternant entre avant-bras et mains pour augmenter l''activation du core et la stabilité de l''épaule.', 'Améliore la stabilité lumbopelvienne et l''endurance des muscles stabilisateurs de l''épaule.', 'En position de planche, passez alternativement des avant-bras aux mains.', 'Gardez les hanches aussi stables que possible, en évitant le balancement latéral.', 'À éviter en cas de douleur aiguë aux épaules ou aux poignets.', 'Balancer excessivement les hanches ou effectuer la transition trop rapidement sans contrôle.'),
('dynamic-plank', 'de', 'Dynamische Plank', 'Plank-Variante, bei der zwischen Unterarmen und Händen gewechselt wird, um die Rumpfaktivierung und Schulterstabilität zu erhöhen.', 'Verbessert die lumbopelvinale Stabilität und die Ausdauer der Schulterstabilisatoren.', 'In Plank-Position abwechselnd von den Unterarmen auf die Hände hochdrücken.', 'Die Hüfte so stabil wie möglich halten und seitliches Schwanken vermeiden.', 'Bei akuten Schulter- oder Handgelenkschmerzen vermeiden.', 'Übermäßiges Hüftschwanken oder zu schneller Wechsel ohne Kontrolle.'),
('dynamic-plank', 'it', 'Plank dinamico', 'Variante del plank che alterna l''appoggio tra avambracci e mani per aumentare l''attivazione del core e la stabilità delle spalle.', 'Migliora la stabilità lumbopelvica e la resistenza dei muscoli stabilizzatori delle spalle.', 'In posizione di plank, passa alternativamente dagli avambracci alle mani.', 'Mantieni il bacino il più stabile possibile, evitando oscillazioni laterali.', 'Evitare in caso di dolore acuto a spalle o polsi.', 'Oscillare eccessivamente il bacino o eseguire la transizione troppo velocemente senza controllo.'),
('dynamic-plank', 'zh', '动态平板支撑', '在手臂和手掌支撑之间交替的平板支撑变体，以增加核心激活和肩部稳定性。', '提高腰盆腔稳定性和肩部稳定肌群的耐力。', '在平板支撑位，交替地从前臂支撑切换到手掌支撑。', '尽量保持臀部稳定，避免左右晃动。', '如有急性肩部或腕部疼痛，请避免使用。', '臀部过度晃动或转换动作过快且失去控制。'),
('dynamic-plank', 'ja', 'ダイナミック・プランク', '前腕と手のひらの支持を交互に入れ替えるプランクバリエーション。コアの活性化と肩の安定性を高めます。', '腰骨盤の安定性と肩の安定筋の持久力を向上させます。', 'プランクの姿勢から、前腕と手の支持を交互に入れ替えます。', '左右に揺れないよう、骨盤をできるだけ安定させます。', '肩や手首に激しい痛みがある場合は避けてください。', '腰を過度に揺らすことや、コントロールを失った速い切り替え。'),
('dynamic-plank', 'ko', '다이내믹 플랭크', '전완과 손바닥 지지를 교대하는 플랭크 변형으로 코어 활성화와 어깨 안정성을 높임.', '요골반 안정성과 어깨 안정근의 지구력을 향상시킴.', '플랭크 자세에서 전완과 손바닥 지지를 번갈아 수행함.', '좌우로 흔들리지 않도록 골반을 최대한 안정적으로 유지할 것.', '어깨나 손목에 급성 통증이 있다면 피할 것.', '골반을 과하게 흔들거나 통제 없이 너무 빠르게 동작할 것.'),
('dynamic-plank', 'ar', 'تمرين البلانك الديناميكي', 'نوع من البلانك يتناوب بين الساعدين واليدين لزيادة تفعيل الجذع واستقرار الكتف.', 'يحسن استقرار منطقة أسفل الظهر والحوض وقوة عضلات الكتف المثبتة.', 'من وضع البلانك، انتقل بالتناوب بين الاستناد على الساعدين والاستناد على اليدين.', 'حافظ على استقرار الحوض قدر الإمكان وتجنب التأرجح الجانبي.', 'تجنب التمرين في حالة وجود آلام حادة في الكتفين أو الرسغين.', 'التأرجح المفرط للحوض أو الانتقال بسرعة كبيرة دون تحكم.'),
('dynamic-plank', 'hi', 'डायनेमिक प्लेंक', 'प्लेंक का संस्करण जो कोर सक्रियण और कंधे की स्थिरता बढ़ाने के लिए अग्रबाहुओं और हाथों के बीच बारी-बारी से चलता है।', 'लंबोपेलविक स्थिरता और कंधे की स्थिरता वाली मांसपेशियों की सहनशक्ति में सुधार करता है।', 'प्लेंक स्थिति में, अग्रबाहुओं से हाथों पर बारी-बारी से जाएं।', 'कूल्हों को यथासंभव स्थिर रखें, अगल-बगल हिलने से बचें।', 'यदि कंधे या कलाई में तीव्र दर्द हो तो न करें।', 'कूल्हों का अत्यधिक हिलना या नियंत्रण के बिना बहुत जल्दी परिवर्तन करना।'),
('dynamic-plank', 'ru', 'Динамическая планка', 'Вариант планки с переходом с предплечий на ладони для усиления активации кора и стабильности плеч.', 'Улучшает пояснично-тазовую стабильность и выносливость мышц плечевого пояса.', 'Из положения планки поочередно переходите с упора на предплечья в упор на ладони.', 'Держите таз максимально стабильным, избегая раскачивания из стороны в сторону.', 'Избегайте при острой боли в плечах или запястьях.', 'Чрезмерное раскачивание таза или слишком быстрый переход без контроля.'),
('dynamic-plank', 'nl', 'Dynamische plank', 'Plank-variant die wisselt tussen onderarmen en handen om core-activering en schouderstabiliteit te verhogen.', 'Verbetert lumbopelvische stabiliteit en uithoudingsvermogen van schouderstabilisatoren.', 'Wissel vanuit plankpositie af tussen steunen op onderarmen en handen.', 'Houd het bekken zo stabiel mogelijk en vermijd zijwaarts zwaaien.', 'Vermijden bij acute schouder- of polspijn.', 'Overmatig zwaaien met bekken of te snelle overgang zonder controle.'),
('dynamic-plank', 'sv', 'Dynamisk planka', 'Plank-variant som växlar mellan underarmar och händer för att öka core-aktivering och axelstabilitet.', 'Förbättrar lumbopelvisk stabilitet och uthållighet i axelstabilisatorer.', 'I plankposition, växla mellan att stödja på underarmar och händer.', 'Håll bäckenet så stabilt som möjligt och undvik att svänga i sidled.', 'Undvik vid akut axel- eller handledssmärta.', 'Att svänga för mycket med bäckenet eller göra övergången för snabbt utan kontroll.'),
('dynamic-plank', 'pl', 'Dynamiczna deska', 'Wariant deski z przechodzeniem z przedramion na dłonie, zwiększający zaangażowanie mięśni tułowia i stabilność barków.', 'Poprawia stabilność lędźwiowo-miedniczną i wytrzymałość stabilizatorów barków.', 'W pozycji deski, przechodź na przemian z podparcia na przedramionach do podparcia na dłoniach.', 'Trzymaj miednicę jak najbardziej stabilnie, unikając kołysania na boki.', 'Unikaj w przypadku ostrego bólu barków lub nadgarstków.', 'Nadmierne kołysanie miednicą lub zbyt szybkie przejście bez kontroli.'),
('dynamic-plank', 'id', 'Dynamic plank', 'Variasi plank yang bergantian antara lengan bawah dan tangan untuk meningkatkan aktivasi core dan stabilitas bahu.', 'Meningkatkan stabilitas lumbopelvik dan daya tahan otot penstabil bahu.', 'Dari posisi plank, bergantian bergerak dari lengan bawah ke tangan.', 'Jaga panggul seimbang mungkin, hindari goyangan dari sisi ke sisi.', 'Hindari jika ada nyeri bahu atau pergelangan tangan akut.', 'Goyangan panggul berlebihan atau melakukan transisi terlalu cepat tanpa kontrol.'),
('dynamic-plank', 'bn', 'ডায়নামিক প্ল্যাঙ্ক', 'কোর অ্যাক্টিভেশন এবং কাঁধের স্থিতিশীলতা বাড়াতে হাতের এবং কনুইয়ের ওপর ভর দেওয়ার একটি প্ল্যাঙ্ক সংস্করণ।', 'লম্বোপেলভিক স্থিতিশীলতা এবং কাঁধের পেশীর সহনশীলতা বাড়ায়।', 'প্ল্যাঙ্ক পজিশন থেকে, কনুই ও হাতের ওপর ভর অদলবদল করুন।', 'হিপ যতটা সম্ভব স্থির রাখুন, ডানে-বামে দোলানো এড়িয়ে চলুন।', 'কাঁধে বা কবজিতে তীব্র ব্যথা থাকলে এটি এড়িয়ে চলুন।', 'হিপ অতিরিক্ত দোলানো বা নিয়ন্ত্রণের বাইরে খুব দ্রুত পরিবর্তন করা।'),
('dynamic-plank', 'vi', 'Plank động', 'Biến thể plank thay đổi giữa cẳng tay và bàn tay để tăng cường kích hoạt core và sự ổn định của vai.', 'Cải thiện sự ổn định vùng thắt lưng-chậu và độ bền của các cơ ổn định vai.', 'Ở tư thế plank, luân phiên thay đổi giữa chống cẳng tay và chống tay.', 'Giữ khung chậu ổn định nhất có thể, tránh đung đưa hai bên.', 'Tránh tập nếu bị đau vai hoặc cổ tay cấp tính.', 'Đung đưa khung chậu quá mức hoặc thực hiện chuyển đổi quá nhanh mất kiểm soát.'),
('dynamic-plank', 'fa', 'پلانک پویا', 'نوعی پلانک که بین ساعدها و دست‌ها جابجا می‌شود تا فعال‌سازی عضلات مرکزی و ثبات شانه‌ها را افزایش دهد.', 'پایداری لومبوی لگنی و استقامت عضلات تثبیت‌کننده شانه را بهبود می‌بخشد.', 'در حالت پلانک، به نوبت از ساعدها به کف دست‌ها جابجا شوید.', 'لگن را تا حد ممکن ثابت نگه دارید و از تاب خوردن جانبی پرهیز کنید.', 'در صورت درد حاد شانه یا مچ دست از انجام آن خودداری کنید.', 'تاب دادن بیش از حد لگن یا انجام جابجایی خیلی سریع و بدون کنترل.');