-- Definición de ejercicio principal
INSERT OR IGNORE INTO exercises (slug, img, video, difficulty) 
VALUES 
('mountain-climbers', 'mountain-climbers.jpg', 'mountain-climbers.mp4', 'intermediate'),
('forearm-plank', 'forearm-plank.jpg', 'forearm-plank.mp4', 'beginner');

-- Relación de grupo muscular
INSERT INTO exercise_body_target (exercise_slug, body_target_slug) 
VALUES 
('forearm-plank', 'abdominals');

-- Relaciones de alternativas (incluyendo el alias como sugerencia)
INSERT OR IGNORE INTO exercise_alternative (exercise_slug, alternative_slug) 
VALUES
('forearm-plank', 'hollow-body-hold'),
('forearm-plank', 'mountain-climbers');

-- Información multiidioma
INSERT OR IGNORE INTO exercises_info (slug, lang, title, description, benefits, instructions, tips, restrictions, mistakes) VALUES 
('forearm-plank', 'es', 'Plancha de antebrazos', 'Ejercicio isométrico para la estabilización central completa.', 'Fortalece todo el core, incluyendo recto abdominal y oblicuos.', 'Mantén el cuerpo en línea recta apoyado sobre antebrazos y puntas de los pies.', 'Activa los glúteos y evita que la cadera se hunda.', 'Evitar si hay problemas lumbares severos.', 'Dejar caer la pelvis o elevar demasiado los glúteos.'),
('forearm-plank', 'en', 'Forearm plank', 'Isometric exercise for full core stabilization.', 'Strengthens the entire core, including rectus abdominis and obliques.', 'Keep the body in a straight line supported by forearms and toes.', 'Engage glutes and prevent hips from sagging.', 'Avoid if severe lower back issues exist.', 'Dropping the pelvis or lifting the glutes too high.'),
('forearm-plank', 'pt', 'Prancha de antebraços', 'Exercício isométrico para estabilização central completa.', 'Fortalece todo o core, incluindo reto abdominal e oblíquos.', 'Mantenha o corpo em linha reta apoiado sobre antebraços e pontas dos pés.', 'Ative os glúteos e evite que o quadril afunde.', 'Evitar se houver problemas lombares severos.', 'Deixar cair a pelve ou elevar demais os glúteos.'),
('forearm-plank', 'fr', 'Gainage sur les avant-bras', 'Exercice isométrique pour la stabilisation centrale complète.', 'Renforce tout le core, y compris le grand droit et les obliques.', 'Gardez le corps en ligne droite en appui sur les avant-bras et la pointe des pieds.', 'Engagez les fessiers et évitez que le bassin ne s''affaisse.', 'À éviter en cas de problèmes lombaires sévères.', 'Laisser tomber le bassin ou lever trop haut les fessiers.'),
('forearm-plank', 'de', 'Unterarmstütz (Plank)', 'Isometrische Übung zur vollständigen Rumpfstabilisierung.', 'Stärkt den gesamten Rumpf, einschließlich des geraden Bauchmuskels und der schrägen Bauchmuskeln.', 'Halte den Körper in einer geraden Linie, gestützt auf Unterarmen und Zehen.', 'Aktiviere die Gesäßmuskulatur und verhindere ein Absinken der Hüfte.', 'Bei schweren Rückenproblemen vermeiden.', 'Das Becken durchhängen lassen oder das Gesäß zu hoch heben.'),
('forearm-plank', 'it', 'Plank sugli avambracci', 'Esercizio isometrico per la stabilizzazione centrale completa.', 'Rinforza tutto il core, inclusi retto addominale e obliqui.', 'Mantieni il corpo in linea retta appoggiato su avambracci e punte dei piedi.', 'Attiva i glutei ed evita che il bacino scenda.', 'Evitare in caso di gravi problemi lombari.', 'Lasciar cadere il bacino o sollevare troppo i glutei.'),
('forearm-plank', 'zh', '前臂平板支撑', '用于全面核心稳定的等长练习。', '增强整个核心，包括腹直肌和腹斜肌。', '保持身体呈直线，支撑在前臂和脚尖上。', '收紧臀部，防止臀部下垂。', '如有严重的腰部问题，请避免使用。', '让骨盆下垂或臀部抬得太高。'),
('forearm-plank', 'ja', 'フォアアームプランク', '体幹全体の安定化のための等尺性運動。', '腹直筋や腹斜筋を含む体幹全体を強化します。', '前腕とつま先で支え、体を一直線に保ちます。', 'お尻に力を入れ、腰が沈まないようにします。', '重度の腰痛がある場合は避けてください。', '骨盤が下がることやお尻を上げすぎること。'),
('forearm-plank', 'ko', '포어암 플랭크', '완전한 코어 안정화를 위한 등척성 운동.', '복직근 및 외복사근을 포함한 코어 전체 강화.', '전완과 발끝으로 지지하며 몸을 일직선으로 유지할 것.', '둔근을 활성화하고 골반이 처지지 않게 주의.', '심각한 요통이 있다면 피할 것.', '골반이 처지거나 엉덩이를 너무 높게 드는 것.'),
('forearm-plank', 'ar', 'تمرين بلانك على الساعدين', 'تمرين متساوي القياس لاستقرار الجذع الكامل.', 'يقوي الجذع بالكامل، بما في ذلك عضلة البطن المستقيمة والعضلات المائلة.', 'حافظ على استقامة جسمك مع الاستناد على الساعدين وأصابع القدمين.', 'شغّل عضلات الأرداف وامنع هبوط الحوض.', 'تجنب التمرين في حالة وجود مشاكل حادة في أسفل الظهر.', 'سقوط الحوض أو رفع الأرداف بشكل مفرط.'),
('forearm-plank', 'hi', 'फोरआर्म प्लैंक', 'पूर्ण कोर स्थिरीकरण के लिए आइसोमेट्रिक व्यायाम।', 'रेक्टस एबडोमिनिस और ऑब्लिक सहित पूरे कोर को मजबूत करता है।', 'अग्रबाहुओं और पैरों के पंजों पर टिककर शरीर को एक सीधी रेखा में रखें।', 'ग्लूट्स को सक्रिय करें और कूल्हों को नीचे गिरने से रोकें।', 'यदि पीठ के निचले हिस्से में गंभीर समस्या हो तो न करें।', 'पेल्विस को गिरने देना या ग्लूट्स को बहुत ऊपर उठाना।'),
('forearm-plank', 'ru', 'Планка на предплечьях', 'Изометрическое упражнение для полной стабилизации кора.', 'Укрепляет весь кор, включая прямую мышцу живота и косые мышцы.', 'Держите тело в прямой линии, опираясь на предплечья и носки.', 'Напрягайте ягодицы и не допускайте провисания таза.', 'Избегайте при серьезных проблемах с поясницей.', 'Опускание таза или слишком высокий подъем ягодиц.'),
('forearm-plank', 'nl', 'Onderarm-plank', 'Isometrische oefening voor volledige core-stabilisatie.', 'Versterkt de hele core, inclusief de rechte buikspier en schuine buikspieren.', 'Houd het lichaam in een rechte lijn, ondersteund door onderarmen en tenen.', 'Activeer de bilspieren en voorkom dat de heupen doorzakken.', 'Vermijden bij ernstige rugklachten.', 'Het bekken laten zakken of de billen te hoog optillen.'),
('forearm-plank', 'sv', 'Underarmsplanka', 'Isometrisk övning för fullständig bålstabilisering.', 'Stärker hela bålen, inklusive den raka magmuskeln och de sneda magmusklerna.', 'Håll kroppen i en rak linje, stödd på underarmar och tår.', 'Aktivera sätesmusklerna och förhindra att höfterna sjunker.', 'Undvik vid allvarliga ryggproblem.', 'Att låta bäckenet sjunka eller att lyfta sätet för högt.'),
('forearm-plank', 'pl', 'Plank na przedramionach', 'Ćwiczenie izometryczne dla pełnej stabilizacji core.', 'Wzmacnia cały core, w tym mięsień prosty brzucha i mięśnie skośne.', 'Utrzymuj ciało w linii prostej, opierając się na przedramionach i palcach stóp.', 'Aktywuj pośladki i zapobiegaj opadaniu bioder.', 'Unikaj w przypadku poważnych problemów z kręgosłupa.', 'Opadanie miednicy lub zbyt wysokie unoszenie pośladków.'),
('forearm-plank', 'id', 'Plank lengan bawah', 'Latihan isometrik untuk stabilisasi core penuh.', 'Memperkuat seluruh core, termasuk otot perut rectus dan oblique.', 'Jaga tubuh dalam garis lurus, ditopang oleh lengan bawah dan jari kaki.', 'Aktifkan otot bokong dan cegah pinggul melorot.', 'Hindari jika ada masalah punggung bawah yang parah.', 'Membiarkan panggul jatuh atau mengangkat bokong terlalu tinggi.'),
('forearm-plank', 'bn', 'ফোরআর্ম প্ল্যাঙ্ক', 'সম্পূর্ণ কোর স্থিতিশীলতার জন্য আইসোমেট্রিক ব্যায়াম।', 'রেকটাস অ্যাবডোমিনিস এবং অবলিকসহ পুরো কোর শক্তিশালী করে।', 'শরীরের ওজন হাতের কবজি ও পায়ের আঙুলের ওপর রেখে সোজা রাখুন।', 'গ্লুটস সক্রিয় করুন এবং নিতম্ব নিচে নেমে যাওয়া রোধ করুন।', 'পিঠের নিচের অংশে গুরুতর সমস্যা থাকলে এটি এড়িয়ে চলুন।', 'পেলভিস নিচে নেমে যাওয়া বা গ্লুটস খুব বেশি উপরে তোলা।'),
('forearm-plank', 'vi', 'Plank cẳng tay', 'Bài tập đẳng trường để ổn định toàn bộ core.', 'Tăng cường toàn bộ core, bao gồm cơ bụng thẳng và cơ chéo.', 'Giữ cơ thể trên một đường thẳng, chống bằng cẳng tay và mũi chân.', 'Kích hoạt cơ mông và tránh để hông võng xuống.', 'Tránh tập nếu bị các vấn đề nghiêm trọng về lưng dưới.', 'Để khung chậu võng xuống hoặc nâng mông quá cao.'),
('forearm-plank', 'fa', 'پلانک روی ساعد', 'تمرین ایزومتریک برای تثبیت کامل هسته بدن.', 'کل هسته بدن، از جمله عضله راست شکمی و عضلات مایل را تقویت می‌کند.', 'بدن را در یک خط مستقیم نگه دارید و روی ساعدها و پنجه‌های پا تکیه کنید.', 'عضلات باسن را درگیر کنید و از افتادن لگن جلوگیری کنید.', 'در صورت وجود مشکلات جدی کمر از انجام آن خودداری کنید.', 'اجازه دادن به لگن برای پایین افتادن یا بلند کردن بیش از حد باسن.');