-- Definición de ejercicios
INSERT OR IGNORE INTO exercises (slug, img, video, difficulty) 
VALUES 
('front-plank', 'front-plank.jpg', 'front-plank.mp4', 'beginner'),
('dynamic-plank', 'dynamic-plank.jpg', 'dynamic-plank.mp4', 'intermediate');

-- Relaciones de grupos musculares
INSERT INTO exercise_body_target (exercise_slug, body_target_slug) 
VALUES 
('front-plank', 'abdominals');

-- Relaciones de alternativas
INSERT INTO exercise_alternative (exercise_slug, alternative_slug) 
VALUES 
('front-plank', 'dynamic-plank');

-- Información multiidioma
INSERT OR IGNORE INTO exercises_info (slug, lang, title, description, benefits, instructions, tips, restrictions, mistakes) VALUES 
('front-plank', 'es', 'Plancha frontal', 'Ejercicio isométrico fundamental para el fortalecimiento de todo el core y la estabilización de la columna.', 'Mejora la postura, la fuerza abdominal profunda y la estabilidad lumbopélvica.', 'Apóyate sobre los antebrazos y las puntas de los pies, manteniendo el cuerpo en línea recta desde la cabeza a los talones.', 'Contrae activamente los glúteos y el abdomen para evitar que la zona lumbar se arquee.', 'Evitar si hay dolor agudo en la zona lumbar o en los hombros.', 'Dejar caer la cadera hacia el suelo o elevarla demasiado en forma de "V".'),
('front-plank', 'en', 'Front plank', 'Fundamental isometric exercise for core strengthening and spinal stabilization.', 'Improves posture, deep abdominal strength, and lumbopelvic stability.', 'Support yourself on forearms and toes, keeping your body in a straight line from head to heels.', 'Actively contract glutes and abs to prevent the lower back from arching.', 'Avoid if acute lower back or shoulder pain exists.', 'Letting hips sag towards the floor or raising them too high into a "V" shape.'),
('front-plank', 'pt', 'Prancha frontal', 'Exercício isométrico fundamental para o fortalecimento de todo o core e estabilização da coluna.', 'Melhora a postura, a força abdominal profunda e a estabilidade lumbopélvica.', 'Apoie-se nos antebraços e nas pontas dos pés, mantendo o corpo em linha reta da cabeça aos calcanhares.', 'Contraia ativamente os glúteos e o abdômen para evitar que a região lombar arqueie.', 'Evitar se houver dor lombar ou nos ombros.', 'Deixar o quadril cair em direção ao chão ou elevá-lo demais em forma de "V".'),
('front-plank', 'fr', 'Planche frontale', 'Exercice isométrique fondamental pour le renforcement du core et la stabilisation de la colonne vertébrale.', 'Améliore la posture, la force abdominale profonde et la stabilité lumbopelvienne.', 'Appuyez-vous sur vos avant-bras et la pointe de vos pieds, en gardant le corps en ligne droite de la tête aux talons.', 'Contractez activement les fessiers et les abdominaux pour éviter que le bas du dos ne se cambre.', 'À éviter en cas de douleur aiguë au bas du dos ou aux épaules.', 'Laisser tomber les hanches vers le sol ou les lever trop haut en forme de "V".'),
('front-plank', 'de', 'Unterarmstütz (Plank)', 'Fundamentale isometrische Übung zur Kräftigung des gesamten Rumpfes und zur Stabilisierung der Wirbelsäule.', 'Verbessert die Haltung, die tiefe Bauchkraft und die lumbopelvinale Stabilität.', 'Auf Unterarme und Fußspitzen stützen, den Körper von Kopf bis Ferse in einer geraden Linie halten.', 'Gesäß und Bauch aktiv anspannen, um ein Durchhängen des unteren Rückens zu vermeiden.', 'Bei akuten Rücken- oder Schulterschmerzen vermeiden.', 'Hüfte durchhängen lassen oder zu weit in V-Form anheben.'),
('front-plank', 'it', 'Plank frontale', 'Esercizio isometrico fondamentale per il rafforzamento di tutto il core e la stabilizzazione della colonna vertebrale.', 'Migliora la postura, la forza addominale profonda e la stabilità lumbopelvica.', 'Poggia sugli avambracci e sulle punte dei piedi, mantenendo il corpo in linea retta dalla testa ai talloni.', 'Contrai attivamente glutei e addome per evitare che la zona lombare si inarchi.', 'Evitare in caso di dolore acuto alla zona lombare o alle spalle.', 'Lasciare cadere il bacino verso il suolo o sollevarlo troppo in forma di "V".'),
('front-plank', 'zh', '平板支撑', '增强核心力量和脊柱稳定性的基础等长训练。', '改善体态，提升腹部深层力量及腰盆腔稳定性。', '用前臂和脚尖支撑，保持身体从头到脚后跟呈一条直线。', '主动收紧臀部和腹部，防止腰部塌陷。', '如有急性腰痛或肩痛，请避免使用。', '臀部下垂或将其抬得过高形成“V”字形。'),
('front-plank', 'ja', 'フロントプランク', 'コア全体の強化と脊椎の安定化のための基本的なアイソメトリック運動。', '姿勢の改善、深層腹筋の強化、腰骨盤の安定性を高めます。', '前腕とつま先で支え、頭からかかとまで体を一直線に保ちます。', '腰が反らないように臀部と腹部を積極的に収縮させます。', '腰や肩に激しい痛みがある場合は避けてください。', '腰が床に落ちることや、逆V字型に高く上げすぎること。'),
('front-plank', 'ko', '프론트 플랭크', '코어 강화와 척추 안정화를 위한 기초 등척성 운동.', '자세 교정, 심부 복근 강화, 요골반 안정성 향상.', '전완과 발끝으로 지지하며 머리부터 발뒤꿈치까지 몸을 일직선으로 유지할 것.', '허리가 꺾이지 않도록 둔근과 복근을 능동적으로 수축시킬 것.', '요통이나 어깨 통증이 있다면 피할 것.', '골반이 바닥으로 처지거나 V자 형태로 너무 높게 올라가는 것.'),
('front-plank', 'ar', 'تمرين البلانك الأمامي', 'تمرين ثبات (إيزومتري) أساسي لتقوية الجذع واستقرار العمود الفقري.', 'يحسن القوام، قوة عضلات البطن العميقة، واستقرار الحوض.', 'استند على ساعديك وأطراف أصابع قدميك، مع الحفاظ على استقامة جسمك من الرأس إلى الكعبين.', 'قبض عضلات المؤخرة والبطن بنشاط لتجنب تقوس أسفل الظهر.', 'تجنب التمرين في حالة وجود آلام حادة في أسفل الظهر أو الكتفين.', 'ترك الحوض ينخفض نحو الأرض أو رفعه عالياً على شكل حرف "V".'),
('front-plank', 'hi', 'फ्रंट प्लेंक', 'पूरे कोर को मजबूत करने और रीढ़ की हड्डी को स्थिर करने के लिए मौलिक आइसोमेट्रिक व्यायाम।', 'मुद्रा (posture), गहरी पेट की ताकत और लंबोपेलविक स्थिरता में सुधार करता है।', 'अग्रबाहुओं और पंजों पर खुद को सहारा दें, शरीर को सिर से एड़ी तक सीधी रेखा में रखें।', 'पीठ के निचले हिस्से को मुड़ने से रोकने के लिए ग्लूट्स और पेट को सक्रिय रूप से सिकोड़ें।', 'यदि पीठ के निचले हिस्से या कंधे में तीव्र दर्द हो तो न करें।', 'कूल्हों को फर्श की ओर गिरने देना या उन्हें "V" आकार में बहुत ऊपर उठाना।'),
('front-plank', 'ru', 'Планка на предплечьях', 'Фундаментальное изометрическое упражнение для укрепления кора и стабилизации позвоночника.', 'Улучшает осанку, силу глубоких мышц живота и пояснично-тазовую стабильность.', 'Опираясь на предплечья и носки, держите тело в одну линию от головы до пяток.', 'Активно напрягайте ягодицы и пресс, чтобы поясница не прогибалась.', 'Избегайте при острой боли в пояснице или плечах.', 'Провисание таза или поднятие его слишком высоко в форме буквы "V".'),
('front-plank', 'nl', 'Front plank', 'Fundamentele isometrische oefening voor core-versterking en spinale stabilisatie.', 'Verbetert houding, diepe buikspierkracht en lumbopelvische stabiliteit.', 'Steun op onderarmen en tenen, houd het lichaam in een rechte lijn van hoofd tot hielen.', 'Span billen en buik actief aan om doorzakken van de onderrug te voorkomen.', 'Vermijden bij acute rug- of schouderpijn.', 'Bekken laten doorzakken of te hoog optillen in V-vorm.'),
('front-plank', 'sv', 'Frontplanka', 'Grundläggande isometrisk övning för bålstyrka och stabilisering av ryggraden.', 'Förbättrar hållning, djup magstyrka och lumbopelvisk stabilitet.', 'Stöd dig på underarmar och tår, håll kroppen i en rak linje från huvud till häl.', 'Aktivera sätet och magen för att undvika att svanka.', 'Undvik vid akut rygg- eller axelsmärta.', 'Att låta bäckenet sjunka eller lyfta det för högt i V-form.'),
('front-plank', 'pl', 'Plank (deska)', 'Podstawowe ćwiczenie izometryczne wzmacniające core i stabilizujące kręgosłup.', 'Poprawia postawę, siłę głęboką brzucha i stabilność lędźwiowo-miedniczną.', 'Podeprzyj się na przedramionach i palcach stóp, utrzymując ciało w linii prostej od głowy do pięt.', 'Aktywnie napinaj pośladki i brzuch, aby uniknąć wyginania kręgosłupa w odcinku lędźwiowym.', 'Unikaj w przypadku ostrego bólu pleców lub barków.', 'Opuszczanie miednicy w stronę podłogi lub zbyt wysokie unoszenie jej w kształt litery "V".'),
('front-plank', 'id', 'Front plank', 'Latihan isometrik dasar untuk penguatan core dan stabilisasi tulang belakang.', 'Meningkatkan postur, kekuatan otot perut dalam, dan stabilitas lumbopelvik.', 'Tumpu pada lengan bawah dan ujung jari kaki, jaga tubuh dalam garis lurus dari kepala ke tumit.', 'Kontraksikan otot glute dan perut untuk mencegah punggung bawah melengkung.', 'Hindari jika ada nyeri punggung bawah atau bahu akut.', 'Membiarkan panggul turun ke lantai atau mengangkatnya terlalu tinggi membentuk "V".'),
('front-plank', 'bn', 'ফ্রন্ট প্ল্যাঙ্ক', 'কোর শক্তিশালী করা এবং মেরুদণ্ড স্থিতিশীল করার জন্য মৌলিক আইসোমেট্রিক ব্যায়াম।', 'শারীরিক গঠন, পেটের গভীরের পেশী শক্তি এবং লম্বোপেলভিক স্থিতিশীলতা উন্নত করে।', 'কনুই ও পায়ের আঙুলের ওপর ভর দিয়ে মাথা থেকে গোড়ালি পর্যন্ত শরীর সোজা রাখুন।', 'নিচের পিঠ বাঁকানো এড়াতে গ্লুটস ও পেটের পেশী শক্ত করে রাখুন।', 'পিঠের নিচের অংশে বা কাঁধে তীব্র ব্যথা থাকলে এটি এড়িয়ে চলুন।', 'হিপ মেঝেতে নামিয়ে দেওয়া বা "V" আকারে খুব উপরে তোলা।'),
('front-plank', 'vi', 'Plank cơ bản', 'Bài tập isometric cơ bản để tăng cường cơ core và ổn định cột sống.', 'Cải thiện tư thế, sức mạnh cơ bụng sâu và sự ổn định vùng thắt lưng-chậu.', 'Chống bằng cẳng tay và mũi chân, giữ cơ thể thành một đường thẳng từ đầu đến gót chân.', 'Gồng mông và bụng để tránh võng lưng dưới.', 'Tránh tập nếu bị đau lưng dưới hoặc đau vai cấp tính.', 'Để khung chậu sụp xuống sàn hoặc nâng quá cao tạo thành hình chữ "V".'),
('front-plank', 'fa', 'پلانک شکمی', 'تمرین ایزومتریک اساسی برای تقویت عضلات مرکزی و تثبیت ستون فقرات.', 'بهبود وضعیت بدنی، قدرت عمقی شکم و ثبات لگنی.', 'روی ساعدها و پنجه پا تکیه کنید و بدن را از سر تا پاشنه در یک خط مستقیم نگه دارید.', 'عضلات باسن و شکم را فعالانه منقبض کنید تا از قوس برداشتن کمر جلوگیری شود.', 'در صورت درد حاد کمر یا شانه از انجام آن خودداری کنید.', 'افتادن لگن به سمت زمین یا بالا آوردن بیش از حد آن به شکل حرف "V".');