-- Definición de ejercicios
INSERT OR IGNORE INTO exercises (slug, img, video, difficulty) 
VALUES 
('glute-bridge', 'glute-bridge.jpg', 'glute-bridge.mp4', 'beginner'),
('single-leg-glute-bridge', 'single-leg-glute-bridge.jpg', 'single-leg-glute-bridge.mp4', 'beginner');

-- Relaciones de grupos musculares (Solo para glute-bridge)
INSERT OR IGNORE INTO exercise_body_target (exercise_slug, body_target_slug) 
VALUES 
('glute-bridge', 'abdominals'),
('glute-bridge', 'glutes');

-- Relaciones de alternativas
INSERT OR IGNORE INTO exercise_alternative (exercise_slug, alternative_slug) 
VALUES 
('glute-bridge', 'single-leg-glute-bridge');

-- Información multiidioma
INSERT OR IGNORE INTO exercises_info (slug, lang, title, description, benefits, instructions, tips, restrictions, mistakes) VALUES 
('glute-bridge', 'es', 'Puente de glúteos', 'Ejercicio de cadena posterior que requiere estabilización abdominal activa para fortalecer glúteos e isquiotibiales.', 'Mejora la fuerza de la cadera y estabiliza el núcleo abdominal.', 'Tumbado boca arriba con rodillas flexionadas, eleva la pelvis hacia el techo contrayendo glúteos y abdomen.', 'Empuja con los talones y mantén el core firme para evitar arquear la zona lumbar.', 'Evitar si hay dolor agudo en la zona lumbar o cervical.', 'Subir con la espalda en lugar de los glúteos o relajar el abdomen durante el movimiento.'),
('glute-bridge', 'en', 'Glute bridge', 'Posterior chain exercise requiring active abdominal stabilization to strengthen glutes and hamstrings.', 'Enhances hip strength and abdominal core stability.', 'Lying on your back with knees bent, lift your pelvis towards the ceiling, squeezing glutes and engaging abs.', 'Push through your heels and keep your core tight to avoid lower back arching.', 'Avoid if acute lower back or neck pain exists.', 'Lifting with your back instead of glutes or relaxing the abs during the movement.'),
('glute-bridge', 'pt', 'Ponte de glúteos', 'Exercício de cadeia posterior que requer estabilização abdominal ativa para fortalecer glúteos e isquiotibiais.', 'Melhora a força do quadril e estabiliza o núcleo abdominal.', 'Deitado de costas com os joelhos flexionados, eleve a pelve em direção ao teto contraindo glúteos e abdômen.', 'Empurre com os calcanhares e mantenha o core firme para evitar arquear a lombar.', 'Evitar se houver dor lombar ou cervical.', 'Subir com as costas em vez dos glúteos ou relaxar o abdômen durante o movimento.'),
('glute-bridge', 'fr', 'Pont fessier', 'Exercice de la chaîne postérieure nécessitant une stabilisation abdominale active pour renforcer les fessiers et les ischio-jambiers.', 'Améliore la force des hanches et stabilise le noyau abdominal.', 'Allongé sur le dos, genoux pliés, levez le bassin vers le plafond en contractant fessiers et abdominaux.', 'Poussez sur vos talons et gardez le core ferme pour éviter de cambrer le bas du dos.', 'À éviter en cas de douleur aiguë au bas du dos ou au cou.', 'Soulever avec le dos plutôt qu''avec les fessiers ou relâcher les abdominaux durant le mouvement.'),
('glute-bridge', 'de', 'Glute Bridge', 'Übung der hinteren Kette, die aktive Bauchstabilisierung erfordert, um Gesäß und Beinrückseite zu stärken.', 'Verbessert die Hüftkraft und stabilisiert den Rumpf.', 'In Rückenlage mit angewinkelten Knien das Becken zur Decke heben und dabei Gesäß und Bauch anspannen.', 'Über die Fersen drücken und den Rumpf fest halten, um ein Durchhängen des Rückens zu vermeiden.', 'Bei akuten Rücken- oder Nackenschmerzen vermeiden.', 'Mit dem Rücken statt mit dem Gesäß heben oder den Bauch während der Bewegung entspannen.'),
('glute-bridge', 'it', 'Ponte per glutei', 'Esercizio della catena posteriore che richiede una stabilizzazione addominale attiva per rinforzare glutei e ischiocrurali.', 'Migliora la forza dell''anca e stabilizza il core addominale.', 'Sdraiato sulla schiena con le ginocchia flesse, solleva il bacino verso il soffitto contraendo glutei e addome.', 'Spingi con i talloni e mantieni il core saldo per evitare di inarcare la zona lombare.', 'Evitare in caso di dolore acuto lombare o cervicale.', 'Sollevare con la schiena invece che con i glutei o rilassare l''addome durante il movimento.'),
('glute-bridge', 'zh', '臀桥', '需要主动腹部稳定的后链练习，以加强臀部和腘绳肌。', '提升髋部力量并稳定腹部核心。', '仰卧，膝盖弯曲，抬起骨盆，同时收紧臀部和腹部。', '用脚后跟发力并保持核心稳固，避免腰部反弓。', '如有急性腰痛或颈痛，请避免使用。', '用背部发力而非臀部，或在动作过程中放松腹部。'),
('glute-bridge', 'ja', 'グルートブリッジ', '臀部とハムストリングを強化するために、アクティブな腹部安定化を必要とする後鎖運動。', '股関節の強度を高め、腹部コアを安定させます。', '仰向けになり膝を立て、臀部と腹部を収縮させながら骨盤を持ち上げます。', 'かかとで押し出し、腰が反らないようにコアをしっかりと保ちます。', '腰や首に激しい痛みがある場合は避けてください。', '臀部ではなく背中で持ち上げることや、動作中に腹部を緩めること。'),
('glute-bridge', 'ko', '글루트 브리지', '둔근과 햄스트링을 강화하기 위해 능동적인 복부 안정화가 필요한 후면 사슬 운동.', '고관절 근력 향상 및 복부 코어 안정화.', '누운 상태에서 무릎을 굽히고 둔근과 복근을 수축하며 골반을 들어 올림.', '뒤꿈치로 밀어내며 허리가 꺾이지 않도록 코어를 단단히 유지할 것.', '요통이나 경추 통증이 있다면 피할 것.', '둔근 대신 허리로 올리거나 동작 중 복근을 이완하는 것.'),
('glute-bridge', 'ar', 'تمرين جسر الأرداف', 'تمرين للسلسلة الخلفية يتطلب تثبيتاً نشطاً للبطن لتقوية الأرداف وأوتار الركبة.', 'يعزز قوة الورك ويثبت عضلات البطن الأساسية.', 'استلقِ على ظهرك مع ثني ركبتيك، وارفع حوضك نحو السقف مع قبض عضلات الأرداف والبطن.', 'ادفع بواسطة كعبيك وحافظ على ثبات الجذع لتجنب تقوس أسفل الظهر.', 'تجنب التمرين في حالة وجود آلام حادة في أسفل الظهر أو الرقبة.', 'الرفع باستخدام الظهر بدلاً من الأرداف أو إرخاء عضلات البطن أثناء التمرين.'),
('glute-bridge', 'hi', 'ग्लूट ब्रिज', 'पश्च श्रृंखला व्यायाम जिसे ग्लूट्स और हैमस्ट्रिंग को मजबूत करने के लिए सक्रिय पेट स्थिरीकरण की आवश्यकता होती है।', 'कूल्हे की ताकत बढ़ाता है और पेट के कोर को स्थिर करता है।', 'पीठ के बल लेटें, घुटने मोड़ें, कूल्हों को छत की ओर उठाएं और ग्लूट्स और पेट को सिकोड़ें।', 'एड़ियों से धक्का दें और पीठ के निचले हिस्से को मुड़ने से रोकने के लिए कोर को सख्त रखें।', 'यदि पीठ के निचले हिस्से या गर्दन में तीव्र दर्द हो तो न करें।', 'ग्लूट्स के बजाय पीठ का उपयोग करना या आंदोलन के दौरान पेट को आराम देना।'),
('glute-bridge', 'ru', 'Ягодичный мостик', 'Упражнение на заднюю цепь, требующее активной стабилизации живота для укрепления ягодиц и бицепсов бедра.', 'Улучшает силу бедер и стабилизирует кор.', 'Лежа на спине, согните ноги в коленях, поднимите таз к потолку, сжимая ягодицы и напрягая пресс.', 'Толкайтесь пятками и держите кор в напряжении, чтобы избежать прогиба в пояснице.', 'Избегайте при острой боли в пояснице или шее.', 'Подъем за счет спины, а не ягодиц, или расслабление живота во время движения.'),
('glute-bridge', 'nl', 'Glute bridge', 'Oefening voor achterste keten die actieve buikstabilisatie vereist om billen en hamstrings te versterken.', 'Verbetert heupkracht en stabiliseert de buikkern.', 'Lig op de rug met gebogen knieën, til bekken naar het plafond en span billen en buik aan.', 'Duw vanuit hielen en houd core vast om holle onderrug te vermijden.', 'Vermijden bij acute onderrug- of nekpijn.', 'Tillen met de rug in plaats van billen of buikspieren ontspannen tijdens beweging.'),
('glute-bridge', 'sv', 'Glute bridge', 'Övning för bakre kedjan som kräver aktiv magstabilisering för att stärka säte och baksida lår.', 'Förbättrar höftstyrka och stabiliserar magkärnan.', 'Ligg på rygg med böjda knän, lyft bäckenet mot taket och knip med sätet och magen.', 'Tryck ifrån med hälarna och håll bålen stadig för att undvika att svanka.', 'Undvik vid akut ländryggs- eller nacksmärta.', 'Lyfta med ryggen istället för sätet eller slappna av i magen under rörelsen.'),
('glute-bridge', 'pl', 'Mostki biodrowe', 'Ćwiczenie na tylną taśmę wymagające aktywnej stabilizacji brzucha, aby wzmocnić pośladki i grupę kulszowo-goleniową.', 'Poprawia siłę bioder i stabilizuje mięśnie brzucha.', 'W leżeniu na plecach, ugnij kolana i unieś miednicę do sufitu, napinając pośladki i brzuch.', 'Pchaj piętami i trzymaj core w napięciu, aby uniknąć wyginania kręgosłupa.', 'Unikaj w przypadku ostrego bólu kręgosłupa lub karku.', 'Unoszenie plecami zamiast pośladkami lub rozluźnianie brzucha podczas ruchu.'),
('glute-bridge', 'id', 'Glute bridge', 'Latihan rantai posterior yang membutuhkan stabilisasi perut aktif untuk memperkuat glute dan hamstring.', 'Meningkatkan kekuatan pinggul dan menstabilkan inti perut.', 'Berbaring telentang dengan lutut ditekuk, angkat panggul ke langit-langit sambil mengencangkan glute dan perut.', 'Dorong dengan tumit dan pertahankan core tetap kencang untuk menghindari punggung bawah melengkung.', 'Hindari jika ada nyeri punggung bawah atau leher akut.', 'Mengangkat dengan punggung bukannya glute atau mengendurkan perut selama gerakan.'),
('glute-bridge', 'bn', 'গ্লুট ব্রিজ', 'গ্লুটস এবং হ্যামস্ট্রিং শক্তিশালী করার জন্য সক্রিয় পেট স্থিতিশীলতার প্রয়োজন এমন একটি পোস্টেরিয়র চেইন ব্যায়াম।', 'হিপের শক্তি বাড়ায় এবং পেটের কোরকে স্থিতিশীল করে।', 'পিঠের ওপর শুয়ে হাঁটু ভাঁজ করুন, পেলভিস উপরের দিকে তুলুন এবং গ্লুটস ও পেটের পেশী শক্ত করুন।', 'গোড়ালির ওপর ভর দিয়ে চাপ দিন এবং পিঠের নিচের অংশ বাঁকানো এড়াতে কোর শক্ত রাখুন।', 'পিঠের নিচের অংশে বা ঘাড়ে তীব্র ব্যথা থাকলে এটি এড়িয়ে চলুন।', 'পিঠের সাহায্যে তোলা বা ব্যায়ামের সময় পেটের পেশী শিথিল করা।'),
('glute-bridge', 'vi', 'Glute bridge', 'Bài tập chuỗi cơ sau yêu cầu ổn định bụng chủ động để tăng cường cơ mông và đùi sau.', 'Cải thiện sức mạnh hông và ổn định phần cơ bụng cốt lõi.', 'Nằm ngửa, gập gối, nâng khung chậu lên trần nhà đồng thời gồng mông và bụng.', 'Đẩy bằng gót chân và giữ cơ core chắc để tránh võng lưng dưới.', 'Tránh tập nếu bị đau lưng dưới hoặc đau cổ cấp tính.', 'Dùng lưng để nâng thay vì mông hoặc thả lỏng bụng trong khi tập.'),
('glute-bridge', 'fa', 'پل باسن', 'تمرین زنجیره خلفی که نیاز به ثبات فعال شکم برای تقویت باسن و همسترینگ دارد.', 'قدرت لگن را بهبود می‌بخشد و مرکز شکم را تثبیت می‌کند.', 'به پشت دراز بکشید، زانوها را خم کنید، لگن را بالا ببرید و همزمان باسن و شکم را منقبض کنید.', 'با پاشنه‌ها فشار دهید و برای جلوگیری از قوس کمر، هسته بدن را محکم نگه دارید.', 'در صورت درد حاد کمر یا گردن از انجام آن خودداری کنید.', 'بالا بردن با کمر به جای باسن یا شل کردن شکم در طول حرکت.');