-- Definición del ejercicio y sus recursos
INSERT OR IGNORE INTO exercises (slug, img, video, difficulty) 
VALUES ('high-cable-kneeling-crunch', 'high-cable-kneeling-crunch.jpg', 'high-cable-kneeling-crunch.mp4', 'intermediate');

-- Relación: el ejercicio trabaja el grupo muscular 'abdominals'
INSERT OR IGNORE INTO exercise_body_target (exercise_slug, body_target_slug) 
VALUES ('high-cable-kneeling-crunch', 'abdominals');

-- Relación: el ejercicio utiliza el equipo 'cable-machine'
INSERT OR IGNORE INTO exercise_machine (exercise_slug, machine_slug) 
VALUES ('high-cable-kneeling-crunch', 'cable_machine');

-- Relación: con otros ejercicios en este caso 'crunch'
INSERT OR IGNORE INTO exercise_alternative (exercise_slug, alternative_slug) 
VALUES ('high-cable-kneeling-crunch', 'crunch');


-- Información multiidioma
INSERT OR IGNORE INTO exercises_info (slug, lang, title, description, benefits, instructions, tips, restrictions, mistakes) VALUES 
('high-cable-kneeling-crunch', 'es', 'Crunch en polea alta de rodillas', 'Variante avanzada que utiliza resistencia externa para maximizar la hipertrofia del recto abdominal mediante carga progresiva.', 'Permite aplicar sobrecarga progresiva al core.\nMejora la densidad muscular abdominal.\nFomenta un control motor superior bajo tensión.', 'Arrodíllate frente a la polea alta y sujeta el agarre de cuerda cerca de la cabeza.\nFlexiona la columna torácica acercando los codos a las rodillas.\nRegresa lentamente a la posición inicial controlando el peso.', 'Mantén la pelvis estable para evitar usar el impulso de la cadera.\nNo permitas que los brazos realicen el esfuerzo; el movimiento nace del abdomen.', 'Evitar con lesiones lumbares crónicas.\nNo realizar si existe falta de control cervical.', 'Usar los brazos como palanca principal.\nRealizar el movimiento con los flexores de la cadera en lugar de la columna.'),
('high-cable-kneeling-crunch', 'en', 'High cable kneeling crunch', 'Advanced variation utilizing external resistance to maximize rectus abdominis hypertrophy through progressive overload.', 'Enables progressive overload for the core.\nImproves abdominal muscle density.\nFosters superior motor control under tension.', 'Kneel in front of a high pulley and hold the rope attachment near your head.\nFlex your thoracic spine, bringing elbows toward knees.\nReturn slowly to the start, controlling the weight.', 'Keep pelvis stable to avoid hip momentum.\nEnsure movement originates from abdominal contraction, not arm pull.', 'Avoid with chronic lower back injuries.\nDo not perform if cervical control is lacking.', 'Using arms as the primary lever.\nPerforming the movement with hip flexors instead of thoracic spine.'),
('high-cable-kneeling-crunch', 'pt', 'Crunch ajoelhado no cabo alto', 'Variação avançada que utiliza resistência externa para maximizar a hipertrofia do reto abdominal através da sobrecarga progressiva.', 'Permite aplicar sobrecarga progressiva ao core.\nMelhora a densidade muscular abdominal.\nPromove um controle motor superior sob tensão.', 'Ajoelhe-se em frente à polia alta e segure a corda perto da cabeça.\nFlexione a coluna torácica aproximando os cotovelos dos joelhos.\nRetorne lentamente controlando o peso.', 'Mantenha a pelve estável para evitar usar o impulso do quadril.\nCertifique-se de que o movimento venha da contração abdominal.', 'Evitar com lesões lombares crônicas.\nNão realizar se faltar controle cervical.', 'Usar os braços como alavanca principal.\nRealizar o movimento com os flexores do quadril em vez da coluna.'),
('high-cable-kneeling-crunch', 'fr', 'Crunch à genoux à la poulie haute', 'Variante avancée utilisant une résistance externe pour maximiser l''hypertrophie du grand droit via une surcharge progressive.', 'Permet une surcharge progressive du tronc.\nAméliore la densité musculaire abdominale.\nFavorise un meilleur contrôle moteur sous tension.', 'Agenouillez-vous face à la poulie haute et saisissez la corde près de la tête.\nFléchissez la colonne thoracique en amenant les coudes vers les genoux.\nRevenez lentement à la position de départ.', 'Gardez le bassin stable pour éviter l''élan des hanches.\nLe mouvement doit provenir de la contraction abdominale, pas des bras.', 'À éviter en cas de lésions lombaires chroniques.\nNe pas effectuer sans un contrôle cervical adéquat.', 'Utiliser les bras comme levier principal.\nUtiliser les fléchisseurs de la hanche au lieu de la colonne.'),
('high-cable-kneeling-crunch', 'de', 'High Cable Kneeling Crunch', 'Fortgeschrittene Variante, die externen Widerstand nutzt, um die Hypertrophie des Rectus abdominis durch progressive Überlastung zu maximieren.', 'Ermöglicht progressive Überlastung des Rumpfes.\nVerbessert die Bauchmuskeldichte.\nFördert überlegene motorische Kontrolle unter Spannung.', 'Knien Sie vor den hohen Kabelzug und halten Sie das Seil nahe am Kopf.\nBeugen Sie die Brustwirbelsäule und bringen Sie die Ellbogen zu den Knien.\nKehren Sie langsam in die Ausgangsposition zurück.', 'Halten Sie das Becken stabil, um Schwung aus der Hüfte zu vermeiden.\nStellen Sie sicher, dass die Bewegung aus der Bauchkontraktion kommt.', 'Bei chronischen Lendenwirbelsäulenverletzungen vermeiden.\nNicht bei mangelnder Kontrolle der Halswirbelsäule ausführen.', 'Verwendung der Arme als primärer Hebel.\nAusführung über Hüftbeuger statt über die Wirbelsäule.'),
('high-cable-kneeling-crunch', 'it', 'Crunch al cavo alto in ginocchio', 'Variante avanzata che utilizza la resistenza esterna per massimizzare l''ipertrofia del retto addominale tramite sovraccarico progressivo.', 'Permette il sovraccarico progressivo del core.\nMigliora la densità muscolare addominale.\nPromuove un controllo motorio superiore sotto tensione.', 'Inginocchiati davanti alla carrucola alta e tieni la corda vicino alla testa.\nFletti la colonna toracica portando i gomiti verso le ginocchia.\nTorna lentamente alla posizione iniziale controllando il peso.', 'Mantieni il bacino stabile per evitare l''impulso delle anche.\nAssicurati che il movimento parta dalla contrazione addominale.', 'Evitare in caso di lesioni lombari croniche.\nNon eseguire se manca il controllo cervicale.', 'Usare le braccia come leva principale.\nEseguire il movimento con i flessori dell''anca anziché con la colonna.'),
('high-cable-kneeling-crunch', 'zh', '高位绳索跪姿卷腹', '利用外部阻力通过渐进负荷最大化腹直肌肥大的进阶变式。', '实现核心的渐进负荷。\n改善腹部肌肉密度。\n在张力下促进卓越的运动控制。', '跪在高位滑轮前，将绳索握柄置于头部附近。\n屈曲胸椎，使肘部靠近膝盖。\n缓慢回到起始位置并控制重量。', '保持骨盆稳定以避免髋部借力。\n确保动作源自腹部收缩而非手臂拉动。', '慢性腰部损伤者禁用。\n颈椎控制能力不足者禁用。', '将手臂作为主要杠杆。\n用髋屈肌而非脊柱完成动作。'),
('high-cable-kneeling-crunch', 'ja', '高位ケーブル・ニーリング・クランチ', '漸進的過負荷を通じて腹直筋の筋肥大を最大化するために外部抵抗を利用する高度なバリエーション。', '体幹の漸進的過負荷を可能にする。\n腹筋の密度を向上させる。\n緊張下での優れた運動制御を促進する。', '高位滑車の前にひざまずき、ロープアタッチメントを頭の近くで保持します。\n胸椎を屈曲させ、肘を膝に近づけます。\n重量をコントロールしながらゆっくりと開始位置に戻ります。', '骨盤を安定させ、股関節の反動を防ぎます。\n動きが腕ではなく腹部の収縮から始まるようにします。', '慢性の腰部損傷がある場合は避けてください。\n頸部のコントロールが不十分な場合は行わないでください。', '腕を主要なレバーとして使用する。\n脊椎ではなく股関節屈筋で動かしている。'),
('high-cable-kneeling-crunch', 'ko', '하이 케이블 니링 크런치', '점진적 과부하를 통해 복직근 비대를 극대화하는 외부 저항 활용 고급 변형 운동.', '코어의 점진적 과부하 가능.\n복부 근육 밀도 개선.\n긴장 상태에서의 뛰어난 운동 제어력 증진.', '하이 풀리 앞에 무릎을 꿇고 로프를 머리 근처에 잡습니다.\n흉추를 굴곡시켜 팔꿈치를 무릎 쪽으로 당깁니다.\n무게를 제어하며 천천히 시작 위치로 돌아옵니다.', '골반을 고정하여 엉덩이 반동을 방지합니다.\n팔이 아닌 복부 수축에서 동작이 시작되도록 합니다.', '만성 요통 환자는 피하세요.\n경추 제어력이 부족하면 수행하지 마세요.', '팔을 주 레버로 사용하는 것.\n척추가 아닌 장요근으로 동작을 수행하는 것.'),
('high-cable-kneeling-crunch', 'ar', 'تمرين الكرنش بالكيبل عالي الركبة', 'تباين متقدم يستخدم المقاومة الخارجية لتعظيم تضخم عضلة البطن المستقيمة من خلال التحميل الزائد التدريجي.', 'تمكين التحميل الزائد التدريجي للبطن.\nتحسين كثافة عضلات البطن.\nتعزيز التحكم الحركي الفائق تحت الضغط.', 'اركد أمام البكرة العالية وأمسك حبل الكيبل بالقرب من رأسك.\nاثنِ العمود الفقري الصدري بتقريب المرفقين نحو الركبتين.\nعد ببطء إلى البداية مع التحكم في الوزن.', 'حافظ على استقرار الحوض لتجنب زخم الورك.\nتأكد أن الحركة تنبع من انقباض البطن وليس سحب الذراعين.', 'تجنب في حالات إصابات أسفل الظهر المزمنة.\nلا تقم بالتمرين إذا كان التحكم في الرقبة مفقوداً.', 'استخدام الذراعين كرافعة أساسية.\nأداء الحركة باستخدام مثنيات الورك بدلاً من العمود الفقري.'),
('high-cable-kneeling-crunch', 'hi', 'हाई केबल नीलिंग क्रंच', 'प्रगतिशील अधिभार के माध्यम से रेक्टस एब्डोमिनिस हाइपरट्रॉफी को अधिकतम करने के लिए बाहरी प्रतिरोध का उपयोग करने वाला एक उन्नत संस्करण।', 'कोर के लिए प्रगतिशील अधिभार सक्षम बनाता है।\nपेट की मांसपेशियों का घनत्व सुधारता है।\nतनाव के तहत बेहतर मोटर नियंत्रण को बढ़ावा देता है।', 'हाई पुली के सामने घुटने टेकें और रस्सी को अपने सिर के पास पकड़ें।\nथोरैसिक रीढ़ को मोड़ें, कोहनियों को घुटनों की ओर लाएं।\nवजन को नियंत्रित करते हुए धीरे-धीरे शुरुआती स्थिति में लौटें।', 'कूल्हे की गति से बचने के लिए श्रोणि को स्थिर रखें।\nसुनिश्चित करें कि आंदोलन पेट के संकुचन से उत्पन्न हो, न कि हाथ के खिंचाव से।', 'पुरानी पीठ की चोटों के साथ न करें।\nयदि सर्वाइकल नियंत्रण की कमी है तो न करें।', 'हाथों को प्राथमिक लीवर के रूप में उपयोग करना।\nरीढ़ के बजाय हिप फ्लेक्सर्स के साथ आंदोलन करना。'),
('high-cable-kneeling-crunch', 'ru', 'Скручивания на верхнем блоке стоя на коленях', 'Продвинутая вариация, использующая внешнее сопротивление для максимизации гипертрофии прямой мышцы живота посредством прогрессивной перегрузки.', 'Позволяет прогрессивно увеличивать нагрузку на кор.\nУлучшает плотность мышц пресса.\nСпособствует лучшему моторному контролю под напряжением.', 'Встаньте на колени перед верхним блоком, удерживая канат у головы.\nСогните грудной отдел позвоночника, приближая локти к коленям.\nМедленно вернитесь в исходное положение, контролируя вес.', 'Держите таз стабильным, чтобы избежать инерции бедер.\nУбедитесь, что движение идет от сокращения пресса, а не от тяги руками.', 'Избегайте при хронических травмах поясницы.\nНе выполняйте, если нет контроля над шейным отделом.', 'Использование рук в качестве основного рычага.\nВыполнение движения за счет сгибателей бедра вместо позвоночника.'),
('high-cable-kneeling-crunch', 'nl', 'High cable kneeling crunch', 'Geavanceerde variant die externe weerstand gebruikt om de hypertrofie van de rechte buikspier te maximaliseren via progressieve overbelasting.', 'Maakt progressieve overbelasting van de core mogelijk.\nVerbetert de buikspierdichtheid.\nBevordert superieure motorische controle onder spanning.', 'Kiel voor de hoge katrol en houd het touw dicht bij je hoofd.\nBuig de thoracale wervelkolom en breng ellebogen naar knieën.\nKeer langzaam terug naar de start en controleer het gewicht.', 'Houd bekken stabiel om heupimpuls te voorkomen.\nZorg dat de beweging uit buikcontractie komt, niet uit armtrekken.', 'Vermijden bij chronische onderrugblessures.\nNiet uitvoeren bij gebrek aan cervicale controle.', 'Armen als primaire hefboom gebruiken.\nBeweging uitvoeren met heupbuigers in plaats van wervelkolom.'),
('high-cable-kneeling-crunch', 'sv', 'High cable kneeling crunch', 'Avancerad variant som använder externt motstånd för att maximera hypertrofi av raka bukmusklerna genom progressiv överbelastning.', 'Möjliggör progressiv överbelastning för core.\nFörbättrar bukmusklernas densitet.\nFrämjar överlägsen motorkontroll under spänning.', 'Knäböj framför hög trissa och håll repet nära huvudet.\nFlexa bröstryggen, för armbågarna mot knäna.\nÅtergå långsamt till start och kontrollera vikten.', 'Håll bäckenet stabilt för att undvika höftimpuls.\nSäkerställ att rörelsen kommer från magkontraktion, inte armdrag.', 'Undvik vid kroniska ländryggsskador.\nUtför ej om cervikal kontroll saknas.', 'Använda armarna som primär hävstång.\nUtföra rörelsen med höftböjare istället för ryggraden.'),
('high-cable-kneeling-crunch', 'pl', 'Crunch na klęczkach przy wyciągu górnym', 'Zaawansowany wariant wykorzystujący opór zewnętrzny do maksymalizacji hipertrofii mięśnia prostego brzucha poprzez progresywne przeciążenie.', 'Umożliwia progresywne przeciążenie core.\nPoprawia gęstość mięśni brzucha.\nSprzyja lepszej kontroli motorycznej pod napięciem.', 'Uklęknij przed wyciągiem górnym i trzymaj linę blisko głowy.\nZegnij kręgosłup piersiowy, kierując łokcie do kolan.\nPowoli wróć do pozycji startowej, kontrolując ciężar.', 'Utrzymuj stabilną miednicę, aby uniknąć używania bioder.\nUpewnij się, że ruch wynika ze skurczu brzucha, a nie ciągnięcia ramionami.', 'Unikać przy przewlekłych urazach kręgosłupa lędźwiowego.\nNie wykonywać przy braku kontroli odcinka szyjnego.', 'Używanie ramion jako głównej dźwigni.\nWykonywanie ruchu za pomocą zginaczy bioder zamiast kręgosłupa.'),
('high-cable-kneeling-crunch', 'id', 'Crunch berlutut kabel tinggi', 'Variasi lanjutan yang menggunakan resistensi eksternal untuk memaksimalkan hipertrofi rektus abdominis melalui overload progresif.', 'Memungkinkan overload progresif untuk core.\nMeningkatkan kepadatan otot perut.\nMendorong kontrol motorik superior di bawah tegangan.', 'Berlutut di depan katrol tinggi dan pegang tali di dekat kepala Anda.\nTekuk tulang belakang toraks, bawa siku ke arah lutut.\nKembali perlahan ke posisi awal sambil mengontrol berat.', 'Jaga panggul stabil untuk menghindari dorongan pinggul.\nPastikan gerakan berasal dari kontraksi perut, bukan tarikan tangan.', 'Hindari dengan cedera punggung bawah kronis.\nJangan lakukan jika kontrol leher kurang.', 'Menggunakan tangan sebagai pengungkit utama.\nMelakukan gerakan dengan fleksor pinggul alih-alih tulang belakang.'),
('high-cable-kneeling-crunch', 'bn', 'হাই ক্যাবল নিলিং ক্রাঞ্চ', 'প্রগতিশীল ওভারলোডের মাধ্যমে রেকটাস অ্যাবডোমিনিস হাইপারট্রফি বাড়ানোর জন্য বাহ্যিক প্রতিরোধের ব্যবহারকারী একটি উন্নত সংস্করণ।', 'কোরের প্রগতিশীল ওভারলোড সক্ষম করে।\nপেটের পেশীর ঘনত্ব উন্নত করে।\nটেনশনের অধীনে উচ্চতর মোটর নিয়ন্ত্রণ প্রচার করে।', 'হাই পুলির সামনে হাঁটু গেড়ে বসুন এবং দড়িটি মাথার কাছে ধরুন।\nথোরাসিক মেরুদণ্ড বাঁকান, কনুইগুলো হাঁটুর দিকে আনুন।\nওজন নিয়ন্ত্রণ করে ধীরে ধীরে শুরুতে ফিরে আসুন।', 'হিপ ইমপালস এড়াতে শ্রোণী স্থির রাখুন।\nনিশ্চিত করুন যে আন্দোলন পেটের সংকোচন থেকে আসছে, হাতের টান থেকে নয়।', 'দীর্ঘস্থায়ী পিঠের ইনজুরিতে এড়িয়ে চলুন।\nসার্ভিকাল নিয়ন্ত্রণ না থাকলে করবেন না।', 'হাতকে প্রাথমিক লিভার হিসেবে ব্যবহার করা।\nমেরুদণ্ডের পরিবর্তে হিপ ফ্লেক্সর দিয়ে আন্দোলন করা。'),
('high-cable-kneeling-crunch', 'vi', 'Crunch quy gối với cáp cao', 'Bien the nang cao su dung suc can ngoai de toi da hoa su phi dai co bung thang thong qua qua tai luy tien.', 'Cho phep qua tai luy tien cho core.\nCai thien mat do co bung.\nThuc day kiem soat van dong tot hon duoi cang thang.', 'Quy truoc ro-ly cao va giu day gan dau.\nUon cong cot song nguc, dua khuyu tay ve phia dau goi.\nTro lai tu tu vi tri ban dau trong khi kiem soat trong luong.', 'Giữ khung chau on dinh de tranh xung luc hong.\nDam bao chuyen dong bat nguon tu su co that bung, khong phai do keo tay.', 'Tranh neu bi chan thuong lung duoi man tinh.\nKhong thuc hien neu thieu kiem soat co.', 'Su dung tay lam don bay chinh.\nThuc hien chuyen dong voi co gap hong thay vi cot song.'),
('high-cable-kneeling-crunch', 'fa', 'کرانچ زانو زده با کابل بالا', 'یک تباین پیشرفته با استفاده از مقاومت خارجی برای به حداکثر رساندن هیپرتروفی عضله راست شکم از طریق اضافه بار تدریجی.', 'امکان اضافه بار تدریجی برای هسته بدن.\nبهبود تراکم عضلات شکم.\nتقویت کنترل حرکتی برتر تحت فشار.', 'در مقابل قرقره بالا زانو بزنید و طناب را نزدیک سر خود نگه دارید.\nستون فقرات سینه‌ای را خم کنید و آرنج‌ها را به سمت زانوها بیاورید.\nبه آرامی به حالت شروع بازگردید و وزن را کنترل کنید.', 'لگن را ثابت نگه دارید تا از ضربه لگن جلوگیری شود.\nاطمینان حاصل کنید که حرکت از انقباض شکم ناشی می‌شود نه کشش دست‌ها.', 'در صورت آسیب مزمن کمر خودداری کنید.\nاگر کنترل گردن ندارید، انجام ندهید.', 'استفاده از دست‌ها به عنوان اهرم اصلی.\nانجام حرکت با فلکسورهای لگن به جای ستون فقرات.');