-- Definición del ejercicio principal
INSERT OR IGNORE INTO exercises (slug, img, video, difficulty) 
VALUES 
('hollow-body-hold', 'hollow-body-hold.jpg', 'hollow-body-hold.mp4', 'intermediate'),
('deadbug', 'deadbug.jpg', 'deadbug.mp4', 'beginner'),
('forearm-plank', 'forearm-plank.jpg', 'forearm-plank.mp4', 'beginner');

-- Relaciones de grupos musculares
INSERT INTO exercise_body_target (exercise_slug, body_target_slug) 
VALUES 
('hollow-body-hold', 'abdominals');

-- Relaciones de alternativas
INSERT INTO exercise_alternative (exercise_slug, alternative_slug) 
VALUES 
('hollow-body-hold', 'dead-bug'),
('hollow-body-hold', 'forearm-plank');

-- Información multiidioma
INSERT OR IGNORE INTO exercises_info (slug, lang, title, description, benefits, instructions, tips, restrictions, mistakes) VALUES 
('hollow-body-hold', 'es', 'Sostén de cuerpo hueco', 'Ejercicio isométrico fundamental para la estabilidad del core y la alineación lumbar.', 'Fortalece el recto abdominal y mejora la conexión del core.', 'Tumbado, eleva piernas y hombros del suelo manteniendo la espalda baja pegada al suelo.', 'Imagina que tu cuerpo es una banana; mantén la zona lumbar presionada contra el piso.', 'Evitar si hay dolor lumbar agudo o debilidad excesiva en el core.', 'Permitir que la espalda baja se separe del suelo o no elevar los hombros lo suficiente.'),
('hollow-body-hold', 'en', 'Hollow body hold', 'Fundamental isometric exercise for core stability and lumbar alignment.', 'Strengthens rectus abdominis and improves core connection.', 'Lying down, lift legs and shoulders off the ground while keeping the lower back pressed into the floor.', 'Imagine your body as a banana; keep your lumbar spine pressed against the floor.', 'Avoid if acute lower back pain or excessive core weakness exists.', 'Allowing the lower back to arch off the floor or failing to lift shoulders high enough.'),
('hollow-body-hold', 'pt', 'Sustentação de corpo oco (Hollow body)', 'Exercício isométrico fundamental para estabilidade do core e alinhamento lombar.', 'Fortalece o reto abdominal e melhora a conexão do core.', 'Deitado, eleve pernas e ombros do chão mantendo a lombar pressionada contra o solo.', 'Imagine que seu corpo é uma banana; mantenha a região lombar pressionada contra o chão.', 'Evitar se houver dor lombar aguda ou fraqueza excessiva no core.', 'Permitir que a lombar se separe do chão ou não elevar os ombros suficientemente.'),
('hollow-body-hold', 'fr', 'Hollow body hold (Gainage banane)', 'Exercice isométrique fondamental pour la stabilité du core et l''alignement lombaire.', 'Renforce le grand droit et améliore la connexion du core.', 'Allongé, levez les jambes et les épaules du sol tout en gardant le bas du dos plaqué contre le sol.', 'Imaginez que votre corps est une banane ; gardez la zone lombaire pressée contre le sol.', 'À éviter en cas de douleur aiguë au bas du dos ou de faiblesse excessive du core.', 'Laisser le bas du dos se décoller du sol ou ne pas assez soulever les épaules.'),
('hollow-body-hold', 'de', 'Hollow Body Hold', 'Grundlegende isometrische Übung für Rumpfstabilität und Lendenwirbelsäulenausrichtung.', 'Stärkt den geraden Bauchmuskel und verbessert die Rumpfverbindung.', 'In Rückenlage Beine und Schultern anheben, während der untere Rücken fest auf den Boden gedrückt bleibt.', 'Stell dir vor, dein Körper ist eine Banane; halte die Lendenwirbelsäule auf den Boden gedrückt.', 'Bei akuten Rückenschmerzen oder übermäßiger Rumpfschwäche vermeiden.', 'Den unteren Rücken den Boden verlassen lassen oder die Schultern nicht hoch genug anheben.'),
('hollow-body-hold', 'it', 'Hollow body hold', 'Esercizio isometrico fondamentale per la stabilità del core e l''allineamento lombare.', 'Rinforza il retto addominale e migliora la connessione del core.', 'Sdraiato, solleva gambe e spalle dal suolo mantenendo la parte bassa della schiena premuta contro il pavimento.', 'Immagina che il tuo corpo sia una banana; mantieni la zona lombare premuta contro il suolo.', 'Evitare in caso di dolore lombare acuto o eccessiva debolezza del core.', 'Lasciare che la parte bassa della schiena si stacchi dal suolo o non sollevare abbastanza le spalle.'),
('hollow-body-hold', 'zh', '空心支撑', '用于核心稳定性和腰椎对齐的基础等长练习。', '增强腹直肌并改善核心连接。', '仰卧，抬起双腿和肩膀，同时保持下背部紧贴地面。', '想象你的身体是一根香蕉；保持腰椎紧贴地面。', '如有急性腰痛或核心力量过度薄弱，请避免使用。', '允许下背部离开地面或肩膀抬起高度不足。'),
('hollow-body-hold', 'ja', 'ホロウボディホールド', '体幹の安定性と腰椎のアライメントのための基本的な等尺性運動。', '腹直筋を強化し、コアの連動性を向上させます。', '仰向けから脚と肩を床から浮かせ、腰を床に押し付けた状態を保ちます。', '体をバナナのようにイメージし、腰椎を床に押し付けてください。', '腰の激しい痛みやコアの筋力が極端に弱い場合は避けてください。', '腰が床から浮くことや、肩の持ち上げ不足。'),
('hollow-body-hold', 'ko', '홀로우 바디 홀드', '코어 안정성 및 요추 정렬을 위한 기본적인 등척성 운동.', '복직근 강화 및 코어 연결성 향상.', '누운 상태에서 다리와 어깨를 바닥에서 띄우고 허리를 바닥에 밀착함.', '몸을 바나나처럼 상상하고 요추를 바닥에 붙일 것.', '요통이 있거나 코어 근력이 너무 약하면 피할 것.', '허리가 바닥에서 뜨거나 어깨를 충분히 높이 들지 않는 것.'),
('hollow-body-hold', 'ar', 'تمرين ثبات الجسم المجوف (Hollow body)', 'تمرين متساوي القياس أساسي لاستقرار الجذع ومحاذاة أسفل الظهر.', 'يقوي عضلة البطن المستقيمة ويحسن تواصل عضلات الجذع.', 'استلقِ، وارفع ساقيك وكتفيك عن الأرض مع الحفاظ على ضغط أسفل ظهرك على الأرض.', 'تخيل أن جسمك على شكل موزة؛ حافظ على ضغط فقراتك القطنية على الأرض.', 'تجنب التمرين في حالة وجود آلام حادة في أسفل الظهر أو ضعف شديد في عضلات الجذع.', 'السماح لأسفل الظهر بالابتعاد عن الأرض أو عدم رفع الكتفين بشكل كافٍ.'),
('hollow-body-hold', 'hi', 'होलो बॉडी होल्ड', 'कोर स्थिरता और काठ (lumbar) संरेखण के लिए बुनियादी आइसोमेट्रिक व्यायाम।', 'रेक्टस एबडोमिनिस को मजबूत करता है और कोर कनेक्शन में सुधार करता है।', 'पीठ के बल लेटें, पैरों और कंधों को जमीन से उठाएं और पीठ के निचले हिस्से को फर्श पर दबाए रखें।', 'कल्पना करें कि आपका शरीर एक केला है; काठ की रीढ़ को फर्श पर दबाए रखें।', 'यदि पीठ के निचले हिस्से में तीव्र दर्द या कोर बहुत कमजोर हो तो न करें।', 'पीठ के निचले हिस्से को जमीन से अलग होने देना या कंधों को पर्याप्त ऊपर न उठाना।'),
('hollow-body-hold', 'ru', 'Удержание «полой» позиции (Hollow body)', 'Базовое изометрическое упражнение для стабильности кора и выравнивания поясницы.', 'Укрепляет прямую мышцу живота и улучшает нейромышечную связь кора.', 'Лежа на спине, оторвите ноги и плечи от пола, плотно прижимая поясницу к полу.', 'Представьте, что ваше тело — это банан; держите поясницу прижатой к полу.', 'Избегайте при острой боли в пояснице или при очень слабом коре.', 'Позволять пояснице отрываться от пола или недостаточно высоко поднимать плечи.'),
('hollow-body-hold', 'nl', 'Hollow body hold', 'Fundamentele isometrische oefening voor core-stabiliteit en lumbale uitlijning.', 'Versterkt de rechte buikspier en verbetert core-verbinding.', 'Lig op de rug, til benen en schouders van de grond terwijl de onderrug tegen de vloer wordt gedrukt.', 'Stel je voor dat je lichaam een banaan is; houd de lendenwervelkolom tegen de vloer gedrukt.', 'Vermijden bij acute onderrugpijn of extreme core-zwakte.', 'De onderrug van de vloer laten komen of de schouders niet hoog genoeg optillen.'),
('hollow-body-hold', 'sv', 'Hollow body hold', 'Grundläggande isometrisk övning för bålstabilitet och lumbal inriktning.', 'Stärker den raka magmuskeln och förbättrar bålförbindelsen.', 'Ligg på rygg, lyft ben och axlar från golvet medan ländryggen hålls pressad mot golvet.', 'Föreställ dig att din kropp är en banan; håll ländryggen pressad mot golvet.', 'Undvik vid akut ländryggssmärta eller extrem bålsvaghet.', 'Att låta ländryggen släppa från golvet eller att inte lyfta axlarna tillräckligt högt.'),
('hollow-body-hold', 'pl', 'Hollow body hold', 'Podstawowe ćwiczenie izometryczne dla stabilności core i ustawienia odcinka lędźwiowego.', 'Wzmacnia mięsień prosty brzucha i poprawia połączenie mięśni core.', 'W leżeniu unieś nogi i barki z podłoża, dociskając odcinek lędźwiowy do podłogi.', 'Wyobraź sobie, że twoje ciało to banan; trzymaj odcinek lędźwiowy dociśnięty do podłogi.', 'Unikaj w przypadku ostrego bólu pleców lub bardzo słabych mięśni core.', 'Pozwalanie na oderwanie odcinka lędźwiowego lub niewystarczające uniesienie barków.'),
('hollow-body-hold', 'id', 'Hollow body hold', 'Latihan isometrik dasar untuk stabilitas core dan kesejajaran lumbal.', 'Memperkuat otot perut rectus dan meningkatkan koneksi core.', 'Berbaring, angkat kaki dan bahu dari lantai sambil menekan punggung bawah ke lantai.', 'Bayangkan tubuh Anda seperti pisang; tekan tulang belakang lumbal ke lantai.', 'Hindari jika ada nyeri punggung bawah akut atau kelemahan core ekstrem.', 'Membiarkan punggung bawah terangkat dari lantai atau tidak mengangkat bahu cukup tinggi.'),
('hollow-body-hold', 'bn', 'হলো বডি হোল্ড', 'কোর স্থিতিশীলতা এবং কটিদেশীয় প্রান্তিককরণের জন্য মৌলিক আইসোমেট্রিক ব্যায়াম।', 'রেকটাস অ্যাবডোমিনিসকে শক্তিশালী করে এবং কোর সংযোগ উন্নত করে।', 'পিঠের ওপর শুয়ে পা ও কাঁধ মাটি থেকে তুলুন এবং পিঠের নিচের অংশ মেঝের সঙ্গে চেপে রাখুন।', 'কল্পনা করুন আপনার শরীরটি একটি কলার মতো; কটিদেশীয় মেরুদণ্ড মেঝেতে চেপে রাখুন।', 'পিঠের নিচের অংশে তীব্র ব্যথা বা কোর খুব দুর্বল হলে এটি এড়িয়ে চলুন।', 'পিঠের নিচের অংশ মাটি থেকে উঠে যাওয়া বা কাঁধ যথেষ্ট উঁচু না করা।'),
('hollow-body-hold', 'vi', 'Hollow body hold', 'Bài tập đẳng trường cơ bản cho sự ổn định core và căn chỉnh thắt lưng.', 'Tăng cường cơ bụng thẳng và cải thiện sự kết nối core.', 'Nằm ngửa, nâng chân và vai khỏi sàn trong khi ép lưng dưới xuống sàn.', 'Hãy tưởng tượng cơ thể bạn giống như một quả chuối; giữ cột sống thắt lưng ép xuống sàn.', 'Tránh tập nếu bị đau lưng dưới cấp tính hoặc core quá yếu.', 'Để lưng dưới hở khỏi sàn hoặc không nâng vai đủ cao.'),
('hollow-body-hold', 'fa', 'هالو بادی هولد', 'تمرین ایزومتریک اساسی برای پایداری هسته بدن و هم‌ترازی کمر.', 'عضله راست شکمی را تقویت کرده و ارتباط هسته بدن را بهبود می‌بخشد.', 'به پشت دراز بکشید، پاها و شانه‌ها را از زمین بلند کنید و کمر را به زمین فشار دهید.', 'تصور کنید بدنتان به شکل موز است؛ ستون فقرات کمری را به زمین فشار دهید.', 'در صورت درد حاد کمر یا ضعف شدید هسته بدن از انجام آن خودداری کنید.', 'اجازه دادن به کمر برای جدا شدن از زمین یا بلند نکردن کافی شانه‌ها.');