-- Definición de ejercicios (Principal + Alternativas)
INSERT OR IGNORE INTO exercises (slug, img, video, difficulty) 
VALUES 
('leg-raises', 'leg-raises.jpg', 'leg-raises.mp4', 'beginner'),
('hanging-leg-raises', 'hanging-leg-raises.jpg', 'hanging-leg-raises.mp4', 'intermediate');

-- Relaciones de grupos musculares (Solo ejercicio actual)
INSERT INTO exercise_body_target (exercise_slug, body_target_slug) 
VALUES 
('leg-raises', 'abdominals');

-- Relaciones de alternativas
INSERT INTO exercise_alternative (exercise_slug, alternative_slug) 
VALUES 
('leg-raises', 'hanging-leg-raises');

-- Información multiidioma
INSERT OR IGNORE INTO exercises_info (slug, lang, title, description, benefits, instructions, tips, restrictions, mistakes) VALUES 
('leg-raises', 'es', 'Elevación de piernas', 'Ejercicio de control core enfocado en la musculatura abdominal inferior.', 'Fortalece el recto abdominal y los flexores de la cadera.', 'Tumbado boca arriba, eleva las piernas extendidas hasta formar un ángulo de 90 grados con el torso.', 'Mantén la zona lumbar pegada al suelo durante todo el recorrido.', 'Evitar si hay dolor agudo en la zona lumbar.', 'Arquear la espalda al bajar las piernas o usar impulso excesivo.'),
('leg-raises', 'en', 'Leg raises', 'Core control exercise focused on the lower abdominal muscles.', 'Strengthens the rectus abdominis and hip flexors.', 'Lying on your back, lift your extended legs until they form a 90-degree angle with your torso.', 'Keep your lower back pressed against the floor throughout the movement.', 'Avoid if acute lower back pain exists.', 'Arching the back when lowering legs or using excessive momentum.'),
('leg-raises', 'pt', 'Elevação de pernas', 'Exercício de controle do core focado na musculatura abdominal inferior.', 'Fortalece o reto abdominal e os flexores do quadril.', 'Deitado de costas, eleve as pernas estendidas até formar um ângulo de 90 graus com o tronco.', 'Mantenha a lombar colada no chão durante todo o movimento.', 'Evitar se houver dor lombar aguda.', 'Arquear as costas ao descer as pernas ou usar impulso excessivo.'),
('leg-raises', 'fr', 'Relevé de jambes', 'Exercice de contrôle du core ciblant la musculature abdominale inférieure.', 'Renforce le grand droit et les fléchisseurs de la hanche.', 'Allongé sur le dos, levez les jambes tendues jusqu''à former un angle de 90 degrés avec le buste.', 'Gardez le bas du dos plaqué au sol pendant tout le mouvement.', 'À éviter en cas de douleur aiguë au bas du dos.', 'Cambrer le dos en descendant les jambes ou utiliser un élan excessif.'),
('leg-raises', 'de', 'Beinheben', 'Core-Kontrollübung mit Fokus auf die untere Bauchmuskulatur.', 'Stärkt den geraden Bauchmuskel und die Hüftbeuger.', 'In Rückenlage die gestreckten Beine anheben, bis sie einen 90-Grad-Winkel zum Oberkörper bilden.', 'Den unteren Rücken während der gesamten Bewegung auf den Boden gedrückt halten.', 'Bei akuten Rückenschmerzen vermeiden.', 'Den Rücken beim Absenken der Beine durchbiegen oder übermäßigen Schwung verwenden.'),
('leg-raises', 'it', 'Sollevamento gambe', 'Esercizio di controllo del core focalizzato sulla muscolatura addominale inferiore.', 'Rinforza il retto addominale e i flessori dell''anca.', 'Sdraiato sulla schiena, solleva le gambe tese fino a formare un angolo di 90 gradi con il busto.', 'Mantieni la zona lombare a contatto con il suolo durante tutto il movimento.', 'Evitare in caso di dolore acuto alla zona lombare.', 'Inarcare la schiena durante la discesa o usare uno slancio eccessivo.'),
('leg-raises', 'zh', '仰卧抬腿', '核心控制练习，专注于下腹部肌肉。', '增强腹直肌和髋屈肌。', '仰卧，抬起伸直的双腿，直到与躯干成90度角。', '在整个运动过程中，保持腰部紧贴地面。', '如有急性腰痛，请避免使用。', '放下腿时拱背或使用过度的惯性。'),
('leg-raises', 'ja', 'レッグレイズ', '下腹部に焦点を当てたコアコントロール運動。', '腹直筋と股関節屈筋を強化します。', '仰向けになり、両脚を伸ばしたまま胴体と90度の角度になるまで持ち上げます。', '動作中ずっと腰を床に押し付けてください。', '腰に激しい痛みがある場合は避けてください。', '脚を下ろすときに腰を反らせることや、反動を使いすぎること。'),
('leg-raises', 'ko', '레그 레이즈', '하복부에 초점을 맞춘 코어 조절 운동.', '복직근 및 고관절 굴곡근 강화.', '누운 상태에서 다리를 펴고 상체와 90도가 될 때까지 들어 올림.', '동작 내내 허리를 바닥에 밀착시킬 것.', '요통이 있다면 피할 것.', '다리를 내릴 때 허리가 꺾이거나 반동을 과하게 사용하는 것.'),
('leg-raises', 'ar', 'تمرين رفع الساقين', 'تمرين للتحكم في الجذع يركز على عضلات البطن السفلية.', 'يقوي عضلة البطن المستقيمة وعضلات الورك.', 'استلقِ على ظهرك، وارفع ساقيك الممدودتين حتى تشكلا زاوية 90 درجة مع جذعك.', 'حافظ على ملامسة أسفل ظهرك للأرض طوال فترة التمرين.', 'تجنب التمرين في حالة وجود آلام حادة في أسفل الظهر.', 'تقوس الظهر عند خفض الساقين أو استخدام الزخم المفرط.'),
('leg-raises', 'hi', 'लेग रेजेज', 'कोर कंट्रोल व्यायाम जो निचले पेट की मांसपेशियों पर केंद्रित है।', 'रेक्टस एबडोमिनिस और कूल्हे के फ्लेक्सर्स को मजबूत करता है।', 'पीठ के बल लेटें, सीधे पैरों को धड़ के साथ 90 डिग्री का कोण बनाने तक ऊपर उठाएं।', 'पूरी गति के दौरान पीठ के निचले हिस्से को फर्श पर दबाकर रखें।', 'यदि पीठ के निचले हिस्से में तीव्र दर्द हो तो न करें।', 'पैर नीचे लाते समय पीठ को मोड़ने या बहुत अधिक गति का उपयोग करने से बचें।'),
('leg-raises', 'ru', 'Подъем ног', 'Упражнение на контроль кора, сфокусированное на нижней части мышц живота.', 'Укрепляет прямую мышцу живота и сгибатели бедра.', 'Лежа на спине, поднимите прямые ноги до угла 90 градусов с корпусом.', 'Прижимайте поясницу к полу на протяжении всего движения.', 'Избегайте при острой боли в пояснице.', 'Прогиб в спине при опускании ног или использование чрезмерной инерции.'),
('leg-raises', 'nl', 'Beenheffen', 'Core-controleoefening gericht op de onderste buikspieren.', 'Versterkt de rechte buikspier en heupbuigers.', 'Lig op de rug, til gestrekte benen op tot ze een hoek van 90 graden met de romp vormen.', 'Houd de onderrug gedurende de hele beweging tegen de vloer gedrukt.', 'Vermijden bij acute onderrugpijn.', 'De rug hol trekken bij het neerlaten of overmatig momentum gebruiken.'),
('leg-raises', 'sv', 'Benlyft', 'Övning för bålstabilitet med fokus på de nedre magmusklerna.', 'Stärker den raka magmuskeln och höftböjarna.', 'Ligg på rygg, lyft de raka benen tills de bildar en 90-graders vinkel mot bålen.', 'Håll ländryggen pressad mot golvet under hela rörelsen.', 'Undvik vid akut ländryggssmärta.', 'Att svanka när benen sänks eller att använda för mycket momentum.'),
('leg-raises', 'pl', 'Unoszenie nóg', 'Ćwiczenie kontroli core ukierunkowane na dolne partie mięśni brzucha.', 'Wzmacnia mięsień prosty brzucha i zginacze bioder.', 'W leżeniu na plecach unieś wyprostowane nogi, aż utworzą kąt 90 stopni z tułowiem.', 'Podczas całego ruchu utrzymuj odcinek lędźwiowy przyciśnięty do podłogi.', 'Unikaj w przypadku ostrego bólu kręgosłupa.', 'Wyginanie pleców przy opuszczaniu nóg lub używanie nadmiernego pędu.'),
('leg-raises', 'id', 'Leg raises', 'Latihan kontroli core yang berfokus pada otot perut bagian bawah.', 'Memperkuat otot perut rectus dan fleksor pinggul.', 'Berbaring telentang, angkat kaki yang lurus hingga membentuk sudut 90 derajat dengan tubuh.', 'Pertahankan punggung bawah menempel ke lantai selama gerakan.', 'Hindari jika ada nyeri punggung bawah akut.', 'Melengkungkan punggung saat menurunkan kaki atau menggunakan momentum berlebihan.'),
('leg-raises', 'bn', 'লেগ রেইজেস', 'নিচের পেটের পেশীর ওপর ফোকাস করা কোর কন্ট্রোল ব্যায়াম।', 'রেকটাস অ্যাবডোমিনিস ও হিপ ফ্লেক্সর শক্তিশালী করে।', 'পিঠের ওপর শুয়ে সোজা পা শরীরের সাথে ৯০ ডিগ্রি কোণ না হওয়া পর্যন্ত তুলুন।', 'ব্যায়ামের পুরো সময় পিঠের নিচের অংশ মেঝের সাথে চেপে রাখুন।', 'পিঠের নিচের অংশে তীব্র ব্যথা থাকলে এটি এড়িয়ে চলুন।', 'পা নামানোর সময় পিঠ বাঁকানো বা অতিরিক্ত গতির ব্যবহার করা।'),
('leg-raises', 'vi', 'Leg raises', 'Bài tập kiểm soát core tập trung vào cơ bụng dưới.', 'Tăng cường cơ bụng thẳng và cơ gập hông.', 'Nằm ngửa, nhấc chân duỗi thẳng cho đến khi tạo thành một góc 90 độ với thân người.', 'Giữ lưng dưới áp sát sàn trong suốt quá trình tập.', 'Tránh tập nếu bị đau lưng dưới cấp tính.', 'Võng lưng khi hạ chân hoặc dùng đà quá mức.'),
('leg-raises', 'fa', 'بالا آوردن پا', 'تمرین کنترل هسته بدن با تمرکز بر عضلات پایین شکم.', 'عضله راست شکمی و خم‌کننده‌های لگن را تقویت می‌کند.', 'به پشت دراز بکشید، پاهای صاف را تا زاویه ۹۰ درجه نسبت به تنه بالا بیاورید.', 'در طول حرکت، کمر را به زمین فشار دهید.', 'در صورت درد حاد کمر از انجام آن خودداری کنید.', 'قوس دادن به کمر هنگام پایین آوردن پاها یا استفاده از شتاب زیاد.');