-- Definición de ejercicios (Principal + Alternativas)
INSERT OR IGNORE INTO exercises (slug, img, video, difficulty) 
VALUES 
('mountain-climbers', 'mountain-climbers.jpg', 'mountain-climbers.mp4', 'intermediate'),
('slow-mountain-climbers', 'slow-mountain-climbers.jpg', 'slow-mountain-climbers.mp4', 'beginner');

-- Relaciones de grupos musculares (Solo ejercicio actual)
INSERT INTO exercise_body_target (exercise_slug, body_target_slug) 
VALUES 
('mountain-climbers', 'abdominals');

-- Relaciones de alternativas
INSERT INTO exercise_alternative (exercise_slug, alternative_slug) 
VALUES 
('mountain-climbers', 'slow-mountain-climbers');

-- Información multiidioma
INSERT OR IGNORE INTO exercises_info (slug, lang, title, description, benefits, instructions, tips, restrictions, mistakes) VALUES 
('mountain-climbers', 'es', 'Escaladores', 'Ejercicio dinámico de alta intensidad que enfatiza la estabilización y contracción abdominal.', 'Mejora la resistencia cardiovascular y fortalece el recto abdominal.', 'En posición de plancha alta, lleva las rodillas hacia el pecho de forma alterna y rápida.', 'Mantén la espalda recta y no permitas que la cadera rebote excesivamente.', 'Evitar si hay lesiones agudas en hombros o muñecas.', 'Elevar la cadera demasiado o realizar el movimiento sin control abdominal.'),
('mountain-climbers', 'en', 'Mountain climbers', 'High-intensity dynamic exercise emphasizing abdominal stabilization and contraction.', 'Improves cardiovascular endurance and strengthens the rectus abdominis.', 'From a high plank position, drive your knees toward your chest alternately and rapidly.', 'Keep your back straight and avoid excessive hip bouncing.', 'Avoid if acute shoulder or wrist injuries exist.', 'Raising hips too high or performing movement without abdominal control.'),
('mountain-climbers', 'pt', 'Escaladores', 'Exercício dinâmico de alta intensidade que enfatiza a estabilização e contração abdominal.', 'Melhora a resistência cardiovascular e fortalece o reto abdominal.', 'Na posição de prancha alta, leve os joelhos em direção ao peito de forma alternada e rápida.', 'Mantenha as costas retas e não permita que o quadril salte excessivamente.', 'Evitar se houver lesões agudas nos ombros ou pulsos.', 'Elevar o quadril demais ou realizar o movimento sem controle abdominal.'),
('mountain-climbers', 'fr', 'Grimpeurs', 'Exercice dynamique à haute intensité mettant l''accent sur la stabilisation et la contraction abdominale.', 'Améliore l''endurance cardiovasculaire et renforce le grand droit.', 'En position de planche haute, ramenez alternativement les genoux vers la poitrine de manière rapide.', 'Gardez le dos droit et évitez les rebonds excessifs des hanches.', 'À éviter en cas de blessures aiguës aux épaules ou aux poignets.', 'Lever les hanches trop haut ou effectuer le mouvement sans contrôle abdominal.'),
('mountain-climbers', 'de', 'Mountain Climbers', 'Dynamische Hochintensitätsübung mit Schwerpunkt auf Bauchstabilisierung und -kontraktion.', 'Verbessert die kardiovaskuläre Ausdauer und stärkt den geraden Bauchmuskel.', 'In der hohen Plank-Position abwechselnd und schnell die Knie zur Brust ziehen.', 'Den Rücken gerade halten und übermäßiges Hüpfwippen der Hüfte vermeiden.', 'Bei akuten Schulter- oder Handgelenksverletzungen vermeiden.', 'Hüfte zu hoch anheben oder die Bewegung ohne Bauchkontrolle ausführen.'),
('mountain-climbers', 'it', 'Mountain climbers', 'Esercizio dinamico ad alta intensità che enfatizza la stabilizzazione e la contrazione addominale.', 'Migliora la resistenza cardiovascolare e rinforza il retto addominale.', 'In posizione di plank alto, porta le ginocchia verso il petto in modo alternato e rapido.', 'Mantieni la schiena dritta ed evita rimbalzi eccessivi del bacino.', 'Evitare in caso di lesioni acute a spalle o polsi.', 'Sollevare troppo il bacino o eseguire il movimento senza controllo addominale.'),
('mountain-climbers', 'zh', '登山者式', '强调腹部稳定和收缩的高强度动态练习。', '提高心血管耐力并增强腹直肌。', '在高平板支撑位，交替快速将膝盖向胸部收缩。', '保持背部挺直，避免臀部过度弹跳。', '如有急性肩部或腕部损伤，请避免使用。', '臀部抬得过高或在没有腹部控制的情况下运动。'),
('mountain-climbers', 'ja', 'マウンテンクライマー', '腹部の安定と収縮を強調する高強度ダイナミックエクササイズ。', '心肺持久力を高め、腹直筋を強化します。', 'ハイプランクの姿勢から、交互に素早く膝を胸に引き寄せます。', '背筋を伸ばし、腰が跳ねすぎないように注意します。', '肩や手首に激しい怪我がある場合は避けてください。', '腰を上げすぎることや、腹部のコントロールなしで動くこと。'),
('mountain-climbers', 'ko', '마운틴 클라이머', '복부 안정화와 수축을 강조하는 고강도 동적 운동.', '심혈관 지구력 향상 및 복직근 강화.', '하이 플랭크 자세에서 무릎을 교대로 빠르게 가슴 쪽으로 당김.', '등을 곧게 유지하고 골반이 과하게 튀지 않도록 할 것.', '어깨나 손목 부상이 있다면 피할 것.', '골반을 너무 높게 들거나 복부 통제 없이 동작하는 것.'),
('mountain-climbers', 'ar', 'تمرين متسلق الجبال', 'تمرين ديناميكي عالي الشدة يركز على تثبيت وقبض عضلات البطن.', 'يحسن التحمل القلبي الوعائي ويقوي عضلة البطن المستقيمة.', 'من وضع البلانك العالي، ادفع ركبتيك نحو صدرك بالتناوب وبسرعة.', 'حافظ على استقامة ظهرك وتجنب قفز الحوض بشكل مفرط.', 'تجنب التمرين في حالة وجود إصابات حادة في الكتفين أو الرسغين.', 'رفع الحوض عالياً جداً أو أداء الحركة دون تحكم في عضلات البطن.'),
('mountain-climbers', 'hi', 'माउंटेन क्लाइम्बर्स', 'उच्च तीव्रता वाला गतिशील व्यायाम जो पेट के स्थिरीकरण और संकुचन पर जोर देता है।', 'हृदय संबंधी सहनशक्ति में सुधार करता है और रेक्टस एबडोमिनिस को मजबूत करता है।', 'हाई प्लेंक स्थिति में, बारी-बारी से और तेजी से घुटनों को छाती की ओर लाएं।', 'पीठ सीधी रखें और कूल्हों को बहुत अधिक उछलने से बचाएं।', 'यदि कंधे या कलाई में तीव्र चोट हो तो न करें।', 'कूल्हों को बहुत ऊपर उठाना या पेट के नियंत्रण के बिना हिलना।'),
('mountain-climbers', 'ru', 'Скалолаз', 'Динамическое упражнение высокой интенсивности, акцентирующее внимание на стабилизации и сокращении мышц живота.', 'Улучшает сердечно-сосудистую выносливость и укрепляет прямую мышцу живота.', 'Из положения планки на прямых руках быстро поочередно подтягивайте колени к груди.', 'Держите спину прямой и избегайте чрезмерных подпрыгиваний таза.', 'Избегайте при острых травмах плеч или запястий.', 'Слишком высокий подъем таза или выполнение упражнения без контроля пресса.'),
('mountain-climbers', 'nl', 'Mountain climbers', 'Dynamische oefening met hoge intensiteit die de nadruk legt op buikstabilisatie en -contractie.', 'Verbetert cardiovasculair uithoudingsvermogen en versterkt de rechte buikspier.', 'Breng vanuit een hoge plankpositie afwisselend en snel de knieën naar de borst.', 'Houd de rug recht en vermijd overmatig stuiteren van de heupen.', 'Vermijden bij acute schouder- of polsblessures.', 'Heupen te hoog optillen of bewegen zonder buikcontrole.'),
('mountain-climbers', 'sv', 'Mountain climbers', 'Dynamisk högintensiv övning som betonar magstabilisering och kontraktion.', 'Förbättrar kardiovaskulär uthållighet och stärker den raka magmuskeln.', 'I en hög plankposition, dra växelvis och snabbt knäna mot bröstet.', 'Håll ryggen rak och undvik att höfterna studsar för mycket.', 'Undvik vid akuta axel- eller handledsskador.', 'Att lyfta höfterna för högt eller utföra rörelsen utan magkontroll.'),
('mountain-climbers', 'pl', 'Mountain climbers (wspinaczka)', 'Dynamiczne ćwiczenie o wysokiej intensywności, kładące nacisk na stabilizację i napięcie mięśni brzucha.', 'Poprawia wydolność sercowo-naczyniową i wzmacnia mięsień prosty brzucha.', 'W pozycji deski, naprzemiennie i szybko przyciągaj kolana do klatki piersiowej.', 'Utrzymuj proste plecy i unikaj nadmiernego podskakiwania miednicy.', 'Unikaj w przypadku ostrych urazów barków lub nadgarstków.', 'Zbyt wysokie unoszenie miednicy lub wykonywanie ruchu bez kontroli brzucha.'),
('mountain-climbers', 'id', 'Mountain climbers', 'Latihan dinamis intensitas tinggi yang menekankan stabilisasi dan kontraksi perut.', 'Meningkatkan daya tahan kardiovaskular dan memperkuat otot perut rectus.', 'Dari posisi plank tinggi, tarik lutut ke dada secara bergantian dan cepat.', 'Jaga punggung tetap lurus dan hindari pantulan panggul yang berlebihan.', 'Hindari jika ada cedera bahu atau pergelangan tangan akut.', 'Mengangkat panggul terlalu tinggi atau melakukan gerakan tanpa kontrol perut.'),
('mountain-climbers', 'bn', 'মাউন্টেন ক্লাইম্বার', 'উচ্চ তীব্রতার ডায়নামিক ব্যায়াম যা পেটের পেশী সংকোচন ও স্থিতিশীলতার ওপর জোর দেয়।', 'হৃদযন্ত্রের সহনশীলতা বাড়ায় ও রেকটাস অ্যাবডোমিনিস শক্তিশালী করে।', 'হাই প্ল্যাঙ্ক পজিশন থেকে, দ্রুত ও অদলবদল করে হাঁটু বুকের দিকে আনুন।', 'পিঠ সোজা রাখুন এবং হিপ অতিরিক্ত দোলানো এড়িয়ে চলুন।', 'কাঁধে বা কবজিতে তীব্র ব্যথা থাকলে এটি এড়িয়ে চলুন।', 'হিপ খুব উঁচুতে তোলা বা পেটের নিয়ন্ত্রণ ছাড়াই ব্যায়াম করা।'),
('mountain-climbers', 'vi', 'Mountain climbers', 'Bài tập động cường độ cao nhấn mạnh vào việc ổn định và gồng cơ bụng.', 'Cải thiện sức bền tim mạch và tăng cường cơ bụng thẳng.', 'Từ tư thế plank cao, luân phiên đưa gối về phía ngực một cách nhanh chóng.', 'Giữ lưng thẳng và tránh để khung chậu nhún nhảy quá mức.', 'Tránh tập nếu bị chấn thương vai hoặc cổ tay cấp tính.', 'Nhấc khung chậu quá cao hoặc thực hiện không kiểm soát cơ bụng.'),
('mountain-climbers', 'fa', 'کوهنوردی (Mountain climbers)', 'تمرین پویا با شدت بالا که بر تثبیت و انقباض عضلات شکم تأکید دارد.', 'استقامت قلبی عروقی را بهبود می‌بخشد و عضله راست شکمی را تقویت می‌کند.', 'در حالت پلانک بالا، زانوها را به صورت متناوب و سریع به سمت قفسه سینه بکشید.', 'کمر را صاف نگه دارید و از پرش بیش از حد لگن خودداری کنید.', 'در صورت آسیب حاد شانه یا مچ دست از انجام آن خودداری کنید.', 'بالا بردن بیش از حد لگن یا انجام حرکت بدون کنترل شکم.');