-- Definición de ejercicios (Principal + Alternativas)
INSERT OR IGNORE INTO exercises (slug, img, video, difficulty) 
VALUES 
('russian-twists', 'russian-twists.jpg', 'russian-twists.mp4', 'intermediate'),
('seated-twists', 'seated-twists.jpg', 'seated-twists.mp4', 'beginner'),
('medicine-ball-twists', 'medicine-ball-twists.jpg', 'medicine-ball-twists.mp4', 'intermediate');

-- Relaciones de grupos musculares (Solo ejercicio actual)
INSERT INTO exercise_body_target (exercise_slug, body_target_slug) 
VALUES 
('russian-twists', 'abdominals');

-- Relaciones de alternativas
INSERT INTO exercise_alternative (exercise_slug, alternative_slug) 
VALUES 
('russian-twists', 'seated-twists'),
('russian-twists', 'medicine-ball-twists');

-- Información multiidioma
INSERT OR IGNORE INTO exercises_info (slug, lang, title, description, benefits, instructions, tips, restrictions, mistakes) VALUES 
('russian-twists', 'es', 'Giros rusos', 'Ejercicio rotacional enfocado en los oblicuos y la estabilidad del core.', 'Fortalece los oblicuos y mejora la estabilidad rotacional del torso.', 'Sentado con rodillas flexionadas, inclina el torso hacia atrás y gira el tronco de lado a lado.', 'Mantén la espalda recta y el movimiento controlado.', 'Evitar si hay hernias discales o dolor lumbar agudo.', 'Realizar giros rápidos sin control o encorvar la espalda.'),
('russian-twists', 'en', 'Russian twists', 'Rotational exercise focused on obliques and core stability.', 'Strengthens obliques and improves rotational torso stability.', 'Seated with knees bent, lean torso back and rotate from side to side.', 'Keep back straight and movement controlled.', 'Avoid if disc herniations or acute lower back pain exist.', 'Performing fast, uncontrolled twists or rounding the back.'),
('russian-twists', 'pt', 'Giros russos', 'Exercício rotacional focado nos oblíquos e na estabilidade do core.', 'Fortalece os oblíquos e melhora a estabilidade rotacional do tronco.', 'Sentado com joelhos dobrados, incline o tronco para trás e gire de lado a lado.', 'Mantenha as costas retas e o movimento controlado.', 'Evitar se houver hérnias de disco ou dor lombar aguda.', 'Fazer giros rápidos sem controle ou curvar as costas.'),
('russian-twists', 'fr', 'Twists russes', 'Exercice de rotation ciblant les obliques et la stabilité du core.', 'Renforce les obliques et améliore la stabilité rotationnelle du buste.', 'Assis avec genoux pliés, inclinez le buste vers l''arrière et pivotez de côté à côté.', 'Gardez le dos droit et le mouvement contrôlé.', 'À éviter en cas de hernie discale ou de douleur aiguë au bas du dos.', 'Effectuer des rotations rapides sans contrôle ou arrondir le dos.'),
('russian-twists', 'de', 'Russian Twists', 'Rotationsübung mit Fokus auf die schräge Bauchmuskulatur und Rumpfstabilität.', 'Stärkt die schrägen Bauchmuskeln und verbessert die Rotationsstabilität des Oberkörpers.', 'Sitzend mit angewinkelten Knien den Oberkörper leicht zurücklehnen und von Seite zu Seite drehen.', 'Rücken gerade halten und die Bewegung kontrolliert ausführen.', 'Bei Bandscheibenvorfällen oder akuten Rückenschmerzen vermeiden.', 'Schnelle, unkontrollierte Drehungen oder einen runden Rücken.'),
('russian-twists', 'it', 'Russian twists', 'Esercizio di rotazione focalizzato sugli obliqui e sulla stabilità del core.', 'Rinforza gli obliqui e migliora la stabilità rotazionale del busto.', 'Seduto con le ginocchia flesse, inclina il busto all''indietro e ruota da un lato all''altro.', 'Mantieni la schiena dritta e il movimento controllato.', 'Evitare in caso di ernia del disco o dolore lombare acuto.', 'Eseguire rotazioni rapide senza controllo o curvare la schiena.'),
('russian-twists', 'zh', '俄罗斯转体', '专注于腹外斜肌和核心稳定性的旋转练习。', '增强腹外斜肌并提高躯干的旋转稳定性。', '坐姿，膝盖弯曲，身体后倾，从一侧转到另一侧。', '保持背部挺直，动作受控。', '如有椎间盘突出或急性腰痛，请避免使用。', '动作过快失去控制或含胸驼背。'),
('russian-twists', 'ja', 'ロシアンツイスト', '腹斜筋とコアの安定性に焦点を当てた回旋運動。', '腹斜筋を強化し、体幹の回旋安定性を向上させます。', '膝を曲げて座り、上体を後ろに倒して左右にひねります。', '背筋を伸ばし、動作をコントロールしてください。', '椎間板ヘルニアや激しい腰痛がある場合は避けてください。', 'コントロールを失った速い回旋や、背中を丸めること。'),
('russian-twists', 'ko', '러시안 트위스트', '복사근 및 코어 안정성에 초점을 맞춘 회전 운동.', '복사근 강화 및 몸통의 회전 안정성 향상.', '무릎을 굽히고 앉아 상체를 뒤로 젖힌 뒤 좌우로 회전.', '등을 곧게 유지하고 통제된 동작으로 수행할 것.', '디스크 질환이나 요통이 있다면 피할 것.', '통제 없이 빠르게 회전하거나 등을 둥글게 말는 것.'),
('russian-twists', 'ar', 'تمرين الالتواء الروسي', 'تمرين دوراني يركز على العضلات المائلة واستقرار الجذع.', 'يقوي العضلات المائلة ويحسن استقرار دوران الجذع.', 'اجلس مع ثني ركبتيك، وقم بإمالة جذعك للخلف وقم بالدوران من جانب إلى آخر.', 'حافظ على استقامة ظهرك وتحكم في الحركة.', 'تجنب التمرين في حالة وجود انزلاق غضروفي أو آلام حادة في أسفل الظهر.', 'القيام بالالتواء السريع دون تحكم أو تقوس الظهر.'),
('russian-twists', 'hi', 'रशियन ट्विस्ट', 'ओब्लिक और कोर स्थिरता पर केंद्रित घूर्णी (rotational) व्यायाम।', 'ओब्लिक को मजबूत करता है और धड़ की घूर्णी स्थिरता में सुधार करता है।', 'घुटने मोड़कर बैठें, धड़ को पीछे झुकाएं और एक तरफ से दूसरी तरफ घुमाएं।', 'पीठ सीधी रखें और गति नियंत्रित रखें।', 'यदि हर्नियेटेड डिस्क या पीठ के निचले हिस्से में तीव्र दर्द हो तो न करें।', 'बिना नियंत्रण के तेजी से ट्विस्ट करना या पीठ को मोड़ना।'),
('russian-twists', 'ru', 'Русские скручивания', 'Вращательное упражнение, сфокусированное на косых мышцах живота и стабильности кора.', 'Укрепляет косые мышцы живота и улучшает вращательную стабильность корпуса.', 'Сидя с согнутыми коленями, отклоните корпус назад и выполняйте повороты из стороны в сторону.', 'Держите спину прямой, а движение контролируемым.', 'Избегайте при грыжах межпозвоночных дисков или острой боли в пояснице.', 'Слишком быстрые неконтролируемые повороты или округление спины.'),
('russian-twists', 'nl', 'Russian twists', 'Rotatieoefening gericht op de schuine buikspieren en core-stabiliteit.', 'Versterkt de schuine buikspieren en verbetert de rotatiestabiliteit van de romp.', 'Zittend met gebogen knieën, leun de romp naar achteren en draai van de ene naar de andere kant.', 'Houd de rug recht en de beweging gecontroleerd.', 'Vermijden bij hernia of acute onderrugpijn.', 'Snel en ongecontroleerd draaien of de rug krommen.'),
('russian-twists', 'sv', 'Russian twists', 'Rotationsövning med fokus på de sneda magmusklerna och bålstabilitet.', 'Stärker de sneda magmusklerna och förbättrar bålens rotationsstabilitet.', 'Sittande med böjda knän, luta överkroppen bakåt och rotera från sida till sida.', 'Håll ryggen rak och rörelsen kontrollerad.', 'Undvik vid diskbråck eller akut ländryggssmärta.', 'Att utföra snabba, okontrollerade vridningar eller att krumma ryggen.'),
('russian-twists', 'pl', 'Rosyjskie skręty', 'Ćwiczenie rotacyjne skupione na mięśniach skośnych brzucha i stabilności core.', 'Wzmacnia mięśnie skośne i poprawia stabilność rotacyjną tułowia.', 'W siadzie z ugiętymi kolanami odchyl tułów do tyłu i skręcaj się z boku na bok.', 'Utrzymuj proste plecy i kontrolowany ruch.', 'Unikaj w przypadku przepukliny krążka międzykręgowego lub ostrego bólu kręgosłupa.', 'Zbyt szybkie, niekontrolowane skręty lub zaokrąglanie pleców.'),
('russian-twists', 'id', 'Russian twists', 'Latihan rotasi yang berfokus pada otot perut miring dan stabilitas core.', 'Memperkuat otot perut miring dan meningkatkan stabilitas rotasi tubuh.', 'Duduk dengan lutut ditekuk, condongkan tubuh ke belakang dan putar dari sisi ke sisi.', 'Jaga punggung tetap lurus dan gerakan terkontrol.', 'Hindari jika ada hernia diskus atau nyeri punggung bawah akut.', 'Melakukan putaran cepat tanpa kontrol atau membungkukkan punggung.'),
('russian-twists', 'bn', 'রাশিয়ান টুইস্ট', 'ওবলিক্স এবং কোর স্থিতিশীলতার ওপর ফোকাস করা রোটেশনাল ব্যায়াম।', 'ওবলিক্স শক্তিশালী করে এবং শরীরের রোটেশনাল স্থিতিশীলতা উন্নত করে।', 'হাঁটু ভাঁজ করে বসে শরীরের ওপরের অংশ পেছনে হেলে দিন এবং দুপাশে ঘোরান।', 'পিঠ সোজা রাখুন এবং গতিবিধি নিয়ন্ত্রণ করুন।', 'হর্নিয়েটেড ডিস্ক বা পিঠের নিচের অংশে তীব্র ব্যথা থাকলে এটি এড়িয়ে চলুন।', 'অনিয়ন্ত্রিত গতিতে টুইস্ট করা বা পিঠ বাঁকানো।'),
('russian-twists', 'vi', 'Russian twists', 'Bài tập xoay tập trung vào cơ chéo bụng và ổn định core.', 'Tăng cường cơ chéo bụng và cải thiện sự ổn định xoay của thân người.', 'Ngồi với đầu gối cong, ngả thân người ra sau và xoay từ bên này sang bên kia.', 'Giữ lưng thẳng và chuyển động có kiểm soát.', 'Tránh tập nếu bị thoát vị đĩa đệm hoặc đau lưng dưới cấp tính.', 'Xoay nhanh mất kiểm soát hoặc gù lưng.'),
('russian-twists', 'fa', 'تویست روسی', 'تمرین چرخشی متمرکز بر عضلات مورب شکم و پایداری هسته بدن.', 'عضلات مورب را تقویت کرده و پایداری چرخشی تنه را بهبود می‌بخشد.', 'در حالت نشسته با زانوهای خم، تنه را به عقب متمایل کنید و به طرفین بچرخید.', 'کمر را صاف نگه دارید و حرکت را کنترل کنید.', 'در صورت فتق دیسک یا کمردرد حاد از انجام آن خودداری کنید.', 'چرخش سریع و غیرکنترل‌شده یا گرد کردن کمر.');