-- Definición de ejercicios
INSERT OR IGNORE INTO exercises (slug, img, video, difficulty) 
VALUES 
('single-leg-glute-bridge', 'single-leg-glute-bridge.jpg', 'single-leg-glute-bridge.mp4', 'intermediate'),
('glute-bridge', 'glute-bridge.jpg', 'glute-bridge.mp4', 'intermediate');

-- Relaciones de grupos musculares (Solo para single-leg-glute-bridge)
INSERT INTO exercise_body_target (exercise_slug, body_target_slug) 
VALUES 
('single-leg-glute-bridge', 'abdominals'),
('single-leg-glute-bridge', 'glutes');

-- Relaciones de alternativas
INSERT INTO exercise_alternative (exercise_slug, alternative_slug) 
VALUES 
('single-leg-glute-bridge', 'glute-bridge');

-- Información multiidioma
INSERT OR IGNORE INTO exercises_info (slug, lang, title, description, benefits, instructions, tips, restrictions, mistakes) VALUES 
('single-leg-glute-bridge', 'es', 'Puente de glúteos a una pierna', 'Variante unilateral del puente de glúteos que aumenta drásticamente la demanda de estabilidad abdominal y la carga en el glúteo activo.', 'Mejora el equilibrio de fuerza unilateral y la estabilidad lumbopélvica profunda.', 'Tumbado boca arriba, eleva una pierna y empuja la pelvis hacia arriba usando solo el talón de la pierna apoyada.', 'Mantén la pelvis nivelada y no permitas que se incline hacia el lado de la pierna libre.', 'Evitar si hay inestabilidad en la rodilla o dolor agudo en la zona lumbar.', 'Permitir que la cadera se caiga lateralmente o usar el impulso en lugar de la contracción controlada.'),
('single-leg-glute-bridge', 'en', 'Single-leg glute bridge', 'Unilateral bridge variant that drastically increases abdominal stability demand and load on the active glute.', 'Enhances unilateral strength balance and deep lumbopelvic stability.', 'Lying on your back, lift one leg and push your pelvis up using only the heel of the planted leg.', 'Keep the pelvis level and do not allow it to tilt toward the side of the free leg.', 'Avoid if knee instability or acute lower back pain exists.', 'Allowing the hip to drop laterally or using momentum instead of controlled contraction.'),
('single-leg-glute-bridge', 'pt', 'Ponte de glúteos unilateral', 'Variante unilateral da ponte de glúteos que aumenta drasticamente a demanda de estabilidade abdominal e a carga no glúteo ativo.', 'Melhora o equilíbrio de força unilateral e a estabilidade lumbopélvica profunda.', 'Deitado de costas, eleve uma perna e empurre a pelve para cima usando apenas o calcanhar da perna de apoio.', 'Mantenha a pelve nivelada e não permita que se incline para o lado da perna livre.', 'Evitar se houver instabilidade no joelho ou dor lombar aguda.', 'Permitir que o quadril caia lateralmente ou usar impulso em vez da contração controlada.'),
('single-leg-glute-bridge', 'fr', 'Pont fessier à une jambe', 'Variante unilatérale du pont fessier augmentant considérablement la demande de stabilité abdominale et la charge sur le fessier actif.', 'Améliore l''équilibre de force unilatéral et la stabilité lumbopelvienne profonde.', 'Allongé sur le dos, levez une jambe et poussez le bassin vers le haut en utilisant uniquement le talon de la jambe au sol.', 'Gardez le bassin à niveau et ne le laissez pas basculer vers le côté de la jambe libre.', 'À éviter en cas d''instabilité du genou ou de douleur aiguë au bas du dos.', 'Laisser la hanche basculer latéralement ou utiliser l''élan au lieu de la contraction contrôlée.'),
('single-leg-glute-bridge', 'de', 'Einbeinige Glute Bridge', 'Einseitige Variante der Glute Bridge, die die Anforderungen an die Bauchstabilität und die Belastung des aktiven Gesäßes drastisch erhöht.', 'Verbessert das einseitige Kraftgleichgewicht und die tiefe lumbopelvinale Stabilität.', 'In Rückenlage ein Bein anheben und das Becken nur mit der Ferse des Standbeins nach oben drücken.', 'Das Becken waagerecht halten und nicht zur Seite des freien Beins abkippen lassen.', 'Bei Knieinstabilität oder akuten Rückenschmerzen vermeiden.', 'Das Becken seitlich abfallen lassen oder Schwung statt kontrollierter Kontraktion verwenden.'),
('single-leg-glute-bridge', 'it', 'Ponte per glutei a una gamba', 'Variante unilaterale del ponte per glutei che aumenta drasticamente la richiesta di stabilità addominale e il carico sul gluteo attivo.', 'Migliora l''equilibrio della forza unilaterale e la stabilità lumbopelvica profonda.', 'Sdraiato sulla schiena, solleva una gamba e spingi il bacino verso l''alto usando solo il tallone della gamba in appoggio.', 'Mantieni il bacino allineato e non permettere che si inclini verso il lato della gamba libera.', 'Evitare in caso di instabilità del ginocchio o dolore lombare acuto.', 'Permettere che l''anca ceda lateralmente o usare l''inerzia invece della contrazione controllata.'),
('single-leg-glute-bridge', 'zh', '单腿臀桥', '单侧臀桥变体，大幅增加了腹部稳定需求和激活侧臀部的负荷。', '增强单侧力量平衡和深层腰盆腔稳定性。', '仰卧，抬起一条腿，仅用支撑腿的脚后跟向上推骨盆。', '保持骨盆水平，不要让它向悬空腿一侧倾斜。', '如有膝关节不稳或急性腰痛，请避免使用。', '允许髋部向侧面下沉或使用惯性而非受控挤压。'),
('single-leg-glute-bridge', 'ja', 'シングルレッグ・グルートブリッジ', '腹部の安定性要求と活性化側の臀部への負荷を劇的に高める片脚ブリッジバリエーション。', '左右の筋力バランスと深層腰骨盤安定性を向上させます。', '仰向けになり片脚を上げ、接地している脚のかかとのみを使って骨盤を押し上げます。', '骨盤を水平に保ち、浮いている脚の側に傾かないようにします。', '膝の不安定感や激しい腰痛がある場合は避けてください。', '腰が横に落ちることや、反動を使って持ち上げること。'),
('single-leg-glute-bridge', 'ko', '싱글 레그 글루트 브리지', '복부 안정성 요구와 활동성 둔근의 부하를 극대화하는 편측 브리지 변형.', '편측 근력 균형 및 심부 요골반 안정성 향상.', '누운 상태에서 한쪽 다리를 들고 지지하는 다리의 뒤꿈치만 사용하여 골반을 밀어 올림.', '골반이 들린 다리 쪽으로 기울지 않도록 수평을 유지할 것.', '무릎 불안정성이나 요통이 있다면 피할 것.', '골반이 옆으로 처지거나 통제된 수축 대신 반동을 사용하는 것.'),
('single-leg-glute-bridge', 'ar', 'تمرين جسر الأرداف بساق واحدة', 'نوع من جسر الأرداف أحادي الجانب يزيد بشكل كبير من متطلبات استقرار البطن والحمل على الأرداف.', 'يعزز توازن القوة أحادي الجانب واستقرار منطقة أسفل الظهر والحوض.', 'استلقِ على ظهرك، وارفع ساقاً واحدة وادفع حوضك للأعلى باستخدام كعب الساق المرتكزة فقط.', 'حافظ على مستوى الحوض ولا تسمح له بالميل نحو جانب الساق المرفوعة.', 'تجنب التمرين في حالة وجود عدم استقرار في الركبة أو آلام حادة في أسفل الظهر.', 'السماح للحوض بالانخفاض جانبياً أو استخدام الزخم بدلاً من الانقباض المتحكم فيه.'),
('single-leg-glute-bridge', 'hi', 'सिंगल-लेग ग्लूट ब्रिज', 'एकतरफा ब्रिज संस्करण जो पेट की स्थिरता की मांग और सक्रिय ग्लूट पर भार को काफी बढ़ा देता है।', 'एकतरफा ताकत संतुलन और गहरे लंबोपेलविक स्थिरता को बढ़ाता है।', 'पीठ के बल लेटें, एक पैर उठाएं और केवल टिके हुए पैर की एड़ी का उपयोग करके कूल्हों को ऊपर धकेलें।', 'कूल्हों को स्तर पर रखें और उन्हें मुक्त पैर की ओर झुकने न दें।', 'यदि घुटने में अस्थिरता या पीठ के निचले हिस्से में तीव्र दर्द हो तो न करें।', 'कूल्हे को पार्श्व में गिरने देना या नियंत्रित संकुचन के बजाय गति (momentum) का उपयोग करना।'),
('single-leg-glute-bridge', 'ru', 'Ягодичный мостик на одной ноге', 'Унилатеральный вариант мостика, значительно повышающий требования к стабильности живота и нагрузке на работающую ягодицу.', 'Улучшает силовой баланс и глубокую пояснично-тазовую стабильность.', 'Лежа на спине, поднимите одну ногу и толкайте таз вверх, используя только пятку опорной ноги.', 'Держите таз ровно, не позволяя ему заваливаться в сторону свободной ноги.', 'Избегайте при нестабильности колена или острой боли в пояснице.', 'Заваливание бедра в сторону или использование инерции вместо контролируемого сокращения.'),
('single-leg-glute-bridge', 'nl', 'Single-leg glute bridge', 'Eenzijdige variant van de glute bridge die de vraag naar buikstabiliteit en belasting op de actieve bil verhoogt.', 'Verbetert eenzijdige krachtbalans en diepe lumbopelvische stabiliteit.', 'Lig op de rug, til één been op en duw het bekken omhoog met alleen de hiel van het steunbeen.', 'Houd het bekken waterpas en laat het niet kantelen naar de kant van het vrije been.', 'Vermijden bij knie-instabiliteit of acute onderrugpijn.', 'Bekken zijwaarts laten zakken of momentum gebruiken in plaats van gecontroleerde contractie.'),
('single-leg-glute-bridge', 'sv', 'Single-leg glute bridge', 'Ensidig bryggvariant som ökar kravet på magstabilitet och belastning på sätet dramatiskt.', 'Förbättrar ensidig styrkebalans och djup lumbopelvisk stabilitet.', 'Ligg på rygg, lyft ett ben och tryck upp bäckenet med endast hälen på stödbenet.', 'Håll bäckenet plant och låt det inte tippa åt det fria benets sida.', 'Undvik vid knäinstabilitet eller akut ländryggssmärta.', 'Att låta bäckenet sjunka i sidled eller använda momentum istället för kontrollerad knipning.'),
('single-leg-glute-bridge', 'pl', 'Mostki biodrowe na jednej nodze', 'Jednostronny wariant mostka, drastycznie zwiększający zapotrzebowanie na stabilizację brzucha i obciążenie pracującego pośladka.', 'Poprawia jednostronną równowagę siłową i głęboką stabilność lędźwiowo-miedniczną.', 'W leżeniu na plecach unieś jedną nogę i wypchnij miednicę w górę, używając tylko pięty nogi podporowej.', 'Trzymaj miednicę równo i nie pozwól jej przechylać się w stronę wolnej nogi.', 'Unikaj w przypadku niestabilności kolana lub ostrego bólu kręgosłupa.', 'Pozwalanie na opadanie miednicy bokiem lub używanie pędu zamiast kontrolowanego napięcia.'),
('single-leg-glute-bridge', 'id', 'Single-leg glute bridge', 'Variasi jembatan satu sisi yang secara drastis meningkatkan permintaan stabilitas perut dan beban pada glute aktif.', 'Meningkatkan keseimbangan kekuatan satu sisi dan stabilitas lumbopelvik dalam.', 'Berbaring telentang, angkat satu kaki dan dorong panggul ke atas hanya menggunakan tumit kaki penyangga.', 'Jaga panggul tetap rata dan jangan biarkan miring ke sisi kaki yang bebas.', 'Hindari jika ada ketidakstabilan lutut atau nyeri punggung bawah akut.', 'Membiarkan panggul jatuh ke samping atau menggunakan momentum daripada kontraksi terkontrol.'),
('single-leg-glute-bridge', 'bn', 'সিঙ্গেল-লেগ গ্লুট ব্রিজ', 'একতরফা ব্রিজ সংস্করণ যা পেটের স্থিতিশীলতার চাহিদা এবং সক্রিয় গ্লুটসের ওপর চাপ বাড়ায়।', 'একতরফা শক্তির ভারসাম্য এবং গভীর লম্বোপেলভিক স্থিতিশীলতা উন্নত করে।', 'পিঠের ওপর শুয়ে একটি পা তুলুন এবং সাপোর্ট পায়ের গোড়ালি দিয়ে পেলভিস ওপরে ঠেলুন।', 'পেলভিস সোজা রাখুন এবং ফ্রি পায়ের দিকে কাত হতে দেবেন না।', 'হাঁটুতে অস্থিরতা বা পিঠের নিচের অংশে তীব্র ব্যথা থাকলে এটি এড়িয়ে চলুন।', 'পেলভিস পাশে ঝুলে পড়তে দেওয়া বা নিয়ন্ত্রিত সংকোচনের পরিবর্তে গতির ব্যবহার করা।'),
('single-leg-glute-bridge', 'vi', 'Single-leg glute bridge', 'Biến thể cầu mông một chân làm tăng đáng kể nhu cầu ổn định bụng và tải trọng lên cơ mông hoạt động.', 'Cải thiện sự cân bằng sức mạnh một bên và sự ổn định vùng thắt lưng-chậu sâu.', 'Nằm ngửa, nhấc một chân và đẩy khung chậu lên bằng gót chân của chân trụ.', 'Giữ khung chậu cân bằng và không để nghiêng về phía chân tự do.', 'Tránh tập nếu bị mất ổn định khớp gối hoặc đau lưng dưới cấp tính.', 'Để khung chậu bị lệch sang bên hoặc dùng đà thay vì gồng cơ có kiểm soát.'),
('single-leg-glute-bridge', 'fa', 'پل باسن تک‌پا', 'نوعی پل یک‌طرفه که نیاز به ثبات شکم و بار روی عضلات باسن فعال را به‌شدت افزایش می‌دهد.', 'تعادل قدرت یک‌طرفه و پایداری عمقی لومبوی لگنی را بهبود می‌بخشد.', 'به پشت دراز بکشید، یک پا را بالا ببرید و با پاشنه پای تکیه‌گاه لگن را بالا هل دهید.', 'لگن را تراز نگه دارید و اجازه ندهید به سمت پای آزاد کج شود.', 'در صورت بی‌ثباتی زانو یا کمردرد حاد از انجام آن خودداری کنید.', 'اجازه دادن به افتادن لگن به سمت جانبی یا استفاده از شتاب به جای انقباض کنترل‌شده.');
