-- Definición de ejercicios (Principal + Alternativas)
INSERT OR IGNORE INTO exercises (slug, img, video, difficulty) 
VALUES 
('mountain-climbers', 'mountain-climbers.jpg', 'mountain-climbers.mp4', 'intermediate'),
('slow-mountain-climbers', 'slow-mountain-climbers.jpg', 'slow-mountain-climbers.mp4', 'beginner');

-- Relaciones de grupos musculares (Principal)
INSERT INTO exercise_body_target (exercise_slug, body_target_slug) 
VALUES 
('slow-mountain-climbers', 'abdominals');

-- Relaciones de alternativas (Si tiene, por ejemplo, mountain-climbers)
INSERT INTO exercise_alternative (exercise_slug, alternative_slug) 
VALUES 
('slow-mountain-climbers', 'mountain-climbers');

-- Información multiidioma (Ya la generamos anteriormente, aquí solo la reafirmo en tu estructura)
INSERT OR IGNORE INTO exercises_info (slug, lang, title, description, benefits, instructions, tips, restrictions, mistakes) VALUES 
('slow-mountain-climbers', 'es', 'Escaladores lentos', 'Variante controlada de los escaladores enfocada en la tensión muscular continua y el control motor.', 'Desarrolla la fuerza isométrica y la estabilidad del core.', 'En posición de plancha, lleva la rodilla al pecho lentamente manteniendo una contracción sostenida.', 'Céntrate en la calidad del movimiento y la activación abdominal profunda.', 'Evitar si hay lesiones agudas en hombros o muñecas.', 'Moverse demasiado rápido perdiendo la conexión abdominal.'),
('slow-mountain-climbers', 'en', 'Slow mountain climbers', 'Controlled mountain climber variant focused on continuous muscle tension and motor control.', 'Develops isometric strength and core stability.', 'From a plank position, drive the knee to the chest slowly maintaining sustained contraction.', 'Focus on movement quality and deep abdominal activation.', 'Avoid if acute shoulder or wrist injuries exist.', 'Moving too fast and losing the abdominal connection.'),
('slow-mountain-climbers', 'pt', 'Escaladores lentos', 'Variante controlada dos escaladores focada na tensão muscular contínua e controle motor.', 'Desenvolve a força isométrica e estabilidade do core.', 'Na posição de prancha, leve o joelho ao peito lentamente mantendo uma contração sustentada.', 'Foque na qualidade do movimento e ativação abdominal profunda.', 'Evitar se houver lesões agudas nos ombros ou pulsos.', 'Mover-se rápido demais perdendo a conexão abdominal.'),
('slow-mountain-climbers', 'fr', 'Grimpeurs lents', 'Variante contrôlée des grimpeurs axée sur la tension musculaire continue et le contrôle moteur.', 'Développe la force isométrique et la stabilité du core.', 'En position de planche, ramenez le genou à la poitrine lentement en maintenant une contraction soutenue.', 'Concentrez-vous sur la qualité du mouvement et l''activation abdominale profonde.', 'À éviter en cas de blessures aiguës aux épaules ou aux poignets.', 'Bouger trop vite et perdre la connexion abdominale.'),
('slow-mountain-climbers', 'de', 'Slow Mountain Climbers', 'Kontrollierte Variante mit Fokus auf kontinuierliche Muskelspannung und motorische Kontrolle.', 'Entwickelt isometrische Kraft und Rumpfstabilität.', 'Aus der Plank-Position das Knie langsam zur Brust führen und die Kontraktion halten.', 'Auf Bewegungsqualität und tiefe Bauchaktivierung konzentrieren.', 'Bei akuten Schulter- oder Handgelenksverletzungen vermeiden.', 'Zu schnelles Bewegen und Verlust der Bauchspannung.'),
('slow-mountain-climbers', 'it', 'Mountain climbers lenti', 'Variante controllata focalizzata sulla tensione muscolare continua e sul controllo motorio.', 'Sviluppa forza isometrica e stabilità del core.', 'Dalla posizione di plank, porta il ginocchio al petto lentamente mantenendo una contrazione sostenuta.', 'Concentrati sulla qualità del movimento e sull''attivazione addominale profonda.', 'Evitare in caso di lesioni acute a spalle o polsi.', 'Muoversi troppo velocemente perdendo la connessione addominale.'),
('slow-mountain-climbers', 'zh', '慢速登山者式', '受控的登山者变体，侧重于持续的肌肉张力和运动控制。', '发展等长力量和核心稳定性。', '在平板支撑位，缓慢将膝盖拉向胸部，并保持持续收缩。', '专注于动作质量和深层腹部激活。', '如有急性肩部或腕部损伤，请避免使用。', '移动太快，导致腹部收缩感丢失。'),
('slow-mountain-climbers', 'ja', 'スロー・マウンテンクライマー', '持続的な筋緊張と運動制御に焦点を当てた、制御されたバリエーション。', '等尺性筋力とコアの安定性を発達させます。', 'プランクの姿勢から、持続的な収縮を維持しながらゆっくりと膝を胸に引き寄せます。', '動作の質と深層腹筋の活性化に集中してください。', '肩や手首に激しい怪我がある場合は避けてください。', '速く動きすぎて腹部の接続が切れること。'),
('slow-mountain-climbers', 'ko', '슬로우 마운틴 클라이머', '지속적인 근긴장과 운동 제어에 초점을 맞춘 통제된 변형.', '등척성 근력과 코어 안정성 발달.', '플랭크 자세에서 지속적인 수축을 유지하며 무릎을 천천히 가슴 쪽으로 당김.', '동작의 질과 심부 복근 활성화에 집중할 것.', '어깨나 손목 부상이 있다면 피할 것.', '너무 빠르게 움직여 복부 연결이 끊기는 것.'),
('slow-mountain-climbers', 'ar', 'تمرين متسلق الجبال البطيء', 'نوع متحكم فيه يركز على التوتر العضلي المستمر والتحكم الحركي.', 'يطور القوة الثابتة واستقرار الجذع.', 'من وضع البلانك، ادفع الركبة نحو الصدر ببطء مع الحفاظ على انقباض مستمر.', 'ركز على جودة الحركة وتفعيل عضلات البطن العميقة.', 'تجنب التمرين في حالة وجود إصابات حادة في الكتفين أو الرسغين.', 'التحرك بسرعة كبيرة وفقدان تفعيل عضلات البطن.'),
('slow-mountain-climbers', 'hi', 'स्लो माउंटेन क्लाइम्बर्स', 'नियंत्रित संस्करण जो निरंतर मांसपेशियों के तनाव और मोटर नियंत्रण पर केंद्रित है।', 'आइसोमेट्रिक ताकत और कोर स्थिरता विकसित करता है।', 'प्लेंक स्थिति से, निरंतर संकुचन बनाए रखते हुए घुटने को धीरे-धीरे छाती की ओर लाएं।', 'आंदोलन की गुणवत्ता और गहरे पेट के सक्रियण पर ध्यान दें।', 'यदि कंधे या कलाई में तीव्र चोट हो तो न करें।', 'बहुत तेजी से आगे बढ़ना और पेट का संबंध खोना।'),
('slow-mountain-climbers', 'ru', 'Медленный скалолаз', 'Контролируемый вариант с акцентом на постоянное мышечное напряжение и контроль движений.', 'Развивает изометрическую силу и стабильность кора.', 'Из положения планки медленно подтягивайте колено к груди, удерживая напряжение.', 'Сосредоточьтесь на качестве движения и глубокой активации мышц живота.', 'Избегайте при острых травмах плеч или запястий.', 'Слишком быстрое движение и потеря мышечного контроля.'),
('slow-mountain-climbers', 'nl', 'Slow mountain climbers', 'Gecontroleerde variant gericht op continue spierspanning en motorische controle.', 'Ontwikkelt isometrische kracht en core-stabiliteit.', 'Breng vanuit plankpositie de knie langzaam naar de borst met behoud van contractie.', 'Focus op bewegingskwaliteit en diepe buikactivatie.', 'Vermijden bij acute schouder- of polsblessures.', 'Te snel bewegen en de buikverbinding verliezen.'),
('slow-mountain-climbers', 'sv', 'Slow mountain climbers', 'Kontrollerad variant med fokus på kontinuerlig muskelspänning och motorisk kontroll.', 'Utvecklar isometrisk styrka och bålstabilitet.', 'Från plankposition, dra knät långsamt mot bröstet med bibehållen kontraktion.', 'Fokusera på rörelsekvalitet och djup magaktivering.', 'Undvik vid akuta axel- eller handledsskador.', 'Att röra sig för snabbt och tappa magkontakten.'),
('slow-mountain-climbers', 'pl', 'Powolna wspinaczka', 'Kontrolowany wariant skupiający się na ciągłym napięciu mięśniowym i kontroli motorycznej.', 'Rozwija siłę izometryczną i stabilność core.', 'Z pozycji deski powoli przyciągaj kolano do klatki piersiowej, utrzymując stałe napięcie.', 'Skup się na jakości ruchu i głębokiej aktywacji mięśni brzucha.', 'Unikaj w przypadku ostrych urazów barków lub nadgarstków.', 'Zbyt szybkie wykonywanie ruchu i utrata napięcia mięśni brzucha.'),
('slow-mountain-climbers', 'id', 'Slow mountain climbers', 'Variasi terkontrol yang berfokus pada ketegangan otot berkelanjutan dan kontrol motorik.', 'Mengembangkan kekuatan isometrik dan stabilitas core.', 'Dari posisi plank, tarik lutut ke dada secara perlahan dengan mempertahankan kontraksi.', 'Fokus pada kualitas gerakan dan aktivasi perut bagian dalam.', 'Hindari jika ada cedera bahu atau pergelangan tangan akut.', 'Bergerak terlalu cepat dan kehilangan koneksi perut.'),
('slow-mountain-climbers', 'bn', 'স্লো মাউন্টেন ক্লাইম্বার', 'নিয়ন্ত্রিত সংস্করণ যা পেশীর ক্রমাগত টান এবং নিয়ন্ত্রণ বাড়ায়।', 'আইসোমেট্রিক শক্তি এবং কোর স্থিতিশীলতা বৃদ্ধি করে।', 'প্ল্যাঙ্ক পজিশন থেকে, পেশীর টান বজায় রেখে ধীরে ধীরে হাঁটু বুকের দিকে আনুন।', 'ব্যায়ামের মান এবং গভীর পেটের সক্রিয়তার ওপর মনোযোগ দিন।', 'কাঁধে বা কবজিতে তীব্র ব্যথা থাকলে এটি এড়িয়ে চলুন।', 'খুব দ্রুত নড়াচড়া করা যার ফলে পেটের পেশীর নিয়ন্ত্রণ হারানো।'),
('slow-mountain-climbers', 'vi', 'Slow mountain climbers', 'Biến thể có kiểm soát tập trung vào lực căng cơ liên tục và kiểm soát vận động.', 'Phát triển sức mạnh tĩnh và sự ổn định core.', 'Từ tư thế plank, từ từ đưa gối về phía ngực, duy trì lực gồng.', 'Tập trung vào chất lượng chuyển động và kích hoạt cơ bụng sâu.', 'Tránh tập nếu bị chấn thương vai hoặc cổ tay cấp tính.', 'Di chuyển quá nhanh làm mất liên kết cơ bụng.'),
('slow-mountain-climbers', 'fa', 'کوهنوردی آرام (Slow mountain climbers)', 'نوع کنترل‌شده با تمرکز بر تنش عضلانی مداوم و کنترل حرکتی.', 'قدرت ایزومتریک و پایداری هسته بدن را توسعه می‌دهد.', 'در حالت پلانک، زانو را به‌آرامی به سمت قفسه سینه بکشید و انقباض را حفظ کنید.', 'بر کیفیت حرکت و فعال‌سازی عمیق شکم تمرکز کنید.', 'در صورت آسیب حاد شانه یا مچ دست از انجام آن خودداری کنید.', 'حرکت خیلی سریع و از دست دادن کنترل شکم.');