-- Definición de ejercicios (Principal + Alternativas)
INSERT OR IGNORE INTO exercises (slug, img, video, difficulty) 
VALUES 
('v-ups', 'v-ups.jpg', 'v-ups.mp4', 'intermediate'),
('toe-touches', 'toe-touches.jpg', 'toe-touches.mp4', 'beginner'),
('jackknife-sit-ups', 'jackknife-sit-ups.jpg', 'jackknife-sit-ups.mp4', 'intermediate');

-- Relaciones de grupos musculares (Solo ejercicio actual)
INSERT INTO exercise_body_target (exercise_slug, body_target_slug) 
VALUES 
('v-ups', 'abdominals');

-- Relaciones de alternativas
INSERT INTO exercise_alternative (exercise_slug, alternative_slug) 
VALUES 
('v-ups', 'toe-touches'),
('v-ups', 'jackknife-sit-ups');

-- Información multiidioma
INSERT OR IGNORE INTO exercises_info (slug, lang, title, description, benefits, instructions, tips, restrictions, mistakes) VALUES 
('v-ups', 'es', 'Abdominales en V', 'Ejercicio avanzado que implica la elevación simultánea de tronco y piernas.', 'Fortalece profundamente el recto abdominal y mejora la coordinación del core.', 'Tumbado, eleva simultáneamente piernas y torso hasta que tus manos toquen tus pies.', 'Mantén las piernas lo más rectas posible y el control constante.', 'Evitar si hay dolor lumbar agudo o problemas de hernia.', 'Usar impulso excesivo o arquear la espalda al bajar.'),
('v-ups', 'en', 'V-ups', 'Advanced exercise involving simultaneous elevation of torso and legs.', 'Deeply strengthens rectus abdominis and improves core coordination.', 'Lying down, simultaneously raise legs and torso until your hands touch your feet.', 'Keep legs as straight as possible and maintain constant control.', 'Avoid if acute lower back pain or disc issues exist.', 'Using excessive momentum or arching the back on descent.'),
('v-ups', 'pt', 'Abdominais em V', 'Exercício avançado que envolve a elevação simultânea do tronco e pernas.', 'Fortalece profundamente o reto abdominal e melhora a coordenação do core.', 'Deitado, eleve simultaneamente pernas e tronco até que as mãos toquem os pés.', 'Mantenha as pernas o mais retas possível e controle constante.', 'Evitar se houver dor lombar aguda ou problemas de hérnia.', 'Usar impulso excessivo ou curvar as costas ao descer.'),
('v-ups', 'fr', 'V-ups (Abdominaux en V)', 'Exercice avancé impliquant l''élévation simultanée du buste et des jambes.', 'Renforce en profondeur le grand droit et améliore la coordination du core.', 'Allongé, levez simultanément les jambes et le buste jusqu''à ce que vos mains touchent vos pieds.', 'Gardez les jambes aussi droites que possible et gardez un contrôle constant.', 'À éviter en cas de douleur aiguë au bas du dos ou de hernie.', 'Utiliser un élan excessif ou cambrer le dos lors de la descente.'),
('v-ups', 'de', 'V-ups', 'Fortgeschrittene Übung, die ein gleichzeitiges Anheben von Oberkörper und Beinen beinhaltet.', 'Stärkt tief den geraden Bauchmuskel und verbessert die Rumpfkoordination.', 'In Rückenlage gleichzeitig Beine und Oberkörper anheben, bis die Hände die Füße berühren.', 'Beine so gerade wie möglich halten und die Bewegung kontrolliert ausführen.', 'Bei akuten Rückenschmerzen oder Bandscheibenproblemen vermeiden.', 'Übermäßigen Schwung holen oder den Rücken beim Absenken durchbiegen.'),
('v-ups', 'it', 'V-ups', 'Esercizio avanzato che comporta l''elevazione simultanea di busto e gambe.', 'Rinforza in profondità il retto addominale e migliora la coordinazione del core.', 'Sdraiato, solleva contemporaneamente gambe e busto finché le mani toccano i piedi.', 'Mantieni le gambe il più dritte possibile e mantieni un controllo costante.', 'Evitare in caso di dolore lombare acuto o ernia.', 'Usare uno slancio eccessivo o inarcare la schiena durante la discesa.'),
('v-ups', 'zh', 'V字两头起', '涉及躯干和腿部同时抬起的高级练习。', '深入增强腹直肌并提高核心协调性。', '仰卧，同时抬起双腿和躯干，直到手触碰到脚。', '尽可能保持双腿伸直并保持持续控制。', '如有急性腰痛或椎间盘问题，请避免使用。', '使用过度的惯性或下放时拱背。'),
('v-ups', 'ja', 'Vアップ', '上体と脚を同時に持ち上げる高度なエクササイズ。', '腹直筋を深く強化し、コアの協調性を向上させます。', '仰向けから、両手で足先に触れるように脚と上体を同時に持ち上げます。', '脚をできるだけ伸ばし、常にコントロールを保ってください。', '腰の激しい痛みや椎間板の問題がある場合は避けてください。', '反動を使いすぎることや、下ろすときに背中を反らせること。'),
('v-ups', 'ko', 'V-업', '상체와 다리를 동시에 들어 올리는 고급 운동.', '복직근을 깊게 강화하고 코어 조절 능력 향상.', '누운 상태에서 다리와 상체를 동시에 들어 올려 손과 발이 닿게 함.', '다리를 최대한 곧게 펴고 지속적으로 통제할 것.', '요통이나 디스크 질환이 있다면 피할 것.', '반동을 과하게 사용하거나 내릴 때 허리가 꺾이는 것.'),
('v-ups', 'ar', 'تمرين حرف V (V-ups)', 'تمرين متقدم يتضمن رفع الجذع والساقين في وقت واحد.', 'يقوي عضلة البطن المستقيمة بعمق ويحسن تنسيق الجذع.', 'استلقِ، وارفع ساقيك وجذعك في آن واحد حتى تلمس يداك قدميك.', 'حافظ على استقامة ساقيك قدر الإمكان وتحكم في الحركة.', 'تجنب التمرين في حالة وجود آلام حادة في أسفل الظهر أو مشاكل في الغضاريف.', 'استخدام زخم مفرط أو تقوس الظهر عند النزول.'),
('v-ups', 'hi', 'वी-अप्स', 'उन्नत व्यायाम जिसमें धड़ और पैरों को एक साथ उठाना शामिल है।', 'रेक्टस एबडोमिनिस को गहराई से मजबूत करता है और कोर समन्वय में सुधार करता है।', 'पीठ के बल लेटें, पैरों और धड़ को एक साथ उठाएं जब तक कि हाथ पैरों को न छुएं।', 'पैरों को जितना संभव हो सीधा रखें और लगातार नियंत्रण बनाए रखें।', 'यदि पीठ के निचले हिस्से में तीव्र दर्द या हर्निया की समस्या हो तो न करें।', 'अत्यधिक गति का उपयोग करना या नीचे आते समय पीठ को मोड़ना।'),
('v-ups', 'ru', 'V-складка', 'Продвинутое упражнение, включающее одновременный подъем корпуса и ног.', 'Глубоко укрепляет прямую мышцу живота и улучшает координацию кора.', 'Лежа на спине, одновременно поднимите ноги и корпус до касания руками стоп.', 'Держите ноги максимально прямыми и сохраняйте постоянный контроль.', 'Избегайте при острой боли в пояснице или проблемах с дисками.', 'Использование излишней инерции или прогиб в спине при опускании.'),
('v-ups', 'nl', 'V-ups', 'Geavanceerde oefening waarbij romp en benen tegelijkertijd worden opgetild.', 'Versterkt de rechte buikspier diep en verbetert core-coördinatie.', 'Lig op de rug, til tegelijkertijd benen en romp op tot de handen de voeten raken.', 'Houd de benen zo recht mogelijk en behoud constante controle.', 'Vermijden bij acute onderrugpijn of hernia-problemen.', 'Te veel momentum gebruiken of de rug krommen bij het neerlaten.'),
('v-ups', 'sv', 'V-ups', 'Avancerad övning som innebär att överkropp och ben lyfts samtidigt.', 'Stärker den raka magmuskeln på djupet och förbättrar bålkoordinationen.', 'Liggande, lyft benen och överkroppen samtidigt tills händerna nuddar fötterna.', 'Håll benen så raka som möjligt och behåll konstant kontroll.', 'Undvik vid akut ländryggssmärta eller diskproblem.', 'Att använda för mycket momentum eller svanka vid sänkningen.'),
('v-ups', 'pl', 'V-ups (Spięcia V)', 'Zaawansowane ćwiczenie wymagające jednoczesnego uniesienia tułowia i nóg.', 'Głęboko wzmacnia mięsień prosty brzucha i poprawia koordynację core.', 'W leżeniu unieś jednocześnie nogi i tułów, aż dłonie dotkną stóp.', 'Trzymaj nogi jak najbardziej proste i zachowaj stałą kontrolę.', 'Unikaj w przypadku ostrego bólu kręgosłupa lub problemów z dyskami.', 'Używanie nadmiernego pędu lub wyginanie pleców przy opuszczaniu.'),
('v-ups', 'id', 'V-ups', 'Latihan lanjutan yang melibatkan pengangkatan batang tubuh dan kaki secara bersamaan.', 'Memperkuat otot perut rectus secara mendalam dan meningkatkan koordinasi core.', 'Berbaring, angkat kaki dan batang tubuh secara bersamaan hingga tangan menyentuh kaki.', 'Jaga kaki tetap lurus dan pertahankan kontrol terus-menerus.', 'Hindari jika ada nyeri punggung bawah akut atau masalah cakram.', 'Menggunakan momentum berlebihan atau melengkungkan punggung saat menurunkan.'),
('v-ups', 'bn', 'ভি-আপস', 'উন্নত ব্যায়াম যা ধড় ও পা একইসাথে ওঠানো বোঝায়।', 'রেকটাস অ্যাবডোমিনিস গভীরভাবে শক্তিশালী করে এবং কোর সমন্বয় বাড়ায়।', 'পিঠের ওপর শুয়ে হাত দিয়ে পা ছোঁয়ার জন্য পা ও ধড় একসাথে তুলুন।', 'পা যতদূর সম্ভব সোজা রাখুন এবং ক্রমাগত নিয়ন্ত্রণ বজায় রাখুন।', 'পিঠের নিচের অংশে তীব্র ব্যথা বা ডিস্কের সমস্যা থাকলে এটি এড়িয়ে চলুন।', 'অতিরিক্ত গতি ব্যবহার করা বা নিচে নামার সময় পিঠ বাঁকানো।'),
('v-ups', 'vi', 'V-ups', 'Bài tập nâng cao đòi hỏi nâng thân người và chân cùng lúc.', 'Tăng cường cơ bụng thẳng sâu và cải thiện sự phối hợp cơ core.', 'Nằm ngửa, nâng đồng thời chân và thân người cho đến khi tay chạm chân.', 'Giữ chân thẳng nhất có thể và duy trì sự kiểm soát.', 'Tránh tập nếu bị đau lưng dưới cấp tính hoặc thoát vị đĩa đệm.', 'Dùng đà quá mức hoặc võng lưng khi hạ xuống.'),
('v-ups', 'fa', 'وی-آپ (V-ups)', 'تمرین پیشرفته که شامل بالا آوردن همزمان تنه و پاها است.', 'عضله راست شکمی را به عمق تقویت کرده و هماهنگی هسته بدن را بهبود می‌بخشد.', 'به پشت دراز بکشید، همزمان پاها و تنه را بلند کنید تا دست‌ها به پاها برسند.', 'پاها را تا حد ممکن صاف نگه دارید و کنترل مداوم داشته باشید.', 'در صورت درد حاد کمر یا مشکلات دیسک از انجام آن خودداری کنید.', 'استفاده از شتاب زیاد یا قوس دادن به کمر هنگام پایین آمدن.');