-- Definición de ejercicio principal
INSERT OR IGNORE INTO exercises (slug, img, video, difficulty) 
VALUES 
('leg-raises', 'leg-raises.jpg', 'leg-raises.mp4', 'beginner'),
('weighted-leg-raises', 'weighted-leg-raises.jpg', 'weighted-leg-raises.mp4', 'advanced');

-- Relación de grupo muscular
INSERT OR IGNORE INTO exercise_body_target (exercise_slug, body_target_slug) 
VALUES 
('weighted-leg-raises', 'abdominals');

-- Relaciones de alternativas
INSERT OR IGNORE INTO exercise_alternative (exercise_slug, alternative_slug) 
VALUES 
('weighted-leg-raises', 'leg-raises');

-- Información multiidioma
INSERT OR IGNORE INTO exercises_info (slug, lang, title, description, benefits, instructions, tips, restrictions, mistakes) VALUES 
('weighted-leg-raises', 'es', 'Elevación de piernas con peso', 'Elevación de piernas añadiendo carga externa (como una mancuerna o tobilleras) para mayor hipertrofia.', 'Aumenta significativamente la resistencia y fuerza del abdomen inferior.', 'Sujeta un peso entre los pies o usa tobilleras; eleva las piernas a 90 grados controladamente.', 'Mantén la zona lumbar pegada al suelo durante todo el recorrido.', 'Evitar si hay debilidad en el core o dolor lumbar presente.', 'Balancear el peso usando inercia en lugar de fuerza abdominal.'),
('weighted-leg-raises', 'en', 'Weighted leg raises', 'Leg raises adding external load (dumbbell or ankle weights) for increased hypertrophy.', 'Significantly increases resistance and strength of the lower abs.', 'Hold weight between feet or use ankle weights; raise legs to 90 degrees in a controlled manner.', 'Keep lumbar spine pressed to the floor throughout the movement.', 'Avoid if core weakness or lumbar pain is present.', 'Swinging the weight using momentum instead of abdominal strength.'),
('weighted-leg-raises', 'pt', 'Elevação de pernas com peso', 'Elevação de pernas com carga externa para maior hipertrofia.', 'Aumenta significativamente a resistência e força do abdômen inferior.', 'Segure um peso entre os pés ou use tornozeleiras; eleve as pernas a 90 graus de forma controlada.', 'Mantenha a lombar pressionada contra o chão durante todo o movimento.', 'Evitar se houver fraqueza no core ou dor lombar presente.', 'Balancear o peso usando inércia em vez de força abdominal.'),
('weighted-leg-raises', 'fr', 'Relevé de jambes lesté', 'Relevé de jambes avec charge externe pour une hypertrophie accrue.', 'Augmente significativement la résistance et la force de la sangle abdominale inférieure.', 'Maintenez un poids entre vos pieds ou utilisez des poids de cheville ; levez les jambes à 90 degrés de manière contrôlée.', 'Gardez le bas du dos plaqué au sol tout au long du mouvement.', 'À éviter en cas de faiblesse du core ou de douleur lombaire.', 'Balancer le poids avec de l''élan au lieu de la force abdominale.'),
('weighted-leg-raises', 'de', 'Beinheben mit Gewicht', 'Beinheben mit externem Widerstand für gesteigerte Hypertrophie.', 'Erhöht signifikant die Ausdauer und Kraft der unteren Bauchmuskulatur.', 'Halte ein Gewicht zwischen den Füßen oder trage Gewichtsmanschetten; hebe die Beine kontrolliert bis 90 Grad.', 'Halte die Lendenwirbelsäule während der gesamten Bewegung fest auf dem Boden.', 'Bei Rumpfschwäche oder Rückenschmerzen vermeiden.', 'Das Gewicht durch Schwung bewegen, anstatt durch Bauchmuskelkraft.'),
('weighted-leg-raises', 'it', 'Sollevamento gambe con peso', 'Sollevamento delle gambe con carico esterno per una maggiore ipertrofia.', 'Aumenta significativamente la resistenza e la forza dell''addome inferiore.', 'Tieni un peso tra i piedi o usa cavigliere; solleva le gambe a 90 gradi in modo controllato.', 'Mantieni la zona lombare premuta al suolo per tutto il movimento.', 'Evitare in caso di debolezza del core o dolore lombare.', 'Oscillare il peso usando l''inerzia anziché la forza addominale.'),
('weighted-leg-raises', 'zh', '负重腿举', '添加外部负荷（哑铃或踝部重量）的腿举，以增加肥大效果。', '显著增加下腹部的耐力和力量。', '在双脚间夹住重物或佩戴踝部负重；受控地将双腿抬起至90度。', '在整个过程中保持下背部贴地。', '如有核心薄弱或腰痛，请避免使用。', '利用惯性摆动重物，而不是使用腹肌力量。'),
('weighted-leg-raises', 'ja', '加重レッグレイズ', '外部負荷（ダンベルやアンクルウェイト）を追加したレッグレイズ。', '下腹部の持久力と筋力を大幅に向上させます。', '足の間に重りを持つかアンクルウェイトを使い、コントロールしながら脚を90度まで上げます。', '動作中ずっと腰を床に押し付けてください。', 'コアの筋力が弱い場合や腰痛がある場合は避けてください。', '腹筋の力ではなく、反動を使って重りを振ること。'),
('weighted-leg-raises', 'ko', '웨이티드 레그 레이즈', '외부 부하(덤벨 또는 발목 무게)를 추가한 레그 레이즈.', '하복부의 지구력과 근력을 크게 향상.', '발 사이에 무게를 두거나 발목 무게를 사용해 조절하며 90도까지 다리를 들어 올림.', '동작 내내 허리를 바닥에 밀착할 것.', '코어 근력이 약하거나 요통이 있다면 피할 것.', '복근 대신 반동을 사용하여 무게를 휘두르는 것.'),
('weighted-leg-raises', 'ar', 'رفع الأرجل مع وزن', 'رفع الأرجل مع إضافة حمل خارجي لزيادة الضخامة العضلية.', 'يزيد بشكل كبير من مقاومة وقوة عضلات البطن السفلية.', 'امسك وزناً بين قدميك أو استخدم أوزان الكاحل؛ ارفع ساقيك إلى 90 درجة بتحكم.', 'حافظ على ضغط فقرات أسفل الظهر على الأرض طوال الحركة.', 'تجنب التمرين في حالة ضعف الجذع أو وجود آلام أسفل الظهر.', 'أرجحة الوزن باستخدام الزخم بدلاً من قوة عضلات البطن.'),
('weighted-leg-raises', 'hi', 'वेटेड लेग रेज', 'हाइपरट्रॉफी बढ़ाने के लिए बाहरी भार (डंबल या एंकल वेट) के साथ लेग रेज।', 'निचले पेट की सहनशक्ति और ताकत को काफी बढ़ाता है।', 'पैरों के बीच वजन पकड़ें या एंकल वेट पहनें; पैरों को नियंत्रित तरीके से 90 डिग्री तक उठाएं।', 'पूरी गति के दौरान पीठ के निचले हिस्से को फर्श पर दबाए रखें।', 'यदि कोर कमजोर हो या पीठ दर्द हो तो न करें।', 'पेट की मांसपेशियों के बजाय गति का उपयोग करके वजन को हिलाना।'),
('weighted-leg-raises', 'ru', 'Подъем ног с отягощением', 'Подъем ног с внешним весом для увеличения гипертрофии.', 'Значительно увеличивает выносливость и силу нижней части живота.', 'Зажмите вес между стоп или используйте утяжелители; поднимите ноги на 90 градусов под контролем.', 'Держите поясницу прижатой к полу на протяжении всего движения.', 'Избегайте при слабости кора или болях в пояснице.', 'Использование инерции для раскачивания веса вместо силы мышц живота.'),
('weighted-leg-raises', 'nl', 'Gewogen leg raises', 'Leg raises met externe belasting voor meer hypertrofie.', 'Verhoogt aanzienlijk het uithoudingsvermogen en de kracht van de onderbuik.', 'Houd een gewicht tussen de voeten of gebruik enkelgewichten; til de benen gecontroleerd op tot 90 graden.', 'Houd de onderrug gedurende de hele beweging tegen de vloer gedrukt.', 'Vermijden bij core-zwakte of rugpijn.', 'Het gewicht laten zwaaien met momentum in plaats van buikspierkracht.'),
('weighted-leg-raises', 'sv', 'Viktad benlyft', 'Benlyft med extern belastning för ökad hypertrofi.', 'Ökar avsevärt uthålligheten och styrkan i nedre magen.', 'Håll en vikt mellan fötterna eller använd ankelvikter; lyft benen kontrollerat till 90 grader.', 'Håll ländryggen pressad mot golvet under hela rörelsen.', 'Undvik vid bålsvaghet eller ryggsmärta.', 'Att svinga vikten med momentum istället för magmuskelkraft.'),
('weighted-leg-raises', 'pl', 'Unoszenie nóg z obciążeniem', 'Unoszenie nóg z zewnętrznym obciążeniem dla zwiększenia hipertrofii.', 'Znacznie zwiększa wytrzymałość i siłę dolnych partii brzucha.', 'Trzymaj ciężar między stopami lub użyj obciążników na kostki; unoś nogi do 90 stopni w kontrolowany sposób.', 'Dociskaj odcinek lędźwiowy do podłogi przez cały czas trwania ruchu.', 'Unikaj w przypadku słabych mięśni core lub bólu kręgosłupa.', 'Używanie pędu do kołysania ciężarem zamiast siły mięśni brzucha.'),
('weighted-leg-raises', 'id', 'Leg raise dengan beban', 'Leg raise dengan beban eksternal untuk hipertrofi yang lebih besar.', 'Secara signifikan meningkatkan daya tahan dan kekuatan perut bawah.', 'Pegang beban di antara kaki atau gunakan beban pergelangan kaki; angkat kaki ke 90 derajat secara terkontrol.', 'Tekan punggung bawah ke lantai selama seluruh gerakan.', 'Hindari jika ada kelemahan core atau nyeri punggung bawah.', 'Menggunakan momentum untuk mengayunkan beban alih-alih kekuatan otot perut.'),
('weighted-leg-raises', 'bn', 'ওয়েটেড লেগ রেইজ', 'হাইপারট্রফি বাড়ানোর জন্য বাহ্যিক লোডসহ লেগ রেইজ।', 'পেটের নিচের অংশের শক্তি ও সহ্যক্ষমতা উল্লেখযোগ্যভাবে বৃদ্ধি করে।', 'পায়ের মাঝে ওজন ধরুন বা অ্যাঙ্কেল ওয়েট ব্যবহার করুন; নিয়ন্ত্রণ বজায় রেখে পা ৯০ ডিগ্রি পর্যন্ত তুলুন।', 'পুরো চলাচলের সময় পিঠের নিচের অংশ মেঝের সঙ্গে চেপে রাখুন।', 'কোর দুর্বল হলে বা পিঠে ব্যথা থাকলে এটি এড়িয়ে চলুন।', 'পেটের পেশির শক্তির পরিবর্তে গতি ব্যবহার করে ওজন ঘোরানো।'),
('weighted-leg-raises', 'vi', 'Nâng chân có tạ', 'Nâng chân với tải trọng ngoài để tăng cường cơ bắp.', 'Tăng đáng kể sức bền và sức mạnh vùng bụng dưới.', 'Giữ tạ giữa hai chân hoặc dùng tạ đeo cổ chân; nâng chân lên 90 độ một cách có kiểm soát.', 'Luôn giữ lưng dưới ép sát sàn trong suốt chuyển động.', 'Tránh tập nếu core yếu hoặc bị đau lưng.', 'Dùng đà để vung tạ thay vì dùng sức mạnh cơ bụng.'),
('weighted-leg-raises', 'fa', 'بالا آوردن پا با وزنه', 'بالا آوردن پا با وزنه خارجی برای افزایش حجم عضلانی.', 'استقامت و قدرت عضلات زیر شکم را به‌طور قابل‌توجهی افزایش می‌دهد.', 'وزنه را بین پاها بگیرید یا از وزنه مچ پا استفاده کنید؛ پاها را با کنترل تا ۹۰ درجه بالا بیاورید.', 'در تمام طول حرکت کمر را به زمین فشار دهید.', 'در صورت ضعف هسته بدن یا کمردرد از انجام آن خودداری کنید.', 'استفاده از شتاب برای تاب دادن وزنه به‌جای استفاده از قدرت عضلات شکم.');