-- Definición del ejercicio y sus recursos
INSERT INTO exercises (slug, img, video, difficulty) 
VALUES ('abdominal-crunch-machine', 'abdominal-crunch-machine.jpg', 'abdominal-crunch-machine.mp4', 'beginner');

-- Relación: el ejercicio trabaja el grupo muscular 'abdominals'
INSERT INTO exercise_body_target (exercise_slug, body_target_slug) 
VALUES ('abdominal-crunch-machine', 'abdominals');

-- Relación: el ejercicio utiliza la máquina 'abdominal_crunch_machine'
INSERT INTO exercise_machine (exercise_slug, machine_slug) 
VALUES ('abdominal-crunch-machine', 'abdominal_crunch_machine');

-- Relación: alternativa al 'crunch' tradicional
INSERT INTO exercise_alternative (exercise_slug, alternative_slug) 
VALUES ('abdominal-crunch-machine', 'crunch');


-- Información multiidioma
INSERT INTO exercises_info (slug, lang, title, description, benefits, instructions, tips, restrictions, mistakes) VALUES 
('abdominal-crunch-machine', 'es', 'Crunch en máquina', 'Ejercicio de aislamiento para el recto abdominal utilizando una máquina de carga guiada para mayor estabilidad.', 'Seguridad en la ejecución mediante el movimiento guiado.\nFacilita la concentración en la contracción abdominal.\nIdeal para principiantes.', 'Siéntate y ajusta el asiento para que el eje coincida con tu torso.\nSujeta los agarres y realiza la flexión de tronco.\nRegresa lentamente a la posición inicial.', 'Mantén el cuello relajado y evita presionar la barbilla contra el pecho.', 'Evitar si se presentan hernias discales agudas.', 'Utilizar el impulso para mover el peso.\nDespegar la zona lumbar del respaldo.'),
('abdominal-crunch-machine', 'en', 'Abdominal crunch machine', 'Isolation exercise for the rectus abdominis using a fixed-path machine for enhanced stability.', 'Safety in execution through guided movement.\nFacilitates concentration on abdominal contraction.\nIdeal for beginners.', 'Sit and adjust the seat so the pivot point aligns with your torso.\nGrab the handles and perform a trunk flexion.\nReturn slowly to the starting position.', 'Keep your neck relaxed and avoid pressing chin against chest.', 'Avoid if acute disc herniations are present.', 'Using body momentum to move the weight.\nLifting the lower back off the pad.'),
('abdominal-crunch-machine', 'pt', 'Crunch na máquina', 'Exercício de isolamento para o reto abdominal usando uma máquina de carga guiada para maior estabilidade.', 'Segurança na execução através do movimento guiado.\nFacilita a concentração na contração abdominal.\nIdeal para iniciantes.', 'Sente-se e ajuste o assento para que o eixo coincida com o seu tronco.\nSegure as pegas e realize a flexão do tronco.\nRegresse lentamente à posição inicial.', 'Mantenha o pescoço relaxado e evite pressionar o queixo contra o peito.', 'Evitar se houver hérnias discais agudas.', 'Usar o impulso para mover o peso.\nDescolar a zona lombar do apoio.'),
('abdominal-crunch-machine', 'fr', 'Crunch sur machine', 'Exercice d''isolation pour le grand droit utilisant une machine à charge guidée pour une meilleure stabilité.', 'Sécurité d''exécution grâce au mouvement guidé.\nFacilite la concentration sur la contraction abdominale.\nIdéal pour les débutants.', 'Asseyez-vous et réglez le siège pour que l''axe coïncide avec votre buste.\nSaisissez les poignées et effectuez la flexion du buste.\nRevenez lentement à la position initiale.', 'Gardez le cou détendu et évitez de presser le menton contre la poitrine.', 'À éviter en cas de hernie discale aiguë.', 'Utiliser l''élan pour déplacer le poids.\nDécoller la zone lombaire du dossier.'),
('abdominal-crunch-machine', 'de', 'Bauchmuskelmaschine', 'Isolationsübung für den geraden Bauchmuskel an einer geführten Kraftmaschine für mehr Stabilität.', 'Sicherheit bei der Ausführung durch geführte Bewegung.\nErleichtert die Konzentration auf die Bauchkontraktion.\nIdeal für Anfänger.', 'Setzen Sie sich und stellen Sie den Sitz so ein, dass die Achse mit Ihrem Oberkörper übereinstimmt.\nGreifen Sie die Griffe und führen Sie die Rumpfbeuge aus.\nKehren Sie langsam in die Ausgangsposition zurück.', 'Halten Sie den Nacken entspannt und vermeiden Sie es, das Kinn gegen die Brust zu drücken.', 'Bei akuten Bandscheibenvorfällen vermeiden.', 'Schwung verwenden, um das Gewicht zu bewegen.\nDen unteren Rücken vom Polster abheben.'),
('abdominal-crunch-machine', 'it', 'Crunch alla macchina', 'Esercizio di isolamento per il retto addominale che utilizza una macchina a carico guidato per una maggiore stabilità.', 'Sicurezza nell''esecuzione grazie al movimento guidato.\nFacilita la concentrazione sulla contrazione addominale.\nIdeale per i principianti.', 'Siediti e regola il sedile in modo che l''asse coincida con il tuo busto.\nAfferra le maniglie ed esegui la flessione del busto.\nTorna lentamente alla posizione iniziale.', 'Mantieni il collo rilassato ed evita di premere il mento contro il petto.', 'Evitare in presenza di ernie discali acute.', 'Usare lo slancio per muovere il peso.\nStaccare la zona lombare dallo schienale.'),
('abdominal-crunch-machine', 'zh', '腹肌训练机卷腹', '利用导向负荷机器进行腹直肌隔离训练，提供更高稳定性。', '通过导向动作提升安全性。\n有助于集中精力进行腹部收缩。\n非常适合初学者。', '坐好并调整座椅，使旋转轴与躯干对齐。\n握住把手并进行躯干屈曲。\n缓慢回到起始位置。', '保持颈部放松，避免下巴紧压胸部。', '急性椎间盘突出者禁用。', '利用惯性移动重量。\n背部下侧离开靠垫。'),
('abdominal-crunch-machine', 'ja', 'アブドミナルクランチマシン', '安定性を高めるガイド付きマシンを使用した腹直筋の分離運動。', 'ガイド付き動作により安全性が向上。\n腹筋の収縮に集中しやすい。\n初心者にとって理想的。', '座り、回転軸が胴体と合うようにシートを調整します。\nハンドルを握り、胴体を屈曲させます。\nゆっくりと開始位置に戻ります。', '首をリラックスさせ、顎を胸に押し付けないようにします。', '急性椎間板ヘルニアがある場合は避けてください。', '反動を使ってウェイトを動かすこと。\n背中下部をパッドから離すこと。'),
('abdominal-crunch-machine', 'ko', '복근 머신 크런치', '안정성을 높이기 위해 가이드 머신을 사용하는 복직근 고립 운동.', '가이드 동작으로 인한 실행 안전성.\n복부 수축에 집중하기 용이함.\n초보자에게 이상적.', '앉아서 회전축이 몸통과 일치하도록 시트를 조절합니다.\n손잡이를 잡고 몸통을 굴곡시킵니다.\n천천히 시작 위치로 돌아옵니다.', '목을 편안하게 유지하고 턱을 가슴에 압박하지 마세요.', '급성 디스크가 있는 경우 피하세요.', '반동을 사용하여 무게를 이동하는 것.\n허리를 패드에서 떼는 것.'),
('abdominal-crunch-machine', 'ar', 'تمرين البطن بالجهاز', 'تمرين عزل لعضلة البطن المستقيمة باستخدام جهاز مسار ثابت لزيادة الاستقرار.', 'الأمان في الأداء من خلال الحركة الموجهة.\nيسهل التركيز على انقباض عضلات البطن.\nمثالي للمبتدئين.', 'اجلس واضبط المقعد بحيث يتوافق محور الدوران مع جذعك.\nأمسك المقابض وقم بثني الجذع.\nعد ببطء إلى وضع البداية.', 'حافظ على استرخاء رقبتك وتجنب ضغط الذقن على صدرك.', 'تجنب التمرين في حالة وجود انزلاق غضروفي حاد.', 'استخدام زخم الجسم لتحريك الوزن.\nرفع أسفل الظهر عن الوسادة.'),
('abdominal-crunch-machine', 'hi', 'क्रंच मशीन', 'बेहतर स्थिरता के लिए गाइडेड-पाथ मशीन का उपयोग करके रेक्टस एब्डोमिनिस के लिए आइसोलेशन व्यायाम।', 'गाइडेड मूवमेंट के माध्यम से निष्पादन में सुरक्षा।\nपेट के संकुचन पर ध्यान केंद्रित करने में मदद करता है।\nशुरुआती लोगों के लिए आदर्श।', 'बैठें और सीट को समायोजित करें ताकि धुरी आपके धड़ के साथ संरेखित हो।\nहैंडल पकड़ें और ट्रंक फ्लेक्सियन करें।\nधीमी गति से शुरुआती स्थिति में लौटें।', 'अपनी गर्दन को आराम दें और ठुड्डी को छाती पर दबाने से बचें।', 'यदि तीव्र डिस्क हर्नियेशन मौजूद है तो न करें।', 'वजन ले जाने के लिए शरीर की गति का उपयोग करना।\nपैड से पीठ के निचले हिस्से को उठाना।'),
('abdominal-crunch-machine', 'ru', 'Скручивания в тренажере', 'Изолирующее упражнение для прямой мышцы живота с использованием тренажера с фиксированной траекторией для дополнительной стабильности.', 'Безопасность выполнения благодаря направляемому движению.\nОблегчает концентрацию на сокращении мышц пресса.\nИдеально подходит для новичков.', 'Сядьте и отрегулируйте сиденье так, чтобы ось вращения совпадала с вашим торсом.\nВозьмитесь за рукоятки и выполните сгибание корпуса.\nМедленно вернитесь в исходное положение.', 'Держите шею расслабленной и не прижимайте подбородок к груди.', 'Избегайте при острых грыжах межпозвоночных дисков.', 'Использование инерции для перемещения веса.\nОтрыв поясницы от спинки тренажера.'),
('abdominal-crunch-machine', 'nl', 'Abdominal crunch machine', 'Isolatie-oefening voor de rechte buikspier met een machine voor extra stabiliteit.', 'Veiligheid door geleide beweging.\nVergemakkelijkt focus op buikspiercontractie.\nIdeaal voor beginners.', 'Ga zitten en verstel de zitting zodat het draaipunt uitlijnt met je torso.\nPak de handgrepen en voer een rompbuiging uit.\nKeer langzaam terug naar de startpositie.', 'Houd je nek ontspannen en vermijd de kin tegen de borst te drukken.', 'Vermijden bij acute hernia.', 'Lichaamsmomentum gebruiken om het gewicht te verplaatsen.\nDe onderrug van het kussen tillen.'),
('abdominal-crunch-machine', 'sv', 'Abdominal crunch-maskin', 'Isoleringsövning för raka bukmusklerna som använder en maskin med fast bana för ökad stabilitet.', 'Säkerhet i utförandet tack vare styrd rörelse.\nUnderlättar koncentrationen på magkontraktion.\nIdealisk för nybörjare.', 'Sitt ner och justera sätet så att vridpunkten hamnar i linje med din överkropp.\nGreppa handtagen och utför en bålflexion.\nÅtergå långsamt till startpositionen.', 'Håll nacken avslappnad och undvik att pressa hakan mot bröstet.', 'Undvik vid akuta diskbråck.', 'Använd kroppsmomentum för att flytta vikten.\nLyft ländryggen från ryggstödet.'),
('abdominal-crunch-machine', 'pl', 'Maszyna do brzuszków', 'Ćwiczenie izolujące mięsień prosty brzucha, wykorzystujące maszynę prowadzoną dla większej stabilności.', 'Bezpieczeństwo dzięki prowadzonemu ruchowi.\nUłatwia koncentrację na skurczu mięśni brzucha.\nIdealne dla początkujących.', 'Usiądź i wyreguluj siedzisko tak, aby oś obrotu pokrywała się z tułowiem.\nChwyć uchwyty i wykonaj zgięcie tułowia.\nPowoli wróć do pozycji wyjściowej.', 'Utrzymuj rozluźnioną szyję i unikaj dociskania brody do klatki piersiowej.', 'Unikaj w przypadku ostrych przepuklin dysku.', 'Używanie pędu ciała do przesuwania ciężaru.\nOdrywanie odcinka lędźwiowego od oparcia.'),
('abdominal-crunch-machine', 'id', 'Mesin crunch perut', 'Latihan isolasi untuk rektus abdominis menggunakan mesin jalur tetap untuk stabilitas yang ditingkatkan.', 'Keamanan dalam eksekusi melalui gerakan terpandu.\nMemfasilitasi konsentrasi pada kontraksi perut.\nIdeal untuk pemula.', 'Duduk dan sesuaikan kursi agar titik poros sejajar dengan batang tubuh Anda.\nPegang pegangan dan lakukan fleksi batang tubuh.\nKembali perlahan ke posisi awal.', 'Jaga leher Anda tetap rileks dan hindari menekan dagu ke dada.', 'Hindari jika ada hernia diskus akut.', 'Menggunakan momentum tubuh untuk memindahkan beban.\nMengangkat punggung bawah dari bantalan.'),
('abdominal-crunch-machine', 'bn', 'অ্যাবডমিনাল ক্রাঞ্চ মেশিন', 'অতিরিক্ত স্থিতিশীলতার জন্য একটি ফিক্সড-পাথ মেশিন ব্যবহার করে রেকটাস অ্যাবডোমিনিস আইসোলেশন ব্যায়াম।', 'গাইডেড মুভমেন্টের মাধ্যমে ব্যায়াম নিরাপদ।\nপেটের সংকোচনের ওপর মনোযোগ দিতে সহজ করে।\nনতুনদের জন্য আদর্শ।', 'বসুন এবং সিট এমনভাবে অ্যাডজাস্ট করুন যাতে পিভট পয়েন্টটি আপনার শরীরের সাথে সারিবদ্ধ থাকে।\nহ্যান্ডেলগুলো ধরুন এবং ট্রাঙ্ক ফ্লেক্সশন করুন।\nধীরে ধীরে শুরুতে ফিরে আসুন।', 'আপনার ঘাড় শিথিল রাখুন এবং চিবুক বুকে চেপে ধরা এড়িয়ে চলুন।', 'তীব্র ডিস্ক হার্নিয়া থাকলে এড়িয়ে চলুন।', 'ওজন সরানোর জন্য শরীরের গতির ব্যবহার।\nপ্যাড থেকে পিঠের নিচের অংশ তোলা।'),
('abdominal-crunch-machine', 'vi', 'Máy tập bụng', 'Bài tập cô lập cơ bụng thẳng sử dụng máy cố định để tăng độ ổn định.', 'An toàn khi tập luyện nhờ chuyển động có hướng dẫn.\nGiúp tập trung tốt hơn vào sự co cơ bụng.\nLý tưởng cho người mới bắt đầu.', 'Ngồi xuống và điều chỉnh ghế sao cho trục quay thẳng hàng với thân người.\nNắm tay cầm và thực hiện gập bụng.\nTrở lại từ từ vị trí ban đầu.', 'Giữ cổ thả lỏng và tránh ép cằm vào ngực.', 'Tránh tập nếu bị thoát vị đĩa đệm cấp tính.', 'Sử dụng đà cơ thể để di chuyển tạ.\nNhấc lưng dưới khỏi đệm tựa.'),
('abdominal-crunch-machine', 'fa', 'دستگاه کرانچ شکم', 'تمرین ایزوله برای عضله راست شکم با استفاده از دستگاه مسیر ثابت برای ثبات بیشتر.', 'ایمنی در اجرا از طریق حرکت هدایت‌شده.\nتمرکز بر انقباض عضلات شکم را تسهیل می‌کند.\nایده‌آل برای مبتدیان.', 'بنشینید و صندلی را طوری تنظیم کنید که نقطه چرخش با تنه شما هم‌تراز باشد.\nدستگیره‌ها را بگیرید و خم شدن تنه را انجام دهید.\nبه آرامی به موقعیت شروع بازگردید.', 'گردن خود را شل نگه دارید و از فشار دادن چانه به قفسه سینه خودداری کنید.', 'در صورت وجود فتق دیسک حاد از انجام آن خودداری کنید.', 'استفاده از تکانه بدن برای جابجایی وزنه.\nبلند کردن کمر از تکیه‌گاه.');