-- Definición del ejercicio y sus recursos
INSERT INTO exercises (slug, img, video, difficulty) 
VALUES ('plank-shoulder-taps', 'plank-shoulder-taps.jpg', 'plank-shoulder-taps.mp4', 'beginner');

-- Relación: el ejercicio trabaja el grupo muscular 'abdominals' (y 'shoulders' si aplica)
INSERT INTO exercise_body_target (exercise_slug, body_target_slug) 
VALUES ('plank-shoulder-taps', 'abdominals');

-- Relación: no requiere máquina, por lo tanto no se inserta en exercise_machine

-- Relación: alternativa al 'plank' tradicional
INSERT INTO exercise_alternative (exercise_slug, alternative_slug) 
VALUES ('plank-shoulder-taps', 'plank');

-- Información multiidioma del ejercicio
-- Información multiidioma del ejercicio
INSERT INTO exercises_info (slug, lang, title, description, benefits, instructions, tips, restrictions, mistakes) VALUES 
('plank-shoulder-taps', 'es', 'Toques de hombros en plancha', 'Ejercicio de estabilidad dinámica que combina la plancha isométrica con toques alternos de hombros.', 'Mejora la estabilidad del core y la fuerza de los hombros.\nDesarrolla el equilibrio corporal.', 'Comienza en posición de plancha alta.\nSin mover la cadera, toca el hombro izquierdo con la mano derecha y viceversa.\nMantén el torso firme durante todo el movimiento.', 'Contrae el abdomen y los glúteos para evitar el balanceo de la cadera.', 'Evitar si hay dolor agudo en las muñecas.', 'Mover la cadera de lado a lado excesivamente.\nRealizar el movimiento muy rápido.'),
('plank-shoulder-taps', 'en', 'Plank shoulder taps', 'Dynamic stability exercise combining isometric plank with alternating shoulder touches.', 'Improves core stability and shoulder strength.\nDevelops body balance.', 'Start in a high plank position.\nWithout moving your hips, touch your left shoulder with your right hand and vice versa.\nKeep your torso firm throughout the movement.', 'Tighten your abdomen and glutes to prevent hip swaying.', 'Avoid if there is acute wrist pain.', 'Moving hips side to side excessively.\nPerforming the movement too quickly.'),
('plank-shoulder-taps', 'pt', 'Toques nos ombros em prancha', 'Exercício de estabilidade dinâmica que combina a prancha isométrica com toques alternados nos ombros.', 'Melhora a estabilidade do core e a força dos ombros.\nDesenvolve o equilíbrio corporal.', 'Comece na posição de prancha alta.\nSem mover a anca, toque no ombro esquerdo com a mão direita e vice-versa.\nMantenha o tronco firme durante todo o movimento.', 'Contraia o abdómen e os glúteos para evitar o balanço da anca.', 'Evitar se houver dor aguda nos pulsos.', 'Mover a anca excessivamente de lado para o lado.\nRealizar o movimento muito rapidamente.'),
('plank-shoulder-taps', 'fr', 'Touche-épaules en planche', 'Exercice de stabilité dynamique combinant la planche isométrique avec des touches d''épaules alternées.', 'Améliore la stabilité du tronc et la force des épaules.\nDéveloppe l''équilibre corporel.', 'Commencez en position de planche haute.\nSans bouger les hanches, touchez l''épaule gauche avec la main droite et vice-versa.\nGardez le buste ferme pendant tout le mouvement.', 'Contractez l''abdomen et les fessiers pour éviter le balancement des hanches.', 'À éviter en cas de douleur aiguë au poignet.', 'Bouger les hanches excessivement de gauche à droite.\nEffectuer le mouvement trop rapidement.'),
('plank-shoulder-taps', 'de', 'Plank Shoulder Taps', 'Dynamische Stabilitätsübung, die eine isometrische Planke mit abwechselndem Schulterberühren kombiniert.', 'Verbessert die Rumpfstabilität und Schulterkraft.\nEntwickelt das Körpergleichgewicht.', 'Starten Sie in einer hohen Plankenposition.\nOhne die Hüfte zu bewegen, berühren Sie die linke Schulter mit der rechten Hand und umgekehrt.\nHalten Sie den Rumpf während der gesamten Bewegung fest.', 'Spannen Sie den Bauch und das Gesäß an, um ein Schaukeln der Hüfte zu verhindern.', 'Bei akuten Handgelenkschmerzen vermeiden.', 'Übermäßiges Bewegen der Hüfte von Seite zu Seite.\nZu schnelles Ausführen der Bewegung.'),
('plank-shoulder-taps', 'it', 'Plank shoulder taps', 'Esercizio di stabilità dinamica che combina il plank isometrico con tocchi alternati alle spalle.', 'Migliora la stabilità del core e la forza delle spalle.\nSviluppa l''equilibrio corporeo.', 'Inizia in posizione di plank alto.\nSenza muovere i fianchi, tocca la spalla sinistra con la mano destra e viceversa.\nMantieni il busto fermo durante tutto il movimento.', 'Contrai l''addome e i glutei per evitare l''oscillazione dei fianchi.', 'Evitare in presenza di dolore acuto ai polsi.', 'Muovere eccessivamente i fianchi da un lato all''altro.\nEseguire il movimento troppo velocemente.'),
('plank-shoulder-taps', 'zh', '平板支撑肩部触碰', '动态稳定性练习，结合了等长平板支撑与交替肩部触碰。', '提高核心稳定性与肩部力量。\n增强身体平衡能力。', '起始于高位平板支撑位置。\n在保持臀部不动的情况下，用右手触碰左肩，反之亦然。\n在整个动作过程中保持躯干紧绷。', '收紧腹部和臀部，防止臀部摇晃。', '手腕有剧痛者禁用。', '臀部过度左右摆动。\n动作速度过快。'),
('plank-shoulder-taps', 'ja', 'プランクショルダータップ', 'アイソメトリックプランクと交互のショルダータッチを組み合わせた動的安定性トレーニング。', '体幹の安定性と肩の強さを向上させます。\n身体のバランス能力を養います。', 'ハイプランクの姿勢から始めます。\n腰を動かさずに、右手で左肩を、左手で右肩をタッチします。\n動作中、胴体をしっかりと固定します。', '腹部と臀部に力を入れ、腰が揺れないようにします。', '手首に激しい痛みがある場合は避けてください。', '腰を左右に大きく動かしすぎること。\n動作を速く行いすぎること。'),
('plank-shoulder-taps', 'ko', '플랭크 숄더 탭', '아이소메트릭 플랭크와 교대 어깨 터치를 결합한 동적 안정성 운동.', '코어 안정성 및 어깨 근력 향상.\n신체 균형 감각 발달.', '하이 플랭크 자세에서 시작합니다.\n골반을 움직이지 않고, 오른손으로 왼쪽 어깨를 터치하고 반대도 수행합니다.\n동작 내내 몸통을 단단하게 유지하세요.', '복부와 둔근에 힘을 주어 골반이 흔들리지 않게 하세요.', '손목에 급성 통증이 있으면 피하세요.', '골반을 과도하게 좌우로 흔드는 것.\n너무 빠르게 동작을 수행하는 것.'),
('plank-shoulder-taps', 'ar', 'تمرين لمس الكتف في وضعية البلانك', 'تمرين ثبات ديناميكي يجمع بين البلانك الثابت ولمس الكتف بالتبادل.', 'تحسين ثبات الجذع وقوة الكتفين.\nتطوير توازن الجسم.', 'ابدأ في وضعية البلانك العالي.\nبدون تحريك الوركين، المس كتفك الأيسر بيدك اليمنى والعكس.\nحافظ على ثبات جذعك طوال الحركة.', 'شد عضلات البطن والأرداف لمنع تأرجح الوركين.', 'تجنب التمرين في حالة وجود ألم حاد في المعصم.', 'تحريك الوركين من جانب إلى آخر بشكل مفرط.\nأداء الحركة بسرعة كبيرة.'),
('plank-shoulder-taps', 'hi', 'प्लैंक शोल्डर टैप्स', 'एक गतिशील स्थिरता व्यायाम जो आइसोमेट्रिक प्लैंक और वैकल्पिक शोल्डर टच को जोड़ता है।', 'कोर स्थिरता और कंधे की ताकत में सुधार करता है।\nशरीर का संतुलन विकसित करता है।', 'हाई प्लैंक स्थिति में शुरू करें।\nकूल्हों को हिलाए बिना, दाएं हाथ से बाएं कंधे को छुएं और इसके विपरीत।\nपूरी गति के दौरान अपने धड़ को स्थिर रखें।', 'कूल्हों को हिलने से रोकने के लिए अपने पेट और ग्लूट्स को कस लें।', 'यदि कलाई में तीव्र दर्द हो तो न करें।', 'कूल्हों को बहुत अधिक इधर-उधर हिलाना।\nगतिविधि को बहुत तेजी से करना。'),
('plank-shoulder-taps', 'ru', 'Касания плеч в планке', 'Упражнение на динамическую стабилизацию, сочетающее статическую планку с попеременными касаниями плеч.', 'Улучшает стабильность кора и силу плеч.\nРазвивает баланс тела.', 'Примите положение высокой планки.\nНе двигая тазом, коснитесь правой рукой левого плеча и наоборот.\nДержите корпус напряженным во время всего движения.', 'Напрягите мышцы пресса и ягодиц, чтобы предотвратить раскачивание таза.', 'Избегайте при острой боли в запястьях.', 'Чрезмерное раскачивание тазом из стороны в сторону.\nСлишком быстрое выполнение упражнения.'),
('plank-shoulder-taps', 'nl', 'Plank shoulder taps', 'Dynamische stabiliteitsoefening die een isometrische plank combineert met afwisselende schoudertikken.', 'Verbetert core-stabiliteit en schouderkracht.\nOntwikkelt lichaamsbalans.', 'Begin in een hoge plankpositie.\nTik zonder je heupen te bewegen met je rechterhand je linkerschouder aan en vice versa.\nHoud je romp stevig tijdens de beweging.', 'Span je buik en bilspieren aan om heupzwiepen te voorkomen.', 'Vermijden bij acute polspijn.', 'Heupen overmatig van links naar rechts bewegen.\nDe beweging te snel uitvoeren.'),
('plank-shoulder-taps', 'sv', 'Plank shoulder taps', 'Dynamisk stabilitetsövning som kombinerar statisk planka med växelvisa axeltouchar.', 'Förbättrar core-stabilitet och axelstyrka.\nUtvecklar kroppsbalans.', 'Börja i en hög plankposition.\nUtan att röra höfterna, rör vänster axel med höger hand och vice versa.\nHåll bålen stadig under hela rörelsen.', 'Spänn magen och sätet för att undvika höftsvaj.', 'Undvik vid akut smärta i handlederna.', 'Att röra höfterna för mycket från sida till sida.\nUtföra rörelsen för snabbt.'),
('plank-shoulder-taps', 'pl', 'Dotykanie ramion w podporze', 'Dynamiczne ćwiczenie stabilizacyjne łączące deskę izometryczną z naprzemiennym dotykaniem ramion.', 'Poprawia stabilność core i siłę ramion.\nRozwija równowagę ciała.', 'Zacznij w pozycji wysokiej deski (podpór).\nNie ruszając biodrami, dotknij lewego ramienia prawą ręką i odwrotnie.\nUtrzymuj tułów napięty przez cały czas.', 'Napnij brzuch i pośladki, aby uniknąć kołysania biodrami.', 'Unikaj w przypadku ostrego bólu nadgarstków.', 'Zbyt duże kołysanie biodrami na boki.\nZbyt szybkie wykonywanie ruchu.'),
('plank-shoulder-taps', 'id', 'Plank shoulder taps', 'Latihan stabilitas dinamis yang menggabungkan plank isometrik dengan sentuhan bahu bergantian.', 'Meningkatkan stabilitas inti dan kekuatan bahu.\nMengembangkan keseimbangan tubuh.', 'Mulai dalam posisi plank tinggi.\nTanpa menggerakkan pinggul, sentuh bahu kiri dengan tangan kanan dan sebaliknya.\nJaga batang tubuh Anda tetap kokoh selama gerakan.', 'Kencangkan perut dan bokong untuk mencegah pinggul bergoyang.', 'Hindari jika ada nyeri pergelangan tangan yang akut.', 'Menggerakkan pinggul dari sisi ke sisi secara berlebihan.\nMelakukan gerakan terlalu cepat.'),
('plank-shoulder-taps', 'bn', 'প্ল্যাঙ্ক শোল্ডার ট্যাপস', 'একটি ডায়নামিক স্ট্যাবিলিটি ব্যায়াম যা আইসোমেট্রিক প্ল্যাঙ্ক এবং অল্টারনেটিং শোল্ডার টাচকে একত্রিত করে।', 'কোর স্ট্যাবিলিটি এবং কাঁধের শক্তি উন্নত করে।\nশরীরের ভারসাম্য বিকাশ করে।', 'হাই প্ল্যাঙ্ক পজিশনে শুরু করুন.\nনিতম্ব না নড়িয়ে, ডান হাত দিয়ে বাম কাঁধ স্পর্শ করুন এবং বিপরীতটি করুন.\nপুরো নড়াচড়ার সময় আপনার শরীর শক্ত রাখুন.', 'নিতম্ব দোলানো এড়াতে আপনার পেট এবং গ্লুটস শক্ত করুন.', 'হাতে তীব্র ব্যথা থাকলে এড়িয়ে চলুন.', 'নিতম্ব খুব বেশি এদিক-ওদিক সরানো.\nখুব দ্রুত ব্যায়াম করা।'),
('plank-shoulder-taps', 'vi', 'Chạm vai ở tư thế plank', 'Bài tập ổn định động kết hợp giữa plank tĩnh và chạm vai luân phiên.', 'Cải thiện sự ổn định của cơ lõi và sức mạnh vai.\nPhát triển sự cân bằng cơ thể.', 'Bắt đầu ở tư thế plank cao.\nKhông di chuyển hông, dùng tay phải chạm vai trái và ngược lại.\nGiữ thân người cố định trong suốt quá trình tập.', 'Gồng bụng và cơ mông để tránh làm hông đung đưa.', 'Tránh tập nếu bị đau cổ tay cấp tính.', 'Lắc hông sang hai bên quá mức.\nThực hiện động tác quá nhanh.'),
('plank-shoulder-taps', 'fa', 'ضربه به شانه در پلانک', 'تمرین ثبات دینامیکی که پلانک ایزومتریک را با لمس متناوب شانه‌ها ترکیب می‌کند.', 'بهبود ثبات هسته و قدرت شانه‌ها.\nتعادل بدن را تقویت می‌کند.', 'در موقعیت پلانک بالا شروع کنید.\nبدون حرکت دادن لگن، با دست راست شانه چپ را لمس کنید و بالعکس.\nدر طول حرکت تنه خود را محکم نگه دارید.', 'شکم و باسن خود را منقبض کنید تا از تکان خوردن لگن جلوگیری شود.', 'در صورت درد حاد مچ دست از انجام آن خودداری کنید.', 'حرکت دادن بیش از حد لگن به طرفین.\nانجام دادن سریع حرکت.');