-- Definición del ejercicio
INSERT OR IGNORE INTO exercises (slug, img, video, difficulty) 
VALUES 
('cable-hip-adduction', 'cable-hip-adduction.jpg', 'cable-hip-adduction.mp4', 'intermediate'),
('adduction-machine', 'adduction-machine.jpg', 'adduction-machine.mp4', 'beginner');

-- Relación de grupo muscular
INSERT OR IGNORE INTO exercise_body_target (exercise_slug, body_target_slug) 
VALUES 
('adduction-machine', 'adductors');

-- Relaciones de alternativas
INSERT OR IGNORE INTO exercise_alternative (exercise_slug, alternative_slug) 
VALUES 
('adduction-machine', 'cable-hip-adduction');

-- Información multiidioma
INSERT OR IGNORE INTO exercises_info (slug, lang, title, description, benefits, instructions, tips, restrictions, mistakes) VALUES 
('adduction-machine', 'es', 'Máquina de aducción', 'Ejercicio en máquina diseñado para aislar los aductores mediante resistencia.', 'Fortalece la cara interna del muslo de forma controlada.', 'Siéntate en la máquina, ajusta el soporte y cierra las piernas contra la resistencia.', 'No utilices impulso; controla el cierre y la apertura.', 'Evitar si hay lesiones agudas en la ingle.', 'Despegar la espalda del respaldo o usar inercia.'),
('adduction-machine', 'en', 'Adduction machine', 'Machine-based exercise designed to isolate adductors using resistance.', 'Strengthens the inner thigh in a controlled manner.', 'Sit in the machine, adjust the pad, and close your legs against the resistance.', 'Do not use momentum; control both closing and opening.', 'Avoid if acute groin injuries exist.', 'Lifting the back off the seat or using momentum.'),
('adduction-machine', 'pt', 'Máquina de adução', 'Exercício em máquina projetado para isolar os adutores por meio de resistência.', 'Fortalece a parte interna da coxa de forma controlada.', 'Sente-se na máquina, ajuste o suporte e feche as pernas contra a resistência.', 'Não use impulso; controle o fechamento e a abertura.', 'Evitar se houver lesões agudas na virilha.', 'Tirar as costas do encosto ou usar inércia.'),
('adduction-machine', 'fr', 'Machine à adduction', 'Exercice sur machine conçu pour isoler les adducteurs grâce à une résistance.', 'Renforce l''intérieur de la cuisse de manière contrôlée.', 'Asseyez-vous sur la machine, ajustez le support et fermez les jambes contre la résistance.', 'N''utilisez pas d''élan ; contrôlez la fermeture et l''ouverture.', 'À éviter en cas de blessures aiguës à l''aine.', 'Décoller le dos du dossier ou utiliser l''inertie.'),
('adduction-machine', 'de', 'Adduktorenmaschine', 'Geräteübung zur isolierten Stärkung der Adduktoren durch Widerstand.', 'Stärkt die Innenseite der Oberschenkel kontrolliert.', 'Hinsetzen, Polster einstellen und die Beine gegen den Widerstand schließen.', 'Keinen Schwung verwenden; das Schließen und Öffnen kontrollieren.', 'Bei akuten Leistenverletzungen vermeiden.', 'Rücken vom Sitz abheben oder Schwung nutzen.'),
('adduction-machine', 'it', 'Macchina per adduzione', 'Esercizio alla macchina progettato per isolare gli adduttori tramite resistenza.', 'Rinforza l''interno coscia in modo controllato.', 'Siediti sulla macchina, regola il supporto e chiudi le gambe contro la resistenza.', 'Non usare slancio; controlla sia la chiusura che l''apertura.', 'Evitare in caso di lesioni acute all''inguine.', 'Staccare la schiena dallo schienale o usare inerzia.'),
('adduction-machine', 'zh', '内收肌训练机', '利用器械进行抗阻训练，专门孤立锻炼内收肌。', '受控地加强大腿内侧。', '坐在器械上，调整支撑垫，双腿用力合拢克服阻力。', '不要借力；控制闭合和打开的过程。', '如有急性腹股沟损伤，请避免。', '背部离开靠背或使用惯性。'),
('adduction-machine', 'ja', 'アダクションマシン', '抵抗を利用して内転筋を分離するように設計されたマシンエクササイズ。', '太ももの内側を制御された方法で強化します。', 'マシンに座り、パッドを調整し、抵抗に抗って脚を閉じます。', '勢いを使わず、閉じる動作と開く動作の両方をコントロールしてください。', '鼠径部に急性損傷がある場合は避けてください。', '背中をシートから浮かせることや、勢いを使うこと。'),
('adduction-machine', 'ko', '어덕션 머신', '저항을 사용하여 내전근을 고립시키는 머신 운동.', '허벅지 안쪽을 안정적으로 강화.', '머신에 앉아 패드를 조절하고 저항을 이겨내며 다리를 모음.', '반동을 쓰지 말고 모으고 벌리는 동작을 통제.', '사타구니 급성 부상 시 피할 것.', '등을 등받이에서 떼거나 반동을 사용하는 것.'),
('adduction-machine', 'ar', 'جهاز التقريب', 'تمرين يعتمد على الجهاز مصمم لعزل المقربات باستخدام المقاومة.', 'يقوي الجزء الداخلي من الفخذ بطريقة محكومة.', 'اجلس على الجهاز، واضبط الدعامة، وأغلق ساقيك ضد المقاومة.', 'لا تستخدم الزخم؛ تحكم في الإغلاق والفتح.', 'تجنب في حالة وجود إصابات حادة في الفخذ.', 'رفع الظهر عن المسند أو استخدام القصور الذاتي.'),
('adduction-machine', 'hi', 'एडक्शन मशीन', 'प्रतिरोध का उपयोग करके एडक्टर्स को अलग करने के लिए डिज़ाइन किया गया मशीन-आधारित व्यायाम।', 'जांघ के भीतरी हिस्से को नियंत्रित तरीके से मजबूत करता है।', 'मशीन में बैठें, पैड समायोजित करें और प्रतिरोध के खिलाफ अपने पैरों को बंद करें।', 'गति (momentum) का उपयोग न करें; बंद करने और खोलने दोनों को नियंत्रित करें।', 'यदि कमर (groin) में तीव्र चोट हो तो न करें।', 'पीठ को सीट से उठाना या झटके का उपयोग करना।'),
('adduction-machine', 'ru', 'Тренажер для сведения ног', 'Упражнение на тренажере для изоляции приводящих мышц с использованием сопротивления.', 'Укрепляет внутреннюю часть бедра под контролем.', 'Сядьте в тренажер, отрегулируйте упоры и сводите ноги, преодолевая сопротивление.', 'Не используйте инерцию; контролируйте движение в обе стороны.', 'Избегайте при острых травмах паха.', 'Отрыв спины от спинки или использование рывков.'),
('adduction-machine', 'nl', 'Adductiemachine', 'Apparaatoefening ontworpen om de adductoren te isoleren met weerstand.', 'Versterkt de binnenkant van het bovenbeen op gecontroleerde wijze.', 'Ga in het apparaat zitten, stel de steun in en sluit de benen tegen de weerstand in.', 'Gebruik geen momentum; controleer het sluiten en openen.', 'Vermijden bij acute liesblessures.', 'Rug van de rugleuning tillen of momentum gebruiken.'),
('adduction-machine', 'sv', 'Adduktormaskin', 'Maskinövning utformad för att isolera adduktorerna med hjälp av motstånd.', 'Stärker insidan av låren på ett kontrollerat sätt.', 'Sätt dig i maskinen, justera stödet och stäng benen mot motståndet.', 'Använd inte momentum; kontrollera stängning och öppning.', 'Undvik vid akuta ljumskskador.', 'Att lyfta ryggen från ryggstödet eller använda sving.'),
('adduction-machine', 'pl', 'Maszyna do przywodzenia', 'Ćwiczenie na maszynie zaprojektowane do izolacji przywodzicieli za pomocą oporu.', 'Wzmacnia wewnętrzną stronę uda w kontrolowany sposób.', 'Usiądź w maszynie, wyreguluj wsporniki i zamykaj nogi, pokonując opór.', 'Nie używaj impetu; kontroluj zamykanie i otwieranie.', 'Unikaj w przypadku ostrych urazów pachwiny.', 'Odrywanie pleców od oparcia lub używanie pędu.'),
('adduction-machine', 'id', 'Adduction machine', 'Latihan berbasis mesin yang dirancang untuk mengisolasi adduktor menggunakan hambatan.', 'Memperkuat paha bagian dalam secara terkontrol.', 'Duduk di mesin, sesuaikan bantalan, dan tutup kaki melawan hambatan.', 'Jangan gunakan momentum; kontrol gerakan menutup dan membuka.', 'Hindari jika ada cedera selangkangan akut.', 'Mengangkat punggung dari kursi atau menggunakan momentum.'),
('adduction-machine', 'bn', 'অ্যাডাকশন মেশিন', 'রেজিস্ট্যান্স ব্যবহার করে অ্যাডাকটর আইসোলেট করার জন্য ডিজাইন করা মেশিন-ভিত্তিক ব্যায়াম।', 'নিয়ন্ত্রিত উপায়ে উরুর ভেতরের অংশ শক্তিশালী করে।', 'মেশিনে বসুন, প্যাড অ্যাডজাস্ট করুন এবং রেজিস্ট্যান্সের বিরুদ্ধে পা বন্ধ করুন।', 'মোমেন্টাম ব্যবহার করবেন না; বন্ধ এবং খোলার সময় নিয়ন্ত্রণ বজায় রাখুন।', 'কুঁচকিতে তীব্র আঘাত থাকলে এটি করবেন না।', 'পিঠ সিট থেকে তোলা বা ঝটকা ব্যবহার করা।'),
('adduction-machine', 'vi', 'Máy tập khép chân', 'Bài tập trên máy giúp cô lập cơ khép nhờ kháng lực.', 'Tăng cường mặt trong đùi một cách có kiểm soát.', 'Ngồi vào máy, điều chỉnh miếng đệm và khép chân lại chống lại lực cản.', 'Không dùng quán tính; kiểm soát động tác khép và mở.', 'Tránh tập nếu bị chấn thương háng cấp tính.', 'Nhấc lưng khỏi ghế hoặc dùng quán tính.'),
('adduction-machine', 'fa', 'تمرين با دستگاه تقريب (اداکشن)', 'تمرين با دستگاه که براي ايزوله کردن عضلات نزديک‌کننده (اداکتورها) با استفاده از مقاومت طراحي شده است.', 'بخش داخلي ران را به صورت کنترل‌شده تقويت مي‌کند.', 'روي دستگاه بنشينيد، پد را تنظيم کنيد و پاها را در برابر مقاومت به هم بچسبانيد.', 'از شتاب استفاده نکنيد؛ بستن و باز کردن را کنترل کنيد.', 'در صورت آسيب حاد کشاله ران انجام ندهيد.', 'جدا کردن کمر از پشتي يا استفاده از ضربه.');