-- 1. Registro
INSERT OR IGNORE INTO exercises (slug, img, video, difficulty) 
VALUES 
('adduction-machine', 'adduction-machine.jpg', 'adduction-machine.mp4', 'beginner'),
('cable-hip-adduction', 'cable-hip-adduction.jpg', 'cable-hip-adduction.mp4', 'intermediate');

-- 2. Relación músculo
INSERT OR IGNORE INTO exercise_body_target (exercise_slug, body_target_slug) 
VALUES 
('cable-hip-adduction', 'adductors');

-- 3. Relación alternativa
INSERT OR IGNORE INTO exercise_alternative (exercise_slug, alternative_slug) 
VALUES 
('cable-hip-adduction', 'adduction-machine');

-- 4. Info multiidioma
INSERT OR IGNORE INTO exercises_info (slug, lang, title, description, benefits, instructions, tips, restrictions, mistakes) VALUES 
('cable-hip-adduction', 'es', 'Aducción de cadera en polea', 'Ejercicio en polea que aísla los aductores moviendo la pierna hacia el centro del cuerpo.', 'Fortalece la cara interna del muslo.', 'De pie junto a la polea, conecta el cable al tobillo cercano y cruza la pierna frente a ti.', 'Mantén el tronco estable usando un apoyo.', 'Evitar si hay dolor de ingle.', 'Usar demasiado impulso con la cadera.'),
('cable-hip-adduction', 'en', 'Cable hip adduction', 'Cable exercise that isolates adductors by moving the leg toward the body midline.', 'Strengthens the inner thigh.', 'Standing next to the cable, attach to the inner ankle and pull across your body.', 'Keep torso stable using a support.', 'Avoid if groin pain exists.', 'Using excessive hip momentum.'),
('cable-hip-adduction', 'pt', 'Adução de quadril na polia', 'Exercício na polia que isola os adutores movendo a perna em direção à linha média do corpo.', 'Fortalece a parte interna da coxa.', 'Em pé ao lado da polia, conecte o cabo ao tornozelo próximo e cruze a perna à sua frente.', 'Mantenha o tronco estável usando um apoio.', 'Evitar se houver dor na virilha.', 'Usar impulso excessivo com o quadril.'),
('cable-hip-adduction', 'fr', 'Adduction de hanche à la poulie', 'Exercice à la poulie qui isole les adducteurs en déplaçant la jambe vers la ligne médiane du corps.', 'Renforce l''intérieur de la cuisse.', 'Debout à côté de la poulie, attachez le câble à la cheville proche et croisez la jambe devant vous.', 'Gardez le buste stable à l''aide d''un appui.', 'À éviter en cas de douleur à l''aine.', 'Utiliser un élan excessif avec la hanche.'),
('cable-hip-adduction', 'de', 'Hüft-Adduktion am Kabelzug', 'Kabelzugübung, die die Adduktoren durch Bewegung des Beins zur Körpermitte isoliert.', 'Stärkt die Oberschenkelinnenseite.', 'Neben dem Kabelzug stehen, das Kabel am nahen Knöchel befestigen und das Bein vor dem Körper kreuzen.', 'Rumpf mithilfe einer Stütze stabil halten.', 'Bei Leistenschmerzen vermeiden.', 'Übermäßigen Schwung aus der Hüfte verwenden.'),
('cable-hip-adduction', 'it', 'Adduzione d''anca ai cavi', 'Esercizio ai cavi che isola gli adduttori muovendo la gamba verso la linea mediana del corpo.', 'Rinforza l''interno coscia.', 'In piedi accanto ai cavi, collega il cavo alla caviglia vicina e incrocia la gamba davanti a te.', 'Mantieni il busto stabile usando un supporto.', 'Evitare in caso di dolore all''inguine.', 'Usare un eccessivo slancio con l''anca.'),
('cable-hip-adduction', 'zh', '绳索髋内收', '绳索练习，通过将腿移向身体中线来孤立锻炼内收肌。', '加强大腿内侧。', '站在绳索旁边，将绳索连接到近侧脚踝，然后将腿交叉到身前。', '使用支撑物保持躯干稳定。', '如有腹股沟疼痛，请避免。', '髋部借力过多。'),
('cable-hip-adduction', 'ja', 'ケーブルヒップアダクション', '脚を体の中心線に向けて動かすことで内転筋を分離するケーブルエクササイズ。', '太ももの内側を強化します。', 'ケーブルの横に立ち、ケーブルを近い方の足首に付け、脚を体の前で交差させます。', 'サポートを使用して体幹を安定させてください。', '鼠径部に痛みがある場合は避けてください。', '股関節の反動を使いすぎること。'),
('cable-hip-adduction', 'ko', '케이블 힙 어덕션', '다리를 몸 중심선으로 움직여 내전근을 고립시키는 케이블 운동.', '허벅지 안쪽 강화.', '케이블 옆에 서서 발목에 케이블을 연결하고 다리를 몸 앞으로 교차.', '지지대를 사용하여 상체를 안정적으로 유지.', '사타구니 통증 시 피할 것.', '고관절 반동을 과도하게 사용.'),
('cable-hip-adduction', 'ar', 'تمرين تقريب الورك بالكابل', 'تمرين بالكابل يعزل المقربات عن طريق تحريك الساق نحو خط منتصف الجسم.', 'يقوي الجزء الداخلي من الفخذ.', 'قف بجانب الكابل، وقم بتوصيل الكابل بالكاحل القريب واقطع ساقك أمامك.', 'حافظ على استقرار الجذع باستخدام دعامة.', 'تجنب في حالة وجود ألم في الفخذ.', 'استخدام زخم مفرط من الورك.'),
('cable-hip-adduction', 'hi', 'केबल हिप एडक्शन', 'केबल व्यायाम जो पैर को शरीर की मध्य रेखा की ओर ले जाकर एडक्टर्स को अलग करता है।', 'जांघ के भीतरी हिस्से को मजबूत करता है।', 'केबल के बगल में खड़े होकर, केबल को पास वाले टखने से जोड़ें और पैर को अपने सामने से क्रॉस करें।', 'सहारे का उपयोग करके धड़ को स्थिर रखें।', 'यदि कमर (groin) में दर्द हो तो न करें।', 'कूल्हे से बहुत अधिक गति (momentum) का उपयोग करना।'),
('cable-hip-adduction', 'ru', 'Приведение бедра на блоке', 'Упражнение на блоке, изолирующее приводящие мышцы путем движения ноги к средней линии тела.', 'Укрепляет внутреннюю часть бедра.', 'Стоя рядом с блоком, прикрепите трос к ближней лодыжке и перекрестите ногу перед собой.', 'Держите корпус стабильным, используя опору.', 'Избегайте при болях в паху.', 'Использование чрезмерной инерции бедра.'),
('cable-hip-adduction', 'nl', 'Cable hip adduction', 'Kabeloefening die de adductoren isoleert door het been naar de middellijn van het lichaam te bewegen.', 'Versterkt de binnenkant van het bovenbeen.', 'Staand naast de kabel, bevestig de kabel aan de dichtstbijzijnde enkel en kruis het been voor je uit.', 'Houd de romp stabiel met behulp van een steun.', 'Vermijden bij liespijn.', 'Overmatig momentum uit de heup gebruiken.'),
('cable-hip-adduction', 'sv', 'Cable hip adduction', 'Kabelövning som isolerar adduktorerna genom att flytta benet mot kroppens mittlinje.', 'Stärker lårets insida.', 'Stå bredvid kabelmaskinen, fäst kabeln vid den närmaste fotleden och korsa benet framför dig.', 'Håll överkroppen stabil med hjälp av ett stöd.', 'Undvik vid ljumsksmärta.', 'Använd för mycket sving från höften.'),
('cable-hip-adduction', 'pl', 'Przywodzenie nogi na wyciągu', 'Ćwiczenie na wyciągu izolujące przywodziciele poprzez ruch nogi w stronę linii środkowej ciała.', 'Wzmacnia wewnętrzną stronę uda.', 'Stojąc przy wyciągu, przypnij linkę do bliższej kostki i krzyżuj nogę przed sobą.', 'Utrzymuj stabilny tułów, korzystając z podparcia.', 'Unikaj w przypadku bólu pachwiny.', 'Używanie nadmiernego impetu z biodra.'),
('cable-hip-adduction', 'id', 'Cable hip adduction', 'Latihan kabel yang mengisolasi adduktor dengan menggerakkan kaki ke arah garis tengah tubuh.', 'Memperkuat paha bagian dalam.', 'Berdiri di samping kabel, pasang kabel ke pergelangan kaki yang dekat dan silangkan kaki di depan Anda.', 'Jaga batang tubuh stabil menggunakan penyangga.', 'Hindari jika ada nyeri selangkangan.', 'Menggunakan momentum pinggul yang berlebihan.'),
('cable-hip-adduction', 'bn', 'কেবল হিপ অ্যাডাকশন', 'কেবল ব্যায়াম যা পা শরীরের মধ্যরেখার দিকে সরিয়ে অ্যাডাকটরকে আইসোলেট করে।', 'উরুর ভেতরের অংশ শক্তিশালী করে।', 'কেবলের পাশে দাঁড়িয়ে, কেবলটি কাছের গোড়ালিতে সংযুক্ত করুন এবং আপনার সামনের দিক দিয়ে পা ক্রস করুন।', 'সাপোর্ট ব্যবহার করে শরীর স্থির রাখুন।', 'কুঁচকিতে ব্যথা থাকলে এটি করবেন না।', 'হিপের অতিরিক্ত মোমেন্টাম ব্যবহার করা।'),
('cable-hip-adduction', 'vi', 'Khép chân với cáp', 'Bài tập với máy cáp giúp cô lập cơ khép bằng cách đưa chân về phía đường giữa cơ thể.', 'Tăng cường cơ mặt trong đùi.', 'Đứng cạnh máy cáp, gắn cáp vào cổ chân gần và bắt chéo chân trước mặt.', 'Giữ thân người ổn định bằng cách tựa vào vật hỗ trợ.', 'Tránh tập nếu bị đau háng.', 'Dùng quán tính hông quá đà.'),
('cable-hip-adduction', 'fa', 'تمرين اداکشن ران با سیم‌کش', 'تمرين با سيم‌کش که عضلات نزديک‌کننده را با حرکت دادن پا به سمت خط وسط بدن ايزوله مي‌کند.', 'بخش داخلي ران را تقويت مي‌کند.', 'در کنار دستگاه بايستيد، سيم‌کش را به مچ پاي نزديک وصل کنيد و پا را از جلوي بدن عبور دهيد.', 'تنه را با استفاده از يک تکيه‌گاه ثابت نگه داريد.', 'در صورت درد کشاله ران انجام ندهيد.', 'استفاده از شتاب بيش از حد لگن.');