-- 1. Registro
INSERT OR IGNORE INTO exercises (slug, img, video, difficulty) 
VALUES 
('band-hip-adduction', 'band-hip-adduction.jpg', 'band-hip-adduction.mp4', 'beginner'),
('lying-adductor-lift', 'lying-adductor-lift.jpg', 'lying-adductor-lift.mp4', 'beginner');

-- 2. Relación músculo
INSERT OR IGNORE INTO exercise_body_target (exercise_slug, body_target_slug) 
VALUES 
('lying-adductor-lift', 'adductors');

-- 3. Relación alternativa
INSERT OR IGNORE INTO exercise_alternative (exercise_slug, alternative_slug) 
VALUES 
('lying-adductor-lift', 'band-hip-adduction');

-- 4. Info multiidioma
INSERT OR IGNORE INTO exercises_info (slug, lang, title, description, benefits, instructions, tips, restrictions, mistakes) VALUES 
('lying-adductor-lift', 'es', 'Elevación de aductor acostado', 'Ejercicio de suelo para aislar los aductores levantando la pierna inferior.', 'Fortalece la cara interna del muslo de forma segura.', 'Tumbado de lado, cruza la pierna superior por delante y levanta la pierna inferior estirada.', 'Haz el movimiento lento y controlado.', 'Evitar si hay dolor agudo de cadera.', 'Balancear el cuerpo o levantar la pierna demasiado rápido.'),
('lying-adductor-lift', 'en', 'Lying adductor lift', 'Floor exercise isolating adductors by lifting the bottom leg.', 'Strengthens the inner thigh safely.', 'Lying on side, cross top leg over and lift the bottom leg while keeping it straight.', 'Perform movement slow and controlled.', 'Avoid if acute hip pain exists.', 'Swinging the body or lifting too fast.'),
('lying-adductor-lift', 'pt', 'Elevação de adutor deitado', 'Exercício de solo para isolar os adutores levantando a perna inferior.', 'Fortalece a parte interna da coxa com segurança.', 'Deitado de lado, cruze a perna superior à frente e levante a perna inferior esticada.', 'Faça o movimento lento e controlado.', 'Evitar se houver dor aguda no quadril.', 'Balançar o corpo ou levantar a perna muito rápido.'),
('lying-adductor-lift', 'fr', 'Élévation d''adducteur couché', 'Exercice au sol pour isoler les adducteurs en levant la jambe inférieure.', 'Renforce l''intérieur de la cuisse en toute sécurité.', 'Allongé sur le côté, croisez la jambe supérieure devant et levez la jambe inférieure tendue.', 'Effectuez le mouvement lentement et avec contrôle.', 'À éviter en cas de douleur aiguë à la hanche.', 'Balancer le corps ou lever la jambe trop rapidement.'),
('lying-adductor-lift', 'de', 'Adduktorenheben im Liegen', 'Bodenübung zur Isolierung der Adduktoren durch Anheben des unteren Beins.', 'Stärkt die Oberschenkelinnenseite sicher.', 'Auf der Seite liegend, das obere Bein vorne abstellen und das untere gestreckte Bein anheben.', 'Bewegung langsam und kontrolliert ausführen.', 'Bei akuten Hüftschmerzen vermeiden.', 'Körper schwingen oder Bein zu schnell anheben.'),
('lying-adductor-lift', 'it', 'Sollevamento adduttore da sdraiato', 'Esercizio a terra per isolare gli adduttori sollevando la gamba inferiore.', 'Rinforza l''interno coscia in modo sicuro.', 'Sdraiato su un fianco, incrocia la gamba superiore davanti e solleva la gamba inferiore tesa.', 'Esegui il movimento in modo lento e controllato.', 'Evitare in caso di dolore acuto all''anca.', 'Oscillare il corpo o sollevare la gamba troppo velocemente.'),
('lying-adductor-lift', 'zh', '侧卧内收肌抬腿', '通过抬起下侧腿来孤立锻炼内收肌的地面练习。', '安全地加强大腿内侧。', '侧卧，将上侧腿交叉放在身前，抬起下侧伸直的腿。', '动作缓慢且受控。', '如有急性髋部疼痛，请避免。', '身体晃动或抬腿速度过快。'),
('lying-adductor-lift', 'ja', 'ライイング・アダクターリフト', '下の脚を持ち上げることで内転筋を分離するフロアエクササイズ。', '太ももの内側を安全に強化します。', '横向きに寝て、上の脚を前に交差させ、下の脚を伸ばしたまま持ち上げます。', 'ゆっくりとコントロールした動作で行ってください。', '股関節に激しい痛みがある場合は避けてください。', '体が揺れることや、脚を速く上げすぎること。'),
('lying-adductor-lift', 'ko', '사이드 라이잉 어덕터 리프트', '아래쪽 다리를 들어 올려 내전근을 고립시키는 바닥 운동.', '허벅지 안쪽을 안전하게 강화.', '옆으로 누워 위쪽 다리를 앞으로 교차하고 아래쪽 다리를 곧게 펴서 들어 올림.', '동작을 느리고 통제하며 수행.', '고관절 통증 시 피할 것.', '몸이 흔들리거나 다리를 너무 빨리 드는 것.'),
('lying-adductor-lift', 'ar', 'رفع المقربات بوضعية الاستلقاء', 'تمرين أرضي لعزل المقربات عن طريق رفع الساق السفلية.', 'يقوي الجزء الداخلي من الفخذ بأمان.', 'استلقِ على جانبك، واقطع الساق العلوية أمامك وارفع الساق السفلية وهي مستقيمة.', 'قم بأداء الحركة ببطء وتحكم.', 'تجنب في حالة وجود ألم حاد في الورك.', 'أرجحة الجسم أو رفع الساق بسرعة كبيرة.'),
('lying-adductor-lift', 'hi', 'लाइंग एडक्टर लिफ्ट', 'फर्श पर किया जाने वाला व्यायाम जो नीचे वाले पैर को उठाकर एडक्टर्स को अलग करता है।', 'जांघ के भीतरी हिस्से को सुरक्षित रूप से मजबूत करता है।', 'करवट लेकर लेटें, ऊपर वाले पैर को आगे क्रॉस करें और नीचे वाले पैर को सीधा रखते हुए ऊपर उठाएं।', 'गति धीमी और नियंत्रित रखें।', 'यदि कूल्हे में तीव्र दर्द हो तो न करें।', 'शरीर को हिलाना या पैर को बहुत तेजी से उठाना।'),
('lying-adductor-lift', 'ru', 'Подъем бедра лежа на боку', 'Упражнение на полу для изоляции приводящих мышц путем подъема нижней ноги.', 'Безопасное укрепление внутренней части бедра.', 'Лежа на боку, перекрестите верхнюю ногу перед собой и поднимите нижнюю прямую ногу.', 'Выполняйте движение медленно и подконтрольно.', 'Избегайте при острых болях в бедре.', 'Раскачивание корпуса или слишком быстрый подъем ноги.'),
('lying-adductor-lift', 'nl', 'Lying adductor lift', 'Grondoefening die de adductoren isoleert door het onderste been op te tillen.', 'Versterkt de binnenkant van het bovenbeen op een veilige manier.', 'Liggend op de zij, kruis het bovenste been naar voren en til het onderste been gestrekt op.', 'Voer de beweging langzaam en gecontroleerd uit.', 'Vermijden bij acute heuppijn.', 'Het lichaam zwaaien of het been te snel optillen.'),
('lying-adductor-lift', 'sv', 'Liggande adduktorlyft', 'Golvövning som isolerar adduktorerna genom att lyfta det understa benet.', 'Stärker lårets insida på ett säkert sätt.', 'Ligg på sidan, korsa det övre benet framför och lyft det undre raka benet.', 'Utför rörelsen långsamt och kontrollerat.', 'Undvik vid akut höftsmärta.', 'Att gunga med kroppen eller lyfta benet för snabbt.'),
('lying-adductor-lift', 'pl', 'Unoszenie nogi na adduktory w leżeniu', 'Ćwiczenie na podłodze izolujące przywodziciele poprzez unoszenie dolnej nogi.', 'Bezpieczne wzmacnianie wewnętrznej strony uda.', 'Leżąc na boku, przełóż górną nogę do przodu i unoś dolną wyprostowaną nogę.', 'Wykonuj ruch powoli i w sposób kontrolowany.', 'Unikaj w przypadku ostrego bólu biodra.', 'Kołysanie ciałem lub zbyt szybkie unoszenie nogi.'),
('lying-adductor-lift', 'id', 'Lying adductor lift', 'Latihan lantai yang mengisolasi adduktor dengan mengangkat kaki bawah.', 'Memperkuat paha bagian dalam dengan aman.', 'Berbaring miring, silangkan kaki atas ke depan dan angkat kaki bawah sambil menjaganya tetap lurus.', 'Lakukan gerakan secara perlahan dan terkontrol.', 'Hindari jika ada nyeri pinggul akut.', 'Mengayunkan tubuh atau mengangkat kaki terlalu cepat.'),
('lying-adductor-lift', 'bn', 'লায়িং অ্যাডাকটর লিফট', 'নিচের পা ওপরে তোলার মাধ্যমে অ্যাডাকটর আইসোলেট করার ফ্লোর ব্যায়াম।', 'নিরাপদভাবে উরুর ভেতরের অংশ শক্তিশালী করে।', 'কাত হয়ে শুয়ে, ওপরের পা সামনে ক্রস করুন এবং নিচের সোজা পা ওপরে তুলুন।', 'ধীর এবং নিয়ন্ত্রিত মুভমেন্ট বজায় রাখুন।', 'হিপে তীব্র ব্যথা থাকলে এটি করবেন না।', 'শরীর দোলানো বা পা খুব দ্রুত ওপরে তোলা।'),
('lying-adductor-lift', 'vi', 'Nằm nghiêng nhấc chân dưới', 'Bài tập trên sàn giúp cô lập cơ khép bằng cách nhấc chân dưới.', 'Tăng cường mặt trong đùi một cách an toàn.', 'Nằm nghiêng, vắt chân trên ra trước và nhấc chân dưới lên trong khi giữ thẳng.', 'Thực hiện động tác chậm và có kiểm soát.', 'Tránh tập nếu bị đau hông cấp tính.', 'Lắc lư cơ thể hoặc nhấc chân quá nhanh.'),
('lying-adductor-lift', 'fa', 'تمرين بالا آوردن اداکتور در حالت خوابیده', 'تمرين روي زمين براي ايزوله کردن عضلات نزديک‌کننده با بلند کردن پاي پاييني.', 'بخش داخلي ران را به صورت ايمن تقويت مي‌کند.', 'به پهلو دراز بکشيد، پاي بالايي را از جلو ضربدري قرار دهيد و پاي پاييني را صاف بالا بياوريد.', 'حرکت را آرام و کنترل‌شده انجام دهيد.', 'در صورت درد شديد لگن انجام ندهيد.', 'تکان دادن بدن يا بالا آوردن خيلي سريع پا.');