-- Definición del ejercicio y sus recursos
INSERT OR IGNORE INTO exercises (slug, img, video, difficulty) 
VALUES ('arch-body-hold', 'arch-body-hold.jpg', 'arch-body-hold.mp4', 'intermediate');

-- Relación: el ejercicio trabaja el grupo muscular 'lower-back'
INSERT OR IGNORE INTO exercise_body_target (exercise_slug, body_target_slug) 
VALUES ('arch-body-hold', 'lower_back');

-- Relación: no requiere máquina, por lo tanto no se inserta en exercise_machine
INSERT OR IGNORE INTO exercise_alternative (exercise_slug, alternative_slug) 
VALUES ('arch-body-hold', 'superman');

-- Información multiidioma del ejercicio
INSERT OR IGNORE INTO exercises_info (slug, lang, title, description, benefits, instructions, tips, restrictions, mistakes) VALUES 
('arch-body-hold', 'es', 'Sostén en arco (Arch Body Hold)', 'Ejercicio de estabilidad isométrica que fortalece la cadena posterior y la zona lumbar.', 'Fortalece la espalda baja, glúteos y mejora la postura.', 'Acuéstate boca abajo, eleva simultáneamente brazos y piernas manteniéndolos rectos.', 'Mantén la mirada hacia el suelo para proteger el cuello.', 'Evitar si hay lesiones graves en la columna vertebral.', 'Levantar demasiado el cuello forzando las cervicales.\nDoblar las rodillas.'),
('arch-body-hold', 'en', 'Arch body hold', 'Isometric stability exercise that strengthens the posterior chain and lower back.', 'Strengthens the lower back, glutes, and improves posture.', 'Lie face down, simultaneously lift arms and legs while keeping them straight.', 'Keep your gaze towards the floor to protect your neck.', 'Avoid if there are serious spinal injuries.', 'Lifting the neck too high, straining the cervical spine.\nBending the knees.'),
('arch-body-hold', 'pt', 'Sustentação em arco', 'Exercício de estabilidade isométrica que fortalece a cadeia posterior e a zona lombar.', 'Fortalece a zona lombar, glúteos e melhora a postura.', 'Deite-se de barriga para baixo, eleve simultaneamente braços e pernas mantendo-os retos.', 'Mantenha o olhar para o chão para proteger o pescoço.', 'Evitar se houver lesões graves na coluna vertebral.', 'Levantar demasiado o pescoço forçando as cervicais.\nDobrar os joelhos.'),
('arch-body-hold', 'fr', 'Maintien en arc (Arch body hold)', 'Exercice de stabilité isométrique renforçant la chaîne postérieure et le bas du dos.', 'Renforce le bas du dos, les fessiers et améliore la posture.', 'Allongez-vous sur le ventre, levez simultanément les bras et les jambes en les gardant tendus.', 'Gardez le regard vers le sol pour protéger le cou.', 'À éviter en cas de lésions graves de la colonne vertébrale.', 'Lever le cou trop haut en forçant sur les cervicales.\nPlier les genoux.'),
('arch-body-hold', 'de', 'Bogenhalt (Arch body hold)', 'Isometrische Stabilitätsübung, die die hintere Kette und den unteren Rücken stärkt.', 'Stärkt den unteren Rücken, das Gesäß und verbessert die Körperhaltung.', 'Legen Sie sich auf den Bauch und heben Sie gleichzeitig Arme und Beine, wobei Sie diese gestreckt halten.', 'Halten Sie den Blick zum Boden, um den Nacken zu schützen.', 'Bei schweren Wirbelsäulenverletzungen vermeiden.', 'Den Nacken zu hoch heben und die Halswirbelsäule belasten.\nDie Knie beugen.'),
('arch-body-hold', 'it', 'Sostegno in arco (Arch body hold)', 'Esercizio di stabilità isometrica che rinforza la catena posteriore e la zona lombare.', 'Rinforza la parte bassa della schiena, i glutei e migliora la postura.', 'Sdraiati a pancia in giù, solleva simultaneamente braccia e gambe mantenendole tese.', 'Mantieni lo sguardo verso il pavimento per proteggere il collo.', 'Evitare in caso di gravi lesioni alla colonna vertebrale.', 'Sollevare troppo il collo sforzando le cervicali.\nFlettere le ginocchia.'),
('arch-body-hold', 'zh', '弓形保持', '等长稳定性练习，增强后侧链和下背部。', '增强下背部、臀部并改善姿势。', '俯卧，同时抬起双臂和双腿，保持伸直。', '视线朝向地板以保护颈部。', '如有严重脊柱损伤，请避免使用。', '过度抬起颈部拉伤颈椎。\n弯曲膝盖。'),
('arch-body-hold', 'ja', 'アーチボディホールド', '後側連鎖と腰部を強化する等尺性安定化エクササイズ。', '腰部と臀部を強化し、姿勢を改善します。', 'うつ伏せになり、腕と脚を伸ばしたまま同時に持ち上げます。', '首を守るため、視線は床に向けます。', '脊椎に深刻な怪我がある場合は避けてください。', '首を上げすぎて頚椎に負担をかけること。\n膝を曲げること。'),
('arch-body-hold', 'ko', '아치 바디 홀드', '후면 사슬과 허리를 강화하는 등척성 안정화 운동.', '허리와 둔근을 강화하고 자세를 교정합니다.', '엎드린 상태에서 팔과 다리를 곧게 펴고 동시에 들어 올립니다.', '목 보호를 위해 시선은 바닥을 향하세요.', '척추에 심각한 부상이 있다면 피하세요.', '목을 너무 높이 들어 경추에 무리를 주는 것.\n무릎을 굽히는 것.'),
('arch-body-hold', 'ar', 'تمرين البقاء في وضع القوس', 'تمرين ثبات متساوي القياس يقوي السلسلة الخلفية وأسفل الظهر.', 'يقوي أسفل الظهر والأرداف ويحسن القوام.', 'استلقِ على بطنك، وارفع ذراعيك وساقيك في وقت واحد مع إبقائهما مستقيمتين.', 'حافظ على نظرك نحو الأرض لحماية رقبتك.', 'تجنب التمرين في حالة وجود إصابات خطيرة في العمود الفقري.', 'رفع الرقبة عاليًا جدًا والضغط على الفقرات العنقية.\nثني الركبتين.'),
('arch-body-hold', 'hi', 'आर्च बॉडी होल्ड', 'आइसोमेट्रिक स्थिरता व्यायाम जो पिछली श्रृंखला और पीठ के निचले हिस्से को मजबूत करता है।', 'पीठ के निचले हिस्से और ग्लूट्स को मजबूत करता है और मुद्रा में सुधार करता है।', 'पेट के बल लेट जाएं, बाजुओं और पैरों को सीधा रखते हुए एक साथ उठाएं।', 'गर्दन की सुरक्षा के लिए फर्श की ओर देखें।', 'यदि रीढ़ की हड्डी में गंभीर चोट हो तो न करें।', 'गर्दन को बहुत ऊपर उठाना जिससे सर्वाइकल पर दबाव पड़े।\nघुटने मोड़ना।'),
('arch-body-hold', 'ru', 'Удержание дуги (Arch body hold)', 'Упражнение на изометрическую стабильность, укрепляющее заднюю цепь мышц и поясницу.', 'Укрепляет поясницу, ягодицы и улучшает осанку.', 'Лягте на живот, одновременно поднимите прямые руки и ноги.', 'Смотрите в пол для защиты шеи.', 'Избегайте при серьезных травмах позвоночника.', 'Слишком высокий подъем шеи с нагрузкой на шейный отдел.\nСгибание коленей.'),
('arch-body-hold', 'nl', 'Arch body hold', 'Isometrische stabiliteitsoefening die de achterste keten en onderrug versterkt.', 'Versterkt de onderrug, billen en verbetert de houding.', 'Ga op je buik liggen en til tegelijkertijd je armen en benen op terwijl je ze gestrekt houdt.', 'Houd je blik op de vloer gericht om je nek te beschermen.', 'Vermijden bij ernstige rugblessures.', 'De nek te hoog optillen en de nekwervels belasten.\nDe knieën buigen.'),
('arch-body-hold', 'sv', 'Arch body hold', 'Isometrisk stabilitetsövning som stärker bakre kedjan och ländryggen.', 'Stärker ländrygg, säte och förbättrar hållningen.', 'Ligg på mage, lyft samtidigt armar och ben medan du håller dem raka.', 'Håll blicken mot golvet för att skydda nacken.', 'Undvik vid allvarliga ryggradsskador.', 'Lyfta nacken för högt och belasta nackkotorna.\nBöja knäna.'),
('arch-body-hold', 'pl', 'Arch body hold', 'Ćwiczenie stabilizacji izometrycznej wzmacniające taśmę tylną i odcinek lędźwiowy.', 'Wzmacnia dół pleców, pośladki i poprawia postawę.', 'Połóż się na brzuchu, jednocześnie unieś wyprostowane ręce i nogi.', 'Utrzymuj wzrok skierowany w podłogę, aby chronić szyję.', 'Unikaj w przypadku poważnych urazów kręgosłupa.', 'Zbyt wysokie unoszenie szyi obciążające kręgi szyjne.\nZginanie kolan.'),
('arch-body-hold', 'id', 'Arch body hold', 'Latihan stabilitas isometrik yang memperkuat rantai posterior dan punggung bawah.', 'Memperkuat punggung bawah, bokong, dan meningkatkan postur.', 'Berbaring tengkurap, angkat lengan dan kaki secara bersamaan sambil tetap lurus.', 'Jaga pandangan ke lantai untuk melindungi leher.', 'Hindari jika ada cedera tulang belakang yang serius.', 'Mengangkat leher terlalu tinggi sehingga membebani leher.\nMenekuk lutut.'),
('arch-body-hold', 'bn', 'আর্চ বডি হোল্ড', 'আইসোমেট্রিক স্টেবিলিটি ব্যায়াম যা পিছনের পেশি এবং পিঠের নিচের অংশকে শক্তিশালী করে।', 'পিঠের নিচের অংশ, গ্লুটসকে শক্তিশালী করে এবং অঙ্গভঙ্গি উন্নত করে।', 'পেট ভরে শুয়ে পড়ুন, হাত ও পা সোজা রেখে একসাথে তুলুন।', 'আপনার ঘাড় রক্ষা করার জন্য মেঝের দিকে তাকান।', 'মেরুদণ্ডে গুরুতর আঘাত থাকলে এড়িয়ে চলুন।', 'ঘাড় খুব উঁচুতে তোলা যা সার্ভিকাল স্পাইনের উপর চাপ সৃষ্টি করে।\nহাঁটু বাঁকানো।'),
('arch-body-hold', 'vi', 'Arch body hold', 'Bài tập ổn định đẳng trường củng cố chuỗi cơ sau và lưng dưới.', 'Tăng cường lưng dưới, cơ mông và cải thiện tư thế.', 'Nằm sấp, nâng đồng thời tay và chân trong khi giữ thẳng.', 'Giữ ánh nhìn xuống sàn để bảo vệ cổ.', 'Tránh tập nếu bị chấn thương cột sống nghiêm trọng.', 'Nâng cổ quá cao gây căng thẳng lên cột sống cổ.\nCo đầu gối.'),
('arch-body-hold', 'fa', 'نگه داشتن بدن در حالت کمان (Arch body hold)', 'تمرین ثبات ایزومتریک که زنجیره خلفی و کمر را تقویت می‌کند.', 'کمر و باسن را تقویت کرده و وضعیت بدنی را بهبود می‌بخشد.', 'روی شکم دراز بکشید، همزمان دست‌ها و پاها را صاف نگه داشته و بلند کنید.', 'برای محافظت از گردن، نگاه خود را به سمت زمین نگه دارید.', 'در صورت آسیب‌های جدی ستون فقرات از انجام آن خودداری کنید.', 'بالا آوردن بیش از حد گردن و فشار به مهره‌های گردنی.\nخم کردن زانوها.');