-- Definición del ejercicio y sus recursos
INSERT INTO exercises (slug, img, video, difficulty) 
VALUES ('bird-dog', 'bird-dog.jpg', 'bird-dog.mp4', 'beginner');

-- Relación: el ejercicio trabaja el grupo muscular 'core'
INSERT INTO exercise_body_target (exercise_slug, body_target_slug) 
VALUES ('bird-dog', 'core');

-- Relación: no requiere máquina
INSERT INTO exercise_alternative (exercise_slug, alternative_slug) 
VALUES ('bird-dog', 'plank');

-- Información multiidioma del ejercicio
INSERT INTO exercises_info (slug, lang, title, description, benefits, instructions, tips, restrictions, mistakes) VALUES 
('bird-dog', 'es', 'Bird dog', 'Ejercicio de estabilidad que mejora el equilibrio, la coordinación y fortalece la zona lumbar y el core.', 'Fortalece la espalda baja y mejora la estabilidad de la columna.', 'En posición de cuatro patas, extiende simultáneamente el brazo y la pierna opuestos.', 'Mantén la columna neutra y evita girar las caderas.', 'Evitar si hay dolor agudo en la zona lumbar.', 'Arquear la espalda excesivamente o elevar demasiado la pierna.'),
('bird-dog', 'en', 'Bird dog', 'Stability exercise that improves balance, coordination, and strengthens the lower back and core.', 'Strengthens the lower back and improves spinal stability.', 'In a quadruped position, simultaneously extend the opposite arm and leg.', 'Keep your spine neutral and avoid rotating your hips.', 'Avoid if there is acute lower back pain.', 'Arching the back excessively or lifting the leg too high.'),
('bird-dog', 'pt', 'Bird dog', 'Exercício de estabilidade que melhora o equilíbrio, a coordenação e fortalece a zona lombar e o core.', 'Fortalece a zona lombar e melhora a estabilidade da coluna.', 'Na posição de quatro apoios, estenda simultaneamente o braço e a perna opostos.', 'Mantenha a coluna neutra e evite rodar as ancas.', 'Evitar se houver dor aguda na zona lombar.', 'Arquear as costas excessivamente ou elevar demasiado a perna.'),
('bird-dog', 'fr', 'Bird dog', 'Exercice de stabilité qui améliore l''équilibre, la coordination et renforce le bas du dos et le tronc.', 'Renforce le bas du dos et améliore la stabilité de la colonne vertébrale.', 'En position à quatre pattes, étendez simultanément le bras et la jambe opposés.', 'Gardez la colonne vertébrale neutre et évitez de pivoter les hanches.', 'À éviter en cas de douleur aiguë au bas du dos.', 'Cambrer le dos excessivement ou lever la jambe trop haut.'),
('bird-dog', 'de', 'Bird Dog', 'Stabilitätsübung zur Verbesserung von Gleichgewicht, Koordination und Stärkung des unteren Rückens und der Körpermitte.', 'Stärkt den unteren Rücken und verbessert die Wirbelsäulenstabilität.', 'Gehen Sie in den Vierfüßlerstand und strecken Sie gleichzeitig den gegenüberliegenden Arm und das gegenüberliegende Bein aus.', 'Halten Sie die Wirbelsäule neutral und vermeiden Sie es, die Hüften zu drehen.', 'Bei akuten Schmerzen im unteren Rücken vermeiden.', 'Übermäßiges Durchbiegen des Rückens oder zu hohes Anheben des Beins.'),
('bird-dog', 'it', 'Bird dog', 'Esercizio di stabilità che migliora l''equilibrio, la coordinazione e rinforza la zona lombare e il core.', 'Rinforza la parte bassa della schiena e migliora la stabilità della colonna vertebrale.', 'In posizione quadrupedica, estendi simultaneamente braccio e gamba opposti.', 'Mantieni la colonna neutra ed evita di ruotare i fianchi.', 'Evitare in caso di dolore acuto alla zona lombare.', 'Inarcare eccessivamente la schiena o sollevare troppo la gamba.'),
('bird-dog', 'zh', 'Bird dog', '稳定性练习，提高平衡、协调性，并增强下背部和核心。', '增强下背部并提高脊柱稳定性。', '四足着地，同时伸展对侧手臂和腿。', '保持脊柱中立，避免旋转臀部。', '如有下背部剧痛，请避免使用。', '过度拱背或抬腿过高。'),
('bird-dog', 'ja', 'バードドッグ', 'バランスと協調性を向上させ、腰部と体幹を強化する安定化エクササイズ。', '腰部を強化し、脊柱の安定性を高めます。', '四つん這いの姿勢から、対角の腕と脚を同時に伸ばします。', '背骨を中立に保ち、腰を捻らないようにします。', '腰に激しい痛みがある場合は避けてください。', '背中を反らしすぎることや、脚を上げすぎること。'),
('bird-dog', 'ko', '버드 독', '균형과 협응력을 향상하고 허리와 코어를 강화하는 안정성 운동.', '허리를 강화하고 척추 안정성을 향상합니다.', '네발기기 자세에서 반대쪽 팔과 다리를 동시에 뻗습니다.', '척추를 중립으로 유지하고 엉덩이가 돌아가지 않게 하세요.', '허리에 급성 통증이 있으면 피하세요.', '허리를 과도하게 젖히거나 다리를 너무 높이 드는 것.'),
('bird-dog', 'ar', 'تمرين بيرد دوج (Bird dog)', 'تمرين استقرار يحسن التوازن والتنسيق ويقوي أسفل الظهر والجذع.', 'يقوي أسفل الظهر ويحسن استقرار العمود الفقري.', 'في وضع الزحف، مد الذراع والساق المتقابلين في وقت واحد.', 'حافظ على استقامة عمودك الفقري وتجنب تدوير الوركين.', 'تجنب التمرين في حالة وجود ألم حاد في أسفل الظهر.', 'تقوس الظهر بشكل مفرط أو رفع الساق عاليًا جدًا.'),
('bird-dog', 'hi', 'बर्ड डॉग', 'स्थिरता व्यायाम जो संतुलन, समन्वय में सुधार करता है और पीठ के निचले हिस्से और कोर को मजबूत करता है।', 'पीठ के निचले हिस्से को मजबूत करता है और रीढ़ की स्थिरता में सुधार करता है।', 'चार पैरों वाली स्थिति में, विपरीत हाथ और पैर को एक साथ सीधा करें।', 'अपनी रीढ़ को तटस्थ रखें और अपने कूल्हों को घुमाने से बचें।', 'यदि पीठ के निचले हिस्से में तीव्र दर्द हो तो न करें।', 'पीठ को अत्यधिक मोड़ना या पैर को बहुत ऊपर उठाना।'),
('bird-dog', 'ru', 'Птица-собака (Bird dog)', 'Упражнение на стабильность, улучшающее баланс, координацию и укрепляющее поясницу и кор.', 'Укрепляет поясницу и улучшает стабильность позвоночника.', 'В положении на четвереньках одновременно вытяните противоположные руку и ногу.', 'Держите позвоночник в нейтральном положении и не разворачивайте бедра.', 'Избегайте при острой боли в пояснице.', 'Чрезмерный прогиб в спине или слишком высокий подъем ноги.'),
('bird-dog', 'nl', 'Bird dog', 'Stabiliteitsoefening die balans, coördinatie en de onderrug en core versterkt.', 'Versterkt de onderrug en verbetert de wervelkolomstabiliteit.', 'Ga op handen en voeten staan en strek tegelijkertijd de tegenovergestelde arm en been uit.', 'Houd je wervelkolom neutraal en voorkom dat je je heupen draait.', 'Vermijden bij acute pijn in de onderrug.', 'De rug overmatig hol trekken of het been te hoog optillen.'),
('bird-dog', 'sv', 'Bird dog', 'Stabilitetsövning som förbättrar balans, koordination och stärker ländryggen och core.', 'Stärker ländryggen och förbättrar ryggradens stabilitet.', 'Stå på alla fyra och sträck samtidigt ut motsatt arm och ben.', 'Håll ryggraden neutral och undvik att vrida höfterna.', 'Undvik vid akut smärta i ländryggen.', 'Att svanka för mycket eller lyfta benet för högt.'),
('bird-dog', 'pl', 'Bird dog', 'Ćwiczenie stabilizujące poprawiające równowagę, koordynację oraz wzmacniające dół pleców i core.', 'Wzmacnia dół pleców i poprawia stabilność kręgosłupa.', 'W pozycji czworaczej wyciągnij jednocześnie przeciwległą rękę i nogę.', 'Utrzymuj kręgosłup w neutralnej pozycji i unikaj skręcania bioder.', 'Unikaj w przypadku ostrego bólu lędźwi.', 'Zbyt mocne wyginanie pleców lub zbyt wysokie unoszenie nogi.'),
('bird-dog', 'id', 'Bird dog', 'Latihan stabilitas yang meningkatkan keseimbangan, koordinasi, dan memperkuat punggung bawah serta inti.', 'Memperkuat punggung bawah dan meningkatkan stabilitas tulang belakang.', 'Dalam posisi merangkak, rentangkan lengan dan kaki yang berlawanan secara bersamaan.', 'Jaga tulang belakang tetap netral dan hindari memutar pinggul.', 'Hindari jika ada nyeri punggung bawah yang akut.', 'Melengkungkan punggung secara berlebihan atau mengangkat kaki terlalu tinggi.'),
('bird-dog', 'bn', 'বার্ড ডগ', 'একটি স্থিতিশীলতা ব্যায়াম যা ভারসাম্য, সমন্বয় উন্নত করে এবং পিঠের নিচের অংশ ও কোর শক্তিশালী করে।', 'পিঠের নিচের অংশ শক্তিশালী করে এবং মেরুদণ্ডের স্থিতিশীলতা উন্নত করে।', 'চার পায়ে হাঁটার পজিশনে, বিপরীত হাত ও পা একসাথে সোজা করুন।', 'আপনার মেরুদণ্ড সোজা রাখুন এবং কোমর ঘোরানো এড়িয়ে চলুন।', 'নিচের পিঠে তীব্র ব্যথা থাকলে এড়িয়ে চলুন।', 'পিঠ অতিরিক্ত বাঁকানো বা পা খুব উঁচুতে তোলা।'),
('bird-dog', 'vi', 'Bird dog', 'Bài tập ổn định cải thiện sự thăng bằng, phối hợp và tăng cường lưng dưới cũng như cơ lõi.', 'Tăng cường lưng dưới và cải thiện độ ổn định của cột sống.', 'Ở tư thế bò, đồng thời duỗi thẳng tay và chân đối diện.', 'Giữ cột sống trung tính và tránh xoay hông.', 'Tránh tập nếu bị đau lưng dưới cấp tính.', 'Võng lưng quá mức hoặc nâng chân quá cao.'),
('bird-dog', 'fa', 'تمرین پرنده-سگ (Bird dog)', 'تمرین ثبات که تعادل و هماهنگی را بهبود می‌بخشد و کمر و هسته را تقویت می‌کند.', 'کمر را تقویت کرده و ثبات ستون فقرات را بهبود می‌بخشد.', 'در وضعیت چهار دست و پا، همزمان دست و پای مخالف را دراز کنید.', 'ستون فقرات خود را خنثی نگه دارید و از چرخش لگن خودداری کنید.', 'در صورت درد حاد در کمر از انجام آن خودداری کنید.', 'قوس دادن بیش از حد به کمر یا بلند کردن بیش از حد پا.');