INSERT INTO body_target_info (slug, lang, title, "desc") VALUES
('abdominals', 'es', 'Abdominales', 'Grupo muscular que comprende el recto abdominal, oblicuos y transverso, fundamentales para la estabilidad del core y la transferencia de fuerza entre el tren superior e inferior.'),
('abdominals', 'en', 'Abdominals', 'Muscular group including the rectus abdominis, obliques, and transverse abdominis, essential for core stability and force transfer between the upper and lower body.'),
('abdominals', 'pt', 'Abdominais', 'Grupo muscular que compreende o reto abdominal, oblíquos e transverso, fundamental para a estabilidade do core e transferência de força entre o tronco superior e inferior.'),
('abdominals', 'fr', 'Abdominaux', 'Groupe musculaire comprenant le grand droit, les obliques et le transverse, essentiel pour la stabilité du tronc et le transfert de force entre le haut et le bas du corps.'),
('abdominals', 'de', 'Bauchmuskeln', 'Muskelgruppe bestehend aus dem geraden Bauchmuskel, den schrägen Bauchmuskeln und dem querverlaufenden Bauchmuskel, die für die Rumpfstabilität und Kraftübertragung unerlässlich ist.'),
('abdominals', 'it', 'Addominali', 'Gruppo muscolare che comprende il retto addominale, gli obliqui e il trasverso, fondamentale per la stabilità del core e il trasferimento di forza tra la parte superiore e inferiore del corpo.'),
('abdominals', 'zh', '腹肌', '包括腹直肌、腹斜肌和腹横肌的肌群，对于核心稳定性以及上下肢之间的力量传导至关重要。'),
('abdominals', 'ja', '腹筋', '腹直筋、腹斜筋、腹横筋を含む筋群で、体幹の安定性と上下肢間の力伝達に不可欠です。'),
('abdominals', 'ko', '복근', '복직근, 복사근, 복횡근을 포함하는 근육군으로, 코어 안정성과 상하체 간의 힘 전달에 필수적입니다.'),
('abdominals', 'ar', 'عضلات البطن', 'مجموعة عضلية تشمل البطن المستقيم والمائل والمستعرض، ضرورية لاستقرار الجذع ونقل القوة بين الجزء العلوي والسفلي من الجسم.'),
('abdominals', 'hi', 'एब्स', 'रेक्टस एब्डोमिनिस, ओब्लिक और ट्रांसवर्स एब्डोमिनिस सहित मांसपेशी समूह, जो कोर स्थिरता और शरीर के ऊपरी और निचले हिस्से के बीच बल हस्तांतरण के लिए आवश्यक हैं।'),
('abdominals', 'ru', 'Пресс', 'Мышечная группа, включающая прямую, косые и поперечную мышцы живота, необходимая для стабильности корпуса и передачи усилия между верхней и нижней частями тела.'),
('abdominals', 'nl', 'Buikspieren', 'Spiergroep bestaande uit de rectus abdominis, schuine buikspieren en de dwarsliggende buikspier, essentieel voor core-stabiliteit en krachtoverdracht tussen het boven- en onderlichaam.'),
('abdominals', 'sv', 'Magemuskler', 'Muskelgrupp som omfattar raka, sneda och tvärgående bukmuskler, avgörande för bålstabilitet och kraftöverföring mellan över- och underkropp.'),
('abdominals', 'pl', 'Mięśnie brzucha', 'Grupa mięśni obejmująca mięsień prosty, skośne i poprzeczny brzucha, kluczowa dla stabilizacji korpusu i przenoszenia siły między górną a dolną częścią ciała.'),
('abdominals', 'id', 'Otot Perut', 'Kelompok otot yang mencakup rektus abdominis, oblik, dan transversus abdominis, penting untuk stabilitas inti dan transfer kekuatan antara tubuh bagian atas dan bawah.'),
('abdominals', 'bn', 'পেটের পেশী', 'রেকটাস অ্যাবডোমিনিস, ওব্লিক এবং ট্রান্সভার্স অ্যাবডোমিনিস সহ পেশী গোষ্ঠী, যা কোরের স্থিতিশীলতা এবং শরীরের উপরের ও নিচের অংশের মধ্যে শক্তি স্থানান্তরের জন্য অপরিহার্য।'),
('abdominals', 'vi', 'Cơ bụng', 'Nhóm cơ bao gồm cơ bụng thẳng, cơ chéo và cơ bụng ngang, thiết yếu cho sự ổn định của phần trung tâm (core) và truyền lực giữa phần trên và phần dưới cơ thể.'),
('abdominals', 'fa', 'عضلات شکم', 'گروه عضلانی شامل عضله راست شکم، مورب و عرضی شکم، که برای ثبات هسته بدن و انتقال نیرو بین بالاتنه و پایین‌تنه ضروری است.');