INSERT INTO body_target_info (slug, lang, title, "desc") VALUES
('abductors', 'es', 'Abductores', 'Grupo muscular situado en la cara externa de la cadera, principalmente el glúteo medio y menor, responsable de la abducción del muslo y la estabilización de la pelvis durante la marcha.'),
('abductors', 'en', 'Abductors', 'Muscular group located on the outer hip, primarily the gluteus medius and minimus, responsible for thigh abduction and pelvic stabilization during gait.'),
('abductors', 'pt', 'Abdutores', 'Grupo muscular localizado na face externa do quadril, principalmente o glúteo médio e mínimo, responsável pela abdução da coxa e estabilização da pélvis durante a marcha.'),
('abductors', 'fr', 'Abducteurs', 'Groupe musculaire situé sur la face externe de la hanche, principalement le moyen et le petit fessier, responsable de l abduction de la cuisse et de la stabilisation du bassin pendant la marche.'),
('abductors', 'de', 'Abduktoren', 'Muskelgruppe an der Außenseite der Hüfte, hauptsächlich der Musculus gluteus medius und minimus, verantwortlich für die Abduktion des Oberschenkels und die Stabilisierung des Beckens beim Gehen.'),
('abductors', 'it', 'Abduttori', 'Gruppo muscolare situato sulla faccia esterna dell anca, principalmente il medio e piccolo gluteo, responsabile dell abduzione della coscia e della stabilizzazione del bacino durante la deambulazione.'),
('abductors', 'zh', '外展肌群', '位于髋关节外侧的肌群，主要包括臀中肌和臀小肌，负责大腿外展并在行走过程中维持骨盆稳定。'),
('abductors', 'ja', '外転筋群', '股関節外側に位置する筋群で、主に中殿筋と小殿筋から成り、大腿の外転および歩行時の骨盤安定化を担います。'),
('abductors', 'ko', '외전근', '고관절 외측에 위치한 근육군으로, 주로 중둔근과 소둔근으로 구성되며, 허벅지 외전과 보행 시 골반 안정화를 담당합니다.'),
('abductors', 'ar', 'العضلات المبعدة', 'مجموعة عضلية تقع على الجانب الخارجي للورك، وبشكل رئيسي العضلة الألوية الوسطى والصغرى، مسؤولة عن إبعاد الفخذ وتثبيت الحوض أثناء المشي.'),
('abductors', 'hi', 'एब्डक्टर्स', 'कूल्हे के बाहरी हिस्से पर स्थित मांसपेशी समूह, मुख्य रूप से ग्लूटियस मेडियस और मिनिमस, जो जांघ के अपहरण और चलने के दौरान श्रोणि के स्थिरीकरण के लिए जिम्मेदार हैं।'),
('abductors', 'ru', 'Отводящие мышцы', 'Группа мышц, расположенная на внешней стороне бедра, преимущественно средняя и малая ягодичные мышцы, отвечающая за отведение бедра и стабилизацию таза при ходьбе.'),
('abductors', 'nl', 'Abductoren', 'Spiergroep aan de buitenzijde van de heup, voornamelijk de gluteus medius en minimus, verantwoordelijk voor de abductie van de dij en de stabilisatie van het bekken tijdens het lopen.'),
('abductors', 'sv', 'Abduktorer', 'Muskelgrupp belägen på höftens utsida, främst gluteus medius och minimus, ansvarig för lårets abduktion och bäckenets stabilisering under gång.'),
('abductors', 'pl', 'Mięśnie odwodziciele', 'Grupa mięśni znajdująca się po zewnętrznej stronie biodra, głównie pośladkowy średni i mały, odpowiedzialna za odwodzenie uda i stabilizację miednicy podczas chodu.'),
('abductors', 'id', 'Abduktor', 'Kelompok otot yang terletak di sisi luar pinggul, terutama gluteus medius dan minimus, yang bertanggung jawab untuk abduksi paha dan stabilisasi panggul saat berjalan.'),
('abductors', 'bn', 'এ্যাডডাক্টর', 'নিতম্বের বাইরের দিকে অবস্থিত পেশী গোষ্ঠী, মূলত গ্লুটিয়াস মিডিয়াস এবং মিনিমাস, যা উরুর এ্যাডডাকশন এবং হাঁটার সময় শ্রোণিকে স্থিতিশীল করার জন্য দায়ী।'),
('abductors', 'vi', 'Cơ khép/dang', 'Nhóm cơ nằm ở mặt ngoài của hông, chủ yếu là cơ mông nhỡ và cơ mông nhỏ, chịu trách nhiệm dang đùi và ổn định khung chậu khi đi bộ.'),
('abductors', 'fa', 'عضلات دورکننده', 'گروه عضلانی واقع در بخش خارجی لگن، عمدتاً عضله سرینی میانی و کوچک، که مسئول دور کردن ران و ثبات لگن در هنگام راه رفتن است.');