INSERT OR IGNORE INTO body_target_info (slug, lang, title, "desc") VALUES
('adductors', 'es', 'Aductores', 'Grupo muscular situado en la cara interna del muslo, incluyendo el pectíneo, aductor largo, corto y mayor, responsables de la aducción de la cadera y la estabilización del fémur.'),
('adductors', 'en', 'Adductors', 'Muscle group located on the inner thigh, including the pectineus, adductor longus, brevis, and magnus, responsible for hip adduction and femur stabilization.'),
('adductors', 'pt', 'Adutores', 'Grupo muscular localizado na parte interna da coxa, incluindo o pectíneo, adutor longo, curto e magno, responsáveis pela adução do quadril e estabilização do fémur.'),
('adductors', 'fr', 'Adducteurs', 'Groupe musculaire situé sur la face interne de la cuisse, comprenant le pectiné, les adducteurs long, court et grand, responsables de l adduction de la hanche et de la stabilisation du fémur.'),
('adductors', 'de', 'Adduktoren', 'Muskelgruppe an der Innenseite des Oberschenkels, einschließlich Musculus pectineus, Musculus adductor longus, brevis und magnus, verantwortlich für die Hüftadduktion und die Stabilisierung des Oberschenkelknochens.'),
('adductors', 'it', 'Adduttori', 'Gruppo muscolare situato sulla parte interna della coscia, che comprende il pettineo, l adduttore lungo, breve e grande, responsabili dell adduzione dell anca e della stabilizzazione del femore.'),
('adductors', 'zh', '内收肌群', '位于大腿内侧的肌群，包括耻骨肌、长收肌、短收肌和大收肌，负责髋关节内收并起到稳定股骨的作用。'),
('adductors', 'ja', '内転筋群', '大腿内側に位置する筋群で、恥骨筋、長内転筋、短内転筋、大内転筋が含まれ、股関節の内転と大腿骨の安定化を担います。'),
('adductors', 'ko', '내전근', '허벅지 안쪽에 위치한 근육군으로, 치골근, 장내전근, 단내전근, 대내전근을 포함하며, 고관절 내전과 대퇴골 안정화를 담당합니다.'),
('adductors', 'ar', 'العضلات المقربة', 'مجموعة عضلية تقع على الجانب الداخلي للفخذ، تشمل العضلة المشطية، والعضلة المقربة الطويلة والقصيرة والكبيرة، وهي مسؤولة عن تقريب الورك وتثبيت عظمة الفخذ.'),
('adductors', 'hi', 'एडक्टर्स', 'जांघ के भीतरी हिस्से में स्थित मांसपेशी समूह, जिसमें पेक्टिनियस, एडक्टर लॉन्गस, ब्रेविस और मैग्नस शामिल हैं, जो कूल्हे के एडक्शन और फीमर के स्थिरीकरण के लिए जिम्मेदार हैं।'),
('adductors', 'ru', 'Приводящие мышцы', 'Группа мышц на внутренней стороне бедра, включая гребенчатую, длинную, короткую и большую приводящие мышцы, отвечающие за приведение бедра и стабилизацию бедренной кости.'),
('adductors', 'nl', 'Adductoren', 'Spiergroep aan de binnenzijde van het bovenbeen, inclusief de musculus pectineus, adductor longus, brevis en magnus, verantwoordelijk voor heupadductie en stabilisatie van het dijbeen.'),
('adductors', 'sv', 'Adduktorer', 'Muskelgrupp på lårts insida, inklusive pectineus, adductor longus, brevis och magnus, ansvarig för höftadduktion och stabilisering av lårbenet.'),
('adductors', 'pl', 'Mięśnie przywodziciele', 'Grupa mięśni po wewnętrznej stronie uda, obejmująca mięsień grzebieniowy, przywodziciel długi, krótki i wielki, odpowiedzialna za przywodzenie biodra i stabilizację kości udowej.'),
('adductors', 'id', 'Adduktor', 'Kelompok otot di paha bagian dalam, termasuk pektineus, adduktor longus, brevis, dan magnus, yang bertanggung jawab untuk adduksi pinggul dan stabilisasi tulang paha.'),
('adductors', 'bn', 'এ্যাডডাক্টর', 'উরুর ভিতরের দিকে অবস্থিত পেশী গোষ্ঠী, যার মধ্যে রয়েছে পেকটিনিয়াস, এ্যাডডাক্টর লঙ্গাস, ব্রেভিস এবং ম্যাগনাস, যা হিপ এ্যাডডাকশন এবং ফিমারের স্থিতিশীলতার জন্য দায়ী।'),
('adductors', 'vi', 'Cơ khép', 'Nhóm cơ nằm ở mặt trong đùi, bao gồm cơ lược, cơ khép dài, ngắn và lớn, chịu trách nhiệm khép hông và ổn định xương đùi.'),
('adductors', 'fa', 'عضلات نزدیک‌کننده', 'گروه عضلانی واقع در بخش داخلی ران، شامل عضله شانه‌ای، نزدیک‌کننده بلند، کوتاه و بزرگ، که مسئول نزدیک کردن لگن و ثبات استخوان ران است.');