INSERT OR IGNORE INTO body_target_info (slug, lang, title, "desc") VALUES
('back', 'es', 'Espalda', 'Estructura muscular posterior que abarca desde la región cervical hasta la lumbar, proporcionando soporte estructural, postura y movilidad al tronco.'),
('back', 'en', 'Back', 'Posterior muscular structure spanning from the cervical to the lumbar region, providing structural support, posture, and trunk mobility.'),
('back', 'pt', 'Costas', 'Estrutura muscular posterior que se estende da região cervical à lombar, fornecendo suporte estrutural, postura e mobilidade ao tronco.'),
('back', 'fr', 'Dos', 'Structure musculaire postérieure s étendant de la région cervicale à la région lombaire, assurant le soutien structurel, la posture et la mobilité du tronc.'),
('back', 'de', 'Rücken', 'Hintere Muskelstruktur, die sich von der Hals- bis zur Lendenwirbelsäule erstreckt und strukturelle Unterstützung, Körperhaltung und Rumpfbeweglichkeit bietet.'),
('back', 'it', 'Schiena', 'Struttura muscolare posteriore che si estende dalla regione cervicale a quella lombare, fornendo supporto strutturale, postura e mobilità al tronco.'),
('back', 'zh', '背部', '从颈部到腰部的后侧肌肉结构，提供结构支撑、姿势维持和躯干灵活性。'),
('back', 'ja', '背中', '頸部から腰部にかけての背面筋群で、構造的なサポート、姿勢の維持、体幹の可動性を提供します。'),
('back', 'ko', '등', '경추에서 요추까지 이어지는 후면 근육 구조로, 구조적 지지, 자세 유지 및 체간의 가동성을 제공합니다.'),
('back', 'ar', 'الظهر', 'هيكل عضلي خلفي يمتد من المنطقة العنقية إلى المنطقة القطنية، ويوفر الدعم الهيكلي والوضعية وحركة الجذع.'),
('back', 'hi', 'पीठ', 'गर्दन से लेकर काठ (लंबर) क्षेत्र तक फैली पिछली मांसपेशी संरचना, जो संरचनात्मक समर्थन, मुद्रा और धड़ की गतिशीलता प्रदान करती है।'),
('back', 'ru', 'Спина', 'Задняя мышечная структура, простирающаяся от шейного до поясничного отдела, обеспечивающая структурную поддержку, осанку и подвижность туловища.'),
('back', 'nl', 'Rug', 'Posterieure spierstructuur die zich uitstrekt van de cervicale tot de lumbale regio, en zorgt voor structurele ondersteuning, houding en rompmobiliteit.'),
('back', 'sv', 'Rygg', 'Posterior muskelstruktur som sträcker sig från nacke till ländrygg, vilket ger strukturellt stöd, hållning och bålrörlighet.'),
('back', 'pl', 'Plecy', 'Tylna struktura mięśniowa rozciągająca się od odcinka szyjnego do lędźwiowego, zapewniająca wsparcie strukturalne, postawę i mobilność tułowia.'),
('back', 'id', 'Punggung', 'Struktur otot posterior yang membentang dari wilayah servikal hingga lumbal, memberikan dukungan struktural, postur, dan mobilitas batang tubuh.'),
('back', 'bn', 'পিঠ', 'ঘাড় থেকে কটিদেশ পর্যন্ত বিস্তৃত পিছনের পেশী কাঠামো, যা কাঠামোগত সমর্থন, ভঙ্গি এবং শরীরের মূল অংশের গতিশীলতা প্রদান করে।'),
('back', 'vi', 'Lưng', 'Cấu trúc cơ phía sau trải dài từ vùng cổ đến vùng thắt lưng, cung cấp hỗ trợ cấu trúc, tư thế và khả năng vận động cho thân mình.'),
('back', 'fa', 'کمر', 'ساختار عضلانی پشتی که از ناحیه گردنی تا کمری امتداد یافته و پشتیبانی ساختاری، وضعیت بدنی و تحرک تنه را فراهم می‌کند.');