INSERT OR IGNORE INTO body_target_info (slug, lang, title, "desc") VALUES
('biceps', 'es', 'Bíceps', 'Músculo de la cara anterior del brazo que consta de dos cabezas (larga y corta); su función principal es la flexión del codo y la supinación del antebrazo.'),
('biceps', 'en', 'Biceps', 'Muscle on the anterior side of the arm consisting of two heads (long and short); its primary function is elbow flexion and forearm supination.'),
('biceps', 'pt', 'Bíceps', 'Músculo da face anterior do braço que consiste em duas cabeças (longa e curta); sua principal função é a flexão do cotovelo e a supinação do antebraço.'),
('biceps', 'fr', 'Biceps', 'Muscle de la face antérieure du bras composé de deux chefs (long et court) ; sa fonction principale est la flexion du coude et la supination de l avant-bras.'),
('biceps', 'de', 'Bizeps', 'Muskel an der Vorderseite des Oberarms, der aus zwei Köpfen (lang und kurz) besteht; seine Hauptfunktion ist die Beugung des Ellenbogens und die Supination des Unterarms.'),
('biceps', 'it', 'Bicipiti', 'Muscolo della faccia anteriore del braccio composto da due capi (lungo e breve); la sua funzione principale è la flessione del gomito e la supinazione dell avambraccio.'),
('biceps', 'zh', '肱二头肌', '上臂前侧肌肉，由长头和短头组成；其主要功能是肘关节屈曲和前臂旋后。'),
('biceps', 'ja', '上腕二頭筋', '上腕前側に位置する筋肉で、長頭と短頭の二つの頭から成ります。主な機能は肘の屈曲と前腕の回外です。'),
('biceps', 'ko', '이두근', '상완 앞쪽에 위치한 근육으로 장두와 단두로 구성됩니다. 주요 기능은 팔꿈치 굴곡과 전완 회외입니다.'),
('biceps', 'ar', 'العضلة ذات الرأسين', 'عضلة تقع في الجزء الأمامي من الذراع تتكون من رأسين (طويل وقصير)؛ وظيفتها الأساسية هي ثني المرفق وبسط الساعد.'),
('biceps', 'hi', 'बाइसेप्स', 'हाथ के सामने की मांसपेशी जो दो सिरों (लंबे और छोटे) से बनी होती है; इसका मुख्य कार्य कोहनी को मोड़ना और अग्रबाहु को सुपीनेशन करना है।'),
('biceps', 'ru', 'Бицепс', 'Мышца передней поверхности плеча, состоящая из двух головок (длинной и короткой); основная функция — сгибание локтя и супинация предплечья.'),
('biceps', 'nl', 'Biceps', 'Spier aan de voorzijde van de bovenarm bestaande uit twee koppen (lang en kort); de primaire functie is elleboogflexie en supinatie van de onderarm.'),
('biceps', 'sv', 'Biceps', 'Muskel på överarmens framsida bestående av två huvuden (långt och kort); dess huvudfunktion är armbågsflexion och underarms supination.'),
('biceps', 'pl', 'Biceps', 'Mięsień przedniej części ramienia składający się z dwóch głów (długiej i krótkiej); jego główną funkcją jest zginanie łokcia i supinacja przedramienia.'),
('biceps', 'id', 'Biceps', 'Otot di sisi anterior lengan yang terdiri dari dua kepala (panjang dan pendek); fungsi utamanya adalah fleksi siku dan supinasi lengan bawah.'),
('biceps', 'bn', 'বাইসেপস', 'হাতের সামনের দিকের পেশী যা দুটি মাথা (লম্বা এবং ছোট) নিয়ে গঠিত; এর প্রধান কাজ হলো কনুই ভাঁজ করা এবং হাতের সামনের অংশ ঘোরানো।'),
('biceps', 'vi', 'Cơ bắp tay', 'Cơ nằm ở mặt trước cánh tay gồm hai đầu (dài và ngắn); chức năng chính là gập khuỷu tay và ngửa cẳng tay.'),
('biceps', 'fa', 'عضله دوسر بازو', 'عضله بخش قدامی بازو متشکل از دو سر (بلند و کوتاه)؛ عملکرد اصلی آن خم کردن آرنج و سوپیناسیون ساعد است.');