INSERT OR IGNORE INTO body_target_info (slug, lang, title, "desc") VALUES
('calves', 'es', 'Pantorrillas', 'Grupo muscular de la parte posterior de la pierna, compuesto principalmente por el gastrocnemio y el sóleo, esenciales para la flexión plantar del pie y la propulsión durante el movimiento.'),
('calves', 'en', 'Calves', 'Muscular group in the back of the lower leg, primarily composed of the gastrocnemius and soleus, essential for plantar flexion of the foot and propulsion during movement.'),
('calves', 'pt', 'Panturrilhas', 'Grupo muscular da parte posterior da perna, composto principalmente pelo gastrocnêmio e sóleo, essenciais para a flexão plantar do pé e propulsão durante o movimento.'),
('calves', 'fr', 'Mollets', 'Groupe musculaire de la partie postérieure de la jambe, composé principalement du gastrocnémien et du soléaire, essentiels pour la flexion plantaire du pied et la propulsion pendant le mouvement.'),
('calves', 'de', 'Waden', 'Muskelgruppe an der Rückseite des Unterschenkels, bestehend hauptsächlich aus dem Gastrocnemius und dem Soleus, die für die Plantarflexion des Fußes und den Vortrieb während der Bewegung unerlässlich sind.'),
('calves', 'it', 'Polpacci', 'Gruppo muscolare della parte posteriore della gamba, composto principalmente dal gastrocnemio e dal soleo, essenziali per la flessione plantare del piede e la propulsione durante il movimento.'),
('calves', 'zh', '小腿肌群', '小腿后侧肌肉群，主要由腓肠肌和比目鱼肌组成，对于脚部跖屈和移动中的动力推进至关重要。'),
('calves', 'ja', 'ふくらはぎ', '下腿後面に位置する筋群で、主に腓腹筋とヒラメ筋から成ります。足の底屈と運動時の推進力に不可欠です。'),
('calves', 'ko', '종아리', '하퇴 후면에 위치한 근육군으로 주로 비복근과 가자미근으로 구성되며, 발의 저측 굴곡과 움직임 시 추진력에 필수적입니다.'),
('calves', 'ar', 'عضلات الساق (بطة الساق)', 'مجموعة عضلية في الجزء الخلفي من أسفل الساق، تتكون بشكل رئيسي من العضلة التوأمية والنعلية، وهي ضرورية لثني القدم للأسفل والدفع أثناء الحركة.'),
('calves', 'hi', 'पिंडलियां', 'निचले पैर के पिछले हिस्से में मांसपेशी समूह, मुख्य रूप से गैस्ट्रोक्नेमियस और सोलियस से बना, जो पैर के प्लांटर फ्लेक्सन और गति के दौरान आगे बढ़ने के लिए आवश्यक है।'),
('calves', 'ru', 'Икры', 'Мышечная группа задней части голени, состоящая преимущественно из икроножной и камбаловидной мышц, необходимая для подошвенного сгибания стопы и толчка при движении.'),
('calves', 'nl', 'Kuiten', 'Spiergroep in het achterste deel van het onderbeen, voornamelijk bestaande uit de gastrocnemius en soleus, essentieel voor plantaire flexie van de voet en voortstuwing tijdens beweging.'),
('calves', 'sv', 'Vader', 'Muskelgrupp på underbenets baksida, främst bestående av gastrocnemius och soleus, avgörande för fotens plantarflexion och framdrivning under rörelse.'),
('calves', 'pl', 'Łydki', 'Grupa mięśni tylnej części podudzia, składająca się głównie z mięśnia brzuchatego i płaszczkowatego, niezbędna do zginania podeszwowego stopy i napędu podczas ruchu.'),
('calves', 'id', 'Betis', 'Kelompok otot di bagian belakang kaki bawah, terutama terdiri dari gastrocnemius dan soleus, penting untuk fleksi plantar kaki dan propulsi selama bergerak.'),
('calves', 'bn', 'পায়ের ডিম (কাফ)', 'পায়ের নিচের অংশের পিছনের পেশী গোষ্ঠী, মূলত গ্যাস্ট্রোকনেমিয়াস এবং সোলিয়াস নিয়ে গঠিত, যা পায়ের পাতা বাঁকানো এবং নড়াচড়ার সময় এগিয়ে যাওয়ার জন্য অপরিহার্য।'),
('calves', 'vi', 'Cơ bắp chân', 'Nhóm cơ phía sau cẳng chân, chủ yếu gồm cơ bụng chân và cơ dép, thiết yếu cho việc gập bàn chân về phía lòng bàn chân và tạo lực đẩy khi di chuyển.'),
('calves', 'fa', 'عضلات ساق پا', 'گروه عضلانی در بخش پشتی ساق پا، متشکل از عضلات دوقلو و نعلی، که برای خم کردن کف پایی و ایجاد پیش‌رانش در حین حرکت ضروری است.');