INSERT INTO body_target_info (slug, lang, title, "desc") VALUES
('chest', 'es', 'Pecho', 'Grupo muscular situado en la parte anterior del torso, formado principalmente por el pectoral mayor y menor, esencial para movimientos de empuje y aducción del brazo.'),
('chest', 'en', 'Chest', 'Muscular group located on the anterior torso, primarily composed of the pectoralis major and minor, essential for pushing movements and arm adduction.'),
('chest', 'pt', 'Peito', 'Grupo muscular localizado na parte anterior do tronco, formado principalmente pelo peitoral maior e menor, essencial para movimentos de empurrar e adução do braço.'),
('chest', 'fr', 'Poitrine', 'Groupe musculaire situé sur la partie antérieure du torse, formé principalement par le grand et le petit pectoral, essentiel pour les mouvements de poussée et l adduction du bras.'),
('chest', 'de', 'Brust', 'Muskelgruppe an der Vorderseite des Oberkörpers, hauptsächlich bestehend aus dem Musculus pectoralis major und minor, die für Druckbewegungen und die Adduktion des Arms unerlässlich ist.'),
('chest', 'it', 'Petto', 'Gruppo muscolare situato nella parte anteriore del torace, formato principalmente dal grande e piccolo pettorale, essenziale per i movimenti di spinta e l adduzione del braccio.'),
('chest', 'zh', '胸部', '位于躯干前侧的肌群，主要由胸大肌和胸小肌组成，对于推举动作和手臂内收至关重要。'),
('chest', 'ja', '胸部', '胴体前部に位置する筋群で、主に大胸筋と小胸筋から成り、押す動作や腕の内転に不可欠です。'),
('chest', 'ko', '가슴', '몸통 앞쪽에 위치한 근육군으로 주로 대흉근과 소흉근으로 구성되며, 미는 동작과 팔의 내전 동작에 필수적입니다.'),
('chest', 'ar', 'الصدر', 'مجموعة عضلية تقع في الجزء الأمامي من الجذع، تتكون بشكل رئيسي من العضلة الصدرية الكبرى والصغرى، وهي ضرورية لحركات الدفع وتقريب الذراع.'),
('chest', 'hi', 'छाती', 'धड़ के सामने स्थित मांसपेशी समूह, मुख्य रूप से पेक्टोरलिस मेजर और माइनर से बना, जो धक्का देने वाले मूवमेंट और हाथ के एडक्शन के लिए आवश्यक है।'),
('chest', 'ru', 'Грудь', 'Мышечная группа, расположенная на передней части торса, состоящая преимущественно из большой и малой грудных мышц, необходимая для жимовых движений и приведения руки.'),
('chest', 'nl', 'Borst', 'Spiergroep aan de voorzijde van de romp, voornamelijk bestaande uit de pectoralis major en minor, essentieel voor duwbewegingen en adductie van de arm.'),
('chest', 'sv', 'Bröst', 'Muskelgrupp belägen på bålens framsida, främst bestående av pectoralis major och minor, avgörande för pressrörelser och armens adduktion.'),
('chest', 'pl', 'Klatka piersiowa', 'Grupa mięśniowa znajdująca się z przodu tułowia, składająca się głównie z mięśnia piersiowego większego i mniejszego, niezbędna do ruchów wypychających i przywodzenia ramienia.'),
('chest', 'id', 'Dada', 'Kelompok otot yang terletak di bagian depan batang tubuh, terutama terdiri dari pektoralis mayor dan minor, penting untuk gerakan mendorong dan adduksi lengan.'),
('chest', 'bn', 'বুক', 'শরীরের সামনের দিকে অবস্থিত পেশী গোষ্ঠী, মূলত পেক্টোরালিস মেজর এবং মাইনর নিয়ে গঠিত, যা ধাক্কা দেওয়ার নড়াচড়া এবং হাতের এ্যাডডাকশনের জন্য অপরিহার্য।'),
('chest', 'vi', 'Ngực', 'Nhóm cơ nằm ở phía trước thân mình, chủ yếu gồm cơ ngực lớn và ngực bé, thiết yếu cho các động tác đẩy và khép cánh tay.'),
('chest', 'fa', 'سینه', 'گروه عضلانی واقع در بخش قدامی تنه، متشکل از عضلات سینه‌ای بزرگ و کوچک، که برای حرکات فشاری و نزدیک کردن بازو ضروری است.');