INSERT OR IGNORE INTO body_target_info (slug, lang, title, "desc") VALUES 
('core', 'es', 'Core', 'Conjunto de músculos que incluye los abdominales, la zona lumbar, la pelvis y los glúteos, fundamentales para la estabilidad.'),
('core', 'en', 'Core', 'Group of muscles including the abdominals, lower back, pelvis, and glutes, essential for stability.'),
('core', 'pt', 'Core', 'Grupo de músculos que inclui o abdómen, zona lombar, pélvis e glúteos, fundamentais para a estabilidade.'),
('core', 'fr', 'Core', 'Groupe de muscles incluant les abdominaux, le bas du dos, le bassin et les fessiers, essentiels pour la stabilité.'),
('core', 'de', 'Core', 'Muskelgruppe bestehend aus Bauch, unterem Rücken, Becken und Gesäß, die für die Stabilität unerlässlich ist.'),
('core', 'it', 'Core', 'Gruppo di muscoli che include addominali, zona lombare, bacino e glutei, fondamentali per la stabilità.'),
('core', 'zh', '核心', '包括腹肌、下背部、骨盆和臀部在内的肌群，对稳定性至关重要。'),
('core', 'ja', '体幹', '腹筋、腰部、骨盤、臀部を含む筋群で、安定性に不可欠です。'),
('core', 'ko', '코어', '복근, 허리, 골반, 둔근을 포함한 근육 그룹으로, 안정성에 필수적입니다.'),
('core', 'ar', 'الجذع', 'مجموعة من العضلات تشمل عضلات البطن وأسفل الظهر والحوض والأرداف، وهي ضرورية للاستقرار.'),
('core', 'hi', 'कोर', 'मांसपेशियों का समूह जिसमें पेट, पीठ के निचले हिस्से, श्रोणि और ग्लूट्स शामिल हैं, जो स्थिरता के लिए आवश्यक हैं।'),
('core', 'ru', 'Кор', 'Группа мышц, включающая пресс, поясницу, таз и ягодицы, необходимая для стабильности.'),
('core', 'nl', 'Core', 'Spiergroep inclusief de buikspieren, onderrug, bekken en bilspieren, essentieel voor stabiliteit.'),
('core', 'sv', 'Core', 'Muskelgrupp som inkluderar magmuskler, ländrygg, bäcken och sätesmuskler, avgörande för stabilitet.'),
('core', 'pl', 'Core', 'Grupa mięśni obejmująca brzuch, dół pleców, miednicę i pośladki, niezbędna dla stabilizacji.'),
('core', 'id', 'Inti', 'Kelompok otot yang mencakup perut, punggung bawah, panggul, dan bokong, penting untuk stabilitas.'),
('core', 'bn', 'কোর', 'পেট, পিঠের নিচের অংশ, শ্রোণি এবং গ্লুটস সহ পেশীগুলির একটি গ্রুপ, যা স্থিতিশীলতার জন্য অপরিহার্য।'),
('core', 'vi', 'Cơ lõi', 'Nhóm cơ bao gồm cơ bụng, lưng dưới, xương chậu và cơ mông, thiết yếu cho sự ổn định.'),
('core', 'fa', 'هسته (Core)', 'گروهی از عضلات شامل عضلات شکم، کمر، لگن و باسن که برای ثبات ضروری هستند.');