INSERT INTO body_target_info (slug, lang, title, "desc") VALUES
('forearms', 'es', 'Antebrazos', 'Grupo muscular que abarca desde el codo hasta la muñeca, responsable de la fuerza de agarre, la flexión y extensión de la muñeca y los movimientos de pronación y supinación.'),
('forearms', 'en', 'Forearms', 'Muscle group extending from the elbow to the wrist, responsible for grip strength, wrist flexion and extension, and pronation and supination movements.'),
('forearms', 'pt', 'Antebraços', 'Grupo muscular que se estende do cotovelo ao punho, responsável pela força de preensão, flexão e extensão do punho e movimentos de pronação e supinação.'),
('forearms', 'fr', 'Avant-bras', 'Groupe musculaire s étendant du coude au poignet, responsable de la force de préhension, de la flexion et de l extension du poignet, ainsi que des mouvements de pronation et de supination.'),
('forearms', 'de', 'Unterarme', 'Muskelgruppe, die sich vom Ellenbogen bis zum Handgelenk erstreckt und für die Griffkraft, die Flexion und Extension des Handgelenks sowie für Pronations- und Supinationsbewegungen verantwortlich ist.'),
('forearms', 'it', 'Avambracci', 'Gruppo muscolare che si estende dal gomito al polso, responsabile della forza di presa, della flessione ed estensione del polso e dei movimenti di pronazione e supinazione.'),
('forearms', 'zh', '前臂', '从肘部延伸至腕部的肌群，负责握力、腕关节屈伸以及前臂旋前和旋后动作。'),
('forearms', 'ja', '前腕', '肘から手首に広がる筋群で、握力、手首の屈曲・伸展、および回内・回外運動を担います。'),
('forearms', 'ko', '전완', '팔꿈치에서 손목까지 이어지는 근육군으로 악력, 손목 굴곡 및 신전, 그리고 회내 및 회외 운동을 담당합니다.'),
('forearms', 'ar', 'الساعد', 'مجموعة عضلية تمتد من المرفق إلى الرسغ، مسؤولة عن قوة القبضة، وثني وبسط الرسغ، وحركات الكب والكب (النبذ).'),
('forearms', 'hi', 'अग्रबाहु (फोरआर्म्स)', 'कोहनी से कलाई तक फैली मांसपेशी समूह, जो पकड़ने की शक्ति, कलाई के फ्लेक्सन और एक्सटेंशन, तथा प्रोनेशन और सुपीनेशन मूवमेंट के लिए जिम्मेदार है।'),
('forearms', 'ru', 'Предплечья', 'Мышечная группа, простирающаяся от локтя до запястья, отвечающая за силу хвата, сгибание и разгибание запястья, а также за движения пронации и супинации.'),
('forearms', 'nl', 'Onderarmen', 'Spiergroep die zich uitstrekt van de elleboog tot de pols, verantwoordelijk voor grijpkracht, polsflexie en -extensie, en pronatie- en supinatiebewegingen.'),
('forearms', 'sv', 'Underarmar', 'Muskelgrupp som sträcker sig från armbåge till handled, ansvarig för greppstyrka, handledsflexion och -extension samt pronations- och supinationsrörelser.'),
('forearms', 'pl', 'Przedramiona', 'Grupa mięśni rozciągająca się od łokcia do nadgarstka, odpowiedzialna za siłę chwytu, zginanie i prostowanie nadgarstka oraz ruchy pronacji i supinacji.'),
('forearms', 'id', 'Lengan Bawah', 'Kelompok otot yang membentang dari siku hingga pergelangan tangan, bertanggung jawab atas kekuatan cengkeraman, fleksi dan ekstensi pergelangan tangan, serta gerakan pronasi dan supinasi.'),
('forearms', 'bn', 'হাতের সামনের অংশ (ফোরআর্মস)', 'কনুই থেকে কব্জি পর্যন্ত বিস্তৃত পেশী গোষ্ঠী, যা গ্রিপ শক্তি, কব্জি বাঁকানো এবং প্রসারণ, এবং প্রোনেশন ও সুপিনেশন নড়াচড়ার জন্য দায়ী।'),
('forearms', 'vi', 'Cẳng tay', 'Nhóm cơ trải dài từ khuỷu tay đến cổ tay, chịu trách nhiệm cho lực nắm, gập và duỗi cổ tay, cùng các chuyển động sấp và ngửa cẳng tay.'),
('forearms', 'fa', 'ساعد', 'گروه عضلانی که از آرنج تا مچ دست امتداد یافته و مسئول قدرت گرفتن، خم و راست کردن مچ دست، و حرکات پرونیشن و سوپیناسیون است.');