INSERT OR IGNORE INTO body_target_info (slug, lang, title, "desc") VALUES
('full_body', 'es', 'Cuerpo completo', 'Entrenamiento que involucra múltiples grupos musculares en una sola sesión para maximizar la eficiencia metabólica y funcional.'),
('full_body', 'en', 'Full body', 'Training that involves multiple muscle groups in a single session to maximize metabolic and functional efficiency.'),
('full_body', 'pt', 'Corpo completo', 'Treino que envolve múltiplos grupos musculares em uma única sessão para maximizar a eficiência metabólica e funcional.'),
('full_body', 'fr', 'Corps complet', 'Entraînement impliquant plusieurs groupes musculaires en une seule séance pour maximiser l efficacité métabolique et fonctionnelle.'),
('full_body', 'de', 'Ganzkörper', 'Training, das mehrere Muskelgruppen in einer einzigen Sitzung einbezieht, um die metabolische und funktionelle Effizienz zu maximieren.'),
('full_body', 'it', 'Corpo intero', 'Allenamento che coinvolge più gruppi muscolari in una singola sessione per massimizzare l efficienza metabolica e funzionale.'),
('full_body', 'zh', '全身', '在单次训练中涉及多个肌肉群，以最大化代谢和功能效率。'),
('full_body', 'ja', '全身', '一度のセッションで複数の筋群を鍛えるトレーニングで、代謝と機能の効率を最大化します。'),
('full_body', 'ko', '전신', '단일 세션에서 여러 근육군을 사용하여 대사 및 기능적 효율성을 극대화하는 훈련입니다.'),
('full_body', 'ar', 'كامل الجسم', 'تمارين تشمل مجموعات عضلية متعددة في جلسة واحدة لزيادة الكفاءة الأيضية والوظيفية.'),
('full_body', 'hi', 'फुल बॉडी', 'एक ही सत्र में कई मांसपेशी समूहों को शामिल करने वाला प्रशिक्षण ताकि चयापचय और कार्यात्मक दक्षता को अधिकतम किया जा सके।'),
('full_body', 'ru', 'Все тело', 'Тренировка, включающая несколько групп мышц за одну сессию, для максимизации метаболической и функциональной эффективности.'),
('full_body', 'nl', 'Full body', 'Training waarbij meerdere spiergroepen in één sessie worden betrokken om de metabole en functionele efficiëntie te maximaliseren.'),
('full_body', 'sv', 'Helkropp', 'Träning som involverar flera muskelgrupper i en enda session för att maximera metabolisk och funktionell effektivitet.'),
('full_body', 'pl', 'Całe ciało', 'Trening angażujący wiele grup mięśniowych podczas jednej sesji w celu maksymalizacji wydajności metabolicznej i funkcjonalnej.'),
('full_body', 'id', 'Seluruh tubuh', 'Latihan yang melibatkan beberapa kelompok otot dalam satu sesi untuk memaksimalkan efisiensi metabolik dan fungsional.'),
('full_body', 'bn', 'ফুল বডি', 'একটি সেশনে একাধিক পেশী গোষ্ঠীকে জড়িত করে এমন প্রশিক্ষণ যা বিপাকীয় এবং কার্যকরী দক্ষতা সর্বাধিক করে।'),
('full_body', 'vi', 'Toàn thân', 'Bài tập liên quan đến nhiều nhóm cơ trong một buổi để tối đa hóa hiệu quả trao đổi chất và chức năng.'),
('full_body', 'fa', 'کل بدن', 'تمرینی که چندین گروه عضلانی را در یک جلسه درگیر می‌کند تا کارایی متابولیک و عملکردی را به حداکثر برساند.');