INSERT OR IGNORE INTO body_target_info (slug, lang, title, "desc") VALUES
('glutes', 'es', 'Glúteos', 'Grupo muscular posterior de la cadera formado por el glúteo mayor, medio y menor; son fundamentales para la extensión de la cadera, la estabilización de la pelvis y la potencia en el movimiento.'),
('glutes', 'en', 'Glutes', 'Posterior hip muscle group consisting of the gluteus maximus, medius, and minimus; they are essential for hip extension, pelvic stabilization, and power during movement.'),
('glutes', 'pt', 'Glúteos', 'Grupo muscular posterior do quadril formado pelo glúteo máximo, médio e mínimo; são fundamentais para a extensão do quadril, estabilização da pélvis e potência durante o movimento.'),
('glutes', 'fr', 'Fessiers', 'Groupe musculaire postérieur de la hanche composé du grand, du moyen et du petit fessier ; ils sont essentiels pour l extension de la hanche, la stabilisation du bassin et la puissance pendant le mouvement.'),
('glutes', 'de', 'Gesäßmuskulatur', 'Hintere Hüftmuskelgruppe, bestehend aus dem Musculus gluteus maximus, medius und minimus; sie sind unerlässlich für die Hüftstreckung, die Stabilisierung des Beckens und die Kraftentfaltung während der Bewegung.'),
('glutes', 'it', 'Glutei', 'Gruppo muscolare posteriore dell anca formato dal grande, medio e piccolo gluteo; sono fondamentali per l estensione dell anca, la stabilizzazione del bacino e la potenza durante il movimento.'),
('glutes', 'zh', '臀部', '髋部后侧肌群，由臀大肌、臀中肌和臀小肌组成；对于髋关节伸展、骨盆稳定以及运动时的动力输出至关重要。'),
('glutes', 'ja', '臀部', '大殿筋、中殿筋、小殿筋から成る股関節後部の筋群で、股関節の伸展、骨盤の安定化、および運動時のパワー発揮に不可欠です。'),
('glutes', 'ko', '둔근', '대둔근, 중둔근, 소둔근으로 구성된 고관절 후면 근육군으로, 고관절 신전, 골반 안정화 및 움직임 시 파워 발휘에 필수적입니다.'),
('glutes', 'ar', 'الأرداف (العضلات الألوية)', 'مجموعة عضلية خلفية للورك تتكون من العضلة الألوية الكبرى والوسطى والصغرى؛ وهي ضرورية لبسط الورك وتثبيت الحوض والقوة أثناء الحركة.'),
('glutes', 'hi', 'ग्लूट्स (कूल्हे की मांसपेशियां)', 'कूल्हे का पिछला मांसपेशी समूह जिसमें ग्लूटियस मैक्सिमस, मेडियस और मिनिमस शामिल हैं; ये कूल्हे के विस्तार, श्रोणि के स्थिरीकरण और गति के दौरान शक्ति के लिए आवश्यक हैं।'),
('glutes', 'ru', 'Ягодицы', 'Задняя мышечная группа бедра, состоящая из большой, средней и малой ягодичных мышц; они необходимы для разгибания бедра, стабилизации таза и мощности при движении.'),
('glutes', 'nl', 'Glutei (billen)', 'Posterieure heupspiergroep bestaande uit de gluteus maximus, medius en minimus; ze zijn essentieel voor heupextensie, bekkenstabilisatie en kracht tijdens beweging.'),
('glutes', 'sv', 'Gluteer (sätesmuskler)', 'Posterior höftmuskelgrupp bestående av gluteus maximus, medius och minimus; de är avgörande för höftextension, bäckenstabilisering och kraft under rörelse.'),
('glutes', 'pl', 'Pośladki', 'Tylna grupa mięśni biodra składająca się z mięśnia pośladkowego wielkiego, średniego i małego; są niezbędne do prostowania biodra, stabilizacji miednicy i generowania mocy podczas ruchu.'),
('glutes', 'id', 'Otot Gluteus (bokong)', 'Kelompok otot pinggul posterior yang terdiri dari gluteus maximus, medius, dan minimus; mereka penting untuk ekstensi pinggul, stabilisasi panggul, dan kekuatan selama bergerak.'),
('glutes', 'bn', 'গ্লুটস (নিতম্বের পেশী)', 'নিতম্বের পিছনের পেশী গোষ্ঠী যা গ্লুটিয়াস ম্যাক্সিমাস, মিডিয়াস এবং মিনিমাস নিয়ে গঠিত; এগুলো হিপ এক্সটেনশন, শ্রোণির স্থিতিশীলতা এবং নড়াচড়ার সময় শক্তির জন্য অপরিহার্য।'),
('glutes', 'vi', 'Cơ mông', 'Nhóm cơ hông phía sau gồm cơ mông lớn, mông nhỡ và mông nhỏ; rất thiết yếu cho việc duỗi hông, ổn định khung chậu và tạo lực khi vận động.'),
('glutes', 'fa', 'عضلات سرینی (باسن)', 'گروه عضلانی خلفی لگن متشکل از عضلات سرینی بزرگ، میانی و کوچک؛ که برای باز کردن مفصل ران، ثبات لگن و قدرت در حین حرکت حیاتی هستند.');