INSERT INTO body_target_info (slug, lang, title, "desc") VALUES
('hamstrings', 'es', 'Isquiotibiales', 'Grupo muscular en la parte posterior del muslo compuesto por el bíceps femoral, semitendinoso y semimembranoso, clave para la flexión de rodilla y extensión de cadera.'),
('hamstrings', 'en', 'Hamstrings', 'Muscle group in the back of the thigh consisting of the biceps femoris, semitendinosus, and semimembranosus, key for knee flexion and hip extension.'),
('hamstrings', 'pt', 'Isquiotibiais', 'Grupo muscular na parte posterior da coxa composto pelo bíceps femoral, semitendíneo e semimembranoso, chave para a flexão do joelho e extensão do quadril.'),
('hamstrings', 'fr', 'Ischio-jambiers', 'Groupe musculaire de la partie postérieure de la cuisse composé du biceps fémoral, du semi-tendineux et du semi-membraneux, essentiel pour la flexion du genou et l extension de la hanche.'),
('hamstrings', 'de', 'Beinrückseite (Ischiocrurale Muskulatur)', 'Muskelgruppe an der Rückseite des Oberschenkels, bestehend aus dem Musculus biceps femoris, semitendinosus und semimembranosus, entscheidend für die Kniebeugung und Hüftstreckung.'),
('hamstrings', 'it', 'Ischiocrurali', 'Gruppo muscolare nella parte posteriore della coscia composto dal bicipite femorale, semitendinoso e semimembranoso, chiave per la flessione del ginocchio e l estensione dell anca.'),
('hamstrings', 'zh', '腘绳肌', '大腿后侧肌群，由股二头肌、半腱肌和半膜肌组成，是膝关节屈曲和髋关节伸展的关键。'),
('hamstrings', 'ja', 'ハムストリングス', '大腿後面に位置する筋群で、大腿二頭筋、半腱様筋、半膜様筋から成り、膝の屈曲と股関節の伸展に不可欠です。'),
('hamstrings', 'ko', '햄스트링', '허벅지 후면에 위치한 근육군으로 대퇴이두근, 반건양근, 반막양근으로 구성되며, 무릎 굴곡과 고관절 신전의 핵심입니다.'),
('hamstrings', 'ar', 'عضلات الفخذ الخلفية (الهامسترينغ)', 'مجموعة عضلية في الجزء الخلفي من الفخذ تتكون من العضلة ذات الرأسين الفخذية، ونصف الوترية، ونصف الغشائية، وهي أساسية لثني الركبة وبسط الورك.'),
('hamstrings', 'hi', 'हैमस्ट्रिंग', 'जांघ के पिछले हिस्से में मांसपेशी समूह जिसमें बाइसेप्स फेमोरिस, सेमीटेंडिनोसस और सेमिमेम्ब्रेनसस शामिल हैं, जो घुटने के फ्लेक्सन और कूल्हे के विस्तार के लिए महत्वपूर्ण हैं।'),
('hamstrings', 'ru', 'Задняя поверхность бедра (хамстринг)', 'Мышечная группа на задней стороне бедра, состоящая из двуглавой мышцы бедра, полусухожильной и полуперепончатой мышц, ключевая для сгибания колена и разгибания бедра.'),
('hamstrings', 'nl', 'Hamstrings', 'Spiergroep aan de achterzijde van het bovenbeen bestaande uit de biceps femoris, semitendinosus en semimembranosus, essentieel voor knieflexie en heupextensie.'),
('hamstrings', 'sv', 'Hamstrings', 'Muskelgrupp på lårts baksida bestående av biceps femoris, semitendinosus och semimembranosus, avgörande för knäflexion och höftextension.'),
('hamstrings', 'pl', 'Mięśnie kulszowo-goleniowe', 'Grupa mięśni tylnej części uda złożona z mięśnia dwugłowego uda, półścięgnistego i półbłoniastego, kluczowa dla zginania kolana i prostowania biodra.'),
('hamstrings', 'id', 'Hamstring', 'Kelompok otot di bagian belakang paha yang terdiri dari bisep femoris, semitendinosus, dan semimembranosus, kunci untuk fleksi lutut dan ekstensi pinggul.'),
('hamstrings', 'bn', 'হ্যামস্ট্রিং', 'উরুর পিছনের পেশী গোষ্ঠী যা বাইসেপস ফেমোরিস, সেমিটেন্ডিনোসাস এবং সেমিমেমব্রানোসাস নিয়ে গঠিত, যা হাঁটু ভাঁজ করা এবং হিপ এক্সটেনশনের জন্য গুরুত্বপূর্ণ।'),
('hamstrings', 'vi', 'Cơ gân kheo', 'Nhóm cơ mặt sau đùi gồm cơ nhị đầu đùi, cơ bán gân và cơ bán màng, đóng vai trò quan trọng trong việc gập gối và duỗi hông.'),
('hamstrings', 'fa', 'عضلات همسترینگ', 'گروه عضلانی در بخش پشتی ران متشکل از عضله دوسر رانی، نیم‌وتری و نیم‌غشایی، کلیدی برای خم کردن زانو و باز کردن مفصل ران.');