INSERT OR IGNORE INTO body_target_info (slug, lang, title, "desc") VALUES
('hip_flexors', 'es', 'Flexores de la cadera', 'Grupo muscular que incluye el psoas ilíaco, recto femoral y sartorio, responsables de elevar el muslo hacia el torso y estabilizar la pelvis durante la marcha.'),
('hip_flexors', 'en', 'Hip flexors', 'Muscle group including the iliopsoas, rectus femoris, and sartorius, responsible for lifting the thigh towards the torso and stabilizing the pelvis during gait.'),
('hip_flexors', 'pt', 'Flexores do quadril', 'Grupo muscular que inclui o iliopsoas, reto femoral e sartório, responsáveis por elevar a coxa em direção ao tronco e estabilizar a pélvis durante a marcha.'),
('hip_flexors', 'fr', 'Fléchisseurs de la hanche', 'Groupe musculaire comprenant l iliopsoas, le droit fémoral et le sartorius, responsables de l élévation de la cuisse vers le torse et de la stabilisation du bassin pendant la marche.'),
('hip_flexors', 'de', 'Hüftbeuger', 'Muskelgruppe, die den Iliopsoas, den Musculus rectus femoris und den Sartorius umfasst, verantwortlich für das Anheben des Oberschenkels zum Oberkörper und die Stabilisierung des Beckens beim Gehen.'),
('hip_flexors', 'it', 'Flessori dell anca', 'Gruppo muscolare che include l ileopsoas, il retto femorale e il sartorio, responsabili dell elevazione della coscia verso il torace e della stabilizzazione del bacino durante la deambulazione.'),
('hip_flexors', 'zh', '髋屈肌', '包括髂腰肌、股直肌和缝匠肌在内的肌群，负责将大腿抬向躯干并在行走过程中稳定骨盆。'),
('hip_flexors', 'ja', '腸腰筋群（股関節屈筋）', '腸腰筋、大腿直筋、縫工筋などから成る筋群で、大腿を体幹部へ引き上げ、歩行時の骨盤安定化を担います。'),
('hip_flexors', 'ko', '고관절 굴곡근', '장요근, 대퇴직근, 봉공근 등을 포함하는 근육군으로, 허벅지를 몸통 쪽으로 들어 올리고 보행 시 골반을 안정시키는 역할을 합니다.'),
('hip_flexors', 'ar', 'عضلات ثني الورك', 'مجموعة عضلية تشمل العضلة الحرقفية القطنية، والعضلة المستقيمة الفخذية، والعضلة الخياطية، وهي مسؤولة عن رفع الفخذ نحو الجذع وتثبيت الحوض أثناء المشي.'),
('hip_flexors', 'hi', 'हिप फ्लेक्सर्स (कूल्हे मोड़ने वाली मांसपेशियां)', 'इलियोप्सोअस, रेक्टस फेमोरिस और सार्टोरियस सहित मांसपेशी समूह, जो जांघ को धड़ की ओर उठाने और चलने के दौरान श्रोणि को स्थिर करने के लिए जिम्मेदार हैं।'),
('hip_flexors', 'ru', 'Сгибатели бедра', 'Мышечная группа, включающая подвздошно-поясничную мышцу, прямую мышцу бедра и портняжную мышцу, отвечающие за подъем бедра к корпусу и стабилизацию таза при ходьбе.'),
('hip_flexors', 'nl', 'Heupbuigers', 'Spiergroep inclusief de iliopsoas, rectus femoris en sartorius, verantwoordelijk voor het heffen van de dij naar de romp en het stabiliseren van het bekken tijdens het lopen.'),
('hip_flexors', 'sv', 'Höftböjare', 'Muskelgrupp som inkluderar iliopsoas, rectus femoris och sartorius, ansvarig för att lyfta låret mot bålen och stabilisera bäckenet under gång.'),
('hip_flexors', 'pl', 'Mięśnie zginacze biodra', 'Grupa mięśni obejmująca mięsień biodrowo-lędźwiowy, prosty uda i krawiecki, odpowiedzialna za unoszenie uda w stronę tułowia i stabilizację miednicy podczas chodu.'),
('hip_flexors', 'id', 'Fleksor pinggul', 'Kelompok otot yang mencakup iliopsoas, rektus femoris, dan sartorius, yang bertanggung jawab untuk mengangkat paha ke arah batang tubuh dan menstabilkan panggul saat berjalan.'),
('hip_flexors', 'bn', 'হিপ ফ্লেক্সর', 'ইলিয়োপসোস, রেকটাস ফেমোরিস এবং সার্টোরিয়াস সহ পেশী গোষ্ঠী, যা উরুকে শরীরের দিকে তোলা এবং হাঁটার সময় শ্রোণিকে স্থিতিশীল করার জন্য দায়ী।'),
('hip_flexors', 'vi', 'Cơ gập hông', 'Nhóm cơ bao gồm cơ thắt lưng chậu, cơ thẳng đùi và cơ may, chịu trách nhiệm nâng đùi về phía thân mình và ổn định khung chậu khi đi bộ.'),
('hip_flexors', 'fa', 'عضلات خم‌کننده لگن', 'گروه عضلانی شامل عضله خاصره‌ای-کمری، راست رانی و خیاطی، مسئول بالا آوردن ران به سمت تنه و ثبات لگن در هنگام راه رفتن.');