INSERT OR IGNORE INTO body_target_info (slug, lang, title, "desc") VALUES
('lats', 'es', 'Dorsales', 'El músculo dorsal ancho es el músculo más grande del torso; su función es la aducción, extensión y rotación interna del brazo, esencial para la tracción.'),
('lats', 'en', 'Lats', 'The latissimus dorsi is the largest muscle of the torso; its function is arm adduction, extension, and internal rotation, essential for pulling movements.'),
('lats', 'pt', 'Dorsais', 'O músculo latíssimo do dorso é o maior músculo do tronco; sua função é a adução, extensão e rotação interna do braço, essencial para a tração.'),
('lats', 'fr', 'Dorsaux', 'Le muscle grand dorsal est le plus grand muscle du torse ; sa fonction est l adduction, l extension et la rotation interne du bras, essentiel pour la traction.'),
('lats', 'de', 'Latissimus', 'Der Musculus latissimus dorsi ist der größte Muskel des Oberkörpers; seine Funktion ist die Adduktion, Extension und Innenrotation des Arms, entscheidend für Zugbewegungen.'),
('lats', 'it', 'Dorsali', 'Il muscolo gran dorsale è il più grande muscolo del torace; la sua funzione è l adduzione, l estensione e la rotazione interna del braccio, essenziale per la trazione.'),
('lats', 'zh', '背阔肌', '背阔肌是躯干最大的肌肉；其功能是手臂内收、伸展和内旋，是进行牵引动作的关键。'),
('lats', 'ja', '広背筋', '広背筋は胴体で最大の筋肉です。その機能は腕の内転、伸展、内旋であり、引く動作（プル系）に不可欠です。'),
('lats', 'ko', '광배근', '광배근은 몸통에서 가장 큰 근육으로, 팔의 내전, 신전, 내회전 기능을 하며 당기기 동작에 필수적입니다.'),
('lats', 'ar', 'عضلات الظهر العريضة', 'العضلة الظهرية العريضة هي أكبر عضلة في الجذع؛ وظيفتها تقريب وبسط وتدوير الذراع للداخل، وهي ضرورية لحركات السحب.'),
('lats', 'hi', 'लैट्स (लैटिसिमस डॉर्सी)', 'लैटिसिमस डॉर्सी धड़ की सबसे बड़ी मांसपेशी है; इसका कार्य हाथ का एडक्शन, एक्सटेंशन और आंतरिक रोटेशन है, जो खींचने वाले मूवमेंट के लिए आवश्यक है।'),
('lats', 'ru', 'Широчайшие мышцы спины', 'Широчайшая мышца спины — самая крупная мышца торса; её функция заключается в приведении, разгибании и внутренней ротации руки, что необходимо для тяговых движений.'),
('lats', 'nl', 'Latissimus dorsi (rugspieren)', 'De latissimus dorsi is de grootste spier van de romp; de functie is adductie, extensie en interne rotatie van de arm, essentieel voor trekkende bewegingen.'),
('lats', 'sv', 'Lats (breda ryggmuskeln)', 'Latissimus dorsi är bålens största muskel; dess funktion är armens adduktion, extension och inåtrotation, avgörande för dragrörelser.'),
('lats', 'pl', 'Mięśnie najszersze grzbietu', 'Mięsień najszerszy grzbietu to największy mięsień tułowia; jego funkcją jest przywodzenie, prostowanie i rotacja wewnętrzna ramienia, niezbędna do ruchów przyciągających.'),
('lats', 'id', 'Lats (Latissimus Dorsi)', 'Latissimus dorsi adalah otot terbesar di batang tubuh; fungsinya adalah adduksi, ekstensi, dan rotasi internal lengan, penting untuk gerakan menarik.'),
('lats', 'bn', 'ল্যাটস (ল্যাটিসিমাস ডরসি)', 'ল্যাটিসিমাস ডরসি শরীরের সবচেয়ে বড় পেশী; এর কাজ হলো হাতের এ্যাডডাকশন, এক্সটেনশন এবং অভ্যন্তরীণ রোটেশন, যা টানার নড়াচড়ার জন্য অপরিহার্য।'),
('lats', 'vi', 'Cơ xô', 'Cơ lưng rộng là cơ lớn nhất của thân mình; chức năng là khép, duỗi và xoay trong cánh tay, thiết yếu cho các động tác kéo.'),
('lats', 'fa', 'عضلات زیربغل (پشتی بزرگ)', 'عضله پشتی بزرگ، بزرگ‌ترین عضله تنه است؛ عملکرد آن نزدیک کردن، باز کردن و چرخش داخلی بازو است که برای حرکات کششی ضروری است.');