INSERT OR IGNORE INTO body_target_info (slug, lang, title, "desc") VALUES
('lower_back', 'es', 'Espalda baja', 'Zona lumbar que incluye los erectores espinales, crucial para la estabilidad de la columna, la postura erguida y la transferencia de fuerza entre el tren inferior y superior.'),
('lower_back', 'en', 'Lower back', 'Lumbar region including the spinal erectors, crucial for spinal stability, upright posture, and force transfer between the lower and upper body.'),
('lower_back', 'pt', 'Costas baixas (lombar)', 'Região lombar que inclui os eretores da espinha, crucial para a estabilidade da coluna, postura ereta e transferência de força entre o tronco inferior e superior.'),
('lower_back', 'fr', 'Bas du dos (lombaire)', 'Région lombaire comprenant les érecteurs du rachis, cruciale pour la stabilité de la colonne vertébrale, la posture droite et le transfert de force entre le bas et le haut du corps.'),
('lower_back', 'de', 'Unterer Rücken (Lendenwirbelsäule)', 'Lendenbereich einschließlich der Rückenstrecker, entscheidend für die Stabilität der Wirbelsäule, aufrechte Körperhaltung und Kraftübertragung zwischen Unter- und Oberkörper.'),
('lower_back', 'it', 'Parte bassa della schiena (lombari)', 'Regione lombare che include gli erettori spinali, cruciale per la stabilità della colonna vertebrale, la postura eretta e il trasferimento di forza tra la parte inferiore e superiore del corpo.'),
('lower_back', 'zh', '下背部（腰部）', '包括竖脊肌在内的腰椎区域，对于脊柱稳定性、直立姿势以及上下肢之间的力量传递至关重要。'),
('lower_back', 'ja', '腰部（下背部）', '脊柱起立筋群を含む腰椎エリアで、脊柱の安定性、直立姿勢の維持、上下肢間の力伝達に重要です。'),
('lower_back', 'ko', '허리 (하배부)', '척추기립근을 포함하는 요추 부위로, 척추 안정성, 직립 자세 유지, 상하체 간 힘 전달에 매우 중요합니다.'),
('lower_back', 'ar', 'أسفل الظهر (المنطقة القطنية)', 'المنطقة القطنية التي تشمل عضلات ناصبة للفقار، وهي حاسمة لاستقرار العمود الفقري، والوقوف المستقيم، ونقل القوة بين الجزء السفلي والعلوي من الجسم.'),
('lower_back', 'hi', 'लोअर बैक (कमर)', 'काठ (लंबर) क्षेत्र जिसमें स्पाइनल इरेक्टर्स शामिल हैं, जो रीढ़ की स्थिरता, सीधी मुद्रा और शरीर के निचले और ऊपरी हिस्से के बीच बल हस्तांतरण के लिए महत्वपूर्ण है।'),
('lower_back', 'ru', 'Поясница', 'Поясничная область, включающая мышцы, выпрямляющие позвоночник; критически важна для стабильности позвоночника, прямой осанки и передачи усилия между нижней и верхней частями тела.'),
('lower_back', 'nl', 'Onderrug (lumbaal)', 'Lumbale regio inclusief de spinale erectors, cruciaal voor ruggengraatstabiliteit, rechtopstaande houding en krachtoverdracht tussen het onder- en bovenlichaam.'),
('lower_back', 'sv', 'Ländrygg', 'Ländryggsregionen inklusive spinala erektorer, avgörande för ryggradsstabilitet, upprätt hållning och kraftöverföring mellan under- och överkropp.'),
('lower_back', 'pl', 'Dolny odcinek pleców (lędźwie)', 'Odcinek lędźwiowy obejmujący prostowniki grzbietu, kluczowy dla stabilności kręgosłupa, wyprostowanej postawy i przenoszenia siły między dolną a górną częścią ciała.'),
('lower_back', 'id', 'Punggung bawah (lumbar)', 'Wilayah lumbal yang mencakup erektor tulang belakang, sangat penting untuk stabilitas tulang belakang, postur tegak, dan transfer kekuatan antara tubuh bagian bawah dan atas.'),
('lower_back', 'bn', 'পিঠের নিচের অংশ (লাম্বার)', 'লাম্বার অঞ্চল যা স্পাইনাল ইরেক্টরকে অন্তর্ভুক্ত করে, যা মেরুদণ্ডের স্থিতিশীলতা, সোজা ভঙ্গি এবং শরীরের নিচের ও উপরের অংশের মধ্যে শক্তি স্থানান্তরের জন্য অত্যন্ত গুরুত্বপূর্ণ।'),
('lower_back', 'vi', 'Lưng dưới (thắt lưng)', 'Vùng thắt lưng bao gồm các cơ dựng sống, rất quan trọng cho sự ổn định của cột sống, tư thế đứng thẳng và truyền lực giữa phần dưới và phần trên cơ thể.'),
('lower_back', 'fa', 'کمر (ناحیه کمری)', 'ناحیه کمری شامل عضلات راست‌کننده ستون فقرات، حیاتی برای ثبات ستون فقرات، وضعیت ایستاده بدن و انتقال نیرو بین پایین‌تنه و بالاتنه.');