INSERT OR IGNORE INTO body_target_info (slug, lang, title, "desc") VALUES
('neck', 'es', 'Cuello', 'Estructura que conecta la cabeza con el torso, compuesta por músculos como el trapecio superior y esternocleidomastoideo, fundamentales para la movilidad, soporte cefálico y estabilidad cervical.'),
('neck', 'en', 'Neck', 'Structure connecting the head to the torso, composed of muscles such as the upper trapezius and sternocleidomastoid, essential for mobility, head support, and cervical stability.'),
('neck', 'pt', 'Pescoço', 'Estrutura que conecta a cabeça ao tronco, composta por músculos como o trapézio superior e esternocleidomastóideo, fundamentais para a mobilidade, suporte cefálico e estabilidade cervical.'),
('neck', 'fr', 'Cou', 'Structure reliant la tête au torse, composée de muscles tels que le trapèze supérieur et le sterno-cléido-mastoïdien, essentiels pour la mobilité, le soutien de la tête et la stabilité cervicale.'),
('neck', 'de', 'Nacken', 'Struktur, die den Kopf mit dem Oberkörper verbindet, bestehend aus Muskeln wie dem oberen Trapezmuskel und dem Musculus sternocleidomastoideus, die für Mobilität, Kopfstütze und Halsstabilität unerlässlich sind.'),
('neck', 'it', 'Collo', 'Struttura che collega la testa al torace, composta da muscoli come il trapezio superiore e lo sternocleidomastoideo, fondamentali per la mobilità, il supporto del capo e la stabilità cervicale.'),
('neck', 'zh', '颈部', '连接头部与躯干的结构，由斜方肌上部和胸锁乳突肌等肌肉组成，对于灵活性、头部支撑和颈椎稳定性至关重要。'),
('neck', 'ja', '首', '頭部と胴体をつなぐ構造で、僧帽筋上部や胸鎖乳突筋などの筋肉から成り、可動性、頭部の支持、頸椎の安定性に不可欠です。'),
('neck', 'ko', '목', '머리와 몸통을 연결하는 구조로, 상부 승모근 및 흉쇄유돌근과 같은 근육으로 구성되어 가동성, 머리 지지 및 경추 안정성에 필수적입니다.'),
('neck', 'ar', 'الرقبة', 'هيكل يربط الرأس بالجذع، يتكون من عضلات مثل العضلة شبه المنحرفة العلوية والعضلة القصية الترقوية الخشائية، وهي ضرورية للحركة ودعم الرأس واستقرار الرقبة.'),
('neck', 'hi', 'गर्दन', 'सिर को धड़ से जोड़ने वाली संरचना, जो ऊपरी ट्रैपेज़ियस और स्टर्नोक्लीडोमस्टॉइड जैसी मांसपेशियों से बनी है, जो गतिशीलता, सिर को सहारा देने और सर्वाइकल स्थिरता के लिए महत्वपूर्ण है।'),
('neck', 'ru', 'Шея', 'Структура, соединяющая голову с туловищем, состоящая из мышц, таких как верхняя часть трапеции и грудино-ключично-сосцевидная мышца, необходимых для подвижности, поддержки головы и стабильности шейного отдела.'),
('neck', 'nl', 'Nek', 'Structuur die het hoofd met de romp verbindt, bestaande uit spieren zoals de bovenste trapezius en sternocleidomastoïdeus, essentieel voor mobiliteit, hoofdondersteuning en cervicale stabiliteit.'),
('neck', 'sv', 'Nacke', 'Struktur som förbinder huvudet med bålen, bestående av muskler såsom övre trapezius och sternocleidomastoideus, avgörande för rörlighet, huvudstöd och cervikal stabilitet.'),
('neck', 'pl', 'Szyja', 'Struktura łącząca głowę z tułowiem, składająca się z mięśni takich jak czworoboczny grzbietu (część górna) i mostkowo-obojczykowo-sutkowy, kluczowa dla mobilności, podparcia głowy i stabilności odcinka szyjnego.'),
('neck', 'id', 'Leher', 'Struktur yang menghubungkan kepala dengan batang tubuh, terdiri dari otot-otot seperti trapezius atas dan sternocleidomastoideus, penting untuk mobilitas, dukungan kepala, dan stabilitas servikal.'),
('neck', 'bn', 'ঘাড়', 'মাথার সাথে শরীরের সংযোগকারী কাঠামো, যা আপার ট্র্যাপেজিয়াস এবং স্টার্নোক্লিডোমাস্টয়েড পেশী দ্বারা গঠিত, যা গতিশীলতা, মাথা ধরে রাখা এবং ঘাড়ের স্থিতিশীলতার জন্য গুরুত্বপূর্ণ।'),
('neck', 'vi', 'Cổ', 'Cấu trúc nối đầu với thân mình, gồm các cơ như cơ thang trên và cơ ức đòn chũm, thiết yếu cho sự linh hoạt, hỗ trợ đầu và ổn định cột sống cổ.'),
('neck', 'fa', 'گردن', 'ساختاری که سر را به تنه متصل می‌کند، متشکل از عضلاتی مانند بخش فوقانی ذوزنقه‌ای و جناغی-چنبری-پستانی، حیاتی برای تحرک، حمایت از سر و ثبات ستون فقرات گردنی.');