INSERT INTO body_target_info (slug, lang, title, "desc") VALUES
('obliques', 'es', 'Oblicuos', 'Músculos situados a los lados del abdomen (interno y externo), responsables de la rotación del tronco, flexión lateral y estabilización de la columna.'),
('obliques', 'en', 'Obliques', 'Muscles located on the sides of the abdomen (internal and external), responsible for trunk rotation, lateral flexion, and spinal stabilization.'),
('obliques', 'pt', 'Oblíquos', 'Músculos situados nas laterais do abdômen (interno e externo), responsáveis pela rotação do tronco, flexão lateral e estabilização da coluna.'),
('obliques', 'fr', 'Obliques', 'Muscles situés sur les côtés de l abdomen (interne et externe), responsables de la rotation du tronc, de la flexion latérale et de la stabilisation de la colonne vertébrale.'),
('obliques', 'de', 'Schräge Bauchmuskeln (Obliques)', 'Muskeln an den Seiten des Bauches (intern und extern), verantwortlich für Rumpfrotation, Seitwärtsbeugung und Wirbelsäulenstabilisierung.'),
('obliques', 'it', 'Obliqui', 'Muscoli situati ai lati dell addome (interno ed esterno), responsabili della rotazione del tronco, della flessione laterale e della stabilizzazione della colonna vertebrale.'),
('obliques', 'zh', '腹斜肌', '位于腹部两侧的肌肉（内斜肌和外斜肌），负责躯干旋转、侧屈和脊柱稳定性。'),
('obliques', 'ja', '腹斜筋', '腹部の側面にある筋肉（内腹斜筋・外腹斜筋）で、体幹の回旋、側屈、脊柱の安定化を担います。'),
('obliques', 'ko', '복사근', '복부 측면에 위치한 근육(내복사근, 외복사근)으로, 체간 회전, 측굴 및 척추 안정화 역할을 합니다.'),
('obliques', 'ar', 'العضلات المائلة', 'عضلات تقع على جانبي البطن (الداخلية والخارجية)، وهي مسؤولة عن دوران الجذع، والانحناء الجانبي، واستقرار العمود الفقري.'),
('obliques', 'hi', 'ओब्लिक्स (पेट की तिरछी मांसपेशियां)', 'पेट के किनारों पर स्थित मांसपेशियां (आंतरिक और बाहरी), जो धड़ के रोटेशन, पार्श्व फ्लेक्सन और रीढ़ की स्थिरता के लिए जिम्मेदार हैं।'),
('obliques', 'ru', 'Косые мышцы живота', 'Мышцы, расположенные по бокам живота (внутренние и внешние), отвечающие за ротацию туловища, боковые наклоны и стабилизацию позвоночника.'),
('obliques', 'nl', 'Obliqui (schuine buikspieren)', 'Spieren aan de zijkanten van de buik (intern en extern), verantwoordelijk voor romp-rotatie, laterale flexie en stabilisatie van de ruggengraat.'),
('obliques', 'sv', 'Obliqui (sneda magmuskler)', 'Muskler belägna på bukens sidor (interna och externa), ansvariga för bålrotation, lateral flexion och ryggradsstabilitet.'),
('obliques', 'pl', 'Mięśnie skośne brzucha', 'Mięśnie znajdujące się po bokach brzucha (wewnętrzne i zewnętrzne), odpowiedzialne za rotację tułowia, zginanie boczne i stabilizację kręgosłupa.'),
('obliques', 'id', 'Obliques (otot miring perut)', 'Otot yang terletak di sisi perut (internal dan eksternal), bertanggung jawab untuk rotasi batang tubuh, fleksi lateral, dan stabilitas tulang belakang.'),
('obliques', 'bn', 'ওবলিক্স (পেটের পেশী)', 'পেটের পাশে অবস্থিত পেশী (অভ্যন্তরীণ এবং বাহ্যিক), যা শরীরের মোচড়, পার্শ্বীয় নড়াচড়া এবং মেরুদণ্ডের স্থিতিশীলতার জন্য দায়ী।'),
('obliques', 'vi', 'Cơ chéo bụng', 'Các cơ nằm ở hai bên bụng (trong và ngoài), chịu trách nhiệm xoay thân mình, gập nghiêng và ổn định cột sống.'),
('obliques', 'fa', 'عضلات مورب شکمی', 'عضلات واقع در طرفین شکم (داخلی و خارجی)، مسئول چرخش تنه، خم شدن جانبی و ثبات ستون فقرات.');