INSERT OR IGNORE INTO body_target_info (slug, lang, title, "desc") VALUES
('rotator_cuff', 'es', 'Manguito rotador', 'Grupo de músculos y tendones que estabilizan la articulación del hombro, esenciales para la rotación y el movimiento seguro del brazo.'),
('rotator_cuff', 'en', 'Rotator cuff', 'Group of muscles and tendons that stabilize the shoulder joint, essential for rotation and safe arm movement.'),
('rotator_cuff', 'pt', 'Manguito rotador', 'Grupo de músculos e tendões que estabilizam a articulação do ombro, essenciais para a rotação e o movimento seguro do braço.'),
('rotator_cuff', 'fr', 'Coiffe des rotateurs', 'Groupe de muscles et de tendons qui stabilisent l articulation de l épaule, essentiels pour la rotation et le mouvement sécurisé du bras.'),
('rotator_cuff', 'de', 'Rotatorenmanschette', 'Gruppe von Muskeln und Sehnen, die das Schultergelenk stabilisieren und für die Rotation sowie die sichere Bewegung des Arms unerlässlich sind.'),
('rotator_cuff', 'it', 'Cuffia dei rotatori', 'Gruppo di muscoli e tendini che stabilizzano l articolazione della spalla, essenziali per la rotazione e il movimento sicuro del braccio.'),
('rotator_cuff', 'zh', '肩袖肌群', '稳定肩关节的肌肉和肌腱群，对于旋转和手臂的安全运动至关重要。'),
('rotator_cuff', 'ja', '回旋筋腱板（ローテーターカフ）', '肩関節を安定させる筋肉と腱の集まりで、回旋運動と腕の安全な動作に不可欠です。'),
('rotator_cuff', 'ko', '회전근개', '어깨 관절을 안정시키는 근육 및 힘줄 그룹으로, 팔의 회전과 안전한 움직임에 필수적입니다.'),
('rotator_cuff', 'ar', 'الكفة المدورة', 'مجموعة من العضلات والأوتار التي تثبت مفصل الكتف، وهي ضرورية للدوران وحركة الذراع الآمنة.'),
('rotator_cuff', 'hi', 'रोटेटर कफ', 'मांसपेशियों और टेंडन का समूह जो कंधे के जोड़ को स्थिर करता है, जो रोटेशन और हाथ की सुरक्षित गति के लिए आवश्यक है।'),
('rotator_cuff', 'ru', 'Вращательная манжета плеча', 'Группа мышц и сухожилий, стабилизирующая плечевой сустав, необходимая для вращения и безопасного движения руки.'),
('rotator_cuff', 'nl', 'Rotator cuff', 'Groep spieren en pezen die het schoudergewricht stabiliseren, essentieel voor rotatie en veilige armbeweging.'),
('rotator_cuff', 'sv', 'Rotatorkuff', 'Grupp av muskler och senor som stabiliserar axelleden, avgörande för rotation och säker armrörelse.'),
('rotator_cuff', 'pl', 'Stożek rotatorów', 'Grupa mięśni i ścięgien stabilizujących staw barkowy, niezbędna do rotacji i bezpiecznego ruchu ramienia.'),
('rotator_cuff', 'id', 'Rotator cuff', 'Kelompok otot dan tendon yang menstabilkan sendi bahu, penting untuk rotasi dan gerakan lengan yang aman.'),
('rotator_cuff', 'bn', 'রোটেটর কাফ', 'পেশী এবং টেন্ডনের গোষ্ঠী যা কাঁধের জয়েন্টকে স্থিতিশীল করে, যা রোটেশন এবং হাতের নিরাপদ নড়াচড়ার জন্য গুরুত্বপূর্ণ।'),
('rotator_cuff', 'vi', 'Chóp xoay vai', 'Nhóm cơ và gân ổn định khớp vai, thiết yếu cho việc xoay và chuyển động cánh tay an toàn.'),
('rotator_cuff', 'fa', 'روتاتور کاف (چرخاننده بازو)', 'گروه عضلات و تاندون‌هایی که مفصل شانه را تثبیت می‌کنند، برای چرخش و حرکت ایمن بازو ضروری هستند.');