INSERT INTO body_target_info (slug, lang, title, "desc") VALUES
('serratus', 'es', 'Serrato', 'Músculo situado en la parte lateral del tórax, clave para la protracción de la escápula y la estabilidad durante movimientos de empuje.'),
('serratus', 'en', 'Serratus', 'Muscle located on the lateral aspect of the thorax, key for scapular protraction and stability during pushing movements.'),
('serratus', 'pt', 'Serrátil', 'Músculo localizado na parte lateral do tórax, chave para a protração da escápula e estabilidade durante movimentos de empurrar.'),
('serratus', 'fr', 'Serratus (Grand dentelé)', 'Muscle situé sur la partie latérale du thorax, essentiel pour la protraction de l omoplate et la stabilité lors des mouvements de poussée.'),
('serratus', 'de', 'Serratus (vorderer Sägemuskel)', 'Muskel an der Seite des Brustkorbs, entscheidend für die Protraktion des Schulterblatts und die Stabilität bei Druckbewegungen.'),
('serratus', 'it', 'Serrato', 'Muscolo situato nella parte laterale del torace, chiave per la protrusione della scapola e la stabilità durante i movimenti di spinta.'),
('serratus', 'zh', '前锯肌', '位于胸廓侧面的肌肉，对于肩胛骨前伸和推举动作中的稳定性至关重要。'),
('serratus', 'ja', '前鋸筋', '胸郭側面に位置する筋肉で、肩甲骨の外転と押す動作の安定性に不可欠です。'),
('serratus', 'ko', '전거근', '흉곽 측면에 위치한 근육으로, 견갑골의 전인과 미는 동작 시 안정성에 핵심적인 역할을 합니다.'),
('serratus', 'ar', 'العضلة المنشارية الأمامية', 'عضلة تقع على الجانب الجانبي من القفص الصدري، وهي أساسية لبروز لوح الكتف والاستقرار أثناء حركات الدفع.'),
('serratus', 'hi', 'सेरेटस', 'छाती के पार्श्व भाग पर स्थित मांसपेशी, जो स्कैपुला के प्रोट्रैक्शन और धक्का देने वाले मूवमेंट के दौरान स्थिरता के लिए महत्वपूर्ण है।'),
('serratus', 'ru', 'Передняя зубчатая мышца', 'Мышца, расположенная на боковой части грудной клетки, ключевая для протракции лопатки и стабильности при жимовых движениях.'),
('serratus', 'nl', 'Serratus (gezaagde spier)', 'Spier aan de zijkant van de borstkas, essentieel voor protractie van het schouderblad en stabiliteit tijdens duwbewegingen.'),
('serratus', 'sv', 'Serratus (främre sågmuskeln)', 'Muskel belägen på bröstkorgens sida, nyckeln till skulderbladets protraktion och stabilitet vid pressrörelser.'),
('serratus', 'pl', 'Mięsień zębaty przedni', 'Mięsień znajdujący się z boku klatki piersiowej, kluczowy dla protrakcji łopatki i stabilności podczas ruchów wypychających.'),
('serratus', 'id', 'Serratus', 'Otot yang terletak di bagian lateral toraks, kunci untuk protraksi skapula dan stabilitas selama gerakan mendorong.'),
('serratus', 'bn', 'সেরাটাস', 'বুকের পাশে অবস্থিত পেশী, যা স্ক্যাপুলার প্রোট্রাকশন এবং ধাক্কা দেওয়ার নড়াচড়ার সময় স্থিতিশীলতার জন্য গুরুত্বপূর্ণ।'),
('serratus', 'vi', 'Cơ răng trước', 'Cơ nằm ở mặt bên lồng ngực, thiết yếu cho việc đưa xương bả vai ra trước và ổn định khi thực hiện các động tác đẩy.'),
('serratus', 'fa', 'عضله دندانه‌ای قدامی', 'عضله واقع در بخش جانبی قفسه سینه، کلیدی برای حرکت رو به جلوی کتف و ثبات در حین حرکات فشاری.');