INSERT INTO body_target_info (slug, lang, title, "desc") VALUES
('shoulders', 'es', 'Hombros', 'Complejo articular formado principalmente por el deltoides (anterior, lateral y posterior); es fundamental para la movilidad del brazo, la fuerza de empuje vertical y la estabilidad del hombro.'),
('shoulders', 'en', 'Shoulders', 'Joint complex primarily formed by the deltoids (anterior, lateral, and posterior); essential for arm mobility, vertical pushing strength, and shoulder stability.'),
('shoulders', 'pt', 'Ombros', 'Complexo articular formado principalmente pelo deltoide (anterior, lateral e posterior); é fundamental para a mobilidade do braço, força de empurrar vertical e estabilidade do ombro.'),
('shoulders', 'fr', 'Épaules', 'Complexe articulaire formé principalement par le deltoïde (antérieur, latéral et postérieur) ; il est essentiel pour la mobilité du bras, la force de poussée verticale et la stabilité de l épaule.'),
('shoulders', 'de', 'Schultern', 'Gelenkkomplex, der hauptsächlich aus dem Deltoideus (anterior, lateral und posterior) besteht; entscheidend für die Armbeweglichkeit, vertikale Druckkraft und Schulterstabilität.'),
('shoulders', 'it', 'Spalle', 'Complesso articolare formato principalmente dal deltoide (anteriore, laterale e posteriore); è fondamentale per la mobilità del braccio, la forza di spinta verticale e la stabilità della spalla.'),
('shoulders', 'zh', '肩部', '主要由三角肌（前束、中束和后束）组成的关节复合体；对于手臂灵活性、垂直推举力量和肩部稳定性至关重要。'),
('shoulders', 'ja', '肩', '主に三角筋（前部、中部、後部）から成る関節複合体で、腕の可動性、垂直方向の押す力、肩の安定性に不可欠です。'),
('shoulders', 'ko', '어깨', '주로 삼각근(전면, 측면, 후면)으로 구성된 관절 복합체로, 팔의 가동성, 수직 미는 힘 및 어깨 안정성에 필수적입니다.'),
('shoulders', 'ar', 'الأكتاف', 'مجمع مفصلي يتكون بشكل أساسي من العضلة الدالية (الأمامية والجانبية والخلفية)؛ وهو ضروري لحركة الذراع وقوة الدفع الرأسي واستقرار الكتف.'),
('shoulders', 'hi', 'कंधे (शोल्डर्स)', 'मुख्य रूप से डेल्टोइड्स (अग्र, पार्श्व और पश्च) से बना संयुक्त कॉम्प्लेक्स; यह हाथ की गतिशीलता, ऊर्ध्वाधर धक्का देने की शक्ति और कंधे की स्थिरता के लिए महत्वपूर्ण है।'),
('shoulders', 'ru', 'Плечи', 'Суставной комплекс, образованный преимущественно дельтовидными мышцами (передней, латеральной и задней); критически важен для подвижности руки, вертикальной жимовой силы и стабильности плечевого сустава.'),
('shoulders', 'nl', 'Schouders', 'Gewrichtscomplex dat voornamelijk wordt gevormd door de deltoideus (anterior, lateraal en posterieur); essentieel voor armmobiliteit, verticale duwkracht en schouderstabiliteit.'),
('shoulders', 'sv', 'Axlar', 'Ledkomplex som främst bildas av deltoideus (anterior, lateral och posterior); avgörande för armrörlighet, vertikal presskraft och axelstabilitet.'),
('shoulders', 'pl', 'Barki', 'Kompleks stawowy tworzony głównie przez mięsień naramienny (przedni, boczny i tylny); jest kluczowy dla mobilności ramienia, siły wypychania pionowego i stabilności barku.'),
('shoulders', 'id', 'Bahu', 'Kompleks sendi yang terutama dibentuk oleh deltoid (anterior, lateral, dan posterior); penting untuk mobilitas lengan, kekuatan mendorong vertikal, dan stabilitas bahu.'),
('shoulders', 'bn', 'কাঁধ (শোল্ডার)', 'প্রাথমিকভাবে ডেল্টয়েড (অ্যান্টেরিয়র, ল্যাটারাল এবং পোস্টেরিয়র) দ্বারা গঠিত জয়েন্ট কমপ্লেক্স; যা হাতের নড়াচড়া, উল্লম্ব ধাক্কা দেওয়ার শক্তি এবং কাঁধের স্থিতিশীলতার জন্য অপরিহার্য।'),
('shoulders', 'vi', 'Vai', 'Phức hợp khớp được hình thành chủ yếu bởi cơ delta (trước, giữa và sau); thiết yếu cho sự linh hoạt của cánh tay, lực đẩy dọc và sự ổn định của vai.'),
('shoulders', 'fa', 'شانه‌ها', 'مجموعه مفصلی که عمدتاً از عضله دلتوئید (قدامی، میانی و خلفی) تشکیل شده است؛ برای تحرک بازو، قدرت فشاری عمودی و ثبات شانه ضروری است.');