INSERT OR IGNORE INTO body_target_info (slug, lang, title, "desc") VALUES
('tibialis', 'es', 'Tibial', 'Músculo situado en la parte anterior de la pierna, responsable de la dorsiflexión del pie y la estabilización del tobillo.'),
('tibialis', 'en', 'Tibialis', 'Muscle located on the anterior aspect of the lower leg, responsible for dorsiflexion of the foot and ankle stabilization.'),
('tibialis', 'pt', 'Tibial', 'Músculo situado na parte anterior da perna, responsável pela dorsiflexão do pé e estabilização do tornozelo.'),
('tibialis', 'fr', 'Tibial', 'Muscle situé sur la partie antérieure de la jambe, responsable de la dorsiflexion du pied et de la stabilisation de la cheville.'),
('tibialis', 'de', 'Tibialis (Schienbeinmuskel)', 'Muskel an der Vorderseite des Unterschenkels, verantwortlich für die Dorsalflexion des Fußes und die Stabilisierung des Sprunggelenks.'),
('tibialis', 'it', 'Tibiale', 'Muscolo situato nella parte anteriore della gamba, responsabile della dorsiflessione del piede e della stabilizzazione della caviglia.'),
('tibialis', 'zh', '胫骨肌', '位于小腿前侧的肌肉，负责足部背屈和踝关节稳定性。'),
('tibialis', 'ja', '前脛骨筋', '下腿前側に位置する筋肉で、足首の背屈と足関節の安定化を担います。'),
('tibialis', 'ko', '전경골근', '하퇴 전면에 위치한 근육으로, 발목의 배굴과 발목 관절 안정화 역할을 합니다.'),
('tibialis', 'ar', 'العضلة الظنبوبية', 'عضلة تقع في الجزء الأمامي من الساق، وهي مسؤولة عن ثني القدم ظهرياً وتثبيت الكاحل.'),
('tibialis', 'hi', 'टिबियलिस', 'निचले पैर के सामने स्थित मांसपेशी, जो पैर के डोर्सिफ्लेक्सन और टखने की स्थिरता के लिए जिम्मेदार है।'),
('tibialis', 'ru', 'Передняя большеберцовая мышца', 'Мышца, расположенная на передней части голени, отвечающая за тыльное сгибание стопы и стабилизацию голеностопного сустава.'),
('tibialis', 'nl', 'Tibialis (scheenbeen spier)', 'Spier aan de voorzijde van het onderbeen, verantwoordelijk voor dorsaalflexie van de voet en stabilisatie van de enkel.'),
('tibialis', 'sv', 'Tibialis (skenbensmuskel)', 'Muskel belägen på underbenets framsida, ansvarig för fotens dorsalflexion och ankelstabilisering.'),
('tibialis', 'pl', 'Mięsień piszczelowy', 'Mięsień znajdujący się z przodu podudzia, odpowiedzialny za zgięcie grzbietowe stopy i stabilizację stawu skokowego.'),
('tibialis', 'id', 'Tibialis', 'Otot yang terletak di bagian depan kaki bawah, bertanggung jawab untuk dorsifleksi kaki dan stabilisasi pergelangan kaki.'),
('tibialis', 'bn', 'টিবিয়ালিস', 'পায়ের নিচের অংশের সামনে অবস্থিত পেশী, যা পায়ের ডরসিফ্লেকশন এবং গোড়ালির স্থিতিশীলতার জন্য দায়ী।'),
('tibialis', 'vi', 'Cơ chày', 'Cơ nằm ở mặt trước cẳng chân, chịu trách nhiệm gập mu bàn chân và ổn định khớp cổ chân.'),
('tibialis', 'fa', 'عضله تیبیالیس (درشت‌نی قدامی)', 'عضله واقع در بخش قدامی ساق پا، مسئول دورسی‌فلکشن (خم کردن رو به بالای) مچ پا و ثبات مفصل مچ پا.');