INSERT OR IGNORE INTO body_target_info (slug, lang, title, "desc") VALUES
('trapezius', 'es', 'Trapecio', 'Músculo grande que abarca la parte superior de la espalda y el cuello; crucial para el movimiento de la escápula, la estabilidad cervical y la postura.'),
('trapezius', 'en', 'Trapezius', 'Large muscle covering the upper back and neck; crucial for scapular movement, cervical stability, and posture.'),
('trapezius', 'pt', 'Trapézio', 'Músculo grande que abrange a parte superior das costas e o pescoço; crucial para o movimento da escápula, estabilidade cervical e postura.'),
('trapezius', 'fr', 'Trapèze', 'Grand muscle couvrant le haut du dos et le cou ; crucial pour le mouvement de l omoplate, la stabilité cervicale et la posture.'),
('trapezius', 'de', 'Trapezmuskel', 'Großer Muskel, der den oberen Rücken und den Nacken bedeckt; entscheidend für die Bewegung des Schulterblatts, die Stabilität der Halswirbelsäule und die Körperhaltung.'),
('trapezius', 'it', 'Trapezio', 'Grande muscolo che copre la parte superiore della schiena e il collo; cruciale per il movimento della scapola, la stabilità cervicale e la postura.'),
('trapezius', 'zh', '斜方肌', '覆盖上背部和颈部的大肌肉；对于肩胛骨运动、颈椎稳定性和姿势至关重要。'),
('trapezius', 'ja', '僧帽筋', '上背部から首にかけて広がる大きな筋肉で、肩甲骨の動き、頸椎の安定性、および姿勢維持に重要です。'),
('trapezius', 'ko', '승모근', '등 상부와 목을 덮고 있는 큰 근육으로, 견갑골의 움직임, 경추 안정성 및 자세 유지에 핵심적입니다.'),
('trapezius', 'ar', 'العضلة شبه المنحرفة', 'عضلة كبيرة تغطي الجزء العلوي من الظهر والرقبة؛ وهي حاسمة لحركة لوح الكتف واستقرار الرقبة والوضعية.'),
('trapezius', 'hi', 'ट्रैपेज़ियस (मांसपेशी)', 'ऊपरी पीठ और गर्दन को कवर करने वाली बड़ी मांसपेशी; जो स्कैपुला की गति, सर्वाइकल स्थिरता और मुद्रा के लिए महत्वपूर्ण है।'),
('trapezius', 'ru', 'Трапециевидная мышца', 'Крупная мышца, покрывающая верхнюю часть спины и шею; важна для движения лопатки, стабильности шейного отдела и осанки.'),
('trapezius', 'nl', 'Trapezius (monnikskapspier)', 'Grote spier die de bovenrug en nek bedekt; cruciaal voor beweging van het schouderblad, cervicale stabiliteit en houding.'),
('trapezius', 'sv', 'Trapezius (kappmuskel)', 'Stor muskel som täcker övre ryggen och nacken; avgörande för skulderbladets rörelse, cervikal stabilitet och hållning.'),
('trapezius', 'pl', 'Mięsień czworoboczny grzbietu', 'Duży mięsień pokrywający górną część pleców i szyję; kluczowy dla ruchu łopatki, stabilności odcinka szyjnego i postawy.'),
('trapezius', 'id', 'Trapezius', 'Otot besar yang menutupi punggung atas dan leher; sangat penting untuk pergerakan skapula, stabilitas servikal, dan postur.'),
('trapezius', 'bn', 'ট্র্যাপেজিয়াস', 'পিঠের উপরের অংশ এবং ঘাড় জুড়ে থাকা বড় পেশী; যা স্ক্যাপুলার নড়াচড়া, ঘাড়ের স্থিতিশীলতা এবং শারীরিক ভঙ্গি বজায় রাখার জন্য গুরুত্বপূর্ণ।'),
('trapezius', 'vi', 'Cơ thang', 'Cơ lớn bao phủ phần lưng trên và cổ; thiết yếu cho chuyển động xương bả vai, ổn định cột sống cổ và tư thế.'),
('trapezius', 'fa', 'عضله ذوزنقه‌ای', 'عضله بزرگ پوشاننده بخش بالایی پشت و گردن؛ حیاتی برای حرکت کتف، ثبات ستون فقرات گردنی و وضعیت بدن.');