INSERT OR IGNORE INTO body_target_info (slug, lang, title, "desc") VALUES
('triceps', 'es', 'Tríceps', 'Músculo de la parte posterior del brazo formado por tres cabezas, encargado de la extensión del codo.'),
('triceps', 'en', 'Triceps', 'Muscle on the back of the arm consisting of three heads, responsible for elbow extension.'),
('triceps', 'pt', 'Tríceps', 'Músculo da parte posterior do braço formado por três cabeças, responsável pela extensão do cotovelo.'),
('triceps', 'fr', 'Triceps', 'Muscle de la partie postérieure du bras composé de trois chefs, responsable de l extension du coude.'),
('triceps', 'de', 'Trizeps', 'Muskel an der Rückseite des Oberarms, bestehend aus drei Köpfen, verantwortlich für die Ellbogenstreckung.'),
('triceps', 'it', 'Tricipiti', 'Muscolo della parte posteriore del braccio formato da tre capi, responsabile dell estensione del gomito.'),
('triceps', 'zh', '肱三头肌', '位于上臂后侧的肌肉，由三个头组成，负责伸肘动作。'),
('triceps', 'ja', '上腕三頭筋', '上腕後面に位置する筋肉で、3つの頭から成り、肘の伸展を担います。'),
('triceps', 'ko', '삼두근', '팔 뒤쪽에 위치한 세 개의 근육 머리로 구성된 근육으로, 팔꿈치를 펴는 역할을 합니다.'),
('triceps', 'ar', 'عضلات ثلاثية الرؤوس (الترايسيبس)', 'عضلة في الجزء الخلفي من الذراع تتكون من ثلاثة رؤوس، وهي مسؤولة عن بسط المرفق.'),
('triceps', 'hi', 'ट्राइसेप्स', 'ऊपरी बांह के पिछले हिस्से में मांसपेशी जिसमें तीन सिर होते हैं, जो कोहनी को सीधा करने के लिए जिम्मेदार है।'),
('triceps', 'ru', 'Трицепс', 'Мышца задней части плеча, состоящая из трех головок, отвечающая за разгибание локтя.'),
('triceps', 'nl', 'Triceps', 'Spier aan de achterzijde van de bovenarm bestaande uit drie koppen, verantwoordelijk voor elleboogextensie.'),
('triceps', 'sv', 'Triceps', 'Muskel på överarmens baksida bestående av tre huvuden, ansvarig för armbågsextension.'),
('triceps', 'pl', 'Mięsień trójgłowy ramienia', 'Mięsień tylnej części ramienia składający się z trzech głów, odpowiedzialny za prostowanie łokcia.'),
('triceps', 'id', 'Trisep', 'Otot di bagian belakang lengan yang terdiri dari tiga kepala, bertanggung jawab untuk ekstensi siku.'),
('triceps', 'bn', 'ট্রাইসেপস', 'উপরের বাহুর পিছনের পেশী যা তিনটি মাথা নিয়ে গঠিত, যা কনুই সোজা করার জন্য দায়ী।'),
('triceps', 'vi', 'Cơ tam đầu', 'Cơ mặt sau cánh tay gồm ba đầu, chịu trách nhiệm duỗi khuỷu tay.'),
('triceps', 'fa', 'عضلات سه‌سر بازویی', 'عضله بخش پشتی بازو متشکل از سه سر، مسئول باز کردن آرنج.')