-- 1. Registro
INSERT OR IGNORE INTO exercises (slug, img, video, difficulty) 
VALUES 
('assisted-pull-up', 'assisted-pull-up.jpg', 'assisted-pull-up.mp4', 'beginner'),
('assisted-close-grip-pull-up', 'assisted-close-grip-pull-up.jpg', 'assisted-close-grip-pull-up.mp4', 'beginner');

-- 2. Relación músculo
INSERT OR IGNORE INTO exercise_body_target (exercise_slug, body_target_slug) 
VALUES 
('assisted-close-grip-pull-up', 'back');

-- 3. Relación alternativa
INSERT OR IGNORE INTO exercise_alternative (exercise_slug, alternative_slug) 
VALUES 
('assisted-close-grip-pull-up', 'assisted-pull-up');

-- 4. Info multiidioma
INSERT OR IGNORE INTO exercises_info (slug, lang, title, description, benefits, instructions, tips, restrictions, mistakes) VALUES 
('assisted-close-grip-pull-up', 'es', 'Dominada asistida agarre cerrado', 'Dominada con asistencia mecánica y agarre estrecho.', 'Desarrolla el dorsal con mayor énfasis en los brazos.', 'Apoya las rodillas en la plataforma, sujeta la barra con agarre estrecho y elévate.', 'Controla la bajada para maximizar el trabajo muscular.', 'Evitar si hay dolor severo en hombros.', 'Usar demasiado impulso en la plataforma.'),
('assisted-close-grip-pull-up', 'en', 'Assisted close-grip pull-up', 'Pull-up with mechanical assistance and narrow grip.', 'Develops lats with more arm emphasis.', 'Place knees on the platform, grasp the bar with a narrow grip, and pull yourself up.', 'Control the descent to maximize muscle work.', 'Avoid if severe shoulder pain exists.', 'Using too much momentum from the platform.'),
('assisted-close-grip-pull-up', 'pt', 'Barra fixa assistida pegada fechada', 'Barra fixa com assistência mecânica e pegada estreita.', 'Desenvolve os dorsais com maior ênfase nos braços.', 'Apoie os joelhos na plataforma, segure a barra com pegada estreita e eleve-se.', 'Controle a descida para maximizar o trabalho muscular.', 'Evitar se houver dor severa nos ombros.', 'Usar impulso excessivo na plataforma.'),
('assisted-close-grip-pull-up', 'fr', 'Tractions assistées prise serrée', 'Tractions avec assistance mécanique et prise étroite.', 'Développe les dorsaux en mettant davantage l''accent sur les bras.', 'Placez les genoux sur la plateforme, saisissez la barre avec une prise étroite et soulevez-vous.', 'Contrôlez la descente pour maximiser le travail musculaire.', 'À éviter en cas de douleur sévère à l''épaule.', 'Utiliser trop d''élan depuis la plateforme.'),
('assisted-close-grip-pull-up', 'de', 'Unterstützte Klimmzüge im engen Griff', 'Klimmzug mit mechanischer Unterstützung und engem Griff.', 'Entwickelt den Lat mit Fokus auf die Arme.', 'Knie auf die Plattform stellen, Stange im engen Griff greifen und hochziehen.', 'Abwärtsbewegung kontrollieren, um den Muskelreiz zu maximieren.', 'Bei starken Schulterschmerzen vermeiden.', 'Zu viel Schwung von der Plattform nutzen.'),
('assisted-close-grip-pull-up', 'it', 'Trazioni assistite presa stretta', 'Trazioni con assistenza meccanica e presa stretta.', 'Sviluppa i dorsali con maggiore enfasi sulle braccia.', 'Appoggia le ginocchia sulla piattaforma, afferra la barra con presa stretta e sollevati.', 'Controlla la discesa per massimizzare il lavoro muscolare.', 'Evitare in caso di forti dolori alla spalla.', 'Usare troppo slancio dalla piattaforma.'),
('assisted-close-grip-pull-up', 'zh', '窄握辅助引体向上', '利用机械辅助进行窄握引体向上。', '在锻炼背阔肌的同时更多地调动双臂。', '将膝盖放在平台上，窄握抓住单杠，将自己拉起。', '控制下落过程以最大化肌肉参与。', '如有严重的肩部疼痛，请避免。', '利用平台产生过多的惯性。'),
('assisted-close-grip-pull-up', 'ja', 'アシスト・クローズグリッププルアップ', '機械的な補助と狭いグリップで行う懸垂。', '背中の広背筋を鍛えつつ、腕の関与を高めます。', '膝をプラットフォームに乗せ、狭いグリップでバーを掴んで引き上げます。', '筋肉への刺激を最大化するために下降動作をコントロールしてください。', '肩に激しい痛みがある場合は避けてください。', 'プラットフォームの反動を使いすぎること。'),
('assisted-close-grip-pull-up', 'ko', '어시스트 클로즈 그립 풀업', '기계식 도움을 받는 좁은 그립 풀업.', '팔에 더 많은 비중을 두어 광배근 발달.', '무릎을 플랫폼에 대고 좁은 그립으로 바를 잡은 뒤 몸을 당김.', '내려올 때 근육 자극을 위해 속도 제어.', '심각한 어깨 통증 시 피할 것.', '플랫폼에서 반동을 과도하게 사용하는 것.'),
('assisted-close-grip-pull-up', 'ar', 'تمرين سحب الجسم المساعد بقبضة ضيقة', 'تمرين سحب الجسم مع مساعدة ميكانيكية وقبضة ضيقة.', 'يطور العضلة الظهرية مع مزيد من التركيز على الذراعين.', 'ضع ركبتيك على المنصة، وأمسك القضيب بقبضة ضيقة، وارفع نفسك.', 'تحكم في النزول لزيادة العمل العضلي.', 'تجنب في حالة وجود ألم شديد في الكتف.', 'استخدام زخم كبير من المنصة.'),
('assisted-close-grip-pull-up', 'hi', 'असिस्टेड क्लोज़-ग्रिप पुल-अप', 'यांत्रिक सहायता और संकीर्ण पकड़ के साथ पुल-अप।', 'हाथों पर अधिक जोर देते हुए लैट्स का विकास करता है।', 'घुटनों को प्लेटफॉर्म पर रखें, संकीर्ण पकड़ के साथ बार पकड़ें और खुद को ऊपर उठाएं।', 'मांसपेशियों के काम को अधिकतम करने के लिए उतरते समय नियंत्रण रखें।', 'यदि कंधे में गंभीर दर्द हो तो न करें।', 'प्लेटफॉर्म से बहुत अधिक गति का उपयोग करना।'),
('assisted-close-grip-pull-up', 'ru', 'Подтягивания в гравитроне узким хватом', 'Подтягивания с механической поддержкой узким хватом.', 'Развивает широчайшие мышцы с акцентом на руки.', 'Поставьте колени на платформу, возьмитесь за перекладину узким хватом и подтянитесь.', 'Контролируйте опускание для максимальной проработки.', 'Избегайте при сильных болях в плечах.', 'Использование чрезмерного импульса от платформы.'),
('assisted-close-grip-pull-up', 'nl', 'Assisted close-grip pull-up', 'Pull-up met mechanische hulp en nauwe greep.', 'Ontwikkelt de lats met meer nadruk op de armen.', 'Plaats de knieën op het platform, pak de stang smal vast en trek jezelf op.', 'Controleer de neerwaartse fase voor maximale spierbelasting.', 'Vermijden bij ernstige schouderpijn.', 'Te veel momentum uit het platform halen.'),
('assisted-close-grip-pull-up', 'sv', 'Assisterad chins med smalt grepp', 'Chins med mekaniskt stöd och smalt grepp.', 'Utvecklar ryggmusklerna med mer fokus på armarna.', 'Placera knäna på plattformen, ta ett smalt grepp om stången och dra dig upp.', 'Kontrollera nedfarten för att maximera muskelaktiveringen.', 'Undvik vid svår axelsmärta.', 'Använd för mycket sving från plattformen.'),
('assisted-close-grip-pull-up', 'pl', 'Podciąganie wspomagane chwytem wąskim', 'Podciąganie ze wsparciem mechanicznym i chwytem wąskim.', 'Rozwija mięśnie najszersze z większym naciskiem na ramiona.', 'Oprzyj kolana na platformie, chwyć drążek wąsko i podciągnij się.', 'Kontroluj opuszczanie, aby zmaksymalizować pracę mięśni.', 'Unikaj w przypadku silnego bólu barku.', 'Używanie zbyt dużego impetu z platformy.'),
('assisted-close-grip-pull-up', 'id', 'Assisted close-grip pull-up', 'Pull-up dengan bantuan mekanis dan genggaman sempit.', 'Mengembangkan lat dengan penekanan lebih pada lengan.', 'Letakkan lutut di platform, pegang palang dengan genggaman sempit, dan tarik tubuh Anda.', 'Kontrol penurunan untuk memaksimalkan kerja otot.', 'Hindari jika ada nyeri bahu yang parah.', 'Menggunakan terlalu banyak momentum dari platform.'),
('assisted-close-grip-pull-up', 'bn', 'অ্যাসিস্টেড ক্লোজ-গ্রিপ পুল-আপ', 'মেকানিক্যাল সাপোর্ট এবং সরু গ্রিপের সাহায্যে পুল-আপ।', 'হাতে বেশি জোর দিয়ে ল্যাটস ডেভেলপ করে।', 'প্ল্যাটফর্মে হাঁটু রাখুন, সরু গ্রিপে বার ধরে ওপরে তুলুন।', 'পেশির কাজ সর্বোচ্চ করতে নামার সময় নিয়ন্ত্রণ করুন।', 'কাঁধে তীব্র ব্যথা থাকলে এটি করবেন না।', 'প্ল্যাটফর্ম থেকে অতিরিক্ত মোমেন্টাম নেওয়া।'),
('assisted-close-grip-pull-up', 'vi', 'Hít xà hỗ trợ tay hẹp', 'Bài tập hít xà với hỗ trợ cơ học và tay nắm hẹp.', 'Phát triển cơ lưng xô với sự tham gia nhiều của cánh tay.', 'Đặt đầu gối lên bệ, nắm thanh xà bằng tay hẹp và kéo người lên.', 'Kiểm soát quá trình hạ người để tối đa hóa hiệu quả.', 'Tránh tập nếu đau vai dữ dội.', 'Dùng quá nhiều quán tính từ bệ hỗ trợ.'),
('assisted-close-grip-pull-up', 'fa', 'بارفیکس کمکي با دست جمع', 'بارفیکس با کمک مکانيکي و دست جمع.', 'عضلات پشتي را با تمرکز بيشتر بر بازوها توسعه مي‌دهد.', 'زانوها را روي پلتفرم قرار دهيد، ميله را با دست جمع بگيريد و خود را بالا بکشيد.', 'فرود را براي به حداکثر رساندن درگيري عضلات کنترل کنيد.', 'در صورت درد شديد شانه انجام ندهيد.', 'استفاده از شتاب بيش از حد پلتفرم.');