-- 1. Registro
INSERT OR IGNORE INTO exercises (slug, img, video, difficulty) 
VALUES 
('lat-pull-down-normal-grip', 'lat-pull-down-normal-grip.jpg', 'lat-pull-down-normal-grip.mp4', 'beginner'),
('cable-neutral-grip-wide-pulldown', 'cable-neutral-grip-wide-pulldown.jpg', 'cable-neutral-grip-wide-pulldown.mp4', 'beginner');

-- 2. Relación músculo
INSERT OR IGNORE INTO exercise_body_target (exercise_slug, body_target_slug) 
VALUES 
('cable-neutral-grip-wide-pulldown', 'back');

-- 3. Relación alternativa
INSERT OR IGNORE INTO exercise_alternative (exercise_slug, alternative_slug) 
VALUES 
('cable-neutral-grip-wide-pulldown', 'lat-pull-down-normal-grip');

-- 4. Info multiidioma
INSERT OR IGNORE INTO exercises_info (slug, lang, title, description, benefits, instructions, tips, restrictions, mistakes) VALUES 
('cable-neutral-grip-wide-pulldown', 'es', 'Jalón al pecho agarre neutro ancho', 'Jalón en polea alta con agarre neutro y amplio.', 'Mejor activación del dorsal ancho con menor estrés articular.', 'Siéntate, sujeta el agarre neutro amplio y tira hacia la parte superior del pecho.', 'Mantén el pecho erguido y los codos dirigidos hacia abajo.', 'Evitar con dolor severo en hombros.', 'Inclinar demasiado el torso hacia atrás.'),
('cable-neutral-grip-wide-pulldown', 'en', 'Cable neutral-grip wide pulldown', 'High pulley pulldown using a wide neutral grip.', 'Improved lat activation with less joint stress.', 'Sit, grasp the wide neutral handle, and pull towards upper chest.', 'Keep chest upright and elbows directed downwards.', 'Avoid with severe shoulder pain.', 'Leaning the torso too far back.'),
('cable-neutral-grip-wide-pulldown', 'pt', 'Puxada alta pegada neutra aberta', 'Puxada alta no cabo usando pegada neutra aberta.', 'Melhor ativação do latíssimo com menos estresse articular.', 'Sente-se, segure o puxador neutro aberto e puxe em direção à parte superior do peito.', 'Mantenha o peito erguido e os cotovelos direcionados para baixo.', 'Evitar com dor severa nos ombros.', 'Inclinar demais o tronco para trás.'),
('cable-neutral-grip-wide-pulldown', 'fr', 'Tirage poitrine poulie haute prise neutre large', 'Tirage à la poulie haute avec prise neutre large.', 'Meilleure activation des dorsaux avec moins de stress articulaire.', 'Asseyez-vous, saisissez la poignée neutre large et tirez vers le haut de la poitrine.', 'Gardez la poitrine haute et les coudes dirigés vers le bas.', 'À éviter en cas de douleur sévère à l''épaule.', 'Incliner le buste trop loin en arrière.'),
('cable-neutral-grip-wide-pulldown', 'de', 'Latziehen im neutralen breiten Griff', 'Latziehen am hohen Kabelzug im neutralen, breiten Griff.', 'Bessere Aktivierung des Latissimus bei weniger Gelenkbelastung.', 'Hinsetzen, neutralen breiten Griff fassen und zur oberen Brust ziehen.', 'Brust aufrecht halten und Ellbogen nach unten richten.', 'Bei starken Schulterschmerzen vermeiden.', 'Oberkörper zu weit zurücklehnen.'),
('cable-neutral-grip-wide-pulldown', 'it', 'Lat machine presa neutra larga', 'Lat machine con presa neutra e ampia.', 'Migliore attivazione del gran dorsale con meno stress articolare.', 'Siediti, afferra la maniglia neutra larga e tira verso la parte alta del petto.', 'Mantieni il petto eretto e i gomiti rivolti verso il basso.', 'Evitare in caso di forti dolori alla spalla.', 'Inclinare troppo il busto all''indietro.'),
('cable-neutral-grip-wide-pulldown', 'zh', '宽距中性握距高位下拉', '使用中性宽握距进行的高位下拉动作。', '更好的背阔肌激活，且关节压力较小。', '坐下，抓住宽距中性把手，向胸部上方拉动。', '保持胸部挺直，手肘向下指。', '如有严重的肩部疼痛，请避免。', '躯干过度向后倾斜。'),
('cable-neutral-grip-wide-pulldown', 'ja', 'ケーブル・ニュートラルグリップ・ワイドプルダウン', 'ニュートラルでワイドなグリップを使用したハイプーリー・プルダウン。', '関節への負担を抑えつつ広背筋を効果的に刺激します。', '座り、ワイドなニュートラルグリップを掴んで上胸部に向けて引きます。', '胸を張り、肘を真下に向けるようにしてください。', '肩に激しい痛みがある場合は避けてください。', '体幹を後ろに倒しすぎること。'),
('cable-neutral-grip-wide-pulldown', 'ko', '케이블 뉴트럴 그립 와이드 풀다운', '뉴트럴 와이드 그립을 이용한 하이 풀리 풀다운.', '관절 부담을 줄이면서 광배근 활성화.', '앉아서 뉴트럴 와이드 그립을 잡고 윗가슴 쪽으로 당김.', '가슴을 펴고 팔꿈치를 아래로 향하게 함.', '심한 어깨 통증 시 피할 것.', '상체를 과도하게 뒤로 젖히는 것.'),
('cable-neutral-grip-wide-pulldown', 'ar', 'تمرين سحب لأسفل بقبضة محايدة واسعة', 'سحب الجسم باستخدام بكرة عالية بقبضة محايدة واسعة.', 'تفعيل أفضل للعضلة الظهرية مع إجهاد أقل للمفاصل.', 'اجلس، أمسك المقبض المحايد الواسع واسحب نحو الجزء العلوي من الصدر.', 'حافظ على استقامة الصدر ووجه المرفقين للأسفل.', 'تجنب في حالة وجود ألم شديد في الكتف.', 'إمالة الجذع للخلف بشكل مفرط.'),
('cable-neutral-grip-wide-pulldown', 'hi', 'केबल न्यूट्रल-ग्रिप वाइड पुलडाउन', 'न्यूट्रल वाइड ग्रिप का उपयोग करके हाई पुली पुलडाउन।', 'कम जोड़ों के तनाव के साथ बेहतर लैट सक्रियता।', 'बैठें, चौड़े न्यूट्रल हैंडल को पकड़ें और ऊपरी छाती की ओर खींचें।', 'छाती को सीधा रखें और कोहनियों को नीचे की ओर रखें।', 'यदि कंधे में गंभीर दर्द हो तो न करें।', 'धड़ को बहुत अधिक पीछे की ओर झुकाना।'),
('cable-neutral-grip-wide-pulldown', 'ru', 'Тяга верхнего блока широким нейтральным хватом', 'Тяга верхнего блока широким нейтральным хватом.', 'Лучшая активация широчайших при меньшей нагрузке на суставы.', 'Сядьте, возьмитесь за широкую нейтральную рукоять и тяните к верхней части груди.', 'Держите грудь ровно, локти направлены вниз.', 'Избегайте при сильных болях в плечах.', 'Чрезмерное отклонение корпуса назад.'),
('cable-neutral-grip-wide-pulldown', 'nl', 'Cable neutral-grip wide pulldown', 'High pulley pulldown met een brede neutrale greep.', 'Betere activatie van de lats met minder gewrichtsbelasting.', 'Ga zitten, pak de brede neutrale handgreep en trek naar de bovenkant van de borst.', 'Houd borst rechtop en ellebogen naar beneden gericht.', 'Vermijden bij ernstige schouderpijn.', 'Het bovenlichaam te ver naar achteren leunen.'),
('cable-neutral-grip-wide-pulldown', 'sv', 'Kabelrodd med brett neutralt grepp', 'Latsdrag med brett neutralt grepp.', 'Bättre aktivering av ryggmusklerna med mindre ledpåfrestning.', 'Sitt ner, greppa det breda neutrala handtaget och dra mot övre delen av bröstet.', 'Håll bröstet upprätt och armbågarna riktade nedåt.', 'Undvik vid svår axelsmärta.', 'Att luta överkroppen för långt bakåt.'),
('cable-neutral-grip-wide-pulldown', 'pl', 'Ściąganie drążka wyciągu górnego chwytem neutralnym szerokim', 'Ściąganie drążka z wyciągu górnego przy użyciu szerokiego chwytu neutralnego.', 'Lepsza aktywacja mięśni najszerszych przy mniejszym obciążeniu stawów.', 'Usiądź, chwyć szeroki uchwyt neutralny i ściągaj do górnej części klatki.', 'Utrzymuj klatkę wyprostowaną, a łokcie skierowane w dół.', 'Unikaj w przypadku silnego bólu barku.', 'Zbyt mocne odchylanie tułowia do tyłu.'),
('cable-neutral-grip-wide-pulldown', 'id', 'Cable neutral-grip wide pulldown', 'Lat pulldown menggunakan katrol tinggi dengan genggaman netral lebar.', 'Aktivasi lat yang lebih baik dengan tekanan sendi yang lebih sedikit.', 'Duduk, pegang pegangan netral lebar, dan tarik ke arah dada bagian atas.', 'Jaga dada tegak dan siku mengarah ke bawah.', 'Hindari jika ada nyeri bahu yang parah.', 'Mencondongkan batang tubuh terlalu jauh ke belakang.'),
('cable-neutral-grip-wide-pulldown', 'bn', 'কেবল নিউট্রাল-গ্রিপ ওয়াইড পুলডাউন', 'নিউট্রাল ওয়াইড গ্রিপ ব্যবহার করে হাই পুলি পুলডাউন।', 'কম জয়েন্ট স্ট্রেস সহ ল্যাটের উন্নত সক্রিয়তা।', 'বসুন, ওয়াইড নিউট্রাল হ্যান্ডেল ধরুন এবং বুকের ওপরের দিকে টানুন।', 'বুক সোজা রাখুন এবং কনুই নিচের দিকে রাখুন।', 'কাঁধে তীব্র ব্যথা থাকলে এটি করবেন না।', 'ধড় খুব বেশি পেছনের দিকে ঝুকানো।'),
('cable-neutral-grip-wide-pulldown', 'vi', 'Kéo cáp tay hẹp trung tính', 'Bài tập kéo xô với tay nắm trung tính rộng.', 'Kích hoạt cơ xô tốt hơn với ít áp lực khớp.', 'Ngồi, nắm tay cầm trung tính rộng và kéo về phía ngực trên.', 'Giữ ngực thẳng và khuỷu tay hướng xuống dưới.', 'Tránh tập nếu đau vai dữ dội.', 'Ngả thân người quá xa về sau.'),
('cable-neutral-grip-wide-pulldown', 'fa', 'بارفیکس با سیم‌کش با دست خنثي باز', 'بارفیکس با قرقره بالا با دست خنثي باز.', 'فعال‌سازي بهتر عضلات پشتي با فشار کمتر بر مفاصل.', 'بنشينيد، دسته دست خنثي باز را بگيريد و به سمت بالاي سينه بکشيد.', 'سينه را صاف و آرنج‌ها را به سمت پايين نگه داريد.', 'در صورت درد شديد شانه انجام ندهيد.', 'خم کردن بيش از حد تنه به عقب.');