-- 1. Registro
INSERT OR IGNORE INTO exercises (slug, img, video, difficulty) 
VALUES 
('barbell-bent-over-row', 'barbell-bent-over-row.jpg', 'barbell-bent-over-row.mp4', 'intermediate'),
('cambered-bar-lying-row', 'cambered-bar-lying-row.jpg', 'cambered-bar-lying-row.mp4', 'advanced');

-- 2. Relación músculo (Solo ejercicio actual)
INSERT OR IGNORE INTO exercise_body_target (exercise_slug, body_target_slug) 
VALUES 
('cambered-bar-lying-row', 'back');

-- 3. Relación alternativa
INSERT OR IGNORE INTO exercise_alternative (exercise_slug, alternative_slug) 
VALUES 
('cambered-bar-lying-row', 'barbell-bent-over-row');

-- 4. Info multiidioma
INSERT OR IGNORE INTO exercises_info (slug, lang, title, description, benefits, instructions, tips, restrictions, mistakes) VALUES 
('cambered-bar-lying-row', 'es', 'Remo con barra curva acostado', 'Remo realizado acostado boca abajo en un banco con barra curva.', 'Estabilización del core y enfoque en trapecio y dorsales.', 'Acostado boca abajo en un banco inclinado, tracciona la barra hacia el pecho.', 'Mantén el pecho pegado al banco durante todo el movimiento.', 'Evitar si existen problemas severos de columna o espalda.', 'Levantar el pecho del banco al realizar el tirón.'),
('cambered-bar-lying-row', 'en', 'Cambered bar lying row', 'Row performed lying face down on a bench using a cambered bar.', 'Core stabilization and focus on traps and lats.', 'Lying face down on an incline bench, pull the bar towards your chest.', 'Keep your chest pressed against the bench throughout the movement.', 'Avoid if there are severe spine or back issues.', 'Lifting your chest off the bench while pulling.'),
('cambered-bar-lying-row', 'pt', 'Remada com barra curvada deitado', 'Remada feita deitado de bruços em um banco usando barra curvada.', 'Estabilização do core e foco em trapézio e dorsais.', 'Deitado de bruços em um banco inclinado, puxe a barra em direção ao peito.', 'Mantenha o peito pressionado contra o banco durante todo o movimento.', 'Evitar se houver problemas graves de coluna ou costas.', 'Levantar o peito do banco ao realizar a puxada.'),
('cambered-bar-lying-row', 'fr', 'Tirage allongé barre cambrée', 'Tirage effectué allongé face contre un banc avec une barre cambrée.', 'Stabilisation du tronc et ciblage des trapèzes et dorsaux.', 'Allongé face contre un banc incliné, tirez la barre vers votre poitrine.', 'Gardez votre poitrine pressée contre le banc pendant tout le mouvement.', 'À éviter en cas de problèmes graves de colonne vertébrale ou de dos.', 'Décoller la poitrine du banc lors du tirage.'),
('cambered-bar-lying-row', 'de', 'Liegendes Rudern mit der Cambered Bar', 'Rudern in Bauchlage auf einer Bank mit einer gebogenen Stange.', 'Rumpfstabilisierung und Fokus auf Trapez und Latissimus.', 'In Bauchlage auf einer Schrägbank die Stange zur Brust ziehen.', 'Die Brust während der gesamten Bewegung fest gegen die Bank drücken.', 'Bei schweren Wirbelsäulen- oder Rückenproblemen vermeiden.', 'Die Brust beim Ziehen von der Bank anheben.'),
('cambered-bar-lying-row', 'it', 'Rematore sdraiato con barra curva', 'Rematore eseguito sdraiati proni su una panca con barra curva.', 'Stabilizzazione del core e focus su trapezi e dorsali.', 'Sdraiato prono su una panca inclinata, tira la barra verso il petto.', 'Mantieni il petto premuto contro la panca durante tutto il movimento.', 'Evitare in caso di gravi problemi alla colonna vertebrale o alla schiena.', 'Sollevare il petto dalla panca durante la trazione.'),
('cambered-bar-lying-row', 'zh', '俯卧曲杆划船', '在长凳上俯卧并使用曲杆进行的划船动作。', '核心稳定性以及对斜方肌和背阔肌的训练。', '俯卧在倾斜长凳上，将杠铃拉向胸部。', '动作全程保持胸部紧贴长凳。', '脊柱或背部严重受损者请避免。', '拉动时胸部离开长凳。'),
('cambered-bar-lying-row', 'ja', 'キャンバードバー・ライイング・ロウ', 'キャンバードバーを使用し、ベンチにうつ伏せになって行うローイング。', '体幹の安定化および僧帽筋と広背筋の鍛錬。', 'インクラインベンチにうつ伏せになり、バーを胸に向けて引きます。', '動作中、胸をベンチから離さないようにしてください。', '重度の脊椎や背中の問題がある場合は避けてください。', '引く際に胸をベンチから浮かせること。'),
('cambered-bar-lying-row', 'ko', '캠버드 바 라이잉 로우', '캠버드 바를 사용하여 벤치에 엎드려 하는 로우.', '코어 안정화 및 승모근과 광배근 집중.', '인클라인 벤치에 엎드려 바를 가슴 쪽으로 당김.', '동작 내내 가슴을 벤치에 붙여 유지.', '척추나 등 부위의 심각한 문제가 있을 시 피할 것.', '당길 때 가슴을 벤치에서 떼는 것.'),
('cambered-bar-lying-row', 'ar', 'تمرين التجديف بالبار المنحني من وضع الاستلقاء', 'تجديف يتم إجراؤه أثناء الاستلقاء على الوجه على مقعد باستخدام بار منحني.', 'تثبيت الجذع وتركيز على العضلة شبه المنحرفة والعضلات الظهرية.', 'استلقِ على وجهك على مقعد مائل، واسحب البار نحو صدرك.', 'حافظ على ضغط صدرك مقابل المقعد طوال الحركة.', 'تجنب في حالة وجود مشاكل خطيرة في العمود الفقري أو الظهر.', 'رفع الصدر عن المقعد أثناء السحب.'),
('cambered-bar-lying-row', 'hi', 'कैम्बर्ड बार लाइइंग रो', 'कैम्बर्ड बार का उपयोग करके बेंच पर पेट के बल लेटकर किया जाने वाला रो।', 'कोर स्थिरीकरण और ट्रैपेज़ियस और लैट्स पर ध्यान।', 'इनक्लाइन बेंच पर पेट के बल लेटें, बार को अपनी छाती की ओर खींचें।', 'पूरी गति के दौरान अपनी छाती को बेंच पर दबाए रखें।', 'रीढ़ की हड्डी या पीठ की गंभीर समस्या होने पर न करें।', 'खींचते समय छाती को बेंच से ऊपर उठाना।'),
('cambered-bar-lying-row', 'ru', 'Тяга изогнутого грифа лежа', 'Тяга изогнутого грифа, лежа на скамье лицом вниз.', 'Стабилизация кора и акцент на трапеции и широчайшие.', 'Лежа на наклонной скамье, тяните гриф к груди.', 'Держите грудь прижатой к скамье на протяжении всего движения.', 'Избегайте при серьезных проблемах с позвоночником или спиной.', 'Отрыв груди от скамьи во время тяги.'),
('cambered-bar-lying-row', 'nl', 'Cambered bar lying row', 'Roeien liggend op de buik op een bank met een gebogen stang.', 'Core-stabilisatie en focus op monnikskapspier en lats.', 'Lig op je buik op een schuine bank en trek de stang naar je borst.', 'Houd je borst gedurende de hele beweging tegen de bank gedrukt.', 'Vermijden bij ernstige rug- of wervelkolomklachten.', 'Je borst van de bank tillen tijdens het trekken.'),
('cambered-bar-lying-row', 'sv', 'Liggande rodd med cambered bar', 'Roddförflyttning liggandes på mage på en bänk med en böjd stång.', 'Kärnstabilitet och fokus på traps och ryggmuskler.', 'Ligg på mage på en bänk och dra stången mot bröstet.', 'Håll bröstet pressat mot bänken under hela rörelsen.', 'Undvik vid allvarliga problem med ryggrad eller rygg.', 'Att lyfta bröstet från bänken vid draget.'),
('cambered-bar-lying-row', 'pl', 'Wiosłowanie sztangą łamaną w leżeniu', 'Wiosłowanie wykonywane w leżeniu na brzuchu na ławce przy użyciu sztangi łamanej.', 'Stabilizacja korpusu oraz nacisk na mięśnie czworoboczne i najszersze.', 'Leżąc na brzuchu na ławce skośnej, przyciągaj sztangę do klatki piersiowej.', 'Trzymaj klatkę piersiową dociśniętą do ławki przez cały ruch.', 'Unikaj przy poważnych problemach z kręgosłupem lub plecami.', 'Odrywanie klatki piersiowej od ławki podczas przyciągania.'),
('cambered-bar-lying-row', 'id', 'Cambered bar lying row', 'Mendayung dengan posisi tengkurap di bangku menggunakan bar melengkung.', 'Stabilisasi inti dan fokus pada trapezius dan lat.', 'Berbaring tengkurap di bangku miring, tarik bar ke arah dada Anda.', 'Jaga dada Anda tetap menempel pada bangku selama gerakan.', 'Hindari jika ada masalah tulang belakang atau punggung yang parah.', 'Mengangkat dada dari bangku saat menarik.'),
('cambered-bar-lying-row', 'bn', 'ক্যাম্বারড বার লাইয়িং রো', 'বেঞ্চে উপুড় হয়ে শুয়ে ক্যাম্বারড বার ব্যবহার করে রোয়িং।', 'কোর স্ট্যাবিলাইজেশন এবং ট্র্যাপেজিয়াস ও ল্যাটের ওপর ফোকাস।', 'একটি ইনক্লাইন বেঞ্চে উপুড় হয়ে শুয়ে বারটি বুকের দিকে টানুন।', 'পুরো নড়াচড়ার সময় বুক বেঞ্চের সাথে চেপে রাখুন।', 'মেরুদণ্ড বা পিঠের গুরুতর সমস্যা থাকলে এটি করবেন না।', 'টানার সময় বুক বেঞ্চ থেকে ওপরে তোলা।'),
('cambered-bar-lying-row', 'vi', 'Chèo đòn cong nằm sấp', 'Bài tập chèo thực hiện nằm sấp trên ghế với đòn cong.', 'Ổn định cơ lõi và tập trung vào cơ cầu vai và cơ xô.', 'Nằm sấp trên ghế dốc, kéo thanh đòn về phía ngực.', 'Giữ ngực ép chặt vào ghế trong suốt chuyển động.', 'Tránh tập nếu có vấn đề nghiêm trọng về cột sống hoặc lưng.', 'Nhấc ngực khỏi ghế khi kéo.'),
('cambered-bar-lying-row', 'fa', 'زیربغل دمبل خم خوابیده با میله خمیده', 'زیربغل در حالت درازکش روی میز با میله خمیده.', 'ثبات هسته بدن و تمرکز بر کول و زیربغل.', 'به شکم روی میز شیب‌دار دراز بکشید و میله را به سمت سینه بکشید.', 'سینه را در تمام طول حرکت به میز بچسبانید.', 'در صورت مشکلات شدید ستون فقرات یا کمر انجام ندهید.', 'بلند کردن سینه از روی میز هنگام کشیدن.');