-- Definición de ejercicios
INSERT OR IGNORE INTO exercises (slug, img, video, difficulty) 
VALUES 
('chin-ups', 'chin-ups.jpg', 'chin-ups.mp4', 'advanced'),
('pull-ups', 'pull-ups.jpg', 'pull-ups.mp4', 'intermediate');

-- Relaciones de grupos musculares
INSERT INTO exercise_body_target (exercise_slug, body_target_slug) 
VALUES 
('chin-ups', 'back'),
('chin-ups', 'biceps');

-- Relaciones de alternativas
INSERT INTO exercise_alternative (exercise_slug, alternative_slug) 
VALUES 
('chin-ups', 'pull-ups');

-- Información multiidioma
INSERT OR IGNORE INTO exercises_info (slug, lang, title, description, benefits, instructions, tips, restrictions, mistakes) VALUES 
('chin-ups', 'es', 'Dominadas supinas', 'Variante de la dominada donde las palmas miran hacia el cuerpo, enfatizando el trabajo de bíceps.', 'Fortalece la espalda y los bíceps simultáneamente.', 'Cuelga de la barra con agarre supino y elévate hasta que la barbilla pase la barra.', 'Mantén el cuerpo recto y evita el balanceo.', 'Evitar si hay lesiones de hombro o codo.', 'Uso excesivo de impulso o no realizar el rango completo.'),
('chin-ups', 'en', 'Chin-ups', 'Pull-up variation where palms face the body, emphasizing biceps.', 'Strengthens the back and biceps simultaneously.', 'Hang from the bar with an underhand grip and pull yourself up until your chin clears the bar.', 'Keep your body straight and avoid swinging.', 'Avoid if there are shoulder or elbow injuries.', 'Excessive momentum or not using full range of motion.'),
('chin-ups', 'pt', 'Elevações supinas (Chin-ups)', 'Variante da elevação onde as palmas das mãos estão voltadas para o corpo, enfatizando o trabalho dos bíceps.', 'Fortalece as costas e os bíceps simultaneamente.', 'Pendure-se na barra com agarre supinado e eleve-se até que o queixo passe a barra.', 'Mantenha o corpo reto e evite balançar.', 'Evitar se houver lesões nos ombros ou cotovelos.', 'Uso excessivo de impulso ou não realizar a amplitude completa.'),
('chin-ups', 'fr', 'Tractions en supination (Chin-ups)', 'Variante de la traction où les paumes sont tournées vers le corps, mettant l''accent sur les biceps.', 'Renforce le dos et les biceps simultanément.', 'Suspendez-vous à la barre en prise supination et remontez jusqu''à ce que le menton dépasse la barre.', 'Gardez le corps droit et évitez le balancement.', 'À éviter en cas de blessures aux épaules ou aux coudes.', 'Utilisation excessive de l''élan ou amplitude incomplète.'),
('chin-ups', 'de', 'Chin-ups', 'Klimmzug-Variante, bei der die Handflächen zum Körper zeigen, was den Bizeps stärker beansprucht.', 'Stärkt Rücken und Bizeps gleichzeitig.', 'Hängen Sie sich mit untergriffigem Griff an die Stange und ziehen Sie sich hoch, bis Ihr Kinn über die Stange geht.', 'Halten Sie Ihren Körper gerade und vermeiden Sie Schwung.', 'Bei Schulter- oder Ellbogenverletzungen vermeiden.', 'Übermäßiger Schwung oder unvollständiger Bewegungsumfang.'),
('chin-ups', 'it', 'Trazioni alla sbarra (Chin-ups)', 'Variante delle trazioni in cui i palmi sono rivolti verso il corpo, enfatizzando il lavoro dei bicipiti.', 'Rinforza schiena e bicipiti simultaneamente.', 'Appenditi alla sbarra con presa supina e sollevati finché il mento non supera la sbarra.', 'Mantieni il corpo dritto ed evita di oscillare.', 'Evitare in caso di lesioni alle spalle o ai gomiti.', 'Uso eccessivo dello slancio o mancato completamento dell''escursione articolare.'),
('chin-ups', 'zh', '反握引体向上 (Chin-ups)', '引体向上变体，掌心朝向身体，强调肱二头肌锻炼。', '同时增强背部和肱二头肌。', '反握悬挂在杠上，向上拉动身体直至下巴超过横杠。', '保持身体挺直，避免晃动。', '如有肩部或肘部损伤，请避免使用。', '过度利用惯性或动作幅度不完整。'),
('chin-ups', 'ja', 'チンアップ', '掌を自分の方に向けて行う懸垂のバリエーションで、上腕二頭筋を強調します。', '背中と上腕二頭筋を同時に強化します。', '逆手でバーにぶら下がり、顎がバーを超えるまで身体を引き上げます。', '身体を真っ直ぐに保ち、反動を避けます。', '肩や肘に怪我がある場合は避けてください。', '過度な反動や可動域不足。'),
('chin-ups', 'ko', '턱걸이 (Chin-ups)', '손바닥이 몸을 향하게 잡는 턱걸이 변형으로, 이두근 운동을 강조합니다.', '등과 이두근을 동시에 강화합니다.', '언더핸드 그립으로 바에 매달린 후 턱이 바 위로 올라올 때까지 당깁니다.', '몸을 곧게 유지하고 반동을 피하세요.', '어깨나 팔꿈치 부상이 있다면 피하세요.', '과도한 반동이나 불완전한 가동 범위.'),
('chin-ups', 'ar', 'تمرين العقلة (Chin-ups)', 'نسخة من تمرين العقلة حيث تواجه الراحتان الجسم، مما يركز على عضلات البايسبس.', 'يقوي الظهر والبايسبس في آن واحد.', 'تدلَّى من البار بقبضة سفلية وارفع نفسك حتى يتجاوز ذقنك البار.', 'حافظ على استقامة جسمك وتجنب التأرجح.', 'تجنب التمرين في حالة وجود إصابات في الكتف أو الكوع.', 'استخدام الزخم المفرط أو عدم إكمال نطاق الحركة الكامل.'),
('chin-ups', 'hi', 'चिन-अप्स', 'पुल-अप का प्रकार जहां हथेलियां शरीर की ओर होती हैं, जो बाइसेप्स पर जोर देता है।', 'पीठ और बाइसेप्स को एक साथ मजबूत करता है।', 'अंडरहैंड ग्रिप के साथ बार पर लटकें और खुद को तब तक ऊपर खींचें जब तक कि आपकी ठुड्डी बार के ऊपर न हो।', 'अपने शरीर को सीधा रखें और झूलने से बचें।', 'यदि कंधे या कोहनी में चोट हो तो न करें।', 'अत्यधिक गति का उपयोग या पूरी गति का उपयोग न करना।'),
('chin-ups', 'ru', 'Подтягивания обратным хватом (Chin-ups)', 'Вариант подтягиваний, при котором ладони обращены к телу, что акцентирует нагрузку на бицепсы.', 'Одновременно укрепляет спину и бицепсы.', 'Повисните на перекладине обратным хватом и подтянитесь до уровня подбородка.', 'Держите тело ровно и избегайте раскачивания.', 'Избегайте при травмах плеч или локтей.', 'Чрезмерный инерционный рывок или неполная амплитуда движения.'),
('chin-ups', 'nl', 'Chin-ups', 'Pull-up variatie waarbij de handpalmen naar het lichaam wijzen, wat de biceps benadrukt.', 'Versterkt de rug en biceps tegelijkertijd.', 'Hang aan de stang met een onderhandse greep en trek jezelf omhoog tot je kin voorbij de stang is.', 'Houd je lichaam recht en vermijd zwaaien.', 'Vermijden bij schouder- of elleboogblessures.', 'Overmatige momentum of niet de volledige bewegingsuitslag benutten.'),
('chin-ups', 'sv', 'Chin-ups', 'Pull-up-variant där handflatorna är vända mot kroppen, vilket betonar biceps.', 'Stärker rygg och biceps samtidigt.', 'Häng från stången med ett underhandgrepp och dra upp dig tills hakan är över stången.', 'Håll kroppen rak och undvik att gunga.', 'Undvik vid axel- eller armbågsskador.', 'Överdrivet momentum eller att inte använda fullt rörelseomfång.'),
('chin-ups', 'pl', 'Podciąganie podchwytem (Chin-ups)', 'Wariant podciągania, gdzie dłonie skierowane są w stronę ciała, co akcentuje pracę bicepsów.', 'Wzmacnia plecy i bicepsy jednocześnie.', 'Zawieś się na drążku w podchwycie i podciągnij się, aż broda znajdzie się nad drążkiem.', 'Utrzymuj ciało prosto i unikaj huśtania.', 'Unikaj w przypadku kontuzji barków lub łokci.', 'Nadmierne wykorzystanie pędu lub niewykorzystanie pełnego zakresu ruchu.'),
('chin-ups', 'id', 'Chin-ups', 'Variasi pull-up di mana telapak tangan menghadap tubuh, menekankan pada otot bisep.', 'Memperkuat punggung dan bisep secara bersamaan.', 'Gantung pada palang dengan genggaman telapak tangan ke arah atas dan tarik tubuh ke atas hingga dagu melewati palang.', 'Jaga tubuh tetap lurus dan hindari mengayun.', 'Hindari jika ada cedera bahu atau siku.', 'Momentum berlebihan atau tidak melakukan rentang gerak penuh.'),
('chin-ups', 'bn', 'চিন-আপ', 'পULL-আপের একটি সংস্করণ যেখানে হাতের তালু শরীরের দিকে থাকে, যা বাইসেপসের ওপর জোর দেয়।', 'একই সাথে পিঠ এবং বাইসেপস শক্তিশালী করে।', 'আন্ডারহ্যান্ড গ্রিপ দিয়ে বারে ঝুলুন এবং নিজেকে উপরে তুলুন যতক্ষণ না আপনার চিবুক বার অতিক্রম করে।', 'আপনার শরীর সোজা রাখুন এবং দোলানো এড়িয়ে চলুন।', 'কাঁধ বা কনুইতে আঘাত থাকলে এড়িয়ে চলুন।', 'অতিরিক্ত গতি ব্যবহার করা বা সম্পূর্ণ ব্যায়াম না করা।'),
('chin-ups', 'vi', 'Chin-ups', 'Biến thể của hít xà với lòng bàn tay hướng vào cơ thể, tập trung vào cơ nhị đầu (biceps).', 'Tăng cường sức mạnh lưng và cơ nhị đầu cùng lúc.', 'Đu xà với lòng bàn tay hướng vào trong và kéo người lên đến khi cằm qua thanh xà.', 'Giữ cơ thể thẳng và tránh đung đưa.', 'Tránh tập nếu bị chấn thương vai hoặc khuỷu tay.', 'Sử dụng đà quá mức hoặc không thực hiện hết biên độ chuyển động.'),
('chin-ups', 'fa', 'بارفیکس دست برعکس (Chin-ups)', 'نوعی از بارفیکس که کف دست‌ها رو به بدن است و روی عضلات دو سر بازو (بایسپس) تمرکز دارد.', 'پشت و بازوها را به طور همزمان تقویت می‌کند.', 'با گرفتن دست به صورت برعکس (کف دست رو به شما) از میله آویزان شوید و خود را بالا بکشید تا چانه از میله عبور کند.', 'بدن خود را صاف نگه دارید و از تاب خوردن خودداری کنید.', 'در صورت آسیب‌دیدگی شانه یا آرنج از انجام آن خودداری کنید.', 'استفاده بیش از حد از شتاب یا انجام ندادن دامنه حرکتی کامل.');