-- 1. Registro
INSERT OR IGNORE INTO exercises (slug, img, video, difficulty) 
VALUES 
('dumbbell-bent-over-row', 'dumbbell-bent-over-row.jpg', 'dumbbell-bent-over-row.mp4', 'intermediate'),
('dumbbell-hammer-grip-incline-bench-two-arm-row', 'dumbbell-hammer-grip-incline-bench-two-arm-row.jpg', 'dumbbell-hammer-grip-incline-bench-two-arm-row.mp4', 'intermediate');

-- 2. Relación músculo
INSERT OR IGNORE INTO exercise_body_target (exercise_slug, body_target_slug) 
VALUES 
('dumbbell-hammer-grip-incline-bench-two-arm-row', 'back');

-- 3. Relación alternativa
INSERT OR IGNORE INTO exercise_alternative (exercise_slug, alternative_slug) 
VALUES 
('dumbbell-hammer-grip-incline-bench-two-arm-row', 'dumbbell-bent-over-row');

-- 4. Info multiidioma
INSERT OR IGNORE INTO exercises_info (slug, lang, title, description, benefits, instructions, tips, restrictions, mistakes) VALUES 
('dumbbell-hammer-grip-incline-bench-two-arm-row', 'es', 'Remo mancuernas agarre neutro banco inclinado', 'Remo bilateral con mancuernas, agarre neutro, apoyado en banco inclinado.', 'Estabiliza el torso y aísla la parte media de la espalda.', 'Apoya el pecho en banco inclinado, sujeta mancuernas agarre neutro y tracciona.', 'Mantén hombros bajos y cuello relajado.', 'Evitar con lesiones lumbares o de hombro.', 'Permitir que las mancuernas toquen el suelo.'),
('dumbbell-hammer-grip-incline-bench-two-arm-row', 'en', 'Dumbbell hammer-grip incline bench two-arm row', 'Bilateral dumbbell row, neutral grip, on incline bench.', 'Stabilizes torso and isolates mid-back.', 'Press chest against incline bench, hold dumbbells neutral grip, and row.', 'Keep shoulders down and neck relaxed.', 'Avoid with lumbar or shoulder injuries.', 'Touching the ground constantly.'),
('dumbbell-hammer-grip-incline-bench-two-arm-row', 'pt', 'Remada bilateral com halteres no banco inclinado', 'Remada com halteres, pegada neutra, no banco inclinado.', 'Estabiliza o tronco e isola o meio das costas.', 'Apoie o peito no banco, segure halteres com pegada neutra e reme.', 'Mantenha ombros baixos e pescoço relaxado.', 'Evitar com lesões lombares ou de ombro.', 'Deixar os halteres tocarem o chão constantemente.'),
('dumbbell-hammer-grip-incline-bench-two-arm-row', 'fr', 'Tirage haltères prise neutre banc incliné', 'Tirage bilatéral aux haltères, prise neutre, sur banc incliné.', 'Stabilise le buste et isole le milieu du dos.', 'Appuyez la poitrine sur le banc, saisissez les haltères en prise neutre et tirez.', 'Gardez les épaules basses et le cou détendu.', 'À éviter en cas de lésions lombaires ou d''épaule.', 'Laisser les haltères toucher le sol en permanence.'),
('dumbbell-hammer-grip-incline-bench-two-arm-row', 'de', 'Kurzhantel-Rudern mit neutralem Griff auf Schrägbank', 'Beidseitiges Rudern mit Kurzhanteln im neutralen Griff auf der Schrägbank.', 'Stabilisiert den Rumpf und isoliert den mittleren Rücken.', 'Brust auf Schrägbank legen, Hanteln im neutralen Griff halten und rudern.', 'Schultern tief und Nacken locker lassen.', 'Bei Lendenwirbel- oder Schulterverletzungen vermeiden.', 'Ständiges Aufsetzen der Hanteln am Boden.'),
('dumbbell-hammer-grip-incline-bench-two-arm-row', 'it', 'Rematore bilaterale con manubri su panca inclinata', 'Rematore con manubri, presa neutra, su panca inclinata.', 'Stabilizza il busto e isola la parte centrale della schiena.', 'Appoggia il petto sulla panca, afferra i manubri a presa neutra e tira.', 'Tieni le spalle basse e il collo rilassato.', 'Evitare in caso di lesioni lombari o alla spalla.', 'Far toccare costantemente i manubri a terra.'),
('dumbbell-hammer-grip-incline-bench-two-arm-row', 'zh', '斜板哑铃对握双臂划船', '在斜板上进行的哑铃对握双臂划船。', '稳定躯干并隔离背部中段。', '胸部支撑在斜板上，使用对握姿势进行划船。', '保持肩膀下沉，颈部放松。', '腰部或肩部受伤者请避免。', '让哑铃频繁触地。'),
('dumbbell-hammer-grip-incline-bench-two-arm-row', 'ja', 'インクラインベンチ・ダンベルロウ（ニュートラルグリップ）', 'インクラインベンチでニュートラルグリップを使用して行う両腕ダンベルロウ。', '体幹を安定させ、背中中央部を効果的に刺激します。', 'インクラインベンチに胸を当て、ニュートラルグリップでダンベルを引きます。', '肩を下げ、首をリラックスさせてください。', '腰や肩の怪我がある場合は避けてください。', '常にダンベルを床につけること。'),
('dumbbell-hammer-grip-incline-bench-two-arm-row', 'ko', '인클라인 벤치 덤벨 로우 (뉴트럴 그립)', '인클라인 벤치에서 뉴트럴 그립을 사용하는 양팔 덤벨 로우.', '몸통 안정화 및 등 중앙부 고립.', '인클라인 벤치에 가슴을 대고 뉴트럴 그립으로 덤벨을 당김.', '어깨를 낮게 유지하고 목을 이완할 것.', '요추나 어깨 부상 시 피할 것.', '덤벨이 계속 바닥에 닿게 하는 것.'),
('dumbbell-hammer-grip-incline-bench-two-arm-row', 'ar', 'تجديف بالدمبل بقبضة محايدة على مقعد مائل', 'تجديف ثنائي بالدمبل، قبضة محايدة، على مقعد مائل.', 'يوازن الجذع ويعزل منتصف الظهر.', 'أسند صدرك على المقعد، أمسك الدمبل بقبضة محايدة واسحب.', 'حافظ على استرخاء الكتفين والرقبة.', 'تجنب في حالة إصابات الظهر أو الكتف.', 'السماح للدمبل بلمس الأرض باستمرار.'),
('dumbbell-hammer-grip-incline-bench-two-arm-row', 'hi', 'इनक्लाइन बेंच डंबल रो (न्यूट्रल ग्रिप)', 'इनक्लाइन बेंच पर न्यूट्रल ग्रिप के साथ द्विपक्षीय डंबल रो।', 'धड़ को स्थिर करता है और मध्य पीठ को अलग करता है।', 'छाती को इनक्लाइन बेंच पर रखें, न्यूट्रल ग्रिप डंबल पकड़ें और रो करें।', 'कंधों को नीचे और गर्दन को रिलैक्स रखें।', 'पीठ या कंधे की चोटों के साथ न करें।', 'डंबल को लगातार जमीन पर छूने देना।'),
('dumbbell-hammer-grip-incline-bench-two-arm-row', 'ru', 'Тяга гантелей нейтральным хватом на наклонной скамье', 'Двусторонняя тяга гантелей нейтральным хватом на наклонной скамье.', 'Стабилизирует корпус и изолирует середину спины.', 'Прижмите грудь к скамье, возьмите гантели нейтральным хватом и тяните.', 'Держите плечи опущенными, а шею расслабленной.', 'Избегайте при травмах поясницы или плеча.', 'Постоянное касание пола гантелями.'),
('dumbbell-hammer-grip-incline-bench-two-arm-row', 'nl', 'Dumbbell hammer-grip incline bench two-arm row', 'Bilaterale dumbbell row, neutrale greep, op schuine bank.', 'Stabiliseert torso en isoleert middenrug.', 'Druk borst tegen schuine bank, houd dumbbells in neutrale greep en roei.', 'Houd schouders laag en nek ontspannen.', 'Vermijden bij onderrug- of schouderblessures.', 'Dumbbells constant de grond laten raken.'),
('dumbbell-hammer-grip-incline-bench-two-arm-row', 'sv', 'Hantelrodd med neutralt grepp på lutande bänk', 'Bilateralt hantelrodd med neutralt grepp på lutande bänk.', 'Stabiliserar överkroppen och isolerar mittryggen.', 'Pressa bröstet mot lutande bänk, håll hantlar med neutralt grepp och ro.', 'Håll axlarna nere och nacken avslappnad.', 'Undvik vid ländryggs- eller axelskador.', 'Låta hantlarna vidröra marken konstant.'),
('dumbbell-hammer-grip-incline-bench-two-arm-row', 'pl', 'Wiosłowanie hantlami chwytem neutralnym na ławce skośnej', 'Obustronne wiosłowanie hantlami, chwyt neutralny, na ławce skośnej.', 'Stabilizuje tułów i izoluje środek pleców.', 'Oprzyj klatkę na ławce, trzymaj hantle chwytem neutralnym i wiosłuj.', 'Trzymaj barki nisko, a szyję rozluźnioną.', 'Unikaj przy urazach lędźwi lub barku.', 'Ciągłe dotykanie podłoża hantlami.'),
('dumbbell-hammer-grip-incline-bench-two-arm-row', 'id', 'Dumbbell hammer-grip incline bench two-arm row', 'Rowing dumbbell bilateral, pegangan netral, pada bangku miring.', 'Menstabilkan tubuh dan mengisolasi punggung tengah.', 'Tekan dada pada bangku miring, pegang dumbbell dengan pegangan netral, dan tarik.', 'Jaga bahu tetap rendah dan leher rileks.', 'Hindari dengan cedera punggung atau bahu.', 'Membiarkan dumbbell menyentuh lantai secara terus-menerus.'),
('dumbbell-hammer-grip-incline-bench-two-arm-row', 'bn', 'ইনক্লাইন বেঞ্চ ডাম্বেল রো (নিউট্রাল গ্রিপ)', 'ইনক্লাইন বেঞ্চে নিউট্রাল গ্রিপ ব্যবহার করে রোয়িং।', 'শরীরের ওপরের অংশ স্থিতিশীল করে এবং মাঝের পিঠের ব্যায়াম।', 'বুক বেঞ্চে চাপিয়ে নিউট্রাল গ্রিপে ডাম্বেল ধরে রো করুন।', 'কাঁধ নিচে এবং ঘাড় শিথিল রাখুন।', 'পিঠ বা কাঁধে ইনজুরি থাকলে এটি করবেন না।', 'ডাম্বেল দিয়ে মেঝেতে বারবার আঘাত করা।'),
('dumbbell-hammer-grip-incline-bench-two-arm-row', 'vi', 'Chèo tạ đơn tay nắm trung tính trên ghế dốc', 'Chèo tạ đơn hai tay, tay nắm trung tính, trên ghế dốc.', 'Ổn định thân người và cô lập phần giữa lưng.', 'Ép ngực vào ghế dốc, nắm tạ tay nắm trung tính và kéo.', 'Giữ vai thấp và cổ thư giãn.', 'Tránh tập nếu bị chấn thương lưng hoặc vai.', 'Để tạ chạm sàn liên tục.'),
('dumbbell-hammer-grip-incline-bench-two-arm-row', 'fa', 'زیربغل دمبل جفت خم روی میز شیب‌دار با دست خنثی', 'زیربغل دمبل دوطرفه با استفاده از دستگیره خنثی (چکشی) روی میز شیب‌دار.', 'ثبات تنه و جداسازی عضلات وسط کمر.', 'سینه را روی میز شیب‌دار تکیه دهید، دمبل‌ها را با دست خنثی بگیرید و بکشید.', 'شانه‌ها را پایین و گردن را رها نگه دارید.', 'در صورت آسیب کمر یا شانه انجام ندهید.', 'اجازه دادن به برخورد مداوم دمبل‌ها با زمین.');