-- 1. Registro
INSERT OR IGNORE INTO exercises (slug, img, video, difficulty) 
VALUES 
('dumbbell-single-arm-row-right', 'dumbbell-single-arm-row-right.jpg', 'dumbbell-single-arm-row-right.mp4', 'beginner'),
('dumbbell-single-arm-row-left', 'dumbbell-single-arm-row-left.jpg', 'dumbbell-single-arm-row-left.mp4', 'beginner');

-- 2. Relación músculo (Solo ejercicio actual)
INSERT OR IGNORE INTO exercise_body_target (exercise_slug, body_target_slug) 
VALUES 
('dumbbell-single-arm-row-left', 'back');

-- 3. Relación alternativa
INSERT OR IGNORE INTO exercise_alternative (exercise_slug, alternative_slug) 
VALUES 
('dumbbell-single-arm-row-left', 'dumbbell-single-arm-row-right');

-- 4. Info multiidioma
INSERT OR IGNORE INTO exercises_info (slug, lang, title, description, benefits, instructions, tips, restrictions, mistakes) VALUES 
('dumbbell-single-arm-row-left', 'es', 'Remo con mancuerna a una mano (izquierda)', 'Remo unilateral con mancuerna usando el brazo izquierdo.', 'Aísla el dorsal y corrige desequilibrios laterales.', 'Apóyate en un banco, sujeta la mancuerna con la mano izquierda y tracciona hacia la cadera.', 'Mantén la espalda neutra y no rotes el torso.', 'Evitar con lesiones lumbares o de hombro.', 'Usar impulso o rotar excesivamente el tronco.'),
('dumbbell-single-arm-row-left', 'en', 'Dumbbell single-arm row (left)', 'Unilateral dumbbell row using the left arm.', 'Isolates the lat and corrects lateral imbalances.', 'Support yourself on a bench, hold the dumbbell with your left hand, and pull towards your hip.', 'Keep your back neutral and do not rotate the torso.', 'Avoid with lumbar or shoulder injuries.', 'Using momentum or excessive trunk rotation.'),
('dumbbell-single-arm-row-left', 'pt', 'Remada unilateral com haltere (esquerda)', 'Remada unilateral com haltere usando o braço esquerdo.', 'Isola o latíssimo e corrige desequilíbrios laterais.', 'Apoie-se num banco, segure o haltere com a mão esquerda e puxe em direção ao quadril.', 'Mantenha as costas neutras e não rode o tronco.', 'Evitar com lesões lombares ou no ombro.', 'Usar impulso ou rodar excessivamente o tronco.'),
('dumbbell-single-arm-row-left', 'fr', 'Tirage haltère à un bras (gauche)', 'Tirage unilatéral avec haltère utilisant le bras gauche.', 'Isole le grand dorsal et corrige les déséquilibres latéraux.', 'Appuyez-vous sur un banc, saisissez l''haltère de la main gauche et tirez vers la hanche.', 'Gardez le dos neutre et ne faites pas pivoter le buste.', 'À éviter en cas de lésions lombaires ou d''épaule.', 'Utiliser l''élan ou faire pivoter excessivement le buste.'),
('dumbbell-single-arm-row-left', 'de', 'Einarmiges Kurzhantel-Rudern (links)', 'Einarmiges Rudern mit der Kurzhantel unter Verwendung des linken Arms.', 'Isoliert den Latissimus und korrigiert seitliche Ungleichgewichte.', 'Auf einer Bank abstützen, Hantel mit der linken Hand halten und zur Hüfte ziehen.', 'Rücken neutral halten und den Oberkörper nicht drehen.', 'Bei Lendenwirbel- oder Schulterverletzungen vermeiden.', 'Schwung verwenden oder den Rumpf übermäßig drehen.'),
('dumbbell-single-arm-row-left', 'it', 'Rematore con manubrio a un braccio (sinistro)', 'Rematore unilaterale con manubrio usando il braccio sinistro.', 'Isola il gran dorsale e corregge gli squilibri laterali.', 'Appoggiati su una panca, afferra il manubrio con la mano sinistra e tira verso l''anca.', 'Mantieni la schiena neutra e non ruotare il busto.', 'Evitare in caso di lesioni lombari o alla spalla.', 'Usare lo slancio o ruotare eccessivamente il tronco.'),
('dumbbell-single-arm-row-left', 'zh', '哑铃单臂划船（左）', '使用左臂进行的单侧哑铃划船。', '隔离背阔肌并纠正左右侧不平衡。', '支撑在长凳上，左手握住哑铃并向髋部拉动。', '保持背部中立，不要旋转躯干。', '腰部或肩部受伤者请避免。', '利用惯性或过度旋转躯干。'),
('dumbbell-single-arm-row-left', 'ja', 'ワンハンド・ダンベルロウ（左）', '左腕を使用した片手ダンベルロウ。', '広背筋を分離し、左右のバランスを矯正します。', 'ベンチに体を支え、左手でダンベルを掴んで腰の方へ引きます。', '背筋をニュートラルに保ち、体幹を回旋させないでください。', '腰や肩に怪我がある場合は避けてください。', '反動を使うことや、体幹を過度に回旋させること。'),
('dumbbell-single-arm-row-left', 'ko', '원 암 덤벨 로우 (왼쪽)', '왼팔을 사용하는 편측 덤벨 로우.', '광배근 고립 및 좌우 불균형 교정.', '벤치에 지지하고 왼손으로 덤벨을 잡아 골반 쪽으로 당김.', '허리를 중립으로 유지하고 몸통을 회전시키지 말 것.', '요추나 어깨 부상 시 피할 것.', '반동을 이용하거나 몸통을 과도하게 회전시키는 것.'),
('dumbbell-single-arm-row-left', 'ar', 'تجديف بالدمبل بذراع واحدة (اليسرى)', 'تجديف أحادي بالدمبل باستخدام الذراع اليسرى.', 'يعزل العضلة الظهرية ويصحح التفاوتات الجانبية.', 'استند على مقعد، أمسك الدمبل بيدك اليسرى واسحب نحو الورك.', 'حافظ على استقامة الظهر ولا تدر الجذع.', 'تجنب في حالة إصابات الظهر أو الكتف.', 'استخدام الدفع أو تدوير الجذع بشكل مفرط.'),
('dumbbell-single-arm-row-left', 'hi', 'डंबल सिंगल-आर्म रो (बायां)', 'बाएं हाथ का उपयोग करके एकतरफा डंबल रो।', 'लैट्स को अलग करता है और पार्श्व असंतुलन को ठीक करता है।', 'बेंच पर सहारा लें, बाएं हाथ से डंबल पकड़ें और कूल्हे की ओर खींचें।', 'अपनी पीठ तटस्थ रखें और धड़ को न घुमाएं।', 'पीठ या कंधे की चोटों के साथ न करें।', 'गति का उपयोग करना या धड़ को अत्यधिक घुमाना।'),
('dumbbell-single-arm-row-left', 'ru', 'Тяга гантели одной рукой (левая)', 'Односторонняя тяга гантели левой рукой.', 'Изолирует широчайшие и исправляет мышечный дисбаланс.', 'Упритесь в скамью, возьмите гантель левой рукой и тяните к бедру.', 'Держите спину ровно и не разворачивайте корпус.', 'Избегайте при травмах поясницы или плеча.', 'Использование инерции или сильный разворот корпуса.'),
('dumbbell-single-arm-row-left', 'nl', 'Dumbbell single-arm row (links)', 'Unilaterale dumbbell row met de linkerarm.', 'Isoleert de lats en corrigeert zijwaartse onevenwichtigheden.', 'Steun op een bank, houd dumbbell met linkerhand en trek naar de heup.', 'Houd rug neutraal en draai de torso niet.', 'Vermijden bij onderrug- of schouderblessures.', 'Momentum gebruiken of overmatige torso-rotatie.'),
('dumbbell-single-arm-row-left', 'sv', 'Hantelrodd med en arm (vänster)', 'Unilateralt hantelrodd med vänster arm.', 'Isolerar ryggmusklerna och korrigerar sidoobalanser.', 'Stöd dig mot en bänk, håll hanteln med vänster hand och dra mot höften.', 'Håll ryggen neutral och rotera inte överkroppen.', 'Undvik vid ländryggs- eller axelskador.', 'Användning av momentum eller överdriven rotation av överkroppen.'),
('dumbbell-single-arm-row-left', 'pl', 'Wiosłowanie hantlem jednorącz (lewa ręka)', 'Jednostronne wiosłowanie hantlem przy użyciu lewej ręki.', 'Izoluje mięśnie najszersze i koryguje nierównowagi boczne.', 'Oprzyj się o ławkę, chwyć hantel lewą ręką i przyciągaj do biodra.', 'Utrzymuj proste plecy i nie rotuj tułowia.', 'Unikaj przy urazach lędźwi lub barku.', 'Używanie impetu lub nadmierna rotacja tułowia.'),
('dumbbell-single-arm-row-left', 'id', 'Dumbbell single-arm row (kiri)', 'Rowing dumbbell unilateral menggunakan lengan kiri.', 'Mengisolasi lat dan memperbaiki ketidakseimbangan lateral.', 'Bersandar pada bangku, pegang dumbbell dengan tangan kiri, dan tarik ke arah pinggul.', 'Jaga punggung tetap netral dan jangan putar torso.', 'Hindari dengan cedera punggung atau bahu.', 'Menggunakan momentum atau rotasi torso berlebihan.'),
('dumbbell-single-arm-row-left', 'bn', 'ডাম্বেল সিঙ্গেল-আর্ম রো (বাঁ হাত)', 'বাঁ হাত ব্যবহার করে ইউনিলেটারাল ডাম্বেল রো।', 'ল্যাট আইসোলেট করে এবং পার্শ্বীয় ভারসাম্যহীনতা ঠিক করে।', 'বেঞ্চে সাপোর্ট নিন, বাঁ হাতে ডাম্বেল ধরে কোমরের দিকে টানুন।', 'পিঠ নিউট্রাল রাখুন এবং ধড় ঘোরাবেন না।', 'পিঠ বা কাঁধে ইনজুরি থাকলে এটি করবেন না।', 'মোমেন্টাম ব্যবহার করা বা ধড় অতিরিক্ত ঘোরানো।'),
('dumbbell-single-arm-row-left', 'vi', 'Chèo tạ đơn một tay (trái)', 'Chèo tạ đơn một bên sử dụng tay trái.', 'Cô lập cơ xô và khắc phục mất cân bằng hai bên.', 'Tựa lên ghế, nắm tạ bằng tay trái và kéo về phía hông.', 'Giữ lưng trung tính và không xoay thân người.', 'Tránh tập nếu bị chấn thương lưng hoặc vai.', 'Sử dụng đà hoặc xoay thân người quá mức.'),
('dumbbell-single-arm-row-left', 'fa', 'زیربغل دمبل تک خم (چپ)', 'زیربغل یک‌طرفه با دمبل با استفاده از دست چپ.', 'عضله زیربغل را جداسازی کرده و عدم تعادل جانبی را اصلاح می‌کند.', 'روی میز تکیه دهید، دمبل را با دست چپ بگیرید و به سمت لگن بکشید.', 'کمر را خنثی نگه دارید و تنه را نچرخانید.', 'در صورت آسیب کمر یا شانه انجام ندهید.', 'استفاده از نیروی تکانه‌ای یا چرخش بیش از حد تنه.');