-- 1. Registro
INSERT OR IGNORE INTO exercises (slug, img, video, difficulty) 
VALUES 
('barbell-bent-over-row', 'barbell-bent-over-row.jpg', 'barbell-bent-over-row.mp4', 'intermediate'),
('dumbbell-bent-over-row', 'dumbbell-bent-over-row.jpg', 'dumbbell-bent-over-row.mp4', 'intermediate');

-- 2. Relación músculo
INSERT OR IGNORE INTO exercise_body_target (exercise_slug, body_target_slug) 
VALUES 
('dumbbell-bent-over-row', 'back');

-- 3. Relación alternativa
INSERT OR IGNORE INTO exercise_alternative (exercise_slug, alternative_slug) 
VALUES 
('dumbbell-bent-over-row', 'barbell-bent-over-row');

-- 4. Info multiidioma
INSERT OR IGNORE INTO exercises_info (slug, lang, title, description, benefits, instructions, tips, restrictions, mistakes) VALUES 
('dumbbell-bent-over-row', 'es', 'Remo con mancuernas inclinado', 'Remo realizado de pie con el torso inclinado hacia adelante utilizando mancuernas.', 'Permite un mayor rango de movimiento y corrección de desequilibrios musculares.', 'Con las rodillas ligeramente flexionadas e inclinado hacia adelante, tira de las mancuernas hacia tus caderas.', 'Mantén la espalda recta y el abdomen contraído.', 'Evitar con lesiones lumbares agudas.', 'Balancear el torso para subir el peso.'),
('dumbbell-bent-over-row', 'en', 'Dumbbell bent-over row', 'Rowing exercise performed while standing with the torso hinged forward, using dumbbells.', 'Allows for a greater range of motion and correction of muscle imbalances.', 'With knees slightly bent and torso hinged forward, pull the dumbbells towards your hips.', 'Keep your back straight and core braced.', 'Avoid with acute lumbar injuries.', 'Swinging your torso to lift the weight.'),
('dumbbell-bent-over-row', 'pt', 'Remada curvada com halteres', 'Exercício de remada realizado em pé com o tronco inclinado para a frente usando halteres.', 'Permite uma maior amplitude de movimento e correção de desequilíbrios musculares.', 'Com os joelhos ligeiramente flexionados e o tronco inclinado, puxe os halteres em direção aos quadris.', 'Mantenha as costas retas e o abdômen contraído.', 'Evitar com lesões lombares agudas.', 'Balancear o tronco para levantar o peso.'),
('dumbbell-bent-over-row', 'fr', 'Tirage buste penché avec haltères', 'Exercice de tirage debout, buste incliné en avant, avec des haltères.', 'Permet une plus grande amplitude de mouvement et la correction des déséquilibres musculaires.', 'Genoux légèrement fléchis, buste incliné, tirez les haltères vers vos hanches.', 'Gardez le dos droit et la sangle abdominale gainée.', 'À éviter en cas de blessures lombaires aiguës.', 'Donner de l''élan avec le buste pour soulever le poids.'),
('dumbbell-bent-over-row', 'de', 'Vorgebeugtes Rudern mit Kurzhanteln', 'Rudern im Stehen bei vorgebeugtem Oberkörper mit Kurzhanteln.', 'Ermöglicht einen größeren Bewegungsradius und den Ausgleich von Muskelungleichgewichten.', 'Knie leicht beugen, Oberkörper nach vorne neigen und Hanteln zur Hüfte ziehen.', 'Rücken gerade halten und Rumpf anspannen.', 'Bei akuten Lendenwirbelverletzungen vermeiden.', 'Mit dem Oberkörper Schwung holen, um das Gewicht zu heben.'),
('dumbbell-bent-over-row', 'it', 'Rematore con manubri a busto flesso', 'Rematore eseguito in piedi con il busto inclinato in avanti usando i manubri.', 'Permette un maggiore range di movimento e la correzione di squilibri muscolari.', 'Con le ginocchia leggermente flesse e il busto inclinato, tira i manubri verso le anche.', 'Mantieni la schiena dritta e l''addome contratto.', 'Evitare in caso di lesioni lombari acute.', 'Oscillare il busto per sollevare il peso.'),
('dumbbell-bent-over-row', 'zh', '俯身哑铃划船', '站立时身体前倾，使用哑铃进行的划船动作。', '允许更大的运动范围并纠正肌肉不平衡。', '膝盖微屈，上半身前倾，将哑铃拉向髋部。', '保持背部挺直，核心收紧。', '急性腰部损伤者请避免。', '用身体惯性摆动来提起重量。'),
('dumbbell-bent-over-row', 'ja', 'ダンベル・ベントオーバーロウ', '立位で上体を前傾させ、ダンベルを使って行うローイング運動。', '可動域が広く、筋肉の不均衡を矯正するのに役立ちます。', '膝を軽く曲げて上体を前傾させ、ダンベルを腰の方へ引きます。', '背筋を伸ばし、腹筋に力を入れてください。', '急性腰痛がある場合は避けてください。', '反動を使って重量を動かすこと。'),
('dumbbell-bent-over-row', 'ko', '덤벨 벤트 오버 로우', '상체를 앞으로 숙인 상태에서 덤벨을 사용하여 하는 로우 운동.', '더 넓은 가동 범위 및 근육 불균형 교정 효과.', '무릎을 살짝 굽히고 상체를 숙인 뒤 덤벨을 골반 쪽으로 당김.', '허리를 곧게 펴고 코어에 힘을 줄 것.', '급성 요추 부상 시 피할 것.', '몸의 반동을 이용하여 무게를 들어 올리는 것.'),
('dumbbell-bent-over-row', 'ar', 'تمرين التجديف بالدمبل من وضع الانحناء', 'تمرين تجديف يتم إجراؤه أثناء الوقوف مع انحناء الجذع للأمام باستخدام الدمبل.', 'يسمح بمدى حركي أكبر وتصحيح التفاوتات العضلية.', 'مع ثني الركبتين قليلاً وانحناء الجذع للأمام، اسحب الدمبل نحو وركيك.', 'حافظ على استقامة الظهر وشد عضلات البطن.', 'تجنب في حالة وجود إصابات حادة في أسفل الظهر.', 'استخدام دفع الجذع لرفع الوزن.'),
('dumbbell-bent-over-row', 'hi', 'डंबल बेंट-ओवर रो', 'डंबल का उपयोग करके आगे झुके हुए धड़ के साथ खड़े होकर किया जाने वाला रोइंग व्यायाम।', 'गति की अधिक सीमा और मांसपेशियों के असंतुलन को ठीक करने की अनुमति देता है।', 'घुटनों को थोड़ा मोड़ें और धड़ को आगे झुकाएं, डंबल को अपने कूल्हों की ओर खींचें।', 'अपनी पीठ सीधी रखें और कोर को टाइट रखें।', 'पीठ के निचले हिस्से में गंभीर चोट होने पर न करें।', 'भार उठाने के लिए धड़ को हिलाना।'),
('dumbbell-bent-over-row', 'ru', 'Тяга гантелей в наклоне', 'Упражнение, выполняемое стоя с наклоном корпуса вперед с гантелями.', 'Позволяет увеличить амплитуду движения и исправить мышечный дисбаланс.', 'Слегка согните колени, наклоните корпус и тяните гантели к бедрам.', 'Держите спину прямой, а мышцы кора напряженными.', 'Избегайте при острых травмах поясницы.', 'Раскачивание корпуса для поднятия веса.'),
('dumbbell-bent-over-row', 'nl', 'Dumbbell bent-over row', 'Roeioefening staand met voorovergebogen torso met dumbbells.', 'Zorgt voor een groter bewegingsbereik en corrigeert spieronevenwichtigheden.', 'Houd knieën licht gebogen, leun voorover en trek de dumbbells naar je heupen.', 'Houd rug recht en core aangespannen.', 'Vermijden bij acute rugblessures.', 'Met je torso zwaaien om het gewicht te tillen.'),
('dumbbell-bent-over-row', 'sv', 'Dumbbell bent-over row', 'Roddförflyttning stående med framåtlutad torso och hantlar.', 'Ger större rörelseomfång och korrigerar muskelobalanser.', 'Med lätt böjda knän och framåtlutad överkropp, dra hantlarna mot höfterna.', 'Håll ryggen rak och spänn magen.', 'Undvik vid akut ländryggsskada.', 'Att svinga med överkroppen för att lyfta vikten.'),
('dumbbell-bent-over-row', 'pl', 'Wiosłowanie hantlami w opadzie', 'Ćwiczenie wiosłowania wykonywane w staniu z tułowiem pochylonym do przodu przy użyciu hantli.', 'Pozwala na większy zakres ruchu i koryguje nierównowagi mięśniowe.', 'Z lekko ugiętymi kolanami i pochylonym tułowiem, przyciągaj hantle do bioder.', 'Utrzymuj proste plecy i napięty brzuch.', 'Unikaj przy ostrych urazach lędźwi.', 'Kołysanie tułowiem w celu podniesienia ciężaru.'),
('dumbbell-bent-over-row', 'id', 'Dumbbell bent-over row', 'Latihan mendayung yang dilakukan saat berdiri dengan torso condong ke depan menggunakan dumbbell.', 'Memungkinkan jangkauan gerak yang lebih besar dan koreksi ketidakseimbangan otot.', 'Dengan lutut sedikit ditekuk dan torso condong ke depan, tarik dumbbell ke arah pinggul Anda.', 'Jaga punggung tetap lurus dan inti tubuh kencang.', 'Hindari jika ada cedera punggung bawah akut.', 'Mengayunkan torso untuk mengangkat beban.'),
('dumbbell-bent-over-row', 'bn', 'ডাম্বেল বেন্ট-ওভার রো', 'ডাম্বেল ব্যবহার করে শরীরের ওপরের অংশ সামনের দিকে ঝুঁকিয়ে দাঁড়িয়ে করা রোয়িং ব্যায়াম।', 'গতির বৃহত্তর পরিসীমা এবং পেশীর ভারসাম্যহীনতা সংশোধন করতে সাহায্য করে।', 'হাঁটু হালকা বাঁকিয়ে শরীরের ওপরের অংশ সামনের দিকে ঝুঁকিয়ে ডাম্বেলগুলো কোমরের দিকে টানুন।', 'পিঠ সোজা রাখুন এবং কোর শক্ত রাখুন।', 'পিঠের নিচের অংশে তীব্র ব্যথা থাকলে এটি করবেন না।', 'ওজন তোলার জন্য শরীরের ওপরের অংশ দোলানো।'),
('dumbbell-bent-over-row', 'vi', 'Chèo tạ đơn gập người', 'Bài tập chèo thực hiện khi đứng với thân trên gập về phía trước sử dụng tạ đơn.', 'Cho phép phạm vi chuyển động lớn hơn và khắc phục mất cân bằng cơ bắp.', 'Với đầu gối hơi chùng và thân trên gập trước, kéo tạ về phía hông.', 'Giữ lưng thẳng và cơ lõi siết chặt.', 'Tránh tập nếu bị chấn thương lưng dưới cấp tính.', 'Đung đưa thân trên để nâng tạ.'),
('dumbbell-bent-over-row', 'fa', 'زیربغل دمبل خم', 'تمرین زیربغل در حالت ایستاده با تنه خمیده به جلو و استفاده از دمبل.', 'اجازه می‌دهد دامنه حرکتی بیشتری داشته باشید و عدم تعادل عضلانی را اصلاح کنید.', 'زانوها را کمی خم کنید، تنه را به جلو متمایل کنید و دمبل‌ها را به سمت لگن بکشید.', 'کمر را صاف نگه دارید و عضلات هسته بدن را منقبض کنید.', 'در صورت آسیب حاد کمر انجام ندهید.', 'تاب دادن تنه برای بلند کردن وزنه.');