-- 1. Registro
INSERT OR IGNORE INTO exercises (slug, img, video, difficulty) 
VALUES ('cable-hip-abduction', 'cable-hip-abduction.jpg', 'cable-hip-abduction.mp4', 'intermediate'),
('cable-hip-abduction-cross-over', 'cable-hip-abduction-cross-over.jpg', 'cable-hip-abduction-cross-over.mp4', 'intermediate');

-- 2. Relación músculo
INSERT OR IGNORE INTO exercise_body_target (exercise_slug, body_target_slug) 
VALUES ('cable-hip-abduction-cross-over', 'abductors');

-- 3. Relación alternativa
INSERT OR IGNORE INTO exercise_alternative (exercise_slug, alternative_slug) 
VALUES ('cable-hip-abduction-cross-over', 'cable-hip-abduction');

-- 4. Info multiidioma
INSERT OR IGNORE INTO exercises_info (slug, lang, title, description, benefits, instructions, tips, restrictions, mistakes) VALUES 
('cable-hip-abduction-cross-over', 'es', 'Abducción de cadera cruzada en polea', 'Variación de abducción en polea cruzando la pierna por delante para mayor estiramiento.', 'Aumenta el rango de estiramiento y activación del glúteo medio.', 'De pie junto a la polea, cruza la pierna de trabajo por delante de la otra antes de abrir lateralmente.', 'Mantén la pelvis estable y no rotes el tronco.', 'Evitar si hay dolor agudo de cadera.', 'Hacer el movimiento con demasiado impulso.'),
('cable-hip-abduction-cross-over', 'en', 'Cable hip abduction cross-over', 'Cable abduction variation crossing the leg in front for deeper stretch.', 'Increases stretch and gluteus medius activation.', 'Standing by the cable, cross the working leg in front of the other before abducting.', 'Keep pelvis stable and do not rotate torso.', 'Avoid if acute hip pain exists.', 'Using excessive momentum.'),
('cable-hip-abduction-cross-over', 'pt', 'Abdução de quadril cruzada no cabo', 'Variação de abdução no cabo cruzando a perna à frente para maior alongamento.', 'Aumenta o alongamento e a ativação do glúteo médio.', 'Em pé ao lado do cabo, cruze a perna de trabalho à frente da outra antes de abrir.', 'Mantenha a pelve estável e não rotacione o tronco.', 'Evitar se houver dor aguda no quadril.', 'Usar impulso excessivo.'),
('cable-hip-abduction-cross-over', 'fr', 'Abduction de hanche croisée à la poulie', 'Variante d''abduction à la poulie en croisant la jambe devant pour un étirement accru.', 'Augmente l''étirement et l''activation du moyen fessier.', 'Debout près de la poulie, croisez la jambe de travail devant l''autre avant d''écarter.', 'Gardez le bassin stable et ne faites pas pivoter le buste.', 'À éviter en cas de douleur aiguë à la hanche.', 'Utiliser un élan excessif.'),
('cable-hip-abduction-cross-over', 'de', 'Gekreuzte Hüftabduktion am Kabelzug', 'Abduktionsvariante mit gekreuztem Beinzug für tiefere Dehnung.', 'Erhöht die Dehnung und Aktivierung des mittleren Gesäßmuskels.', 'Neben dem Kabelzug stehen, das Arbeitsbein vor dem anderen kreuzen und dann abduzieren.', 'Becken stabil halten und Rumpf nicht drehen.', 'Bei akuten Hüftschmerzen vermeiden.', 'Schwung verwenden.'),
('cable-hip-abduction-cross-over', 'it', 'Abduzione dell''anca ai cavi incrociata', 'Variante di abduzione ai cavi che incrocia la gamba davanti per un maggiore allungamento.', 'Aumenta l''allungamento e l''attivazione del gluteo medio.', 'In piedi accanto ai cavi, incrocia la gamba di lavoro davanti all''altra prima di aprire.', 'Mantieni il bacino stabile e non ruotare il tronco.', 'Evitare in caso di dolore acuto all''anca.', 'Usare troppo slancio.'),
('cable-hip-abduction-cross-over', 'zh', '绳索交叉髋外展', '绳索外展的变式，通过将腿交叉在身前以获得更大的拉伸感。', '增加臀中肌的拉伸和激活度。', '站在绳索旁，将工作腿交叉在另一条腿前方，然后外展。', '保持骨盆稳定，不要转动躯干。', '如有急性髋部疼痛，请避免。', '动作惯性过大。'),
('cable-hip-abduction-cross-over', 'ja', 'ケーブル・ヒップアブダクション・クロスオーバー', '脚を前にクロスさせて行う、より深いストレッチを狙ったケーブル外転運動。', '中殿筋のストレッチと活性化を向上させます。', 'ケーブルの横に立ち、脚をもう一方の脚の前にクロスさせてから外転させます。', '骨盤を安定させ、体幹を回旋させないようにしてください。', '股関節に激しい痛みがある場合は避けてください。', '反動を使いすぎること。'),
('cable-hip-abduction-cross-over', 'ko', '케이블 힙 어브덕션 크로스오버', '다리를 앞쪽으로 교차하여 더 깊은 스트레칭을 유도하는 케이블 외전 변형.', '중둔근의 스트레칭 및 활성화 증대.', '케이블 옆에 서서 일하는 다리를 반대쪽 다리 앞으로 교차한 뒤 외전.', '골반을 고정하고 상체를 회전하지 않도록 주의.', '고관절 통증 시 피할 것.', '반동을 과하게 사용하는 것.'),
('cable-hip-abduction-cross-over', 'ar', 'تمرين أبعاد الورك بالكابل مع التقاطع', 'اختلاف في تمرين الأبعاد بالكابل بتقاطع الساق أمام الأخرى لزيادة التمدد.', 'يزيد من تمدد وتنشيط العضلة الألوية الوسطى.', 'قف بجانب الكابل، واقطع الساق العاملة أمام الأخرى قبل فتحها.', 'حافظ على استقرار الحوض ولا تدر الجذع.', 'تجنب في حالة وجود ألم حاد في الورك.', 'استخدام زخم مفرط.'),
('cable-hip-abduction-cross-over', 'hi', 'केबल हिप एबडक्शन क्रॉस-ओवर', 'केबल एबडक्शन का एक प्रकार, जिसमें अधिक खिंचाव के लिए पैर को सामने क्रॉस किया जाता है।', 'ग्लूटस मेडियस के खिंचाव और सक्रियण को बढ़ाता है।', 'केबल के पास खड़े होकर, काम करने वाले पैर को दूसरे के सामने क्रॉस करें और फिर एबडक्ट करें।', 'पेल्विस स्थिर रखें और धड़ को न घुमाएं।', 'यदि कूल्हे में तीव्र दर्द हो तो न करें।', 'अत्यधिक गति (momentum) का उपयोग करना।'),
('cable-hip-abduction-cross-over', 'ru', 'Отведение бедра на блоке с перекрестом', 'Вариант отведения на блоке с перекрестом ноги для глубокого растяжения.', 'Увеличивает растяжение и активацию средней ягодичной мышцы.', 'Стоя у блока, заведите рабочую ногу перед опорной, затем отведите в сторону.', 'Держите таз стабильным, не вращайте корпус.', 'Избегайте при острой боли в тазобедренном суставе.', 'Использование слишком большого импульса.'),
('cable-hip-abduction-cross-over', 'nl', 'Cable hip abduction cross-over', 'Variatie op kabelabductie waarbij het been voor het andere been wordt gekruist voor extra rek.', 'Verhoogt de rek en activering van de gluteus medius.', 'Staand bij de kabel, kruis het werkbeen voor het andere been voordat je abduceert.', 'Houd het bekken stabiel en roteer de romp niet.', 'Vermijden bij acute heuppijn.', 'Gebruik van overmatig momentum.'),
('cable-hip-abduction-cross-over', 'sv', 'Cable hip abduction cross-over', 'Kabelabduktion med benet korsat framför för djupare stretch.', 'Ökar stretch och aktivering av gluteus medius.', 'Stående vid kabeln, korsa arbetsbenet framför det andra innan du abducerar.', 'Håll bäckenet stabilt och rotera inte överkroppen.', 'Undvik vid akut höftsmärta.', 'Användning av överdriven fart.'),
('cable-hip-abduction-cross-over', 'pl', 'Krzyżowe odwodzenie bioder na wyciągu', 'Wariant odwodzenia na wyciągu z krzyżowaniem nogi przed drugą dla głębszego rozciągnięcia.', 'Zwiększa rozciągnięcie i aktywację mięśnia pośladkowego średniego.', 'Stojąc przy wyciągu, skrzyżuj nogę pracującą przed drugą przed wykonaniem odwodzenia.', 'Utrzymuj miednicę w stabilnej pozycji i nie rotuj tułowia.', 'Unikaj w przypadku ostrego bólu biodra.', 'Używanie nadmiernego pędu.'),
('cable-hip-abduction-cross-over', 'id', 'Cable hip abduction cross-over', 'Variasi abduksi kabel dengan menyilangkan kaki di depan untuk peregangan lebih dalam.', 'Meningkatkan peregangan dan aktivasi gluteus medius.', 'Berdiri di dekat kabel, silangkan kaki kerja di depan kaki lainnya sebelum abduksi.', 'Jaga panggul stabil dan jangan putar batang tubuh.', 'Hindari jika ada nyeri pinggul akut.', 'Menggunakan momentum berlebihan.'),
('cable-hip-abduction-cross-over', 'bn', 'কেবল হিপ অ্যাবডাকশন ক্রস-ওভার', 'কেবল অ্যাবডাকশনের একটি ভ্যারিয়েশন যেখানে গভীর স্ট্রেচের জন্য পা সামনে ক্রস করা হয়।', 'গ্লুটাস মিডিয়াসের স্ট্রেচ ও অ্যাক্টিভেশন বাড়ায়।', 'কেবল মেশিনের পাশে দাঁড়িয়ে, কাজ করা পা অন্য পায়ের সামনে ক্রস করে অ্যাবডাক্ট করুন।', 'পেলভিস স্থির রাখুন এবং শরীর ঘোরানো এড়িয়ে চলুন।', 'হিপে তীব্র ব্যথা থাকলে এটি করবেন না।', 'অতিরিক্ত গতির ব্যবহার।'),
('cable-hip-abduction-cross-over', 'vi', 'Đá chân ngang cáp chéo', 'Biến thể đá chân ngang với cáp bằng cách bắt chéo chân để tăng độ kéo giãn.', 'Tăng độ kéo giãn và kích hoạt cơ mông nhỡ.', 'Đứng gần cáp, bắt chéo chân làm việc qua chân kia trước khi giạng ra.', 'Giữ khung chậu ổn định và không xoay thân người.', 'Tránh tập nếu bị đau hông cấp tính.', 'Sử dụng đà quá mạnh.'),
('cable-hip-abduction-cross-over', 'fa', 'ابداکشن لگن با کابل و تقاطع', 'تغییر در ابداکشن با کابل با عبور پا از جلو برای کشش بیشتر.', 'کشش و فعال‌سازی سرینی متوسط را افزایش می‌دهد.', 'کنار کابل بایستید، پای کار را قبل از باز کردن، از جلوی پای دیگر عبور دهید.', 'لگن را ثابت نگه دارید و تنه را نچرخانید.', 'در صورت درد حاد لگن انجام ندهید.', 'استفاده از ضربه زیاد.');