-- Definición de ejercicios (Principal + Alternativas)
INSERT OR IGNORE INTO exercises (slug, img, video, difficulty) 
VALUES 
('cable-hip-abductions', 'cable-hip-abductions.jpg', 'cable-hip-abductions.mp4', 'beginner'),
('standing-hip-abduction', 'standing-hip-abduction.jpg', 'standing-hip-abduction.mp4', 'beginner');

-- Relaciones de grupos musculares
INSERT OR IGNORE INTO exercise_body_target (exercise_slug, body_target_slug) 
VALUES 
('cable-hip-abductions', 'abductors');

-- Relaciones de alternativas
INSERT OR IGNORE INTO exercise_alternative (exercise_slug, alternative_slug) 
VALUES 
('cable-hip-abductions', 'standing-hip-abduction');

-- Información multiidioma
INSERT OR IGNORE INTO exercises_info (slug, lang, title, description, benefits, instructions, tips, restrictions, mistakes) VALUES 
('cable-hip-abductions', 'es', 'Abducción de cadera en polea', 'Ejercicio de aislamiento para los abductores usando resistencia constante de cable.', 'Mejora la estabilidad de la cadera y fortalece el glúteo medio.', 'De pie lateral a la polea, sujeta el tobillo y mueve la pierna hacia afuera alejándola del cuerpo.', 'Mantén el torso erguido y evita balancear el cuerpo para generar impulso.', 'Evitar si hay dolor agudo en la articulación de la cadera.', 'Usar demasiado peso sacrificando el rango de movimiento.'),
('cable-hip-abductions', 'en', 'Cable hip abductions', 'Isolation exercise for abductors using constant cable resistance.', 'Improves hip stability and strengthens the gluteus medius.', 'Stand sideways to the cable machine, attach to ankle, and move leg outward away from body.', 'Keep torso upright and avoid swaying your body to generate momentum.', 'Avoid if acute hip joint pain exists.', 'Using too much weight and sacrificing range of motion.'),
('cable-hip-abductions', 'pt', 'Abdução de quadril no cabo', 'Exercício de isolamento para os abdutores usando resistência constante de cabo.', 'Melhora a estabilidade do quadril e fortalece o glúteo médio.', 'Fique de lado para a máquina de cabo, prenda no tornozelo e mova a perna para fora.', 'Mantenha o tronco ereto e evite balançar o corpo para gerar impulso.', 'Evitar se houver dor aguda na articulação do quadril.', 'Usar muito peso sacrificando a amplitude de movimento.'),
('cable-hip-abductions', 'fr', 'Abduction de hanche à la poulie', 'Exercice d''isolation des abducteurs utilisant une résistance constante par câble.', 'Améliore la stabilité de la hanche et renforce le moyen fessier.', 'Debout latéralement à la machine, fixez le câble à la cheville et levez la jambe vers l''extérieur.', 'Gardez le buste droit et évitez de vous balancer pour générer de l''élan.', 'À éviter en cas de douleur aiguë à l''articulation de la hanche.', 'Utiliser trop de poids au détriment de l''amplitude de mouvement.'),
('cable-hip-abductions', 'de', 'Kabelzug-Hüftabduktion', 'Isolationsübung für die Abduktoren mit konstantem Kabelwiderstand.', 'Verbessert die Hüftstabilität und stärkt den mittleren Gesäßmuskel.', 'Seitlich zur Kabelmaschine stehen, am Knöchel befestigen und das Bein nach außen führen.', 'Oberkörper aufrecht halten und kein Schwung aus dem Körper holen.', 'Bei akuten Schmerzen im Hüftgelenk vermeiden.', 'Zu viel Gewicht verwenden und den Bewegungsumfang einschränken.'),
('cable-hip-abductions', 'it', 'Abduzione dell''anca ai cavi', 'Esercizio di isolamento per gli abduttori con resistenza costante ai cavi.', 'Migliora la stabilità dell''anca e rinforza il gluteo medio.', 'Posizionati di lato alla macchina, attacca il cavo alla caviglia e muovi la gamba verso l''esterno.', 'Mantieni il busto eretto ed evita di oscillare per generare slancio.', 'Evitare in caso di dolore acuto all''articolazione dell''anca.', 'Usare troppo peso sacrificando l''ampiezza del movimento.'),
('cable-hip-abductions', 'zh', '拉力器髋外展', '使用恒定拉力电阻进行的外展肌隔离练习。', '提高髋部稳定性并增强臀中肌。', '侧对拉力器站立，连接脚踝，将腿向外远离身体移动。', '保持躯干挺直，避免利用身体摆动产生惯性。', '如有急性髋关节疼痛，请避免使用。', '使用过大重量导致动作幅度受限。'),
('cable-hip-abductions', 'ja', 'ケーブルヒップアブダクション', 'ケーブルの定抵抗を利用した外転筋の分離運動。', '股関節の安定性を高め、中殿筋を強化します。', 'マシンに対して横向きに立ち、足首にケーブルを装着して脚を外側に開きます。', '上体を真っ直ぐに保ち、反動を使わないようにしてください。', '股関節に激しい痛みがある場合は避けてください。', '可動域を犠牲にして重すぎる重量を使うこと。'),
('cable-hip-abductions', 'ko', '케이블 힙 어브덕션', '케이블 저항을 이용한 외전근 고립 운동.', '고관절 안정성 향상 및 중둔근 강화.', '기계 옆에 서서 발목에 연결한 뒤 다리를 바깥쪽으로 들어 올림.', '상체를 곧게 유지하고 반동을 사용하지 않도록 주의.', '고관절 통증이 있다면 피할 것.', '가동 범위를 희생할 정도로 너무 무거운 무게 사용.'),
('cable-hip-abductions', 'ar', 'تمرين أبعاد الورك بالكابل', 'تمرين عزل للأبعاد باستخدام مقاومة الكابل الثابتة.', 'يحسن استقرار الورك ويقوي العضلة الألوية الوسطى.', 'قف جانبياً أمام جهاز الكابل، وقم بتوصيله بكاحلك، وحرك ساقك للخارج بعيداً عن جسمك.', 'حافظ على استقامة جذعك وتجنب أرجحة جسمك لتوليد الزخم.', 'تجنب التمرين في حالة وجود آلام حادة في مفصل الورك.', 'استخدام وزن زائد يضحي بمدى الحركة.'),
('cable-hip-abductions', 'hi', 'केबल हिप एबडक्शन', 'केबल प्रतिरोध का उपयोग करके एबडक्टर्स के लिए आइसोलेशन व्यायाम।', 'कूल्हे की स्थिरता में सुधार करता है और ग्लूटस मेडियस को मजबूत करता है।', 'केबल मशीन के बगल में खड़े हों, टखने से जुड़ें और पैर को शरीर से बाहर की ओर ले जाएं।', 'धड़ को सीधा रखें और गति उत्पन्न करने के लिए शरीर को हिलाने से बचें।', 'यदि कूल्हे के जोड़ में तीव्र दर्द हो तो न करें।', 'बहुत अधिक वजन का उपयोग करना और गति की सीमा (range of motion) से समझौता करना।'),
('cable-hip-abductions', 'ru', 'Отведение бедра в кроссовере', 'Изолирующее упражнение для отводящих мышц с использованием троса.', 'Улучшает стабильность тазобедренного сустава и укрепляет среднюю ягодичную мышцу.', 'Встаньте боком к тренажеру, прикрепите трос к лодыжке и отводите ногу в сторону.', 'Держите корпус ровно и избегайте раскачиваний.', 'Избегайте при острой боли в тазобедренном суставе.', 'Использование слишком большого веса в ущерб амплитуде движения.'),
('cable-hip-abductions', 'nl', 'Kabel heupabductie', 'Isolatie-oefening voor de abductoren met constante kabelweerstand.', 'Verbetert heupstabiliteit en versterkt de gluteus medius.', 'Sta zijwaarts ten opzichte van de kabelmachine, bevestig de enkelband en beweeg het been naar buiten.', 'Houd de romp rechtop en voorkom zwaaien met het lichaam.', 'Vermijden bij acute pijn in het heupgewricht.', 'Te veel gewicht gebruiken ten koste van de bewegingsuitslag.'),
('cable-hip-abductions', 'sv', 'Kabel-höftabduktion', 'Isolationsövning för abduktorer med konstant kabelmotstånd.', 'Förbättrar höftstabilitet och stärker gluteus medius.', 'Stå sidleds mot maskinen, fäst vid ankeln och för benet utåt från kroppen.', 'Håll överkroppen upprätt och undvik att svänga med kroppen.', 'Undvik vid akut smärta i höftleden.', 'Att använda för mycket vikt och offra rörelseomfånget.'),
('cable-hip-abductions', 'pl', 'Odwodzenie nog w wyciągu', 'Ćwiczenie izolacyjne dla mięśni odwodzicieli z użyciem wyciągu.', 'Poprawia stabilność bioder i wzmacnia mięsień pośladkowy średni.', 'Stań bokiem do maszyny, przymocuj uchwyt do kostki i wykonuj odwodzenie nogi.', 'Utrzymuj wyprostowany tułów i unikaj kołysania ciałem.', 'Unikaj w przypadku ostrego bólu stawu biodrowego.', 'Używanie zbyt dużego ciężaru kosztem pełnego zakresu ruchu.'),
('cable-hip-abductions', 'id', 'Cable hip abduction', 'Latihan isolasi untuk abduktor menggunakan kabel.', 'Meningkatkan stabilitas pinggul dan memperkuat gluteus medius.', 'Berdiri menyamping ke mesin, pasang tali ke pergelangan kaki, dan gerakkan kaki ke luar.', 'Jaga batang tubuh tegak dan hindari mengayunkan tubuh.', 'Hindari jika ada nyeri sendi pinggul akut.', 'Menggunakan beban terlalu berat yang mengurangi jangkauan gerak.'),
('cable-hip-abductions', 'bn', 'কেবল হিপ অ্যাবডাকশন', 'কেবল রেজিসট্যান্স ব্যবহার করে অ্যাবডাক্টর ব্যায়াম।', 'হিপের স্থিতিশীলতা উন্নত করে এবং গ্লুটাস মিডিয়াস শক্তিশালী করে।', 'মেশিনের পাশে দাঁড়িয়ে অ্যাঙ্কেলের সাথে ক্যাবল লাগিয়ে পা বাইরের দিকে সরান।', 'শরীর সোজা রাখুন এবং শরীর দোলানো এড়িয়ে চলুন।', 'হিপ জয়েন্টে তীব্র ব্যথা থাকলে এটি এড়িয়ে চলুন।', 'খুব বেশি ওজন ব্যবহার করা যা চলাচলের পরিধি কমিয়ে দেয়।'),
('cable-hip-abductions', 'vi', 'Đá chân ngang với cáp', 'Bài tập cô lập cơ giạng hông sử dụng cáp.', 'Cải thiện sự ổn định của hông và tăng cường cơ mông nhỡ.', 'Đứng nghiêng so với máy, móc cáp vào cổ chân và đưa chân ra ngoài.', 'Giữ thân người thẳng và tránh đung đưa cơ thể.', 'Tránh tập nếu bị đau khớp hông cấp tính.', 'Dùng quá nhiều tạ làm giảm phạm vi chuyển động.'),
('cable-hip-abductions', 'fa', 'ابداکشن لگن با کابل', 'تمرین ایزولاسیون برای عضلات ابداکتور با استفاده از مقاومت کابل.', 'پایداری لگن را بهبود بخشیده و عضله سرینی متوسط را تقویت می‌کند.', 'به‌صورت پهلو نسبت به دستگاه بایستید، کابل را به مچ پا وصل کنید و پا را به بیرون بکشید.', 'تنه را صاف نگه دارید و از تاب دادن بدن خودداری کنید.', 'در صورت درد حاد مفصل لگن از انجام آن خودداری کنید.', 'استفاده از وزن بیش از حد که دامنه حرکتی را محدود می‌کند.');