-- Definición del ejercicio
INSERT OR IGNORE INTO exercises (slug, img, video, difficulty) 
VALUES 
('curtsy-lunges', 'curtsy-lunges.jpg', 'curtsy-lunges.mp4', 'beginner');

-- Relación de grupo muscular
INSERT INTO exercise_body_target (exercise_slug, body_target_slug) 
VALUES 
('curtsy-lunges', 'abductors');

-- Relaciones de alternativas
INSERT INTO exercise_alternative (exercise_slug, alternative_slug) 
VALUES 
('curtsy-lunges', 'standing-hip-abduction');

-- Información multiidioma
INSERT OR IGNORE INTO exercises_info (slug, lang, title, description, benefits, instructions, tips, restrictions, mistakes) VALUES 
('curtsy-lunges', 'es', 'Zancadas cruzadas', 'Ejercicio compuesto que trabaja los abductores y el glúteo medio mediante un patrón de movimiento lateral y rotacional.', 'Mejora la estabilidad lateral y la fuerza de los estabilizadores de la cadera.', 'Desde posición erguida, cruza una pierna por detrás de la otra y baja la cadera hacia el suelo.', 'Mantén el torso erguido y asegúrate de que la rodilla delantera no colapse hacia adentro.', 'Evitar si hay dolor agudo en las rodillas.', 'Hacer el cruce demasiado corto o perder el equilibrio por falta de control.'),
('curtsy-lunges', 'en', 'Curtsy lunges', 'Compound exercise targeting abductors and gluteus medius through lateral and rotational movement.', 'Improves lateral stability and hip stabilizer strength.', 'From a standing position, step one leg behind and across the other, then lower your hips.', 'Keep torso upright and ensure your front knee does not collapse inward.', 'Avoid if acute knee pain exists.', 'Stepping too shallow or losing balance due to lack of control.'),
('curtsy-lunges', 'pt', 'Afundo cruzado', 'Exercício composto que trabalha abdutores e glúteo médio através de movimento lateral e rotacional.', 'Melhora a estabilidade lateral e a força dos estabilizadores do quadril.', 'Da posição em pé, cruze uma perna atrás da outra e desça o quadril em direção ao solo.', 'Mantenha o tronco ereto e garanta que o joelho da frente não desabe para dentro.', 'Evitar se houver dor aguda nos joelhos.', 'Cruzar muito pouco ou perder o equilíbrio por falta de controle.'),
('curtsy-lunges', 'fr', 'Fentes croisées', 'Exercice composé travaillant les abducteurs et le moyen fessier via un mouvement latéral et rotationnel.', 'Améliore la stabilité latérale et la force des stabilisateurs de hanche.', 'Debout, croisez une jambe derrière l''autre et abaissez vos hanches vers le sol.', 'Gardez le buste droit et assurez-vous que le genou avant ne rentre pas vers l''intérieur.', 'À éviter en cas de douleur aiguë aux genoux.', 'Croiser trop peu ou perdre l''équilibre par manque de contrôle.'),
('curtsy-lunges', 'de', 'Curtsy Lunges (Kreuzausfallschritt)', 'Verbundübung für Abduktoren und mittleren Gesäßmuskel durch laterales und rotatorisches Bewegungsmuster.', 'Verbessert die laterale Stabilität und die Kraft der Hüftstabilisatoren.', 'Aus dem Stand ein Bein hinter das andere kreuzen und die Hüfte zum Boden senken.', 'Oberkörper aufrecht halten und darauf achten, dass das vordere Knie nicht nach innen einknickt.', 'Bei akuten Knieschmerzen vermeiden.', 'Zu flaches Kreuzen oder Gleichgewichtsverlust durch mangelnde Kontrolle.'),
('curtsy-lunges', 'it', 'Affondi incrociati', 'Esercizio composto che lavora su abduttori e gluteo medio tramite un movimento laterale e rotatorio.', 'Migliora la stabilità laterale e la forza degli stabilizzatori dell''anca.', 'Partendo da in piedi, incrocia una gamba dietro l''altra e abbassa il bacino verso il suolo.', 'Mantieni il busto eretto e assicurati che il ginocchio anteriore non ceda verso l''interno.', 'Evitare in caso di dolore acuto alle ginocchia.', 'Eseguire un incrocio troppo breve o perdere l''equilibrio per mancanza di controllo.'),
('curtsy-lunges', 'zh', '交叉弓步蹲', '复合练习，通过侧向和旋转运动模式锻炼外展肌和臀中肌。', '提高侧向稳定性和髋部稳定肌的力量。', '从站立姿势开始，将一条腿交叉在另一条腿后方，然后下蹲。', '保持躯干挺直，确保前膝不会向内塌陷。', '如有急性膝关节疼痛，请避免使用。', '交叉幅度太小或因缺乏控制而失去平衡。'),
('curtsy-lunges', 'ja', 'カーテシーランジ', '横方向と回旋方向の動作パターンにより外転筋と中殿筋を鍛えるコンパウンドエクササイズ。', '横方向の安定性と股関節の安定筋力を向上させます。', '直立姿勢から一方の足を後ろに交差させ、腰を床に向かって下げます。', '上体を真っ直ぐに保ち、前の膝が内側に入らないようにしてください。', '膝に激しい痛みがある場合は避けてください。', '交差が浅すぎることや、コントロール不足によるバランスの崩れ。'),
('curtsy-lunges', 'ko', '커트시 런지', '측면 및 회전 동작 패턴을 통해 외전근과 중둔근을 단련하는 복합 운동.', '측면 안정성 및 고관절 안정근력 향상.', '선 자세에서 한쪽 다리를 다른 다리 뒤로 교차하며 골반을 낮춤.', '상체를 곧게 유지하고 앞쪽 무릎이 안으로 쏠리지 않도록 주의.', '무릎 통증이 있다면 피할 것.', '교차 거리가 너무 짧거나 통제 부족으로 인한 균형 상실.'),
('curtsy-lunges', 'ar', 'طعنات التكرار (Curtsy Lunges)', 'تمرين مركب يستهدف الأبعاد والعضلة الألوية الوسطى من خلال نمط حركة جانبي ودوراني.', 'يحسن الاستقرار الجانبي وقوة عضلات استقرار الورك.', 'من وضع الوقوف، ضع ساقك خلف الأخرى وانزل بحوضك نحو الأرض.', 'حافظ على استقامة جذعك وتأكد من عدم انهيار ركبتك الأمامية للداخل.', 'تجنب التمرين في حالة وجود آلام حادة في الركبتين.', 'التقاطع القصير جداً أو فقدان التوازن بسبب نقص التحكم.'),
('curtsy-lunges', 'hi', 'कर्टसी लंज', 'पार्श्व और घूर्णी गति पैटर्न के माध्यम से एबडक्टर्स और ग्लूटस मेडियस को लक्षित करने वाला संयुक्त व्यायाम।', 'पार्श्व स्थिरता और कूल्हे के स्टेबलाइजर्स की ताकत में सुधार करता है।', 'खड़े होकर एक पैर को दूसरे के पीछे ले जाएं और कूल्हों को फर्श की ओर नीचे करें।', 'धड़ को सीधा रखें और सुनिश्चित करें कि सामने वाला घुटना अंदर की ओर न गिरे।', 'यदि घुटनों में तीव्र दर्द हो तो न करें।', 'क्रॉस बहुत छोटा करना या नियंत्रण की कमी के कारण संतुलन खोना।'),
('curtsy-lunges', 'ru', 'Выпады «реверанс»', 'Базовое упражнение, прорабатывающее отводящие мышцы и среднюю ягодичную мышцу с помощью боковых и ротационных движений.', 'Улучшает боковую стабильность и силу мышц-стабилизаторов бедра.', 'Из положения стоя заведите одну ногу за другую и опустите таз к полу.', 'Держите корпус ровно и следите, чтобы переднее колено не заваливалось внутрь.', 'Избегайте при острой боли в коленях.', 'Слишком короткий шаг или потеря равновесия из-за недостаточного контроля.'),
('curtsy-lunges', 'nl', 'Curtsy lunges', 'Samengestelde oefening die de abductoren en gluteus medius traint via zijwaartse en roterende patronen.', 'Verbetert zijwaartse stabiliteit en kracht van de heupstabilisatoren.', 'Stap vanuit stand één been achter het andere en laat de heupen naar de grond zakken.', 'Houd de romp rechtop en zorg dat de voorste knie niet naar binnen valt.', 'Vermijden bij acute kniepijn.', 'Te ondiep stappen of evenwichtsverlies door gebrek aan controle.'),
('curtsy-lunges', 'sv', 'Curtsy lunges', 'Sammansatt övning som tränar abduktorer och gluteus medius genom laterala och roterande mönster.', 'Förbättrar lateral stabilitet och styrka i höftstabilisatorerna.', 'Från stående, korsa ett ben bakom det andra och sänk höfterna mot golvet.', 'Håll överkroppen upprätt och se till att det främre knät inte faller inåt.', 'Undvik vid akut knäsmärta.', 'Att stega för kort eller tappa balansen på grund av bristande kontroll.'),
('curtsy-lunges', 'pl', 'Wykroki typu "curtsy"', 'Ćwiczenie złożone angażujące odwodziciele i mięsień pośladkowy średni za pomocą wzorców bocznych i rotacyjnych.', 'Poprawia stabilność boczną i siłę stabilizatorów bioder.', 'W staniu przesuń jedną nogę za drugą i obniż biodra w kierunku podłoża.', 'Utrzymuj wyprostowany tułów i dbaj o to, by kolano nogi wykrocznej nie uciekało do wewnątrz.', 'Unikaj w przypadku ostrego bólu kolan.', 'Zbyt płytkie wykroki lub utrata równowagi przez brak kontroli.'),
('curtsy-lunges', 'id', 'Curtsy lunges', 'Latihan gabungan yang melatih abduktor dan gluteus medius melalui pola gerakan lateral dan rotasi.', 'Meningkatkan stabilitas lateral dan kekuatan penstabil pinggul.', 'Dari posisi berdiri, silangkan satu kaki di belakang yang lain dan turunkan pinggul ke lantai.', 'Jaga batang tubuh tegak dan pastikan lutut depan tidak menekuk ke dalam.', 'Hindari jika ada nyeri lutut akut.', 'Langkah terlalu pendek atau kehilangan keseimbangan karena kurang kontrol.'),
('curtsy-lunges', 'bn', 'কার্টসি লাঞ্জ', 'পার্শ্বীয় এবং ঘূর্ণন গতির মাধ্যমে অ্যাবডাক্টর এবং গ্লুটাস মিডিয়াসকে লক্ষ্য করে করা কমপাউন্ড ব্যায়াম।', 'পার্শ্বীয় স্থিতিশীলতা এবং হিপ স্টেবিলাইজারের শক্তি বাড়ায়।', 'সোজা দাঁড়িয়ে এক পা অন্য পায়ের পেছনে নিয়ে হিপস নিচের দিকে নামান।', 'শরীর সোজা রাখুন এবং সামনের হাঁটু যাতে ভেতরে না ঢোকে তা নিশ্চিত করুন।', 'হাঁটুতে তীব্র ব্যথা থাকলে এটি এড়িয়ে চলুন।', 'ক্রস খুব ছোট করা বা নিয়ন্ত্রণের অভাবে ভারসাম্য হারানো।'),
('curtsy-lunges', 'vi', 'Fentes croisées', 'Bài tập phức hợp tác động lên cơ giạng và cơ mông nhỡ thông qua chuyển động ngang và xoay.', 'Cải thiện độ ổn định ngang và sức mạnh của các cơ ổn định hông.', 'Từ tư thế đứng, bắt chéo một chân ra sau chân kia và hạ hông xuống.', 'Giữ thân người thẳng và đảm bảo đầu gối trước không bị đổ vào trong.', 'Tránh tập nếu bị đau đầu gối cấp tính.', 'Bước chéo quá nông hoặc mất thăng bằng do thiếu kiểm soát.'),
('curtsy-lunges', 'fa', 'لانژ کرتسی (Curtsy Lunges)', 'تمرین ترکیبی که عضلات ابداکتور و سرینی متوسط را از طریق الگوی حرکتی جانبی و چرخشی هدف قرار می‌دهد.', 'پایداری جانبی و قدرت عضلات تثبیت‌کننده لگن را بهبود می‌بخشد.', 'از حالت ایستاده، یک پا را پشت پای دیگر قرار دهید و لگن را به سمت زمین پایین بیاورید.', 'تنه را صاف نگه دارید و مطمئن شوید که زانوی جلویی به سمت داخل خم نمی‌شود.', 'در صورت درد حاد زانو از انجام آن خودداری کنید.', 'گام خیلی کوتاه یا از دست دادن تعادل به دلیل عدم کنترل.');