-- Definición del ejercicio
INSERT OR IGNORE INTO exercises (slug, img, video, difficulty) 
VALUES 
('cable-hip-abductions', 'cable-hip-abductions.jpg', 'cable-hip-abductions.mp4', 'beginner'),
('hip-abduction-machine', 'hip-abduction-machine.jpg', 'hip-abduction-machine.mp4', 'beginner');

-- Relación de grupo muscular
INSERT OR IGNORE INTO exercise_body_target (exercise_slug, body_target_slug) 
VALUES 
('hip-abduction-machine', 'abductors');

-- Relaciones de alternativas
INSERT OR IGNORE INTO exercise_alternative (exercise_slug, alternative_slug) 
VALUES 
('hip-abduction-machine', 'cable-hip-abductions');

-- Información multiidioma
INSERT OR IGNORE INTO exercises_info (slug, lang, title, description, benefits, instructions, tips, restrictions, mistakes) VALUES 
('hip-abduction-machine', 'es', 'Máquina de abducción de cadera', 'Ejercicio sentado en máquina para aislar y fortalecer los abductores.', 'Fortalece eficazmente el glúteo medio y mejora la estabilidad pélvica.', 'Siéntate en la máquina, ajusta las almohadillas a la parte exterior de las rodillas y empuja hacia afuera.', 'Mantén la espalda apoyada contra el respaldo y evita arquear la zona lumbar.', 'Evitar si hay dolor agudo en la articulación de la cadera o espalda baja.', 'Realizar el movimiento demasiado rápido o levantar la pelvis del asiento.'),
('hip-abduction-machine', 'en', 'Hip abduction machine', 'Seated machine exercise to isolate and strengthen the abductors.', 'Effectively strengthens the gluteus medius and improves pelvic stability.', 'Sit in the machine, adjust pads to the outside of your knees, and push outward.', 'Keep back pressed against the seat and avoid arching the lower back.', 'Avoid if acute hip joint or lower back pain exists.', 'Performing the movement too fast or lifting the pelvis off the seat.'),
('hip-abduction-machine', 'pt', 'Máquina de abdução de quadril', 'Exercício sentado em máquina para isolar e fortalecer os abdutores.', 'Fortalece eficazmente o glúteo médio e melhora a estabilidade pélvica.', 'Sente-se na máquina, ajuste as almofadas na parte externa dos joelhos e empurre para fora.', 'Mantenha as costas apoiadas no encosto e evite curvar a lombar.', 'Evitar se houver dor aguda na articulação do quadril ou lombar.', 'Realizar o movimento rápido demais ou elevar a pelve do assento.'),
('hip-abduction-machine', 'fr', 'Machine à abduction de hanche', 'Exercice assis sur machine pour isoler et renforcer les abducteurs.', 'Renforce efficacement le moyen fessier et améliore la stabilité pelvienne.', 'Asseyez-vous sur la machine, ajustez les coussins à l''extérieur de vos genoux et poussez vers l''extérieur.', 'Gardez le dos appuyé contre le dossier et évitez de cambrer le bas du dos.', 'À éviter en cas de douleur aiguë à l''articulation de la hanche ou au bas du dos.', 'Effectuer le mouvement trop rapidement ou soulever le bassin du siège.'),
('hip-abduction-machine', 'de', 'Hüftabduktionsmaschine', 'Sitzende Maschinenübung zur Isolierung und Stärkung der Abduktoren.', 'Stärkt effektiv den mittleren Gesäßmuskel und verbessert die Beckenstabilität.', 'Auf die Maschine setzen, Polster an den Außenseiten der Knie anpassen und nach außen drücken.', 'Rücken gegen die Lehne halten und ein Hohlkreuz vermeiden.', 'Bei akuten Hüft- oder Rückenschmerzen vermeiden.', 'Die Bewegung zu schnell ausführen oder das Becken vom Sitz abheben.'),
('hip-abduction-machine', 'it', 'Macchina per abduzione dell''anca', 'Esercizio da seduti alla macchina per isolare e rinforzare gli abduttori.', 'Rinforza efficacemente il gluteo medio e migliora la stabilità pelvica.', 'Siediti sulla macchina, regola i cuscinetti all''esterno delle ginocchia e spingi verso l''esterno.', 'Mantieni la schiena appoggiata allo schienale ed evita di inarcare la zona lombare.', 'Evitare in caso di dolore acuto all''articolazione dell''anca o lombare.', 'Eseguire il movimento troppo velocemente o sollevare il bacino dal sedile.'),
('hip-abduction-machine', 'zh', '坐姿髋外展机', '坐姿器械练习，用于隔离和加强外展肌。', '有效增强臀中肌并改善骨盆稳定性。', '坐在机器上，将垫子调整到膝盖外侧并向外推。', '保持背部紧贴靠背，避免弓背。', '如有急性髋关节或腰部疼痛，请避免使用。', '动作过快或臀部离开座位。'),
('hip-abduction-machine', 'ja', 'ヒップアブダクションマシン', '外転筋を分離・強化するための座位マシンエクササイズ。', '中殿筋を効果的に強化し、骨盤の安定性を高めます。', 'マシンに座り、パッドを膝の外側に合わせて外側に押し開きます。', '背中を背もたれに当て、腰を反らせないようにしてください。', '股関節や腰に激しい痛みがある場合は避けてください。', '動作が速すぎることや、お尻がシートから浮くこと。'),
('hip-abduction-machine', 'ko', '힙 어브덕션 머신', '외전근을 고립하고 강화하기 위한 좌식 머신 운동.', '중둔근을 효과적으로 강화하고 골반 안정성 향상.', '머신에 앉아 패드를 무릎 바깥쪽에 맞추고 바깥쪽으로 밈.', '등을 등받이에 대고 허리가 꺾이지 않도록 주의.', '고관절이나 요통이 있다면 피할 것.', '동작을 너무 빠르게 하거나 엉덩이를 시트에서 떼는 것.'),
('hip-abduction-machine', 'ar', 'جهاز أبعاد الورك', 'تمرين جلوس على الجهاز لعزل وتقوية الأبعاد.', 'يقوي العضلة الألوية الوسطى بفعالية ويحسن استقرار الحوض.', 'اجلس على الجهاز، واضبط الوسائد على الجزء الخارجي من ركبتيك وادفع للخارج.', 'حافظ على ظهرك مسنداً على المسند وتجنب تقوس أسفل الظهر.', 'تجنب التمرين في حالة وجود آلام حادة في مفصل الورك أو أسفل الظهر.', 'أداء الحركة بسرعة كبيرة أو رفع الحوض عن المقعد.'),
('hip-abduction-machine', 'hi', 'हिप एबडक्शन मशीन', 'एबडक्टर्स को अलग और मजबूत करने के लिए बैठने वाली मशीन का व्यायाम।', 'ग्लूटस मेडियस को प्रभावी ढंग से मजबूत करता है और पेल्विक स्थिरता में सुधार करता है।', 'मशीन पर बैठें, पैड को घुटनों के बाहर सेट करें और बाहर की ओर धक्का दें।', 'पीठ को बैकरेस्ट के खिलाफ रखें और पीठ के निचले हिस्से को मोड़ने से बचें।', 'यदि कूल्हे के जोड़ या पीठ के निचले हिस्से में तीव्र दर्द हो तो न करें।', 'गति को बहुत तेजी से करना या सीट से पेल्विस को उठाना।'),
('hip-abduction-machine', 'ru', 'Тренажер для отведения бедра', 'Сидячее упражнение на тренажере для изоляции и укрепления отводящих мышц.', 'Эффективно укрепляет среднюю ягодичную мышцу и улучшает стабильность таза.', 'Сядьте в тренажер, отрегулируйте валики по внешней стороне коленей и толкайте наружу.', 'Держите спину прижатой к спинке и не прогибайте поясницу.', 'Избегайте при острой боли в тазобедренном суставе или пояснице.', 'Слишком быстрое выполнение или отрыв таза от сиденья.'),
('hip-abduction-machine', 'nl', 'Heupabductie machine', 'Zittende machine-oefening om de abductoren te isoleren en te versterken.', 'Versterkt effectief de gluteus medius en verbetert bekkenstabiliteit.', 'Ga in de machine zitten, stel de kussens in aan de buitenkant van de knieën en duw naar buiten.', 'Houd de rug tegen de rugleuning en voorkom een holle rug.', 'Vermijden bij acute pijn in de heup of onderrug.', 'De beweging te snel uitvoeren of het bekken van de zitting tillen.'),
('hip-abduction-machine', 'sv', 'Höftabduktionsmaskin', 'Sittande maskinövning för att isolera och stärka abduktorerna.', 'Stärker effektivt gluteus medius och förbättrar bäckenstabiliteten.', 'Sitt i maskinen, justera kuddarna mot utsidan av knäna och tryck utåt.', 'Håll ryggen mot ryggstödet och undvik att svanka.', 'Undvik vid akut smärta i höft eller rygg.', 'Att utföra rörelsen för snabbt eller lyfta bäckenet från sitsen.'),
('hip-abduction-machine', 'pl', 'Maszyna do odwodzenia nóg', 'Ćwiczenie siedzące na maszynie izolujące i wzmacniające odwodziciele.', 'Skutecznie wzmacnia mięsień pośladkowy średni i poprawia stabilność miednicy.', 'Usiądź na maszynie, ustaw podkładki po zewnętrznej stronie kolan i wypychaj na zewnątrz.', 'Trzymaj plecy oparte o oparcie i unikaj wyginania odcinka lędźwiowego.', 'Unikaj w przypadku ostrego bólu bioder lub pleców.', 'Zbyt szybkie wykonywanie ruchu lub unoszenie miednicy z siedziska.'),
('hip-abduction-machine', 'id', 'Mesin abduksi pinggul', 'Latihan duduk pada mesin untuk mengisolasi dan memperkuat abduktor.', 'Memperkuat gluteus medius secara efektif dan meningkatkan stabilitas panggul.', 'Duduk di mesin, sesuaikan bantalan ke bagian luar lutut dan dorong ke luar.', 'Jaga punggung tetap bersandar pada sandaran dan hindari melengkungkan punggung bawah.', 'Hindari jika ada nyeri sendi pinggul akut atau punggung bawah.', 'Melakukan gerakan terlalu cepat atau mengangkat panggul dari kursi.'),
('hip-abduction-machine', 'bn', 'হিপ অ্যাবডাকশন মেশিন', 'অ্যাবডাক্টর শক্তিশালী করার জন্য মেশিনে বসে করা ব্যায়াম।', 'গ্লুটাস মিডিয়াসকে কার্যকরভাবে শক্তিশালী করে এবং পেলভিক স্থিতিশীলতা বাড়ায়।', 'মেশিনে বসে প্যাডগুলো হাঁটুর বাইরের দিকে অ্যাডজাস্ট করুন এবং বাইরের দিকে ঠেলুন।', 'পিঠ ব্যাকরেস্টের সঙ্গে চেপে রাখুন এবং পিঠের নিচের অংশ বাঁকানো এড়িয়ে চলুন।', 'হিপ জয়েন্ট বা পিঠের নিচের অংশে তীব্র ব্যথা থাকলে এটি এড়িয়ে চলুন।', 'খুব দ্রুত ব্যায়াম করা বা সিট থেকে পেলভিস তুলে ফেলা।'),
('hip-abduction-machine', 'vi', 'Máy tập giạng hông', 'Bài tập ngồi trên máy để cô lập và tăng cường cơ giạng.', 'Tăng cường hiệu quả cơ mông nhỡ và cải thiện sự ổn định vùng chậu.', 'Ngồi vào máy, điều chỉnh miếng đệm áp vào ngoài đầu gối và đẩy ra ngoài.', 'Giữ lưng tựa vào ghế và tránh võng lưng dưới.', 'Tránh tập nếu bị đau khớp hông hoặc lưng dưới cấp tính.', 'Thực hiện động tác quá nhanh hoặc nâng khung chậu khỏi ghế.'),
('hip-abduction-machine', 'fa', 'دستگاه ابداکشن لگن', 'تمرین نشسته با دستگاه برای ایزوله و تقویت عضلات ابداکتور.', 'عضله سرینی متوسط را به‌طور موثر تقویت کرده و پایداری لگن را بهبود می‌بخشد.', 'روی دستگاه بنشینید، پدها را در قسمت بیرونی زانوها تنظیم کنید و به بیرون فشار دهید.', 'کمر را به پشتی تکیه دهید و از قوس دادن به کمر خودداری کنید.', 'در صورت درد حاد مفصل لگن یا کمر از انجام آن خودداری کنید.', 'انجام سریع حرکت یا بلند کردن لگن از روی صندلی.');