-- Definición del ejercicio
INSERT OR IGNORE INTO exercises (slug, img, video, difficulty) 
VALUES 
('jumping-jacks', 'jumping-jacks.jpg', 'jumping-jacks.mp4', 'beginner');

-- Relación de grupo muscular
INSERT INTO exercise_body_target (exercise_slug, body_target_slug) 
VALUES 
('jumping-jacks', 'abductors');

-- Relaciones de alternativas
INSERT INTO exercise_alternative (exercise_slug, alternative_slug) 
VALUES 
('jumping-jacks', 'standing-hip-abduction');

-- Información multiidioma
INSERT OR IGNORE INTO exercises_info (slug, lang, title, description, benefits, instructions, tips, restrictions, mistakes) VALUES 
('jumping-jacks', 'es', 'Jumping jacks', 'Ejercicio dinámico que implica la abducción repetida de las piernas y brazos para elevar la frecuencia cardíaca y activar los abductores.', 'Mejora la agilidad, la resistencia cardiovascular y la activación dinámica de la cadera.', 'Salta abriendo las piernas y brazos simultáneamente, luego salta de nuevo para cerrarlos.', 'Mantén un ritmo constante y aterriza suavemente sobre las puntas de los pies.', 'Evitar si hay problemas articulares en rodillas o tobillos.', 'Impacto excesivo al aterrizar o realizar saltos demasiado rígidos.'),
('jumping-jacks', 'en', 'Jumping jacks', 'Dynamic exercise involving repeated abduction of legs and arms to raise heart rate and activate abductors.', 'Improves agility, cardiovascular endurance, and dynamic hip activation.', 'Jump to spread legs and arms simultaneously, then jump again to close them.', 'Maintain a steady rhythm and land softly on the balls of your feet.', 'Avoid if knee or ankle joint issues exist.', 'Excessive impact upon landing or performing stiff jumps.'),
('jumping-jacks', 'pt', 'Jumping jacks (Polichinelos)', 'Exercício dinâmico que envolve abdução repetida de pernas e braços para elevar a frequência cardíaca.', 'Melhora a agilidade, resistência cardiovascular e ativação dinâmica do quadril.', 'Salte abrindo pernas e braços simultaneamente, depois salte novamente para fechá-los.', 'Mantenha um ritmo constante e pouse suavemente sobre as pontas dos pés.', 'Evitar se houver problemas articulares nos joelhos ou tornozelos.', 'Impacto excessivo ao aterrissar ou realizar saltos muito rígidos.'),
('jumping-jacks', 'fr', 'Jumping jacks', 'Exercice dynamique impliquant l''abduction répétée des jambes et des bras pour augmenter la fréquence cardiaque.', 'Améliore l''agilité, l''endurance cardiovasculaire et l''activation dynamique de la hanche.', 'Sautez en écartant simultanément les jambes et les bras, puis sautez à nouveau pour les fermer.', 'Maintenez un rythme constant et atterrissez en douceur sur la pointe des pieds.', 'À éviter en cas de problèmes articulaires aux genoux ou aux chevilles.', 'Impact excessif à la réception ou effectuer des sauts trop rigides.'),
('jumping-jacks', 'de', 'Jumping Jacks (Hampelmann)', 'Dynamische Übung mit wiederholter Abduktion von Beinen und Armen zur Steigerung der Herzfrequenz.', 'Verbessert Agilität, kardiovaskuläre Ausdauer und dynamische Hüftaktivierung.', 'Springe und öffne gleichzeitig Beine und Arme, dann springe erneut, um sie zu schließen.', 'Halte ein gleichmäßiges Tempo und lande sanft auf den Fußballen.', 'Bei Knie- oder Sprunggelenkproblemen vermeiden.', 'Übermäßiger Aufprall bei der Landung oder zu steife Sprünge.'),
('jumping-jacks', 'it', 'Jumping jacks', 'Esercizio dinamico che comporta l''abduzione ripetuta di gambe e braccia per elevare la frequenza cardiaca.', 'Migliora agilità, resistenza cardiovascolare e attivazione dinamica dell''anca.', 'Salta aprendo gambe e braccia simultaneamente, poi salta di nuovo per chiuderle.', 'Mantieni un ritmo costante e atterra dolcemente sulle punte dei piedi.', 'Evitare in caso di problemi articolari a ginocchia o caviglie.', 'Impatto eccessivo all''atterraggio o esecuzione di salti troppo rigidi.'),
('jumping-jacks', 'zh', '开合跳', '涉及反复进行腿部和手臂外展的动态练习，旨在提高心率并激活外展肌。', '提高敏捷性、心血管耐力及髋部的动态激活。', '跳跃并同时张开双腿和双臂，然后再次跳跃以闭合。', '保持稳定的节奏，并轻柔地落地。', '如有膝盖或脚踝关节问题，请避免使用。', '落地时冲击力过大或跳跃动作过于僵硬。'),
('jumping-jacks', 'ja', 'ジャンピングジャック', '心拍数を上げ、外転筋を活性化させるための、脚と腕の反復的な外転を伴うダイナミックなエクササイズ。', '敏捷性、心血管持久力、股関節のダイナミックな活性化を向上させます。', 'ジャンプして脚と腕を同時に開き、再びジャンプして閉じます。', '一定のリズムを保ち、つま先で柔らかく着地してください。', '膝や足首に関節の問題がある場合は避けてください。', '着地時の衝撃が強すぎることや、硬い動作。'),
('jumping-jacks', 'ko', '점핑 잭', '심박수를 높이고 외전근을 활성화하기 위해 다리와 팔을 반복적으로 외전하는 동적 운동.', '민첩성, 심혈관 지구력 향상 및 고관절 동적 활성화.', '점프하며 다리와 팔을 동시에 벌리고, 다시 점프하여 오므림.', '일정한 리듬을 유지하고 발끝으로 부드럽게 착지.', '무릎이나 발목 관절 문제가 있다면 피할 것.', '착지 시 충격이 과하거나 동작이 너무 경직됨.'),
('jumping-jacks', 'ar', 'تمرين قفز القرفصاء (Jumping jacks)', 'تمرين ديناميكي يتضمن إبعاد الساقين والذراعين بشكل متكرر لرفع معدل ضربات القلب وتنشيط الأبعاد.', 'يحسن الرشاقة، التحمل القلبي الوعائي، وتنشيط الورك الديناميكي.', 'اقفز مع فتح ساقيك وذراعيك في نفس الوقت، ثم اقفز مرة أخرى لإغلاقهما.', 'حافظ على إيقاع ثابت واهبط برفق على كرات قدميك.', 'تجنب التمرين في حالة وجود مشاكل في مفاصل الركبة أو الكاحل.', 'تأثير مفرط عند الهبوط أو القيام بقفزات صلبة جداً.'),
('jumping-jacks', 'hi', 'जंपिंग जैक', 'हृदय गति बढ़ाने और एबडक्टर्स को सक्रिय करने के लिए पैरों और बाहों के बार-बार एबडक्शन को शामिल करने वाला गतिशील व्यायाम।', 'चपलता, कार्डियोवैस्कुलर सहनशक्ति और कूल्हे के गतिशील सक्रियण में सुधार करता है।', 'कूदें और एक साथ पैरों और बाहों को खोलें, फिर उन्हें बंद करने के लिए फिर से कूदें।', 'एक स्थिर गति बनाए रखें और अपने पैरों के पंजों पर धीरे से उतरें।', 'यदि घुटने या टखने के जोड़ में समस्या हो तो न करें।', 'उतरते समय अत्यधिक प्रभाव या बहुत सख्त कूद।'),
('jumping-jacks', 'ru', 'Прыжки «Джампинг Джек»', 'Динамическое упражнение, включающее повторяющееся отведение ног и рук для повышения пульса.', 'Улучшает ловкость, сердечно-сосудистую выносливость и динамическую активацию бедра.', 'Прыгните, одновременно разводя ноги и руки, затем прыгните снова, чтобы свести их.', 'Поддерживайте устойчивый ритм и приземляйтесь мягко на носки.', 'Избегайте при проблемах с коленными или голеностопными суставами.', 'Чрезмерный удар при приземлении или выполнение прыжков слишком жестко.'),
('jumping-jacks', 'nl', 'Jumping jacks', 'Dynamische oefening met herhaalde abductie van benen en armen om de hartslag te verhogen.', 'Verbetert behendigheid, cardiovasculair uithoudingsvermogen en dynamische heupactivatie.', 'Spring terwijl je benen en armen tegelijkertijd spreidt, en spring dan opnieuw om ze te sluiten.', 'Houd een constant ritme aan en land zachtjes op de bal van de voet.', 'Vermijden bij knie- of enkelgewrichtsproblemen.', 'Overmatige impact bij de landing of te stijve sprongen.'),
('jumping-jacks', 'sv', 'Jumping jacks', 'Dynamisk övning som involverar upprepad abduktion av ben och armar för att höja pulsen.', 'Förbättrar smidighet, kardiovaskulär uthållighet och dynamisk höftaktivering.', 'Hoppa och sprid ben och armar samtidigt, hoppa sedan igen för att stänga dem.', 'Håll en jämn rytm och landa mjukt på tårna.', 'Undvik vid knä- eller fotledsproblem.', 'För hög belastning vid landning eller för stela hopp.'),
('jumping-jacks', 'pl', 'Pajacyki (Jumping jacks)', 'Ćwiczenie dynamiczne polegające na powtarzalnym odwodzeniu nóg i rąk w celu podniesienia tętna.', 'Poprawia zwinność, wytrzymałość sercowo-naczyniową i dynamiczną aktywację bioder.', 'Wyskocz, rozkładając jednocześnie nogi i ręce, a następnie wyskocz ponownie, aby je złączyć.', 'Utrzymuj stałe tempo i ląduj miękko na palcach.', 'Unikaj w przypadku problemów ze stawami kolanowymi lub skokowymi.', 'Zbyt duże uderzenie przy lądowaniu lub zbyt sztywne skoki.'),
('jumping-jacks', 'id', 'Jumping jacks', 'Latihan dinamis yang melibatkan abduksi kaki dan lengan berulang untuk meningkatkan detak jantung.', 'Meningkatkan kelincahan, daya tahan kardiovaskular, dan aktivasi pinggul dinamis.', 'Lompat sambil membuka kaki dan lengan secara bersamaan, lalu lompat lagi untuk menutupnya.', 'Pertahankan ritme yang stabil dan mendarat dengan lembut di bagian depan kaki.', 'Hindari jika ada masalah sendi lutut atau pergelangan kaki.', 'Dampak berlebihan saat mendarat atau lompatan yang terlalu kaku.'),
('jumping-jacks', 'bn', 'জাম্পিং জ্যাক', 'হার্ট রেট বাড়ানো এবং অ্যাবডাক্টর সক্রিয় করার জন্য পা ও হাত বারবার খোলার ডায়নামিক ব্যায়াম।', 'তত্পরতা, কার্ডিওভাসকুলার সহনশীলতা এবং হিপের গতিশীল সক্রিয়তা উন্নত করে।', 'লাফিয়ে পা ও হাত একসাথে ছড়িয়ে দিন, আবার লাফিয়ে সেগুলো বন্ধ করুন।', 'একটি স্থির ছন্দ বজায় রাখুন এবং পায়ের ওপর আলতো করে ল্যান্ড করুন।', 'হাঁটু বা গোড়ালিতে সমস্যা থাকলে এটি এড়িয়ে চলুন।', 'ল্যান্ড করার সময় অতিরিক্ত আঘাত বা খুব শক্ত লাফ।'),
('jumping-jacks', 'vi', 'Jumping jacks', 'Bài tập động bao gồm việc giạng chân và tay lặp đi lặp lại để tăng nhịp tim và kích hoạt cơ giạng.', 'Cải thiện sự nhanh nhẹn, sức bền tim mạch và kích hoạt hông linh hoạt.', 'Nhảy để tách chân và tay đồng thời, sau đó nhảy lại để khép chúng.', 'Duy trì nhịp độ ổn định và tiếp đất nhẹ nhàng bằng mũi chân.', 'Tránh tập nếu bị vấn đề về khớp đầu gối hoặc cổ chân.', 'Tác động quá mạnh khi tiếp đất hoặc thực hiện các cú nhảy quá cứng nhắc.'),
('jumping-jacks', 'fa', 'جامپینگ جک (Jumping jacks)', 'تمرین پویا شامل ابداکشن مکرر پاها و دست‌ها برای افزایش ضربان قلب و فعال‌سازی عضلات ابداکتور.', 'چابکی، استقامت قلبی عروقی و فعال‌سازی پویای لگن را بهبود می‌بخشد.', 'بپرید و همزمان پاها و دست‌ها را باز کنید، سپس دوباره بپرید و آن‌ها را ببندید.', 'ریتم ثابتی داشته باشید و نرم روی پنجه پا فرود بیایید.', 'در صورت مشکلات مفصلی زانو یا مچ پا از انجام آن خودداری کنید.', 'ضربه شدید هنگام فرود یا انجام پرش‌های خیلی سفت.');