-- 1. Registro
INSERT OR IGNORE INTO exercises (slug, img, video, difficulty) 
VALUES 
('side-lying-hip-abduction', 'side-lying-hip-abduction.jpg', 'side-lying-hip-abduction.mp4', 'beginner'),
('lateral-band-walk', 'lateral-band-walk.jpg', 'lateral-band-walk.mp4', 'beginner');

-- 2. Relación músculo
INSERT OR IGNORE INTO exercise_body_target (exercise_slug, body_target_slug) 
VALUES ('lateral-band-walk', 'abductors');

-- 3. Relación alternativa
INSERT OR IGNORE INTO exercise_alternative (exercise_slug, alternative_slug) 
VALUES ('lateral-band-walk', 'side-lying-hip-abduction');

-- 4. Info multiidioma
INSERT OR IGNORE INTO exercises_info (slug, lang, title, description, benefits, instructions, tips, restrictions, mistakes) VALUES 
('lateral-band-walk', 'es', 'Caminata lateral con banda', 'Caminar de lado contra la resistencia de una banda colocada en los tobillos o rodillas.', 'Activa el glúteo medio y mejora la estabilidad lateral de la rodilla.', 'Con banda en los tobillos y rodillas semiflexionadas, da pasos laterales manteniendo tensión.', 'Mantén la espalda recta y no permitas que las rodillas se colapsen hacia adentro.', 'Evitar si hay dolor agudo en la rodilla.', 'Arrastrar los pies o mantener las rodillas muy juntas.'),
('lateral-band-walk', 'en', 'Lateral band walk', 'Walking sideways against the resistance of a band around ankles or knees.', 'Activates gluteus medius and improves lateral knee stability.', 'With band around ankles and knees slightly bent, step sideways maintaining tension.', 'Keep back straight and do not let knees collapse inward.', 'Avoid if acute knee pain exists.', 'Dragging feet or keeping knees too close together.'),
('lateral-band-walk', 'pt', 'Caminhada lateral com faixa', 'Caminhar de lado contra a resistência de uma faixa nos tornozelos ou joelhos.', 'Ativa o glúteo médio e melhora a estabilidade lateral do joelho.', 'Com a faixa nos tornozelos e joelhos semi-flexionados, dê passos laterais mantendo a tensão.', 'Mantenha as costas retas e não permita que os joelhos colapsem para dentro.', 'Evitar se houver dor aguda no joelho.', 'Arrastar os pés ou manter os joelhos muito juntos.'),
('lateral-band-walk', 'fr', 'Marche latérale avec bande', 'Marcher de côté contre la résistance d''une bande placée aux chevilles ou aux genoux.', 'Active le moyen fessier et améliore la stabilité latérale du genou.', 'Avec une bande aux chevilles et genoux semi-fléchis, faites des pas latéraux en gardant la tension.', 'Gardez le dos droit et ne laissez pas les genoux s''effondrer vers l''intérieur.', 'À éviter en cas de douleur aiguë au genou.', 'Traîner les pieds ou garder les genoux trop serrés.'),
('lateral-band-walk', 'de', 'Seitliches Bandgehen', 'Seitwärtsgehen gegen den Widerstand eines Bandes um Knöchel oder Knie.', 'Aktiviert den mittleren Gesäßmuskel und verbessert die laterale Kniestabilität.', 'Mit Band um die Knöchel und leicht gebeugten Knien seitliche Schritte machen und Spannung halten.', 'Rücken gerade halten und Knie nicht nach innen einknicken lassen.', 'Bei akuten Knieschmerzen vermeiden.', 'Füße schleifen oder Knie zu nah beieinander lassen.'),
('lateral-band-walk', 'it', 'Camminata laterale con banda', 'Camminare di lato contro la resistenza di una banda attorno alle caviglie o alle ginocchia.', 'Attiva il gluteo medio e migliora la stabilità laterale del ginocchio.', 'Con banda alle caviglie e ginocchia semiflesse, fai passi laterali mantenendo la tensione.', 'Mantieni la schiena dritta e non permettere alle ginocchia di cedere verso l''interno.', 'Evitare in caso di dolore acuto al ginocchio.', 'Trascinare i piedi o tenere le ginocchia troppo vicine.'),
('lateral-band-walk', 'zh', '弹力带侧向行走', '在脚踝或膝盖套上弹力带，向侧方行走以对抗阻力。', '激活臀中肌并改善膝关节侧向稳定性。', '套上弹力带，膝盖微屈，保持阻力进行侧向跨步。', '保持背部挺直，不要让膝盖向内扣。', '如有急性膝盖疼痛，请避免。', '拖脚或膝盖靠得太近。'),
('lateral-band-walk', 'ja', 'レジスタンスバンド・ラテラルウォーク', '足首や膝にバンドを装着し、抵抗に抗って横歩きをする運動。', '中殿筋を活性化し、膝の側方安定性を向上させます。', 'バンドを装着し、膝を軽く曲げてテンションを保ちながら横にステップします。', '背筋を伸ばし、膝が内側に入らないようにしてください。', '膝に激しい痛みがある場合は避けてください。', '足を擦ることや、膝を近づけすぎること。'),
('lateral-band-walk', 'ko', '저항 밴드 래터럴 워크', '발목이나 무릎에 밴드를 차고 저항을 이겨내며 옆으로 걷는 운동.', '중둔근 활성화 및 무릎 측면 안정성 향상.', '밴드를 차고 무릎을 살짝 굽혀 긴장감을 유지하며 옆으로 발걸음을 옮김.', '허리를 펴고 무릎이 안으로 모이지 않도록 주의.', '무릎 통증 시 피할 것.', '발을 끌거나 무릎을 너무 붙이는 것.'),
('lateral-band-walk', 'ar', 'المشي الجانبي بشريط مقاومة', 'المشي جانبياً ضد مقاومة الشريط الموضعة حول الكاحلين أو الركبتين.', 'ينشط العضلة الألوية الوسطى ويحسن الاستقرار الجانبي للركبة.', 'مع وضع الشريط حول الكاحلين وثني الركبتين قليلاً، خذ خطوات جانبية مع الحفاظ على التوتر.', 'حافظ على استقامة ظهرك ولا تدع الركبتين تنهاران للداخل.', 'تجنب في حالة وجود ألم حاد في الركبة.', 'سحب القدمين أو إبقاء الركبتين قريبتين جداً.'),
('lateral-band-walk', 'hi', 'लैटरल बैंड वॉक', 'टखनों या घुटनों के चारों ओर लगे बैंड के प्रतिरोध के खिलाफ साइड में चलना।', 'ग्लूटस मेडियस को सक्रिय करता है और घुटने की पार्श्व स्थिरता में सुधार करता है।', 'बैंड के साथ और घुटनों को थोड़ा मोड़कर, तनाव बनाए रखते हुए साइड में कदम रखें।', 'पीठ सीधी रखें और घुटनों को अंदर की ओर झुकने न दें।', 'यदि घुटने में तीव्र दर्द हो तो न करें।', 'पैरों को घसीटना या घुटनों को बहुत पास रखना।'),
('lateral-band-walk', 'ru', 'Боковая ходьба с эспандером', 'Ходьба боком с преодолением сопротивления ленты вокруг лодыжек или коленей.', 'Активирует среднюю ягодичную мышцу и улучшает боковую стабильность колена.', 'С лентой на лодыжках и слегка согнутыми коленями делайте шаги в сторону, сохраняя натяжение.', 'Держите спину прямой, не позволяйте коленям заваливаться внутрь.', 'Избегайте при острой боли в колене.', 'Шарканье ногами или слишком близкое сведение коленей.'),
('lateral-band-walk', 'nl', 'Lateral band walk', 'Zijwaarts lopen tegen de weerstand van een band rond enkels of knieën.', 'Activeert gluteus medius en verbetert zijwaartse kniestabiliteit.', 'Met band rond enkels en licht gebogen knieën, doe zijwaartse stappen met constante spanning.', 'Houd de rug recht en laat de knieën niet naar binnen vallen.', 'Vermijden bij acute kniepijn.', 'Voeten slepen of de knieën te dicht bij elkaar houden.'),
('lateral-band-walk', 'sv', 'Lateral band walk', 'Gå i sidled mot motståndet från ett band runt anklarna eller knäna.', 'Aktiverar gluteus medius och förbättrar knäets sidostabilitet.', 'Med band runt anklarna och lätt böjda knän, ta steg i sidled med bibehållen spänning.', 'Håll ryggen rak och låt inte knäna falla inåt.', 'Undvik vid akut knäsmärta.', 'Att släpa fötterna eller hålla knäna för tätt ihop.'),
('lateral-band-walk', 'pl', 'Boczny chód z gumą', 'Chodzenie bokiem z oporem gumy założonej na kostki lub kolana.', 'Aktywuje mięsień pośladkowy średni i poprawia boczną stabilność kolana.', 'Z gumą na kostkach i lekko ugiętymi kolanami, rób kroki w bok utrzymując napięcie.', 'Trzymaj proste plecy i nie pozwalaj kolanom schodzić się do wewnątrz.', 'Unikaj w przypadku ostrego bólu kolana.', 'Wleczenie stóp lub trzymanie kolan zbyt blisko siebie.'),
('lateral-band-walk', 'id', 'Lateral band walk', 'Berjalan ke samping melawan hambatan pita di sekitar pergelangan kaki atau lutut.', 'Mengaktifkan gluteus medius dan meningkatkan stabilitas lateral lutut.', 'Dengan pita di pergelangan kaki dan lutut sedikit ditekuk, ambil langkah ke samping sambil menjaga ketegangan.', 'Jaga punggung tetap lurus dan jangan biarkan lutut menekuk ke dalam.', 'Hindari jika ada nyeri lutut akut.', 'Menyeret kaki atau menjaga lutut terlalu dekat.'),
('lateral-band-walk', 'bn', 'ল্যাটারাল ব্যান্ড ওয়াক', 'গোড়ালি বা হাঁটুর চারপাশে ব্যান্ড রেখে প্রতিরোধের বিপরীতে পাশে হাঁটা।', 'গ্লুটাস মিডিয়াস সক্রিয় করে এবং হাঁটুর পার্শ্বীয় স্থিতিশীলতা বাড়ায়।', 'ব্যান্ড পরে হাঁটু সামান্য বাঁকিয়ে টান বজায় রেখে পাশে পা ফেলুন।', 'পিঠ সোজা রাখুন এবং হাঁটু ভেতরে আসতে দেবেন না।', 'হাঁটুতে তীব্র ব্যথা থাকলে এটি করবেন না।', 'পা ঘষে চলা বা হাঁটু খুব কাছে রাখা।'),
('lateral-band-walk', 'vi', 'Đi ngang với dây kháng lực', 'Đi sang ngang chống lại lực cản của dây đặt ở cổ chân hoặc đầu gối.', 'Kích hoạt cơ mông nhỡ và cải thiện độ ổn định ngang của đầu gối.', 'Với dây quanh cổ chân và đầu gối hơi khuỵu, bước sang ngang trong khi vẫn duy trì lực căng.', 'Giữ lưng thẳng và không để đầu gối chụm vào trong.', 'Tránh tập nếu bị đau đầu gối cấp tính.', 'Lê chân hoặc để đầu gối quá sát nhau.'),
('lateral-band-walk', 'fa', 'پیاده‌روی جانبی با باند', 'راه رفتن به پهلو در برابر مقاومت باند دور مچ پا یا زانوها.', 'سرینی متوسط را فعال کرده و ثبات جانبی زانو را بهبود می‌بخشد.', 'با باند دور مچ پا و زانوهای کمی خم شده، گام‌های جانبی بردارید و کشش را حفظ کنید.', 'کمر را صاف نگه دارید و اجازه ندهید زانوها به سمت داخل جمع شوند.', 'در صورت درد حاد زانو انجام ندهید.', 'کشیدن پاها روی زمین یا چسباندن زانوها.');