-- 1. Registro en la tabla principal
INSERT OR IGNORE INTO exercises (slug, img, video, difficulty)
VALUES 
('standing-hip-abduction', 'standing-hip-abduction.jpg', 'standing-hip-abduction.mp4', 'beginner'),
('pelvic-drop', 'pelvic-drop.jpg', 'pelvic-drop.mp4', 'intermediate');

-- 2. Registro de grupo muscular
INSERT OR IGNORE INTO exercise_body_target (exercise_slug, body_target_slug) 
VALUES 
('pelvic-drop', 'abductors');

-- 3. Registro de alternativas (ejemplo de enlace)
INSERT OR IGNORE INTO exercise_alternative (exercise_slug, alternative_slug) 
VALUES 
('pelvic-drop', 'standing-hip-abduction');

-- 4. Registro completo de información multiidioma
INSERT OR IGNORE INTO exercises_info (slug, lang, title, description, benefits, instructions, tips, restrictions, mistakes) VALUES 
('pelvic-drop', 'es', 'Caída pélvica', 'Ejercicio de control pélvico para activar el glúteo medio.', 'Mejora la estabilidad de la pelvis durante la marcha.', 'De pie en un escalón, deja caer una pierna lentamente y recupérala usando la otra cadera.', 'Mantén la rodilla estirada y el movimiento controlado.', 'Evitar si hay inestabilidad severa de tobillo.', 'Doblar la rodilla o mover el tronco lateralmente.'),
('pelvic-drop', 'en', 'Pelvic drop', 'Pelvic control exercise to activate the gluteus medius.', 'Improves pelvic stability during gait.', 'Standing on a step, slowly drop one leg down and recover it using the other hip.', 'Keep knee straight and movement controlled.', 'Avoid if severe ankle instability exists.', 'Bending the knee or swaying the torso.'),
('pelvic-drop', 'pt', 'Queda pélvica', 'Exercício de controle pélvico para ativar o glúteo médio.', 'Melhora a estabilidade da pelve durante a marcha.', 'Em pé num degrau, deixe cair uma perna lentamente e recupere-a usando o outro quadril.', 'Mantenha o joelho esticado e o movimento controlado.', 'Evitar se houver instabilidade severa de tornozelo.', 'Dobrar o joelho ou mover o tronco lateralmente.'),
('pelvic-drop', 'fr', 'Chute pelvienne', 'Exercice de contrôle pelvien pour activer le moyen fessier.', 'Améliore la stabilité du bassin pendant la marche.', 'Debout sur une marche, laissez tomber une jambe lentement et récupérez-la en utilisant l''autre hanche.', 'Gardez le genou tendu et le mouvement contrôlé.', 'À éviter en cas d''instabilité sévère de la cheville.', 'Plier le genou ou balancer le buste.'),
('pelvic-drop', 'de', 'Beckenabsenken', 'Beckenkontrollübung zur Aktivierung des mittleren Gesäßmuskels.', 'Verbessert die Beckenstabilität beim Gehen.', 'Auf einer Stufe stehend, ein Bein langsam absenken und mit der anderen Hüfte wieder hochziehen.', 'Knie gestreckt halten und Bewegung kontrolliert ausführen.', 'Bei schwerer Sprunggelenksinstabilität vermeiden.', 'Knie beugen oder Rumpf seitlich bewegen.'),
('pelvic-drop', 'it', 'Drop pelvico', 'Esercizio di controllo pelvico per attivare il gluteo medio.', 'Migliora la stabilità del bacino durante la camminata.', 'In piedi su un gradino, abbassa lentamente una gamba e recuperala usando l''altra anca.', 'Mantieni il ginocchio dritto e il movimento controllato.', 'Evitare in caso di grave instabilità della caviglia.', 'Piegare il ginocchio o muovere il busto lateralmente.'),
('pelvic-drop', 'zh', '骨盆下沉', '用于激活臀中肌的骨盆控制练习。', '改善行走时的骨盆稳定性。', '站在台阶上，缓慢放下一条腿，然后用另一侧髋部将其抬起。', '保持膝盖伸直，动作受控。', '如有严重脚踝不稳，请避免。', '弯曲膝盖或躯干侧倾。'),
('pelvic-drop', 'ja', 'ペルビックドロップ', '中殿筋を活性化させるための骨盤コントロールエクササイズ。', '歩行時の骨盤の安定性を向上させます。', '台の上に立ち、片脚をゆっくりと下げ、もう一方の股関節を使って戻します。', '膝を伸ばし、動きをコントロールしてください。', '足首に重度の不安定感がある場合は避けてください。', '膝を曲げることや、体幹を揺らすこと。'),
('pelvic-drop', 'ko', '펠빅 드롭', '중둔근 활성화를 위한 골반 조절 운동.', '보행 시 골반 안정성 향상.', '단차 위에 서서 한쪽 다리를 천천히 내렸다가 반대쪽 골반을 이용해 다시 올림.', '무릎을 펴고 동작을 통제할 것.', '발목 불안정성이 심할 경우 피할 것.', '무릎을 굽히거나 상체를 흔드는 것.'),
('pelvic-drop', 'ar', 'تمرين سقوط الحوض', 'تمرين التحكم في الحوض لتنشيط العضلة الألوية الوسطى.', 'يحسن استقرار الحوض أثناء المشي.', 'قف على درجة، اترك ساقاً واحدة تسقط ببطء واستعدها باستخدام الورك الآخر.', 'حافظ على استقامة الركبة وتحكم في الحركة.', 'تجنب في حالة وجود عدم استقرار شديد في الكاحل.', 'ثني الركبة أو تحريك الجذع جانبياً.'),
('pelvic-drop', 'hi', 'पेल्विक ड्रॉप', 'ग्लूटस मेडियस को सक्रिय करने के लिए पेल्विक नियंत्रण व्यायाम।', 'चलने के दौरान पेल्विक स्थिरता में सुधार करता है।', 'सीढ़ी पर खड़े होकर, एक पैर को धीरे-धीरे नीचे गिरने दें और दूसरे कूल्हे का उपयोग करके इसे वापस उठाएं।', 'घुटने सीधे रखें और नियंत्रित गति रखें।', 'यदि टखने में गंभीर अस्थिरता हो तो न करें।', 'घुटने को मोड़ना या धड़ को बगल में हिलाना।'),
('pelvic-drop', 'ru', 'Тазовый спуск', 'Упражнение для контроля таза и активации средней ягодичной мышцы.', 'Улучшает стабильность таза при ходьбе.', 'Стоя на ступеньке, медленно опустите одну ногу и поднимите ее, используя другую мышцу бедра.', 'Держите колено прямым, движение должно быть контролируемым.', 'Избегайте при сильной нестабильности голеностопа.', 'Сгибание колена или наклоны корпуса в стороны.'),
('pelvic-drop', 'nl', 'Pelvic drop', 'Bekkencontrole-oefening om de gluteus medius te activeren.', 'Verbetert bekkenstabiliteit tijdens het lopen.', 'Staand op een opstapje, laat één been langzaam zakken en breng het omhoog met de andere heup.', 'Houd de knie recht en de beweging gecontroleerd.', 'Vermijden bij ernstige enkelinstabiliteit.', 'Knie buigen of romp zijwaarts bewegen.'),
('pelvic-drop', 'sv', 'Pelvic drop', 'Bäckenkontrollövning för att aktivera gluteus medius.', 'Förbättrar bäckenstabiliteten under gång.', 'Stå på ett trappsteg, sänk långsamt ner ena benet och lyft tillbaka det med hjälp av den andra höften.', 'Håll knäet rakt och utför rörelsen kontrollerat.', 'Undvik vid allvarlig fotledsinstabilitet.', 'Att böja knäet eller röra överkroppen i sidled.'),
('pelvic-drop', 'pl', 'Pelvic drop', 'Ćwiczenie kontroli miednicy aktywujące mięsień pośladkowy średni.', 'Poprawia stabilność miednicy podczas chodu.', 'Stojąc na stopniu, powoli opuszczaj jedną nogę i podnoś ją za pomocą drugiego biodra.', 'Utrzymuj proste kolano i kontrolowany ruch.', 'Unikaj w przypadku poważnej niestabilności stawu skokowego.', 'Uginanie kolana lub poruszanie tułowiem w bok.'),
('pelvic-drop', 'id', 'Pelvic drop', 'Latihan kontrol panggul untuk mengaktifkan gluteus medius.', 'Meningkatkan stabilitas panggul saat berjalan.', 'Berdiri di anak tangga, biarkan satu kaki turun perlahan dan angkat kembali menggunakan pinggul lainnya.', 'Jaga lutut tetap lurus dan gerakan terkontrol.', 'Hindari jika ada ketidakstabilan pergelangan kaki yang parah.', 'Menekuk lutut atau menggerakkan batang tubuh ke samping.'),
('pelvic-drop', 'bn', 'পেলভিক ড্রপ', 'গ্লুটাস মিডিয়াস সক্রিয় করার জন্য পেলভিক কন্ট্রোল ব্যায়াম।', 'হাঁটার সময় পেলভিক স্থায়িত্ব বাড়ায়।', 'একটি ধাপে দাঁড়িয়ে, একটি পা ধীরে ধীরে নিচে নামান এবং অন্য হিপ ব্যবহার করে তা ওপরে তুলুন।', 'হাঁটু সোজা এবং নড়াচড়া নিয়ন্ত্রিত রাখুন।', 'অ্যাঙ্কেলের গুরুতর অস্থিরতা থাকলে এটি করবেন না।', 'হাঁটু বাঁকানো বা শরীর ডানে-বামে ঝোলানো।'),
('pelvic-drop', 'vi', 'Đá chân thả khung chậu', 'Bài tập kiểm soát khung chậu để kích hoạt cơ mông nhỡ.', 'Cải thiện độ ổn định vùng chậu khi đi bộ.', 'Đứng trên một bậc thang, thả lỏng một chân từ từ và nâng lên bằng hông bên kia.', 'Giữ thẳng đầu gối và thực hiện động tác có kiểm soát.', 'Tránh tập nếu bị mất ổn định cổ chân nghiêm trọng.', 'Khuỵu gối hoặc lắc lư thân người.'),
('pelvic-drop', 'fa', 'تمرين افتادن لگن (پلويك دراپ)', 'تمرين کنترل لگن برای فعال‌سازی سرینی متوسط.', 'ثبات لگن را هنگام راه رفتن بهبود می‌بخشد.', 'روی یک پله بایستید، یک پا را به آرامی پایین بیاورید و با استفاده از لگن دیگر بالا بیاورید.', 'زانو را صاف نگه دارید و حرکت را کنترل کنید.', 'در صورت بی‌ثباتی شدید مچ پا انجام ندهید.', 'خم کردن زانو یا تکان دادن تنه به طرفین.');