-- Definición del ejercicio
INSERT OR IGNORE INTO exercises (slug, img, video, difficulty) 
VALUES 
('standing-hip-abduction', 'standing-hip-abduction.jpg', 'standing-hip-abduction.mp4', 'beginner'),
('resistance-band-standing-balance-hip-abduction', 'resistance-band-standing-balance-hip-abduction.jpg', 'resistance-band-standing-balance-hip-abduction.mp4', 'intermediate');

-- Relación de grupo muscular
INSERT INTO exercise_body_target (exercise_slug, body_target_slug) 
VALUES 
('resistance-band-standing-balance-hip-abduction', 'abductors');

-- Relación de alternativas
INSERT INTO exercise_alternative (exercise_slug, alternative_slug) 
VALUES 
('resistance-band-standing-balance-hip-abduction', 'standing-hip-abduction');

-- Información multiidioma
INSERT OR IGNORE INTO exercises_info (slug, lang, title, description, benefits, instructions, tips, restrictions, mistakes) VALUES 
('resistance-band-standing-balance-hip-abduction', 'es', 'Abducción de cadera en equilibrio con banda', 'Abducción de pie con banda, manteniendo el equilibrio sobre una pierna.', 'Mejora la estabilidad del core, el equilibrio y la fuerza del glúteo medio.', 'De pie con una banda en los tobillos, levanta una pierna lateralmente mientras mantienes el equilibrio.', 'Mantén el core activado y la mirada al frente para ayudar al equilibrio.', 'Evitar si hay inestabilidad severa en el tobillo.', 'Balancear el torso para ayudar al movimiento de la pierna.'),
('resistance-band-standing-balance-hip-abduction', 'en', 'Standing balance hip abduction with band', 'Standing abduction with a band, maintaining balance on one leg.', 'Improves core stability, balance, and gluteus medius strength.', 'Standing with a band around ankles, lift one leg laterally while balancing.', 'Keep core engaged and eyes forward to help with balance.', 'Avoid if severe ankle instability exists.', 'Swinging the torso to assist the leg movement.'),
('resistance-band-standing-balance-hip-abduction', 'pt', 'Abdução de quadril em equilíbrio com faixa', 'Abdução em pé com faixa, mantendo o equilíbrio em uma perna.', 'Melhora a estabilidade do core, o equilíbrio e a força do glúteo médio.', 'Em pé com uma faixa nos tornozelos, levante uma perna lateralmente enquanto se equilibra.', 'Mantenha o core ativado e olhe para frente para ajudar no equilíbrio.', 'Evitar se houver instabilidade severa no tornozelo.', 'Balançar o tronco para ajudar no movimento da perna.'),
('resistance-band-standing-balance-hip-abduction', 'fr', 'Abduction de hanche en équilibre avec bande', 'Abduction debout avec bande, en gardant l''équilibre sur une jambe.', 'Améliore la stabilité du core, l''équilibre et la force du moyen fessier.', 'Debout avec une bande autour des chevilles, levez une jambe latéralement en gardant l''équilibre.', 'Gardez le core engagé et regardez devant pour aider à l''équilibre.', 'À éviter en cas d''instabilité sévère de la cheville.', 'Balancer le buste pour aider au mouvement de la jambe.'),
('resistance-band-standing-balance-hip-abduction', 'de', 'Stehende Hüftabduktion mit Band im Gleichgewicht', 'Stehende Abduktion mit Band, während das Gleichgewicht auf einem Bein gehalten wird.', 'Verbessert Rumpfstabilität, Gleichgewicht und Kraft des mittleren Gesäßmuskels.', 'Im Stehen mit Band um die Knöchel ein Bein seitlich anheben und das Gleichgewicht halten.', 'Rumpf angespannt lassen und den Blick geradeaus richten.', 'Bei schwerer Instabilität im Sprunggelenk vermeiden.', 'Den Oberkörper schwingen, um die Beinbewegung zu unterstützen.'),
('resistance-band-standing-balance-hip-abduction', 'it', 'Abduzione dell''anca in equilibrio con banda', 'Abduzione in piedi con banda, mantenendo l''equilibrio su una gamba.', 'Migliora la stabilità del core, l''equilibrio e la forza del gluteo medio.', 'In piedi con una banda alle caviglie, solleva una gamba lateralmente mantenendo l''equilibrio.', 'Mantieni il core attivo e lo sguardo in avanti per l''equilibrio.', 'Evitare in caso di grave instabilità della caviglia.', 'Oscillare il busto per aiutare il movimento della gamba.'),
('resistance-band-standing-balance-hip-abduction', 'zh', '弹力带站姿平衡外展', '佩戴弹力带进行站姿外展，同时保持单腿平衡。', '提高核心稳定性、平衡感及臀中肌力量。', '站立，脚踝套上弹力带，在保持平衡的同时将一条腿向侧方抬起。', '保持核心收紧，目视前方以帮助平衡。', '如有严重的踝关节不稳，请避免使用。', '晃动躯干来辅助腿部运动。'),
('resistance-band-standing-balance-hip-abduction', 'ja', 'レジスタンスバンド・スタンディングバランス・ヒップアブダクション', 'バンドを装着し、片足でバランスを取りながら行うスタンディング外転運動。', 'コアの安定性、バランス感覚、中殿筋の筋力を向上させます。', '足首にバンドを巻いて立ち、バランスを取りながら片脚を横に上げます。', 'コアに力を入れ、視線を前に向けてバランスを保ちます。', '足首の不安定感がひどい場合は避けてください。', '脚の動きを助けるために体幹を揺らすこと。'),
('resistance-band-standing-balance-hip-abduction', 'ko', '저항 밴드 스탠딩 밸런스 힙 어브덕션', '밴드를 차고 한 발로 균형을 잡으며 수행하는 스탠딩 외전 운동.', '코어 안정성, 균형 감각, 중둔근 근력 향상.', '발목에 밴드를 두르고 서서, 균형을 잡으며 한쪽 다리를 옆으로 들어 올림.', '코어를 활성화하고 정면을 응시하여 균형 유지.', '발목 불안정성이 심하다면 피할 것.', '다리 동작을 돕기 위해 상체를 흔드는 것.'),
('resistance-band-standing-balance-hip-abduction', 'ar', 'تمرين أبعاد الورك في توازن مع شريط مقاومة', 'تمرين أبعاد في وضع الوقوف مع شريط، مع الحفاظ على التوازن على ساق واحدة.', 'يحسن استقرار الجذع، التوازن، وقوة العضلة الألوية الوسطى.', 'قف مع وضع شريط حول الكاحلين، وارفع ساقاً واحدة جانبياً أثناء الحفاظ على التوازن.', 'حافظ على شد عضلات الجذع وانظر للأمام للمساعدة في التوازن.', 'تجنب في حالة وجود عدم استقرار حاد في الكاحل.', 'أرجحة الجذع للمساعدة في حركة الساق.'),
('resistance-band-standing-balance-hip-abduction', 'hi', 'रेजिस्टेंस बैंड स्टैंडिंग बैलेंस हिप एबडक्शन', 'बैंड के साथ खड़े होकर एबडक्शन, एक पैर पर संतुलन बनाए रखना।', 'कोर स्थिरता, संतुलन और ग्लूटस मेडियस की ताकत में सुधार करता है।', 'टखनों के चारों ओर बैंड के साथ खड़े होकर, संतुलन बनाते हुए एक पैर को बगल में उठाएं।', 'कोर को सक्रिय रखें और संतुलन बनाए रखने के लिए सामने देखें।', 'यदि टखने में गंभीर अस्थिरता हो तो न करें।', 'पैर की गति में सहायता के लिए धड़ को हिलाना।'),
('resistance-band-standing-balance-hip-abduction', 'ru', 'Отведение бедра стоя в балансе с эспандером', 'Отведение стоя с лентой, удерживая баланс на одной ноге.', 'Улучшает стабильность кора, баланс и силу средней ягодичной мышцы.', 'Стоя с лентой на лодыжках, поднимите одну ногу в сторону, сохраняя равновесие.', 'Держите кор напряженным, а взгляд направленным вперед.', 'Избегайте при сильной нестабильности голеностопа.', 'Раскачивание корпуса для облегчения движения ноги.'),
('resistance-band-standing-balance-hip-abduction', 'nl', 'Stande balansoefening heupabductie met band', 'Staande abductie met band, waarbij balans wordt gehouden op één been.', 'Verbetert core-stabiliteit, balans en kracht van de gluteus medius.', 'Staand met band rond de enkels, til één been zijwaarts op terwijl je balanceert.', 'Houd de core aangespannen en kijk vooruit voor balans.', 'Vermijden bij ernstige enkelinstabiliteit.', 'Het bovenlichaam zwaaien om de beenbeweging te ondersteunen.'),
('resistance-band-standing-balance-hip-abduction', 'sv', 'Stående balanserande höftabduktion med band', 'Stående abduktion med band, där balansen hålls på ett ben.', 'Förbättrar bålstabilitet, balans och styrka i gluteus medius.', 'Stående med band runt anklarna, lyft ett ben i sidled samtidigt som du balanserar.', 'Håll bålen aktiverad och blicken framåt för balans.', 'Undvik vid grav fotledsinstabilitet.', 'Att gunga överkroppen för att underlätta benrörelsen.'),
('resistance-band-standing-balance-hip-abduction', 'pl', 'Stanie na jednej nodze z odwodzeniem bioder z gumą', 'Stojące odwodzenie z gumą, z zachowaniem równowagi na jednej nodze.', 'Poprawia stabilność core, równowagę i siłę pośladka średniego.', 'Stojąc z gumą wokół kostek, unieś jedną nogę w bok, zachowując równowagę.', 'Utrzymuj napięty core i patrz przed siebie, aby pomóc w równowadze.', 'Unikaj w przypadku poważnej niestabilności stawu skokowego.', 'Kołysanie tułowiem w celu ułatwienia ruchu nogi.'),
('resistance-band-standing-balance-hip-abduction', 'id', 'Abduksi pinggul keseimbangan berdiri dengan pita', 'Abduksi berdiri dengan pita, sambil menjaga keseimbangan pada satu kaki.', 'Meningkatkan stabilitas core, keseimbangan, dan kekuatan gluteus medius.', 'Berdiri dengan pita di sekitar pergelangan kaki, angkat satu kaki ke samping sambil menyeimbangkan.', 'Jaga core tetap aktif dan lihat ke depan untuk membantu keseimbangan.', 'Hindari jika ada ketidakstabilan pergelangan kaki yang parah.', 'Mengayunkan batang tubuh untuk membantu gerakan kaki.'),
('resistance-band-standing-balance-hip-abduction', 'bn', 'ব্যান্ডের সাথে ব্যালেন্স হিপ অ্যাবডাকশন', 'ব্যান্ডের সাথে দাঁড়িয়ে অ্যাবডাকশন, এক পায়ে ভারসাম্য রক্ষা করে।', 'কোর স্থিতিশীলতা, ভারসাম্য এবং গ্লুটাস মিডিয়াসের শক্তি বাড়ায়।', 'গোড়ালিতে ব্যান্ড বেঁধে দাঁড়িয়ে ভারসাম্য রক্ষা করে এক পা পাশে তুলুন।', 'কোর শক্ত রাখুন এবং ভারসাম্য রাখতে সামনে তাকান।', 'গোড়ালিতে গুরুতর অস্থিরতা থাকলে এটি করবেন না।', 'পায়ের গতি বাড়াতে শরীর দোলানো।'),
('resistance-band-standing-balance-hip-abduction', 'vi', 'Đá chân ngang đứng thăng bằng với dây', 'Đá chân ngang với dây, duy trì thăng bằng trên một chân.', 'Cải thiện sự ổn định core, thăng bằng và sức mạnh cơ mông nhỡ.', 'Đứng với dây quanh cổ chân, nhấc một chân sang ngang trong khi giữ thăng bằng.', 'Giữ core siết chặt và nhìn về phía trước để giữ thăng bằng.', 'Tránh tập nếu bị mất ổn định cổ chân nghiêm trọng.', 'Lắc lư thân người để hỗ trợ chuyển động của chân.'),
('resistance-band-standing-balance-hip-abduction', 'fa', 'ابداکشن لگن با حفظ تعادل و باند', 'ابداکشن در حالت ایستاده با باند، در حالی که تعادل روی یک پا حفظ می‌شود.', 'ثبات هسته بدن، تعادل و قدرت سرینی متوسط را بهبود می‌بخشد.', 'در حالت ایستاده با باند دور مچ پا، تعادل خود را حفظ کرده و یک پا را به پهلو بلند کنید.', 'هسته بدن را منقبض و برای حفظ تعادل به جلو نگاه کنید.', 'در صورت ناپایداری شدید مچ پا انجام ندهید.', 'چرخش تنه برای کمک به حرکت پا.');