-- Definición del ejercicio
INSERT OR IGNORE INTO exercises (slug, img, video, difficulty) 
VALUES 
('hip-abduction-machine', 'hip-abduction-machine.jpg', 'hip-abduction-machine.mp4', 'beginner'),
('resistance-band-seated-hip-abduction', 'resistance-band-seated-hip-abduction.jpg', 'resistance-band-seated-hip-abduction.mp4', 'beginner');

-- Relación de grupo muscular
INSERT OR IGNORE INTO exercise_body_target (exercise_slug, body_target_slug) 
VALUES 
('resistance-band-seated-hip-abduction', 'abductors');

-- Relación de alternativas (vinculamos con la máquina para mayor contexto funcional)
INSERT OR IGNORE INTO exercise_alternative (exercise_slug, alternative_slug) 
VALUES 
('resistance-band-seated-hip-abduction', 'hip-abduction-machine');

-- Información multiidioma completa
INSERT OR IGNORE INTO exercises_info (slug, lang, title, description, benefits, instructions, tips, restrictions, mistakes) VALUES 
('resistance-band-seated-hip-abduction', 'es', 'Abducción sentado con banda', 'Ejercicio de abducción sentado enfocado en glúteo medio y menor.', 'Fortalece glúteos y mejora estabilidad pélvica.', 'Sentado con banda sobre rodillas, separa las piernas venciendo la resistencia.', 'Mantén espalda recta y torso estable.', 'No realizar si hay dolor lumbar o de cadera.', 'Cerrar las rodillas rápido sin control.'),
('resistance-band-seated-hip-abduction', 'en', 'Seated resistance band hip abduction', 'Seated abduction exercise focusing on gluteus medius and minimus.', 'Strengthens glutes and improves pelvic stability.', 'Seated with band around knees, push knees outward against resistance.', 'Keep back straight and torso stable.', 'Avoid if lower back or hip pain exists.', 'Allowing knees to snap shut without control.'),
('resistance-band-seated-hip-abduction', 'pt', 'Abdução de quadril sentado com faixa', 'Exercício de abdução sentado focado em glúteo médio e mínimo.', 'Fortalece glúteos e melhora a estabilidade pélvica.', 'Sentado com faixa nos joelhos, afaste os joelhos contra a resistência.', 'Mantenha as costas retas e o tronco estável.', 'Evitar se houver dor lombar ou no quadril.', 'Deixar os joelhos fecharem sem controle.'),
('resistance-band-seated-hip-abduction', 'fr', 'Abduction de hanche assise avec bande', 'Exercice d''abduction assis ciblant le moyen et petit fessier.', 'Renforce les fessiers et améliore la stabilité pelvienne.', 'Assis avec une bande autour des genoux, écartez les genoux contre la résistance.', 'Gardez le dos droit et le buste stable.', 'À éviter en cas de douleur lombaire ou de hanche.', 'Laisser les genoux se refermer sans contrôle.'),
('resistance-band-seated-hip-abduction', 'de', 'Sitzende Hüftabduktion mit Widerstandsband', 'Sitzende Abduktionsübung mit Fokus auf mittleren und kleinen Gesäßmuskel.', 'Stärkt die Gesäßmuskulatur und verbessert die Beckenstabilität.', 'Im Sitzen mit Band um die Knie die Beine gegen den Widerstand öffnen.', 'Rücken gerade und Oberkörper stabil halten.', 'Bei Rücken- oder Hüftschmerzen vermeiden.', 'Knie unkontrolliert zuschnappen lassen.'),
('resistance-band-seated-hip-abduction', 'it', 'Abduzione dell''anca da seduti con banda', 'Esercizio di abduzione da seduti mirato a gluteo medio e piccolo.', 'Rinforza i glutei e migliora la stabilità pelvica.', 'Seduto con banda attorno alle ginocchia, divarica le ginocchia contro resistenza.', 'Mantieni la schiena dritta e il busto stabile.', 'Evitare in caso di dolore lombare o all''anca.', 'Lasciar chiudere le ginocchia senza controllo.'),
('resistance-band-seated-hip-abduction', 'zh', '坐姿弹力带髋外展', '专注于臀中肌和臀小肌的坐姿外展练习。', '加强臀部并改善骨盆稳定性。', '坐在椅子上，将弹力带套在膝盖上，向外打开双膝。', '保持背部挺直，躯干稳定。', '如有腰痛或髋部疼痛，请避免。', '让膝盖不受控制地合拢。'),
('resistance-band-seated-hip-abduction', 'ja', '座位レジスタンスバンド・ヒップアブダクション', '中殿筋と小殿筋に焦点を当てた座位での外転運動。', '殿筋を強化し、骨盤の安定性を向上させます。', '椅子に座り膝にバンドを装着して、抵抗に逆らって膝を開きます。', '背筋を伸ばし、体幹を安定させます。', '腰痛や股関節痛がある場合は避けてください。', 'コントロールを失い膝が閉じてしまうこと。'),
('resistance-band-seated-hip-abduction', 'ko', '좌식 저항 밴드 힙 어브덕션', '중둔근과 소둔근에 집중한 앉아서 하는 외전 운동.', '둔근 강화 및 골반 안정성 향상.', '의자에 앉아 무릎에 밴드를 두르고 저항을 이겨내며 무릎을 벌림.', '허리를 곧게 펴고 상체를 안정적으로 유지.', '요통이나 고관절 통증 시 피할 것.', '제어하지 않고 무릎을 닫아버리는 것.'),
('resistance-band-seated-hip-abduction', 'ar', 'تمرين أبعاد الورك جالساً مع شريط مقاومة', 'تمرين أبعاد في وضع الجلوس يستهدف العضلة الألوية الوسطى والصغرى.', 'يقوي الأرداف ويحسن استقرار الحوض.', 'جالساً مع وضع الشريط حول الركبتين، افتح الركبتين ضد المقاومة.', 'حافظ على استقامة ظهرك وثبات جذعك.', 'تجنب في حالة وجود ألم في أسفل الظهر أو الورك.', 'السماح للركبتين بالانغلاق دون تحكم.'),
('resistance-band-seated-hip-abduction', 'hi', 'बैठकर रेजिस्टेंस बैंड हिप एबडक्शन', 'ग्लूटस मेडियस और मिनिमस पर केंद्रित बैठकर किया जाने वाला एबडक्शन व्यायाम।', 'कूल्हों को मजबूत करता है और पेल्विक स्थिरता में सुधार करता है।', 'घुटनों के चारों ओर बैंड के साथ बैठकर, प्रतिरोध के खिलाफ घुटनों को बाहर की ओर धकेलें।', 'पीठ को सीधा रखें और धड़ को स्थिर रखें।', 'यदि पीठ के निचले हिस्से या कूल्हे में दर्द हो तो न करें।', 'घुटनों को बिना नियंत्रण के बंद होने देना।'),
('resistance-band-seated-hip-abduction', 'ru', 'Отведение бедра сидя с эспандером', 'Сидячее упражнение на отведение, сфокусированное на средней и малой ягодичных мышцах.', 'Укрепляет ягодицы и улучшает стабильность таза.', 'Сидя с лентой на коленях, разводите ноги, преодолевая сопротивление.', 'Держите спину прямой, а корпус стабильным.', 'Избегайте при болях в пояснице или тазобедренном суставе.', 'Позволять коленям сходиться без контроля.'),
('resistance-band-seated-hip-abduction', 'nl', 'Zittende heupabductie met band', 'Zittende abductie-oefening gericht op gluteus medius en minimus.', 'Versterkt de bilspieren en verbetert bekkenstabiliteit.', 'Zittend met band rond de knieën, duw de knieën naar buiten tegen de weerstand in.', 'Houd de rug recht en de romp stabiel.', 'Vermijden bij onderrug- of heuppijn.', 'De knieën ongecontroleerd laten sluiten.'),
('resistance-band-seated-hip-abduction', 'sv', 'Sittande höftabduktion med band', 'Sittande abduktionsövning fokuserad på gluteus medius och minimus.', 'Stärker sätesmusklerna och förbättrar bäckenstabiliteten.', 'Sittande med band runt knäna, pressa knäna utåt mot motståndet.', 'Håll ryggen rak och överkroppen stabil.', 'Undvik vid rygg- eller höftsmärta.', 'Att låta knäna falla ihop utan kontroll.'),
('resistance-band-seated-hip-abduction', 'pl', 'Siedzące odwodzenie bioder z gumą', 'Siedzące ćwiczenie odwodzące skupione na mięśniu pośladkowym średnim i małym.', 'Wzmacnia pośladki i poprawia stabilność miednicy.', 'W siadzie z gumą wokół kolan wypychaj kolana na zewnątrz przeciw oporowi.', 'Utrzymuj proste plecy i stabilny tułów.', 'Unikaj w przypadku bólu pleców lub bioder.', 'Pozwalanie kolanom na bezwładne schodzenie się.'),
('resistance-band-seated-hip-abduction', 'id', 'Abduksi pinggul duduk dengan pita', 'Latihan abduksi duduk yang berfokus pada gluteus medius dan minimus.', 'Memperkuat otot bokong dan meningkatkan stabilitas panggul.', 'Duduk dengan pita di sekitar lutut, dorong lutut ke luar melawan hambatan.', 'Jaga punggung tetap lurus dan batang tubuh stabil.', 'Hindari jika ada nyeri punggung bawah atau pinggul.', 'Membiarkan lutut menutup tanpa kendali.'),
('resistance-band-seated-hip-abduction', 'bn', 'বসে রেজিস্ট্যান্স ব্যান্ড হিপ অ্যাবডাকশন', 'গ্লুটাস মিডিয়াস এবং মিনিমাসকে লক্ষ্য করে বসে করা অ্যাবডাকশন ব্যায়াম।', 'হিপের শক্তি বাড়ায় এবং পেলভিক স্থিতিশীলতা উন্নত করে।', 'হাঁটুর চারপাশে ব্যান্ড রেখে বসে হাঁটুকে বাইরের দিকে চাপ দিন।', 'পিঠ সোজা রাখুন এবং শরীর স্থির রাখুন।', 'পিঠের নিচের অংশে বা হিপে ব্যথা থাকলে এটি করবেন না।', 'হাঁটু নিয়ন্ত্রণহীনভাবে ভেতরে আসতে দেওয়া।'),
('resistance-band-seated-hip-abduction', 'vi', 'Đá chân ngang ngồi với dây', 'Bài tập giạng hông ngồi tập trung vào cơ mông nhỡ và mông bé.', 'Tăng cường cơ mông và cải thiện độ ổn định của khung chậu.', 'Ngồi với dây quanh đầu gối, đẩy đầu gối ra ngoài ngược với lực cản.', 'Giữ lưng thẳng và thân người ổn định.', 'Tránh tập nếu bị đau lưng dưới hoặc hông.', 'Để đầu gối khép lại mà không kiểm soát.'),
('resistance-band-seated-hip-abduction', 'fa', 'ابداکشن لگن نشسته با باند', 'تمرین ابداکشن در حالت نشسته با تمرکز بر عضله سرینی متوسط و کوچک.', 'عضلات باسن را تقویت کرده و ثبات لگن را بهبود می‌بخشد.', 'در حالت نشسته با باند دور زانوها، زانوها را در برابر مقاومت به بیرون فشار دهید.', 'کمر را صاف و تنه را ثابت نگه دارید.', 'در صورت درد کمر یا لگن انجام ندهید.', 'اجازه دادن به زانوها برای بسته شدن بدون کنترل.');