-- Definición de ambos ejercicios
INSERT OR IGNORE INTO exercises (slug, img, video, difficulty) 
VALUES 
('side-lying-hip-abduction', 'side-lying-hip-abduction.jpg', 'side-lying-hip-abduction.mp4', 'beginner'),
('resistance-band-clam', 'resistance-band-clam.jpg', 'resistance-band-clam.mp4', 'beginner');

-- Relación de grupo muscular
INSERT OR IGNORE INTO exercise_body_target (exercise_slug, body_target_slug) 
VALUES 
('resistance-band-clam', 'abductors');

-- Relaciones de alternativas
INSERT OR IGNORE INTO exercise_alternative (exercise_slug, alternative_slug) 
VALUES 
('resistance-band-clam', 'side-lying-hip-abduction');

-- Información multiidioma
INSERT OR IGNORE INTO exercises_info (slug, lang, title, description, benefits, instructions, tips, restrictions, mistakes) VALUES 
('resistance-band-clam', 'es', 'Almeja con banda de resistencia', 'Ejercicio de aislamiento para el glúteo medio realizado tumbado de lado, utilizando una banda alrededor de las rodillas.', 'Fortalece específicamente el glúteo medio y mejora la estabilidad de la pelvis.', 'Tumbado de lado con rodillas flexionadas, abre la rodilla superior contra la resistencia de la banda sin mover la pelvis.', 'Mantén los pies juntos durante todo el movimiento y evita rotar el tronco.', 'No realizar si hay dolor agudo en la zona lateral de la cadera.', 'Rotar la pelvis hacia atrás o usar una banda demasiado tensa que impide el rango completo.'),
('resistance-band-clam', 'en', 'Resistance band clam', 'Isolation exercise for the gluteus medius performed side-lying, using a band around the knees.', 'Specifically strengthens the gluteus medius and improves pelvic stability.', 'Lying on your side with knees bent, open the top knee against the band resistance without moving your pelvis.', 'Keep feet together throughout the movement and avoid rotating the torso.', 'Do not perform if there is acute lateral hip pain.', 'Rotating the pelvis backwards or using a band that is too tight, limiting range of motion.'),
('resistance-band-clam', 'pt', 'Concha com faixa de resistência', 'Exercício de isolamento para glúteo médio feito deitado de lado, usando uma faixa ao redor dos joelhos.', 'Fortalece especificamente o glúteo médio e melhora a estabilidade pélvica.', 'Deitado de lado com os joelhos dobrados, abra o joelho superior contra a resistência da faixa sem mover a pelve.', 'Mantenha os pés juntos durante todo o movimento e evite rotacionar o tronco.', 'Não realizar se houver dor aguda na região lateral do quadril.', 'Rotacionar a pelve para trás ou usar uma faixa muito tensa que limita a amplitude.'),
('resistance-band-clam', 'fr', 'Clamshell avec bande de résistance', 'Exercice d''isolation pour le moyen fessier réalisé allongé sur le côté, avec une bande autour des genoux.', 'Renforce spécifiquement le moyen fessier et améliore la stabilité pelvienne.', 'Allongé sur le côté, genoux fléchis, ouvrez le genou supérieur contre la résistance de la bande sans bouger le bassin.', 'Gardez les pieds joints pendant tout le mouvement et évitez de faire pivoter le tronc.', 'Ne pas effectuer en cas de douleur aiguë à la hanche latérale.', 'Pivoter le bassin vers l''arrière ou utiliser une bande trop tendue limitant l''amplitude.'),
('resistance-band-clam', 'de', 'Muschel-Übung (Clamshell) mit Widerstandsband', 'Isolationsübung für den mittleren Gesäßmuskel in Seitenlage mit einem Band um die Knie.', 'Stärkt gezielt den mittleren Gesäßmuskel und verbessert die Beckenstabilität.', 'In Seitenlage mit gebeugten Knien das obere Knie gegen den Bandwiderstand öffnen, ohne das Becken zu bewegen.', 'Halte die Füße während der gesamten Bewegung zusammen und vermeide es, den Rumpf zu drehen.', 'Bei akuten Schmerzen im seitlichen Hüftbereich nicht ausführen.', 'Becken nach hinten drehen oder ein zu starkes Band verwenden, das den Bewegungsumfang einschränkt.'),
('resistance-band-clam', 'it', 'Clamshell con banda elastica', 'Esercizio di isolamento per il gluteo medio eseguito sdraiati di lato, con una fascia attorno alle ginocchia.', 'Rinforza specificamente il gluteo medio e migliora la stabilità pelvica.', 'Sdraiato su un fianco con le ginocchia flesse, apri il ginocchio superiore contro la resistenza della fascia senza muovere il bacino.', 'Mantieni i piedi uniti durante tutto il movimento ed evita di ruotare il tronco.', 'Non eseguire in caso di dolore acuto all''anca laterale.', 'Ruotare il bacino all''indietro o utilizzare una fascia troppo tesa che limita l''ampiezza.'),
('resistance-band-clam', 'zh', '抗阻带侧卧蚌式开合', '侧卧进行的中臀肌孤立练习，在膝盖上方套上抗阻带。', '专门加强中臀肌并提高骨盆稳定性。', '侧卧，屈膝，克服阻带阻力张开上侧膝盖，骨盆保持不动。', '在整个动作过程中保持双脚并拢，避免躯干旋转。', '如有急性髋部侧向疼痛，请勿进行。', '骨盆向后旋转或使用过紧的阻力带限制运动范围。'),
('resistance-band-clam', 'ja', 'レジスタンスバンド・クラムシェル', '膝にバンドを装着し、横向きに寝て行う中殿筋のアイソレーションエクササイズ。', '中殿筋を重点的に強化し、骨盤の安定性を向上させます。', '横向きに寝て膝を曲げ、骨盤を動かさずにバンドの抵抗に逆らって上の膝を開きます。', '動作中ずっと足をついたままにし、体幹を回旋させないようにしてください。', '股関節の外側に激しい痛みがある場合は行わないでください。', '骨盤が後ろに倒れることや、強すぎるバンドを使って可動域が制限されること。'),
('resistance-band-clam', 'ko', '저항 밴드 클램셸', '무릎에 밴드를 감고 옆으로 누워 수행하는 중둔근 고립 운동.', '중둔근을 집중 강화하고 골반 안정성을 향상.', '옆으로 누워 무릎을 굽힌 뒤, 골반을 고정한 채 저항을 이겨내며 위쪽 무릎을 벌림.', '동작 내내 발을 붙이고 체간이 회전하지 않도록 주의.', '고관절 측면에 통증이 있다면 피할 것.', '골반이 뒤로 돌아가거나 너무 강한 밴드를 사용하여 가동 범위가 제한됨.'),
('resistance-band-clam', 'ar', 'تمرين المحار (Clamshell) مع شريط مقاومة', 'تمرين عزل للعضلة الألوية الوسطى يتم إجراؤه بالاستلقاء على الجانب مع وضع شريط حول الركبتين.', 'يقوي العضلة الألوية الوسطى بشكل خاص ويحسن استقرار الحوض.', 'استلقِ على جانبك مع ثني الركبتين، وافتح الركبة العلوية ضد مقاومة الشريط دون تحريك حوضك.', 'حافظ على ضم القدمين طوال الحركة وتجنب تدوير الجذع.', 'لا تقم بالتمرين في حالة وجود ألم حاد في جانب الورك.', 'تدوير الحوض للخلف أو استخدام شريط ضيق جداً يحد من نطاق الحركة.'),
('resistance-band-clam', 'hi', 'रेजिस्टेंस बैंड क्लैम', 'घुटनों के चारों ओर बैंड का उपयोग करके साइड-लाइंग में किया जाने वाला ग्लूटस मेडियस के लिए अलगाव व्यायाम।', 'विशेष रूप से ग्लूटस मेडियस को मजबूत करता है और कूल्हे की स्थिरता में सुधार करता है।', 'घुटने मोड़कर करवट लेकर लेटें, अपने पेल्विस को हिलाए बिना बैंड के प्रतिरोध के खिलाफ ऊपरी घुटने को खोलें।', 'पूरी गति के दौरान पैरों को साथ रखें और धड़ को घुमाने से बचें।', 'यदि कूल्हे के किनारे में तीव्र दर्द हो तो न करें।', 'पेल्विस को पीछे की ओर घुमाना या बहुत तंग बैंड का उपयोग करना जो गति की सीमा को सीमित करता है।'),
('resistance-band-clam', 'ru', 'Упражнение «Ракушка» с эспандером', 'Изолирующее упражнение для средней ягодичной мышцы в положении лежа на боку с лентой вокруг коленей.', 'Целенаправленно укрепляет среднюю ягодичную мышцу и улучшает стабильность таза.', 'Лежа на боку с согнутыми коленями, откройте верхнее колено, преодолевая сопротивление ленты, не двигая тазом.', 'Держите стопы вместе во время всего движения и избегайте вращения корпуса.', 'Не выполняйте при острой боли в боковой части бедра.', 'Вращение тазом назад или использование слишком тугой ленты, ограничивающей амплитуду.'),
('resistance-band-clam', 'nl', 'Resistance band clam', 'Isolatieoefening voor de gluteus medius uitgevoerd op de zij, met een band rond de knieën.', 'Versterkt specifiek de gluteus medius en verbetert de bekkenstabiliteit.', 'Liggend op de zij met gebogen knieën, open de bovenste knie tegen de weerstand van de band zonder het bekken te bewegen.', 'Houd de voeten bij elkaar tijdens de beweging en voorkom rotatie van de romp.', 'Niet uitvoeren bij acute pijn in de heupzijkant.', 'Het bekken naar achteren draaien of een te strakke band gebruiken die het bereik beperkt.'),
('resistance-band-clam', 'sv', 'Resistance band clam', 'Isolationsövning för gluteus medius utförd liggande på sidan, med ett band runt knäna.', 'Stärker specifikt gluteus medius och förbättrar bäckenstabiliteten.', 'Ligg på sidan med böjda knän, öppna det övre knät mot bandets motstånd utan att flytta bäckenet.', 'Håll fötterna ihop under hela rörelsen och undvik att rotera överkroppen.', 'Utför ej vid akut smärta i höftens utsida.', 'Rotera bäckenet bakåt eller använd ett för hårt band som begränsar rörelseomfånget.'),
('resistance-band-clam', 'pl', 'Muszelka z gumą oporową', 'Ćwiczenie izolujące mięsień pośladkowy średni w leżeniu na boku, z gumą wokół kolan.', 'Wzmacnia konkretnie pośladek średni i poprawia stabilność miednicy.', 'Leżąc na boku z ugiętymi kolanami, otwórz górne kolano przeciw oporowi gumy, nie poruszając miednicą.', 'Trzymaj stopy razem przez cały ruch i unikaj rotacji tułowia.', 'Nie wykonuj w przypadku ostrego bólu bocznej części biodra.', 'Rotowanie miednicy do tyłu lub używanie zbyt mocnej gumy, co ogranicza zakres ruchu.'),
('resistance-band-clam', 'id', 'Resistance band clam', 'Latihan isolasi untuk gluteus medius yang dilakukan berbaring menyamping, menggunakan pita di sekitar lutut.', 'Secara khusus memperkuat gluteus medius dan meningkatkan stabilitas panggul.', 'Berbaring menyamping dengan lutut ditekuk, buka lutut atas melawan hambatan pita tanpa menggerakkan panggul.', 'Jaga agar kaki tetap bersamaan sepanjang gerakan dan hindari memutar batang tubuh.', 'Jangan lakukan jika ada nyeri pinggul lateral akut.', 'Memutar panggul ke belakang atau menggunakan pita yang terlalu ketat sehingga membatasi rentang gerak.'),
('resistance-band-clam', 'bn', 'রেজিস্ট্যান্স ব্যান্ড ক্ল্যাম', 'হাঁটুর চারপাশে ব্যান্ড ব্যবহার করে পাশ ফিরে শুয়ে গ্লুটাস মিডিয়াসের জন্য আইসোলেশন ব্যায়াম।', 'বিশেষভাবে গ্লুটাস মিডিয়াসকে শক্তিশালী করে এবং পেলভিক স্থিতিশীলতা উন্নত করে।', 'হাঁটু বাঁকিয়ে শুয়ে পড়ুন এবং পেলভিস না নড়িয়ে ব্যান্ডের প্রতিরোধের বিপরীতে ওপরের হাঁটু খুলুন।', 'পুরো নড়াচড়ার সময় পা জোড়া রাখুন এবং শরীর ঘোরানো এড়িয়ে চলুন।', 'হিপের পাশে তীব্র ব্যথা থাকলে এটি করবেন না।', 'পেলভিস পেছনে ঘোরানো বা খুব টাইট ব্যান্ড ব্যবহার করা যা গতির সীমা কমায়।'),
('resistance-band-clam', 'vi', 'Clamshell với dây kháng lực', 'Bài tập cô lập cơ mông nhỡ khi nằm nghiêng, sử dụng dây kháng lực quanh đầu gối.', 'Tăng cường sức mạnh cơ mông nhỡ và cải thiện độ ổn định của khung chậu.', 'Nằm nghiêng, đầu gối gập, mở gối trên ngược với lực cản của dây mà không làm di chuyển khung chậu.', 'Giữ hai bàn chân chụm vào nhau trong suốt quá trình và tránh xoay thân người.', 'Không tập nếu bị đau hông bên cấp tính.', 'Xoay khung chậu về phía sau hoặc dùng dây quá chặt làm hạn chế phạm vi chuyển động.'),
('resistance-band-clam', 'fa', 'صدفی با باند مقاومتی (Resistance band clam)', 'تمرین ایزوله برای عضله سرینی متوسط که در حالت خوابیده به پهلو و با باند دور زانوها انجام می‌شود.', 'به طور خاص سرینی متوسط را تقویت کرده و ثبات لگن را بهبود می‌بخشد.', 'به پهلو دراز بکشید، زانوها را خم کنید و زانوی بالایی را در برابر مقاومت باند باز کنید، بدون اینکه لگن حرکت کند.', 'در طول حرکت پاها را کنار هم نگه دارید و از چرخش تنه خودداری کنید.', 'در صورت درد حاد در ناحیه جانبی لگن انجام ندهید.', 'چرخش لگن به عقب یا استفاده از باند خیلی سفت که دامنه حرکتی را محدود می‌کند.');