-- 1. Registro en la tabla principal
INSERT OR IGNORE INTO exercises (slug, img, video, difficulty) 
VALUES 
('resistance-band-clam', 'resistance-band-clam.jpg', 'resistance-band-clam.mp4', 'beginner'),
('side-lying-hip-abduction', 'side-lying-hip-abduction.jpg', 'side-lying-hip-abduction.mp4', 'beginner');

-- 2. Registro de grupo muscular
INSERT OR IGNORE INTO exercise_body_target (exercise_slug, body_target_slug) 
VALUES ('side-lying-hip-abduction', 'abductors');

-- 3. Registro de alternativas (ejemplo de enlace)
INSERT OR IGNORE INTO exercise_alternative (exercise_slug, alternative_slug) 
VALUES ('side-lying-hip-abduction', 'resistance-band-clam');

-- 4. Registro completo de información multiidioma
INSERT OR IGNORE INTO exercises_info (slug, lang, title, description, benefits, instructions, tips, restrictions, mistakes) VALUES 
('side-lying-hip-abduction', 'es', 'Elevación de pierna lateral tumbado', 'Ejercicio de peso corporal que aísla el glúteo medio y los abductores.', 'Fortalece los estabilizadores de la cadera sin impacto.', 'Tumbado de lado, eleva la pierna superior manteniéndola estirada y vuelve a bajar.', 'Mantén el pie paralelo al suelo y evita rotar la cadera hacia atrás.', 'No realizar si hay dolor agudo en la zona lateral de la cadera.', 'Elevar la pierna demasiado rápido o dejar caer la pelvis.'),
('side-lying-hip-abduction', 'en', 'Side-lying hip abduction', 'Bodyweight exercise that isolates the gluteus medius and abductors.', 'Strengthens hip stabilizers without impact.', 'Lying on your side, lift the top leg while keeping it straight, then lower it.', 'Keep foot parallel to the floor and avoid rotating the hip backwards.', 'Do not perform if acute lateral hip pain exists.', 'Lifting the leg too fast or letting the pelvis drop.'),
('side-lying-hip-abduction', 'pt', 'Abdução de quadril deitado de lado', 'Exercício de peso corporal que isola o glúteo médio e os abdutores.', 'Fortalece os estabilizadores do quadril sem impacto.', 'Deitado de lado, eleve a perna superior mantendo-a esticada e volte a baixar.', 'Mantenha o pé paralelo ao chão e evite rotacionar o quadril para trás.', 'Não realizar se houver dor aguda na região lateral do quadril.', 'Elevar a perna rápido demais ou deixar a pelve cair.'),
('side-lying-hip-abduction', 'fr', 'Abduction de hanche couché sur le côté', 'Exercice au poids du corps qui isole le moyen fessier et les abducteurs.', 'Renforce les stabilisateurs de la hanche sans impact.', 'Allongé sur le côté, levez la jambe supérieure en la gardant tendue, puis abaissez-la.', 'Gardez le pied parallèle au sol et évitez de faire pivoter la hanche vers l''arrière.', 'À éviter en cas de douleur aiguë à la hanche latérale.', 'Lever la jambe trop vite ou laisser le bassin tomber.'),
('side-lying-hip-abduction', 'de', 'Seitliche Hüftabduktion in Seitenlage', 'Körpergewichtsübung zur Isolierung des mittleren Gesäßmuskels und der Abduktoren.', 'Stärkt die Hüftstabilisatoren ohne Aufprall.', 'In Seitenlage das obere Bein gestreckt anheben und wieder absenken.', 'Fuß parallel zum Boden halten und die Hüfte nicht nach hinten drehen.', 'Bei akuten Schmerzen im seitlichen Hüftbereich nicht ausführen.', 'Das Bein zu schnell anheben oder das Becken absinken lassen.'),
('side-lying-hip-abduction', 'it', 'Abduzione dell''anca da sdraiati sul fianco', 'Esercizio a corpo libero che isola il gluteo medio e gli abduttori.', 'Rinforza gli stabilizzatori dell''anca senza impatto.', 'Sdraiato su un fianco, solleva la gamba superiore mantenendola tesa, poi abbassala.', 'Mantieni il piede parallelo al suolo ed evita di ruotare l''anca all''indietro.', 'Non eseguire in caso di dolore acuto all''anca laterale.', 'Sollevare la gamba troppo velocemente o lasciar cadere il bacino.'),
('side-lying-hip-abduction', 'zh', '侧卧髋外展', '自重练习，孤立锻炼臀中肌和外展肌。', '在无冲击的情况下加强髋部稳定肌。', '侧卧，向上抬起伸直的上腿，然后放下。', '保持脚与地面平行，避免髋部向后旋转。', '如有急性髋部侧向疼痛，请勿进行。', '抬腿过快或盆骨下沉。'),
('side-lying-hip-abduction', 'ja', 'サイドライイング・ヒップアブダクション', '中殿筋と外転筋を分離する自重エクササイズ。', '衝撃を与えずに股関節の安定筋を強化します。', '横向きに寝て、脚を伸ばしたまま上に上げ、戻します。', '足を床と平行に保ち、股関節を後ろに回さないようにしてください。', '股関節の外側に激しい痛みがある場合は行わないでください。', '脚を速く上げすぎることや、骨盤が落ちること。'),
('side-lying-hip-abduction', 'ko', '사이드 라잉 힙 어브덕션', '중둔근과 외전근을 고립시키는 맨몸 운동.', '충격 없이 고관절 안정근 강화.', '옆으로 누워 위쪽 다리를 곧게 펴서 올렸다가 내림.', '발을 바닥과 평행하게 유지하고 골반이 뒤로 돌아가지 않도록 주의.', '고관절 측면에 통증이 있다면 피할 것.', '다리를 너무 빠르게 올리거나 골반이 처지는 것.'),
('side-lying-hip-abduction', 'ar', 'تمرين أبعاد الورك بالاستلقاء الجانبي', 'تمرين بوزن الجسم يعزل العضلة الألوية الوسطى والأبعاد.', 'يقوي مثبتات الورك بدون تأثير.', 'استلقِ على جانبك، وارفع الساق العلوية مع إبقائها مستقيمة، ثم أنزلها.', 'حافظ على موازاة القدم للأرض وتجنب تدوير الورك للخلف.', 'لا تقم بالتمرين في حالة وجود ألم حاد في جانب الورك.', 'رفع الساق بسرعة كبيرة أو السماح للحوض بالهبوط.'),
('side-lying-hip-abduction', 'hi', 'साइड-लाइंग हिप एबडक्शन', 'ग्लूटस मेडियस और एबडक्टर्स को अलग करने वाला बॉडीवेट व्यायाम।', 'बिना किसी प्रभाव के कूल्हे के स्टेबलाइजर्स को मजबूत करता है।', 'करवट लेकर लेटें, ऊपरी पैर को सीधा रखते हुए ऊपर उठाएं, फिर नीचे लाएं।', 'पैर को फर्श के समानांतर रखें और कूल्हे को पीछे की ओर घुमाने से बचें।', 'यदि कूल्हे के किनारे में तीव्र दर्द हो तो न करें।', 'पैर को बहुत तेजी से उठाना या पेल्विस को नीचे गिरने देना.'),
('side-lying-hip-abduction', 'ru', 'Отведение бедра лежа на боку', 'Упражнение с собственным весом для изоляции средней ягодичной мышцы и отводящих мышц.', 'Укрепляет мышцы-стабилизаторы бедра без ударной нагрузки.', 'Лежа на боку, поднимите верхнюю ногу, удерживая ее прямой, затем опустите.', 'Держите стопу параллельно полу и избегайте вращения таза назад.', 'Не выполняйте при острой боли в боковой части бедра.', 'Подъем ноги слишком быстро или провисание таза.'),
('side-lying-hip-abduction', 'nl', 'Zijliggende heupabductie', 'Lichaamsgewichtoefening die de gluteus medius en abductoren isoleert.', 'Versterkt de heupstabilisatoren zonder impact.', 'Liggend op de zij, til het bovenste been op terwijl je het gestrekt houdt, en laat het zakken.', 'Houd de voet parallel aan de vloer en voorkom dat de heup naar achteren draait.', 'Niet uitvoeren bij acute pijn in de heupzijkant.', 'Het been te snel optillen of het bekken laten zakken.'),
('side-lying-hip-abduction', 'sv', 'Liggande höftabduktion', 'Kroppsviktsövning som isolerar gluteus medius och abduktorer.', 'Stärker höftstabilisatorer utan belastning.', 'Liggande på sidan, lyft det övre benet medan du håller det rakt, sänk sedan.', 'Håll foten parallellt med golvet och undvik att rotera höften bakåt.', 'Utför ej vid akut smärta i höftens utsida.', 'Att lyfta benet för snabbt eller låta bäckenet falla.'),
('side-lying-hip-abduction', 'pl', 'Leżące odwodzenie bioder', 'Ćwiczenie z masą ciała izolujące mięsień pośladkowy średni i odwodziciele.', 'Wzmacnia stabilizatory bioder bez obciążenia.', 'Leżąc na boku, unieś górną nogę, trzymając ją prosto, a następnie opuść.', 'Utrzymuj stopę równolegle do podłogi i unikaj rotacji biodra do tyłu.', 'Nie wykonuj w przypadku ostrego bólu bocznej części biodra.', 'Zbyt szybkie unoszenie nogi lub opadanie miednicy.'),
('side-lying-hip-abduction', 'id', 'Abduksi pinggul berbaring menyamping', 'Latihan berat badan yang mengisolasi gluteus medius dan abduktor.', 'Memperkuat penstabil pinggul tanpa dampak.', 'Berbaring menyamping, angkat kaki atas sambil menjaga tetap lurus, lalu turunkan.', 'Jaga kaki sejajar dengan lantai dan hindari memutar pinggul ke belakang.', 'Jangan lakukan jika ada nyeri pinggul lateral akut.', 'Mengangkat kaki terlalu cepat atau membiarkan panggul jatuh.'),
('side-lying-hip-abduction', 'bn', 'সাইড-লাইং হিপ অ্যাবডাকশন', 'গ্লুটাস মিডিয়াস এবং অ্যাবডাক্টরকে আইসোলেট করার জন্য বডিওয়েট ব্যায়াম।', 'কোনো প্রভাব ছাড়াই হিপের স্ট্যাবিলাইজার শক্তিশালী করে।', 'পাশ ফিরে শুয়ে ওপরের পা সোজা রেখে তুলুন এবং নামান।', 'পা মেঝের সমান্তরাল রাখুন এবং হিপ পেছনে ঘোরানো এড়িয়ে চলুন।', 'হিপের পাশে তীব্র ব্যথা থাকলে এটি করবেন না।', 'পা খুব দ্রুত তোলা বা পেলভিস নিচে পড়ে যাওয়া।'),
('side-lying-hip-abduction', 'vi', 'Đá chân ngang nằm nghiêng', 'Bài tập với trọng lượng cơ thể cô lập cơ mông nhỡ và cơ giạng.', 'Tăng cường sức mạnh cơ ổn định hông mà không gây chấn động.', 'Nằm nghiêng, nâng chân trên lên trong khi giữ thẳng, sau đó hạ xuống.', 'Giữ bàn chân song song với sàn và tránh xoay hông về phía sau.', 'Không tập nếu bị đau hông bên cấp tính.', 'Nhấc chân quá nhanh hoặc để khung chậu hạ xuống.'),
('side-lying-hip-abduction', 'fa', 'ابداکشن لگن در حالت خوابیده به پهلو', 'تمرین با وزن بدن که عضله سرینی متوسط و ابداکتورها را ایزوله می‌کند.', 'ثبات‌دهنده‌های لگن را بدون ضربه تقویت می‌کند.', 'به پهلو دراز بکشید، پای بالایی را صاف بلند کرده و سپس پایین بیاورید.', 'پا را موازی با زمین نگه دارید و از چرخش لگن به عقب خودداری کنید.', 'در صورت درد حاد در ناحیه جانبی لگن انجام ندهید.', 'بلند کردن سریع پا یا افتادن لگن.');