-- 1. Registro
INSERT OR IGNORE INTO exercises (slug, img, video, difficulty) 
VALUES ('single-leg-glute-bridge-abduction', 'single-leg-glute-bridge-abduction.jpg', 'single-leg-glute-bridge-abduction.mp4', 'advanced');

-- 2. Relación músculo
INSERT OR IGNORE INTO exercise_body_target (exercise_slug, body_target_slug) 
VALUES ('single-leg-glute-bridge-abduction', 'abductors');

-- 3. Relación alternativa
INSERT OR IGNORE INTO exercise_alternative (exercise_slug, alternative_slug) 
VALUES ('single-leg-glute-bridge-abduction', 'resistance-band-clam');

-- 4. Info multiidioma
INSERT OR IGNORE INTO exercises_info (slug, lang, title, description, benefits, instructions, tips, restrictions, mistakes) VALUES 
('single-leg-glute-bridge-abduction', 'es', 'Puente de glúteo a una pierna con abducción', 'Puente de glúteo elevando una pierna y añadiendo una apertura lateral.', 'Fortalece glúteos y mejora la estabilidad pélvica.', 'En posición de puente, eleva una pierna y ábrela lateralmente manteniendo el control.', 'Mantén la pelvis elevada y no dejes que el torso se incline.', 'No realizar si hay dolor lumbar.', 'Dejar caer la cadera o balancear el cuerpo.'),
('single-leg-glute-bridge-abduction', 'en', 'Single-leg glute bridge abduction', 'Glute bridge elevating one leg and adding a lateral opening.', 'Strengthens glutes and improves pelvic stability.', 'In bridge position, lift one leg and open it laterally maintaining control.', 'Keep pelvis elevated and do not let the torso tilt.', 'Avoid if lower back pain exists.', 'Letting the hip drop or swinging the body.'),
('single-leg-glute-bridge-abduction', 'pt', 'Ponte de glúteo unilateral com abdução', 'Ponte de glúteo elevando uma perna e adicionando uma abertura lateral.', 'Fortalece glúteos e melhora a estabilidade pélvica.', 'Na posição de ponte, eleve uma perna e abra lateralmente mantendo o controle.', 'Mantenha a pelve elevada e não deixe o tronco inclinar.', 'Evitar se houver dor lombar.', 'Deixar o quadril cair ou balançar o corpo.'),
('single-leg-glute-bridge-abduction', 'fr', 'Pont fessier sur une jambe avec abduction', 'Pont fessier en levant une jambe et en ajoutant une ouverture latérale.', 'Renforce les fessiers et améliore la stabilité pelvienne.', 'En position de pont, levez une jambe et ouvrez-la latéralement en gardant le contrôle.', 'Gardez le bassin élevé et ne laissez pas le buste basculer.', 'À éviter en cas de douleur lombaire.', 'Laisser tomber la hanche ou balancer le corps.'),
('single-leg-glute-bridge-abduction', 'de', 'Einbeinige Glute Bridge mit Abduktion', 'Glute Bridge mit angehobenem Bein und seitlichem Öffnen.', 'Stärkt Gesäßmuskeln und verbessert die Beckenstabilität.', 'In Brückenposition ein Bein heben und kontrolliert seitlich öffnen.', 'Becken oben halten und Oberkörper nicht kippen lassen.', 'Bei Rückenschmerzen vermeiden.', 'Hüfte absinken lassen oder Körper schwingen.'),
('single-leg-glute-bridge-abduction', 'it', 'Ponte per glutei a una gamba con abduzione', 'Ponte per glutei sollevando una gamba e aggiungendo un''apertura laterale.', 'Rinforza i glutei e migliora la stabilità pelvica.', 'In posizione di ponte, solleva una gamba e aprila lateralmente mantenendo il controllo.', 'Mantieni il bacino elevato e non lasciare che il busto si inclini.', 'Evitare in caso di dolore lombare.', 'Lasciar cadere l''anca o oscillare il corpo.'),
('single-leg-glute-bridge-abduction', 'zh', '单腿臀桥外展', '在抬起一条腿的同时进行臀桥，并增加侧向开合。', '加强臀部并改善骨盆稳定性。', '在臀桥位置，抬起一条腿并保持控制地向侧方打开。', '保持骨盆抬高，不要让躯干倾斜。', '如有腰痛，请避免。', '臀部下沉或晃动身体。'),
('single-leg-glute-bridge-abduction', 'ja', '片脚グルートブリッジ・アブダクション', '片脚を上げた状態でグルートブリッジを行い、外転を加える運動。', '殿筋を強化し、骨盤の安定性を向上させます。', 'ブリッジの姿勢で片脚を上げ、コントロールしながら横に開きます。', '骨盤を高く保ち、体幹が傾かないようにしてください。', '腰痛がある場合は避けてください。', '腰が落ちることや、体が揺れること。'),
('single-leg-glute-bridge-abduction', 'ko', '한 발 둔근 브릿지 외전', '한쪽 다리를 들고 둔근 브릿지를 수행하며 외전을 추가.', '둔근 강화 및 골반 안정성 향상.', '브릿지 자세에서 한쪽 다리를 들고 제어하며 옆으로 벌림.', '골반을 높게 유지하고 상체가 기울지 않도록 주의.', '요통 시 피할 것.', '골반이 처지거나 몸이 흔들리는 것.'),
('single-leg-glute-bridge-abduction', 'ar', 'تمرين جسر الأرداف بساق واحدة مع الأبعاد', 'جسر الأرداف مع رفع ساق واحدة وإضافة فتح جانبي.', 'يقوي الأرداف ويحسن استقرار الحوض.', 'في وضع الجسر، ارفع ساقاً واحدة وافتحها جانبياً مع الحفاظ على التحكم.', 'حافظ على ارتفاع الحوض ولا تدع الجذع يميل.', 'تجنب في حالة وجود ألم في أسفل الظهر.', 'سقوط الورك أو أرجحة الجسم.'),
('single-leg-glute-bridge-abduction', 'hi', 'सिंगल-लेग ग्लूट ब्रिज एबडक्शन', 'एक पैर ऊपर उठाकर और साइड में खोलकर किया जाने वाला ग्लूट ब्रिज।', 'कूल्हों को मजबूत करता है और पेल्विक स्थिरता में सुधार करता है।', 'ब्रिज स्थिति में, एक पैर उठाएं और नियंत्रण रखते हुए इसे बगल में खोलें।', 'पेल्विस ऊपर रखें और धड़ को झुकने न दें।', 'यदि पीठ के निचले हिस्से में दर्द हो तो न करें।', 'कूल्हे को नीचे गिरने देना या शरीर को हिलाना।'),
('single-leg-glute-bridge-abduction', 'ru', 'Ягодичный мостик на одной ноге с отведением', 'Мостик с поднятой ногой и добавлением отведения в сторону.', 'Укрепляет ягодицы и улучшает стабильность таза.', 'В позиции мостика поднимите ногу и отведите ее в сторону, сохраняя контроль.', 'Держите таз высоко, не позволяйте корпусу наклоняться.', 'Избегайте при болях в пояснице.', 'Опускание бедра или раскачивание корпуса.'),
('single-leg-glute-bridge-abduction', 'nl', 'Single-leg glute bridge abduction', 'Glute bridge met één been omhoog en een zijwaartse opening.', 'Versterkt de bilspieren en verbetert bekkenstabiliteit.', 'In brugpositie, til één been op en open zijwaarts met controle.', 'Houd het bekken hoog en laat het bovenlichaam niet kantelen.', 'Vermijden bij onderrugpijn.', 'Heup laten zakken of het lichaam zwaaien.'),
('single-leg-glute-bridge-abduction', 'sv', 'Single-leg glute bridge abduction', 'Glute bridge med ett ben lyft och en sidöppning.', 'Stärker sätesmusklerna och förbättrar bäckenstabiliteten.', 'I bryggposition, lyft ett ben och öppna det i sidled med kontroll.', 'Håll bäckenet högt och låt inte överkroppen luta.', 'Undvik vid ländryggssmärta.', 'Att låta höften sjunka eller gunga med kroppen.'),
('single-leg-glute-bridge-abduction', 'pl', 'Mostek biodrowy na jednej nodze z odwodzeniem', 'Mostek biodrowy z uniesioną nogą i dodaniem odwodzenia bocznego.', 'Wzmacnia pośladki i poprawia stabilność miednicy.', 'W pozycji mostka unieś nogę i otwórz ją bokiem, zachowując kontrolę.', 'Trzymaj miednicę wysoko i nie pozwól tułowiu się przechylać.', 'Unikaj w przypadku bólu lędźwi.', 'Opadanie biodra lub kołysanie ciałem.'),
('single-leg-glute-bridge-abduction', 'id', 'Single-leg glute bridge abduction', 'Glute bridge dengan mengangkat satu kaki dan menambahkan bukaan lateral.', 'Memperkuat otot bokong dan meningkatkan stabilitas panggul.', 'Dalam posisi bridge, angkat satu kaki dan buka ke samping dengan terkontrol.', 'Jaga panggul tetap tinggi dan jangan biarkan batang tubuh miring.', 'Hindari jika ada nyeri punggung bawah.', 'Membiarkan pinggul turun atau mengayunkan tubuh.'),
('single-leg-glute-bridge-abduction', 'bn', 'সিঙ্গেল-লেগ গ্লুট ব্রিজ অ্যাবডাকশন', 'এক পা উপরে তুলে গ্লুট ব্রিজ এবং পাশে খোলা।', 'গ্লুটস শক্তিশালী করে এবং পেলভিক স্থিতিশীলতা উন্নত করে।', 'ব্রিজ পজিশনে এক পা তুলে নিয়ন্ত্রণে রেখে পাশে খুলুন।', 'পেলভিস উঁচু রাখুন এবং শরীর ঝুকতে দেবেন না।', 'পিঠের নিচের অংশে ব্যথা থাকলে এটি করবেন না।', 'হিপ নিচে পড়ে যাওয়া বা শরীর দোলানো।'),
('single-leg-glute-bridge-abduction', 'vi', 'Cầu mông một chân với đá ngang', 'Cầu mông khi nhấc một chân và thêm chuyển động mở ngang.', 'Tăng cường cơ mông và cải thiện độ ổn định vùng chậu.', 'Ở tư thế cầu, nhấc một chân và mở sang ngang trong khi kiểm soát.', 'Giữ khung chậu cao và không để thân người nghiêng.', 'Tránh tập nếu bị đau lưng dưới.', 'Để hông hạ xuống hoặc lắc lư thân người.'),
('single-leg-glute-bridge-abduction', 'fa', 'پل باسن تک پا با ابداکشن', 'پل باسن با بلند کردن یک پا و اضافه کردن باز کردن جانبی.', 'عضلات باسن را تقویت کرده و ثبات لگن را بهبود می‌بخشد.', 'در حالت پل، یک پا را بلند کرده و با کنترل به پهلو باز کنید.', 'لگن را بالا نگه دارید و اجازه ندهید تنه کج شود.', 'در صورت درد کمر انجام ندهید.', 'افتادن لگن یا تکان دادن بدن.');