-- Definición del ejercicio
INSERT OR IGNORE INTO exercises (slug, img, video, difficulty) 
VALUES 
('wall-push-abduction', 'wall-push-abduction.jpg', 'wall-push-abduction.mp4', 'beginner');

-- Relación de grupo muscular
INSERT OR IGNORE INTO exercise_body_target (exercise_slug, body_target_slug) 
VALUES 
('wall-push-abduction', 'abductors');

-- Relaciones de alternativas
INSERT OR IGNORE INTO exercise_alternative (exercise_slug, alternative_slug) 
VALUES 
('wall-push-abduction', 'standing-hip-abduction');

-- Información multiidioma
INSERT OR IGNORE INTO exercises_info (slug, lang, title, description, benefits, instructions, tips, restrictions, mistakes) VALUES 
('wall-push-abduction', 'es', 'Abducción contra la pared', 'Ejercicio isométrico presionando la pierna lateralmente contra una pared.', 'Fortalece abductores sin estrés articular.', 'De pie junto a una pared, presiona la cara externa de la rodilla contra ella.', 'Mantén la postura erguida y no apoyes el peso sobre la pared.', 'Evitar si hay dolor agudo de cadera.', 'Empujar solo con el pie o inclinarse hacia la pared.'),
('wall-push-abduction', 'en', 'Wall-push abduction', 'Isometric exercise pressing the leg laterally against a wall.', 'Strengthens abductors without joint stress.', 'Standing next to a wall, press the outer side of your knee against it.', 'Keep posture upright and do not lean weight against the wall.', 'Avoid if acute hip pain exists.', 'Pushing only with the foot or leaning into the wall.'),
('wall-push-abduction', 'pt', 'Abdução contra a parede', 'Exercício isométrico pressionando a perna lateralmente contra uma parede.', 'Fortalece abdutores sem estresse articular.', 'Em pé ao lado de uma parede, pressione a face externa do joelho contra ela.', 'Mantenha a postura ereta e não apoie o peso na parede.', 'Evitar se houver dor aguda no quadril.', 'Empurrar apenas com o pé ou inclinar-se contra a parede.'),
('wall-push-abduction', 'fr', 'Abduction contre le mur', 'Exercice isométrique en pressant la jambe latéralement contre un mur.', 'Renforce les abducteurs sans stress articulaire.', 'Debout contre un mur, pressez la face externe du genou contre celui-ci.', 'Gardez une posture droite et ne vous appuyez pas sur le mur.', 'À éviter en cas de douleur aiguë à la hanche.', 'Pousser uniquement avec le pied ou se pencher contre le mur.'),
('wall-push-abduction', 'de', 'Abduktion gegen die Wand', 'Isometrische Übung durch seitliches Drücken des Beins gegen eine Wand.', 'Stärkt Abduktoren ohne Gelenkbelastung.', 'Neben einer Wand stehen, die Außenseite des Knies gegen die Wand drücken.', 'Aufrechte Haltung bewahren und Gewicht nicht auf die Wand verlagern.', 'Bei akuten Hüftschmerzen vermeiden.', 'Nur mit dem Fuß drücken oder gegen die Wand lehnen.'),
('wall-push-abduction', 'it', 'Abduzione contro il muro', 'Esercizio isometrico premendo la gamba lateralmente contro un muro.', 'Rinforza gli abduttori senza stress articolare.', 'In piedi accanto a un muro, premi la parte esterna del ginocchio contro di esso.', 'Mantieni la postura eretta e non appoggiare il peso sul muro.', 'Evitare in caso di dolore acuto all''anca.', 'Spingere solo con il piede o inclinarsi contro il muro.'),
('wall-push-abduction', 'zh', '墙壁推外展', '等长收缩练习，将腿向侧方压向墙壁。', '在无关节压力的情况下加强外展肌。', '站在墙边，将膝盖外侧压向墙壁。', '保持姿势挺直，不要把重心压在墙上。', '如有急性髋部疼痛，请避免。', '仅用脚推或身体向墙壁倾斜。'),
('wall-push-abduction', 'ja', 'ウォールプッシュ・アブダクション', '脚を横に壁に押し付ける等尺性運動。', '関節に負担をかけずに外転筋を強化します。', '壁の横に立ち、膝の外側を壁に押し付けます。', '姿勢を正しく保ち、壁に体重をかけないようにしてください。', '股関節に激しい痛みがある場合は避けてください。', '足だけで押すことや、壁に寄りかかること。'),
('wall-push-abduction', 'ko', '벽 밀기 외전', '무릎 외측을 벽에 대고 미는 등척성 운동.', '관절 부담 없이 외전근 강화.', '벽 옆에 서서 무릎 바깥쪽을 벽에 대고 뺌.', '자세를 곧게 유지하고 벽에 체중을 싣지 않도록 주의.', '고관절 통증 시 피할 것.', '발로만 밀거나 벽 쪽으로 몸을 기울이는 것.'),
('wall-push-abduction', 'ar', 'تمرين الأبعاد بالضغط على الجدار', 'تمرين متساوي القياس عن طريق الضغط على الساق جانبياً مقابل الجدار.', 'يقوي الأبعاد بدون إجهاد للمفاصل.', 'قف بجانب الجدار، واضغط بالجانب الخارجي لركبتك ضده.', 'حافظ على استقامة القامة ولا تسند وزنك على الجدار.', 'تجنب في حالة وجود ألم حاد في الورك.', 'الضغط بالقدم فقط أو الميل نحو الجدار.'),
('wall-push-abduction', 'hi', 'वॉल-पुश एबडक्शन', 'आइसोमेट्रिक व्यायाम जिसमें पैर को दीवार के खिलाफ बगल में दबाया जाता है।', 'जोड़ों पर तनाव डाले बिना एबडक्टर्स को मजबूत करता है।', 'दीवार के बगल में खड़े होकर, घुटने के बाहरी हिस्से को दीवार पर दबाएं।', 'सीधे खड़े रहें और दीवार पर वजन न डालें।', 'यदि कूल्हे में तीव्र दर्द हो तो न करें।', 'केवल पैर से धक्का देना या दीवार की ओर झुकना।'),
('wall-push-abduction', 'ru', 'Отведение с опорой о стену', 'Изометрическое упражнение: давление ногой в сторону о стену.', 'Укрепляет отводящие мышцы без нагрузки на суставы.', 'Стоя у стены, давите внешней стороной колена на стену.', 'Держите осанку ровной, не переносите вес на стену.', 'Избегайте при острой боли в бедре.', 'Нажим только стопой или наклон в сторону стены.'),
('wall-push-abduction', 'nl', 'Wall-push abduction', 'Isometrische oefening waarbij het been zijwaarts tegen een muur wordt geduwd.', 'Versterkt abductoren zonder gewrichtsbelasting.', 'Staand naast een muur, druk de buitenkant van de knie tegen de muur.', 'Houd de houding rechtop en leun niet op de muur.', 'Vermijden bij acute heuppijn.', 'Alleen met de voet duwen of tegen de muur leunen.'),
('wall-push-abduction', 'sv', 'Wall-push abduction', 'Isometrisk övning genom att pressa benet i sidled mot en vägg.', 'Stärker abduktorer utan ledstress.', 'Stå vid en vägg, pressa knäets utsida mot väggen.', 'Håll hållningen upprätt och luta inte vikten mot väggen.', 'Undvik vid akut höftsmärta.', 'Att bara pressa med foten eller luta sig mot väggen.'),
('wall-push-abduction', 'pl', 'Odwodzenie przy ścianie', 'Ćwiczenie izometryczne polegające na naciskaniu nogą w bok na ścianę.', 'Wzmacnia odwodziciele bez obciążania stawów.', 'Stojąc przy ścianie, naciskaj zewnętrzną stroną kolana na ścianę.', 'Utrzymuj wyprostowaną postawę i nie opieraj ciężaru o ścianę.', 'Unikaj w przypadku ostrego bólu biodra.', 'Naciskanie tylko stopą lub przechylanie się na ścianę.'),
('wall-push-abduction', 'id', 'Wall-push abduction', 'Latihan isometrik dengan menekan kaki ke samping ke dinding.', 'Memperkuat abduktor tanpa stres sendi.', 'Berdiri di samping dinding, tekan bagian luar lutut ke dinding.', 'Jaga postur tegak dan jangan tumpukan berat badan ke dinding.', 'Hindari jika ada nyeri pinggul akut.', 'Menekan hanya dengan kaki atau bersandar ke dinding.'),
('wall-push-abduction', 'bn', 'ওয়াল-পুশ অ্যাবডাকশন', 'আইসোমেট্রিক ব্যায়াম যেখানে পা পাশের দিকে দেয়ালের বিরুদ্ধে চাপ দেওয়া হয়।', 'জয়েন্টে চাপ না দিয়ে অ্যাবডাক্টর শক্তিশালী করে।', 'দেয়ালের পাশে দাঁড়িয়ে হাঁটু বাইরের দিক থেকে দেয়ালের বিরুদ্ধে চাপুন।', 'সোজা হয়ে দাঁড়ান এবং দেয়ালে ওজন দেবেন না।', 'হিপে তীব্র ব্যথা থাকলে এটি করবেন না।', 'শুধু পা দিয়ে ধাক্কা দেওয়া বা দেয়ালের দিকে ঝুঁকে থাকা।'),
('wall-push-abduction', 'vi', 'Đá chân ngang vào tường', 'Bài tập đẳng trường bằng cách ép chân sang ngang vào tường.', 'Tăng cường cơ giạng mà không gây áp lực khớp.', 'Đứng gần tường, ép mặt ngoài đầu gối vào tường.', 'Giữ tư thế thẳng và không dồn trọng lượng vào tường.', 'Tránh tập nếu bị đau hông cấp tính.', 'Chỉ dùng bàn chân ép hoặc nghiêng người vào tường.'),
('wall-push-abduction', 'fa', 'تمرين ابداکشن با فشار به دیوار', 'تمرين ايزومتريک با فشار دادن پا به پهلو به ديوار.', 'ابداکتورها را بدون فشار به مفاصل تقويت مي‌کند.', 'کنار ديوار بايستيد، قسمت خارجي زانو را به ديوار فشار دهيد.', 'صاف بايستيد و وزن خود را به ديوار تکيه ندهيد.', 'در صورت درد شديد لگن انجام ندهيد.', 'فشار فقط با پا يا خم شدن به سمت ديوار.');