-- Definición del ejercicio y sus recursos
INSERT OR IGNORE INTO exercises (slug, img, video, difficulty) 
VALUES ('burpees', 'burpees.jpg', 'burpees.mp4', 'advanced');

-- Relación: el ejercicio trabaja el grupo muscular 'full_body'
INSERT OR IGNORE INTO exercise_body_target (exercise_slug, body_target_slug) 
VALUES ('burpees', 'full_body');

-- Relación: no requiere máquina
INSERT OR IGNORE INTO exercise_alternative (exercise_slug, alternative_slug) 
VALUES ('burpees', 'squat-jumps');

-- Información multiidioma del ejercicio
INSERT OR IGNORE INTO exercises_info (slug, lang, title, description, benefits, instructions, tips, restrictions, mistakes) VALUES 
('burpees', 'es', 'Burpees', 'Ejercicio de alta intensidad que combina sentadilla, flexión y salto.', 'Mejora la resistencia cardiovascular, la fuerza y la quema de calorías.', 'Desde posición de pie, baja a cuclillas, lanza los pies atrás, haz una flexión, vuelve a recoger y salta.', 'Mantén un ritmo constante y evita arquear la espalda al hacer la flexión.', 'Evitar si hay problemas articulares graves o cardiovasculares.', 'Realizar el movimiento de forma descontrolada o no completar el salto.'),
('burpees', 'en', 'Burpees', 'High-intensity exercise that combines a squat, a push-up, and a jump.', 'Improves cardiovascular endurance, strength, and calorie burn.', 'From a standing position, squat down, kick your feet back, do a push-up, jump feet forward, and jump up.', 'Maintain a steady pace and avoid arching your back during the push-up.', 'Avoid if you have serious joint or cardiovascular issues.', 'Performing the movement uncontrollably or not completing the jump.'),
('burpees', 'pt', 'Burpees', 'Exercício de alta intensidade que combina agachamento, flexão e salto.', 'Melhora a resistência cardiovascular, a força e a queima de calorias.', 'Da posição em pé, agache, lance os pés para trás, faça uma flexão, volte a recolher e salte.', 'Mantenha um ritmo constante e evite arquear as costas ao fazer a flexão.', 'Evitar se houver problemas articulares graves ou cardiovasculares.', 'Realizar o movimento de forma descontrolada ou não completar o salto.'),
('burpees', 'fr', 'Burpees', 'Exercice de haute intensité combinant squat, pompe et saut.', 'Améliore l''endurance cardiovasculaire, la force et la combustion des calories.', 'Depuis la position debout, accroupissez-vous, lancez les pieds en arrière, faites une pompe, revenez en position accroupie et sautez.', 'Gardez un rythme constant et évitez de cambrer le dos lors de la pompe.', 'À éviter en cas de problèmes articulaires graves ou cardiovasculaires.', 'Effectuer le mouvement de manière incontrôlée ou ne pas compléter le saut.'),
('burpees', 'de', 'Burpees', 'Hochintensive Übung, die Kniebeuge, Liegestütz und Sprung kombiniert.', 'Verbessert die kardiovaskuläre Ausdauer, Kraft und Kalorienverbrennung.', 'Aus dem Stand in die Hocke gehen, Füße nach hinten werfen, Liegestütz machen, wieder in die Hocke springen und hochspringen.', 'Halten Sie ein konstantes Tempo und vermeiden Sie es, beim Liegestütz den Rücken durchzuhängen.', 'Bei schweren Gelenk- oder Herz-Kreislauf-Problemen vermeiden.', 'Die Bewegung unkontrolliert ausführen oder den Sprung nicht vollständig abschließen.'),
('burpees', 'it', 'Burpees', 'Esercizio ad alta intensità che combina squat, flessione e salto.', 'Migliora la resistenza cardiovascolare, la forza e il consumo calorico.', 'Dalla posizione eretta, scendi in squat, lancia i piedi all''indietro, fai una flessione, torna in posizione e salta.', 'Mantieni un ritmo costante ed evita di inarcare la schiena durante la flessione.', 'Evitare in caso di gravi problemi articolari o cardiovascolari.', 'Eseguire il movimento in modo incontrollato o non completare il salto.'),
('burpees', 'zh', '波比跳 (Burpees)', '结合深蹲、俯卧撑和跳跃的高强度练习。', '提高心肺耐力、力量并消耗热量。', '站立姿势，下蹲，双脚后踢，做一个俯卧撑，收回双脚，然后向上跳跃。', '保持稳定的节奏，并在俯卧撑时避免拱背。', '如有严重的关节或心血管问题，请避免使用。', '动作失控或未完成跳跃动作。'),
('burpees', 'ja', 'バーピー', 'スクワット、腕立て伏せ、ジャンプを組み合わせた高強度エクササイズ。', '心肺持久力、筋力、カロリー消費を向上させます。', '立った状態からしゃがみ、足を後ろに蹴り出し、腕立て伏せを行い、足を戻して上にジャンプします。', '一定のペースを保ち、腕立て伏せの際に背中を反らさないようにします。', '重度の関節疾患や心血管疾患がある場合は避けてください。', 'コントロールを失った動作や、ジャンプを完了しないこと。'),
('burpees', 'ko', '버피', '스쿼트, 팔굽혀펴기, 점프를 결합한 고강도 운동.', '심혈관 지구력, 근력, 칼로리 소모를 향상합니다.', '선 자세에서 쪼그리고 앉아 발을 뒤로 뻗고, 팔굽혀펴기를 한 뒤, 다시 다리를 모으고 위로 점프합니다.', '일정한 속도를 유지하고 팔굽혀펴기를 할 때 허리가 젖혀지지 않게 하세요.', '심각한 관절이나 심혈관 질환이 있다면 피하세요.', '동작을 통제하지 못하거나 점프를 제대로 수행하지 않는 것.'),
('burpees', 'ar', 'تمرين بيربي (Burpees)', 'تمرين عالي الكثافة يجمع بين القرفصاء، تمرين الضغط، والقفز.', 'يحسن القدرة على التحمل القلبي الوعائي والقوة وحرق السعرات الحرارية.', 'من وضع الوقوف، انزل إلى وضع القرفصاء، ادفع قدميك للخلف، قم بتمرين الضغط، ثم عد إلى وضع القرفصاء واقفز.', 'حافظ على وتيرة ثابتة وتجنب تقوس ظهرك عند القيام بضغط الصدر.', 'تجنب التمرين في حالة وجود مشاكل مفصلية أو قلبية وعائية خطيرة.', 'القيام بالحركة بشكل غير محكوم أو عدم إكمال القفزة.'),
('burpees', 'hi', 'बर्पीज़', 'उच्च तीव्रता वाला व्यायाम जो स्क्वाट, पुश-अप और जंप को जोड़ता है।', 'हृदय सहनशक्ति, ताकत और कैलोरी बर्न में सुधार करता है।', 'खड़े होने की स्थिति से, स्क्वाट करें, पैरों को पीछे फेंकें, एक पुश-अप करें, वापस आएं और कूदें।', 'एक स्थिर गति बनाए रखें और पुश-अप करते समय अपनी पीठ को मोड़ने से बचें।', 'यदि गंभीर जोड़ों या हृदय संबंधी समस्याएं हों तो न करें।', 'अनियंत्रित तरीके से गति करना या कूदना पूरा न करना।'),
('burpees', 'ru', 'Бёрпи (Burpees)', 'Высокоинтенсивное упражнение, сочетающее приседание, отжимание и прыжок.', 'Улучшает сердечно-сосудистую выносливость, силу и сжигание калорий.', 'Из положения стоя присядьте, отбросьте ноги назад, отожмитесь, верните ноги обратно и выпрыгните вверх.', 'Держите постоянный темп и избегайте прогиба в спине при отжимании.', 'Избегайте при серьезных проблемах с суставами или сердечно-сосудистой системой.', 'Выполнение движения без контроля или неполное выполнение прыжка.'),
('burpees', 'nl', 'Burpees', 'Hoge intensiteit oefening die squat, push-up en sprong combineert.', 'Verbetert cardiovasculair uithoudingsvermogen, kracht en calorieverbranding.', 'Vanuit stand, hurk neer, schiet de voeten naar achteren, doe een push-up, trek de voeten in en spring omhoog.', 'Houd een constant tempo aan en voorkom dat je je rug hol trekt tijdens de push-up.', 'Vermijden bij ernstige gewrichts- of hart- en vaatproblemen.', 'De beweging ongecontroleerd uitvoeren of de sprong niet afmaken.'),
('burpees', 'sv', 'Burpees', 'Högintensiv övning som kombinerar knäböj, armhävning och hopp.', 'Förbättrar kondition, styrka och kaloriförbränning.', 'Från stående, gå ner i knäböj, skjut bak fötterna, gör en armhävning, hoppa fram med fötterna och hoppa upp.', 'Håll ett jämnt tempo och undvik att svanka under armhävningen.', 'Undvik vid allvarliga led- eller hjärt-kärlproblem.', 'Att utföra rörelsen okontrollerat eller att inte fullfölja hoppet.'),
('burpees', 'pl', 'Burpees', 'Ćwiczenie o wysokiej intensywności łączące przysiad, pompkę i wyskok.', 'Poprawia wytrzymałość sercowo-naczyniową, siłę i spalanie kalorii.', 'Z pozycji stojącej przejdź do przysiadu, wyrzuć nogi do tyłu, zrób pompkę, wróć nogami do przysiadu i wyskocz w górę.', 'Utrzymuj stałe tempo i unikaj wyginania pleców podczas pompek.', 'Unikaj w przypadku poważnych problemów ze stawami lub układem krążenia.', 'Wykonywanie ruchu w sposób niekontrolowany lub niepełny wyskok.'),
('burpees', 'id', 'Burpees', 'Latihan intensitas tinggi yang menggabungkan squat, push-up, dan lompat.', 'Meningkatkan daya tahan kardiovaskular, kekuatan, dan pembakaran kalori.', 'Dari posisi berdiri, jongkok, tendang kaki ke belakang, lakukan push-up, tarik kaki kembali, dan melompat.', 'Jaga ritme yang konstan dan hindari melengkungkan punggung saat push-up.', 'Hindari jika ada masalah sendi atau kardiovaskular yang serius.', 'Melakukan gerakan secara tidak terkontrol atau tidak menyelesaikan lompatan.'),
('burpees', 'bn', 'বার্পি', 'একটি উচ্চ-তীব্রতার ব্যায়াম যা স্কোয়াট, পুশ-আপ এবং লাফকে একত্রিত করে।', 'কার্ডিওভাসকুলার সহনশীলতা, শক্তি এবং ক্যালোরি পোড়াতে সাহায্য করে।', 'দাঁড়ানো অবস্থা থেকে, স্কোয়াট করুন, পা পিছনের দিকে ফেলুন, একটি পুশ-আপ করুন, আবার ফিরে আসুন এবং লাফ দিন।', 'একটি স্থির গতি বজায় রাখুন এবং পুশ-আপ করার সময় পিঠ বাঁকানো এড়িয়ে চলুন।', 'গুরুতর জয়েন্ট বা কার্ডিওভাসকুলার সমস্যা থাকলে এড়িয়ে চলুন।', 'অনিয়ন্ত্রিতভাবে নড়াচড়া করা বা লাফ শেষ না করা।'),
('burpees', 'vi', 'Burpees', 'Bài tập cường độ cao kết hợp squat, hít đất và nhảy.', 'Cải thiện sức bền tim mạch, sức mạnh và đốt cháy calo.', 'Từ tư thế đứng, hạ người xuống squat, bật chân ra sau, hít đất, thu chân lại và nhảy lên.', 'Giữ nhịp độ ổn định và tránh võng lưng khi hít đất.', 'Tránh tập nếu có vấn đề nghiêm trọng về khớp hoặc tim mạch.', 'Thực hiện động tác không kiểm soát hoặc không hoàn thành cú nhảy.'),
('burpees', 'fa', 'برپی (Burpees)', 'تمرین با شدت بالا که اسکوات، شنا و پرش را ترکیب می‌کند.', 'استقامت قلبی عروقی، قدرت و کالری‌سوزی را بهبود می‌بخشد.', 'از حالت ایستاده، به حالت اسکوات بروید، پاها را به عقب پرتاب کنید، شنا بزنید، پاها را جمع کنید و به بالا بپرید.', 'سرعت ثابتی داشته باشید و هنگام شنا از قوس دادن به کمر خودداری کنید.', 'در صورت مشکلات جدی مفصلی یا قلبی عروقی از انجام آن خودداری کنید.', 'انجام حرکت به صورت کنترل‌نشده یا کامل نکردن پرش.');